[ Bat] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #10
Opened 2021-03-04 10:04 UTC by kjk402

안녕하세요, 웹백엔드과정 Bat입니다.

하기와 같이 미션1 구현하여 pull request 드립니다.

• mission1 summary
=====================================
• 미션1 구현 URL : https://bat-spring-qna.herokuapp.com/

• HTML 중복제거 : HTML 들의 공통적으로 들어가는 중복을 제거하였습니다.
공통사항을 head, navbar, script 세가지로 나누었습니다.

• 회원가입 기능 : 회원가입은 POST 요청을 받으면, 객체를 List users 저장합니다. 

• 회원정보 보기 : userId를 이용하여 GET 요청을 보낼 시 users/{userId}로 정보 확인합니다.

• 회원정보수정기능 : profile에서 수정을 누르면 아이디와 비밀번호 확인 창으로 넘어갑니다. 입력한 정보가 맞다면 수정창으로 넘어가고 틀리다면 다시 확인 창으로 redirect 됩니다.  수정창에서는 이름, 비밀번호, 이메일 수정가능합니다.

• 질문하기, 목록 : 회원가입 기능가 유사하게 POST 방식과 GET방식으로 질문 작성 및 질문을 볼 수 있습니다.

=====================================

• mission1에서 못한 점.
스프링을 처음시작하다보니 상대경로와 절대경로와 많이 헷갈려  경로지정이 난잡합니다. 양해 부탁드립니다.

리뷰 잘 부탁드립니다.
감사합니다.

2021-03-04 12:12 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/Question.java
> +    private String currentTime;
currentTime 같은 값은 스트링으로 변환된 값보다 DateTime 객체로 변환전의 값을 가지고 있는 편이 보통 좋습니다.

2021-03-04 12:16 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/Question.java
> +    public Question(Calendar currentTime) {
https://d2.naver.com/helloworld/645609 읽어보시고 LocalDateTime을 사용해 보면 어때요?

2021-03-04 12:17 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/Question.java
> +    public Question(Calendar currentTime) {
네 알겠습니다. 수정해보겠습니다.

2021-03-04 12:17 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/Question.java
> +        return currentTime;
여기서 String으로 변환해서 리턴하면 될 것 같아요.

2021-03-04 12:32 UTC, honux77 requested changes
무난히 잘 구현하셨네요. 크게 수정할 건 없어보지만 코멘트 보시고 조금 개선해 보세요.

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        question.setId(id);
```suggestion
        question.setId(questions.size() + 1);
```

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        return "redirect:/";
redirect는 왜 쓰는 건지 알고 있나요? 확인 차원에서 물어봅니다.

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/User.java
> +    }
이런거 자동완성되는 toString() 사용해도 괜찮아요.

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("users")
```suggestion
    @PostMapping("/users")
```
다른 것들도 수정 요망

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        return "redirect:/users";
회원 가입 후에 /users 로 리다이렉트하는게 좋은 아이디어일까요? 더 좋은 방안은 없을까요?

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/users/confirmUserInfo")
users URL이기 때문에 뒤에 url은 빼도 될 것 같아요. /users/confim 정도로 어때요?

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("/users/{userId}/update")
보통은 Put /users/{id} 이렇게 하면 업데이트의 의미를 갖습니다. 근데 put을 적용하기가 어려울 수도 있어요. 한번 시도해 보세요.

2021-03-04 12:32 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        System.out.println("user Info: " + user);
ID가 동일한 유저가 생길 것 같은 느낌? 중복사용자에 대한 validation이 필요해 보이는데, 나중에 해도 될 것 같긴 해요.

2021-03-04 12:32 UTC, honux77 commented on src/main/resources/templates/index.html
> +<div id="registerModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
이부분 주석처리 한 것 같은데, 불필요한 주석도 없애는 걸 권장합니다.

2021-03-04 12:45 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        return "redirect:/users";
가입 후에는 "redirect:/" 으로 질문페이지로 바로 넘어가는 것이 좋을 것 같습니다.

2021-03-04 12:47 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        return "redirect:/users";
ad7f136 에서 변경하였습니다.

2021-03-04 12:51 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        System.out.println("user Info: " + user);
오!! 그러네요. ID 는 primary key인데 지금 제 코드는 중복이 발생할 수 있는 구조입니다.
다음 스텝에서 구조 변경해보겠습니다.

2021-03-04 13:03 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        return "redirect:/";
사용자가 요청한 페이지가 아닌 다른 페이지로 넘겨주고 싶을 때 사용하는 기능으로 알고있습니다.

2021-03-04 13:12 UTC, kjk402 commented on src/main/resources/templates/index.html
> +<div id="registerModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
네 주석한 부분 제거하였습니다.

2021-03-04 13:19 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/users/confirmUserInfo")
15e003f 에서 줄여줬습니다. 

감사합니다.

2021-03-04 13:27 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("users")
수정하였습니다. ~~

2021-03-04 13:30 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/User.java
> +    }
3565744 에서 사용해보았습니다.
toString을 자동완성기능을 많이 써보질 않아서 습관처럼 전부 입력하게되는 것 같습니다. ㅎㅎ
호눅스 좋은 의견 감사합니다. 앞으로 자주 사용하겠습니다. ^^

2021-03-04 15:13 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        question.setId(id);
d9db1da 에서 말씀하신 것과 같이 수정하였습니다.

2021-03-04 15:20 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/Question.java
> +        return currentTime;
d9db1da 에서 LocalDateTime 사용하게 변경하였습니다. 

'처음부터 String으로 받는다면 값을 다르게 사용해야할 때 변환이 복잡해져 원래 값을 가지고 있는 LocalDateTime을 사용해야 한다. '
라고 이해하였습니다. 

혹시 잘못 이해했다면, 지적해주심 감사하겠습니다.

2021-03-04 15:21 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/Question.java
> +    private String currentTime;
d9db1da 에서 LocalDateTime 사용하게 변경하였습니다.

감사합니다.

2021-03-04 17:21 UTC, kjk402 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("/users/{userId}/update")
6b97ca8 에서 put 적용하였습니다.

WebApplicationInitializer 으로 삽질하느라 조금 오래걸리긴 했지만 
새로운 기술 사용해서 신기합니다. ^^

감사합니다.~~

2021-03-08 04:05 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/Question.java
> +        return currentTime;
보통 데이터를 저장할 때는 원본을 저장하고 보여줄 때 포맷만 바꿔서 보여주는게 일반적입니다.

2021-03-08 04:06 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        return "redirect:/users";
이거 보니까 요구사항이 리스트를 보는 거였네요 ㅋㅋㅋㅋ.  그래도 질문페이지가 더 자연스럽죠 ㅎㅎ

2021-03-08 04:07 UTC, honux77 commented
수고하셨어요. 늦어서 죄송합니다 ㅜㅜ

2021-03-08 04:07 UTC, merged