[Jung] 미션 3 PR입니다
codesquad-members-2021/spring-boot-qna pull request #101
Opened 2021-03-21 10:47 UTC by rla36

안녕하세요 Jung입니다.
미션3PR을 목요일에 보내는 것이 목표였는데, 마지막 실습인 답변 기능에서 막혀 이제야 PR드립니다.
(아직도 Answer기능 구현은 못했으나, 빨리 넘어가고 다시 돌아오는 것을 목표로 하고 있습니다.
혹시 show.html에서 답변하기 버튼 클릭시 questions/{questionId}/answers url로 넘어가지 않는 이유가
눈에 보이신다면 말씀해주시면 감사하겠습니다..)

리뷰해주셔서 감사합니다!

2021-03-22 03:50 UTC, ksundong requested changes
안녕하세요! Jung!! 리뷰어 Dion입니다!
3단계 미션을 진행해주시느라 고생하셨습니다.
먼저 이번 PR은 **변경 요청**을 드리게 되었습니다.

## 애플리케이션 관련 피드백

- 애플리케이션에 회원가입을 할 수 없었습니다. 확인 부탁드릴게요.

## 코드 관련 피드백

- 빈 라인도 코드입니다. 앞으로는 조금 더 신중하게 사용해주세요. 빈 라인의 의미는, 위의 내용과 아래의 내용이 의미상 구분된다는 의미입니다.
- 조금 더 객체의 자립도를 높여주세요. 객체에게 메시지를 전달해서, 객체가 알아서 일을 수행하도록 해줘야합니다.
- 정렬을 습관화 해줍시다.

보다 자세한 내용은 아래의 코멘트를 참고해주세요~
궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으시다면 코멘트 남겨주세요.
고생하셨습니다~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    }
👍 
Exception Handler의 사용 좋습니다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +
빈 라인이 많이 들어갔네요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +    private QuestionService questionService;
`final`을 붙여주세요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +    public String addAnswer(@PathVariable Long questionId, HttpSession session, String contents) {
저는 `add`로도 충분하다고 생각해요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        answerService.save(new Answer(question, writer, contents));
answerService에서 question을 찾고 추가하는 형태로 구현해보면 어떨까요?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private AnswerService answerService;
answerService가 왜 필요해졌을까요?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +
빈 줄의 사용에 신중해주세요~
빈 줄도 코드입니다. 의미를 구분지어주어야 할 때만 사용해주세요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String clickUpdateQuestion(@PathVariable Long id, Model model, HttpSession session) {
`click` 같은 동작은 이벤트입니다. 저희가 작성하는건 이벤트 핸들러는 아니기 때문에 굳이 `click`이 나올 필요는 없다고 생각해요.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        SessionUtility.verifySessionUser(sessionedUser, writer, "본인이 작성한 글만 수정할 수 있습니다.");
Controller가 해야할 일은 무엇이고, Service가 해야할 일은 무엇일까요? 한 번 공부해보세요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +    public String addAnswer(@PathVariable Long questionId, HttpSession session, String contents) {
생각해보니까 addAnswer도 좋은 것 같네요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        question.updateQuestion(title, contents);
요기는 update로 충분하겠죠?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        SessionUtility.verifySessionUser(sessionedUser, writer, "본인이 작성한 글만 삭제할 수 있습니다.");
String은 상수로 빼봅시다~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +            throw new UserException("비밀번호가 틀렸습니다.");
`UserException`이 너무 다양한 예외를 포함할 것 같지 않나요?
다른 예외명을 고민해봅시다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        user.update(newInfoUser);
엇 여기는 `update`네요 ㅎㅎ

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        if(user == null) {
정렬을 습관화해봅시다~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        }
이건 사용자 경험과 관련된 건데요. 너무 예외는 자세히 사용자에게 전달될 필요는 없습니다.
로그에만 남는다면 괜찮다고 생각되고요, 문자열만 추출해봅시다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.setAttribute("sessionedUser", user);
SessionUtility에 추출해주면 어떨까요?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @GetMapping("/logout")
logout은 GET, POST 둘 중에 어떤 것을 써야할까요?
한 번 검색해보시고, Jung만의 답을 내려보세요.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @Column
이 애노테이션을 꼭 붙여줘야할까요~?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    protected Answer() {}
👍

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        this.writtenDateTime = LocalDateTime.now();
저같은 경우에는 작성 시간은 항상 그 시간이 되도록 필드에 지정해줍니다.
이러면 여러개의 생성자가 생겼을 때, 편해요.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        return writtenDateTime.format(QuestionUtility.DATE_PATTERN);
사실 Utility에는 method들만 사용할 수 있도록 하고, 상수를 모아두는 클래스는 Constants로 지정하는 것이 관례입니다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    }
setter 안 만들어주시고 잘 작성하셨어요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
>      }
Answer 코드와 포매팅한 유형이 다르네요

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    public void updateQuestion(String title, String contents) {
`update`여도 충분할 것 같습니다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/repository/AnswerRepository.java
> +    public List<Answer> findByQuestionId(Long questionId);
음... 이 메서드가 필요한 이유는 무엇인가요?

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/repository/UserRepository.java
> +    User findByUserId(String userId);
반드시 해당 User가 리턴될까요? 잘 생각해보세요~

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/LoginException.java
> +public class LoginException extends RuntimeException{
Custom 예외를 RuntimeException으로 정의해주셔서 드리는 질문
`CheckedException`과 `UnchekcedException`에 대해서 알고 계신가요?
모르신다면 한 번 학습해봅시다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
이렇게 구현하는 것도 좋은 것 같아요 ㅎㅎ

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
하지만 Answer를 반환하는 식의 구현도 할 수 있음은 알아두세요!

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
user에게 물어보는 식으로 작성해봅시다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
`getter`로 꺼내서 비교하는 방법은 전혀 '객체지향'적이지 않습니다!

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    private SessionUtility() { }
private 기본생성자 좋습니다. 근데 여기도 포맷 유형이 다르네요.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +            throw new LoginException("로그인해주십시오.");
LoginException이 의미하는 바는 Login을 하라는 의미인가요? 그럼 보다 명확한 UnAuthenticated를 사용하는 것을 권해봅니다.

2021-03-22 03:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +        if (sessionedUser.getId() != user.getId()) {
객체에게 물어보는 식으로 바꿔보세요~

2021-03-22 15:23 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +    private QuestionService questionService;
넵! 수정했습니다. QuestionController에서도 final 이 빠져있어 마찬가지로 수정해줬습니다!

2021-03-22 15:27 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +    public String addAnswer(@PathVariable Long questionId, HttpSession session, String contents) {
url은 중복 없도록(RESTful하도록) add, delete 등을 쓰지 않았는데, 
메소드명은 제가 헷갈려서 자세히 적었습니다 
QuestionController에서 add가 있는데, 어떤 걸 add 하는 건지는 메소드가 위치한 파일을 확인하면 되는 일이지만 메소드명만으로 알수있도록 한번 이렇게 해봤습니당!

2021-03-22 16:09 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        answerService.save(new Answer(question, writer, contents));
컨트롤러에 저렇게 잡다하게 로직이 들어가면 안된다고 생각했는데, 정말 Service로 빼내는게 좋을 것 같습니다 QuestionController, UserController도 비슷하게 복잡한 로직은 전부 Service단에서 처리하도록 수정하겠습니다. 다만 어디까지가 Controller에 있어도 될정도의 로직이고, 어디서부터 너무 복잡한지 판단하기가 어렵네용.. 예외처리가 들어가면 일단 Service로 빼내도록하겠습니다!!

AnswerService 안에 
1) QuestionRepository를 넣을지, 아니면
2) QuestionService에 id로 question을 찾아내는 메소드가 존재하므로, 이것을 재사용하기 위해 AnswerSerivce안에 QuestionService를 넣을지 고민했습니다.
[Service가 다른 Service를 호출해도 되는지?](https://softwareengineering.stackexchange.com/questions/230983/is-it-ok-for-services-to-reference-one-another)
이 글을 참고해 AnswerService 내에 QuestionService를 집어넣어 findById메서드를 재사용하기로 했습니다!

2021-03-22 16:18 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private AnswerService answerService;
1) AnswerController의 addAnswer메소드에서는 댓글을 AnswerRepository에 저장하도록만 하고, 
return "redirect:/questions/" + questionId; 로 해당 질문으로 redirect 하게 했습니다.
2) 리다이렉트 되어서 찾아간(?) QuestionController의 @GetMapping("questions/{id}") showQuestion메소드에서는 
**해당 질문에 달린 모든 댓글을 찾아내** answers란 이름으로 모델에 담아 해당 질문의 html인 show.html을 리턴하도록 했습니다. 

해당 질문에 달린 모든 댓글을 찾는 메소드가 answerService내에 있기 떄문에 이 메소드를 사용하기 위해서 QuestionController에  answerService가 들어갔습니다.

 차라리 QuestionService에 해당 질문에 달린 모든 댓글을 찾아내는 메소드를 넣는 것이 나을까요?

2021-03-22 16:19 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +
넵 유념하겠습니다 ㅜㅜ

2021-03-22 16:21 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String clickUpdateQuestion(@PathVariable Long id, Model model, HttpSession session) {
showUpdateForm으로 수정했습니다!

2021-03-22 22:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        answerService.save(new Answer(question, writer, contents));
컨트롤러가 하는 역할은 화면을 출력하고, 데이터를 연결해주는 정도의 역할만 수행하면 됩니다.
그 이외의 것은 서비스에게 위임해주면 될 것 같아요.
좋은 고민을 하신 것 같아요. 👍

2021-03-22 22:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private AnswerService answerService;
넵 그 편이 좋을 것 같아요.

2021-03-23 02:40 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        SessionUtility.verifySessionUser(sessionedUser, writer, "본인이 작성한 글만 수정할 수 있습니다.");
Service의 역할은 도메인의 데이터를 가공해서 컨트롤러에 전달하는 것이라고 알고 있습니다
예외를 발생시키는 부분, 글쓴이와 로그인사용자를 비교하는 부분을 Service로 빼냈고
 getter을 쓰지 않도록 수정했습니다!

2021-03-23 02:41 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        question.updateQuestion(title, contents);
넵 앞에 question이라고 객체가 드러나니 메소드명은 update로 충분할것같습니다
69번째 줄의 매핑메소드는 updateQuestion으로 그대로 두겠습니다!

2021-03-23 02:45 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        SessionUtility.verifySessionUser(sessionedUser, writer, "본인이 작성한 글만 삭제할 수 있습니다.");
요 부분은 위에서 컨트롤러의 역할에 해당하지 않는 부분 service로 추출해내면서 삭제되었습니다!
그래도 앞으로 변경가능성이 있거나 반복 사용될 스트링이 있다면 용이한 유지보수를 위해 상수로 빼내는 습관 들이겠습니다

2021-03-23 02:52 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +            throw new UserException("비밀번호가 틀렸습니다.");
다른 사용자의 글/댓글을 수정/삭제하려는 경우에 발생하는 예외를 포함시키고 싶었습니다
InvalidUserException으로 수정해보았습니다..!

2021-03-23 02:54 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        user.update(newInfoUser);
앗 네... 일관성이 없네여 Question클래스의 updateQuestion메소드는 update로 리네이밍했습니다

2021-03-23 02:55 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        if(user == null) {
if랑 for 다음에 띄어쓰기하는걸 계속 까먹네요 기억하겟습니다!

2021-03-23 03:09 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        }
사용자가 발생시킨 예외이기 때문에 원인을 자세히 알려주면 예외를 피해갈 수 있을 것이라고 생각해서 이렇게 적었는데요 (사실 제가 로그인 실패할때 id때문인지 비번 때문인지 안알려주면 짜증나니까...ㅋㅋㅋ) 
보안문제도 있을 것 같네요!!

에러메세지  "id 또는 비밀번호가 틀렸습니다."는 LoginException클래스 내에 private static final 변수로 정의해두었습니다.
LoginException는 로그인 실패시에 발생하는 예외이기 때문에 에러메세지도 항상 이 메세지일것으로 생각해서 매개변수 없는 LoginException생성자를 만들고, 이 생성자를 사용할 시에 에러메세지가 자동으로 "id 또는 비밀번호가 틀렸습니다."가 되도록 수정했습니다.

2021-03-23 03:15 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.setAttribute("sessionedUser", user);
넵 HttpSession을 쓰지 않는 데이터 처리 부분은 Service로 빼내도록해야겠어요! 수정했습니다

2021-03-23 05:32 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.setAttribute("sessionedUser", user);
"sessionedUser"을 public static final String으로 SessionUtility에 추출했습니다 제가 이해한게 맞겠죠??

2021-03-23 05:47 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @GetMapping("/logout")
https://stackoverflow.com/questions/3521290/logout-get-or-post
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.1
GET and HEAD methods SHOULD NOT have the significance of taking an action other than retrieval.

get은 있던 것을 가져오는 역할만을 수행해야하는데, 로그아웃은 session에 저장된 것을 삭제하므로 post로 수정하도록하겠습니다!

2021-03-23 06:19 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @GetMapping("/logout")
html의 <a> tag가 post를 지원하지 않기 때문에 <form>을 사용해야합니다. 
그런데 주변의 서식과 어울리게 form submit버튼을 만드는 방법을 모르겠어서 일단 get으로 두겠습니다 ..
form에 button으로 로그아웃하도록 만들었더니 초록색 버튼이 너무 흉해서요ㅜ
get과 post를 언제사용해야하는지 배운것으로 만족하겠습니다!

2021-03-23 06:31 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @Column
@Column 애노테이션은 name, nullable, length, unique를 설정할때 사용하는 것이고 
따로 설정하지 않는다면 @Column을 사용하지 않아도 entity에 매핑된다는 말씀이신가요??

2021-03-23 06:37 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        this.writtenDateTime = LocalDateTime.now();
모종의 이유로 이미 작성되었던 question/answer의 생성자가 또 쓰이는 경우 
원래의 작성시간을 유지하도록 
말씀해주신대로 answer, question모두  수정했습니다!!

2021-03-23 06:39 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        return writtenDateTime.format(QuestionUtility.DATE_PATTERN);
원래 QuestionUtility에서 포맷된 형식의 localDateTime을 리턴하는 메서드를 만들려했는데, 계획대로 하지 않고 상수만 정의하게 됐네요.
어차피 answer에서도 포맷된 time이 필요하니까, TimeConstants 클래스를 만들겠습니다!

2021-03-23 06:44 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    public void updateQuestion(String title, String contents) {
넵 question클래스에 있으니 메소드명을 update만으로해도 충분히 기능이 드러날것같습니다! 위에서 지적해주셔서 수정했습니당

2021-03-23 06:48 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/repository/AnswerRepository.java
> +    public List<Answer> findByQuestionId(Long questionId);
question id에 해당하는 모든 answer들을 리턴하도록 정의한 것입니다 미션4 답변달기 진행하면서 수정해나가도록하겠습니다..!

2021-03-23 06:52 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/repository/UserRepository.java
> +    User findByUserId(String userId);
해당하는 user이 없을 경우 null이 리턴될수도있겠네요 optional로 바꾸는 것이 좋겠습니다! 수정했습니다

2021-03-23 06:53 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/exception/LoginException.java
> +public class LoginException extends RuntimeException{
넵 게시판을 사용하는 쪽에서 발생시키는 exception이기 떄문에 RuntimeException으로 했습니다!

2021-03-23 06:55 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
넵 answer을 리턴하도록 하면 쓰임새가 더 다양해질 것 같습니다!

2021-03-23 07:04 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
넵!! 필요한 메소드를 새롭게 정의하고 수정했습니다

2021-03-23 07:20 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +            throw new LoginException("로그인해주십시오.");
로그인하지 않았거나 로그인에 실패했을때 예외가 발생합니다 
예외의 의미가 더 명확히 드러나도록 이름지어야겠군요 수정하겠습니다!

2021-03-23 07:22 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +        if (sessionedUser.getId() != user.getId()) {
넵!

2021-03-23 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        }
네 사용자의 편의만 신경쓰면, 보안이 취약해지는 포인트가 생깁니다. 잘 캐치하셨네요~

2021-03-23 11:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.setAttribute("sessionedUser", user);
`SessionUtility.setUser(user);`

```java
public static void setUser(User user) {
    session.setAttribute(SESSION_USER, user);
}
```

와 같은 식이면 좋을 것 같네요~

2021-03-23 11:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @GetMapping("/logout")
태그 쓰시면 ㅋㅋ 안보입니다.
일단은 알아만 두고 넘어가시죠~

2021-03-23 11:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @Column
한 번 해보세요~

2021-03-23 11:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/repository/AnswerRepository.java
> +    public List<Answer> findByQuestionId(Long questionId);
JPA를 이용하면 굳이 이런 메서드를 정의해주지 않아도 될텐데요!

2021-03-23 12:30 UTC, ksundong requested changes
안녕하세요! Jung 리뷰어 Dion입니다!!
피드백 반영해주시느라 고생하셨습니다!

## 웹 애플리케이션 관련 리뷰

- 헤로쿠가 안들어가지네요. 😱

## 코드 관련 리뷰

- 대부분 깔끔해진 것 같고, 아래에 세부적인 피드백을 보시고 고쳐보시고 싶은 부분은 바로 고쳐보시면 될 것 같아요.

궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으면 코멘트 남겨주세요.
고생하셨습니다~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        User writer = SessionUtility.findSessionedUser(session);
요거는 필요없지 않을까요?

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
```suggestion
        User sessionedUser = SessionUtility.findSessionedUser(session);
        
        questionService.verifyQuestionWriter(question, sessionedUser);
```
요기는 떼어주는게 좋을 것 같아요~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.save(question);
questionService.update로 줄여볼 수 있을 것 같네요~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.save(question);
여기는 verify해주지 않아도 괜찮나요?

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
verify는 중복이 되니, 중복을 제거해봅시다. 서비스 내부에서 호출하는건 어떨까요?

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.removeAttribute(SessionUtility.SESSIONED_USER);
요것도 SessionUtil에 넘겨줄 수 있을거에요~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    protected Question() { }
어디는 중괄호 사이에 공백이 있고, 어디는 없는데 신경 써주세요!!

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    public boolean hasSamePassword(User user) {
👍

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    private QuestionService questionService;
여기는 final이 빠져있네요~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    public void delete(Question question) { questionRepository.delete(question); }
```suggestion
    public void delete(Question question) {
        questionRepository.delete(question);
    }
```

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +                .orElseThrow(() -> new QuestionNotFoundException("찾으시는 질문이 존재하지 않습니다."));
문자열은 예외 내부에서 관리하도록 해보세요~

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    }
요 메서드는 SessionUtiliy에 있을 필요가 있을까요?

2021-03-23 12:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/TimeConstant.java
>              = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
한 줄로 써주면 어떨까요?

2021-03-23 15:05 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.setAttribute("sessionedUser", user);
아 83번줄 전체를 메서드로 추출하라는 말씀이셨군요 알겠습니다!!

2021-03-24 01:30 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/repository/AnswerRepository.java
> +    public List<Answer> findByQuestionId(Long questionId);
프라이머리 키가 아닌 값으로 찾을떄만 메서드를 지원해주는 줄 알았어요ㅜ 수정해보겠습니다!

2021-03-24 01:47 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        User writer = SessionUtility.findSessionedUser(session);
로그인되지 않은 사용자가 글을 쓰려하면 로그인 페이지로 이동시키기 위해 필요합니다..!!
findSessionedUser해서 sessionedUser가 없으면 예외가 발생하는 방식의 메소드인데 이걸 잘 드러낼 수 있도록 어떻게 수정할지 고민해보겠습니다

2021-03-24 02:02 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.save(question);
service로 추출했습니다!

위에 
@GetMapping("{id}/update")
    public String showUpdateForm
에서 수정페이지로 이동할 때 글작성자가 아니면 수정form을 못보도록했기 떄문에 verify는 생략했습니다

2021-03-24 02:13 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
서비스는 도메인의 데이터를 관리하는 역할을 담당하기 때문에 HttpSession를 다루지 않는 것이 좋다고 어딘가에서 본 기억이 나서 verify메소드를 서비스에 따로 추출하지 않고 있었습니다ㅜㅜ
verify 메소드는 세션에 저장된(로그인된) 사용자와 수정/삭제하려는 글/댓글의 작성자를 비교하는데 이걸 QuestionService에 넣어버리면 메소드 매개변수로 HttpSession 를 넣어야하지 않나요..?

2021-03-24 02:15 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        session.removeAttribute(SessionUtility.SESSIONED_USER);
넵!!

2021-03-24 02:43 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    protected Question() { }
넵 공백없는 것으로 통일했습니다!

2021-03-24 02:46 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    private QuestionService questionService;
넵!!

2021-03-24 02:50 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    public void delete(Question question) { questionRepository.delete(question); }
통일성에 신경쓰겠습니다!

2021-03-24 02:52 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    }
세션을 쓰지도 않으니 UserService에 있는것이 더 적절해보입니다..!

2021-03-24 02:57 UTC, rla36 commented
https://jung-spring-boot-qna.herokuapp.com/
ㄴ요기로 접속해보세요..! 저는 프로그램에 문제가 발견되어서 수정하고 있겠습니다

2021-03-24 11:08 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        User writer = SessionUtility.findSessionedUser(session);
그러면 메서드를 따로 만들어주는 편이 좋을 것 같아요!

2021-03-24 11:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.save(question);
흠 과연 괜찮을까요~?
사용자는 Jung이 생각하는 만큼 행동하지 않습니다.
특히 백엔드 개발자는 사용자가 내 생각대로 행동하지 않을거라고 생각하고 개발하시는게 좋아요.

2021-03-24 11:13 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
뭔가 잘못 이해하신 것 같은데요~
메서드로 호출해주면 다루지 않는걸까요?
다시 한 번 천천히 생각해보시면 답을 찾으실 수 있을 것 같네요~

2021-03-24 11:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    }
User에 있는게 더 적절하겠죠? ㅎㅎ

2021-03-24 11:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
그리고 question에게 물어보는 방향도 생각해보세요~

2021-03-24 11:18 UTC, ksundong commented
@rla36 
헷갈리시는 부분에 대해서 답변 달았으니, 확인부탁드리고 다 변경되셨다면, 리뷰요청 해주세요!

2021-03-26 01:33 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.save(question);
넵 로그인 사용자 검증하는 과정 추가하겠습니다!

2021-03-26 04:52 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    }
앗 그렇군요...ㅎㅎ 아직 도메인과 서비스의 역할분리가 헷갈리는 것 같습니다 ㅜ도메인에서  예외를 throw하는 메소드를 가져도 좋을지 (도메인 자체의 속성과 관련됐다기 보다는 예외가 발생하기 때문에 컨트롤러와 도메인의 중간에 가까운 것 같아서) 확신이 서지 않아서 서비스에 넣었는데 수정하겠습니다!

2021-03-26 06:25 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
`    public Question verifyQuestionWriter(Long id, User user) {
        Question question = findById(id);
        if (!question.isWriter(user)) {
            throw new UnauthorizedUserException(UnauthorizedUserException.UNAUTHORIZED_USER_TO_QUESTION);
        }
        return question;
    }`
와 같이 수정했습니다.

id로 question을 찾은 후에 
메소드의 파라미터로 전달된 user가 글쓴이와 일치하는지 question에게  묻고,
일치하지 않는 경우에 수정/삭제 권한이 없다는 예외를 발생시키도록 했습니다.
만약 예외가 발생하지 않고 질문글쓴이와 로그인사용자가 일치한다면 question을 리턴하도록 했습니다.

> 메서드로 호출해주면 다루지 않는걸까요?
메소드로 호출해주면 다룬다는 말씀으로 이해했습니다. 그렇기 때문에 서비스에 포함된 메소드의 파라미터로 HttpSession을 받으면 안되고, session을 사용해 로그인사용자를 받는부분까지는 컨트롤러에 남겨뒀습니다..

제가 제대로 이해한 것이 맞는지 모르겠으나 일단.. 이렇게 수정했습니다..!

2021-03-26 07:36 UTC, rla36 commented
@ksundong 
[배포url](https://jung-spring-boot-qna.herokuapp.com/questions)
디온 이게 30분에 한번씩 접속하지 않으면 다시 빌드해야해서 좀 기다리셔야한대요...!
다른 팀원분들께 열어봐달라고 부탁드렸는데, 조금(오래) 기다리니 제대로 접속된다고 하시더라고요..!!
죄송하지만 한번만 더 열어봐주시길 부탁드립니다!!!

마지막 커밋에서는 Question컨트롤러에서의 역할을
HttpSession으로 로그인User을 찾고, 모델에 question을 담는 것으로 제한시키고
나머지는 모든 서비스의 역할로 넘겨버렸습니다. 
QuestionController의 deleteQuestion(69번째 라인)에서 지적해주신것이 이런 식으로 수정하라는  말씀이셨나여??

그리고 도메인에서 예외를 throw하는 만큼의 비즈니스 로직과 관련된 메소드를 가져도되는지 궁금합니다..!

2021-03-27 06:13 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        questionService.verifyQuestionWriter(question, sessionedUser);
네 제가 의도했던 방향과 유사하게 코드를 작성해주신 것 같아요.
그리고 제가 한 말씀을 잘 이해하셨네요. 👍

2021-03-27 06:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +    }
이 부분은 Jung이 선택하기 나름입니다.
이는 도메인이 정말 도메인 자체만 가지는 순수한 도메인이냐, 아니면 비즈니스 로직을 포함하는 풍성한 도메인이냐의 차이기도 하고요.
저는 개인적으로 도메인에게 어느정도 책임을 주는 것이 좋다고 생각합니다. 이게 좀 더 객체지향적이지 않을까? 하는 생각이에요.

2021-03-27 07:46 UTC, ksundong approved these changes
넵! 이번엔 잘 접속되네요!
한 가지 또 생각해봐야 할 점은
Controller, Service, Repository, Entity가 가지는 각각의 역할과 책임이 있을 것인데요.
이 기준을 반드시 정하고 코딩을 해주시는 것이 좋습니다.
여러 글을 읽으시면서 기준이 잘 정해지셨으면 좋겠습니다.

마지막 질문은 해당 코멘트에 답변해두었으니 참고해주세요!

## 웹 애플리케이션 리뷰

- 중복되는 아이디로 가입이되네요.
- 아이디가 수정이 가능하네요.
- 비밀번호 확인 기능이 없네요.
- 게시글 조회화면에서 목록으로 갈 수 없네요.

## 코드 관련 리뷰

- Serivce에 모든 책임을 다 넘겨주지는 마세요!
- 네이밍은 항상 신경써줍시다!

사실 이번 단계 요구사항이 지켜지지 않았으나, 다음 단계를 진행하시면서 고쳐주시면 좋을 것 같습니다.
고생하셨습니다~

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    }
이 부분을 제외한 나머지는 동작이 동일하니 공통 예외 처리도 구현하는 편이 좋을 것 같아요.

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        User writer = SessionUtility.findSessionedUser(session);
이 부분은 다음 단계에서 고민해봅시다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String saveQuestionForm(String title, String contents, HttpSession session) {
question form을 저장한다는 의미보다는
question을 만드는 느낌으로 작성하면 더 좋을 것 같아요!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    @GetMapping("{id}/update")
어디는 form이고 어디는 update인데
저는 form으로 통일시키는게 좋을 것 같아요.

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionService.verifyQuestionWriter(id, sessionedUser);
훨씬 좋아졌네요! 👍

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionService.verifyQuestionWriter(id, sessionedUser);
question을 가져와서, question에게 writer를 묻는 편이 좋을 것 같은데요!
지금은 메서드명이 뭔가 이질적입니다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionService.verifyQuestionWriter(id, sessionedUser);
그렇게 되면, controller는 정말 최소한의 정보만 알게 되겠죠?

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        user.verifySessionUser(sessionedUser, "본인의 회원정보만 수정할 수 있습니다.");
문자열은 상수화하고, 여기서는 해당 문자열을 몰라도 되도록 바꿔봅시다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +            throw new UnauthorizedUserException(UnauthorizedUserException.WRONG_PASSWORD);
너무 길어지면 static import도 고려해보세요!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +            throw new UnauthorizedUserException(UnauthorizedUserException.WRONG_PASSWORD);
그리고, userService에 자꾸 책임을 넘기기 보다는 user가 직접 수행할 수 있는 일은 user가 수행해주도록 합시다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    protected Question() {}
이거 왜 이렇게 생성자를 만들어줘야 하는지 알고계시죠~?
알고 계신다면 넘어갑시다! 아니라면 한 번 공부해봅시다~

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +
앗 갑자기 빈 라인이 추가되었네요.

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
왜 equals hashCode를 할 때, id를 가지고 했는지 고민해보시면 좋아요~

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QuestionNotFoundException.java
> +    public static String QUESTION_NOT_FOUND_MSG = "찾으시는 질문이 존재하지 않습니다.";
```suggestion
    public static final String QUESTION_NOT_FOUND_MSG = "찾으시는 질문이 존재하지 않습니다.";
```
조심합시다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/UnAuthenticatedLoginException.java
> +public class UnAuthenticatedLoginException extends RuntimeException{
```suggestion
public class UnAuthenticatedLoginException extends RuntimeException {
```

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/UnauthorizedUserException.java
> +    public static final String WRONG_PASSWORD = "비밀번호가 틀렸습니다.";
이 메시지는 안주는게 좋을 것 같은데요!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    private AnswerRepository answerRepository;
```suggestion
    private final AnswerRepository answerRepository;
```

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +        save(new Answer(question, writer, contents));
음 `save`는 따로 추출해주지 않아도 좋을 것 같습니다!

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +                .orElseThrow(() -> new QuestionNotFoundException());
```suggestion
                .orElseThrow(QuestionNotFoundException::new);
```
자바의 람다는 메서드 오퍼레이터를 지원합니다.

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
굳이 service를 거칠 필요가 있을까요?

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        return user;
```suggestion
        try {
            User user = findByUserId(userId);
            user.verifyPassword(password);
            return user;
        } catch(RuntimeException e) {
            throw new UnAuthenticatedLoginException(UnAuthenticatedLoginException.WRONG_ID_OR_PASSWORD);
        }
```

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +        Object value = session.getAttribute(SESSIONED_USER);
value 보다는 좋은 이름으로 바꾸어봅시다.

2021-03-27 07:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +//    }
안쓰는 코드는 그 때 그 때 제거해줍시다!

2021-03-27 07:46 UTC, merged

2021-03-29 05:34 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    }
넵 알겠습니다!

2021-03-29 05:42 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String saveQuestionForm(String title, String contents, HttpSession session) {
update, delete 메소드들을 따라 saveQuestion으로 수정하겠습니다!

2021-03-29 05:46 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    @GetMapping("{id}/update")
넵 url 이름이 비슷하면 헷갈릴것같아 차이를 줬는데 
어차피 메소드로 다 차이가 나니까 그것으로 구분하고 통일성을 주는게 좋을수있겠단 생각이 들었어여!

2021-03-29 05:50 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/SessionUtility.java
> +        Object value = session.getAttribute(SESSIONED_USER);
로그인되어있을수도있고, 아닐수도있으니까 potentialLoginUser로 바꿔봤습니다

2021-03-29 06:14 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/exception/UnauthorizedUserException.java
> +    public static final String WRONG_PASSWORD = "비밀번호가 틀렸습니다.";
회원정보 수정할 때 비밀번호가 틀려서 회원정보 수정에 실패하는 경우는 
비밀번호 오류로 수정불가하다는 메세지를 줘야한다고 생각했습니다..!

2021-03-29 06:35 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +                .orElseThrow(() -> new QuestionNotFoundException());
넵 공부해보겠습니다!

2021-03-29 06:40 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
이미 User에 있는 메소드인데 또 만들었네요.. 수정하겠습니다!!