[yeon] 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #102
Opened 2021-03-21 11:04 UTC by kimnayeon0108

안녕하세요! yeon입니다.
미션 4구현 완료 하고 코드리뷰 요청드립니다. 질문과 답변을 삭제하는 기능까지 구현했고, 요구사항대로 DB데이터를 실제로 삭제하지 않고 soft delete 방식으로 구현했습니다.

로직상 크게 변경된 부분과 새롭게 알게된 부분에 대해 말씀드리면, 

repository(DAO)를 통해 DB에 접근하는 코드와 비즈니스로직을 컨트롤러에서 service 클래스로 옮겼습니다. 컨트롤러에서는 최대한 service를 통해서 일을 처리하도록 구현해보았는데 올바르게 한건지 잘 모르겠습니다..

@Where 어노테이션을 사용해서 엔티티 객체를 필터링할 수 있다는 것을 알게되었습니다. 
엔티티 클래스에 @Where(clause = "deleted = false")를 붙이고 findAll()하면 deleted 값이 false인것만 가져온다는 것을 알게되어서 사용해보았습니다.

2021-03-22 00:37 UTC, wheejuni commented
@kimnayeon0108 (리뷰가 아니라서 죄송합니다) 피알 메세지 안에 at 기호(@) 가 있으면, 유저가 태그됩니다 ㅋㅋ where 님이 태그되셔서 제가 코드 블록으로 감쌌습니다. 

앞으로 애노테이션을 표현하실 땐 `` 를 사용하셔서 코드 블록으로 감싸주세요!

`@Where`, `@kimnayeon0108` 이런 식으로요. 그러면 태그되지 않습니다.

2021-03-22 02:42 UTC, kimnayeon0108 commented
> @kimnayeon0108 (리뷰가 아니라서 죄송합니다) 피알 메세지 안에 at 기호(@) 가 있으면, 유저가 태그됩니다 ㅋㅋ where 님이 태그되셔서 제가 코드 블록으로 감쌌습니다.
> 
> 앞으로 애노테이션을 표현하실 땐 `` 를 사용하셔서 코드 블록으로 감싸주세요!
> 
> `@Where`, `@kimnayeon0108` 이런 식으로요. 그러면 태그되지 않습니다.

세상에 ㅋㅋㅋㅋㅋㅋㅋㅋ 감사합니다ㅠㅠ 앞으로 꼭 코드블럭으로 감싸야겠군요..

2021-03-22 12:51 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
좋은 구조를 갖고 잘 구현해주신 것으로 생각됩니다. 💯 
곳곳에서 간단히 수정될만한 것들, 궁금한 것 모아서 피드백을 남겨 보았습니다. 참고해주세요~

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @GeneratedValue
`strategy` 는요? 부여하지 않는다면, 기본값은 무엇일까요?
그리고 각 `strategy` 가 갖는 성능상의 차이는 어떨까요?

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Id
요 세 줄에는 각각 한 줄씩의 줄비움이 필요할 것 같네요.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return answers.size() == 0;
이럴때 사용할 수 있는 [이런 메소드](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#isEmpty--) 가 있습니다.

```suggestion
        return answers.isEmpty();

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return true;
헉, 이 로직은 언제 사용되는 거죠?
모든 답변을 순회하며 글쓴이 일치 여부를 체크하는 것 같은데, 구현됐어야 할 이유가 궁금해요.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setDeletedTrue() {
`public void delete()` 정도로 충분하지 않을까 싶습니다.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
`AnswerService` 에서 질문도 찾아주는군요.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    private final QuestionRepository questionRepository;
`AnswerService` 에서 `QuestionRepository` 도 주입받네요.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return userRepository.findByUserId(userId).orElseThrow(() -> new NotFoundException("해당 유저가 존재하지 않습니다."));
문자열이 길어져서 줄이 넘어갈 경우엔, 적절히 강제 개행을 해 주세요.
지금같은 경우엔 `.orElseThrow(` 앞에서 엔터를 한번 쳐 주시면 완벽할 것 같아요.

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
바로 예외를 던지는 것보단 `boolean` 타입을 리턴해서, 소비하는 쪽에서 다음 로직을 결정하게 해 주면,
조금 더 유연한 구현이 가능하지 않을까요? (이건 취향 문제라서 연이 생각하시는 대로 하셔도 상관없습니다.)

2021-03-22 12:51 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +    private HttpSessionUtils() {}
👍

2021-03-22 17:01 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @GeneratedValue
@wheejuni IDENTITY 전략으로 생성하도록 추가했습니다! 
학습을 해보았는데 데이터베이스에 대한 개념이 빈약해서 완벽히 이해하지는 못했습니다 ([학습링크](https://gmlwjd9405.github.io/2019/08/12/primary-key-mapping.html)) 데이터베이스 학습을 하루빨리 해야겠다는 생각이 이번 프로젝트하면서 계속 드는데 얼른 실행으로 옮겨야겠네요😖

기본값은 AUTO이고, 이경우에는 JPA 구현체가 자동으로 세가지 생성 전략중 하나를 결정합니다. 

IDENTITY 전략은 기본키 생성을 DB에 위임합니다. id값을 null로 하면 DB가 알아서 AUTO_INCREMENT를 해줍니다.

SEQUENCE 전략은 데이터베이스의 유일한 값을 순서대로 생성하는 특별한 데이터베이스 오브젝트인 Sequence Object를 사용합니다. `@SequenceGenerator`라는 어노테이션에 sequenceName 속성으로 매핑할 데이터베이스의 시퀀스 이름을 지정해주고
여기서 매핑한 시퀀스 전략에서 id값을 가져옵니다.

TABLE은 데이터베이스에 키 생성 전용테이블을 만들어서 기본키를 생성합니다. 

이정도로 정리해보았는데 틀린부분이 있다면 피드백 주시면 감사하겠습니다!

2021-03-22 17:08 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return true;
@wheejuni QuestionService에서 질문을 삭제할때 사용됩니다. 요구사항중에서 삭제하려는 게시물의 유저와 모든 답변의 유저가 일치해야만 삭제할수 있다는 내용이 있어서 이 로직을 추가하게 되었습니다..!

2021-03-22 17:10 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setDeletedTrue() {
@wheejuni 오호.. 수정하겠습니다~!

2021-03-22 17:19 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
@wheejuni 엇.. 이제보니 어색해보이네요😅 수정하겠습니다

2021-03-22 17:20 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return userRepository.findByUserId(userId).orElseThrow(() -> new NotFoundException("해당 유저가 존재하지 않습니다."));
@wheejuni 넵 앞으로 이부분도 더 신경쓰도록 해야겠습니다

2021-03-22 17:24 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
@wheejuni 네네 다른분들 코드보니깐 말씀해주신대로 구현되어있길래 그 편이 더 나을거같다는 생각을 했습니다. 수정하겠습니다!

2021-03-22 17:31 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
@wheejuni 예외를 던지는걸 서비스에서 해줘야되나, 컨트롤러에서 해주는게 더 맞는건가 라는 고민을 했습니다. 그리고 서비스에서 구현하는게 더 맞는거 같아서 이렇게 구현한듯 합니다. 말씀해주신바로는 컨트롤러에서 예외를 던지는것도 괜찮은거 같으니 수정하겠습니다!

2021-03-22 17:56 UTC, kimnayeon0108 commented
@wheejuni 피드백 주신사항 수정완료했습니다.
AnswerService에서 QuestionRepository를 주입받는건 삭제했는데, Answer 객체 생성시 Question 이 필요해서 AnswerController에서 QuestionService를 주입받게 되는데 이부분은 괜찮은 것인지... 잘 모르겠습니다.😰

checkValidByPassword 메소드는 boolean 으로 리턴타입 수정했습니다. 
User 컨트롤러에서 회원정보 업데이트 하는 부분에서도 기존의 user.isPasswordMatching을 호출하는 부분을 checkValidByPassword메소드를 호출하는편이 나아보여서 이부분도 수정했습니다.
반면에 checkValidById의 같은 경우에는 컨트롤러의 대부분의 기능에서 호출되는데, 이때마다 예외를 던지면 중복코드가 발생할거같아서 기존방법대로 바로 예외를 던지도록 했습니다,,

2021-03-24 00:19 UTC, wheejuni approved these changes
👍

2021-03-24 00:20 UTC, merged