[Woody] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #103
Opened 2021-03-21 11:20 UTC by jihye-woo

안녕하세요! 우디입니다😀 

이번 미션은 사실 구현할 것들은 별로 없어서 `soft-delete`을 적용한 것 빼고는 이전 코드와 큰 차이가 없습니다!

이번 미션에서는 soft delete 구현 방식에 대해서 가장 고민을 많이 했습니다..! (사실 고민할게 이거밖에 없었...죠😅)
제가 고민한 부분에 대해서 아래에 간단히 적어보았습니다!

---

### 🤔 Soft Delete, 어떤 식으로 구현해야 좋을까?
soft-delete을 구현할 수 있는 방법이 여러가지가 있더라구요! 제가 찾아본 방식은 아래와 같은데 그 중 두 번째 방식을 사용해주었습니다..! 하지만 다 장단점이 있는 것 같아서 제가 적용한 방식이 맞는지 확신은 없습니다😳

1. `@Where`
   - `@Where(clause = "isActive=true")` 를 Entity에 추가
   - 그런데 이렇게 되면 hibernate를 implement한 경우에만 작동하고, `isActive=false`인 데이터는 가져올 수가 없다고  [스택오버플로우](https://stackoverflow.com/a/33168644)에서 주워들었습니다
   - (hibernate 관련된 부분은 아직 잘 모르겠지만ㅠ 두 번째 이유를 제 짧은 지식으로 이해해본 결과.. 항상 해당 Entity와 관련된 액션들에는 저 where 옵션이 붙기 때문에 삭제 상태인 데이터들은 가져올 수 없다고 말한게 아닐까라고 생각했습니당)
   - (-) 만약 그런거라면 제가 알고 있기론 delete 대신 softDelete을 하는 이유가 삭제된 데이터도 나중에 사용이 될 수 있기 때문인데 그 장점이 사라지는 것 같아서 일단 적용해주지는 않았습니다..!
   - 제가 이해한게 맞는지는 잘 모르겠네요..😳 사실 다들 Where 쓰시는 것 같아서 그 방법이 맞아보이는 것 같긴한데 말이죠..😂
  
2. 직접 Repository에서 `@Query` 작성
    - Repository에서 오버라이드한 메소드 위에 `@Query` 어노테이션을 통해 쿼리문을 직접 작성할 수 있더라구요!
    - 그래서 조회, 삭제 메소드에 직접 쿼리문을 작성해서 soft-delete를 구현해주었습니다!
    - (-) 그런데 이 방법을 사용해주게되면 JPA가 자동으로 쿼리문을 만들어주는 좋은 기능을 제대로 사용하지 못하게 되는 것 같아서 이것도 좋은 방법인건가..? 라는 의구심이 듭니다..

3. `@SQLDelete`
   - `@SQLDelete`를 적용하면, delete 요청이 들어왔을 때 `@SQLDelete` 내부에 작성해놓은 쿼리문이 실행된다고 하더라구요!
   - 근데 조회하는 기능도 건드려줘야하고 쿼리를 작성해주어야 한다는 점에서는 2번 옵션과 크게 다르지 않아보여서 적용해주진 않았습니다!

---

### 🚨 커밋 이력이 너무 길어요!
 - 제가 아직 이전 미션이 머지되지 않아서 그런지 아직 이전 커밋 이력들까지 남아있네요!
 - 아래 커밋 히스토리 중 `docs :  미션 4 체크 리스트` 라는 커밋부터 5개의 커밋만 이번 미션에 대한 커밋입니다!

---

읽어주셔서 감사합니다!

2021-03-22 13:02 UTC, LarryJung requested changes
안녕하세요~~ 제가 오랜만에 리뷰를 해서 죄송하지만 5개 커밋 이하의 변경사항까지 한번에 봐 버렸습니다.ㅠㅋㅋ

협업에서는 아주 간단히 컬럼 추가해서 직접 컬럼 업데이트하거나 where절에 일일이 조건 추가해서 가져오기도 하고요~ 팀바팀으로 다양하게 하고 있습니다. delete할 필요가 없는 테이블은 관련 컬럼도 없기도 하고요 ㅎㅎ

잘 하셨구요~! 몇개 더 수정사항 코멘트 달아 드렸으니 확인하시고 궁금한 점은 답글 달아주세요!!

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    @PostMapping()
인자가 없을때는 괄호를 제거하는게 낫지 않을까요?ㅎㅎ

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
나중에 요 포멧터가 공통으로 쓰인다면 밖으로 빼주세요~

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    @Column(name="is_active")
꼭 name에 is_active로 지정하지 않아도 됩니다. 기본은 스네이크 케이스로 인식합니다~

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    }
getCreateaAt을 String으로 변환할 필요가 있나요?

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +        }
빌더를 직접 만드셨네요~ 잘 하셨는데 한가지 요청드리면 Builder 기본생성자를 private으로 해놓고 빌더를 사용하려면 어떻게 해야할까요?ㅎㅎ

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/exception/CRUDAuthenticationException.java
> +public class CRUDAuthenticationException extends RuntimeException {
이름이 조금 어색한 느낌입니다. ㅠ 
CRUD 가 줄임말이어서 대문자가 맞지만 스프링의 CrudRepository 도 있는만큼 CRUD 말고 Crud 라고 해도 괜찮을 것 같구요~ 

이건 저의 제안인데 CrudNotAllowedException 같은 이름은 어떤가요? Authentication의 뜻도 의미가 있지만 웹개발에서 인증이란 용어가 디비 관련해서 등장하니 왠지 낯설어 보여서요~

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
저는 id 인자가 어떤 엔티티의 아이디인지 확실하게 알 수 있도록 도움을 주기 위해 answerId, questionId 등으로 그냥 id는 보통 쓰지 않습니다. 참고해서 혼동스런 부분이 있다면 수정해주세요~

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
create 메서드에 session말고 User가 인자로 들어오는 건 어떤가요?

왜냐하면 create(아래 delete) 하는데 session 정보가 로직 내부에 들어올 필요가 없어 보여서입니다. 보다 중요한 정보는 User인것 같고, 만약 User 정보가 session 이 아닌 다른 곳에서 정보를 가져오게 의존성이 바뀐다면 핵심 비즈니스 로직이 들어있는 서비스 로직을 건드리는 것보다는 그 밖의 레이어(컨트롤러 등) 을 수정해주는 편이 변화를 대응하는데 좀 더 안전할 것 같습니다.

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public void create(long questionId, String contents, HttpSession session){
트랜잭션 어노테이션이 어느 곳에서도 보이지 않는데, 아직 개념을 배우지 않으신건지요~ 
만약 그렇다면 @Transational 에 대해서 학습해주세요!

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    }
메서드 이름은 동사로 해 주시고요!
questionId를 넘기는데 List<Answer> 타입으로 반환하고 있으니 코드 리더들을 위해 getAnswersByQuestionId 등으로 수정하는편이 좋아보입니다!

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
여기도 이름 동사로 수정부탁드려요~

2021-03-22 13:02 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User loginUser = SessionUtils.getLoginUser(session);
혹시 여기까지 생각해보셨는지요?

세션에서 꺼내온 User과 db에서 꺼내온 User 가 같은 타입이더라도 둘은 상당히 큰 차이가 있습니다.

jpa의 영속성 컨텍스트의 관리를 받고 있냐 아니냐의 차이라고.. 이 내용이 궁금하시다면 jpa책을 살펴보시기를 바랍니다.ㅎㅎ

요지는 엔티티의 기능을 하지 않는다면 세션에 담는 클래스를 UserSessionDto 등과 같이 db와 관련이 없음을 클래스 이름을 통해서 알려주도록 하는 것도 좋을 것 같다는 이야기 입니다.~

2021-03-23 12:15 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    @PostMapping()
앗 그렇군요! 
()를 써주는게 통일성이 있다고 생각해서 빈칸으로 남겨두었는데
생각해보면 불필요한 부분들은 최대한 제거를 하는 편이 좋겠네요! 감사합니다!

2021-03-23 13:15 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
DateTimeUtils라는 유틸 클래스를 만들어서 밖으로 빼주었습니다!😀😀

2021-03-23 13:16 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    @Column(name="is_active")
앗...! 그렇군요! 이미 is_active라고 변환이 되니까 굳이 한 번 더 명시해줄 필요가 없겠군요! 
수정하였습니다 디테일하게 봐주셔서 감사합니다아😆😆

2021-03-23 14:15 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
앗 이 부분은 신경쓰지 않고 넘어갔었는데, 말씀하신대로 충분히 헷갈릴 수 있는 지점이라는 생각이 드네요!
- `Question`, `Answer`의 id 수정 완료 했습니다
- `User`의 경우 **id과 userId가 구분되어 사용되고 있기 때문에** User 엔티티와 관련된 id들은 그대로 두었습니다!

2021-03-23 14:25 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    }
앗 이 부분도 너무 생각없이 네이밍을 해버렸네요..! 
이참에 명사로 되어있던 메서드 이름을 모두 동사화 해 주었습니다! 감사합니다😀😀

위에서 코멘트 해주신 메소드 네이밍은 고민을 많이 했습니다...!
- 말씀해주신 `getAnswersByQuestionId()`는 메소드가 구체적으로 어떤 행동을 하는지 명확하게 표현할 수 있어서 좋다고 생각했지만!!
- 한 편으로는, 현재 메소드가 서비스 계층에 있기도 하고, 개인적으로 흐름을 알아보기 쉽게 하기 위해서 일단 `findAllAnswer()`라는 메소드 명으로 수정했습니다!

만약 들어주신 예시처럼 조금 더 구체적인 행동을 명시하는 것이 더 좋은 명명법이라면 바로 다시 수정하겠습니다!💦
(네이밍은 항상 어렵네요 흛흐😂)

2021-03-23 14:29 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
네엡! 마찬가지로 `findAllUser()`라고 수정했습니다!!

2021-03-23 18:01 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
`User 정보가 session이 아닌 다른 곳에서 정보를 가져오게 의존성이 바뀐다`는 상황은 생각을 해본적이 없었는데 
- 말씀하신 내용을 곰곰히 생각해보니 언급해주신 상황을 대비해서
- 그리고 서비스 계층이 최대한 Q&A 비즈니스 로직만 가질 수 있도록 하려면

Session 체킹 로직은 Controller 쪽으로 빼는게 훨씬 나아보이네요!!👀👀

말씀하신대로 수정하되, UserSerivce의 login() 메소드에서 만큼은 session 정보를 확인하는 과정이 들어가도 좋을 것 같다고 생각해서..! (예쁜 코드는 아니지만) 일단 로그인 메소드는 아래와 같이 session을 인자로 받아오도록 했습니다!
```java
// UserController 클래스
public String login(String userId, String password, HttpSession session) {
        User user = userService.login(userId, password, session);
        session.setAttribute("sessionedUser", user);
        return "redirect:/";
    }
```

```java
// UserService 클래스
public User login(String userId, String password, HttpSession session) {
        if(SessionUtils.isLoginUser(session)){
            return SessionUtils.getLoginUser(session);
        }

        User user = userRepository.findByUserId(userId)
                .orElseThrow(() -> new EntityNotFoundException("No user with userId " + userId));

        if (!user.isMatchingPassword(password)) {
            throw new FailedLoginException();
        }
        return user;
    }
```

2021-03-23 18:22 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/exception/CRUDAuthenticationException.java
> +public class CRUDAuthenticationException extends RuntimeException {
그렇군요!! 웹개발에서 인증이라는 용어가 디비와 함께 쓰일 때 어색하다는 점은 잘 몰랐습니다..!! 'Authentication'이라는 단어는 잘 생각해보고 사용해야겠군요!👀

그리고 말씀하신대로 공식적으로 제공하는 클래스명이 CrudRepository인걸 보면 'Crud'도 좋을 것 같네요! 저도 사실 구현하면서 클래스명 앞에 대문자가 여러 개 오는 점이 신경쓰이긴 했었거든요! 매의 눈으로 캐치해주셔서 감사합니다!🕵️‍♀️

제안해주신 대로 `CrudNotAllowedException`이라는 이름으로 수정했습니다! 감사합니다아🙇‍♀️

2021-03-23 19:01 UTC, jihye-woo commented
오늘 수정해놓은 부분까지 푸쉬해놓긴 했지만, 아직 **주신 코멘트 반영해서 더 수정하고 싶은 부분이 있습니다!!**
(그럴리 없겠지만🙄) 호옥시나 approve가 될까봐 미리 말씀드려요!!

리뷰 반영이 늦어져서 죄송해요😂😂 내일(24일)까지 빨리 마저하고 다시 PR 요청 드리겠습니다!

2021-03-24 14:27 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    }
넵 ㅎㅎ 실제로 인증방식이 바뀌는 경우는 잦은 일이 아니기는 하나, 계층을 분리해본다는 차원에서 말씀을 드린 것입니다~

2021-03-24 14:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    }
네 어떻게 해도 괜찮아 보입니다. ㅎㅎ 서비스 메서드를 쿼리문 쓰듯이 쓸 수만은 없는 것이니깐요
컨벤션 잘 지켜주시고, 나름의 기준으로 작성하시면 됩니다!

2021-03-24 14:29 UTC, LarryJung commented
> 오늘 수정해놓은 부분까지 푸쉬해놓긴 했지만, 아직 **주신 코멘트 반영해서 더 수정하고 싶은 부분이 있습니다!!**
> (그럴리 없겠지만🙄) 호옥시나 approve가 될까봐 미리 말씀드려요!!
> 
> 리뷰 반영이 늦어져서 죄송해요😂😂 내일(24일)까지 빨리 마저하고 다시 PR 요청 드리겠습니다!

네 현재 수정사항까지 확인 했구요~ 화이팅입니다!

2021-03-24 16:08 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public void create(long questionId, String contents, HttpSession session){
짤막하게 공부한 바로는..! Spring data Jpa에서 기본으로 제공하는 CRUD 메소드들은 트렌젝션을 보장해주는 것으로 알고있습니다..!

하지만 아직 `@Transactional`과 친하지 않기 때문에, 일단은 원자성이 반드시 유지되어야 한다고 생각하는 메소드에만 `@Transactional` 을 표기해주었습니다! (사실 조회 기능을 제외하고 거의 다 붙여준 것 같네요 허허🙄)

2021-03-24 16:31 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +        }
Builder 생성자를 private으로 전환해주는 대신 엔티티 클래스 내부에 `build()`라는 클래스 메소드를 만들어서 Builder 객체를 리턴하도록 수정하였습니다..!

```java
public User toEntity(){
  // return new User.Builder(userId, password) 대신!!
        return User.build(userId, password)
                .name(name)
                .email(email)
                .build();
    }
```

2021-03-24 16:36 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/domain/answer/Answer.java
> +    }
엔티티 클래스의 getter에서 String으로 변환해주지 않으면, 프론트 단에서 datetime 값을 포멧팅해주어야하는걸로 알고있습니다..! (혹시 다른 방법이 있는거라면 다시 한 번 찾아보겠습니다...😳!!) 

프론트를 건드리는 일이 아직 익숙하지 않아서 현재로써는 이렇게 Entity 내부에서 미리 포멧팅을 한 형태로 반환하고 있습니다😂😂

2021-03-24 18:19 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User loginUser = SessionUtils.getLoginUser(session);
영속성 컨텍스트에 대해서 아직 정확하게 안다고 할 수는 없지만..!ㅠㅠ
Entity를 사용하게 되면 영속성 문제로 의도치않게 다른 Entity에 영향을 주는 등 사이드 이펙트가 발생할 수 있어서 최대한 Entity를 사용하지 않는 쪽으로 코드를 작성해야한다고 알고있습니다!

그래서 말씀하신대로 세션정보를 User 엔티티가 아니라 UserSessionDto 클래스에 담아보려고 했지만...ㅠ 현재 제 코드가 **User 엔티티를 담고있는 세션정보**와 **의존도가 높아서** 결국 해당 리뷰는 반영하지 못했습니다... (특히 id 관련해서 문제가 발생했었는데 제대로 핸들하지 못했네요..😂)

2021-03-24 18:28 UTC, jihye-woo commented
24일까지 요청드린다고 했는데 하루를 넘겨버렸네요.. 흛.. 죄송합니다😂

생각보다 변경사항은 그렇게 많이 없긴 하지만.. 세션정보를 `User` 엔티티가 아닌 `UserSessionDto` 라는 DTO에 저장해보려고 시도하는 과정에서 시간이 생각보다 많이 걸렸습니다..ㅠ

늦었지만 다시 PR 요청 드려요오!! 감사합니다!🙇‍♀️

2021-03-30 02:11 UTC, LarryJung commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User loginUser = SessionUtils.getLoginUser(session);
이 요구사항은 나중에라도 꼭 해보는게 좋을것 같습니다~ 엔티티는 통상 비즈니스 로직(서비스 이하)에 등장하고 컨트롤러까지 나오지 않거든요ㅎㅎ 주변분들과 이야기하시면서 개선해보세요!

2021-03-30 02:16 UTC, LarryJung approved these changes
리뷰를 늦게 드려 죄송하네요~ㅠ 
수정사항은 어느정도 확인했고 승인 하도록 하겠습니다.

하지만 단방향 관련 커밋은 다음에 꼭 반영해주세요
Question 이 Answer를 가지고 있고, Answer도 Question을 가지고 있으면 양방향 관계입니다.
커밋 내용으로 보면 Question, Answer가 서로 멤버변수로 가지고 있으니 양방향 관계에서 setter를 수정하신 것인데, 이렇게 되면 데이터 저장 시 문제가 발생할 수 있으니 
단방향으로 하신다면 멤버 변수를 완전 제거 하셔야 합니다~

수고하셨습니다! 다음 단계 진행하시면서 개선해보세요👍

2021-03-30 05:07 UTC, merged

2021-03-30 05:07 UTC, honux77 commented
JPA 단방향 양방향은 검색해서 공부해 보면 좋겠네요! 화이팅입니다!