[MJ]미션4: 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #104
Opened 2021-03-21 11:33 UTC by MJbae

안녕하세요~ MJ입니다. 이번 리뷰도 잘 부탁드립니다!

[배포] ([https://spring-qna.herokuapp.com/](https://spring-qna.herokuapp.com/))

**미션 3, 4를 함께 진행하였습니다.**

**고민사항**

1. Controller와 Service의 역할을 아래와 같이 정리하였으나, 아직 확신이 없습니다. 혹시 아래와 같은 정리에 문제가 있다면 코멘트 부탁드립니다.
    - Controller의 역할

        → 클라이언트로부터 받는 데이터의 유효성 검사

        → 위의 데이터에 이상이 없다면 Service에 '유효한 데이터' 전달

    - Service의 역할

        → Controller로부터 전달 받은 '유효한 데이터'를 바탕으로 비지니스 로직 실행

2. Soft Deletion 구현에 어려움이 있었습니다. Question 객체에 맵핑된 List answers를 뷰에 뿌려주는 부분이 어려웠습니다.
    - Question 클래스의 answers에 Where 어노테이션 추가하여 deleted 속성이 false인 경우만 뷰에 전달되도록 설정하여 위의 문제를 해결하였습니다.

        → @Where(clause = "deleted=false")

    - '이노'의 코드를 보고 도움을 받았습니다.

2021-03-23 03:37 UTC, wheejuni requested changes
미션 두 개를 한번에 진행하시느라 고생 많으셨습니다. 💯 
다만 리뷰가 늦어진다면 우선 다음 미션을 진행하고, 이전 미션이 머지된 후 진행중인 브랜치를 최신화하는 방향으로 대응 가능하니, 앞으로는 가급적이면 한 PR에서 두 미션에 대한 리뷰를 요청하는 것은 자제를 부탁드려요. 

예외 처리에 대해서 고민하신 것 같아 그 부분을 잘 살펴봤는데, 특별히 이상한 점은 느끼지 못했습니다. 

피드백드린 내용은 `AnswerService` 의 역할 확장에 관한 내용과 **기본적인 코딩 컨벤션** 에 관한 내용입니다.
기본적인 코딩 컨벤션들은 과정 시작부터 지금까지 반복적으로 피드백드리고 있는 만큼, PR 오픈 이전에 한 번씩 다시 체크해 보시는 것도 좋을 것 같습니다. 
아울러 MJ의 코딩 습관에서 지역 변수를 다소 적극적으로 사용하시는 모습이 보입니다.
지역 변수의 할당 없이 원하는 결과값을 리턴할 수 있다면, 그렇게 하는 것이 사이드 이펙트를 줄이고 코드 가독성을 올리는 길입니다. 
그렇게 할 수 있도록 도와주는 편의 메소드들이 이미 많이 구현되어 있으니, 이런 관점에서 코드를 바라보고 고민하시는 것도 추천합니다. 

피드백 살펴보시고, 추가 질문이 있다면 알려주세요! 👍

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.remove(answer);
`AnswerService` 에 삭제 명령을 내릴 때에, `User` 까지 한 번에 넘겨서 권한을 체크한 후 액션이 일어나야 한다고 생각합니다.
이렇게 변경하는 것을 검토해 보시겠어요?

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private User writer;
**질문** 아까 컨트롤러에서 보니, 컨트롤러에서 `Answer` 객체의 `User` 를 꺼내 로그인된 유저와 비교하는 로직이 있었습니다.
그렇다면 이 `writer` 필드는 어떤 시점에 로드될까요?
`@ManyToOne` 매핑 전략을 취했을 때, 이 애노테이션이 붙어 있는 변수는 언제 초기화될까요? 
_이 원리를 숙지하고 사용하셔야 나중에 사고가 나지 않습니다._

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
`User` 쪽의 `.equals()` 오버라이드를 조금 더 정교하게 설계하는 방면으로 대응해야 할 것 같아요.
만약 MJ가 생각하시기에 `User` 의 동등성(equality)을 체크하는 유일한 기준이 `userId` 라면 말이죠.

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public void updateUserInfo(User referenceUser, String newPassword) {
이 메소드의 파라메터 구성에 이해되지 않는 부분이 있습니다.
우선, `referenceUser`  라는 네이밍은 직관적이지 않네요. 조금 더 좋은 네이밍을 고민해주셔야 할 것 같고요,
더불어, `newPassword` 라면 왜 `referenceUser` 에 담겨있으면 안되나요? 
오히려 `oldPassword` 를 받아서 정보를 바꿀 권한이 있는지 체크하는 구현은 안 되는걸까요?

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    Logger logger = LoggerFactory.getLogger(AnswerService.class);
접근제어자 좀 잊지 말아주세요. 
패키지에 있는 다른 클래스에서 이 변수에 접근해야 하나요? 아닐 거라고 생각합니다.

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        logger.info("testAnswer: " + testAnswer.toString());
로거는 스트링 템플릿을 지원합니다. 이 편이 [성능에도 이점이 있습니다.](https://stackoverflow.com/questions/10555409/logger-slf4j-advantages-of-formatting-with-instead-of-string-concatenation) 
앞으로는 템플릿을 적극적으로 사용해 주시면 좋을 것 같습니다. 

```suggestion
        logger.info("testAnswer: {}", testAnswer);

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        User redundantUser = userRepository.findByUserId(user.getUserId()).orElse(null);
아래와 같이 바꿀 수 있을 것 같네요.
직접 로직을 구현하기 전에 _미리 구현되어 있는 뭔가가 있지 않나_ 고민하는 습관을 가지는 것이 좋습니다. 

```suggestion
        User redundantUser = userRepository.findByUserId(user.getUserId))).isPresent();

2021-03-23 03:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    }
여기도 한 줄로 리팩토링이 가능할 것 같습니다. 어떻게 가능할까요?

2021-03-24 03:07 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.remove(answer);
SessionUser와 Answer의 writer의 동등성을 비교하는 로직을 비지니스로직으로 생각하는 것이 적절하네요. AnswerController를 포함하여 QuestionController, UserController의 관련 로직을 각각의 Service 계층으로 옮겼습니다.

2021-03-24 03:08 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
equlas를 제대로 사용하지 못하고 있었네요... userId 외에도 다른 속성의 동등성까지 체크하는 방식으로 변경하였습니다.

2021-03-24 03:08 UTC, MJbae commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    Logger logger = LoggerFactory.getLogger(AnswerService.class);
이런... 주의해야겠네요.

2021-03-24 03:09 UTC, MJbae commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        logger.info("testAnswer: " + testAnswer.toString());
그렇군요! 앞으로 템플릿을 잘 확인하고 사용해보겠습니다 :)

2021-03-24 03:15 UTC, MJbae commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    }
public static boolean isLoginUser(HttpSession session) {
    return session.getAttribute(USER_SESSION_KEY) != null;
}

이렇게 줄일 수가 있네요.

그런데 이렇게 줄이면 한 눈에 동작방식이 들어오지 않는 것 같습니다.

변경 전의 방식이 가독성면에서 좋지 않을까라는 생각이 듭니다.

@wheejuni의 의견이 궁금합니다.

2021-03-24 03:16 UTC, MJbae commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        User redundantUser = userRepository.findByUserId(user.getUserId()).orElse(null);
그렇군요... Optional에 대해 제대로 공부하지 않고 사용한 부분이 있습니다. 코드에 반영 전에 조금 더 알아보는 습관을 만들어 봐야겠습니다.

2021-03-24 03:21 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public void updateUserInfo(User referenceUser, String newPassword) {
다시 고민해보니 네이밍이 직관적이지 않네요. referenceUser -> newUserInfo로 변경했습니다. 

비밀번호 체크하는 부분은 한 번 고민해보겠습니다. 좋은 의견 감사합니다.

2021-03-24 03:26 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private User writer;
@wheejuni 아직 JPA에 대한 학습을 제대로 하지 않아서 그런지 질문이 이해가 되지 않습니다...
1. writer 필드가 로드되는 시점에 대해서 물어보셨는데, 그 시점이라는 것은 컴파일 시점과 런타임 시점 중 하나를 말씀하시는 건가요? 
2. ManyToOne 맵핑 전략에 따라 변수가 초기화되는 시점도 어떤 시점이 옵션으로 있는지조차 지식이 없습니다.
3. 1번과 2번 질문에 대해 스스로 공부해보고 싶은데 키워드라도 알려주시면 빠르게 공부해볼 수 있을 것 같습니다.

2021-03-24 03:27 UTC, wheejuni commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    }
저는 새로운 방향이 가독성 면에서도 더 낫다고 보지만, 이 부분은 개인의 주관이 들어가는 곳이라 @MJbae 께서 생각하시기에 좋은 방향으로 유지/수정 해주시면 좋겠어요.

2021-03-24 13:56 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private User writer;
@MJbae 우선 컴파일 타임에 초기화할 수 있는 지시자를 작성하진 않으셨으니 컴파일 타임에의 로드를 기대할 수는 없겠죠(사실 컴파일 타임에서의 로드라는 것이 잘 이해되지 않기는 합니다. 클래스로더를 말씀하신 건가요)? 

"JPA ManyToOne fetch, JPA fetch, JPA fetch join" 등으로 검색해보시면 좋을 것 같습니다.

2021-03-24 13:56 UTC, wheejuni approved these changes
수고하셨습니다. JPA 관련한 코멘트 하나 남겼는데요, 확인해보시고 학습 진행해보시면 좋겠습니다.
우선 이번 PR은 머지할게요. 👍

2021-03-24 13:56 UTC, merged