[새리] 미션3: 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #107
Opened 2021-03-22 06:36 UTC by min27604

안녕하세요 새리입니다.

미션 1, 2를 진행하며 개념공부를 차근히 하고 미션을 진행하니 진도가 너무 더뎌 강의영상을 보며 무작정 따라하고 고칠 부분은 Todo로 주석을 남기고 기능구현 후 고치는 식으로 진행해보았습니다. 지난번 미션보다는 더 빨리 진행이 된 것 같습니다.

이번 미션 요구사항에 따라 구현한 부분은 아래와 같습니다.

- HttpSession을 이용해 로그인 기능 구현
- 로그인 상태에 따른 메뉴 처리 및 로그아웃 기능
- 개인정보 수정(자기 자신의 정보만)
- 질문 수정하기 및 삭제하기
- User과 Question 연결
- 테스트 데이터 추가

위의 기능들을 구현하는데에는 강의 동영상이 있어 큰 어려움은 없었지만 그룹원들에게 코드리뷰를 받을 때 커스텀 예외를 만들고 핸들러를 이용해 처리하고 여러 중복되는 코드들은 메서드로 빼는 게 좋을 것 같다는 피드백을 받아 리팩토링까지 마쳤습니다.

힘들었던 점은 어디까지가 컨트롤러, 서비스의 역할인지, 중복되는 부분을 메서드로 분리할 때 어느 단에서 만드는 게 맞는 건지 헷갈려 그룹원들의 도움을 받았습니다.

시간내주어 리뷰해주셔서 감사합니다😊

배포링크: https://sallys-qna.herokuapp.com/

2021-03-23 15:43 UTC, sonypark requested changes
안녕하세요 새리, 리뷰어 소니 입니다.😊
와 코드가 정말 많이 깔끔해졌네요!! 코멘트 할 부분이 거의 없을 정도였어요💯
예외처리도 잘해주시고, optional.get() 메서드도 많이 줄었고(사용한 부분도 있지만..ㅎㅎ)
요구사항대로 잘 동작하네요. 아주 잘 구현하셨습니다!👍
고민을 많이한 흔적이 보였어요.
피드백은 간단한 거 몇개 남겼으니 확인해주세요~~ 수고하셨습니다!

![image](https://user-images.githubusercontent.com/34808501/112173978-64f90d00-8c39-11eb-9cac-277101651b68.png)

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        //registry.addViewController("/questions/form").setViewName("qna/form");
사용하지 않는 코드는 삭제해주세요~

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
ExceptionHandler는 CommonExceptionHandler에서 한꺼번에 처리해주면 되지 않을까요?

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
- Optional<User>을 리턴하지 않고 해당하는 id의 User가 존재하지 않으면 예외를 발생시키는 건 어떨까요?

- `Optional.get()` 메서드는 지양해야 합니다. 왜 그럴까요?

- `errorMessage` 만으로는 어떤 에러인지 모르겠죠?

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/HttpSessionUtils.java
> +    }
```suggestion
    public static boolean isLoginUser(HttpSession session) {
        return session.getAttribute(USER_SESSION_KEY) != null;
    }
```

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/HttpSessionUtils.java
> +    }
👍

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/CommonExceptionHandler.java
> +
👍

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          logger.info("Updated info: {}", updatedUser);
👍

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          model.addAttribute("user", user);
`errorMessage` 를 넣어주신건 어떤 의도인가요?

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            return "redirect:/users/{id}/wrongPassword";
비밀번호 예외처리 페이지까지👍

2021-03-23 15:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
👍

2021-03-24 01:29 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
QuestionNotFounException 자체가 저기서만 발생해서 저기다 뒀었는데 예외 핸들러가 있으면 거기다가 다 넣어주는게 좋은 것 같네요!

2021-03-24 01:51 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          model.addAttribute("user", user);
mustache 문법(html에 {{#errorMessage}})을 이용해서 뷰에서 에러메세지가 있으면 에러메세지를 보여주는 식으로 처리하기 위해 넣었습니다.

2021-03-24 02:16 UTC, min27604 commented on src/main/java/com/codessquad/qna/HttpSessionUtils.java
> +    }
불필요한 변수선언 줄이겠습니다!

2021-03-24 03:21 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
말씀하신대로 optional의 사용은 없애고 UserService에서 userId로 User를 찾아 존재하는지 여부를 확인하는 메서드를 만들어 컨트롤러에서 사용하도록 수정했습니다. 에러메세지는 단순히 뷰에만 넘겨준다는 생각이 들어 간단하게 적었는데 말씀하신대로 어떤 메세지인지 적으면 더 좋을 것 같아 그렇게 수정해두었습니다!

2021-03-24 03:25 UTC, min27604 commented
소니! 칭찬을 많이 해주셔서 몸 둘 바를 모르겠네요 ㅎㅎ 지난주 미션 마무리 단계에서 그룹리뷰를 받았었는데 그게 확실히 도움이 많이 되었던 것 같습니다. 다 그룹원들 덕입니다. 그래도 칭찬받으니 자신감도 생기고 기분이 좋네요😁 
항상 그렇듯 좋은 리뷰 감사합니다. 말씀하신 부분들 수정해서 리퀘스트 보냅니다. 감사합니다!

2021-03-24 14:00 UTC, sonypark approved these changes
새리 리뷰 반영하신거 확인했습니다.
수고하셨어요!!
머지 하겠습니다 😁

2021-03-24 14:00 UTC, merged