[Bibi] 미션2 - 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #108
Opened 2021-03-22 15:27 UTC by bibi6666667

안녕하세요, 백엔드반의 Bibi입니다😀
미션2 - 데이터베이스 활용 내용을 구현해 PR 드립니다!

<구현한 점>
- 미션1에서 만들어 둔 기능들을 H2데이터베이스를 사용하도록 수정

<배운 점>
- 스프링 애플리케이션과 데이터베이스(H2)연결하기 
- CrudRepository, JpaRepository의 차이점
- CrudRepository의 메서드들
- PUT method 사용법

<아직도 익숙하지 않은 부분>
- Optional과 그 메소드 사용법
- 메서드와 URL 네이밍..

이번 PR도 부족한 점이 많지만 피드백 받으면서 개선하겠습니다!
많은 코멘트, 피드백 부탁드립니다🙇‍♀️

좋은 밤 되세요! 감사합니다🙂

2021-03-23 12:25 UTC, d-h-k commented
@bibi6666667  비비선생님 코드 잘 보고 갑니다! 감사합니다!

2021-03-23 12:28 UTC, LarryJung requested changes
안녕하세요! 아직 미션2 이지만 학습하고 고민한 내용이 코드에 묻어 나오는 것 같아 좋았습니다. ㅎㅎ 
부족한 점은 얼마든지 개선할 수 있는 것이구요~

코멘트를 드렸으니 어렵거나 질문 있으시면 답글 남겨 주세요 화이팅입니다!

+ Optional 사용법은 검색하면 엄청 많이 나오는데요~ 하나만 가져와 봤습니다.
https://mangkyu.tistory.com/70

제가 생각하는 팁은 Optional 이 어떤 메서드가 있는지 . 만 찍어도 IDE에서 상세히 알려줄텐데 메서드의 Input, Output 타입이 어떤건지를 잘 살펴보면 도움이 될겁니다!

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        String dateTimeString = dateTime.format(dateTimeFormatter);
포멧을 적용한 DateTimeFormatter 까지 컨트롤러의 static 변수로 선언해서 쓰는것은 어떨까요?
newQuestion할때마다 포멧터를 만들지 않고 미리 만들어져 있는 포멧터를 사용한다면 비용을 조금 아낄 수 있을 것 같네요~

하지만 String, primitive type 이 아닌 클래스를 스프링 빈의 정적 변수로 사용하기 위해서는 꼭 그 객체가 thread safe 한지 찾아본 후 결정해야 합니다.

다행히 DateTimeFormatter는 thread-safe 하다고 나와 있네요~
https://www.callicoder.com/java-simpledateformat-thread-safety-issues/ 
의 하단 My Advice 참고 부탁드려요

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("question", questionRepository.findById(id).get());
Optional 에서 바로 get() 을 호출하지 않도록 해 주세요

Optional 타입을 받아왔으니 orElseThrow 등으로 값이 없을 때 처리를 해 주는 것이 좋습니다.^^
처음에는 사용법이 어려울 수 있는데 map, flatMap 등보다는 
orElseThrow, ifPresent 정도만 써서 없을때, 있을때 처리만 해보는 것으로 시작하셨음 하네요~

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        Iterable<User> users = userRepository.findAll();
Iterable 을 사용한 이유가 있으신가요~

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
단수보다는 복수형이 권장됩니다.^^

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User user = userRepository.findById(id).orElseGet(User::new);
찾는 user가 없다면 예외 상황으로 간주해도 될 것 같은데 새로 객체를 만들어 넘기는 이유는 무엇인가요?

2021-03-23 12:28 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        user.setEmail(targetUser.getEmail());
User 클래스 내에 tartgetUser를 인자로 받아 3개 필드를 set하는 메서드를 만들어 보세요~

2021-03-24 03:29 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        user.setEmail(targetUser.getEmail());
네! 만들어서 해당 부분 리팩토링 하겠습니다.

2021-03-24 03:30 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User user = userRepository.findById(id).orElseGet(User::new);
예외를 정의해서 사용하는 법을 잘 몰랐어서 이렇게 선언했었는데, 오늘 짝프로그래밍 하면서 동료분이 가르쳐 주셨습니다! 수정해서 다시 커밋하겠습니다😀

2021-03-24 03:35 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
`user`->`users` 로 URL 수정하겠습니다!
그런데 혹시, URL에 단수형보다 복수형을 사용했을 때의 특별한 이점이 있나요? 복수형 `users`로 사용하면 회원목록은 `/users`로 자연스럽지만, 나머지 URL들 (회원가입`/users/signup`, 회원정보 수정은 `/users/{id}`..)은 여러 회원들을 회원가입/수정하는 것 같은 의미가 되어버려서 일부러 `user`를 사용했었거든요. 🤔 조언 주시면 감사드리겠습니다😀

2021-03-24 03:37 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        Iterable<User> users = userRepository.findAll();
앗 이 부분은.. 단순히 `userRepository.findAll()`에 인텔리제이 단축키 (ctrl+alt+v)를 사용했더니 Iterable이 나오길래 그대로 사용했습니다. 그런데 굳이 Iterable을 사용할 이유가 없네요😅 다른 방법으로 사용하도록 수정하겠습니다!

2021-03-24 03:38 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("question", questionRepository.findById(id).get());
네! 코멘트 주신 링크도 참고해서 공부해 사용해 보겠습니다. 감사합니다😀👍

2021-03-24 03:39 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        String dateTimeString = dateTime.format(dateTimeFormatter);
그렇게 하는 게 훨씬 낫겠네요! 말씀대로 수정해 보겠습니다😀 학습링크와 조언 감사합니다!!👍

2021-03-24 05:18 UTC, bibi6666667 commented
안녕하세요, 백엔드반의 Bibi입니다😀
요청 주신 변경사항들을 반영했습니다!

<변경 사항>
- Optional 객체에 대해 `get()` 사용 부분들을 `orElseThrow`로 변경
- 예외 처리를 위해 각 예외를 정의 및 사용하는 법을 배우고 적용 (피어리뷰 때 도움을 받았습니다)
- templates폴더의 html파일들을 하위 폴더로 분류
- URL 개선 (user->users 등등)

<질문>
> user->users 로 URL 수정하겠습니다!
그런데 혹시, URL에 단수형보다 복수형을 사용했을 때의 특별한 이점이나 이유가 있나요? 복수형 users로 사용하면 회원목록은 `/users` 도  자연스럽지만, 나머지 URL들 (회원가입 `/users/signup`, 회원정보 수정`/users/{id}`..)은 여러 회원들을 회원가입/수정하는 것 같은 의미가 되어버려서 일부러 user를 사용했었거든요. 🤔 조언 주시면 감사드리겠습니다😀

2021-03-24 14:36 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
음.. 제 생각은 복수를 쓰는 것이 `rest api 의 컨벤션이다` 정도로만 말씀드리고 싶네요. ㅎㅎ 
그런데 그것을 지키지 않는 경우도 더러 있지만, 먼저는 rest api 다운것이 무엇인지 학습해보시고 그렇지 않은 것과 비교해보세요!

참고: https://bcho.tistory.com/914

2021-03-24 14:39 UTC, LarryJung commented on src/main/java/com/codessquad/qna/exception/QuestionNotFoundException.java
> +}
이렇게 각각 Exception을 전부 만들어 줄 수 도 있겠지만 만들다보면 엄청 많아질 수도 있거든요~
에러 메세지의 내용을 달리하여 구분할 수 있다면 EntityNotFoundException 과 같이 공통으로 사용할 예외를 만들어 사용하는 편이 편할 수도 있습니다!

2021-03-24 14:40 UTC, LarryJung commented on src/main/java/com/codessquad/qna/repository/User.java
> +        this.email = user.getEmail();
여기서는 user.password 로 필드에 바로 접근할 수도 있습니다.^^

2021-03-24 14:42 UTC, LarryJung approved these changes
수정 사항 확인했습니다. 먼저 승인 하도록 하고 나머지 내용들은 다음 미션에 반영해주세요! 

수고하셨습니다 :)

2021-03-24 14:42 UTC, merged

2021-03-25 05:42 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
그렇군요! 참고해서 공부해 보겠습니다. 감사합니다👍

2021-03-25 08:26 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/exception/QuestionNotFoundException.java
> +}
그렇군요! `EntityNotFoundException`으로 통합해서 사용하도록 수정하겠습니다 😀

2021-03-25 08:27 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/repository/User.java
> +        this.email = user.getEmail();
앗ㅋㅋㅋ그렇네요 수정하겠습니다! 감사합니다😀👍