[Roach] Mission2 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #11
Opened 2021-03-04 10:31 UTC by tmdgusya

## Dto 를 만든 이유 🧐

팀원 코드리뷰를 받았을때, @ModelAttribute 라는 것을 사용해보면 어떻겠냐는 의견을 들었습니다.
그런데 @ModelAttribute 의 내부 동작이 setter 와 getter 가 정의가 되어있어야 작동한다고 명시되어있어
Entity 에 Setter 를 추가하는것은 옳지 않은 방향이 아닐까..? 라는 생각이 있었는데 마침 팀원이 Dto 라는 개념을 도입해보면 어떻겠냐고 해서
Dto 를 사용하게 되었습니다. Dto 는 Mapper 클래스의 mapToEntity 이라는 method 를 통해 해당 Entity 로서 변환할 수 있도록 하였습니다.

Dto 를 만들자 중복됬던 @ParamValue 들을 줄일 수 있게 되었습니다. 

**코드를 짜면서 최대한 중복코드를 줄이고, 역할을 분리하는 방향으로 나아가려고 노력했습니다.**
하지만 부족한점이 많을것 같아. 잘못된 방향에 대해서 지적해주시면 감사하겠습니다

2021-03-04 13:41 UTC, imjinbro commented on src/main/java/com/codessquad/qna/dto/PostDto.java
> +public class PostDto {
@lombok을 공부해보시는 것도 추천드립니다.

2021-03-04 13:45 UTC, imjinbro commented on src/main/java/com/codessquad/qna/util/Mapper.java
> +public class Mapper {
Mapper를 만들어서 dto -> entity로 가시려고 하는 의도는 좋아보입니다.
다만 Mapper를 만드셨다면 더 역할을 강화하는게 좋아보여요
Post 생성자에 있는 String을 인자로 받아 Date로 저장하는 것이나 PostDto에 값이 Null로 들어올 경우에 대한 예외처리 등이 필요해보입니다.

그리고 EntityMapper가 필요할만큼 코드 복잡도가 높아보이지 않아서 오히려 Post나 User의 생성자에서 처리하는 것도 나쁘지 않아보이네요

2021-03-04 13:46 UTC, imjinbro commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        Optional<User> user = userRepository.findById(userId);
예외처리 좋네요 
하나 더 줄일 수 있는 팁을 드리자면 아래 처럼 구현하셔도 됩니다
`
return userRepository.findById(userId)
                        .orElseThrow(CanNotFindUserException::new)
`

2021-03-04 13:49 UTC, imjinbro commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    public Optional<User> findById(Long userId);
User 클래스를 보면 Id(DB PK)로 지정된 프로퍼티가 Id 입니다.
기본적으로 스프링 JPA가 findById가 만들어질거고요

지금 메소드는 의도한대로라면 findByUserId 가 되어야할겁니다.
해당 메소드도 Spring JPA가 생성해줄 것으로 생각되는데 한번 테스트 해보시길 바래요

2021-03-04 13:50 UTC, imjinbro commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    public Optional<User> findById(Long userId) {
Id(Entity PK)인지 UserId 인지 혼동되지 않도록 쿼리메소드명을 지을 때 정확한 프로퍼티명을 기입해주세요

2021-03-04 13:52 UTC, imjinbro commented on src/main/java/com/codessquad/qna/repository/MemoryPostRepository.java
> +public class MemoryPostRepository implements PostRepository {
오호 인터페이스를 잘 활용해보셨네요

2021-03-04 13:53 UTC, imjinbro commented on src/main/java/com/codessquad/qna/entity/User.java
> +    public void Change(String id, String password, String name, String email) {
메소드명은 소문자로 지정해주세요

2021-03-04 13:55 UTC, imjinbro commented
안녕하세요 리뷰어 콜린입니다.
버그를 일으킬 수 있거나 오버엔지니어링된 부분이 있어보여 코멘트 달아두었습니다.
해당 부분 수정되는 것이 좋을 것 같아 Change Request 하도록 하겠습니다

2021-03-04 13:56 UTC, imjinbro requested changes
안녕하세요 리뷰어 콜린입니다.
버그를 일으킬 수 있는 코드와 조금은 오버엔지니어링 아닌가? 혹은 보강할 수 있는 부분이 아닌가 하는 부분이 있어서 생각해보시길 권해드리면서 Request changes 드리겠습니다.
고생하셨어요!

2021-03-05 01:11 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        Optional<User> user = userRepository.findById(userId);
감사합니다!~

이렇게 한줄로 줄여쓸수 있었는데 두줄로쓰고 있었네요!

2021-03-05 01:12 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    public Optional<User> findById(Long userId);
감사합니다 이런 세세한 부분도 신경썼어야 했는데 신경쓰지 못했네요!

2021-03-05 02:01 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/util/Mapper.java
> +public class Mapper {
아직 이런 부분에서 판단하는게 어렵네요!

다만 생성자로 처리해주지 않은 부분은 @ModelAttribute 가 Setter 가 있어야 하더라고요
Mapper 에서 예외처리가 되지 않은 부분들을 고민해보고 처리해서 다시 올릴 수 있도록 하겠습니다!

2021-03-05 03:10 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/dto/PostDto.java
> +public class PostDto {
lombok 적용하니 코드가 정말많이 줄어드네요. 👍
컴파일 시점에 코드를 만들어주다니.. class 파일 눈으로보니 신기하네요!

2021-03-05 08:05 UTC, tmdgusya commented
에러 페이지를 만들어서 에러 메세지를 홈페이지로 출력할 수 있도록 했습니다.
공통적인 예외처리 부분은 아직은 따로 둬도 괜찮을 것 같다는 생각에 @ControllerAdvice 로 따로 아직 빼지는 않았습니다.
이 부분에 대한 조언도 주시면 감사하겠습니다~!

2021-03-08 04:47 UTC, honux77 commented on src/main/java/com/codessquad/qna/dto/PostDto.java
> +public class PostDto {
하지만 과정 중에는 롬복 사용하시면 안 됩니다 ㅋㅋ. 나중에 쓰세요.

2021-03-08 04:48 UTC, honux77 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        Optional<User> user = userRepository.findById(userId);
생성자 참조라고 해요 ㅎㅎ.

2021-03-08 05:14 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/dto/PostDto.java
> +public class PostDto {
> 하지만 과정 중에는 롬복 사용하시면 안 됩니다 ㅋㅋ. 나중에 쓰세요.

리뷰받은 부분이라 넣은 상태로 요청드렸는데, 다시 제거해야겠군요. 어차피 @Getter 랑 @NoargsContructor 밖에 안써서 다행이네요.
롬복 제거해서 반영하도록 하겠습니다.

2021-03-08 07:20 UTC, honux77 approved these changes
제가 대신 머지할게요. 
제 생각에도 DTO를 쓸만큼 복잡한 코드는 아니라고 생각하지만 그래도 학습용으로는 좋은 것 같습니다. 수고하셨어요!

2021-03-08 07:21 UTC, merged