[Tree]미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #110
Opened 2021-03-23 03:00 UTC by choitree

안녕하세요 트리입니다.

미션2의 내용에 따라서, h2 DB와 연결하고, 데이터가 생성되도록 변경하였습니다.
- 사용자 데이터 추가
- 사용자 목록 조회
- 사용자 조회
- 질문 데이터 저장하기
- 질문 목록 구현하기
- 질문 상세보기
- 회원정보 수정

회원정보 수정의 경우, 자바지기님 강의를 보고 User 클래스에 update 메소드를 만들어서 변경하였습니다.
해당 메소드를 사용하지 않고 변경하고 싶었으나 한계가 있어 우선 강의 내용대로 구현하였습니다.

이번 미션에서는 커밋을 조금 더 세부적으로 했지만, 그래도 기능별로 쪼개지는 못한 것 같습니다.
다음 미션에서는 커밋 단위를 더 쪼개보도록 하겠습니다.

2021-03-23 12:25 UTC, d-h-k commented
@choitree 트리 코드 잘 보고 갑니다!! 화이팅하세요!

2021-03-23 13:59 UTC, sonypark requested changes
안녕하세요 Tree, 리뷰어 소니 입니다.😊
미션2 구현하느라 고생많으셨습니다👍
기능 동작하는거 확인했고, 요구사항 대로 동작을 안 하거나 아쉬운 부분은 코멘트 남겼은 확인 후 수정부탁드려요!

- 회원 정보 수정이 요구사항대로 안되는데 확인 부탁해요.
    - 아래 조건대로 작동하는지도 확인해주세요.
    - 비밀번호, 이름, 이메일만 수정할 수 있으며, 사용자 아이디는 수정할 수 없다.
    - 비밀번호가 일치하는 경우에만 수정 가능하다.

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
final을 붙여주는게 어떨까요?

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String showQuestion(@PathVariable Long id, Model model) {
QuestionController의 메서드이니 메서드명에서 question은 빼도 될 것 같아요

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        model.addAttribute("question", questionRepository.findById(id).get());
`Optional.get()` 메서드는 사용하지 않을 것을 권장합니다. 왜 그럴까요?

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        userRepository.save(user);
여기도 `Optional.get()`을 사용하지 않도록 변경해보세요.

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          }
user가 null인 경우 이 조건문까지 들어오나요??

2021-03-23 13:59 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/User.java
>      }
이 메서드가 필요할까요?

2021-03-23 18:50 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        model.addAttribute("question", questionRepository.findById(id).get());
어제 간략하게 옵셔널을 학습해봤었는데, 이 부분이 Optional인지도 모르고 있었네요😱
제가 사용한 방법은 null 여부를 확인하지 못해서 nullpointerException이 발생할 수 있다고 학습했었습니다.
Optional.orElse(null); 이렇게 작성하면 될까요?~~

2021-03-23 18:52 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          }
😱😱😱 비어있는 유저가 생성되네요 엄청 치명적인 오류네요!!!! 
수정해보도록 하겠습니다!!

2021-03-23 18:52 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        userRepository.save(user);
넵!!

2021-03-23 18:56 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          }
근데 User클래스에서 userId 컬럼을 nullable로 만들었는데, 어떻게 생성되는건지 이해가 안가네요....ㅠㅠ
이 부분은 조금 더 찾아보고 변경해보도록 하겠습니다~

2021-03-28 18:59 UTC, choitree commented on src/main/java/com/codessquad/qna/domain/User.java
>      }
그룹 리뷰에서도 동일 부분에 대해서 리뷰를 받았습니다.
getter와 setter를 모두 생성해놓고 사용하곤했는데 setter는 사용될 때마다 생성해서 사용하는 습관을 들여보겠습니다!

2021-03-28 19:03 UTC, choitree commented
리뷰 내용 다시 요청드리는 것이 매우 지연되었네요ㅠㅠ
리뷰해주신 부분은 모두 수정하였습니다.
Optional.get()을 Optional.orElse(null)로 수정했는데 현재 상태에서는 이런 방향으로 변경해도 괜찮은건지와
회원가입 부분에서 user의 null을 체크하는 내용을 ""또는 null로 체크하도록 변경했는데 이 부분이 맞는건지 알려주실 수 있나요?~
제 생각의 한계에서는 회원가입 시 공백이나 null값이 들어가면 안된다는 생각에 모든 값에 공백이나 null이 들어가지 않도록 if문으로 조건을 주었는데 아닐 수 있을 것 같아서 여쭤봅니다

2021-03-29 00:52 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        model.addAttribute("question", questionRepository.findById(id).get());
Optional은 NPE를 방지하기 위해서 사용하는데, `Optional.orElse(null)` 이렇게 할 경우 결국 null 인 경우 null을 리턴하는 것이므로 의미가 없습니다. 또 다시 null인지 아닌지 체크하는 로직을 추가해줘야 되기 때문입니다. `questionRepository.findById(id)` 메서드의 목적은 id에 해당하는 question이 있다면 question을 리턴하고 없다면 예외를 발생시키는 것이라고 생각합니다. 따라서 orElse 가 아닌 orElseThrow를 이용해서 해당 id의 question이 존재하지 않는다는 예외를 발생시키면 되지 않을까 싶네요~

2021-03-29 03:41 UTC, sonypark approved these changes
Tree 안녕하세요
질문하신 부분에 대한 답변은 코멘트로 남겼습니다.
다음 미션 진행하면서 반영해주세요💪
이번 단계는 여기서 머지할게요! 수고하셨습니다 👍

2021-03-29 03:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>          }
validation을 하는 방법은 아래 링크를 참고해서 반영해주세요~

[Validation in Spring Boot](https://www.baeldung.com/spring-boot-bean-validation)
[Complete Guide to Validation With Spring Boot](https://reflectoring.io/bean-validation-with-spring-boot/)

2021-03-29 03:41 UTC, merged