Mission3
codesquad-members-2021/spring-boot-qna pull request #112
Opened 2021-03-23 09:07 UTC by d-h-k

# 글 수정중입니다

2021-03-23 15:02 UTC, sonypark requested changes
안녕하세요 Dong, 리뷰어 소니 입니다.😊
미션3 금방 구현해주셨네요.
확인 결과 제대로 동작하지 않는 부분이 있어 코멘트 남깁니다.

1. 로그인 후 질문 수정/삭제가 되지 않습니다.
2. 로그인 후 로그아웃 버튼이 생기지 않네요.
위와 같은 문제로 요구사항 확인이 어렵습니다. 확인 부탁드려요!

기타 사항은 코멘트로 남겼습니다:)

++ 현재 컨트롤러에 모든 로직이 집중되어 있는데, 컨트롤러와 서비스를 분리해보면 더 좋을 것 같습니다

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/UserRepository.java
> +    //리턴타입 2 optional
반환값은 `Optional<User>`가 돼야하지 않을까요?

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        }
이 로직은 이렇게 하기 보단 findByUserId에서 해당하는 id의 User 없을때 예외를 발생시키는 걸로 바꿔주세요~

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/utils/SessionUtil.java
> +    }
예외가 발생했을 때 처리 코드가 없네요

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          return "user/updateForm";
질문을 작성한 사용자와 로그인한 사용자가 같은 사용자인지 검증하는 로직이 없네요

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        }
이 코드에서 sessionUser가 null인 경우가 있나요?

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          User currentUser = userRepository.findById(id).orElseThrow(() -> new Exception("데이터 검색에 실패하였습니다"));
커스텀 예외를 사용해보세요. Exception을 예외로 발생시키는건 너무 추상적입니다. "데이터 검색에 실패하였습니다"와 같은 추상적인 예외 메시지도 적절치 않네요.

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        model.addAttribute("userlist", userRepository.findAll());
session이 필요한가요??

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
UserController..! 😅

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        model.addAttribute("user", user);
이 코드를 추가해주신 이유가 있나요?

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          questionRepostory.save(question);
setWriter가 아니라 Question의 생성자로 받는 건 어떨까요? setter 사용은 지양하는게 좋습니다.

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          Question currentQuestion = questionRepostory.findById(id).orElseThrow(() -> new Exception("데이터 검색에 실패하였습니다"));
여기도 exception 부분을 커스텀예외로 바꿔주세요

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDateTime createDate;
변수명은 명사로 바꿔주세요~

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return createDate.format(DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm:ss"));
패턴 포맷 문자열은 상수로 빼도 좋을 것 같아요~

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          return "/qna/show";
아래 링크 참고하셔서 로거를 고쳐보세요~

[SLF4J Logger 사용법 & 잘못된 사용법: Binding Parameters, Logging Exception Stack Trace](http://dveamer.github.io/backend/HowToUseSlf4j.html)

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/exception/NotFoundException.java
> +    }
- 이 메서드가 여기 있는게 맞을까요??
- 파라미터에 Model을 넣어주신 이유가 있나요?

2021-03-23 15:02 UTC, sonypark commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +
여기는 아무것도 하고 있지 않네요..??

2021-03-23 15:02 UTC, sonypark commented on src/main/resources/templates/qna/list.html
> +
사용하지 않는 코드는 삭제해주세요:)

2021-03-23 15:02 UTC, sonypark commented on build.gradle
> +
이 의존성은 왜 추가해주신건가요??

2021-03-23 15:24 UTC, d-h-k commented on build.gradle
> +
아 넵 해당부분 Spring 빌드가 계속 나고, 구글검색해도 답을 얻지 못해 혹시나 하는 마음에 추가해 본 의존성인데요, 해당 방법은 해결책이 아니였습니다.

알고보니, data.sql 파일에 오타가 있어서 spring 빌드가 실패했었는데, 삭제를 하지 않아 남아있었습니다. 삭제하도록 하겠습니다!

2021-03-23 15:25 UTC, d-h-k commented on src/main/resources/templates/qna/list.html
> +
넵 해당부분 html 주석은 모두 삭제 처리하겠습니다! 감사합니다!

2021-03-23 15:29 UTC, d-h-k commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +
아 네 해당부분은 익셉션 핸들러를 처리해주려고 자바 익셉션 기능을 처음 공부하면서 작성중이였습니다.

예를들어서, userRepository에서 데이터 검색시 존재하지 않으면 nullPointerException발생하는걸 if문 예외처리로 막아주는 방식인데요, 이부분을 Exception 기능을 사용해서, 발생시 redirect 처리 하는 기능을 구현중인데, 지식이 모자라서 아직 코드를 추가하지 못하고 있었습니다 ㅠㅠ..

2021-03-23 15:35 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          return "/qna/show";
넵 감사합니다!  위 링크를 참고해 제 나름대로 정리를 해봤습니다 
https://www.notion.so/11-9e084610ce8242baac9e826c3082a993

```
logger.info("update Question : {}" + currentQuestion.getTitle());
```
- 코드는 위 방식으로 수정을 했습니다! 
앞으로도 로거에서 문자열 연산은 하지않도록 주의하겠습니다 좋은 말씀 감사합니다!!

2021-03-23 15:38 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        model.addAttribute("userlist", userRepository.findAll());
앗 넵 user list 를 확인하는건 "admin" 같은 슈퍼계정에서만 가능하도록 강제하려고 했는데, 이게 막상 돌려보니까 테스트가 너무 힘들어서 나중에 완성직전에 해당 기능을 넣기로 하고, 세션에 상관없이 user list 를 조회할 수 있도록 변경했는데, 해당 입력파라미터를 삭제하지 않은 부분을 정확하게 캐치해주셨네요 ㅠㅠ..!!! 감사합니다 바로 수정하겠습니다!

2021-03-23 15:47 UTC, d-h-k commented on src/main/java/com/codessquad/qna/utils/SessionUtil.java
> +    }
넵 해당부분 MD-5 해쉬함수 적용하느라 try-catch 가 필요했는데, MD-5로 인해서 로그인에 장애가 발생하는 side-effect 가 발생해서 해당 기능은 나중에 사용하도록, 다시 문자열상수로 키를 사용하는 코드로 변경하였습니다...!!! ㅠㅠ.. 

해당 코드는 삭제하겠습니다!

2021-03-23 15:54 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return createDate.format(DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm:ss"));
넵 해당 패턴포맷스트링은 상수로 빼겠습니다!

2021-03-23 16:01 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDateTime createDate;
넵 생각해보니 변수명으로는 부적절한 동사를 변수의 이름으로 사용하고 있었네요, 동일한 의미이지만 명사형인 creationDate 으로 바꾸겠습니다.

2021-03-23 17:26 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/UserRepository.java
> +    //리턴타입 2 optional
넵 해당부분은 User보다는 조금더 방어적은 Optional을 사용해야 좋은 코드였던거 같습니다 말씀해 주셔서 감사합니다

2021-03-23 17:27 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        }
넵 해당부분은 Optinal 로 리턴받는곳에서 NPE 방어를 예외를 발생시켜 처리하겠습니다.

2021-03-23 17:31 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          return "user/updateForm";
넵 제가 이부분은 접근하는 사람의 세션으로 유효성 검사를 하지 않았네요 말씀해주셔서 감사합니다! 

앞으로 조금 더 꼼꼼하게 세션체크가 필요한곳에 꼭 로직을 넣도록 하겠습니다!

2021-03-23 17:39 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          questionRepostory.save(question);
setter 사용을 지양하는것도 몰랐는데, 조금더 학습해보겠습니다 말씀 해 주셔서 감사합니다.

말씀하신대로 Question의 생성자로 받는방식으로 수정해보니까 코드가 훨씬 가독성도 좋아지고, 간결해졌어요! 감사합니다

2021-03-23 17:51 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        model.addAttribute("user", user);
넵 해당부분에 user 객체를 넣어 준 이유는, qna/form.html 페이지에서 사용자 id 가 disabled 로 변경은 불가능하지만, 표시가 되도록 하고 싶어서 구태여 user 객체를 모델로 전달해주었습니다. 

자바지기님 영상에서는 아이디가 출력되지 않고, 다른 커뮤니티를 봐도 글올리는 공간에 userID가 따로 표시되지는 않아서 해당부분은 UserID가 표시되지 않도록 수정하고, 삭제하겠습니다

2021-03-24 14:32 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        }
차근차근 코드를 살펴보니 null인 경우가 없습니다! 
해당코드는 중복이므로 삭제하겠습니다

2021-03-24 14:33 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          User currentUser = userRepository.findById(id).orElseThrow(() -> new Exception("데이터 검색에 실패하였습니다"));
넵 해당부분에는 커스템 예외로 발생시키도록 처리하겠습니다

2021-03-24 14:34 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
앗 퀘스천에 유저라니;;; ! 미쳐 발견하지 못했습니다 ㅠㅠ..! 바로 수정하겠습니다

감사합니다 앞으로는 좀더 주의하겠습니다

2021-03-24 14:37 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>          Question currentQuestion = questionRepostory.findById(id).orElseThrow(() -> new Exception("데이터 검색에 실패하였습니다"));
넵 해당부분도 exception 부분을 커스텀예외

2021-03-24 14:39 UTC, d-h-k commented on src/main/java/com/codessquad/qna/exception/NotFoundException.java
> +    }
없습니다! Exception 을 잘 모를때 만든것이라, 불필요한 코드들이 많이 있네요 ㅠㅠ.. 수정했습니다!

2021-03-25 09:53 UTC, sonypark approved these changes
Dong 안녕하세요~
전보다 코드가 많이 깔끔해졌네요!
미션4 관련 코드가 몇개 보이는데, 현재는 미션3 리뷰이기에 해당 부분은 코멘트 남기지 않았습니다.
코멘트 남긴 부분은 미션4 진행하며 반영해주세요~
다음 미션 진행해주세요~ 수고하셨어요!

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +import com.codessquad.qna.exception.NotFoundException;
커밋하기 전에 `Optimize imports` 해주세요~~
여기말고 다른 클래스에도 사용하지 않는 import 가 보이네요

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.isLogin(session);
`Model` 은 사용되지 않는데 추가한 이유가 있나요~?

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
이 메서드는 필요없을 것 같아요

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        Question question = questionRepostory.findById(id).orElseThrow(NotFoundException::new);
ownerUser가 필요한가요?

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        User foundUser = userRepository.findById(id).orElseThrow(NotFoundException::new);
여기도 Model은 쓰이지 않네요

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/utils/StringUtil.java
> +}
이걸 StringUtils로 뺄 필요까지는 없을 것 같아요.
PATTERN_FORMAT만 보고는 어떤 패턴인지 알 수 없는데, 네이밍을 좀 더 명확히 하면 좋겠네요~

2021-03-25 09:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String deleteQuestion(@PathVariable Long id, User ownerUser, HttpSession session) {
Question 컨트롤러 메서드인만큼 메서드명에서 question은 빼도 될 것 같아요
User나 Answer도 마찬가지~

2021-03-25 09:54 UTC, merged

2021-03-25 12:55 UTC, d-h-k commented
안녕하세요 @sonypark 먼저 이번 미션3 좋은 리뷰들 남겨주셔서 정말정말 감사드립니다. 

미션4 내용이 섞여있는 이유는, 미션3을 진행하다 보니까 아쉬운 부분이 몇가지 있었는데
- Question에 Answer가 달려있으면, 데이터베이스 에러가 발생해서 이 문제를 해결하고자 검색한 결과가 미션4의 구현 요구사항이였던.. 것이라서 어쩌다 보니 미션4 요구사항의 대부분이 기능구현이 완료되어 버린 상황입니다.. ㅠㅠ 

남겨주신 다른 부분도 모두 다음 PR에서는 반영해 조금 더 깔끔한 코드를 만들수 있도록 지속적으로 노력하겠습니다! 

감사합니다

2021-03-25 13:01 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +import com.codessquad.qna.exception.NotFoundException;
넵 인텔리제이 기능을 활용해서 전체 코드 옵티마이즈를 진행하겠습니다!

2021-03-25 13:16 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String deleteQuestion(@PathVariable Long id, User ownerUser, HttpSession session) {
넵 말씀해주셔서 생각해보니 정말 의미중복이 있다고 느껴집니다. 해당 부분 개선하였습니다!