[Starve + Kyu] Mission4 - 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #113
Opened 2021-03-23 12:04 UTC by Jiwon-JJW

안녕하세요.

코드스쿼드 백엔드 과정 Starve입니다.

이번 주 부터 Kyu와 함께 짝 프로그래밍을 진행하며 미션 4를 완료하였습니다!
이번 코드도 잘 부탁드립니다!

[배포 사이트](https://starve-spring-0119.herokuapp.com/)

##### 이번 미션에서 고민하고 있는 사항:

* Result 클래스를 통해 에러메세지를 입력받아 출력하고 있는 상황인데, 클래스 이름이 적절치 않아 보인다는 것이 고민이었기에, 리뷰어분의 의견이 궁금합니다! 

##### 이번 미션에서 달라진 점:

* Service 클래스를 구현하여 기존 컨트롤러에서 Repository에 저장하거나 삭제하는 기능을 옮기는 리팩토링 과정을 진행 해 보았습니다.
  HttpSession에서 관리하는 것들도 옮기는 것이 좋을까 고민했지만, 그 것은 Controller에서 관리하는 것이 더 잘 맞을 것 같아 옮기지 않았습니다.
* 날짜 포맷팅을 변경하였습니다. 본래 ISO_DATE_TIME을 사용했지만, 포맷팅을 안한것이랑 다를 바가 없어보여 새롭게 지정하여 변경해 보았습니다.

감사합니다!

2021-03-24 23:28 UTC, wheejuni commented
@Jiwon-JJW 컨플릭트가 있네요. 컨플릭트를 먼저 해결해주세요.

2021-03-25 01:06 UTC, Jiwon-JJW commented
컨플릭트 해결했습니다! 😅 감사합니다!

2021-03-25 12:39 UTC, wheejuni requested changes
우선 `Result` 클래스의 이름은 별 문제가 없어 보입니다. 👍 
그러나 리팩토링할 부분은 많이 있습니다. 하나씩 천천히 개선해나가면 될 것 같고요,
성공적인 리팩토링을 위해 어떤 점을 지켜야할지 알려드립니다. **꼭 지켜주세요.**

_원칙_

- 관성적으로 코딩하지 않는다. 잘못되거나 어색한 점이 없는지 항상 반문한다. 
    - 학습자 단계인 지금부터 관성적으로 코딩한다면 현업에선 어떻게 일할 것인가?
    - 내가 작성한 코드에 명쾌한 해설을 말할 수 있어야 한다. 근거를 가지고 코딩하라. 
- 기본적인 코딩 컨벤션은 누가 가이드하지 않아도 항상 유념하고 코딩한다.
- `Service` 에 과감히 더 많은 기능 맡겨본다. 
    - `Controller` 에 존재하는 `private` 메소드는 모두 걷어낸다. 

조금만 더 고생해주세요. 화이팅! 🥇

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
`Answer` 리스트 자체를 통째로 바꿔야 할 일이 자주 일어날까요? 자주 일어나지 않는 것이 아닌, 아예 일어나지 않도록 막아야 하는 건 아닐까요?
`addAnswer`, `updateAnswer` 등으로 안전하게 질문을 하나씩 추가할 수 있는 메소드를 작성하는 것이 관성적으로 세터를 만드는 것보다 훨씬 좋을 거라고 생각되네요.

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
네... 이 메소드는 여기 왜 있어야 하나요?

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        Question question = questionRepository.findById(id).orElseThrow(NoUserException::new);
어...네... 
질문이 없는데 `NoUserException` 을 던지는 이유는요?

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        questionRepository.save(question);
4단계까지 왔으니까 추가적으로 학습을 하나 진행해볼까요.
여기서 `questionRepository.save()` 없이 **변경 내용을 `Question` 에 반영하는 방법을 알아보세요.**

_힌트_

- `@Transactional`
- `EntityManager`
- `PersistenceContext`

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
`User` 에 있어야 할 메소드 같아요.

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        Answer answer = new Answer(user, question, contents);
이것도 `AnswerService` 안에서 수행될 수 있도록 해 주세요.
`AnswerService` 의 역할인 것 같아요.

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        return String.format("redirect:/question/%d", questionId);
덧셈 연산을 쓰는 것이 가독성 측면에서 더 좋고, 성능 면에서도 별 차이가 없습니다.

```suggestion
        return "redirect:/question/" + questionId;

2021-03-25 12:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        questionService.delete(question);
`QuestionService` 에서 `id` 와 `user` 파라메터를 받아서 삭제 가능 여부를 알아본 다음,
삭제가 가능하거나 불가능하다면 `Result` 객체를 리턴하거나,
기타 예외가 발생했다면 `exception` 을 던지는 구조로는 안될까요? 
컨트롤러에서 서비스를 두 번이나 호출할 필요는 없는 로직으로 보입니다.

2021-03-25 22:53 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        Answer answer = new Answer(user, question, contents);
@Jiwon-JJW 파라미터 session도 service에 넣으려면 좀 생각을 해봐야겠네용..

2021-03-28 08:21 UTC, wheejuni commented
@Jiwon-JJW @kyu-kim-kr 안녕하세요. 아직 수정중이신가요?

2021-03-28 11:49 UTC, Jiwon-JJW commented
> @Jiwon-JJW @kyu-kim-kr 안녕하세요. 아직 수정중이신가요?

안녕하세요! 현재 update 부분에서 Repository에 save하지 않고 사용하는 것을 구현하는 것에 막혀서 아직 수정중입니다 ㅜㅜ 내일까지 재 리퀘스트 드릴 수 있도록 하겠습니다..!

2021-03-29 06:03 UTC, Jiwon-JJW commented
안녕하세요! 리뷰해주신 사항에 대하여 최대한 수정하여 재 pr 드렸습니다! 감사합니다!

2021-03-30 00:23 UTC, wheejuni approved these changes
👍

2021-03-30 00:23 UTC, merged