[K] step6. 페이지 나누기
codesquad-members-2021/spring-boot-qna pull request #117
Opened 2021-03-24 10:16 UTC by PizzaCola-K

[배포 주소](https://safe-waters-28423.herokuapp.com/)

TDD는 어떻게 해야할 지 감을 못잡아서 하지 못했습니다.

Page의 전체 페이지와 현재 접근하는 페이지만 정해지면 Pagination의 모양을 결정할 수 있습니다. 그러므로, QuestionController의 list 메소드에서 Model에 Page 객체와 현재 접근하는 페이지을 Model에 담아 View로 보내면, handlebars에서 질문 목록 html을 추가합니다. 또한 CustomHandlebarsHelper에서 Pagination을 만들어냅니다.

그외 #92 에서 코멘트 남겨주셨던 것을 최대한 반영하였습니다.

1. DateTimeFormatter 변수의 이름

"yyyy-MM-dd HH:mm" 라는 포맷의 이름을 좀 더 명확하게 드러내고 싶었는데, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)은 이런 형태의 포맷 모두를 지칭하는 포맷이라 좋은 이름이 생각나지 않아 그냥 단순한 이름으로 수정하였습니다.

2. Question.addAnswer()

JPA에 지식이 부족해서 Question과 Answer 사이에 cascade 가 없는데도 불구하고 동작하는 것 때문에 Mapping 사이에서 cascade 옵션을 무엇을 줘야할 지 모르겠습니다.

[Best Practices for Many-To-One and One-To-Many Association Mappings](https://thorben-janssen.com/best-practices-many-one-one-many-associations-mappings/)

에, 5번 Implement helper methods to update bi-directional associations 과 같이 Question.addAnswer(Answer)로 수정해서 내부 list에 추가하며 answer와 question 사이 관계를 맺었습니다.

그런데 ApiAnswerService에서 create할 때 JPA에 반영된 Answer를 JSON 형식으로 반환해줘야 해서, Question의 OneToMany cascade 는 아닌 것 같고... 아직 이해가 부족합니다.

리뷰 잘 부탁드립니다.

2021-03-26 08:45 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/handlebarsHelper/handlebarsHelper.java
> +    public CharSequence questionPagination(Page<Question> questions, int pageNumber, Options options) {
저는 Util로 처리해서 그러는데 혹시 Options 매개인자로 받으신 이유를 여쭤봐도 될까요?

2021-03-26 10:57 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/handlebarsHelper/handlebarsHelper.java
> +    public CharSequence questionPagination(Page<Question> questions, int pageNumber, Options options) {
handlebars helper 기능 써보다가 뭐가 안되서 결국은 사용 안하고 넘어갔어요.

2021-03-26 11:19 UTC, wheejuni requested changes
마지막 단계까지 잘 구현하셨고, 수고 많으셨어요. 👍 
리뷰 요청 메세지도 잘 읽어보았고, 저도 추가 질문이 있습니다.
인라인 코멘트로 추가 질문을 남겨봤으니 댓글 부탁드려요.

2021-03-26 11:19 UTC, wheejuni commented on src/main/java/com/codessquad/qna/handlebarsHelper/CustomHandlebarsHelper.java
> +        int PAGE = 5;
상수라면 메소드 밖, 클래스 상단으로 끌올해주세요.

2021-03-26 11:19 UTC, wheejuni commented on src/main/java/com/codessquad/qna/handlebarsHelper/CustomHandlebarsHelper.java
> +                    .append("</a></li>");
네, 좋은데요...
`.html` 안에서도 HandleBars가 제공하는 기능으로 충분히 구현 가능한 범위였을 것 같아요.
가급적이면 자바 코드로 html을 생성하거나 다루는 구현은 자제해주세요. 우선 가독성이 굉장히 떨어지고요, FE-BE 협업의 측면에서도 유지보수가 굉장히 어려워집니다(아무리 뷰 템플릿을 사용한다 하더라도 마크업을 외부 개발조직이나 마크업 전문가에게 공급받고, 그것을 복붙해서 뷰 템플릿을 구성하는 경우가 굉장히 흔합니다). 
이번에는 새로운 피쳐를 학습했다는 측면에서 의미를 찾도록 하고, 앞으로는 가급적이면 뷰 파일 안에서 해결책을 찾아주세요!

2021-03-26 11:19 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        question.addAnswer(answer);
질문하신 부분이 이 부분인가요? 그런데 JSON으로 데이터가 내려가는 것과, `cascade` 설정간에 어떤 관계가 있는지 궁금해요.
만약 JSON 표현을 위한 필드 구성이 따로 필요하다면 `AnswerDto` 와 같은 클래스를 다시 작성하는 것은 어떨까요?

2021-03-28 04:05 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/handlebarsHelper/CustomHandlebarsHelper.java
> +        int PAGE = 5;
앗 그렇네요.

2021-03-28 04:05 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/handlebarsHelper/CustomHandlebarsHelper.java
> +                    .append("</a></li>");
템플릿은 최대한 유지하면서 모델에 데이터를 담아서 구성하는 것이 더 좋다는 말씀이시군요.

제가 이렇게 작성했던 이유는 다음과 같습니다.

페이지 목록은 전체 페이지 갯수와, 현재 접근하는 페이지 이 두 가지가 있으면 목록을 만들어낼 수 있습니다. 여기서 컨트롤러에서 Page 객체와 현재 접근하는 페이지 넘버를 갖고있으니, 페이지 목록을 만드는 것은 View에서 담당하는 것이 좋겠다는 생각이었습니다.

그런데 템플릿을 형태를 유지하면서, Model에 페이지 목록의 정보를 담은 Pagination 객체를 넘기는 방법이 말씀대로 좀더 가독성도 좋고, 의미하는 바가 명확한 것 같습니다. 이것은 수정하겠습니다.

2021-03-28 04:06 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        question.addAnswer(answer);
아 이건 제가 이해를 잘못했습니다. Question에서 Answer로 OneToMany 관계를 갖고 있고, 이를 반영하려면 questionRepository.save(question)을 불러서 persist 하거나 merge 해야한다고 이해하고 있었습니다. 그렇게 되면  ApiAnswerService에서 Persist Context에 반영된 Answer를 반환하는 방법이 없다고 생각했습니다.

그런데 Answer에서 Question으로 ManyToOne 관계가 있으니, answerRepository.save(answer)만 불러도 question으로 영속성이 전파될 수 있는 것을 잊고 있었습니다. 이 부분은 제가 잘못 이해하고 질문한 것입니다.

JSON 표현이나 기타 등등을 위해서 DTO를 사용하는 것은 좋은 것 같습니다. Entity 객체에 JsonProperty 같은 것이 너무 덕지덕지 붙어있는데 기능을 분리하는 면에서는 좋을 것 같습니다. 근데 아직까지 잘 몰라서 사용하고 있지 않았습니다.

2021-03-28 04:07 UTC, PizzaCola-K commented
Pagination 부분에서 helper에서 html 구성하는 부분을 수정하였습니다.

리뷰 감사드립니다.

2021-03-28 08:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        question.addAnswer(answer);
@PizzaCola-K 저도 생각하신것처럼 Entity에 표현 계층에서의 정보가 너무 많이 묻어있는 구현은 그리 선호하지 않습니다.
말씀처럼 그럴 바에야 DTO를 따로 설계하는 것이 낫죠. 좋네요.

2021-03-28 08:23 UTC, wheejuni approved these changes
👍

2021-03-28 08:23 UTC, merged