[마르코 & Woody] Mission3 PR 요청입니다.
codesquad-members-2021/spring-boot-qna pull request #118
Opened 2021-03-25 09:00 UTC by 95degree

안녕하세요. 이번 미션은 [마르코& Woody] 페어프로그래밍으로 진행했습니다.
- 최대한 요구사항에 맞춰서 기능을 구현하였습니다!!

### 트렌젝션 어노테이션 위치 - 고민을 많이 했습니다..! 
- 일단, service 계층의 클래스에 전체적으로 `@Transactional(readOnly = true)` 를 적용했습니다
- 그리고 DB에 즉시 반영되어야 한다고 생각되는 메소드들(update, delete 등)은 `@Transactional`을 적용했습니다.
- 아직 어디에 적용해야하는지 확신이 없는데, 혹시 틀린 부분이나 조언해주실 부분이 있다면 말씀해주세요!!

### 👬 함께 짝 프로그래밍으로 구현한 내용

#### 1. 질문 수정하기
- update() 메소드 구현
  - QuestionController
  - QuestionService

#### 2. User와 Question 연결
- @ManyToOne 매핑
  - Question과 User 간 N : 1 관계 형성
- toEntity() 생성
  - sessionedUser 정보를 추가해주는 로직과 Dto에서 Entity로 변환해주는 로직을 toEntity()로 통합

#### 3. 질문 삭제하기
- delete() 메소드 구현
  - QuestionController
  - QuestionService

#### 4. 리팩토링
- id 네이밍
   - 어떤 Entity의 id값인지 드러나도록 수정
- 공통 url 묶기 @RequestMapping
   - AnswerController에서 "/questions/{questionId
- @Autowired 삭제
  - Service 클래스에서 @Autowired 삭제

2021-03-26 00:39 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 💯 
쭉 둘러보며 피드백을 남겨 보았는데요, 이해되는 부분은 반영해주시고,
추가 질문이 필요하다면 언제든지 던져주세요!

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/HttpSessionUtils.java
> +        return sessionedUser != null;
한 줄로 줄일 수도 있을 것 같은데요, 의도하신 구현인가요?

```suggestion
        return sessino.getAttribute(USER_SESSION_KEY) != null;

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable long questionId, AnswerDto answerDto, HttpSession session) {
두 가지 제안이 있습니다. 
1. `AnswerDto` 로 `createAnswer` 해도 되나요? 답변을 작성할 때 필요한 컨텐츠와, 답변을 보여줄 때 필요한 컨텐츠가 다를 수도 있을 텐데요.
2. `questionId` 도 `AnswerDto` 에 갖고 있으면 안되나요? 답변 정보가 질문에 대한 정보 없이 독립적으로 존재하긴 어려울 것 같아요.

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.create(answerDto, question, sessionedUser);
위 두 가지 사항이 반영된다면 이 부분도 간단하게 고칠 수 있을 것 같군요.

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String deleteAnswer(@PathVariable long questionId, @PathVariable long answerId, HttpSession session) {
단순히 리디렉션만 만들어주기 위해서 `questionId` 를 받는건가요? 그러면 요청자가 이 부분만 변조하면 얼마든지 자신이 원하는 질문으로 넘어갈 수 있는 거군요.
물론 지금은 별 로직이 없어서 괜찮지만 나중엔 일종의 보안 허점이 될 수도 있습니다.
`answerService.delete()` 에서 리디렉션으로 넘어갈 `questionId` 를 리턴할 수는 없는 건가요? 그럴 수 있을 것 같네요.

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.save(question);
여기도 이 세 줄은 `QuestionService` 에서 수행돼야 할 것 같군요.

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.delete(question);
여기도요. 왜 `questionService.delete(id, sessionedUser);` 로 하지 않는거죠?

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private String time;
`time` 인데 `String` 타입이군요. 이렇게 선택한 이유는요?

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/dto/AnswerDto.java
> +    private Question question;
`QuestionDto` 가 있음에도 `Question` 을 그대로 받고 있네요. 이유가 있나요?

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/dto/AnswerDto.java
> +    }
`Answer` 엔티티에서 바로 이 객체로 올 수 있는 스태틱 메소드도 하나 있으면 설계상에 이점이 생기지 않을까요?

2021-03-26 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
여기엔 `@Transactional` 없어도 될까요?

2021-03-27 08:46 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
허헣..ㅠㅠ 짚어주신 부분이 정상적으로 작동하지 않아서 `@Transaction` 어노테이션 위치를 아래와 같은 기준으로 수정했습니다..!!

- CRUD 서비스 메소드 → `@Transactional`
- 조회와 관련된 서비스 메소드 →  `@Transactional(readOnly = true)`

2021-03-27 08:46 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/dto/AnswerDto.java
> +    }
'**Entity → DTO 변환 책임**을 가진 스태틱 메소드를 Answer 엔티티 클래스 내부에 아래와 같이 만들면 좋을 것 같다'
라는 말씀으로 이해하고 메소드를 추가하려고 했지만 AnswerDto를 제거하는 과정에서 실제 구현은 못하게 되었습니다..!ㅠㅠ 하지만! 좋은 포인트 짚어주셔서 감사드려요! (혹시 잘못 이해한거라면 말씀해주시면 감사드리겠습니다!)
```java
// Answer 클래스
public static AnswerDto of() {
   // ...
   return new AnswerDto();
}
```

2021-03-27 08:57 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/dto/AnswerDto.java
> +    private Question question;
앗 Entity와 달리 AnswerDto는 필드 설정이 자유로우니까(DB 눈치(?)를 안봐도 되니까요!),
1. **필요한 정보만 최소한으로** 가지고 있는게 좋을 것 같다는 점에서 
2. 그리고 Entity 정보는 최대한 사용하지 않는게 좋다는 점에서

Question 대신 questionDto 혹은 questionId 정보만 가지고 있게 해도 될 것 같네요! 
생각하지 못했던 부분이었습니다! 감사드려요🙇‍♀️

2021-03-27 09:07 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private String time;
LocalDateTime 포멧팅 처리가 미숙해서 String 타입으로 저장해놓았었습니다..!

####  HandlebarHelper 클래스 구현
- 현재는 `@HandlebarsHelper` 어노테이션을 추가한 `HandlebarHelper` 클래스 아래 포멧팅을 담당하는 메소드를 만들어 적용해주었습니다.

####  html에 적용
- 구현한 메소드를 적용해서 ( `{{formatDateTime time}}` ) 포멧팅된 시간 데이터를 출력합니다!

2021-03-27 10:32 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable long questionId, AnswerDto answerDto, HttpSession session) {
### 1번
1번은 createAnswer()에서는 AnswerDto가 아니라 Answer 생성에 필요한 다른 타입으로 받아와야하는게 아닌가? 라는 말씀으로 이해하고서 AnswerDto 타입 대신 String 타입 contents를 받아오게끔 수정했습니다!

```java
@PostMapping
    public String createAnswer(@PathVariable long questionId, String contents, HttpSession session) {
        User sessionedUser = HttpSessionUtils.getUserFromSession(session);
        answerService.create(sessionedUser, questionId, contents);
        return "redirect:/questions/" + questionId;
    }
```
### 2번
이 부분은 정확하게 이해하지 못했습니다😂 죄송합니다..!ㅠ

 - 일단 2번 자체는, `AnswerDto`가 어떤 질문과 연관이 있는지를 questionId 정보를 통해서 알 수 있도록 하는 것이 좋겠다라는 말씀으로 이해했습니다..! 
 - 하지만 1번을  'AnswerDto 대신 다른 타입 파라미터로 받는게 좋을 것 같다'로 이해해서 그런지 이를 반영하고 나면 `AnswerDto`를 더 이상 사용하지 않아서 2번 내용을 적용할 수 없게 됩니다...!
 - 제가 뭔가 말씀하신 의도를 정확하게 이해하지 못한 것 같네요💦

2021-03-27 10:49 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.create(answerDto, question, sessionedUser);
주신 두 가지 제안을 잘 이해하지 못해서 그런지.. 코드를 수정해도 코드 복잡도는 이전과 비슷합니다ㅠ

```java
@PostMapping
    public String createAnswer(@PathVariable long questionId, String contents, HttpSession session) {
        User sessionedUser = HttpSessionUtils.getUserFromSession(session);
        answerService.create(sessionedUser, questionId, contents);
        return "redirect:/questions/" + questionId;
    }
```

최대한 말씀하신 부분을 이해하고서 수정하면 어떻게 될까를 생각해보았는데요..!

(1번은 적용하지 않고 answerDto를 살리는 방향으로 생각해보았을 때) 
만약 말씀하신 2번 내용대로
 1. questionId를 AnswerDto에 넣고
 2. answerService()를 호출하는 형태였으면 
 
아래와 같이 create()의 메소드 파라미러를 하나 줄일 수 있을 것 같습니다!!
```java
answerDto.setQuestionId(questionId); // 👈👈 조금 걸리는 부분이긴 하지만, 
                                      // questionId를 `@PathVariable`로 받아오기 때문에 setter를 사용하지 않고서
                                      // answerDto에 questionId를 넣어줄 다른 방법이 떠오르지 않네용..!
answerService.create(sessionedUser, answerDto);
```

저의 짧은 지식으로 최대한 이해해보려고 했는데 맞는지 모르겠네용..!😂

2021-03-27 11:28 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String deleteAnswer(@PathVariable long questionId, @PathVariable long answerId, HttpSession session) {
그런 부분은 잘 생각하지 못하고 진행해왔네요..😂
코멘트 주신대로 

- 리디렉션 url에 사용되는 `questionId` 정보를 `@PathVariable`에서 바로 가져오는 대신
-  `answerService.delete()` 메소드에서 delete한 answer 객체에서 가져온 `questionId`를 리턴하는 방식으로 변경하였습니다..!

---
### get().get() → 네이밍 고민..!
(사실 이건 그렇게 중요한 부분은 아니지만 그래도.. 적어보았습니다..!)

주신 코멘트 대로 수정하는 과정에서 뜻하지 않게 네이밍에 대한 고민을 하게 되었는데요😂, 경위는 아래와 같습니다..ㅠ
 1. delete에서 questionId를 리턴하도록 만들다 보니 아래와 같은 코드가 나오게 되었습니다..!

```java
public long delete(long answerId, User user) {
        // ..
        return answer.getQuestion().getId();
    }
```
2. get().get() 방식이 거슬려서 Answer 클래스 내부에서 questionId를 리턴하는 메소드를 만들어주었습니다..! 
문제는 이 메소드를 만들고 프로그램을 실행하면  Answer 클래스에 questionId 필드가 없다는 에러 메시지가 뜹니다.. 됴륵

```java
// Answer 클래스 내부
 public long getQuestionId(){
        return question.getId();
    }
```
뭔가 내부적으로 get{필드명}이라고 인식을 해버려서 에러가 발생한 것 같은데 좋은 네이밍이 떠오르지 않아서 일단은 get().get() 못생긴 코드를 그대로 두었습니다ㅠㅠ 

혹시..  좋은 네이밍 아이디어 있으신 분.. 연락주세요..☎

2021-03-27 11:29 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.delete(question);
그러네용... questionService를 계속 불러서 수행할거라면 차라리 서비스 내부로 해당 작업을 옮기는 것이 훨씬 좋아보여서 말씀하신대로 수정하였습니다!

2021-03-27 11:30 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.save(question);
해당 로직을 `QuestionService` 내부로 옮겨놓았습니다!!

2021-03-27 11:33 UTC, jihye-woo commented
### PR 리뷰 수정
(크게 리뷰를 통해 수정한 내용은 다음과 같습니다!!)
- **LocalDateTime 포멧팅 방식 변경**
  - 커스텀 HandlebarsHelper 구현 후 이를 적용하여 time 정보 수정
  - 엔티티에서는 포멧팅 되지 않은 LocalDateTime 정보를 가지고 있도록 수정
- **리디렉션 시 사용하는 questionId는 서비스 계층에서!**
  - Controller 메소드에서 `@PathVariable`을 통해서 받아온 questionId X
  - Service 계층에서 가지고 온 questionId 정보를 가지고 리디렉션
- **`@Transactional` 어노테이션 서비스 클래스에 추가**
  - CRUD 서비스 메소드 → `@Transactional`
  - 조회와 관련된 서비스 메소드 → `@Transactional(readOnly = true)`
- **문제아 AnswerDTO 삭제**
  -  AnswerDto를 삭제

--- 
### 그밖의 수정사항

- 양방향 매핑으로 수정
- cascade 옵션으로 question과 answer가 변경사항을 반영할 수 있도록 함
```java
@OneToMany(mappedBy = "question", cascade = CascadeType.ALL)
    private List<Answer> answers = new ArrayList<>();
```
- html에서 답변 개수 정보를 출력
  - question → answers  → length
  - {{#questions}} ...  {{answers.length}} ... {{/questions}}

2021-03-28 08:19 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.create(answerDto, question, sessionedUser);
@jihye-woo 이제 이해하신 것 같군요.

2021-03-29 03:49 UTC, wheejuni approved these changes
👍

2021-03-29 03:49 UTC, merged