[MJ]미션5: XHR과 AJAX
codesquad-members-2021/spring-boot-qna pull request #119
Opened 2021-03-25 09:22 UTC by MJbae

안녕하세요~ MJ입니다. 이번 리뷰도 잘 부탁드립니다!

[배포] ([https://spring-qna.herokuapp.com/](https://spring-qna.herokuapp.com/))

**변경사항**

1. AJAX 방식으로 답변 추가, 삭제 기능 구현
2. 답변 개수 카운팅 기능 구현
3. 도메인 객체의 공통 부분을 아우르는 부모 클래스 생성
4. Swagger2 활용하여 API 문서화
5. CRUD 기능에 대한 RESTful API 구현
    → ApiAnswerController, APIQuestionoController

2021-03-26 23:57 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
전반적으로 잘 구현되었습니다. 구조상 크게 변경할 부분은 없을 것 같고요, 
다만 서비스 레이어와 컨트롤러 레이어가 역할을 분담하는 방식에 대해 피드백을 하나 남겨 보았습니다. 
한번 읽어보시고요, 추가 질문이 있다면 남겨주시거나, 코드에 반영해주시면 감사하겠습니다. 💯

2021-03-26 23:57 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @JsonProperty
JSON 필드명이 다르게 매핑되어야 하거나 기타 특별한 필요가 있는 경우를 제외하고는,
모든 필드에 `@JsonProperty` 를 붙이는것보다는, 오히려 JSON 직렬화에서 제외되어야 할 필드에 대해 `@JsonIgnore` 를 붙이는 등의 방향으로 대응하시는 것이 좋을 듯합니다.

2021-03-26 23:57 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
결국 새로 업데이트될 부분은 `contents` 가 유일한 것 같네요.
그렇다면 굳이 `Answer` 를 통째로 파라메터로 받을 필요가 있냐는 생각도 듭니다.
제 생각엔 `Answer` 를 업데이트하는데 필요한 정보만 담은 별도의 클래스가 작성된다면, `Controller` 와 `Service`, 그리고 이 엔티티에 이르기까지 유용하게 사용되리라 생각되네요.

2021-03-26 23:57 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer update(Answer targetAnswer, Answer newAnswerInfo, User sessionUser) {
_서비스가 더 많은 기능을 해야 한다_ 고 꾸준히 피드백 드리고 있는데요, 이 메소드에서 `targetAnswer` 라는 `Answer` 타입의 파라메터를 받는 것도 같은 관점에서 볼 수 있을 것 같습니다.

컨트롤러가 이 메소드를 호출하는 관점에서, 이 파라메터를 만들어주기 위해 `Service` 클래스를 한번 더 호출해야 하는 것도 조금은 어색하고, 특히 영속성 컨텍스트의 관점에서 서비스 레이어를 벗어난 객체를 다시 한 번 서비스 레이어로 불러들이는 것은 불필요한 사이드 이펙트를 초래할 여지도 있습니다(지금은 스프링 MVC의 기본 설정에 의해 컨트롤러 레이어까지 영속성 컨텍스트가 확장되어 있어 별 탈이 없는 것입니다). 

제가 보기에 `targetAnswer` 는 답변의 ID, 즉 `Long` 타입의 파라메터 하나로 충분할 것 같고, 뒤의 `newAnswerInfo` 도 사실은 `Answer` 의 전체 정보가 필요한 것이 아닌 `contents` 만 필요한 것입니다. 이 메소드에서 온전히 사용되는 파라메터는 `sessionUser` 가 유일한 것 같습니다.

새로운 답변 내용과, 내용이 바뀌어야 할 답변의 ID를 담은 `AnswerUpdateDto` 와 같은 클래스를 구상해보시는 건 어떨까요?

2021-03-26 23:57 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
이것도 나쁘지 않지만, `decrease` 를 했다 하더라도... 그 `decrease` 의 대상이 된, 그러니까 이미 삭제된 `Answer` 가 이 객체의 `List<Answer>` 에는 여전히 남아있을 것이란 점도 생각하셔야 합니다.

그래서 저라면 이 메소드의 이름을 `deleteAnswer` 정도로 바꾼 후, `List<Answer>` 에서 [remove()](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-java.lang.Object-) 를 호출하여 리스트에서 삭제 대상 답변을 빼내는 작업도 병행할 수 있도록 파라메터로 `Answer` 를 받을 것 같습니다.

2021-03-27 00:35 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @JsonProperty
아하! 그렇군요 반영하겠습니다~

2021-03-29 05:50 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
decreaseCountOfAnswers의 메소드명을 deleteAnswer로 변경했습니다. 
deleteAnswer의 로직을 다음과 같이 변경했습니다. 
1. countAnswers를 차감
2. List<Answer> answers의 요소에 대해 soft delete하는 방향으로 수정했습니다.

제안하신 방법처럼 List<Answer> answers에 대해 remove()를 적용하여 완전삭제할 수 있지만 soft delete에 대한 요구사항이 있어서 위와 같이 수정했습니다. 혹시 제가 놓치고 있는 부분이 있을까요?

2021-03-29 05:52 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
@MJbae `cascade` 설정을 빼면 `.remove()` 해서 참조가 제거되어도 DB엔 남아있을 것 같네요.

2021-03-29 06:58 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
그렇군요! 말로만 듣던 DTO가 왜 필요한지 이제 이해가 되네요! 그런데 코드에 적용하려니 너무 막막한 감이 있습니다... 추후에 충분한 시간을 갖고 개념부터 제대로 학습하고 적용해보겠습니다 :)

2021-03-29 07:00 UTC, MJbae commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer update(Answer targetAnswer, Answer newAnswerInfo, User sessionUser) {
검색하면서 찾아보니 DTO가 어떤 건지는 감이 옵니다. 그런데 감만으로는 코드에 적용이 잘 안되네요... 특히 영속성 컨텍스트가 키워드인거 같은데 아무래도 스프링 MVC에 대한 기본이 제대로 닦여있지 않아서 그런 것 같습니다. 추후에 제대로 학습해서 적용해보겠습니다 :)

2021-03-30 00:24 UTC, merged