[아이작] 미션5: XHR과 AJAX
codesquad-members-2021/spring-boot-qna pull request #120
Opened 2021-03-25 12:49 UTC by isaac56

안녕하세요. 아이작입니다.

미션5로 AJAX를 이용해 답변을 추가하고 삭제하기 구현해보았습니다.
대부분 자바지기님의 강의 동영상을 보며 따라했습니다.

기존 강의:
 - 강의에서는 Answer의 DELETE부분에서 Result를 반환합니다.
 - ajax의 success에 등록된 함수에서 Result.valid 여부에 따라 delete성공 여부를 판단하고 페이지를 수정합니다.

강의와 다르게 구현한 점:
 - 저는 delete가 불가한 상황을 판단하여 exception을 throw하도록 하였습니다.
 - RestController에서 발생하는 Exception만 처리하는, ApiGlobalExceptionHandler를 생성하였습니다.
 - ApiGlobalExceptionHandler에서는, Exception에 따라 ResponseStatus를 설정하고 에러메세지로 String을 반환합니다.
 - ajax의 error에 등록된 함수에서 responseText를 경고창으로 보여줍니다.

이미 Controller 내부에서도 Exception을 발생시키고 handler에서 처리하는 방식이었습니다.
RestController도 기존과 비슷한 방식으로 설계하고 싶었는데, 이게 자주 쓰는 방법인지는 잘 모르겠습니다😅.

항상 좋은 리뷰 감사합니다.
이번에도 잘부탁드립니다.

2021-03-27 10:02 UTC, ksundong requested changes
안녕하세요! 아이작! 리뷰어 Dion입니다!!
미션 5단계 까지 수행해주시느라 고생하셨습니다!
AJAX 처음 배울 때, 저는 되게 이해 안갔었는데, 이해가 가셨는지 모르겠네요 ㅎㅎ
아무튼, 구현을 하는데 많은 고민을 하셨을거라고 생각되는 코드였습니다!

## 웹 애플리케이션 관련 리뷰

- 이전 단계의 요구사항인, 회원정보 수정시 비밀번호 인증기능이 없네요.
- 회원 프로필의 사진이 출력되지 않네요.
- 댓글을 달면 입력 필드가 비워지지 않네요.
- 질문목록에 답변 개수가 노출되지 않네요.

## 코드 관련 리뷰

- 대부분 깔끔했고, 제가 코드를 보면서 가졌던 의문점을 코멘트 해뒀어요. 참고해주세요~

고생하셨습니다. 다음 단계를 진행하기 전에, 웹 애플리케이션 관련 요구사항을 고쳐봅시다!
궁금하신 점이나, 도움이 필요하신 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분은 코멘트 남겨주세요!

2021-03-27 10:02 UTC, ksundong commented on build.gradle
> +    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
- swagger를 사용하는 이유는 무엇인가요?
- compile과 implementation의 차이에 대해서 학습해봅시다.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/QnaApplication.java
> +	public Docket newsApi(){
```suggestion
	@Bean
	public Docket newsApi() {
```
왜 newsApi인가요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
>      @Autowired
`@Autowired`를 제거해줄 수 있는데 왜 제거해줄 수 있는지 학습해보세요~

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +    public Answer create(@PathVariable long questionId, String contents, HttpSession session) {
보통 REST API는 생성 요청에 대한 응답으로 201응답 코드를 주는데요.
- 201이 의미하는 바는 무엇인지
- Spring에서 이 응답코드를 어떻게 반환해 줄 수 있는지
학습해보세요~

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/AbstractEntity.java
> +public class AbstractEntity {
보통 클래스에는 `Abstract`같은 키워드를 적어주는 것은 안티패턴입니다.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +        return Result.OK();
꼭 그 행동에 대한 결과를 반드시 반환해줄 필요는 없습니다.
삭제요청의 경우 204응답을 주곤하는데요. 이 역시 학습해보시죠!

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/AbstractEntity.java
> +    @Id
```suggestion
    private static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    
    @Id
```
- dateTimeFormatter라고 클래스의 이름을 명시해주기보다는 다른 이름을 고민해봅시다.
- 또한 이것이 여기 있어야 하는지도 생각해봅시다.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @JsonProperty
`@JsonProperty`가 필드마다 다 들어갔는데, 이것을 이렇게 작성해주신 이유가 무엇인가요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
>  @Table(name = "ANSWER")
테이블 명을 직접 정의해주신 이유가 있나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @JsonIgnore
`@JsonIgnore`를 사용해주신 이유가 있나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Result.java
> +public class Result {
이 클래스가 필요할까요~?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return this.getId().equals(user.getId());
getter를 사용한 방법으로 바꿔주신 이유가 있나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/AlreadyExistException.java
> +    public AlreadyExistException(String msg) {
가급적이면 빈 생성자를 하나 만들어서 메시지가 없더라도 생성할 수 있도록 해줍시다.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/NotAuthorizedException.java
> +        super(msg);
`msg` 보다는 `message`가 좋습니다.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/exceptionHandler/ApiGlobalExceptionHandler.java
> +        return "로그인이 필요합니다.";
이것은 왜 직접 메시지를 작성해주셨나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/exceptionHandler/ApiGlobalExceptionHandler.java
> +    public String NotAuthorizedException(NotAuthorizedException ex) {
사실 HTTP의 UNAUTHORIZED는 Unauthenticated의 의미와 비슷합니다.
Mozlia 쪽 문서가 이에 대해서 설명해두었으니 참고해주세요.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
>  public interface AnswerRepository extends GenericRepository<Answer, Long> {
GenericRepository가 뭔가 하구 찾아봤네요 ㅎㅎ
필요한 부분만 상속해주셨겠죠?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        }
이게 발생한 경우가 있나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        }
저라면 null이 리턴됐다면 그냥 리턴해줄 것 같아요.
아마 실패하면 제 생각엔 예외를 뱉을 것 같은데요.

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return deleted;
의미 단위로 개행해주는 습관도 들여봅시다.
또한, isWriter에서 그냥 예외를 처리해줘도 되지 않을까요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return deleted;
지워진걸 반환해주는 이유가 있나요?

2021-03-27 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new AlreadyExistException(newUser.getUserId() + " 인 Id가 이미 존재합니다.");
예외처리 좋은데, 문자열 부분을 예외 안으로 넣는 방향도 고려해보세요~

2021-03-27 10:02 UTC, ksundong commented on src/main/resources/static/js/scripts.js
> +    var queryString = $(".answer-write").serialize();
ES6 문법을 한 번 활용해봅시다.

2021-03-27 10:04 UTC, ksundong commented
> 이미 Controller 내부에서도 Exception을 발생시키고 handler에서 처리하는 방식으로 구현하고 있었습니다.
> RestController도 비슷한 방식으로 설계하고 싶었는데, 이게 좋은 방법인지는 모르겠습니다😅.

저는 좋은 시도라고 생각됩니다~ 👍👍

2021-03-29 06:03 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return deleted;
의미 단위로 개행하는 습관 연습해보겠습니다~!
isWriter에서 예외를 처리하는 것도 생각해봤습니다.
삭제, 수정 같은 서비스의 기능에서 권한없음 예외를 처리하는게, 의미상 맞는 것 같아서 이렇게 구현했습니다.
코드 중복이 많아진다면 isWriter에서 예외를 처리하는 게 더 좋을 것 같기도 합니다. 감사합니다

2021-03-29 06:18 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +    public Answer create(@PathVariable long questionId, String contents, HttpSession session) {
201은 요청을 성공적으로 처리해서 새 리소스를 작성했다는 응답이군요.
@ResponseStatus 어노테이션의 value값을 이용해 응답코드를 반환할 수 있다는 걸 알았습니다.

2021-03-29 06:36 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +        return Result.OK();
오 void 메서드는 제대로 동작을 안 하길래 찜찜한 마음으로 Result를 반환 했는데, 이런 방법이 있군요
감사합니다~!

2021-03-29 06:42 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @JsonProperty
RestController에서 Entity를 Json으로 반환할 때, 필드를 넣어준다고 명시하기 위해서 작성했습니다.
1. getter가 존재하면 자동으로 Json에 포함
2. @JsonProperty가 붙으면 getter가 없어도 Json에 포함
3. @JsonIgnore를 붙이면 getter가 있어도 Json에서 제외
이렇게 알고 있는데, 명시적으로 @JsonProperty를 붙여 관리하면 getter를 신경안써도 될 것 같아서 일일이 붙였습니다.😅

2021-03-29 06:48 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/Answer.java
>  @Table(name = "ANSWER")
따로 정의하지 않으면 JPA가 클래스명으로 테이블을 생성한다고 알고 있습니다.
정확히 기억은 안나지만, Entity 클래스명과 DB 키워드가 겹쳐서 테이블 생성 에러가 났던 적이 있습니다.
그 때부터 습관적으로 테이블 명을 직접 정의하고 있는데, 불필요한거 같아서 지우겠습니다.

2021-03-29 06:55 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @JsonIgnore
Answer 객체가 json으로 serialized될 때, 멤버 변수로 Question을 갖고 있습니다.
이 때, Question도 json으로 serialized될 때 멤버 변수로 Answer를 갖고 있으면 무한 참조가 일어나서 StackOverFlow가 발생했습니다.

임시방편으로 Question의 answers를 @JsonIgnore로 막아뒀습니다. ㅠㅠ

2021-03-29 07:00 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return this.getId().equals(user.getId());
중복 제거를 위한 리팩터링 후에, id는 AbstractEntity에 private으로 정의되어 있습니다.
AbstractEntity를 상속받은 User에서는 id에 직접 접근을 못하게 되어서 getter를 사용하게 되었습니다.

2021-03-29 07:08 UTC, isaac56 commented on src/main/java/com/codessquad/qna/exceptionHandler/ApiGlobalExceptionHandler.java
> +        return "로그인이 필요합니다.";
```javascript
function onError(xhr, status) {
    console.log("Error");
    console.log("xhr: " + xhr);
    console.log("status: " + status);
    alert(xhr.responseText);
}
```
ajax에서 요청이 실패하면, onError에서

2021-03-29 07:11 UTC, isaac56 commented on src/main/java/com/codessquad/qna/exceptionHandler/ApiGlobalExceptionHandler.java
> +        return "로그인이 필요합니다.";
앗 딱히 이유는 없고 미처 수정하지 못하고 놓친 부분 같습니다.
수정하도록 하겠습니다.

2021-03-29 07:18 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/Result.java
> +public class Result {
204응답을 알게 되어서, 필요없어졌습니다 ㅎㅎ 삭제하겠습니다

2021-03-29 07:29 UTC, isaac56 commented on build.gradle
> +    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
- swagger를 사용하면 api가 자동으로 문서화되어 제공되고, swagger-ui에서 api 테스트도 할 수 있는 유용한 도구라고 알고 있습니다.
- 일단 요구사항과 자바지기님 강의를 보며 따라하긴 했는데, 아직은 부족하여 진짜 필요한 시점이 되어야 알 것 같습니다.
<br>
- compile과 implementation의 차이는 <https://hack-jam.tistory.com/13>를 보고 학습하였습니다.
-

2021-03-29 07:44 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        }
저게 발생한 적은 없습니다
null은 꼭 처리해야할 것 같아서 저렇게 작성했는데, 알아서 예외를 뱉는다면 필요 없겠네요
감사합니다~!

2021-03-29 07:50 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return deleted;
추가나 수정할 때도 저장된 결과를 반환하다보니 일관적으로 지워진것도 반환하게 했습니다.
지금 생각하니 필요가 없을 것 같네요😅 void로 수정하겠습니다.

2021-03-29 08:00 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
>      @Autowired
spring 4.3 이후부터는, 생성자가 하나일 경우 @Autowired 없이도 자동으로 DI를 해주는 군요.
<https://docs.spring.io/spring-framework/docs/4.3.x/spring-framework-reference/htmlsingle/#beans-autowired-annotation>

2021-03-29 11:44 UTC, isaac56 commented
안녕하세요 Dion!
생각하거나 학습할 거리를 많이 던져주셔서 도움이 많이 되었습니다.
자세하고 친절한 코드리뷰 감사드립니다!

##웹 애플리케이션 관련 리뷰
- 이전 단계의 요구사항인, 회원정보 수정시 비밀번호 인증기능이 없네요.
  - 비밀번호 인증은 수정화면에서 기존 비밀번호와 일치하지 않으면 수정이 안되도록 막고 있습니다.
- 회원 프로필의 사진이 출력되지 않네요.
  - 기본 아이콘이 출력되도록 수정했습니다.
- 댓글을 달면 입력 필드가 비워지지 않네요.
  - 입력 필드 비워지도록 수정했습니다. 
- 질문목록에 답변 개수가 노출되지 않네요.
  - 답변 개수 노출하는 기능 추가했습니다.
  - 2개 이상의 Entity가 동시에 변경되게 구현해서 @Transactional 어노테이션 사용했습니다.
    (Answer 추가/삭제 시, Question의 countOfAnswer 증가/감소)

##코드 관련 리뷰
- 달아주신 코멘트에 답변 달아놨습니다.

감사합니다!

2021-03-30 10:12 UTC, ksundong commented on build.gradle
> +    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
- API 문서화를 하는 이유는 무엇일까요? 좀 더 깊이 공부해보시는 것도 추천해보겠습니다.
- compile과 implementation의 가장 큰 차이는 deprecated 되었는가? 아닌가?라고 생각합니다. 이후 제거될 기능은 사용하지 않는 것이 좋겠죠.

2021-03-30 10:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/QnaApplication.java
> +	public Docket newsApi(){
답변좀 해주세용~

2021-03-30 10:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +    public Answer create(@PathVariable long questionId, String contents, HttpSession session) {
충분하게 학습하셨네요.

2021-03-30 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +        return Result.OK();
제대로 동작을 안한다는 것은 어떤 의미일까용?

2021-03-30 10:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @JsonProperty
저는 일반적으로 getter를 사용하고, Json 직렬화가 필요없는 경우 Ignore 시켜주는 편입니다.
명시적으로 작성하는 것보다 암묵적으로 설정하는 것이 때론 괜찮을 때도 있습니다.
RoR의 철학 중 Convention over Configuration이라는 용어가 있는데요, 이것도 재미있으니 한 번 알아보세요~

2021-03-30 10:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
>  @Table(name = "ANSWER")
직접 정의해주는 것이 나쁘진 않습니다만, 명명규칙과 같이 가져가는 것이 좋겠죠~

2021-03-30 10:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @JsonIgnore
순환 참조는 참 어려운 문제죠 ㅎㅎ 고생하셨습니다.

2021-03-30 10:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return deleted;
그렇네요. 좋은 생각이에요.

2021-03-30 10:38 UTC, ksundong approved these changes
피드백 반영해주시느라 고생하셨습니다!
다음 단계 진행해볼까요!!

2021-03-30 10:38 UTC, ksundong commented on build.gradle
> +    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
spring boot에서는 spring validation starter를 제공해줍니다. 이걸 사용해보세요!

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +    public void delete(@PathVariable long questionId, @PathVariable long answerId, HttpSession session) {
👍

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +public class Answer extends CommonEntity {
Common보단 Base가 더 맞는 표현인 것 같아요.

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        this.question.decreaseAnswerCount();
이런걸 관리하는 클래스는 신중하게 선택해주어야 합니다.
많은 고민을 하셨겠죠?? 😊

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/CommonEntity.java
> +    private static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
dateTimeFormatter 말고 좋은 이름을 고민해봅시다. ㅎㅎ

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private Integer countOfAnswer;
이 필드는 null인 경우가 존재할까요?

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    @JsonIgnore
👍

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/UserAlreadyExistException.java
> +    public UserAlreadyExistException(String userId){
```suggestion
    public UserAlreadyExistException(String userId) {
```

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/UserNotFoundInSessionException.java
> +    public UserNotFoundInSessionException(String message){
```suggestion
    public UserNotFoundInSessionException(String message) {
```

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Transactional
혹시 어떤역할을 해주는지 알고 사용하신건가요?👍👍

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
>      public void deleteAnswer(long answerId, User tryToDelete) {
User tryToDelete보다 다른 이름을 고민해보는게 어떨까요?

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +            throw new NotFoundException(answerId+"번 Answer는 이미 삭제되었습니다.");
```suggestion
            throw new NotFoundException(answerId + "번 Answer는 이미 삭제되었습니다.");
```

2021-03-30 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        if(answer.isDeleted()){
```suggestion
        if(answer.isDeleted()) {
```
포매팅을 꼭 해주세요

2021-03-30 10:51 UTC, isaac56 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private Integer countOfAnswer;
Question 새로 생성시 null로 들어오고 있었네요 ㅠㅠ
```java
@JsonProperty
@Column(nullable = false, columnDefinition = "int default 0")
private Integer countOfAnswer = 0;
```
으로 수정해서 null이 안들어오게 고쳤습니다

2021-03-30 10:53 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        if(answer.isDeleted()){
import.sql 파일 수정한다고 잠시 save action을 끄고 수정했네요.
알려주셔서 감사합니다~!

2021-03-30 11:06 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/api/ApiAnswerController.java
> +        return Result.OK();
제가 204 응답이 아니라 200응답을 주고 있었습니다.
200 응답과 함께 void를 리턴하면 ajax에서 error로 인식하더라구요.
자꾸 ajax에서 parseerror가 나면서 onSuccess가 아닌 onError가 호출되어서 Result를 반환하게 했었습니다.

2021-03-30 11:10 UTC, isaac56 commented on src/main/java/com/codessquad/qna/QnaApplication.java
> +	public Docket newsApi(){
앗 죄송합니다 못보고 지나쳤네요

일단 자바지기님 강의를 보고 따라한거긴 한데, 무슨 의미로 작성한건지 정확히는 모르겠습니다 ㅠㅠ
Api 명세를 발행한다는 느낌에서 newsApi라고 정의한게 아닐까 조심스럽게 추측해봅니다

2021-03-30 11:52 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Transactional
@Transactional을 선언하면 해당 부분이 트랜잭션 처럼 작동하는걸 보장한다고 알고 있습니다.
중간에 에러가 나면 해당 메서드를 통해 db에 반영되었던 것이 rollback 시켜서 Atomicity를 보장한다고 알고 있습니다.
또, AOP로 해당 메서드 앞 뒤에 transaction begin과 transaction commit을 시켜주는걸로 알고있습니다.
JPA에서는 commit 할 때 자동으로 dirty checking으로 DB에 변경한 값을 반영하기 때문에 save할 필요가 없다고 알고 있습니다.

2021-03-30 14:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/QnaApplication.java
> +	public Docket newsApi(){
저라면 qnaApi와 같은 식으로 이 API가 어떤 API인지 문서화 해줄 것 같아요!

2021-03-30 14:20 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private Integer countOfAnswer;
null이 안들어온다면 wrapper type일 필요가 있을까요?

2021-03-30 14:22 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Transactional
트랜잭션 처럼이 아니라 트랜잭션입니다. ㅎㅎ
트랜잭션을 start하고 해당하는 쿼리를 실행하다가 오류가 나는 경우 해당 트랜잭션이 롤백되고, 오류가 나지 않으면 전체가 커밋되는 All or Nothing이죠.
그럼 이 트랜잭션을 왜 써야할까요?

2021-03-30 14:22 UTC, merged