[Bibi & 이노] 미션3 - 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #121
Opened 2021-03-25 14:24 UTC by bibi6666667

안녕하세요, 백엔드반의 Bibi입니다😀
'미션3. 로그인 구현'을 이노와 피어 프로그래밍으로 구현 완료해 PR 드립니다!
(선택사항인 User-Question 연결, Answer은 생략했습니다. 미션4에서 함께 구현하겠습니다🙇‍♀️)

<🤔함께 고민한 부분>
- 좋은 커밋메시지(커밋 컨벤션)
- 좋은 메서드명, 좋은 URL ..
- 세션을 활용하는 메서드 로직🤯
- 리팩토링과 객체지향적 프로그램

이번 미션3부터 이노와 함께 짝 프로그래밍으로 본격적으로 진행하게 되었습니다. 주로 제가 Navigator를, 이노가 Driver를 맡아 진행했습니다. 처음엔 많이 어색하고 제가 도움이 되지 않을까 봐 걱정했지만(😭) 이노가 저를 잘 견뎌 주셔서(❓) 미션 진행 속도도, 코드의 수준도 더 높아진 것을 느꼈습니다. (감사합니다 이노!😀👍)

또 이번 미션은 루카스 영상 위주로 따라하되, 개선할 수 있어 보이는 부분들은 과감히 개선해 보았습니다. 하지만 과도해 보이거나 바람직하지 못한 부분이 있다면 코멘트 부탁드립니다!

부족한 코드지만 열심히 학습하고 고쳐 보겠습니다.  아낌없는 피드백 주시면 감사드리겠습니다! 🙇‍♀️🙇‍♀️
끝으로, 좋은 밤 되세요 🌙

2021-03-25 15:19 UTC, LarryJung requested changes
안녕하세요 이번에는 두분이서 진행하셨네요ㅎㅎ 같이 하나의 결과물을 만들었다는 것만으로 가치가 있다고 생각합니다. ^^

전보다는 코드가 읽기 편해진 것 같아서 좋았구요, 코멘트 확인 후 적용 부탁드릴게요!

2021-03-25 15:19 UTC, LarryJung commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.192'
버전 추가하신 이유가 있으실까요~

2021-03-25 15:19 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
이 로직이 getUserFromSession 내의 로직과 같은데.. 어떻게 중복을 줄여볼 수 있을까요? 고민해보시면 좋을것 같네요!

2021-03-25 15:19 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String viewQuestion(@PathVariable("questionId") Long questionId, Model model) {
PathVariable 괄호안에 questionId는 지워도 동작합니다~ 변수명이 같으면 됩니다.^^

2021-03-25 15:19 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
현재는 계층이 Repository, Controller 두개이고, repository는 조회만 하니깐.. 어떤 데이터를 조작하는 로직이 Controller에 private 메서드로 계속 추가될 것 같은데요, repository, controller 사이에 private 메서드를 수행할 계층이 있으면 어떨까요? 

실은 Service라는 이름으로 사용되는 클래스를 말하는 것이구요ㅎㅎ 계층(레이어라고 말하는게 편합니다만)은 어떤 기준에서 나누고, 나누면 어떤 점들이 좋은지 찾아보시고요!
스프링에서는 주로 어떻게 하더라~ 는 일종의 컨벤션도 알아보는것을 권해드립니다. (적당히 찾아보시는게 좋습니다. ㅎㅎ 이것도 깊게 가면 의견들이 너무 갈려서리..)

2021-03-25 15:19 UTC, LarryJung commented on src/main/java/com/codessquad/qna/exception/EntryNotFoundException.java
> +}
Entry가 아닌 Entity 가 아닐까요~

2021-03-25 15:19 UTC, LarryJung commented on src/main/java/com/codessquad/qna/repository/Question.java
> +    }
엔티티에서 save라는 메서드는 잘 안쓰긴하는데 일단 이렇게 하시다가, 나중에 어색해보이면 적절한 이름으로 바꿔보셔도 좋겠습니다~

2021-03-28 12:09 UTC, eNoLJ commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.192'
안녕하세요. 비비랑 같이 과제를 진행한 이노입니다. 이 부분 제 요청에 따라 버전을 추가했습니다.
비비랑 과제를 같이 진행하게 되었는데 비비는 최신버전으로 로컬에 h2를 따로 설치를 해서 사용을 하고 계셨고 저는 내장되어 있는걸 사용했기 때문에 차이가 생겼습니다.

찾아보니 1.4.198버전 이상부터는  db가 내장되어 있지 않고 따로 설치가 필요하다고 하더라구요. 그래서 의도적으로 버전을 낮춰 내장 db를 사용하고 로컬에 따로 설치를 하지 않는 쪽으로 합의를 보고 버전을 지정해 줬습니다.

2021-03-28 12:14 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
이 부분 `getUserFromSession` 메소드를 사용하는 걸로 수정했습니다. 이 부분에서 궁금한게 생겼습니다. `getUserFromSession` 메소드는 User를 반환하도록 짜여져 있는데 수정한 코드처럼 따로 받지 않고 그냥 세션을 확인하는 용도로 쓰는 것에 대해 해주실 말씀 있다면 부탁드리겠습니다!! 그리고 혹시 리뷰를 해주실 때 이 방법 외에 염두해 두신 방법이 있다면 그 부분도 부탁드릴게요ㅎㅎ

2021-03-28 12:14 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String viewQuestion(@PathVariable("questionId") Long questionId, Model model) {
해당 부분 전혀 몰랐는데 덕분에 간결하게 수정할 수 있었습니다. 감사합니다!!

2021-03-28 12:15 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/exception/EntryNotFoundException.java
> +}
아... 이 부분 전에 리뷰를 보고 제가 착각을 하였습니다. 말씀대로 `Entity`로 수정했습니다.

2021-03-28 12:16 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/repository/Question.java
> +    }
해당 부분에 있어서 추천해주실 만한 적절한 이름이 있을까요?? 궁금합니다!!

2021-03-28 12:25 UTC, bibi6666667 commented
안녕하세요, 백엔드반의 Bibi & 이노 입니다! 
미션3 피드백 사항들을 모두 수정 완료해 다시 요청 드립니다😀

<수정사항>
- Service 계층 분리 : UserService, QuestionService 생성
- Model 디렉토리 추가 : User, Question 클래스를 Model로 분리
- utils 디렉토리 추가 및 HttpSessionUtils, ErrorMessages 분류
- 아이디 중복검사 로직 추가
- 각종 예외 처리 : 예외 처리 코드에 Enum을 활용
- 리팩토링 : Controller 중심으로 코드 중복을 제거하고 가독성을 높임

글을 작성하며 다시 보니 재요청이 많이 늦어졌네요😅
이번 피드백에서는 특히 Service 계층을 만들 때 함께 토론하며 코드를 짜느라 시간이 많이 소요되었던 것 같습니다.
또 최대한 중복제거, 리팩토링을 했지만, 아직 미흡한 부분이나 바람직하지 못한 변경점이 있을 것 같습니다.
마찬가지로 코멘트 남겨 주시면 더 공부하고 수정해 보겠습니다!
얼마 남지 않았지만(😭) 좋은 주말 되시고, 이번 미션에서도 정성스러운 리뷰 주셔서 다시 한 번 감사합니다.
😀👍

- Bibi 올림

2021-03-28 12:26 UTC, eNoLJ commented
먼저 시간 내서 리뷰 달아주셔서 감사합니다. 말씀해주신 부분 최대한 수정 완료 했습니다. 덕분에 코드를 좀 더 간결하게, 불필요한 부분은 제거할 수 있었습니다. 그리고 이번 미션을 진행하면서 리뷰어님의 의견을 듣고 싶은 부분이 하나 생겨 여쭤봅니다.

보시면 아시겠지만 ErrorMessage라는 enum을 하나 만들었습니다. 처음 enum을 사용하자 싶었던 계기는 GlobalExceptionHandler에서 handleUserAccountException 메소드에서 사용하기 위함이였습니다. 에러를 구분하여 view를 달리해줄 필요가 있었습니다. 그렇게 사용하게 되었고 만들게 되면서 다른 메세지들도 모아서 사용하면 간결해질 것 같아 사용 중인 모든 메세지에 대해 상수를 만들어 사용했습니다.

이런식으로 관리를 하는 것이 어떤지 의견을 주시면 감사하겠습니다. 미션을 진행하면서 생각하는 부분이지만 솔직히 방법은 생각이 나서 적용을했다 해도 이 방법이 적절한지 부족한지 너무 과한지 판단이 서질 않습니다. 그리고 이 외에 더 간결하고 적당한 방법이 있을까 싶기도 하고요. 그래서 도움을 요청드려요!!

2021-03-28 12:51 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
안녕하세요! Service계층을 먼저 만들어 보셨던 이노의 조언에 따라 Controller의 주요 로직을 Service로 분리해 보았습니다.
코멘트 주신 내용을 보면서 '스프링 웹 계층'이라는 키워드로 구글링해 보았는데, 아래와 같은 계층이 있었습니다. 현재 저희가 진행 중인 미션에 이 계층구조를 대응해 보려 했는데,
1. 웹 계층 : @Controller, View, exception handlers
  - UserController, QuestionController, templates(html파일들)
  - GlobalExceptionHandler
2. 서비스 계층 : @Service
  - UserService, QuestionService 
3. 리포지토리 계층 : ??
4. DTOs : DTO의 영역
  - DTO : User, Question 객체?
5. 도메인 모델 : @Entity가 사용된 영역
  - User, Question ??

.. 이처럼 각 계층을 잘 이해하지 못해서 구분이 잘 안 되었습니다😭 혹시 제가 잘못 이해하고 있는 걸까요?
질문이 너무 기네요ㅠ 계층 이해에 도움이 될 만한 링크라도 알려 주시면 감사드리겠습니다..🙇‍♀️

2021-03-29 14:32 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
https://www.petrikainulainen.net/software-development/design/understanding-spring-web-application-architecture-the-classic-way/

요 링크를 읽어보시면 좋을 것 같습니다. ㅎㅎ 

1. 요지는 3가지 계층 정도면 충분하다. (Web layer, Service layer, Repository layer)
2. 각 계층간 (web - service, service - repository) 주고받는 데이터는 
  web-service -> DTO
  service - repository -> Entity

아마도 dto, 엔티티 이런 개념이 헷갈리실 수 있습니다. 
가볍게 설명 드리면 현재 h2에 저장하고 있는 데이터베이스 테이블을 모델화 한 것이 엔티티 이구요,
엔티티가 아닌(db관련된 어노테이션이 하나도 붙어있지 않은 아주 가볍게 만들어진 Object) 각종 로직을 수행하기 위해 만들 객체들을 dto 라고 합니다.

엔티티는 잘못 사용하면 테이블에 원치 않는 데이터가 저장될 수 있어서 공부를 많이 해보면 좋지만, 리뷰 드릴 당시에는
각 계층간 주고받는 데이터 형식을 지켜달라기 보다는 컨트롤러에 비즈니스로직이 많이 등장하면서 로직을 위임할 새로운 클래스를 만들어보라는 것이었습니다. ㅎㅎ (그냥 체스 만들듯이 자바 코드 짠다고 생각하시면 됩니다.)

2021-03-29 14:35 UTC, LarryJung commented on src/main/java/com/codessquad/qna/repository/Question.java
> +    }
저라면 일단 setWriter 로 시작할것 같네요 ㅎㅎ

2021-03-29 14:38 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
HttpSessionUtils에 메서드 하나 만들어서 세션에서 꺼낸 User의 null 체크를 할 것 같네요~

2021-03-29 15:15 UTC, LarryJung approved these changes
컨트롤러, 서비스의 역할분담이 잘 되어서 전보다 코드 파악하기 수월해진 것 같네요~👍👍

주신 질문에 의견을 더 드렸는데 도움이 되면 좋겠습니다!ㅎㅎ
Exception을 던질 때 enum을 사용하는 것은 상당히 자주 사용하는 패턴입니다. 서비스 덩치가 커지면 각종 예외가 발생하는데 globalHandler에서 코드값을 보고 처리하도록 로직을 한곳으로 모으곤 합니다. 잘 하셨습니다~ 

추가 리뷰는 일단 승인하고 다음번에 반영해주시는 걸로 하겠습니다. 수고하셨습니다~

2021-03-29 15:15 UTC, LarryJung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            model.addAttribute("user", userService.findById(id));
결과를 받아와서 리턴할 뷰를 분기하는 부분은 좋네요~ 하지만 result 가 false인 이유가 WRONG_PASSWORD 밖에 없을까요? (현재는 그렇지만.. 만약 password 형식이 틀렸다던지... 여러 이유가 생긴다면?)

boolean과 ErrorMessage를 묶은 객체를 userService.update() 에서 응답하게 한다면 좀 더 유연하지 않을까 하네요~

2021-03-29 15:15 UTC, LarryJung commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
findAll 결과가 List인데 questionList add 할 필요는 없어보입니다!

2021-03-29 15:15 UTC, LarryJung commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
문제가 있는 코드는 아니지만.. 이왕 계층에 대해서 찾아보셨으니 조금 더 이야기를 드리면
서비스 계층과 웹 계층의 차이점은 웹계층은 
- 보여지는 뷰
- http 요청,응답

을 주로 담당하고 서비스 계층은 만들고자 하는 핵심로직에 집중합니다. (질문을 생성하고, 글쓴이 검증하고.. 등등) 
verifyQuestion의 인자로 넘어가는 User가 세션에서 꺼내왔는지 어디 다른 db에서 가져왔는지 중요하지 않습니다.(몰라도됩니다) 그런 상황에서 글쓴이가 일치하지 않았을 때는 InvalidSessionException보다는 좀더 코어 로직의 오류를 나타내는 이름의 예외를 만들어 응답하고, 그 예외를 ExceptionHandler에서 받아 처리하는게 계층을 더 확실히 구분하는 방식이 아닐까 하네요

(현업에서 이렇게까지 까다롭게 구분해서 하는 경우는 많지 않습니다.. 저도 노력하는 부분..^^  원론적인 이야기를 드리는 것이니 참고부탁드려요.)

2021-03-29 15:15 UTC, LarryJung commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        userRepository.findAll().forEach(userList::add);
findAll 결과를 바로 리턴해주세요~

2021-03-29 15:15 UTC, LarryJung commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
한가지 고민해보시면
boolean 리턴 후 결과 받아 처리 vs. throw new Exception() 후 handler혹은 catch로 후처리

요 두가지 방식으로 만들 수 있는데 장단점이 무엇일지? 

저는 throw 를 하는 편입니다~

2021-03-30 03:00 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
넵 `questionRepository.findAll()`을 바로 리턴하도록 수정하겠습니다!😀

2021-03-30 03:02 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
으음음 그렇군요🤔. 예외 이름을 `IllegalUserAccessException`으로 바꿔 보았는데 이 이름은 적당한가요? (코멘트 감사합니다!😀)

2021-03-30 03:02 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        userRepository.findAll().forEach(userList::add);
넵 수정하겠습니다!

2021-03-30 03:04 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
`throw new Exception()` 등으로 예외를 바로 발생시키는 게 좋은 것 같네요. 해당 부분 수정하겠습니다! 감사합니다😊

2021-03-30 03:08 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            model.addAttribute("user", userService.findById(id));
코멘트 감사합니다! 좀 더 다양한 예외상황을 커버하기 위해, boolean을 사용한 if문 대신 switch-case에서 Exception enum을 받아오는 방식으로 바꿔 보았습니다😀

2021-03-30 03:14 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
아 그렇군요!! 코멘트 의도는 알았지만 공부하다가 이해가 잘 안 되어서 질문드렸습니다. 이렇게 상세히 설명해 주시고 링크까지 주셔서 정말 감사합니다🙇‍♀️!!

2021-03-31 01:25 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
래리 상세한 설명 좋네요!

2021-03-31 01:47 UTC, merged