[Dong] Mission4 객체-관계 매핑 제출올립니다
codesquad-members-2021/spring-boot-qna pull request #122
Opened 2021-03-25 14:34 UTC by d-h-k

### Intro
: 안하세요 백엔드반 Dong 입니다. Mission4 요구사항을 모두 개발해 PullRequest 요청 올립니다. 
- 배포페이지는 아래 링크를 클릭해 확인하실 수 있습니다.
> 배포링크 : https://spring-boot-qna-dong.herokuapp.com/qna/list

### 미션4
: 이번 미션4에서 주요 사항은 다음과 같습니다
-

2021-03-27 06:08 UTC, d-h-k commented
이번 미션에서 그동안 쌓여왔던 기술 부채를 텅고 가려고 합니다 

- 댓글 작성 되는지 테스트
- 댓글 수정, 삭제도 테스트 불가합니다.
- 댓글 개수도 제대로 출력되는지 
- 글 작성, 수정시 글쓴이 닉네임이 출력되는지( 요구사항대로라면 출력되지 않아야 함)
- 예외 페이지의 처리
- 다른 사용자가 수정, 삭제를 시도할 경우 (댓글, 질문글)
- 회원 목록페이지 이동은 관리자만 가능하도록(admin 계정)

2021-03-27 11:41 UTC, ksundong requested changes
안녕하세요! Dong! 리뷰어 Dion입니다!!
미션 4단계를 수행해주시느라 고생많으셨습니다!

## 웹 애플리케이션 리뷰

- 회원 중복가입 방지가 되어있지 않습니다. 500에러가 발생해요~(요구사항은 아니니 처리하지 않으셔도 괜찮습니다.)
- 글 목록, 글 조회시 글에 대한 생성시간이 노출되지 않습니다.
- 다른 사람의 글을 수정, 삭제하려고 할 때, 500에러가 발생합니다.
- 내가 글 작성자가 아닌경우 내가 작성한 답변을 삭제할 수 없습니다.
- 글 작성자는 모든 답변을 삭제할 수 있고, 질문을 지울 때에는 오류가 발생합니다.
- 예외 페이지의 처리가 되어있지 않습니다. (404만 나옵니다.)
- 글 수정시 글쓴이 닉네임이 나옵니다.

Admin 계정은 제가 봤을 때에는 아직 이른 구현이라고 생각됩니다. (어렵습니다.)

## 코드 관련 리뷰

- Service가 몰라도 되는 정보들은 제거해주세요.
- RESTful한 url 설계에 대해서 공부해보시고, url을 전체적으로 바꿔주세요.(Question, User, Answer)
- login 폼으로 연결되는 Controller가 Question에 있는것은 조금 이상합니다.
- 예외를 생성해 줄 때, 빈 기본 생성자가 보였는데, 이는 지양해봅시다.
- 좀 더 객체지향적으로 생각해봅시다!
- 예외가 발생했을 때, 어떻게 하면 유저에게 효과적으로 전달할 수 있을지 고민해봅시다.

고생하셨습니다. 자세한 사항은 코멘트를 참고해주세요.
궁금하시거나 도움이 필요한 부분, 이해가 되지 않거나 토론하고 싶은 부분은 언제든 코멘트 남겨주세요!!

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping("/qna/{questionId}/answers")
`@RequestMapping`으로 중복을 제거해주시면좋을 것 같아요.
그리고, `qna`보다는 `question`이 좀 더 RESTful 할 것 같습니다!

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>          return String.format("redirect:/qna/%d", questionId);
`format`을 사용하는 것은 성능면에서나, 가독성 면에서 그리 좋지 않습니다.
저는 + 연산을 사용하는 것을 추천드려요!

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      }
login을 하는 곳인가요? 그러면 QuestionController에 있으면 안되지 않을까요?

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        //@Todo 모델에다가 데이터를 집어넣어주는건 컨트롤러 역할 같다. 개선할 수 있는 방법을 찾아보자
네 이 부분 저도 동의합니다.
이번 단계에서 개선해봅시다 ^^

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
이 빈 줄은 제거해줍시다.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      @PostMapping("/questions")
이쪽 url이 전반적으로 가다듬어질 필요가 있을 것 같네요.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String listShow() {
보통은 동사+명사 조합을 많이 사용합니다.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
RESTful한 url을 설계할 때는 리소스는 복수형으로 보통 표현합니다.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PostMapping("/create")
url에는 동사가 가급적이면 드러나지 않는 것이 좋습니다.
특히 create는 이미 POST가 그 역할을 다 하고 있습니다.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
👍 
근데 보통은 외부에서 들어오는 인자의 경우에는 null인 경우가 있어서 속성이 먼저 오는 편이 낫습니다~

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return createdDateTime.format(DateTimeFormatter.ofPattern(DATE_AND_TIME_FORMAT));
저는 DateTimeFormatter 자체를 추출해보시길 권하고 싶네요.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/LoginFailedException.java
>      }
왜 비어있는 생성자가 있을까요?

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (!isDeleteAble(questionId)) {
```suggestion
        if (!isDeleteable(questionId)) {
```

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        Question question = questionRepostory.findById(questionId).orElseThrow(NotFoundException::new);
NotFoundException만 주는 것은 별로 바람직하지 않다고 생각되고, QuestionNotFoundException을 주거나 Question이 없음을 알 수 있도록 해주는 편이 좋겠네요.

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>              throw new UnauthorizedException("질문글 삭제 - 실패, 권한없는 사용자의 삭제시도");
문자열을 상수화 해서 Exception에서 관리하는 방향도 생각해보세요~

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (!isDeleteAble(questionId)) {
이 부분, question을 이미 가져왔으니, question에 이 메서드를 두는 편이 낫지 않을까요?

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
위에 이 메서드와 관련된 의견을 남겼으니 참고해주세요~

2021-03-27 11:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public void validationCheck(Long id, HttpSession session) {
이 메서드는 여기 있으면 안될 것 같네요~

2021-03-28 06:14 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return createdDateTime.format(DateTimeFormatter.ofPattern(DATE_AND_TIME_FORMAT));
해당부분 format을 직접 추출하니 훨씬 코드가 깔끔해지고 성능도 조금이나마 더 개선되었을듯 합니다 좋은 리뷰 감사합니다! 👍

2021-03-28 06:27 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
해당부분 말씀해주신대로 Question 에서 처리하게끔 수정하니까 훨씬 코드도 깔끔해지고, 불필요한 DB 접근도 두번이나 줄일수 있었습니다!! 감사합니다!

2021-03-28 07:41 UTC, d-h-k commented on src/main/java/com/codessquad/qna/exception/LoginFailedException.java
>      }
메시지 없이 에러만 날려주는 코드를 쓰기위해 였던듯 한데요, 앞으로 예외발생시 기본생성자가 아니라, 메시지를 추가한 생성자를 사용 할 수 있도록 수정하겠습니다.

2021-03-28 07:42 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (!isDeleteAble(questionId)) {
말씀해주신부분 동감합니다! 수정하였습니다

2021-03-28 07:55 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      }
해당부분은 메서드명이 부정확했고, 또 중복된 메서드를 제작한것을 확인해 수정하였습니다! 감사합니다

2021-03-28 07:59 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        //@Todo 모델에다가 데이터를 집어넣어주는건 컨트롤러 역할 같다. 개선할 수 있는 방법을 찾아보자
해당부분 컨트롤러에서 컨트롤러에서 model 을 추가해주고, 더이상 서비스에서 모델에 관여하지 않도록 수정하였습니다!!

2021-03-28 08:02 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String listShow() {
말씀 듣고 반영해서 showUserList  라는 이름으로 바꿔주니 훨씬 더 자연스럽고 의미도 명확히 전달되는 메서드가 되었습니다! 감사합니다

2021-03-28 15:00 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping("/qna/{questionId}/answers")
1) @RequestMapping 어노테이션으로 중복을 제거하고
2) qna에서 >>  question 으로 변경은 완료했습니다.

아직 RESTful 이 뭔지 잘 모르겠어서 조금씩 수정중인데, 나름 코드가 RESTful 하게 수정되면 그때 Resolve 하겠습니다!

2021-03-28 15:01 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      @PostMapping("/questions")
넵 Question 부분의url을 전반적으로 가다듬어 보겠습니다!

2021-03-28 15:12 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/UserController.java
>  @RequestMapping("/user")
넵 user >> users 로 변경하였습니다!

2021-03-28 15:30 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PostMapping("/create")
좋은 리뷰 감사합니다 

찬찬히 생각해보니 전혀 REST-ful 하지 않은 코드였습니다. 해당 부분을 signup 이라는 키워드로 리팩토링하였습니다!

2021-03-28 16:03 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>              throw new UnauthorizedException("질문글 삭제 - 실패, 권한없는 사용자의 삭제시도");
넵 에러관련 문자열들을 상수화 하였습니다

2021-03-29 10:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping("/qna/{questionId}/answers")
RESTful은 정말 어렵지만, 이를 흉내내는 정도만 되어도 됩니다 ㅎㅎ

2021-03-29 10:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PostMapping("/create")
굳이 없어도 됩니다 ㅎㅎ

2021-03-29 10:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/LoginFailedException.java
>      }
기본생성자가 비어있지만 않으면 됩니다. 기본 메시지를 할당하는 식으로 저는 자주 사용해요!

2021-03-29 10:39 UTC, ksundong approved these changes
피드백 반영해주시느라 고생많으셨습니다.
다음 단계를 진행하기에 앞서서, 아래의 코멘트 사항들을 꼼꼼히 읽어보시고, 다음단계 진행하시면서 반영해주시면 감사하겠습니다.
고생하셨어요~

## 다음 단계 진행 전 반드시 지켜져야 할 것

- 회원가입이 정상적으로 되도록 수정
- `/users/`가 user의 목록을 출력하도록 url 변경
- 그 밖의 위에서 말씀드렸던 제대로 동작하지 않는 사항들 꼼꼼히 확인해주세요.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("/answers")
answers도 중복이 되죠? 위로 중복을 제거해줘도 됩니다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            throw new UnauthorizedException(NEED_LOGIN);
그냥 빈 생성자에 기본값을 NEED_LOGIN으로 줘도 좋을 것 같네요!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            throw new UnauthorizedException(NEED_LOGIN);
또한 verifyLoginUser라는 메서드를 SessionUtil에 두는 것도 좋을 것 같아요.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            throw new UnauthorizedException(NEED_LOGIN);
여기서만 쓰이지 않을테니까 중복이 제거될겁니다!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info("signup >> users/form.html: in");
이런 정보는 info 레벨 보다는 debug 레벨이 어울릴 것 같습니다!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +import static com.codessquad.qna.utils.DateUtil.DATE_AND_TIME_FORMAT;
어떤 FORMAT인지 드러나게끔 네이밍을 해주는 것도 좋아보여요~

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
👍

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +    }
요런 중복이 있다면, 하나의 메서드에서 처리해주는 것도 좋아보입니다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +    }
기본적인 예외를 모두 처리해주는 Exception class Handler도 한 번 만들어보세요~

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +        logger.warn(exceptionMessage);
`logger.warn("설명", exception);`
형태로도 작성할 수 있습니다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionMessages.java
> +public class ExceptionMessages {
이렇게 모든 ExceptionMessage를 한 클래스에서 관리하기 보다는 각 클래스에서 개별적으로 에러메시지를 처리해주는 것이 좋아보입니다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/UnauthorizedException.java
> +// location.href = "something" 스크립트 코드 두개로 커버 가능!
주석이 들어갔네요 👀

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +            logger.info(UNAUTHORIZED_FAILED_LOGIN);
굳이 로깅해주지 않아도 될 것 같아요.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        //User ownerUser = questionRepostory.findById(questionId).orElseThrow(() -> new NotFoundException(NOT_FOUNDED_USER)).getWriter();
사용하지 않는 코드는 주석 처리 말고 바로 지워줍시다!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        if (!isValidUser(session, answer.getWriter())) {
이렇게 내부 메서드를 호출하기 보다는, 객체에게 물어보는 식으로 수정해보세요!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>          //@Todo 비어있는 타이틀이나, 비어있는 컨텐츠가 들어오면 그냥 저장되는 문제..
이 주석도 마찬가지로 제거해주세요~

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        //return questionRepostory.findById(id).orElseThrow(() -> new NotFoundException(NOT_FOUNDED_QUESTION));
여기도 주석이 있네요!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +            throw new UnauthorizedException(FREE2ASK_BUT_DELETE);
상수의 이름이 읽기가 조금 힘드네요!

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +            logger.info(UNAUTHORIZED_FAILED_QUESTION);
대부분의 코드가 이런 형태인데, 이런 로그는 거의 의미가 없습니다. warn으로 또 찍히거든요.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +
빈 라인이 있네요 👀

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        if (userRepository.findByUserId(user.getUserId()).get() != null) {
옵셔널 강제 언래핑을 해주지 말고, `isPresent()`를 사용해봅시다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new LoginFailedException(FAILED_LOGIN);
빈 생성자에 FAILED_LOGIN을 넣어봅시다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/utils/DateUtil.java
> +public class DateUtil {
항상 이런류의 클래스는 인스턴스 생성을 막기위해 private 기본 생성자를 만들어줍시다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/utils/DateUtil.java
> +public class DateUtil {
또한 단순 상수를 가지고 있는 클래스의 네이밍은 Constants를 더 많이 사용합니다.

2021-03-29 10:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/utils/SessionUtil.java
> +            throw new NotLoggedInException("");
메시지를 넘기지 않는 것은 지양해주세요.

2021-03-29 10:39 UTC, ksundong commented on src/main/resources/templates/qna/show.html
> +                              <!-- <-&#45;&#45; {{createdDateTime}} -&ndash;&gt; -->
이 주석도 지워주세요!

2021-03-30 02:16 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
감사합니다!

2021-03-30 03:29 UTC, d-h-k commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info("signup >> users/form.html: in");
네 말씀해주신대로 평소에는 딱히 필요가 없고, 디버깅시에 출력되도록 변경하겠습니다.

2021-03-30 03:36 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +import static com.codessquad.qna.utils.DateUtil.DATE_AND_TIME_FORMAT;
날짜와 시간에 관한 패턴을 정하는 문자열이라는 의미에서 DATE_AND_TIME_PATTERN 로 변수명을 변경하겠습니다! 포맷보다는 패턴이라고 말해주는게 조금 더 의미전달에는 좋을꺼같아요!

2021-03-30 03:47 UTC, d-h-k commented on src/main/java/com/codessquad/qna/exception/ControllerExceptionHandler.java
> +    }
넵 이런 부분도 제가 찾아서 제거했어야 하는데, 말씀해주셔서 감사합니다.

하나의 메서드에 >> 여러가지 익셉션을 달아주고 싶었는데, 그런 기능은 없어서 별도의 프라이빗 메서드를 작성하였습니다.

나중에 프로젝트가 더 커지면, 익셉션들간의 상속관계를 추가해야겠다는 생각을 했습니다!

2021-03-30 03:55 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        //User ownerUser = questionRepostory.findById(questionId).orElseThrow(() -> new NotFoundException(NOT_FOUNDED_USER)).getWriter();
넵 유의하겠습니다

2021-03-30 03:57 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        if (!isValidUser(session, answer.getWriter())) {
아하 좀더 객체지향적으로 짜라는 말씀은 바로 이런부분이였군요..... 미쳐 생각하지 못한 부분입니다!!! 감사합니다

2021-03-30 04:09 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>          //@Todo 비어있는 타이틀이나, 비어있는 컨텐츠가 들어오면 그냥 저장되는 문제..
해당부분은 조금 더 고민하고 결정을 미루고 싶어서요 ㅠㅠ,.. 혹시 다음미션까지 꼭 지우는걸로 진행해도 될까요 ㅠㅠ..?

2021-03-30 04:27 UTC, d-h-k commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new LoginFailedException(FAILED_LOGIN);
와 이러니까 훨씬 코드가 깔끔해졌어요, 불필요하게 여기저기 흩어져있는 데이터들을 한곳으로 모으는효과도 있고요!! 감사합니다

2021-03-30 05:51 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +import static com.codessquad.qna.utils.DateUtil.DATE_AND_TIME_FORMAT;
음.. 표준을 명시해줘도 좋고, 아니면 QNA_DATETIME_FORMAT 정도여도 무난해보입니다.
일반적인 이름보다는 어떤 형태인지 짐작가는 것이 좋은 것 같아요.

2021-03-30 05:52 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>          //@Todo 비어있는 타이틀이나, 비어있는 컨텐츠가 들어오면 그냥 저장되는 문제..
넵넵~

2021-03-30 05:53 UTC, ksundong commented
반영 다 되셨나요? 머지해도 될까요?

2021-03-30 06:27 UTC, d-h-k commented
넵넵 반영 다 했습니다 머지 부탁드려요! @ksundong

2021-03-30 06:28 UTC, merged

2021-03-30 06:28 UTC, d-h-k commented
@ksundong 좋은 리뷰 감사드립니다 !!!