[새리 & Jung] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #125
Opened 2021-03-27 12:53 UTC by min27604

안녕하세요, 새리입니다.

이번 미션도 이전 미션들과 마찬가지로 자바지기님의 강의를 먼저 듣고 따라하는 형식으로 진행했습니다. 삽질하느라 과정이 매끄럽진 못했지만 배운 점이 많았습니다.
이번 미션에서는 답변추가 및 삭제기능을 구현했습니다.
그룹에서 코드리뷰를 받을 때 답변을 구현하는 과정에 있어 컨트롤러보다 서비스에 좀 더 역할을 부여해주는 편이 좋을 것 같다는 피드백을 받아 최대한 건내받은 정보를 가공(?)하는 부분은 서비스로 옮겼습니다.

시간내주어 리뷰해주셔서 감사합니다. 좋은 하루 되세요.

2021-03-28 12:55 UTC, sonypark requested changes
안녕하세요 새리, 리뷰어 소니 입니다.😊
미션4 잘 구현해주셨네요. 👍
soft delete가 적용이 안된건 같은데 확인 한 번 해주세요~

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +
QuestionService는 사용되고 있지 않은데 넣어주신 이유가 있나요?

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +
여기서 QuestionService를 사용하고 있으니 Answer 컨트롤러에서는 QuestionService가 없어도 될 것 같네요

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private Question validateQuestionWriter(Long id, HttpSession session) {
Question 컨트롤러 내 메서드이니 메서드명에서 question은 없어도 될 것 같아요.

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime timeCreated = LocalDateTime.now();
final을 붙이면 좋겠네요.
필드명은 createdDateTime이 더 자연스러운 것 같아요~ (제 생각😅)

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +
👍

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +                '}';
현재 Question과 Answer는 양방향 연관관계를 갖고 있는데요.
양방향관계에서 toString을 사용할 때 주의해야할 점이 무엇이 있을까요?
중요한 부분이니 꼭 공부해주세요~

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
TODO에 적힌대로 적절한 예외가 아니네요

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
soft-delete가 적용된건가요?

2021-03-28 12:55 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        if (this.answers.size() == 0) {
```suggestion
        if (this.answers.isEmpty()) {
```

2021-03-29 16:14 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +                '}';
검색해본 바로는 양방향 관계에서는 toString때문에 무한루프에 빠져 스택오버플로우가 날 가능성이 있어 toString 사용을 자제하라고 합니다. 문제를 해결하려면 toString에서 question을 불러오는 부분을 없내는 편이 좋을까요? 검색하다보니 ToStringBuilder를 쓰라는 블로그 글도 봤는데 큰 설명없이 사용방법만 나와있어 적절한 해결책인지 의문이 듭니다.

2021-03-29 16:22 UTC, min27604 commented
소니 안녕하세요! 먼저 리뷰 감사합니다😊
이번주가 팀프로젝트 들어가기 전 마지막 주라고 생각하니 마음이 급해져서 미션 4의 선택사항인 soft delete 구현부분도 미션 5에서 해야겠다 싶어 스킵하고 디테일한 부분도 크게 신경쓰지 않고 PR을 올렸습니다. 그랬더니 여기저기 어처구니 없는 실수를 많이 해버렸네요. 부끄럽습니다..
피드백 주신 부분들은 모두 수정했습니다. 그리고 soft delete로 질문과 답변을 삭제하는 부분은 요구사항을 참고해 일단 제 머리속에서 나오는대로 구현해보았는데 작동은 잘 하는 것 같습니다만 혹시 제가 놓치는 부분이 있거나 공부해야할 부분의 키워드가 있다면 알려주시면 감사하겠습니다!!

2021-03-30 10:47 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +                '}';
네 `toString()` 을 사용할거라면 양방향 연관관계에 있는 엔티티 (여기서는 question)을 제외하고 사용하시길 권장드립니다 :)

2021-03-30 10:54 UTC, sonypark reviewed
새리 수고하셨습니다!

2021-03-30 10:54 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +
변수명은 축약하지 말고 써주세요~ a -> answer

2021-03-30 10:54 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
💯

2021-03-30 10:55 UTC, sonypark approved these changes

2021-03-30 10:55 UTC, merged