[Cooper] 미션6. 페이지 나누기
codesquad-members-2021/spring-boot-qna pull request #126
Opened 2021-03-27 21:20 UTC by pbg0205

안녕하세요.
코드스쿼드 마스터즈 백엔드 과정이 Cooper 입니다!🚀
QnA 미션6 요구 사항을 완료하여 PR을 보내게 되었습니다.
구현한 기능은 아래와 같습니다.

1️⃣ Pagination 구현
- CrudRepository를 JpaRepository interface로 변경하였습니다.
 JpaRepository의 하위 인터페이스이며, CRUD 기능 뿐만 아니라 pagination과 
같은 JPA 특화 포함하고 있어 해당 repository로 변경했습니다.

- PageUtil을 추가하였습니다.
 PagInation과 관련된 정보를 전달하기 위해. PageUtil 내부에는 pagination에 필요한 정보 및 로직을 추가하였습니다. question 수에 따른 해당 페이지에서 출력하는 리스트 수, 버튼 상태에 대한 정보를 동적으로 저장할 수 있도록 구현하였습니다.

배포 주소는 [http://cooper-boot-qna.herokuapp.com/](http://cooper-boot-qna.herokuapp.com/)입니다. 😄
바쁘신데 일정 속에 시간 내어 리뷰해주셔서 감사합니다.
사소하더라도 디테일한 피드백은 사랑입니다 😄
잘부탁드립니다!

2021-03-28 13:00 UTC, ksundong requested changes
안녕하세요! Cooper!! 리뷰어 Dion입니다!!
마지막 미션까지 진행해주시느라 수고 많으셨습니다!
다만, 커밋이 두 개 밖에 없어서 아쉽네요. 코쿼 과정 중에는 의도적으로라도 커밋을 분리하는 연습을 해주시길 당부드립니다.
코드는 대부분 깔끔했고, `PageUtil`이 조금 아쉬운 부분이 있었습니다.
이번 리뷰에서 한 번 PageUtil을 좀 더 잡고 가보시죠!

## 웹 애플리케이션 관련 리뷰

- 페이징 기능은 대부분 정상적으로 동작합니다. 다만, 999페이지 같이 없는 페이지를 조회하는 경우 500에러가 발생합니다.

## 코드 관련 리뷰

- 우리가 제공하는 메서드는 외부에서 사용하는 API라고 생각하시면 됩니다.
- 전반적으로 매직넘버를 상수로 추출하는 것이 잘 안되고 있습니다. 꼭 상수로 추출하는 습관을 들여주세요~
- 메서드가 가지는 책임에 따라 메서드를 이동시켜주는 것이 필요해보입니다.
- 복잡한 메서드는 개별적인 메서드로 분리해서 가독성을 높여줍시다.
- 개발자는 지루한 작업을 자동화 하는것을 항상 고민해야합니다. 한 번 SQL문을 자동화 해봅시다.

마지막 미션까지 진행하느라 고생하셨습니다!
몇 가지 제안사항과 리뷰를 남겨드리니 참고해서 수정해주세요!
궁금하시거나 도움이 필요한 부분, 이해가 되지 않는 부분 토론하고 싶은 부분은 언제든 코멘트 남겨주세요!
고생하셨습니다~

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    public Page<Question> findUnRemovedList(Pageable pageable) {
굳이 메서드 명에 unRemoved라는 얘기는 없어도 될 것 같아요~

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        pageable = PageRequest.of(page, 5, Sort.Direction.DESC, "id");
요구사항은 시간을 역순 정렬하는 것이었는데, id를 역순정렬 해주신 이유가 있을까요?

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        pageable = PageRequest.of(page, 5, Sort.Direction.DESC, "id");
5라는 숫자는 언제든 요구사항이 변할 수 있을 것 같아요. 상수로 추출해볼까요?

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    public Page<Question> findUnRemovedList(Pageable pageable) {
그러면 메서드 명이 변경되지 않고도 요구사항이 변경되는 것에 대응이 되겠죠?

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>      }
이 메서드는 service가 가져야 할까요?

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +public class PageUtil {
Util이라는 이름은 조금 특이하네요.
보통 Utility성 클래스들은 상태를 가지지 않습니다.

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +    private int currentPage;
```suggestion
    private int max;
    private int previousPage;
    private int currentPage;
    private int nextPage;
    private List<Integer> pages;
```

max가 의미하는 바가 잘 안와닿네요. 어떤 의미인가요?
그리고 필드도 가급적이면 비슷한 의미끼리 묶어주시는걸 추천드리겠습니다!

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +    }
하드코딩 된 부분은 전부 상수로 추출해봅시다.
그리고 클래스의 동작이 조금 복잡하게 느껴지는 것 같아요.
차근차근 메서드 분리를 통해서 읽기 좋게 분리해봅시다.

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +    }
메서드 네이밍이 조금 이질적이네요.
nextCount() 정도면 어떨까요?

2021-03-28 13:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        model.addAttribute("pageUtil", questionService.getPageUtil(questions));
아하 이렇게 쓰려고 PageUtil이군요.
좀 더 좋은 방안을 고민해봅시다!

2021-03-28 13:00 UTC, ksundong commented on src/main/resources/data.sql
> +VALUES ('2021-03-26 09:13', null, 'content 34', false, 'title 34', 1);
설마 이거 직접 다 입력해주신 것은 아니겠죠?
프로그래밍 방식으로 한 번 해결해봅시다.

2021-03-28 13:00 UTC, ksundong commented on src/main/resources/templates/home.html
> +                    {{/pageUtil}}
백엔드가 조금 로직을 처리하는 대신 프론트가 상대적으로 수월하게 처리할 수 있군요!

2021-04-04 15:10 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    public Page<Question> findUnRemovedList(Pageable pageable) {
말씀해주신대로 메서드명을 기존에 findQuestionList로 변경 해보았습니다!
피드백 감사합니다👍

2021-04-04 15:11 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        pageable = PageRequest.of(page, 5, Sort.Direction.DESC, "id");
우선적으로 id로 작동 여부 확인 후, 변경하지 못했습니다. 해당 요구사항 수정 완료하였습니다!
말씀해주신대로 페이지 사이즈는 요구사항 변경에 대비해 상수로 별도로 분리하였습니다!

2021-04-04 16:07 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>      }
처음에는 로직을 구현하는 부분은 service에서 구현하는 것이 맞다고 생각해서 구현해보았는데 단순 변수명만 할당한 부분이라 컨트롤러에서 구현하는 것이 더욱 적합해 보입니다! 그리고 불필요하게 메서드를 호출하는 느낌이라 안좋아보이네요. Controller에서 처리하는 방법으로 변경하겠습니다!!

2021-04-04 16:09 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +public class PageUtil {
그렇다면 Util은 부적합한 클래스명인 것 같습니다. 페이지에 관련된 정보를 가지고 있으니 Page로 변경해보겠습니다!

2021-04-04 17:02 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +    private int currentPage;
제가 봐도 좀 난잡해보이네요;;
의미가 구분될 수 있도록 하겠습니다!

2022-04-22 23:37 UTC, closed without merging