[Jung] 미션4 PR입니다
codesquad-members-2021/spring-boot-qna pull request #129
Opened 2021-03-29 05:33 UTC by rla36

안녕하세요 Jung입니다! 미션4 PR입니다. 

미션 요구사항을 충실히 따라 특별한 점은 없으나
예외 처리를 하기 위한 커스텀 예외들을 만들었고, RuntimeException을 상속받는 QnaException을 만들어 
이 Qna 프로젝트의 모든 다른 예외들이 QnaException을 상속받게 만들었습니다
미션3 리뷰받은 것들 수정사항도 추가하겠습니다!

리뷰 감사합니다~

2021-03-29 12:27 UTC, ksundong requested changes
안녕하세요~ Jung! 리뷰어 Dion입니다.
미션 4단계까지 진행하시느라 고생많으셨습니다. 다음단계부터는 다른 리뷰어 분께 코드를 맡겨봅시다. ㅎㅎ
이것저것 열심히 공부해보신 것 같네요! 좋은 것 같아요!

혹시 요구사항 중 추가 요구사항은 구현해보지 않으신걸까요?
추가 요구사항도 한 번 구현해보셨으면 합니다! (선택이기 때문에 하지 않으셔도 괜찮습니다.)

`@Valid` 애노테이션을 사용해서 한 번 객체를 검증해보세요. 다른 에러가 발생할거에요!

## 웹 애플리케이션 관련 리뷰

- 로그인 시 개인정보 수정 페이지가 연결되어있지 않네요~
- 개인정보 수정 시 사용자 아이디가 변경 가능하게 되어있네요! 미션 3 요구사항에 의하면, 변경이 불가능해야합니다!
- 글 목록에서 사용자 아이디 클릭시 404 에러가 발생합니다.
- 수정 페이지에서, 빈 공백이 추가되어있네요. 왜일까요?
- Validation 로직이 동작하지 않네요!
- 답변 작성이 동작하지 않네요!

코드 관련 리뷰는 아래의 코멘트를 참고해주세요!

4단계 진행하느라 고생많으셨고, 동작하지 않는 부분이 있어서 **변경 요청** 드리겠습니다.
궁금하시거나 도움이 필요한 부분, 이해가 되지 않거나 토론하고 싶은 부분은 언제든 코멘트 남겨주세요!
고생하셨어요!!

2021-03-29 12:27 UTC, ksundong commented on build.gradle
>  	compile 'pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.2'
compile과 implementation의 차이에 대해서 한 번 학습해보세요~

2021-03-29 12:27 UTC, ksundong commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
Wow validation starter가 들어왔군요!

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    public String blankNotAllowed(ConstraintViolationException e, Model model) {
이 Exception말고 다른 Exception은 없었나요?
요 Exception이 떨어진다는 것은, Spring의 Validation이 적용이 제대로 안된 것 같다는 생각이드네요.

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +        model.addAttribute("exceptionMessage", e.getLocalizedMessage());
와 localizedMessage!
혹시 이것을 왜 사용해주셨나요?

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        Question question = questionService.findById(questionId);
그냥 questionId를 save에 넘겨주는건 어떻게 생각하시나요?

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력값입니다.")
보통 Validation은 DTO 영역에서 해주곤 하지만, 지금은 이대로도 괜찮을 것 같아요!

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    }
👍

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    @NotBlank(message = "제목은 필수 입력값입니다.")
길이제한도 줄 수 있습니다.!

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
Wrapper type으로 반환해줄 이유가 있나요?

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    public List<Answer> getAnswers() { return answers; }
```suggestion
    public List<Answer> getAnswers() {
        return answers;
    }
```

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/AnswerNotFoundException.java
> +public class AnswerNotFoundException extends QnaException {
👍

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +public class QnaException extends RuntimeException{
```suggestion
public class QnaException extends RuntimeException {
```

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +public class QnaException extends RuntimeException{
이 Exception의 선언은 좋네요~

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +    public QnaException(String message) { super(message); }
```suggestion
    public QnaException(String message) {
        super(message);
    }
```

이것 말고도 여러개의 생성자를 선언해주면, 상속하는 Exception이 좀 더 다양한 표현을 활용할 수 있습니다.

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public void delete(Long id, User sessionedUser) {
너무 메서드명을 DB에 의존적으로 작성하지 않아도 좋다고 생각해요!

2021-03-29 12:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    private QuestionRepository questionRepository;
```suggestion
    private final QuestionRepository questionRepository;
```

2021-03-31 02:20 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
애초에는 댓글이 21억개 이상 달리는 가상의 경우를 고려해서 long으로 했는데
생각해보니 answers.size()에서 오버플로우가 발생한다면 int를 long으로 변환해봤자 소용이 없겠네요 ㅋㅋ ㅜ 
int로 수정해야겠습니다

2021-03-31 02:22 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력값입니다.")
Validation을 DTO영역에서 해주는군요...! 각 영역이 주로 담당하는 역할을 좀더 심도있게 공부해봐야할것같습니다ㅜㅜ 지

2021-03-31 02:47 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        Question question = questionService.findById(questionId);
원래는 그렇게 했었는데
AnswerService의 save메소드 내에서 questionService의 findById로 question을 찾기 위해선,  answerService내에서 questionService를 호출,삽입해야해서 서비스 간 독립성?을 유지해보고자 하는 생각에 위와 같이 컨트롤러로 question을 찾는 부분을 빼냈습니다

서비스 간 독립성을 유지해보려고 한 이유는 AnswerService  생성자에 QuestionService를 넣고, QuestionService  생성자에 AnswerService를 넣으니 순환참조 문제로 빌드가 되지 않아, 꼭 필요한 경우에만 한 서비스에 다른 서비스를 넣으려고 
서비스 내 다른 서비스 호출하는 것을 아껴두고(?) 있었기  때문입니다. 

그럼 일단 말씀하신대로 한번 수정해보겠습니다..!

2021-03-31 03:11 UTC, rla36 commented on build.gradle
>  	compile 'pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.2'
compile은 deprecated되었군요..! implementation으로 수정했습니다.
[링크](https://tomgregory.com/gradle-implementation-vs-compile-dependencies/) 를 읽어보았는데 class path관해서도 공부해야할것같네요 공부 키워드 주셔서 감사합니당

2021-03-31 03:14 UTC, rla36 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
회원가입/질문 작성 시 공백으로도 가입/질문하기가 되는 문제를  다른분들은 어떻게 해결했나 여쭤서 넣어봤습니다..
Entity의 공백이면 안되는 칼럼에 @NotBlank애노테이션을 추가하고 저 부분을 추가했습니다..!

2021-03-31 03:16 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +        model.addAttribute("exceptionMessage", e.getLocalizedMessage());
잘못 사용했습니다 ㅋㅋ  ㅜㅜ 지금은 수정된 상태입니다

2021-03-31 03:18 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    public String blankNotAllowed(ConstraintViolationException e, Model model) {
이 Exception을 핸들러로 다뤄준 이유는 예외 발생시 보여지는 화면이 
흰바탕에 검은글씨 에러페이지...?가 아니라 사용자의 예외발생 이전화면과 유사한 서식의 에러페이지가 뜨도록 하기 위해서였습니다!

2021-03-31 03:21 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +    public QnaException(String message) { super(message); }
[RuntimeException](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/RuntimeException.html)의 다양한 생성자 확인했습니다! 다만 지금 쓰일 일이 없을 것 같아서 저것만 선언해주었습니다.

2021-03-31 03:32 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public void delete(Long id, User sessionedUser) {
미션 1,2 까지는 service역할이 repository와 controller을 중계해주는 데 그쳐서 repository의 메소드명을 그대로 서비스에서 사용했습니다.  나름 일관성을 위해서 미션 3,4에서까지 저렇게 한 것 같네요 ㅋㅋ 적절한 메소드명 찾기가 어려운데 상황에 맞는 이름 찾도록 노력해보겠습니다!

2021-03-31 14:34 UTC, ksundong commented on build.gradle
>  	compile 'pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.2'
화이팅!

2021-03-31 14:35 UTC, ksundong commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
네 Bean Validation도 학습해 두시면 좋을거에요!

2021-03-31 14:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/ExceptionHandlers.java
> +    public String blankNotAllowed(ConstraintViolationException e, Model model) {
이 Exception이 언제 발생하는지 알아보시고, 예외 처리의 여러 방식을 고민해보세요!
지금도 잘 처리해주시긴 하셨는데, 원래라면 이 Exception이 발생하지 않을거같거든요!

2021-03-31 14:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/AnswerController.java
> +        Question question = questionService.findById(questionId);
자 한 번 생각해봅시다!
순환 참조가 발생했다면, 어쩌면 한 쪽이 다른 한쪽을 가지는게 맞는지 고민을 해봐야겠죠?
그리고, 이를 해결하기 위한 방법을 고민해봐야 할겁니다.
좀 더 나아가면 설계 측면에서, Question이 Answer를 포함하므로, Answer는 Question을 통해서만 접근 가능하게 해줄 수도 있답니다~
일단은 그대로 진행하시죠~

2021-03-31 14:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력값입니다.")
사실 Domain에서도 Validation이 들어가야 하는데, 서로 성격이 다릅니다.
사용자의 입력을 검증하는 것은 DTO에서, Domain 자체의 유효성을 검사하는건 Domain에서 수행해줘야겠죠~

2021-03-31 14:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
사실 Wrapper Type은 `Long`, `long`의 차이를 알고 계시고 사용하신건지 여쭤본 거였습니다!

2021-03-31 14:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +    public QnaException(String message) { super(message); }
예외 포장에 대해서도 한 번 공부해보세요~

2021-03-31 14:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public void delete(Long id, User sessionedUser) {
화이팅!

2021-04-02 02:55 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/exception/QnaException.java
> +    public QnaException(String message) { super(message); }
넵 발생하는 여러 예외들을 캐치해서 더 적절한 새로운 예외를 throw하는 방법 학습했습니다!

2021-04-02 02:57 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
아 넵넵 기본형과 객체라는 차이 알고 있습니다!

2021-04-02 07:14 UTC, rla36 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
넵 알겠습니다!

2021-04-02 08:10 UTC, rla36 commented
[배포링크](https://jung-spring-boot-qna.herokuapp.com/questions) 입니다!
미션5까지 진행된 상태이고 말씀해주신 것들 반영했습니다.

2021-04-02 10:05 UTC, ksundong approved these changes
안녕하세요! Jung!! 리뷰가 늦어져서 죄송합니다. 😭
코드가 많이 깔끔해서 좋은 것 같아요.
고생많으셨습니다!

다음단계 바로 PR 제출해주셔도 좋을 것 같아요!

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>              throw new UnauthorizedUserException(UnauthorizedUserException.WRONG_PASSWORD);
비밀번호가 잘못되었다고 사용자에게 혹시 알려주나요?

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QuestionNotFoundException.java
> +public class QuestionNotFoundException extends QnaException {
👍

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exception/QuestionNotFoundException.java
> +    public static final String QUESTION_NOT_FOUND_MSG = "찾으시는 질문이 존재하지 않습니다.";
👍

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
>      private final QuestionService questionService;
👍

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +    public List<Answer> findByQuestionId(Long questionId) {
Repository의 내용이 그대로 노출되기 보다는 좋은 이름을 한 번 고민해봐주세요~
사실 노출이 되어도 상관 없긴 합니다. 😊

2021-04-02 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +                .orElseThrow(QuestionNotFoundException::new);
👍

2021-04-02 10:06 UTC, merged