[이노] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #13
Opened 2021-03-04 13:01 UTC by eNoLJ

미션 1 진행했습니다. 요구사항에 있는 부분들을 중점으로 충실히 구현했습니다.
폴더와 컨트롤러 메소드 이름을 최대한 어울리도록 지어봤는데 맞는 형식인지 모르겠네요. 혹시 이부분에 대해서 좀 더 나은 방법이나 써야하는 이름이 있다면 알려주시면 감사하겠습니다.

이번 스프링 미션도 잘부탁드립니다!!
항상 리뷰 감사드려요.

배포 URL : https://enolj-spring-qna.herokuapp.com

2021-03-05 00:33 UTC, wheejuni requested changes
전반적으로 구현을 쉽고 빠르게 잘 해주셨네요! 👍 💯 
생각해볼 점 두 가지만 짚어보고 merge하면 될 것 같아요.
수고 많으셨습니다~

2021-03-05 00:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    Questions questions = new Questions();
`public`? `private`? 뭐가 좋을까요?

2021-03-05 00:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +        question.setId(this.questionList.size() + 1);
질문 삭제 기능이 추가되면 어떻게 하죠?

2021-03-05 02:33 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    Questions questions = new Questions();
저 부분을 깜박하고 있었네요. QuestionController와 UserController의 자료구조에 private의 접근제어자를 만들어줬습니다!!
감사합니다.

2021-03-05 02:34 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +        question.setId(this.questionList.size() + 1);
디온의 말을 듣고 Questions와 Users 클래스에 delete 메소드를 만들었습니다. 그리고 두 클래스의 메소드 모두 find와 delete 메소드에 인덱스 값이 필요하여 이부분을 따로 getIndex 메소드로 따로 만들어봤습니다.

2021-03-05 02:35 UTC, eNoLJ commented
이번 리뷰도 감사드립니다!!
좋은 하루 되세요.

2021-03-05 03:13 UTC, wheejuni requested changes
빠르게 수정 잘 해주셨는데 다른 궁금한 점들이 생겨서 코멘트 달아봤습니다.

2021-03-05 03:13 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +        question.setId(this.questionList.size() + 1);
그게 아니라 `ID` 는 `questionList` 의 크기와 상관없이 부여돼야 한다고 말씀드린 거였는데요.
질문 ID는 독립적으로 부여되어야 나중에 유연하게 대응할 수 있을 듯해요.

2021-03-05 03:13 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +                .orElse(-1);
이런 목적이라면 `IntStream` 이 아니라 `questionList` 에서 시작되는 스트림을 만드는게 더 효율적이지 않을까요?

2021-03-05 08:11 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +        question.setId(this.questionList.size() + 1);
이해를 잘 못했었네요. delete에 관한 메소드는 현재는 불필요하여 일단 다시 삭제했습니다. 그리고 말씀하신 부분은 따로 id값을 관리하는 멤버변수를 만들어 부여하게 했습니다!!

2021-03-05 08:19 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/repository/Questions.java
> +                .orElse(-1);
여기서 IntStream으로 한 이유는 해당 질문의 index값을 알기 위해서 사용했습니다. 말씀해주신 questionList로 스트림을 만들면 index값을 얻을 방법이 없더라구요.

그리고 위에 리뷰해주신 사항 외에도 회원정보수정 부분에 못보고 구현하지 못한 부분 구현했습니다.
아이디는 변경 불간으해야한다. -> readonly로 바꿨습니다.
비밀번호가 일치해야한다. -> 새로운 비밀번호를 받는 입력창을 하나 더 만들었습니다.
회원정보 수정 요청을 post에서 put으로 바꿨습니다.

저장되어 있는 유저와 질문을 요청하는경우 페이지 전환이 되도록 UserController와 QeustionController를 변경했습니다.

오후에 그룹에서 리뷰하는 시간을 가졌는데 그때 얘기가 나와던 부분들도 추가해 봤어요. 변경된 내용이 많아서 다시 리뷰하는 기분이시겠지만 보시고 코멘트 부탁드립니다!!!!!

2021-03-06 11:10 UTC, wheejuni approved these changes
미션 1에서 진행하시기에 충분한 경험을 하신 것 같아 merge 하겠습니다. 💯 
수고하셨습니다.

2021-03-06 11:10 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/HttpMethodFilter.java
> +    }
헉 갑자기 이건 왜 추가된거죠;; ㄷㄷ

2021-03-06 11:10 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/Question.java
> +        SimpleDateFormat simpleDate = new SimpleDateFormat( "yyyy-MM-dd HH:mm");
`static` 으로 한번 만들어두고 계속 다시써도 괜찮아 보여요.

2021-03-06 11:10 UTC, merged

2021-03-06 11:26 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/config/HttpMethodFilter.java
> +    }
@wheejuni

그룹 리뷰시간에 해당 내용이 나와서 궁금해서 해봤어요ㅋㅋㅋㅋ UserController에 updateProfile 메소드에서 putmapping을 하려고 만들었습니다.
updateForm.html 파일에
```html
<form name="user" method="post" action="/user/{{userId}}/update">
                  <input type="hidden" name="_method" value="put" />
```
이렇게 해놓고 컨트롤러에서 put으로 받았습니다. 근데 말씀하신 저 필터가 없으면 안들어오더라구요. 혹시 이부분에 대해 짧게라도 의견 있으시면 말씀해주시면 감사하겠습니다!!!ㅎㅎ

2021-03-06 11:27 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/Question.java
> +        SimpleDateFormat simpleDate = new SimpleDateFormat( "yyyy-MM-dd HH:mm");
이 부분은 다음 미션에 적용하도록 하겠습니다.
그리고 매번 제 코드 리뷰해주셔서 감사해요!!