[마르코 & Woody] Mission 4 PR 요청 드립니다.
codesquad-members-2021/spring-boot-qna pull request #130
Opened 2021-03-29 07:08 UTC by jihye-woo

안녕하세요 👬 마르코, 우디 입니다!

이번 미션은 간단하게 soft-delete만 구현해서 그렇게 오래걸리지 않았습니다!

### 📃Soft Delete 구현 내용
Question과 Answer 엔티티 클래스 - 어노테이션 및 필드 추가

#### 1. isActive 필드 추가
  -  현재 엔티티가 delete된 상태라면 false, 반대의 경우에는 true
#### 2. `@SQLDelete` 어노테이션 추가
  - Delete 요청 시, SQLDelete 어노테이션을 통해 지정한 sql문이 실행되도록 설정
  - `@SQLDelete(sql = "UPDATE {엔티티 이름} SET is_active = '0' WHERE id = ?")`
#### 3. `@Where` 어노테이션 추가
  - 엔티티와 관련된 쿼리 수행 시 where 구에 is_active == true 조건을 항상 추가하도록 설정

감사합니다!!✨✨

2021-03-29 11:57 UTC, ksundong requested changes
안녕하세요! 마르코와 Woody!! 리뷰어 Dion입니다.
변경사항이 별로 없어서, 리뷰할 내용이 그렇게 많지는 않았네요.
혹시 이전 단계에서 다른 요구사항을 다 충족시켜주셨던 걸까요?

## 웹 애플리케이션 관련 리뷰

- 중복 회원가입이 가능합니다. 한 번 방지하는 로직을 구현해보세요.
- 도전하는 의미에서, 사용자의 입력에 대한 유효성 검사를 진행해보세요.
- 질문하기 페이지의 CSS가 깨집니다. 회원정보 수정도 마찬가지에요~
  ![image](https://user-images.githubusercontent.com/38597469/112830988-4201a980-90ce-11eb-8315-a0b92010d30d.png)
- 질문 상세보기 페이지에서 출력되는 시간을 포매팅해서 출력해주세요.
- 수정 완료 후 해당 글로 이동하는게 좋지 않을까요?
- 다른 사람의 회원정보 수정 시도시 500에러가 발생합니다.
- 다른 사람이 작성한 글을 수정, 삭제 시도시 500에러가 발생합니다.
- 다른 사람의 답변이 있는 글을 삭제 시도했을 때, 삭제가 가능합니다. (요구사항을 참고해주세요.)
- 사용자 아이디가 수정이 가능한가요? 이전 단계의 요구사항을 확인해보세요. (필드가 입력가능합니다.)
- 회원정보 수정 시 기존 이메일이 표시되지 않습니다.
- 사용자 입장에서 보면, 인터렉션이 없어서, 내가 한 작업이 완료가 되었는지 확인하기 힘듭니다.

## 코드관련 리뷰

`QuestionController.java` 의 이 부분 redirect 하는 방식으로 변경해주세요!
```java
    @GetMapping("/")
    public String list(Model model) {
        model.addAttribute("questions", questionService.findQuestions());
        return "index";
    }
```

그런 다음 `@RequestMapping`으로 중복을 제거해보세요~

이 부분 url 변경해주세요. RESTful한 url을 지향해주세요~
```java
    @PutMapping("{id}/update")
    public String updateUser(@PathVariable Long id, String oldPassword, User updateUser) {
        User targetUser = userService.findUserById(id);
        if (targetUser.isMatchingPassword(oldPassword)) {
            targetUser.update(updateUser);
            userService.create(targetUser);
            return "redirect:/users";
        }
        return "redirect:/users/{id}/form";
    }
```

if 문이 한 줄 이더라도 중괄호를 꼭 넣어주세요.
```java
    @GetMapping("/questions/form")
    public String viewQuestionForm(HttpSession session) {
        if (!HttpSessionUtils.isLoginUser(session))
            return "redirect:/users/loginForm";
        return "qna/form";
    }
```

이 메서드는 answer가 직접 처리하는 편이 깔끔할 것 같습니다.
```java
    public boolean verifyAnswer(Answer answer, User sessionedUser) {
        return sessionedUser.isMatchingUserId(answer.getWriter());
    }
```

4단계를 짝프로그래밍으로 진행하느라 고생많으셨습니다.
변경할 부분이 조금 보여서 **변경 요청** 드립니다.
변경된 코드는 대부분 깔끔했고, 아무래도 볼 코드가 없어서 직접 레포지토리 들어가서 확인했는데, 조금 걸리는 부분들에 리뷰를 더 남겼습니다.
궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는부분, 토론하고 싶은 부분은 언제든 두 분 다 코멘트 남겨주세요.
고생하셨습니다~

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET is_active = '0' WHERE id = ?")
다들 이 방법을 많이 사용하시는 군요 ㅎㅎ

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@Where(clause = "is_active=1")
위와 작성해주신 형식이 다르네요.

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime time = LocalDateTime.now();
time 보다는 더 명확한 이름을 사용해주세요.

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Column
이 애노테이션은 굳이 필요없을 것 같은데요!

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private Boolean isActive = true;
Wrapper Type을 사용해주셨는데, isActive가 Null인 경우가 있나요?

2021-03-29 11:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
빈 라인은 제거해주세요~

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET is_active = '0' WHERE id = ?")
사실 처음에는 Repository에서 delete() 메소드를 오버라이드 한 뒤에 `@Query`로 쿼리문을 작성해봤었는데요! 
영속성 전이가 되지 않아서(Question을 삭제했는데 Answer가 함께 삭제되지 않는 문제가 있었습니다..!)
[다른 방법](https://stackoverflow.com/a/36632922)을 찾아봤더니 `@SQLDelete`으로 하는 방법을 추천한다는 글을 보고 수정했더니 해결되었습니다!

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@Where(clause = "is_active=1")
`@SQLDelete(sql = "UPDATE ANSWER SET is_active = '0' WHERE id = ?")`와 `@Where(clause = "is_active=1")`에서 is_active 값에 대한 형식('0'과 1)이 다르다라는 말씀으로 이해하고 한 가지 방법으로 통일했습니다!

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime time = LocalDateTime.now();
확실히 제너럴한 의미라서 좀 더 명확하게 바꿔주는 것이 좋겠네요! 
createdAt이라는 이름으로 수정했습니다! 감사합니다!

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Column
앗 그러네요 어노테이션 붙인게 딱히 의미가 없네요!ㅠ
그냥 넘어갔던 부분이었는데 짚어주셔서 감사합니다!

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
넵! 코드 포멧팅 완료했습니다아..!!

2021-03-31 06:17 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private Boolean isActive = true;
그렇군요..! 처음에는 큰 차이가 없겠다 싶었는데 
다시 보니, reference 타입일 경우 초기화가 안되었을 경우 null이 반환될 수도 있군요..! 
물론 필드에서 초기화를 시켜주긴했지만 어쨌든 불필요해보이니 value 타입으로 바꾸는게 더 좋겠네요!
디테일!!✨✨ 감사합니다!

2021-03-31 07:05 UTC, jihye-woo commented
코멘트 주신 부분들은 수정 완료하였습니다..! 다시 PR 요청 드려요!

🔗 배포 링크 https://springqna.herokuapp.com/

그리고 '사용자 입장에서 보면, 인터렉션이 없어서, 내가 한 작업이 완료가 되었는지 확인하기 힘듭니다.'라는 말씀을 보고 반영을 하는게 좋을 것 같다고 생각했지만, 에러 메시지를 출력하는 것만으로도 코드가 복잡해지는 바람에 완료 작업에 대한 메시지는 따로 띄우지 않는 상태입니다..!

혹시 완료 작업에 대한 안내는 미션 5에서 진행해도 괜찮을까요? Restcontroller + js + Result 객체를 활용하면 서버 코드에 특별한 로직을 추가하지 않아도 될 것 같아서 완료 작업 메시지는 이 방식으로 시도해보고싶습니다..!

감사합니다!!

2021-03-31 14:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET is_active = '0' WHERE id = ?")
혹시 그런 현상이 왜 일어나는지 탐구해보셨나요?
Cascade 옵션을 주어도 해당 현상이 발생했었나요?

2021-03-31 14:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime time = LocalDateTime.now();
저는 createDateTime을 더 선호하긴 합니다 ㅎㅎ

2021-03-31 14:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private Boolean isActive = true;
필드 초기화가 항상 안전하지 만은 않습니다.

2021-03-31 15:14 UTC, ksundong approved these changes
안녕하세요! 마르코 & Woody! 피드백 반영해주시느라 수고하셨습니다.
다음 단계 진행해주셔도 좋을 것 같고, 코멘트를 참고해주세요.

## 웹 애플리케이션 관련 피드백

- 자세히 보면 수정 버튼 위의 CSS가 조금 다릅니다. 한 번 고쳐보실까요?
  ![image](https://user-images.githubusercontent.com/38597469/113167427-ad8a7900-927e-11eb-9645-27c6d3817d2d.png)
- 질문쪽은 아직 검증이 안되는군요?
- 요구사항 중 하나인 '다른 사람의 답변이 있는 글을 삭제 시도했을 때, 삭제가 불가능해야한다'는 요구사항이 지켜지지 않았습니다.

대부분은 잘 구현해주셔서 다음 단계 바로 진행하셔도 좋을 것 같아요!
다음단계로 갑시다~

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/HandlebarHelper.java
> +    public static CharSequence formatDateTime(LocalDateTime createdAt) {
이쪽의 네이밍은 일반적인 이름을 주는게 좋을것 같습니다./

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        if (!answerService.delete(answer, sessionedUser)) {
answer에게 delete 가능한지 물어보는 구조로 구현해봐도 좋을것 같네요.
이것도 괜찮아요!

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        if (!answerService.delete(answer, sessionedUser)) {
가급적이면 Service에 id를 넘겨서 하는방식이 더 좋다고 생각됩니다.
Domain이 Controller까지 드러나는 것은 별로 좋지 않은 구조라고 생각돼요. (User를 제외하고요)

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String visit() {
그냥 동사 말고 home 정도여도 괜찮을 것 같습니다.

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (!question.isMatchingWriter(sessionedUser)) {
👍

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            logger.info(user.toString());
```suggestion
            logger.info("user: {}", user);
```

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            logger.info(user.toString());
로깅도 잘 해야하는데, 저는 이런 코드는 debug로 남깁니다.

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            throw new NotLoginException("로그인하실 수 없습니다.");
NotLogin은 뭔가 영어식으로 맞지 않는 표현인 것 같네요~

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            throw new NotLoginException("로그인하실 수 없습니다.");
차라리 Unauthenticated가 알맞아 보입니다. 이건 그냥 예시에요~

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            model.addAttribute("error", "자신의 정보만 수정할 수 있습니다.");
이런 문자열 상수는 추출하는 편이 좋겠죠?

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@Where(clause = "is_active=1")
```suggestion
@Where(clause = "is_active = 1")
```
이렇겐 안되나요?

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private boolean isActive = true;
빈 라인 제거해주세요!

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private boolean isActive = true;
좀 더 간단하게 표현하면 isDeleted로 하면 true값이 없어도 되겠죠?

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return userId.equals("") || password.equals("") || name.equals("") || email.equals("");
userId가 null이면 NPE가 날겁니다.
보통은 `"".equals(userId)`가 더 안전하고, 중복이 많이 되니, 별도의 utility 메서드로 추출하는 게 낫겠습니다.

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return userId.equals("") || password.equals("") || name.equals("") || email.equals("");
`isEmpty(String string)`과 같은 메서드면 되겠죠?

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/dto/QuestionDto.java
>      }
이 setter는 과연 필요할까요?

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +public class AnswerService{
```suggestion
public class AnswerService {
```

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
>          Question question = questionRepository.findById(questionId).orElseThrow(IllegalArgumentException::new);
AnswerService에서 QuestionRepository에 직접 접근하지 않도록 QuestionService를 거쳐서 이용하도록 바꿔봅시다.
저는 이런 형태의 구현을 선호합니다. (별도의 로직이 들어가지 않는다면 상관없지만, 들어가도록 바뀐다면 어떨까요?)

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer findAnswerByAnswerId(long answerId) {
Repository Method의 이름을 그대로 따오는 네이밍은 별로 추천드리고 싶지 않습니다.

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public boolean delete(Answer answer, User user) {
delete 결과는 주지 않아도 됩니다.
실패하면 예외를 던져주는게 더 일반적이겠죠.

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return userRepository.findUserByUserId(userId).orElseThrow(() -> new NotLoginException("로그인하실 수 없습니다."));
로그인 할수 없는거 맞나요?
못찾아서 생긴 오륜데요!

2021-03-31 15:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return !userRepository.findUserByUserId(user.getUserId()).isPresent();
exists라는 쿼리도 있습니다.

2021-03-31 15:14 UTC, ksundong commented on src/main/resources/templates/qna/form.html
> +                <div class="clearfix"/>
이건 왜 들어왔나용?

2021-03-31 15:14 UTC, ksundong commented on src/main/resources/templates/user/create_failed.html
> +            <div class="alert alert-danger" role="alert">중복된 아이디이거나 비어있는 부분이 존재합니다. 다시 입력해주세요.</div>
이 메시지를 create form 쪽에 두고, 조건에 따라서 노출되게 하는 기법을 도입해봅시다.

2021-03-31 15:14 UTC, ksundong commented on src/main/resources/templates/user/update_failed.html
> +                <div class="alert alert-danger" role="alert">기존 비밀번호가 일치하지 않습니다. 다시 입력해주세요.</div>
여기도 마찬가지의 피드백입니다.

2021-04-01 12:08 UTC, ksundong commented
@95degree @jihye-woo 
다음 단계 진행중이신가요? 머지할까요~?

2021-04-02 09:15 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/HandlebarHelper.java
> +    public static CharSequence formatDateTime(LocalDateTime createdAt) {
넵!! 말씀하신대로 `formatedDateTime`이 더 맞는 것 같아서 수정하도록 하겠습니다!

2021-04-02 09:15 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String visit() {
넵! 수정하도록 하겠습니다!!

2021-04-02 09:35 UTC, jihye-woo commented on src/main/resources/templates/qna/form.html
> +                <div class="clearfix"/>
css 깨지는 현상 말씀해주셔서 `<div class="clearfix"/>` 추가하니까 해결되더라구요!

2021-04-02 09:38 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (!question.isMatchingWriter(sessionedUser)) {
말씀하신대로 수정했습니다ㅎㅎ 감사합니당

2021-04-02 10:52 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +public class AnswerService{
앗... 포멧팅..ㅎㅎ 신경쓰겠습니다!ㅠㅠ

2021-04-02 10:53 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/dto/QuestionDto.java
>      }
생각해보니 질문 작성 시간은 생성자에서 설정해준 뒤로는 수정될 일이 없기 때문에 setter가 따로 필요하진 않겠군요!! 삭제했습니다! 디테일 감사드려요!!👀

2021-04-02 10:57 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return userId.equals("") || password.equals("") || name.equals("") || email.equals("");
와아..👍 이 문제는 전혀 생각 못하고 있었는데 세심히 봐주셔서 감사해요!!
이런 상황에서는 NPE가 날 수 있군요!!! 
말씀하신대로 StringUtils라는 유틸 클래스를 만들고, User 내부의 isEmpty()에서는 StringUtils의 메소드를 통해 값들을 비교할 수 있도록 수정하였습니다..! 감사합니다!😀

2021-04-02 11:04 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private boolean isActive = true;
앗 그렇군요! 이렇게하면 굳이 필드에서 초기화를 직접 해줄 필요가 없겠군요!
(제가 이해하기로는..!) 말씀하신대로 초기화를 하지 않으면 default value인 false값이 들어가는 기능(?)을 사용해서 
`isDeleted`로 변경하고 초기화하는 코드를 삭제해주었습니다..!! 훨씬 깔끔하네용👍

2021-04-02 11:06 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private boolean isActive = true;
사실... 빈라인이 어떤 의미인지 정확하게 이해하지 못해서 제거해주지 못했습니다...ㅠ  인텔리제이의 코드 포멧팅으로는 잡아내지 못했네용 흛흐...

2021-04-02 11:07 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@Where(clause = "is_active=1")
앗 바로 수정해주었습니다..! 코드 포멧팅을 너무 맹신하고 있었네요..ㅠㅠ 스트링까지 확인하지 못했습니다 흛흐😂

2021-04-02 11:10 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            throw new NotLoginException("로그인하실 수 없습니다.");
네이밍이 제일 어렵네요..ㅠ 예시라고 하셨지만, 말씀하신대로 수정..하고 싶어서 수정했습니다...!!

2021-04-02 11:27 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            logger.info(user.toString());
앗 그렇군요..! 로깅 레벨에 대해서 아직 명확한 차이를 못느끼고 있어서 좀 더 알아 볼 필요가 있겠네요..ㅠㅠ
코멘트 주신 덕분에 한 번 더 로깅 레벨에 대해서 들여다 볼 수 있었습니다!!
info 로그는 확실히 좀 더 프로그램 실행에서 유의미하다고 생각되는 정보들(설정 정보 등)만 설정해놓는게 좋을 것 같네요!!(맞나요..?👀)

2021-04-02 14:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String visit() {
꼭 동사가 아니어도, 괜찮더라고요?
동사를 붙이면 어색해지는 경우가 종종 있었는데
엘레강트 오브젝트라는 책에서 빌더라고 불리는 형태의 메서드입니다. (빌더 패턴이 아니에요!)

2021-04-02 14:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            logger.info(user.toString());
유의미한 정보라고 판단된다면, 얼마든지 남겨줄 수 있습니다.
다만 성능상의 문제도 있기 때문에, 유의미한 정보를 적절히 판단해야겠죠.

2021-04-02 14:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private boolean isActive = true;
30번 라인?을 제거해주세요!

2021-04-02 14:02 UTC, ksundong commented
머지할게요! 고생하셨습니다~

2021-04-02 14:02 UTC, merged