[Bibi&이노] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #133
Opened 2021-03-30 09:20 UTC by bibi6666667

안녕하세요, 백엔드반의 Bibi입니다😀
이노와 함께 미션4를 모두 진행해 Pull Request 드립니다!
이번 미션에서는 선택사항인 질문 삭제하기(soft-delete)까지 모두 구현했습니다.

<❗ 이번 미션에서 배운 점>
- 객체들 간의 관계 맵핑을 이해하기
  - User-Question, Question-Answer 관계를 왜 맵핑해야 하고 어떤 어노테이션을 사용해야 하는지
  - 객체 관계를 맵핑하고 나면 무엇이 달라지는지
- Question←Answer라는 종속관계가 각 객체에 미치는 영향(...)
  - 종속관계로 인해 각 클래스를 로직을 짤 때 어떻게 신경써야 하는지(🤯..)
- soft-delete 이해하고 구현하기
  - Question의 deleted상태와, 종속된 Answers의 deleted상태에 따른 삭제 로직 구현하기(🤯🤯....)
  - handlebars로 `deleted=false`인 항목만 뷰에서 보여주기

<❓ 이번 미션에서 궁금했던 점>
- QuestionService 클래스에서 delete 처리하기 
  ```java
  @DeleteMapping("/{questionId}")
  public String deleteQuestion(@PathVariable Long questionId, Model model, HttpSession session) {
      boolean result = questionService.delete(questionId, getUserFromSession(session));
      if (!result) {
          model.addAttribute("question", questionService.findById(questionId));
          model.addAttribute("errorMessage", ErrorMessage.DELETE_FAILED);
          return "qna/questionDetail";
      }
      return "redirect:/";
  }
  
Question을 Delete할 때, 미션 제약조건에 따라 "질문자와 답변자가 다른 경우" 질문 작성자 본인이라도 자신의 질문을 삭제할 수 없어야 합니다. 처음에는 지금껏 Exception을 던진 것처럼 기존 예외를 활용하거나 새로운 예외를 선언해 throw하려고 했습니다. 하지만 이런 상황은 '예외'상황이라기보다는 삭제할 수 없는 경우일 뿐이므로, Exception으로 처리하기보다는 Model에 에러메시지만 보내주는 것이 낫겠다고 이노가 제안하셨고 저도 이 부분에 동의해 이렇게 코드를 짰습니다.
혹시 이 방법보다, 그냥 처음에 생각했듯 Exception으로 처리하는 게 더 나았을까요? 아니면 제3의 더 좋은 방법이 있을까요? 저희의 판단이 맞는지 조언을 부탁드립니다.
- soft-delete
Question과 Answer에 soft-delete를 구현한 뒤에는, `deleted=false`인 항목만 화면에 표시되어야 합니다.
이 때 Controller/Service선에서 `deleted=false`인 항목만 뷰에 보내주는 게 나을지, 아니면 기존처럼 Question들과 Answer들을 모두 보낸 뒤 뷰에서 handlebars 문법을 활용해  `deleted=false`인 항목만 보여주는 게 나을지를 고민했는데, 지금은 후자를 선택했습니다.
어떤 방법이 더 바람직한 방법인가요? 아니면 역시 제3의 다른 방법이 있다면 조언을 부탁드리겠습니다.🙇‍♀️

이번 미션도 배울 거리와 고민할 거리가 아주 많았던 것 같습니다😀
힘들기도 하고, 아직 다 이해는 되지 않지만 그래도 따라하는 과정 중에도 배우는 게 많네요.

이번 PR도 잘못 구현한 점, 바람직하지 못한 점, 더 개선할 만한 점.. 등등 많은 피드백 부탁드리겠습니다!
요즘 날씨가 정말 좋은데(미세먼지는 빼고요😷) 리뷰어 분들도 행복한 한 주 되세요🌸.

- Bibi 올림

2021-03-30 15:11 UTC, sonypark requested changes
안녕하세요 비비&이노, 리뷰어 소니 입니다.😊
페어프로그래밍으로 미션 구현하느라 고생 많으셨습니다.
같이 하면 혼자할때에 비해 시간도 오래걸리고 체력 소모도 많지만, 그만큼 집중하고 서로 의견 나누며 배우는것도 많을거라 생각됩니다. 커밋 로그도 꼼꼼히 남겨주시고 질문하신 내용을 봐도 고민하며 작성한게 느껴집니다.

질문 주신 내용과 이번 미션의 요구사항에 대해 몇가지 코멘트 남겼는데요.
수정해야할 부분이 꽤 있을 것 같아요! 차근차근 반영해보시면 좋겠네요.
추가 질문있으시면 코멘트로 남겨주세요~

++ heroku 링크에서 테스트 해본 결과 답변 추가가 되지 않는데, 이 부분도 확인 부탁드려요~

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    private static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
위치를 최상단으로 이동해주세요~

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Answer.java
> +
이 메서드가 필요할까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    }
getter,setter 가 무분별하게 선언되어 있는것 같아요. 정말 다 필요한 메서드일까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    }
메서드가 아닌 생성자를 통해서 주입 받는건 어떨까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Answer.java
> +}
양방향 연관관계를 가진 엔티티가 toString() 메서드에 포함되어 있을 때 어떤 문제가 발생할까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Question.java
> +    private String title;
```suggestion
    @Column(nullable = false)
    private String dateTime;
    
    @Column(nullable = false)
    private String title;
```

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Question.java
> +    }
여기도 getter, setter가 정말 다 필요한 메서드인지 생각해보세요~

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/Question.java
> +}
여기도 toString()에 연관관계를 같는 엔티티를 호출하네요

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/User.java
> +    }
음.. 모든 엔티티에서 메서드를 이용해 초기화를 해주는군요.
생성자를 이용한 방식으로 변경해보시면 어떨까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    private QuestionRepository questionRepository;
Field Injection의 단점은 무엇이 있을까요?
아래 링크를 참고해서 공부해보세요~🧐

[생성자 주입을 @Autowired를 사용하는 필드 주입보다 권장하는 하는 이유](https://madplay.github.io/post/why-constructor-injection-is-better-than-field-injection)

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    private QuestionRepository questionRepository;
여기도 생성자 주입을 고려해보세요~

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/utils/ErrorMessage.java
> +public enum ErrorMessage {
ErrorMessage를 enum으로 만드신것은 좋은데, 위치는 utils 보다는 exception 패키지로 옮겨주시면 더 좋을 것 같아요

2021-03-30 15:11 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        return "index";
HomeController에서 QuestionService를 의존하기 보다, QuestionController의 질문 목록 조회 메서드를 호출하도록 리다이렉트 해보는건 어떨까요?

2021-03-30 15:11 UTC, sonypark commented on src/main/resources/templates/index.html
>                          <div class="main">
현재 handlebars로 deleted=false인 항목만 뷰에 보여주고 있는데요
이렇게 되면 DB에서 매번 모든 항목을 다 가져온 후 분기해줘야 되는 구조겠네요.
데이터가 10만개이고, 그 중 삭제된 데이터가 5만개라면 어떻게 될까요? DB에서 삭제가 안된 5만개만 가져오면 되는데, 전체 데이터인 10만개씩 가져와서 분기를 해주는건 비효율적이겠죠?

DB에서 삭제되지 않은 항목만 필터링해서 가져오도록 수정해보세요~

2021-03-31 02:41 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    private static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
최상단으로 이동했습니다!!

2021-03-31 02:44 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/Answer.java
> +}
양방향 관계를 가지게되면 순환참조가 일어나는 걸 이해했습니다. 해당 부분 수정했어요!!

2021-03-31 02:44 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/model/Question.java
> +    private String title;
개행 추가하겠습니다!😅

2021-03-31 02:45 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/Question.java
> +}
이쪽도 수정했습니다!!

2021-03-31 02:46 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    private QuestionRepository questionRepository;
해당 글 잘 읽었습니다. 이런 부분은 생각을 해보지 못했는데 덕분에 생각해 볼 계기가 되었네요ㅎㅎ
그리고 수정 완료 했습니다!!

2021-03-31 02:46 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/utils/ErrorMessage.java
> +public enum ErrorMessage {
넵 ErrorMessage 파일 패키지를 exception로 변경하겠습니다!😀

2021-03-31 02:47 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    private QuestionRepository questionRepository;
마찬가지로 수정했습니다.

2021-03-31 02:47 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        return "index";
HomController에서 QuestionController의 viewMain 메서드로 이동하도록 만들었습니다.
말씀하신 의도가 이게 맞을까요??

2021-03-31 02:48 UTC, eNoLJ commented on src/main/resources/templates/index.html
>                          <div class="main">
question repository에서 findAllByDeletedFalse를 만들어 필터링해서 가져오게 만들었습니다.

2021-03-31 03:20 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/User.java
> +    }
@sonypark
현재 모든 엔티티 클래스에서 생성자를 만들어서 초기화를 해주는걸 추천해 주셨는데 그 부분에 대해서 질문 사항이 있습니다.

먼저 저희는 

```java
@PostMapping("/signup")
    public String signup(User user) {
        userService.save(user);
        return "redirect:/users";
    }
```
처럼 초기화를 컨트롤러에 매개변수로 사용하여 컨트롤러의 set 메소드를 통해 초기화가 되도록 구현을 했습니다.
현재 제가 소니의 리뷰를 이해한 바로는 User, Answer, Question 클래스의 save 메소드를 생성자로 대체 하고 update나 delete는 지금 처럼 메소드를 사용하라는 걸로 이해를 했습니다.
이 상황에서 소니의 리뷰를 적용하려 해봤는데 

User class에
```java
public User(String userId, String password, String name, String email) {
        this.userId = userId;
        this.password = password;
        this.name = name;
        this.email = email;
    }
```
이러한 생성자를 만들어서

UserController에서
```java
@PostMapping("/signup")
public String signup(String userId, String password, String name, String email) {
    userService.save(new User(userId, password, name, email));
    return "redirect:/users";
}
```
이런식으로 사용을 하란 말씀인가요?? (메소드의 내용은 당연히 보완을 할 예정입니다. 예시로만 봐주세요!!)

저렇게까지 분리를 하게 되면 DTO 클래스를 User, Answer, Question 각각 다 만들어서 받아 쓰는게 좋을 것 같아져서 내용 수정이 너무 많아지네요.
물론 현재 매개변수로 엔티티 클래스를 사용하는거에 있어서 문제가 있다는 건 숙지하고 있습니다. 엔티티 클래스는 db와 직접적인 연관을 갖는 클래스라 request나 response 객체는 따로 DTO를 만들어 사용해야 하는 것도요. 이 부분을 이번 주에 알게되어 수정을 다 하지 못한 점은 반성을 하고 있습니다.

제가 이해한 바가 맞는지 아님 다른 의도가 있으셨다면 조금 더 자세한 설명 부탁드리겠습니다!!

2021-03-31 13:58 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        return "index";
네 맞습니다 😊

2021-03-31 14:17 UTC, sonypark commented on src/main/java/com/codessquad/qna/model/User.java
> +    }
네 이노가 이해하신 부분이 맞습니다.

1. 생성자를 이용한 초기화를 권장하는 이유는 객체가 생성되었을 때의 불완정성을 줄이기 위함입니다. 이전 코드에서는 Answer나 Question의 경우 save 메서드로 User 나 Question을 주입해주고 있습니다. 이 경우 객체가 생성되고 save 메서드로 필드를 주입해주기 전까지는 해당 필드가 null 인 상태로 객체의 상태가 불완전한 상태입니다. save 메서드로 주입해주는걸 잊을 경우 NPE가 발생할 가능성이 높고 해당 엔티티의 본래 역할을 할 수 없을 가능성이 높습니다. 하지만 생성자를 통해 필요한 필드를 모두 주입해주게 되면 이러한 문제가 발생할 가능성을 차단할 수 있습니다. 이러한 이유로 생성자를 통한 초기화를 권장드렸습니다. -- User의 경우 request에서 필요한 필드를 모두 주입해주기 때문에 위에서 말씀하신 예시는 User로 받아도 괜찮습니다. (물론 DTO를 사용하시면 더 좋겠죠?)

2. 답변하신 내용을 보니 엔티티로 request의 데이터를 직접 매핑할 때의 문제점과 엔티티 대신 DTO를 사용해야하는 이유를 알고 계신것 같습니다. 아직 다른 분들도 DTO를 사용한 분은 거의 보지 못해서 말씀만 드리고 그냥 넘어간 경우가 많은데, 적용가능하시면 한 번 도전해보시는 것도 좋겠네요.

2021-03-31 14:23 UTC, sonypark commented
@bibi6666667 @eNoLJ  heroku 링크에 답변 등록이 안되는것 같은데, 아직 반영되기 전인가요~?

2021-04-01 01:33 UTC, eNoLJ commented
@sonypark 어제 수정사항 다 적용하고 배포하자 싶어서 넘어갔었는데 깜박했네요;; 다시 배포 했습니다!!

2021-04-01 09:31 UTC, sonypark commented
링크에 반영된거 확인했습니다 :)
추가적으로 개선할점 반영 되면 리뷰 요청 주세요~

2021-04-01 10:44 UTC, eNoLJ commented
@sonypark 
UserDto, QuestionDto, AnswerDto 클래스를 만들어 컨트롤러의 request와 response에 사용하도록 수정했습니다. 그리고 불필요한 getter, setter 메소드는 제거 했습니다. 또한 entity 객체는 최대한 스스로 상태를 변경하지 않도록 구현했습니다. (Answer entity는 부분적으로 실패 했습니다. 스스로 상태를 변경하는 메소드가 들어가 있어요...) 그래서 진행하면서 궁금한 점이 생겼습니다.

1. dto 클래스 안에 ManyToOne이나 OneToMany로 매핑되어 있는 객체들도 dto 클래스여야 하나요?? 그러니까 QuestionDto 클래스에 writer가 ManyToOne으로 매핑되어 있는게 writer 또한 UserDto를 사용해야 하는 것인지 궁금합니다. 일단 제 판단으로는 그렇게 해야하는 게 맞다고 생각해서 그렇게 수정했습니다. 이유는 그렇게 하지 않으면 entity 클래스에 비지니스 로직이 생기더라구요. 현재 상태에선 Answer 클래스에 matchWriter, delete 메소드가 그렇다고 생각합니다.

2. QuestionDto에 answers도 List<AnswerDto> answers 로 관리를 하고 싶어서 
```java
public QuestionDto(Question question) {
    this.id = question.getId();
    this.writer = new UserDto(question.getWriter());
    this.dateTime = question.getDateTime();
    this.title = question.getTitle();
    this.contents = question.getContents();
    this.answers = `changeAnswerToAnswerDto(question.getAnswers());`
    this.deleted = question.isDeleted();
}

public List<AnswerDto> changeAnswerToAnswerDto(List<Answer> answers) {
    return answers.stream()
            .map(AnswerDto::new)
            .collect(Collectors.toList());
}
```

처럼 구현을 했더니 stackoverflow 에러가 떳습니다. 이유는 Answer의 Question이 있고 그 Question에 또 Answer가 있어서 Answer를 AnswerDto로 바꿀 때 계속 순환이 되어 문제가 발생했습니다. 이 부분 해결할 수 있는 방안이 있을까요??

질문 1에서 언급했듯이 List<answer>로 정의되어 있어서 Answer 클래스에 맞지 않게 matchWriter, delete가 사용되어 걸리적 거리네요...

최대한 열심히 진행해 봤습니다!! 그리고 혹시라도 더 변경할 사항이 생긴다면 다음 미션에서 수정을 할수있도록 해주시면 감사하겠습니다. 페어랑 같이 할 기간이 내일까지라 최대한 페이징 구현은 맛보고 싶습니다!!

그리고 덕분에 이번 미션에서도 많은걸 배워갑니다. 정성스런 리뷰 감사드려요^^

2021-04-01 14:08 UTC, sonypark commented
> 1. dto 클래스 안에 ManyToOne이나 OneToMany로 매핑되어 있는 객체들도 dto 클래스여야 하나요?? 그러니까 QuestionDto 클래스에 writer가 ManyToOne으로 매핑되어 있는게 writer 또한 UserDto를 사용해야 하는 것인지 궁금합니다. 일단 제 판단으로는 그렇게 해야하는 게 맞다고 생각해서 그렇게 수정했습니다. 이유는 그렇게 하지 않으면 entity 클래스에 비지니스 로직이 생기더라구요. 현재 상태에선 Answer 클래스에 matchWriter, delete 메소드가 그렇다고 생각합니다.

- 말씀하신대로 DTO 내에서 엔티티를 갖는 경우는 지양하며, DTO 내에는 DTO만 있어야 합니다. (단, 엔티티로 변환을 위한 toEntity 메서드에서 엔티티를 사용하는 방식으로는 사용됩니다.)
- DTO의 역할은 데이터를 전달하는 역할이 핵심입니다. DTO는 비즈니스 로직을 갖지 않습니다. 비즈니스 로직은 Entity 클래스나 Service에서 해주면 됩니다. 컨트롤러에서 DTO클래스로 request로 온 데이터를 받아서 Service 영역에서 Dto.toEntity()와 같은 메서드를 통해 엔티티로 변환해준 후 비즈니스 로직을 수행하시면 됩니다. 

> 2. 비지니스 로직을 entity 클래스에서 해야하는지 dto 클래스에서 해야하는지 궁금합니다. save, update, delete 같은 메서드로 상태를 바꾸는 과정이요. 전 일단 dto에 있는게 맞다고 생각을해서 그렇게 했는데 이부분도 답변 부탁드리겠습니다!!

1번 답변에서 말씀드렸다 싶이 DTO는 비즈니스 로직을 갖지 않습니다. 따라서 `questionDto.delete();` 와 같은 코드는 잘못 사용되었다고 볼 수 있습니다. `questionDto.toEntity();`를 통해 엔티티 객체로 변경한 후 비즈니스 로직을 수행하시면 됩니다.


> 3. QuestionDto에 answers도 List answers 로 관리를 하고 싶어서
> 
> ```java
> public QuestionDto(Question question) {
>     this.id = question.getId();
>     this.writer = new UserDto(question.getWriter());
>     this.dateTime = question.getDateTime();
>     this.title = question.getTitle();
>     this.contents = question.getContents();
>     this.answers = changeAnswerToAnswerDto(question.getAnswers());
>     this.deleted = question.isDeleted();
> }
> 
> public List<AnswerDto> changeAnswerToAnswerDto(List<Answer> answers) {
>     return answers.stream()
>             .map(AnswerDto::new)
>             .collect(Collectors.toList());
> }
> ```
> 
> 처럼 구현을 했더니 stackoverflow 에러가 떳습니다. 이유는 changeAnswerToAnswerDto 메소드 호출 시 Answer의 Question이 있고 그 Question에 또 Answer가 있어서 Answer를 AnswerDto로 바꿀 때 계속 순환이 되어 문제가 발생했습니다. 이 부분 해결할 수 있는 방안이 있을까요??

DTO내에서 엔티티에 의존하고 있어서 생기는 문제 같은데요. QuestionDTO 내에서 Answer 엔티티가 아닌 AnswerDTO를 사용하도록 해보세요.

++ 피드백이 도움이 되셨다니 다행이네요  현 단계에서 DTO를 적용하는건 추가 미션이라고 생각합니다. 제가 리뷰한 분들중에서는 DTO를 적용한 분이 비비와 이노가 처음이었습니다. 열심히 공부하시며 적용하는 모습이 참 좋네요! 앞으로도 더 성장하실 것 같습니다. 이번 미션은 여기서 머지하겠습니다. 제가 추가로 리뷰 남긴 부분은 다음 미션 때 시간 남으면 적용해보세요~~ 앞으로 다른 미션 하면서도 DTO를 사용할 일은 많을테니 그 때 공부하셔도 좋습니다. 수고 많으셨어요!💯

2021-04-01 14:09 UTC, sonypark approved these changes

2021-04-01 14:09 UTC, merged