[Tree]미션3,4 로그인 구현 / 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #137
Opened 2021-04-01 07:54 UTC by choitree

안녕하세요 트리입니다.
미션3을 진행하다보니, 3의 선택 내용이 미션4와 많이 겹쳐서 두가지 미션을 합쳐서 PR 요청드립니다.

* 로그인 기능 구현
* 로그인 상태에 따른 메뉴 처리 및 로그아웃
* 자기 자신의 정보 수정
* 질문하기, 질문 목록 기능 구현
* User/Question 연결
* Answer 구현
* 질문 상세보기 
* 질문 수정하기
* 질문 삭제하기(로그인한 사람과 질문자가 동일하며, 댓글이 없거나 질문자와 댓글 작성자가 동일한 경우만 삭제 가능)

질문자와 답변자가 다른 경우 삭제가 불가능하도록 하는 내용은 우선 미션에 있는 내용대로 구현하였으나
그룹별 리뷰에서는 다른 유저가 댓글을 달아도 게시글이 삭제되어야 하는 것이 통상적이라는 리뷰를 토대로
향후에는 댓글 작성자가 다르더라도 삭제 가능하도록 구현하도록 변경 예정입니다.

첫번째 브랜치를 merge하지 않고 브랜치를 삭제하고, 해당 내용을 코드에 덧붙여서 작성했었는데
그렇게 하다보니 리베이스에서 첫번째 브랜치가 함께 머지되서 리베이스를 하는데 상당 시간이 소요되었습니다.ㅠㅠ
사실 리베이스가 제대로 된건지 약간 혼돈스러운 상황이지만, 코드 내로 내용이 다 반영되었기에 정상적으로 작동되었다고 판단하고,,
PR 요청드립니다.

2021-04-01 14:16 UTC, sonypark commented
@choitree 현재 conflict가 나고 있는데, 충돌 해결해서 요청 부탁드립니다 :)

2021-04-01 14:41 UTC, sonypark requested changes
안녕하세요 Tree, 리뷰어 소니 입니다.😊
미션3,4 동시에 구현하시느라 고생많으셨습니다.
개선할 수 있는 부분에 대해 코멘트 남겼으니 확인 부탁드립니다!
질문거리는 코멘트로 남겨주시면 답변 드리겠습니다.

++ 브랜치 충돌이 나는 부분은 해결 부탁드립니다~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    }
`String.format()`도 좋지만 얼마전 [디온이 공유해준 링크](https://redfin.engineering/java-string-concatenation-which-way-is-best-8f590a7d22a8)처럼 `String.format()`이 생각보다 성능이 많이 떨어지기 때문에 + 연산자를 써주는게 더 좋을 것 같아요~
```suggestion
        return "redirect:/questions/" + questionId
    }
```

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +            return "redirect:/users/loginForm";
```suggestion
        if (!HttpSessionUtils.isLoginUser(session)) {
            return "redirect:/users/loginForm";
```

포맷팅이 조금 이상하게 되어있는 것 같습니다. `!`는 띄지 말고 붙여주세요~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
중복되는 코드가 있는데 메서드로 추출해서 중복제거를 해보세요~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "/qna/show";
`Optional.get()`는 지양해야합니다. 이렇게하면 Optional을 쓰는 의미가 없습니다 ㅎㅎ
`Optional.get()`을 왜 지양해야하는지 꼭 공부해보세요~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +
사용되는곳이 없는것 같아요~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
이것도 사용되지 않는것 같아요~

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
final을 붙여주는게 좋겠죠?

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "/user/profile";
해당하는 id가 없다면 null을 리턴하는게 맞을까요?
예외를 발생시켜 사용자에게 id가 잘못되었음을 알려주는건 어떨까요?

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
여기도 중복 로직이 보이네요. (updateUserInfo에도 비슷한 로직이 있는데 메서드로 추출 가능할 것 같아요)

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    public Answer() {}
기본생성자는 protected로 하는건 어떨까요?

[JPA Entity의 기본 생성자 관련 예외 정리하기](https://wbluke.tistory.com/6)

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    }
```suggestion
     public static boolean isLoginUser(HttpSession session) {
          return session.getAttribute(USER_SESSION_KEY) != null;
    }
```

2021-04-01 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +        }
이 부분이 꼭 필요한가요?

2021-04-01 14:44 UTC, choitree commented
소니 충돌난 부분을 해결해보려고 하는데, 여기 Resolve conflicts 버튼은 제가 권한이 없어서 안 눌러지는 것이 맞나요?~
일단 다시 풀/푸시를 해봤는데 반영되었는지 여부를 알 수 있는 방법이 있을까요?ㅠㅠ

2021-04-02 13:58 UTC, sonypark commented
> 소니 충돌난 부분을 해결해보려고 하는데, 여기 Resolve conflicts 버튼은 제가 권한이 없어서 안 눌러지는 것이 맞나요?~
> 일단 다시 풀/푸시를 해봤는데 반영되었는지 여부를 알 수 있는 방법이 있을까요?ㅠㅠ
> 
> 오 해결되었네요.... 이론적으로 이해하고 있는 Git과 실제로 적용이 안되서 자꾸 문제가 발생되네요ㅠㅠ

네 git을 잘 다루는게 어렵죠..ㅠㅠ 그래도 잘 해결하셨네요!
(Github에서 resolve conflict를 하는것보단 이번에 하신것 처럼 로컬에서 충돌해결해서 푸시하는걸 권장합니다.)
실무에서는 git이 매우 중요하기 때문에 평소에 잘 공부해두는게 좋습니다.
이렇게 충돌을 해결해본 경험이 나중에 도움이 될거에요!

2022-08-24 15:17 UTC, closed without merging