[Sky] 미션1 : 회원가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #14
Opened 2021-03-04 14:04 UTC by aksmf1442

안녕하세요. Sky입니다! 스프링이 처음이라서 이상한 부분이 많을텐데 그런 부분들 피드백 해주시면 감사하겠습니다!😅

> 기본적으로는 controller, service, repository, domain의 패키지를 만들고 controller 패키지에 들어있는 클래스들은 요청한 url을 처리해주는 역할을 맡고 있고, service 패키지에 들어있는 클래스들은 controller에서 필요한 서비스들을 제공하는 역할을 맡고 있습니다. 그리고 domain 패키지에 들어있는 클래스들은 user, question과 같은 객체들의 정보를 가지고 있습니다.

## 고민했던 점들

* 회원가입 기능을 만들 때 userId가 같으면 데이터를 저장하지 않고 실패했다는 문구를 띄우고 싶어서 처음에는 join_failed.html을 따로 만들고 이 곳을 출력할 수 있도록 로직을 짯었는데 나중에 handlebars 문법을 조금 공부하면서 if문을 할 수 있다는 걸 알고 기존의 user/form.html에 if문을 추가하는 것으로 해결했습니다.

* redirect를 사용해서 바로 url로 접근할 때 데이터를 넘기는 방법을 고민하다가 RedirectAttributes의 addFlashAttribute 메서드를 사용하면 넘길 수 있다는 것을 알고 적용해보았습니다.

* user를 관리하는 repository에서 처음에는 list로 user정보를 관리하다가 userId를 통해서 user 객체의 정보를 가져오려면 map을 사용하는게 더 편리할 것 같아서 map을 사용했습니다.

### 배포사이트 

[배포사이트](https://sky-codesquad.herokuapp.com/)

2021-03-05 16:03 UTC, ksundong requested changes
안녕하세요! Sky! 리뷰어 디온입니다.
재밌는 Spring의 첫 시작이네요. 어떤 부분은 많이 어렵겠지만, 발전해나가는 Q&A 사이트를 보면서 재미를 느껴보셨음 좋겠습니다.

사이트는 잘 동작하네요~ 현재는 글쓴이를 직접 입력해야하는 것 같지만 이건 나중에 해결하실 수 있을겁니다!
하지만 초기에 접속하는데 로딩이 길었는데요, Heroku는 한동안 접속하지 않으면 다운타임이 있거든요. 이것을 어떻게 하면 해결할 수 있을까요??

고민했던 점들을 쭉 읽어보았는데, 알차게 공부하신 것 같아요! 💯 

먼저 이번 PR은 아쉽게도 변경 요청을 드립니다. 몇몇 아쉬운 부분이 있었어요.

- 접근제어자의 사용이 미숙했어요. 이제는 익숙해져 봅시다!
- 스프링의 인젝션 방식에 대해서 한 번 공부해보세요. 너무 어렵다면 미루셔도 돼요.
- flashAttribute와 attribute의 차이에 대해서 공부해보세요. (flashAttribute의 사용은 잘하신겁니다! 참고해주세요)
- Url을 조금만 더 고민해봐주세요. 아직 익숙하지 않으실 거에요!
- toString을 재정의 해주셨는데, 그 이유가 궁금해요.
- 우리의 사이트는 한 명만이 접속할 것이라고 예상하기 어렵습니다. 여러명이 접속하고, 동시에 많은 처리를 할 수 있을 텐데요. 현재의 구조는 이에 취약한 부분이 몇 군데 있습니다. 코멘트를 남겨드렸으니 참고해주세요.
- 커밋 전 꼭 리포맷을 수행해주세요.
- `@Override` 애노테이션이 빠진, 오버라이딩하는 메서드가 있었습니다. 이 부분은 유의해주세요.
- 파일 저장시에 마지막에 빈 줄을 추가해주세요.

처음 스프링 미션 수행하시느라 고생많으셨습니다! 코멘트 확인하시고, 궁금한 점이나 이해가 가지 않거나 대화가 필요한 부분은 언제든 코멘트 남겨주세요~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/qna/form").setViewName("qna/form");
이 설정이 하는 일은 무엇인가요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/QnaConfig.java
> +}
일단 이것이 어떻게 동작하는지는 나중에 꼭 학습해 봅시다.
현재는 돌아가는걸 보는 것 만으로도 충분하지만, 중요하니 체크해둡시다!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    QnaService qnaService;
우리 저번 미션에서 접근 제어자에 대해서 학습했었죠?
접근제어자를 추가해주세요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    }
굳이 `@Autowired`가 필요 없을 것 같은데요~ 확인해주세요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    }
생성자 인젝션에 대해서 공부해보세요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
`redirect`가 해주는 일은 무엇일까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private final UserService userService;
오 여기는 제대로 써주셨네요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @Autowired
요건 빼셔도 될 것 같아요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
`flashAttribute`는 무엇이고 왜 쓸까요?
한 번 공부해보세요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
그냥 `addAttribute`와 어떤 차이가 있는지 생각해보세요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userList(User user, RedirectAttributes redirect) {
어떻게 `User` 타입으로 받을 수 있을까요?
요것도 나중에 한 번 공부해보세요~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private static int serialCode = 1;
이 필드는 여러 곳에서 접근한다면 어떻게 될까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return new SimpleDateFormat("yyyy-MM-dd HH:mm").format(currentTimeMillis);
여기에 DateFormat이 그냥 String 리터럴로 작성되어있는데, 상수로 추출해볼까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
toString을 재정의 해주신 이유가 있을까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
writer는 현재 단순한 String이군요. 나중에는 어떻게 바뀔지 궁금해지네요!

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +public class MemoryQnaRepository implements QnaRepository{
```suggestion
public class MemoryQnaRepository implements QnaRepository {
```

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    List<Question> questions = new ArrayList<>();
여기는 접근제어자가 없네요.

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    List<Question> questions = new ArrayList<>();
여러 군데에서 이 `List`에 접근하면 어떻게 될지도 한 번 생각해봐주세요~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +        return questions.get(index-1);
```suggestion
        return questions.get(index - 1);
```

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    private Map<String, User> userMap = new HashMap<>();
여기도 동시에 접근하는 경우를 생각해봐주세요~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    }
이건 User의 `equals` 메서드를 오버라이딩을 하는 것으로 해결해보면 어떨까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    public List<User> findUserALl() {
```suggestion
    public List<User> findUserAll() {
```

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    }
이 save는 `@Override`가 따로 정의되지 않았군요. 어떤 문제가 발생할 수 있을까요?

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QnaService.java
> +    QnaRepository qnaRepository;
여기도 접근제어자 꼭 붙여주세요~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    private UserRepository userRepository;
`final`을 붙여주는 것을 추천합니다~

2021-03-05 16:03 UTC, ksundong commented on src/main/resources/application.properties
> +spring.devtools.restart.quiet-period=1s
Save할 때, 빈 줄이 추가되도록 하는 설정을 여길 참고해서 해주세요~
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/list")
```suggestion
    @GetMapping("")
```
이렇게 바꿀 것을 제안드립니다.
이 부분에 대해서는 사실 나중에 학습하는게 좋을 것 같긴 하지만 간단히 알려드리자면,

GET /users는 보통 user의 list를 가져오는 요청으로 읽을 수 있습니다.
POST /users는 user를 생성하는 요청으로 읽을 수 있습니다.

현재는 GET과 POST만 사용가능하기 때문에 이렇게만 공부하고 넘어가봅시다~

2021-03-05 16:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userList(User user, RedirectAttributes redirect) {
그리고 변경을 하는데, 메서드 명이 `userList`네요.
이 메서드명, 과연 괜찮을까요? 또한, 경로도 /users/list 일텐데, list를 수정하는게 아니지 않나요?

2021-03-05 16:03 UTC, ksundong commented on src/main/resources/templates/home.html
> +                      <li><a href="#">»</a></li>
기본으로 들어있었겠지만 링크에 `#`을 넣어주는건 요즘엔 잘 쓰지 않습니다~

2021-03-05 16:03 UTC, ksundong commented on src/main/resources/templates/qna/show.html
> +          <form class="delete-answer-form" action="/api/questions/{3}/answers/{4}" method="POST">
0, 1, 2, 3, 4라는 숫자는 참 알기 어렵네요.
저도 예전에 이렇게 구현했던 것 같은데, 일단은 넘어가봅시다.

2021-03-05 16:03 UTC, ksundong commented on src/main/resources/templates/user/updateForm.html
> +      {{/if}}
if 문의 사용 좋습니다! 👍

2021-03-05 16:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String time;
시간을 `String`으로 저장하는것 과연 좋은 선택일까요?
자바8에서 추가된 날짜/시간 클래스를 한 번 이용해봅시다.

2021-03-06 09:29 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/qna/form").setViewName("qna/form");
addViewController는 특별한 로직이 없으면 url을 바로 view로 매핑할 수 있도록 하는거라고 알고 있어요! 그런데 setOrder같은 경우에는 매핑 한 것에대한 우선순위를 정해준다고 알고 있긴한데 자세하게는 모르겠네요. 😅

2021-03-06 09:29 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/config/QnaConfig.java
> +}
제가 최근에 공부한 지식으로 말씀드려보자면 @Configuration 애노테이션이 Bean을 생성할 수 있도록 해주는 애노테이션 이라고 알고있고, Configuration 애노테이션이 없으면 Bean을 생성 못하는걸로 알고있어요! 그리고 Bean을 생성하면 Spring 컨테이너에 등록되서 싱글턴으로 활용할 수 있다고 알고 있는데, 혹시 잘못된 지식이라면 지적해주시면 감사하겠습니다!😆

2021-03-06 09:29 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    QnaService qnaService;
변경했습니다!

2021-03-06 09:30 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    }
필드 주입이나 세터 주입이 아니면 @Autowired를 사용할 필요가 없군요! 사실 피드백 받기 전에도 @Autowired 없이 해봤는데 동작되길래 이게 왜 되는거지?라는 생각을 했었는데 생성자가 하나면 굳이 @Autowired를 사용할 필요가 없고, 두 개 이상이면 필요하다고 하네요. 피드백 감사합니다!

2021-03-06 09:30 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
redirect는 view로 접근하지 않고 url로 접근한다고 알고 있고, 예를들어서 redirect:/는 GET메서드 형식으로 전달되서 @GETMAPPING("/")로 매핑되어 있는 메서드로 접근해서 처리되는 구조?라고 알고있어요!

2021-03-06 09:30 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @Autowired
넵 변경했습니다

2021-03-06 09:31 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
제대로 이해한건지는 모르겠는데 말씀드려보자면 flashAttribute는 세션에 data를 저장해서 redirect후에 바로 data가 삭제되고, 세션에 저장되서 addAttribte와 다르게 data가 url에 노출되지 않는 장점이 있다? 이정도로만 알고 있어요!

2021-03-06 09:31 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userList(User user, RedirectAttributes redirect) {
사실 저도 어떻게 User타입으로 받는지 궁금했는데 구현하느라 급급해서 공부를 못해봤네요! 찾아보니까 jQuery 덕분인거 같기는 한데, jQuery도 그렇고 자바스크립트도 잘 몰라서 이해하기가 힘드네요. 다음에 다시 공부해볼게요!

2021-03-06 09:31 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private static int serialCode = 1;
아닐수도 있겠지만 말씀 드려보자면, 멀티 쓰레드 환경에서 여러 명이 동시에 접근하면 동기화 작업이 안되어 있어서 정보가 날라갈 수 있다?는 점인 것 같아요.

2021-03-06 09:32 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        return new SimpleDateFormat("yyyy-MM-dd HH:mm").format(currentTimeMillis);
변경했습니다!

2021-03-06 09:32 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
편하게 디버깅 하려고 toString()을 오버라이딩 했었어요 ! Logger를 사용했어야 했는데 System.out.print()를 사용했었네요.. Logger 사용해볼게요😅

2021-03-06 09:34 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
생각해보니까 나중에 user랑 연동하려면 User로 했어야 겠네요. 그 상황이 오면 바꿔보겠습니다!

2021-03-06 09:34 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +public class MemoryQnaRepository implements QnaRepository{
리포맷했습니다!

2021-03-06 09:34 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    List<Question> questions = new ArrayList<>();
변경했습니다!

2021-03-06 09:35 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    }
생각해보니까 userId가 같으면 어차피 userId가 같으면 같은 유저니까 equals로 오버라이딩 해도 되겠네요! 변경했습니다.

2021-03-06 09:35 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    }
지금 당장에 동작에는 아무런 상관이 없겠지만 인터페이스의 메서드명이 바뀌면 @Override가 없으면 에러가 나지 않아서 이게 그 메서드인지 확인하기가 힘들 수 있겠네요.

2021-03-06 09:35 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/service/QnaService.java
> +    QnaRepository qnaRepository;
넵 변경했습니다!

2021-03-06 09:35 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    private UserRepository userRepository;
넵 변경했습니다!

2021-03-06 09:36 UTC, aksmf1442 commented on src/main/resources/application.properties
> +spring.devtools.restart.quiet-period=1s
저번에 설정했었는데 노트북이 바뀌면서 까먹었네요.. 감사합니다!

2021-03-06 09:36 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/list")
변경했습니다!

2021-03-06 09:37 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String time;
이렇게 변경하는게 맞는지는 모르겠는데, 일단 나름대로 변경했습니다!

2021-03-06 09:44 UTC, aksmf1442 commented
이렇게 세세하게 리뷰 해주셔서 감사합니다! 생각치도 못한 부분들을 다시 공부할 수 있어서 좋았습니다!! 리뷰 받은 부분들 나름대로 변경해봤는데 제대로 변경한지는 잘 모르겠네요🥲,,  그래도 스프링 재밌네요 ㅎㅎ

2021-03-06 11:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/QnaConfig.java
> +}
스프링의 빈 생성 방식에 대해서 한 번 공부해봅시다!
빈 생성 방식은 스프링의 기반으로 중요한 내용이니 꼭 학습해두세요.
참고로, 빈의 스코프가 있는데 기본값이 싱글턴입니다!

2021-03-06 11:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    }
세터 주입에도 필요한가요? 제가 알기론 아닌데 저도 확인해봐야겠네요!

2021-03-06 11:04 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
한 번 크롬 네트워크 콘솔창을 열어보고 `redirect`가 어떤 동작을 하는지 확인해봅시다.

2021-03-06 11:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
그냥 `addAttribute`하면 url에 데이터가 노출되나요?

2021-03-06 11:08 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userList(User user, RedirectAttributes redirect) {
`User` 타입으로 받을 수 있는 이유는 스프링의 데이터 바인딩과 관련된 건데요. 재미로만 공부해보세요. 어려운 부분입니다.
`jQuery`는 아무 도움도 주지 않았습니다 ㅋㅋ

2021-03-06 11:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private static int serialCode = 1;
네, 정보가 덮어 씌워져서 결과적으로 날아가버리는 현상이 발생할 겁니다. 어떻게 해결할 수 있을까요?

2021-03-06 11:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    }
항상 `equals()`를 오버라이딩 할 때에는 어떤 정보가 같아야 하는지 꼭 생각해보세요!

2021-03-06 11:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +    }
꼭 붙여주세요 ㅎㅎ

2021-03-06 11:29 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    }
확인해보니까 필요없는 것 같네요!

2021-03-06 11:33 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
쿼리 스트링으로 노출되는 것 같더라구요!

2021-03-06 11:33 UTC, aksmf1442 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userList(User user, RedirectAttributes redirect) {
그렇군요 ㅋㅋㅋ 잘못 알았네요. 감사합니다!

2021-03-06 11:37 UTC, ksundong approved these changes
안녕하세요! Sky 리뷰를 적극적으로 반영해주셔서 감사합니다!
스프링 Bean 등록 방식에 대해서 좀 더 학습해보시고, 현재 더 많이 사용하는 방식을 제안드렸으니 확인해주세요.
구현에는 문제가 없으니 다음단계 바로 진행하셔도 됩니다! 고생하셨어요!!

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/QnaConfig.java
> +}
아 그리고 보니 이 클래스는 전혀 필요하지 않은 클래스였네요.
제거해봅시다.

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/UserConfig.java
> +}
이 클래스도 필요하지 않습니다. 잠시 착각했네요.

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        return "redirect:/";
순서를 설명해드리자면 클라이언트가 두 번 요청을 보내게됩니다~

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        if (!originUser.isMatchingPassword(receivedPassword)) {
! 을 붙이는 것 말고도 메서드의 동작을 반대로 바꿔 `Not`을 메서드에 넣어줘도 됩니다~
취향차이에요!

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int id;
```suggestion
    public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm";
    
    private int id;
```

빈 라인으로 구분지어주세요~

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDate date;
👍

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryUserRepository.java
> +    private final Map<String, User> userMap = Collections.synchronizedMap(new HashMap<>());
Map 구현체중에 ConcurrentHashMap이 있을거에요.
https://stackoverflow.com/questions/510632/whats-the-difference-between-concurrenthashmap-and-collections-synchronizedmap

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/MemoryQnaRepository.java
> +public class MemoryQnaRepository implements QnaRepository {
여기에 `@Component`를 추가해주시면 빈으로 등록됩니다.
`@Repository`라는 애너테이션도 있어요.

2021-03-06 11:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QnaService.java
> +public class QnaService {
여기도 `@Service`라는 애너테이션을 붙여줍시다!

2021-03-06 11:37 UTC, ksundong commented on src/main/resources/application.properties
> +spring.devtools.restart.quiet-period=1s
아직 안바뀌었군요 👀

2021-03-06 11:42 UTC, aksmf1442 commented on src/main/resources/application.properties
> +spring.devtools.restart.quiet-period=1s
앗.. 그렇네요 preferences -> General -> On Save -> Ensure every saved file ends with a line break를 체크 했는데 이게 아닌가요?

2021-03-06 12:06 UTC, ksundong commented on src/main/resources/application.properties
> +spring.devtools.restart.quiet-period=1s
맞는데 가끔 동작하지 않는데 이유는 저도 잘 모르겠어옹

2021-03-06 12:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            redirect.addFlashAttribute("fail", true);
아 순간 헷갈렸네요 redirect를 시켜줄 때에는 노출되는게 맞습니다.

2021-03-08 07:31 UTC, merged

2021-03-08 07:31 UTC, honux77 commented
조금씩 개선사항이 아직 보이는 것 같은데 다음 단계 제출할 때 참고해 주세요.