[August] 미션 1:  회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #15
Opened 2021-03-05 02:47 UTC by Polynomeer

### 미션 1:  회원 가입, 사용자 목록, 질문하기 구현

안녕하세요, 코드스쿼드 백엔드 과정의 August입니다. 항상 좋은 리뷰 감사합니다! 이번 과제는 주어진 요구사항인 회원 가입, 사용자 목록에 해당하는 기능을 구현하였고, 질문하기 및 질문 목록을 조회하는 기능을 구현했습니다. 마지막으로, 선택 사항에 해당하는 회원 정보 수정 기능도 요구사항에 따라 구현 완료하였습니다.

### 구현 내용

**config**

- MvcConfig : 과제에서 주어진 코드를 적용했습니다.

**controller**

- MainController - 기본 경로에 대한 맵핑을 해주는 컨트롤러 입니다.
  - index() - url의 루트 경로를 index 페이지로 맵핑해주는 메서드입니다. 

- QuestionController - `/questions`로 들어온 url을 맵핑해주는 컨트롤러 입니다.
  - Question을 ArrayList에 저장하여 관리합니다.
  - index() - Model 객체를 받아서 questions 리스트를 모델에 추가하고, /qua/list 로 url을 맵핑합니다.
  - create() - Question을 받아서 생성날짜를 지정하고 id를 지정한 다음, questions 리스트에 추가합니다. 그리고 /questions 페이지로 리다이렉션 합니다.
  - list() - 해당 질문의 id를 GET으로 넘겨받아서 해당 질문글을 모델 객체에 추가하고, /qna/show 페이지로 넘겨줍니다.

- UserController - /users로 들어온 url을 맵핑하고 처리하는 컨트롤러 입니다.
  - User를 ArrayList에 저장하여 관리합니다.
  - profile() - userId를 GET으로 넘겨받고 userId에 해당하는 User객체를 가져와서 모델 객체에 추가합니다. 그리고 /user/profile 페이지로 맵핑합니다.
  - list() - 모델 객체에 users 리스트를 모두 추가하고 /user/list 페이지로 맵핑합니다.
  - create() - (회원가입) 전달받은 User객체를 users리스트에 추가합니다. 그리고 /users로 리다이렉션 합니다.
  - form() - (회원정보 수정페이지) userId를 넘겨받으면서 해당 User를 찾은 다음, 만약에 존재한다면 모델 객체에 추가하고 수정 페이지 `/user/updateForm` 로 맵핑합니다.
  - update() - (회원정보 수정) userId에 해당하는 User를 찾고, 전달받은 User객체로 변경합니다. 그리고 다시 /users 페이지로 리다이렉션 합니다.
  - findeUserById() - users리스트에서 userId가 같은 User 객체를 찾는 로직이 반복수행되어 별도의 메서드로 분리하였습니다.

**domain**

- Question - 질문 하나를 담는 클래스 입니다.

- User - 사용자 한명의 정보를 담는 클래스 입니다.
  - update() - User객체를 전달받아서 그 User의 데이터로 전부 변경합니다.
  - matchUserId() - userId는 User의 내부 데이터이므로 여기에서 일치하는지 비교합니다.

2021-03-05 16:54 UTC, ksundong requested changes
안녕하세요! August! 리뷰어 Dion입니다!
첫번째 재미있는 스프링과제를 진행하신걸 축하드립니다! 앞으로의 과정은 더더욱 재밌을 예정입니다.
먼저 이번 PR은 아쉽게도 변경 요청을 드리게 되었습니다. 생각해 보실 내용들을 코멘트에 작성해두었으니 참고해주세요.

## 리뷰

- Heroku에 처음 접속하면 꽤 긴 로딩시간이 발생합니다. 이를 어떻게 해결해줄 수 있을까요?
- https://august-qna.herokuapp.com/user/profile 여기로 접속하면 404가 발생하네요. 이건 어떻게 해결할 수 있을까요?
- 회원정보 수정기능은 상식적으로 생각했을 때, 비밀번호가 채워져있으면 안되겠죠?
- Controller의 책임이 너무 과도하게 많습니다. 적절하게 분리해주세요.
- url 설정과 메서드 네이밍에 대해서도 좀 더 고민해봐주세요!
- `System.out.println()`은 이 미션 이후로 봉인해두시면 됩니다. Logger를 사용해주세요.
- 여러 곳에서 접근할 수 있는 자원에 대해서 고민해봐주세요.
- 시간을 String 타입으로 저장하는 것은 어떤 손해가 있을까요?

미션 진행해주시느라 고생많으셨고, 궁금하시거나, 이해가 가지 않는 내용 대화가 필요하시면 언제든 코멘트 달아주세요.
고생많으셨습니다!

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/questions/form").setViewName("qna/form");
이것이 어떤 설정인지 공부해보셨나요? 한 번 공부해봐주세요~

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
여길 참고해서 설정 수정 꼭 해주세요~

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final List<Question> questions = new ArrayList<>();
이름은 Controller인데, questions를 여기서 관리하는군요?
이렇게 개발하면 Controller의 책임이 많아지게 됩니다. 한 번 생각해봐주세요.

그리고, 여러 요청이 동시에 들어올 때 ArrayList는 과연 안전할까요?

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String index(Model model) {
`index`보다 좋은 이름 고민해봐주세요 ㅋㅋ

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setCreatedDate(formatDateTime);
흠.. 왜 포맷된 시간을 넣어주시는지 궁금하네요!

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
`redirect`를 하면 어떻게 될까요?
그냥 `/`를 써주는 것과 어떤 차이가 있을까요?

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String list(@PathVariable("id") long id, Model model) {
메서드명은 list인데, list 아닌것 같네요.

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setId(questions.size() + 1);
이 부분도 조심해야할 것 같아요. 여러곳에서 접근할 때를 항상 생각해봅시다.

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        System.out.println(user);
이제부턴 `System.out.println()`은 봉인하시고, Logger를 사용해주세요.

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String form(@PathVariable String userId, Model model) {
이 url은 이해하기 어렵네요. 어떤 의도인지 파악하기 쉽게 네이밍해주세요.

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
불편하다고 느끼셨나요? Map의 사용도 고려해보셨을 것 같네요!

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
나중엔 `User` 타입으로 바뀌겠죠? 기대가 됩니다.

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String createdDate;
과연 시간을 이렇게 저장하는게 맞을까요?

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +
👍

2021-03-05 16:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
`toString()`을 오버라이딩 해주신 이유가 있을까요?

2021-03-05 16:54 UTC, ksundong commented on src/main/resources/templates/common/subnav.html
> +                <li><a href="#" role="button">개인정보수정</a></li>
기본으로 있는 `#`일텐데 요즘엔 잘 안쓴다고 합니다.
참고만 해주세요~

2021-03-05 16:54 UTC, ksundong commented on src/main/resources/templates/qna/show.html
> +                    <form class="delete-answer-form" action="/api/questions/{3}/answers/{4}" method="POST">
기본으로 있는 것 같긴한데 0, 1, 2, 3, 4는 뭐가 올지 잘 모르겠네요!

2021-03-05 17:28 UTC, ksundong commented
그리고 다른분들 과제를 보니까 회원 목록에서 번호가 나오더라고요!
근데 August거에선 안나와서 확인부탁드려요~

2021-03-08 15:02 UTC, Polynomeer commented
- Heroku에 처음 접속하면 꽤 긴 로딩시간이 발생합니다. 이를 어떻게 해결해줄 수 있을까요?

  - 로컬 환경에서는 저렇게까지 느리지 않은데, 처음 접속할 때만 느리네요. Heroku가 미국 서버인 것도 원인인 것 같은데, 해결 방법을 잘 모르겠습니다.. 다른 분들 중에 빠른 사람도 있고 아닌 사람도 있는데 좀 더 학습해보겠습니다!
  - 여러가지 조사를 해보니 서버 애플리케이션이 일정 시간동안 사용이 안되면 헤로쿠 서버의 메모리에서 자동으로 언로드 되는것 같습니다. 트래픽이 많을수록 서버의 메모리에 계속 상주하게 되는듯 합니다. 즉, 유독 빠른 서버의 경우 인기가 많은 서버일수도 있겠네요!
  - 같은 스터디원인 bat가 http://kaffeine.herokuapp.com 여기에 등록을 하면 30분 마다 ping을 날려서 서버를 데워주는(?) 방법을 알려주어서 등록해보았더니, 다소 빨라진 것 같습니다!
  - https://stackoverflow.com/questions/2606190/why-are-my-basic-heroku-apps-taking-two-seconds-to-load
  - https://www.quora.com/Scalability/Scalability-How-does-Heroku-work-2
  - https://devcenter.heroku.com/articles/how-heroku-works
- https://august-qna.herokuapp.com/user/profile 여기로 접속하면 404가 발생하네요. 이건 어떻게 WhiteLabelErrorPage가 뜨는것을 해결할 수 있을까요?

  - 이 부분은 어떠한 해결사항을 말씀하지는지 이해가 잘 가지 않습니다. 기본적으로 회원가입 후 사용자 이름을 클릭하면, `users/{userId}`로 이동하여 프로필은 출력됩니다. 그리고 `users/profile`로 접속하면 현재는 이름이 비어있는 상태로 프로필 페이지가 표시됩니다. 하지만 비정상적인 url에 대한 처리를 해주어야 한다는 말씀이신가요?
  - https://goddaehee.tistory.com/214
  - https://zetcode.com/springboot/whitelabelerror/
  - https://techblogstation.com/spring-boot/whitelabel-error-page-spring-boot/
- 회원정보 수정기능은 상식적으로 생각했을 때, 비밀번호가 채워져있으면 안되겠죠?

  - 사실, 그 생각은 했지만 비밀번호가 맞는지를 검증하는 로직을 구현하는 것을 다음 미션에서 수행하지 않을까 해서 일단 두었는데, 수정해야겠네요!! 😅
  - 우선은 updateForm.html에서 패스워드 부분을 제거했습니다. User의 update에서도 패스워드는 변경하지 못 하도록 했습니다. 패스워드 확인 후 변경완료를 하는 등의 로직은 미션을 좀 더 수행하고 해보겠습니다.
- Controller의 책임이 너무 과도하게 많습니다. 적절하게 분리해주세요.
  - UserController::findUserById같은 로직은 Service에 포함되어야 한다는 것은 알겠습니다. 하지만 계속 시도해보았지만 의존주입과 같은 개념이 아직 많이 부족해서 이번 미션에서는 이 부분을 그냥 넘어가려고 합니다.. ;(
- url 설정과 메서드 네이밍에 대해서도 좀 더 고민해봐주세요!
  - 같은 url을 가지더라도 메서드(GET, POST)로 식별이 가능해서 update로 변경했습니다!
- `System.out.println()`은 이 미션 이후로 봉인해두시면 됩니다. Logger를 사용해주세요.

  - Logger의 필요성을 아직 느끼지 못해서 무작정 쓰기가 어려웠는데, 이참에 사용목적에 대하여 공부해보았습니다.
  - 로그를 보다 풍부하게 다루기 위해서 앞으로 `Logger`사용을 습관화해야겠습니다!
  - https://www.baeldung.com/java-system-out-println-vs-loggers
- 여러 곳에서 접근할 수 있는 자원에 대해서 고민해봐주세요.
  - 이 부분은 멀티스레드 환경에서 synchronized되지않은 Collections에 대해서 말씀하시는 건가요? 지금은 이해가 부족해서 좀 보류하였습니다 ;(
- 시간을 String 타입으로 저장하는 것은 어떤 손해가 있을까요?
  - 스프링에서는 기본적으로 String 파라미터를 Date나 다른 time 객체로 변환하는 것이 불가능하다고 합니다. 따라서 ConversionFailedException이 발생할 수 있습니다.
  - LocalDateTime을 저장하도록 변경했습니다!
  - https://www.baeldung.com/spring-date-parameters

2021-03-08 15:31 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
네, 자바지기님의 영상을 보고 참고하다가 Logger에서 출력하면서 User 데이터가 잘 들어갔는지 확인하기 위해서 있는 부분인데, 프로젝트가 완성 되고나서 필요가 없다면 제거해야 할 것 같습니다!

2021-03-08 15:32 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String createdDate;
LocalDateTime으로 저장하도록 변경했습니다!

2021-03-08 15:34 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String list(@PathVariable("id") long id, Model model) {
잘못된 네이밍인것 같습니다. show로 변경하고 index를 list로 변경했습니다.

2021-03-08 15:34 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
계속 테스트 해보았는데, 동일하게 루트 경로의 url을 GET요청 하는 것 같습니다. 동일한 것 아닌가요?

2021-03-08 15:36 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setCreatedDate(formatDateTime);
생각을 약간 잘못한 것 같습니다. 생성자를 통해서 LocalDateTime.now()를 넣고, 가져올 때 포맷팅해주도록 변경했습니다.

2021-03-08 15:36 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String index(Model model) {
home은 어떤가요? 우선 그렇게 변경했습니다!

2021-03-08 15:38 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final List<Question> questions = new ArrayList<>();
service 패키지를 만들고, Service클래스를 만들어서 분리하려고 했으나, 아직 의존주입과 같은 개념에 대한 학습이 부족해서 어렵네요.

ArrayList 및 Collections의 기본 자료구조는 멀티스레드 환경에서 thread-safe하지 않습니다. 따라서 synchronizedList()를 사용하는 것이 바람직하다는 것을 공부했습니다. 하지만 적용하지는 못 했습니다.

2021-03-08 15:38 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +}
참고하여 인텔리제이 설정을 변경했습니다!

2021-03-08 15:57 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/questions/form").setViewName("qna/form");
- `ViewControllerRegistry` - 상태 코드 and/or view로 미리 설정된 간단한 자동화 컨트롤러 등록을 지원합니다.
- `setOrder(int order)` - Spring MVC에서 설정된 다른 핸들러 맵핑과 관련된 뷰 컨트롤러를 맵핑 하는데 사용되는 `HandlerMapping`에 사용할 순서를 지정합니다. `Ordered.HIGHEST_PRECEDENCE`로 지정함으로써 높은 우선순위부터 등록됩니다.
- `addViewController(String urlPathOrPattern)` - URL 경로 또는 패턴을 뷰 컨트롤러에 맵핑하여 구성된 상태코드 및 뷰로 응답을 렌더링합니다.
- `addViewController("users/form").setViewName("user/form")`은 한마디로 가장 기본이 되는 컨트롤러에 "user/form"이라는 뷰를 사전등록 해놓는 것 입니다. 즉, "users/form"이라는 url요청이 오면 가장 먼저 "user/form"이 맵핑됩니다.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/ViewControllerRegistry.html

2021-03-08 16:01 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String form(@PathVariable String userId, Model model) {
url이 같지만 메서드(GET, POST)로 구분이 가능하므로 update라는 이름으로 변경했습니다.

2021-03-09 10:01 UTC, ksundong commented
다 작업하신건가요? 다 작업하셨으면 리뷰 요청 다시 눌러주세요~

2021-03-09 10:37 UTC, ksundong approved these changes
안녕하세요. August! 수정하느라 고생하셨습니다.
몇 가지 코멘트 남겨드리는데요, 이 부분 이 단계에서 수정해주셔도 좋고, 다음 단계에서 수정사항 반영해주셔도 좋습니다.
고생하셨어요~

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/questions/form").setViewName("qna/form");
잘 정리하셨네요 굿굿 👍

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/MainController.java
> +        return "redirect:/questions";
잘 처리해주셨어요.

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final List<Question> questions = new ArrayList<>();
음 의존 주입을 시도해보시는게 좋았을 것 같네요. 그래야 어떤 시도를 하셨고, 리뷰어는 그걸 보고 이렇게 했으면 좋겠다는 가이드를 줄 수 있으니까요!
뒤의 내용은 굳이 적용하지 않으셔도 됩니다 ㅎㅎ

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
이에 대한 동작을 보기 위해서는 개발자 도구로 네트워크 탭을 확인해주셔야해요.
브라우저에 301 응답이 전달될겁니다.

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
redirect와 그냥 /의 차이는 꼭 알아두세요~

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    Logger logger = LoggerFactory.getLogger(UserController.class);
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
```

이렇게 해주시는걸 권장합니다~

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
차라리 user가 null이면 조회할 수 없게끔 하는게 깔끔하지 않을까요?

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info(user.toString());
```suggestion
        logger.info("user: {}", user);
```
이렇게 변경하는 것을 추천드립니다!

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
다른 부분은 그렇게 처리해주셔서 충분히 가능할 것 같아요!

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDateTime createdDate;
```suggestion
    private LocalDateTime createdDateTime;
```

저는 좀 더 자료형에 알맞게 이름을 바꿔주는 것을 권장하고 싶네요.

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
가급적이면 getter는 getter대로 쓰고, 별도의 getter메서드로 포맷된 값을 반환해주도록 해봅시다.

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
정의해주는 것 자체는 좋은 습관인데, 나중에 겪어보실테지만, 쉽게 발생할 수 있는 문제가 있어서 알려드렸어요!

2021-03-09 10:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/util/DateTimeUtils.java
> +public class DateTimeUtils {
👍

2021-03-09 10:37 UTC, ksundong commented on src/main/resources/templates/error/404.html
> +</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
👍  💯 
이런 페이지도 만들어줄 수 있죠! 잘하셨어요.

2021-03-09 10:37 UTC, ksundong commented on src/main/resources/templates/qna/form.html
> +{{> common/base}}
아직 설정 반영이 안되었는지 통행금지 표시가 남아있네요.

2021-03-09 10:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String index(Model model) {
좋네요 index보다 훨씬 나은 것 같아요.
다만 ㅎㅎ home으로 가는것이 과연 QuestionController의 책임인가도 생각해봅시다.

2021-03-09 10:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String form(@PathVariable String userId, Model model) {
사실 지금 다시보니 잘 읽히네요. 제가 왜 이런 피드백을 주었을까요 ㅠㅠ
죄송합니다 ㅠㅠ

2021-03-09 10:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info(user.toString());
그리고 메서드 명에 동사가 들어가면 안되는데, 제가 피드백을 잘못드려서 동사가 들어가도록 하신 것 같아요.
죄송합니다 ㅠㅠ

2021-03-09 10:45 UTC, ksundong requested changes
앗 죄송합니다. 제가 피드백을 잘못 드리는 바람에 url 매핑이 해결이 안되었군요.
이 부분이 해결되면 바로 Approve 해드릴게요. 번복해서 죄송합니다.

RESTful하다는 것은 간단하게 URL과 METHOD의 조합으로 하는 일이 무엇인지 알 수 있다는 건데요.
URL은 리소스를 표현합니다. 따라서 왠만한 경우에는 URL에는 동사가 들어가지 않도록 하는 것을 권장합니다.

죄송합니다. ㅠㅠ

2021-03-09 10:53 UTC, ksundong commented
> * Heroku에 처음 접속하면 꽤 긴 로딩시간이 발생합니다. 이를 어떻게 해결해줄 수 있을까요?
>   
>   * 로컬 환경에서는 저렇게까지 느리지 않은데, 처음 접속할 때만 느리네요. Heroku가 미국 서버인 것도 원인인 것 같은데, 해결 방법을 잘 모르겠습니다.. 다른 분들 중에 빠른 사람도 있고 아닌 사람도 있는데 좀 더 학습해보겠습니다!
>   * 여러가지 조사를 해보니 서버 애플리케이션이 일정 시간동안 사용이 안되면 헤로쿠 서버의 메모리에서 자동으로 언로드 되는것 같습니다. 트래픽이 많을수록 서버의 메모리에 계속 상주하게 되는듯 합니다. 즉, 유독 빠른 서버의 경우 인기가 많은 서버일수도 있겠네요!
>   * 같은 스터디원인 bat가 http://kaffeine.herokuapp.com 여기에 등록을 하면 30분 마다 ping을 날려서 서버를 데워주는(?) 방법을 알려주어서 등록해보았더니, 다소 빨라진 것 같습니다!
>   * https://stackoverflow.com/questions/2606190/why-are-my-basic-heroku-apps-taking-two-seconds-to-load
>   * https://www.quora.com/Scalability/Scalability-How-does-Heroku-work-2
>   * https://devcenter.heroku.com/articles/how-heroku-works

네 kaffeine을 활용해서 서버가 warm하게 유지되도록 해줄 수 있습니다. cold start를 하기 때문인데 쉽게 말해서 요청이 들어갔을 때, 부팅을 한다고 생각하시면 좋을 것 같아요.

> * https://august-qna.herokuapp.com/user/profile 여기로 접속하면 404가 발생하네요. 이건 어떻게 WhiteLabelErrorPage가 뜨는것을 해결할 수 있을까요?
>   
>   * 이 부분은 어떠한 해결사항을 말씀하지는지 이해가 잘 가지 않지만, error페이지를 커스터마이징 하여 처리했습니다.
>   * https://goddaehee.tistory.com/214
>   * https://zetcode.com/springboot/whitelabelerror/
>   * https://techblogstation.com/spring-boot/whitelabel-error-page-spring-boot/

오 제가 생각했던건, 404 페이지보다 로직상으로 예외를 해결해주는 방향을 생각만 해보셨으면해서 였습니다. 404 페이지 멋지네요.

> * 회원정보 수정기능은 상식적으로 생각했을 때, 비밀번호가 채워져있으면 안되겠죠?
>   
>   * 사실, 그 생각은 했지만 비밀번호가 맞는지를 검증하는 로직을 구현하는 것을 다음 미션에서 수행하지 않을까 해서 일단 두었는데, 수정해야겠네요!! 😅
>   * 우선은 updateForm.html에서 패스워드 부분을 제거했습니다. User의 update에서도 패스워드는 변경하지 못 하도록 했습니다. 패스워드 확인 후 변경완료를 하는 등의 로직은 미션을 좀 더 수행하고 해보겠습니다.

앗 역시 그러셨군요. 실제 사이트라고 생각하고 개발해봐주세요!

> * Controller의 책임이 너무 과도하게 많습니다. 적절하게 분리해주세요.
>   
>   * UserController::findUserById같은 로직은 Service에 포함되어야 한다는 것은 알겠습니다. 하지만 계속 시도해보았지만 의존주입과 같은 개념이 아직 많이 부족해서 이번 미션에서는 이 부분을 그냥 넘어가려고 합니다.. ;(

ㅠㅠ 가장 중요한 부분이라 현재 단계에서부터 지속적으로 고민해봐주세요.

> * url 설정과 메서드 네이밍에 대해서도 좀 더 고민해봐주세요!
>   
>   * 같은 url을 가지더라도 메서드(GET, POST)로 식별이 가능해서 update로 변경했습니다!

에구 이 부분은 제가 피드백을 잘못 드렸습니다. 죄송해요.

> * `System.out.println()`은 이 미션 이후로 봉인해두시면 됩니다. Logger를 사용해주세요.
>   
>   * Logger의 필요성을 아직 느끼지 못해서 무작정 쓰기가 어려웠는데, 이참에 사용목적에 대하여 공부해보았습니다.
>   * 로그를 보다 풍부하게 다루기 위해서 앞으로 `Logger`사용을 습관화해야겠습니다!
>   * https://www.baeldung.com/java-system-out-println-vs-loggers

학습하시는 습관 아주 좋습니다.

> * 여러 곳에서 접근할 수 있는 자원에 대해서 고민해봐주세요.
>   
>   * 이 부분은 멀티스레드 환경에서 synchronized되지않은 Collections에 대해서 말씀하시는 건가요? 지금은 이해가 부족해서 좀 보류하였습니다 ;(

이제 체스와 다르게 여러 사용자가 동시에 접근 할 수 있는 경우가 발생합니다. 앞으로는 이 부분을 개발시에 꼭 염두에 두고 개발을 해주세요.

> * 시간을 String 타입으로 저장하는 것은 어떤 손해가 있을까요?
>   
>   * 스프링에서는 기본적으로 String 파라미터를 Date나 다른 time 객체로 변환하는 것이 불가능하다고 합니다. 따라서 ConversionFailedException이 발생할 수 있습니다.
>   * LocalDateTime을 저장하도록 변경했습니다!
>   * https://www.baeldung.com/spring-date-parameters

String이면 시간으로 사용하기 위해 처리를 해주어야 하고, 명확하지 않기 때문도 있습니다.
또한, 여러 형태로 변환하기에도 까다로운 단점이 있습니다.

학습하시느라 고생많으셨네요. 제가 잘못 피드백드린 부분이 있어서 죄송합니다. 😭

2021-03-09 12:08 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
오~! 처음엔 이해가 안 갔는데, 가져오는 이름을 다르게 지정해 주었더니, 템플릿 엔진은 별도의 getter를 인식하는군요!

2021-03-09 12:20 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
그래서 getXXX 의 사용은 조심해야해요~

2021-03-09 13:17 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info(user.toString());
컨트롤러에서 맵핑을 해주는 메서드의 이름은 동사가 아니라 (url과 마찬가지로 자원에 대한)명사가 들어가나요? 우선, account로 메서드명을 변경해보았습니다.

2021-03-09 14:26 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
다시 테스트 해봤더니 계속 302만 나오네요.. 좀 더 공부해보겠습니다!

2021-03-09 15:16 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
처음에는 무슨말인지 이해가 잘 가지않았는데, getter의 이름을 기준으로 템플릿 엔진이 맵핑해주는군요!

2021-03-09 15:16 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDateTime createdDate;
저도 그게 더 명확하고 좋은 것 같아서 변경했습니다!

2021-03-09 15:17 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
null이면 조회할 수  없게끔 변경했습니다!

2021-03-09 15:25 UTC, ksundong approved these changes
리뷰 내용 빠르게 반영해주셨네요! 고생하셨습니다!
다음 단계 바로 진행하셔도 될 것 같아요~

2021-03-09 15:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "redirect:/";
앗 302군요. 제가 실수했네요.

2021-03-09 15:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("{userId}/info")
info 보다는 수정하는 화면에 어울리는 매핑이 나을 것 같아요.

2021-03-09 15:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +    }
관례상 save를 권장드려요!
그리고 굳이 Question을 붙여주는건 동어 반복같은 느낌이네요~

2021-03-09 15:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
Spring의 Injection에 대해서 공부해보세요~
여기선 `@Autowired`는 생략해줘도 됩니다.

2021-03-09 16:14 UTC, Polynomeer commented
아주 많은 내용을 리뷰해주셔서 감사합니다! 다음 미션을 진행해가면서 좀 더 공부해보겠습니다.

2021-03-10 02:46 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String form(@PathVariable String userId, Model model) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ form 이 더 나은 것 같기도 한데요? 잘 모르겠다 ㅋㅋㅋㅋㅋ

2021-03-10 02:46 UTC, honux77 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
지금도 User 타입으로 참조했어도 될 것 같네요. 그것도 재미있었을 듯 ㅎㅎ

2021-03-10 03:27 UTC, honux77 commented
두분다 수고 많으셨어요. 재밌게 잘 읽었습니다 ㅎㅎ.

2021-03-10 03:27 UTC, merged