[아이작] 미션 1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #17
Opened 2021-03-05 05:51 UTC by isaac56

안녕하세요, 코드스쿼드 백엔드 과정의 아이작입니다. 
과제에서 주어진 아래 요구사항에 대하여 구현하였습니다.
 - 회원 가입
 - 회원 목록 조회
 - 질문하기
 - 질문 목록 조회
 - 회원 정보 수정
Spring에 대한 기본지식이 없는 상태에서 구현하였기 때문에 많이 부족합니다.
항상 좋은 코드리뷰 감사합니다.

구현 내용:
## config
MvcConfig : 과제에서 주어진 코드를 적용하여, url을 templates 폴더에 있는 html 파일로 맵핑하였습니다.

## Controller
MainController - "/"에 대한 맵핑을 해주는 컨트롤러 입니다.

UserController - "/users"에 대한 맵핑을 해주는 컨트롤러 입니다. (회원 관련)

QuestionController - "/questions"에 대한 맵핑을 해주는 컨트롤러 입니다. (질문 관련)

## Service
UserService - 내부적으로 arrayList로 회원 정보를 관리하며, 회원을 관리하는데 필요한 로직을 서비스 내부에 구현했습니다.

QuestionService - 내부적으로 arrayList로 질문을 관리하며, 서비스 내부에 로직을 구현했습니다.

## Domain
User - 회원 한명에 대한 정보를 저장하는 class입니다.

Question - 질문 한개에 대한 정보를 저장하는 class입니다.

2021-03-05 17:38 UTC, ksundong requested changes
안녕하세요! 아이작! 리뷰어 디온입니다!
첫 스프링 미션을 시작하신것을 축하드립니다. 앞으로 더 재미있는 과정들이 기다리고 있으니 재밌게 진행해주세요.

먼저, 배포된 App에 사소한 문제가 있어서 짚어드리려고 합니다.

- subnav가 없습니다. 다른 분들 화면상단과 비교해보세요.
  - 따라서 profile 화면도 확인하지 못했습니다.
- 회원 정보 수정시 id 수정이 안되고, 비밀번호를 비우는 것은 좋은데, 나머지 필드도 다 비워지는 건 별로 사용성이 좋지 못한 것 같아요.
- 회원 목록에서 번호가 0부터 시작하는데, 좀 이상하지 않을까요?

그리고 동기화에도 신경쓰시고, 계층 구조를 만드시려고 하신부분도 잘 하신 것 같습니다.
하지만, 몇몇 아쉬운 부분이 있어서 변경 요청을 드립니다. 

- 접근제어자가 누락된 부분이 곳곳에 있습니다. 꼭 확인해주세요.
- 네이밍에 `get`은 지양해주세요. 결코 좋은 습관이 아닙니다. `get` prefix가 붙은 네이밍은 관례상으로도 그렇고 여러 측면에서 지양하시는걸 추천드립니다.
- Java8 이전의 날짜/시간 API는 지양해주시고, Java8에서 추가된 날짜/시간 API를 사용해주세요.
- 게시글의 날짜를 String으로 저장하는 것은 별로 좋지 못한 것 같아요.
- `Controller`의 역할에 대해서 좀 더 고민해보세요. `Optional`이 이곳에 등장하는 것은 `Controller`의 책임을 벗어날 수 있다고 생각됩니다.
- 인터페이스 구현체의 네이밍에 `Impl` postfix는 지양해주세요. 그리고 굳이 Interface 분리를 해주지 않아도 되는데, 그 이유도 한 번 공부해보세요.

미션 1 진행해주시느라 고생하셨고, 코멘트 보시면서 궁금하시거나 이해가 되지 않는 부분, 의논하고 싶은 부분, 도움이 필요한 부분은 코멘트 남겨주세요.
고생하셨습니다~

2021-03-05 17:38 UTC, ksundong commented on README.md
> +## 배포 URL: [https://glacial-eyrie-85861.herokuapp.com](https://glacial-eyrie-85861.herokuapp.com)
```suggestion
## 배포 URL: <https://glacial-eyrie-85861.herokuapp.com>
```
요렇게 써주시면 됩니다.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    QuestionService questionService;
Spring의 Injection 방식에 대해서 학습해보세요.
그리고, 접근제어자 꼭 붙여주세요~

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    String getMainPage(Model model) {
굳이 get~ 을 써주지 않아도 됩니다.
mainPage 정도면 적당할 것 같아요.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    @GetMapping
이렇게 되면 기본값이 들어가게 되는데요, 기본값이 무엇인지 항상 확인해봅시다!

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
여기 참고해서 반영해주세요~

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/questions/form").setViewName("qna/form");
이 설정은 어떤 설정일까요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +import java.util.Date;
이거 말고 Java8의 날짜/시간 API를 사용해주세요.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private Integer index;
Integer를 사용해주신 이유가 있나요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private String dateTime;
날짜를 String으로 저장해주셨는데, 어떤 문제가 있을 수 있을까요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    }
toString을 오버라이딩 해주신 이유는 어떤 이유인가요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        question.setDateTime(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
상수로 빼도 좋을 만한건 상수로 빼봅시다.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        return "redirect:/";
`redirect`는 어떤 역할을 할까요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +    String createQuestion(Question question) {
네이밍 좋네요.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        }
Controller에서 Optional에 대한 처리를 하지 않고, Service에서 해봅시다.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +@Component
`Component`를 붙여주신 이유가 있나요?
`@Service`와 `Component`는 도대체 무슨 차이가 있을까요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +public class QuestionServiceImpl implements QuestionService {
`Impl`은 사용하지 않으시는걸 권장드리고 싶네요.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionService.java
> +public interface QuestionService {
인터페이스는 가급적이면 깔끔하게 유지해주세요.
이런 사용은 지양하는 편이 좋습니다.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +    private final List<Question> questions = Collections.synchronizedList(new ArrayList<>());
👍

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +        synchronized (questions) {
오우 동기화 관련 코드군요.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +        return Optional.of(questions.get(actualIndex));
`questions`에 `null`이 있다면 어떻게 될까요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/User.java
> +    }
👍

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/User.java
> +    }
👍 
정말 Id만 같으면 되는지도 생각해보세요!

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/UserController.java
> +    @PostMapping("/{id}/update")
일관성을 위해서 `userId`를 사용하는건 어떤가요?

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/UserController.java
> +    String getUsers(Model model) {
이 클래스의 메서드들은 접근제어자가 다 누락되었네요 확인부탁드려요~

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/UserServiceImpl.java
> +        return;
불필요한 return 문입니다.

2021-03-05 17:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/UserServiceImpl.java
> +            if (user.getUserId().equals(toUpdate.getUserId()) && user.getPassword().equals(toUpdate.getPassword())) {
User에 별도의 메서드로 추출하는건 어때요?

2021-03-05 17:38 UTC, ksundong commented on src/main/resources/templates/user/profile.html
> +{{user.userId}} 프로필 정보
이 부분은 프로필이 조회가 안돼서 테스트를 못해보겠네요.

2021-03-05 17:38 UTC, ksundong commented on src/main/resources/templates/user/profile.html
> +{{user.userId}} 프로필 정보
까먹을까봐 여기다 적는데, subnav가 없어서 안보입니다!

2021-03-09 09:01 UTC, isaac56 commented
죄송합니다ㅠㅠ 일이 좀 생겨서 코쿼 미션을 못하고 있었습니다.
내일 리뷰 반영해서 꼭 리뷰 재요청하겠습니다.. 기다려주세요

2021-03-10 06:16 UTC, isaac56 commented on src/main/java/com/codessquad/qna/MainController.java
> +    QuestionService questionService;
Spring에서는 IoC 컨테이너가 Bean으로 등록된 객체를 통해서 인스턴스를 생성해주고, 이를 의존성 주입이라고 부른다는 것을 배웠습니다.

2021-03-10 06:53 UTC, isaac56 commented on src/main/java/com/codessquad/qna/MainController.java
> +    @GetMapping
Bean객체가 등록된 IoC컨테이너에서 Type으로 먼저 찾은 후에 @Qualifier로 지정된 id를 확인하여 주입하는 걸로 알고 있습니다. 
현재는 QuestionService의 구현체가 하나밖에 없으므로 @Qualifier로 지정하지 않아도 Type만으로 QuestionServiceImpl이 기본값으로 들어가게 됩니다.

2021-03-10 07:01 UTC, isaac56 commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/questions/form").setViewName("qna/form");
static 폴더에 있던 html파일들을 templates 폴더로 옮겼습니다.
따라서 각 url을 templates에 있는 view 파일로 mapping하기 위한 설정을 추가하였습니다.

2021-03-10 07:02 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private Integer index;
특별한 이유가 없네요😓 
int로 수정하도록 하겠습니다.

2021-03-10 07:08 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    }
Debug 과정에서 확인하기 위해 오버라이딩했습니다.

2021-03-10 07:16 UTC, isaac56 commented on src/main/java/com/codessquad/qna/users/User.java
> +    }
UserService에서 User 구분을 id로 하고있고(primary key처럼 생각), 따라서 id만 같으면 같은 객체로 바라보게 해서 중복 id로 User가 생성되지 않도록 했습니다

2021-03-10 07:44 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private String dateTime;
dateTime에 날짜와 관련없는 문자열이 저장될 경우 문제가 생길 수 있을 것 같습니다.
dateTime은 LocalDateTime으로 저장하고, getter에서 string으로 변환하여 반환하는 방법이 나을 것 같습니다.

2021-03-10 07:51 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        return "redirect:/";
브라우저로 하여금 redirect로 지정한 url로 get요청을 하도록 하는걸로 알고 있습니다.

2021-03-10 08:51 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        }
Service의 getQuestion(int index) 메소드는
```java
    public Optional<Question> getQuestion(int index) {
        int actualIndex = index - 1;
        if (actualIndex < 0 || questions.size() <= actualIndex) {
            return Optional.empty();
        }
        return Optional.of(questions.get(actualIndex));
    }
```

index가 유효한지 확인한 후 내부의 list의 get으로 값을 반환하는 메소드인데 Service 에서 어떻게 Optional을 처리해야 할지 감이 잡히지 않네요 ㅠㅠ

2021-03-10 08:57 UTC, isaac56 commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +        return Optional.of(questions.get(actualIndex));
```java
    private final List<Question> questions = Collections.synchronizedList(new ArrayList<>());
```
questions를 final로 선언하였고 선언과 동시에 초기화하여서 null이 들어갈 상황이 없다고 생각했습니다.

2021-03-10 09:32 UTC, isaac56 commented
안녕하세요 Dion!
이번에도 자세한 코드 리뷰 감사합니다.
남겨주신 코멘트 제가 이해한 선에서 반영해보았고, 잘 모르겠는 부분은 질문으로 남겨놨습니다.
개인 사정으로 너무 늦어져서 죄송합니다 😓
잘부탁드려요!

2021-03-10 14:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    QuestionService questionService;
공부 많이 하셨네요. 잘 하셨습니다.

2021-03-10 14:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    @GetMapping
앗 제가 말씀드린 부분은 `GetMapping`입니다.
제가 의도한 건 아닌데, 좋은 공부를 하셨네요.

2021-03-10 14:22 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private String dateTime;
`getter`에서 `String`을 리턴하는건 주의해주세요.
왠만하면 그 `String`에 대한 `getter`를 만들어 주시는 편을 권장합니다.

2021-03-10 14:24 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionController.java
> +        }
이럴 경우에는 `Optional` 리턴을 하지 말자는 의미로 받아들이시면 됩니다.
`Optional`말고 그냥 예외를 던지는 것도 생각해보세요.

2021-03-10 14:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +        return Optional.of(questions.get(actualIndex));
컬렉션 자체는 null이 아닐지 모르지만, 요소는 `null` 일 수 있습니다.

2021-03-10 14:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionServiceImpl.java
> +        return Optional.of(questions.get(actualIndex));
그럴 때, `Optional.of()` 만 사용하면 예외가 발생합니다.

2021-03-10 14:44 UTC, ksundong approved these changes
안녕하세요! 아이작!
학습도 열심히 해주시고, 대부분은 다 반영이 된 것 같습니다.
아래 피드백을 남기니, 참고해서 다음 단계에 반영해주시면 되겠습니다.

다음 미션을 진행해주세요! 고생하셨습니다!

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    @Autowired
이 `@Autowired`는 굳이 붙여줄 필요가 없습니다.
위의 `Service`가 `final`이면 가능한데요. 한 번 해보세요!

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/MainController.java
> +    private QuestionService questionService;
`MainController`에서 `QuestionService`를 보는 것도 좋은 발상인데
저라면 `redirect`를 해줬을 것 같습니다!

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    private LocalDateTime dateTime;
어떤 `dateTime`인지 명확하지 않네요~

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/Question.java
> +    }
`getter`는 그대로 `dateTime`을 리턴해주고
`getFormattedDateTime()`으로 변경해주는게 좋다고 생각합니다.
그리고 `DateTimeFormatter` 부분도 상수로 추출하는 편이 좋을 것 같아요.

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/questions/QuestionService.java
> +        synchronized (questions) {
👍

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/User.java
> +    }
`equals`와 `hashCode`는 동일하게 맞추시는걸 추천드려요.

2021-03-10 14:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/users/UserController.java
> +    private String userList(Model model) {
여기 메서드들 다 `private`인데, 왜 `private`으로 만들어주셨는지 궁금하네요.

2021-03-10 14:44 UTC, ksundong commented on src/main/resources/application.properties
> +handlebars.cache=false
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
여기 확인해주시고 설정 변경해주세요!

2021-03-11 12:08 UTC, merged