[프레디]미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #18
Opened 2021-03-05 07:46 UTC by Dae-Hwa

안녕하세요 프레디입니다. 미션 1  완료했습니다.

데이터 저장은 List에 했습니다. 더미 데이터를 따로 넣는게 힘들어서 리스트 생성 시 넣어주고 있습니다.
리스트에서 찾아오는 id는 리스트의 index라고 생각하고 진행했습니다. 예를 들어, List의 0번째에 있는 데이터의 id를 0이라고 생각했습니다.

저는 `ModelAndView`가 마음에 들어서 사용했는데, 파라미터에 `Model`을 선언해주는 식으로 많이 사용하시는 것 같았습니다. 혹시 특별한 이유가 있는 것인지 궁금했습니다. `ModelAndView`는 `View` 를 클래스로 따로 지정해줘야 하는 경우가 아니면 잘 사용하지 않는 것인가요? deprecated 된 것도 아니고 이유까지는 찾기가 힘들어 질문 드립니다!

**User**

사용자 정보를 가진 클래스 입니다.

**UserController**

-   Get: /users - 사용자 목록을 출력합니다.
-   Get: /users/{id} - id와 일치하는 사용자를 출력합니다.
-   Post: /users - 사용자를 추가합니다.
-   Get: /users/{id}/form - id와 일치하는 사용자의 정보를 수정하기 위한 페이지를 보여줍니다.
-   Post: /users/{id} - id와 일치하는 사용자의 정보를 update합니다.

**Question**

질문 정보입니다. 

**Question Controller**

-   Get: /questions - 질문 목록을 출력합니다.
-   Get: /questions/{id} - id와 일치하는 질문을 출력합니다.
-   Post: /questions - 질문을 추가합니다.

**MainController**

index.html에 question과 관련된 것을 작성하는 것이 제 생각에는 어색해보였습니다. 그래서 root 디렉토리로 접속하면 /questions 로 포워딩 해주도록 했습니다.. 처음에 리디렉션으로 구현했다가 차이점을 비교해보니 제가 생각했던 방식은 포워딩이 맞는 것 같아 포워딩을 사용했습니다.

**MvcConfig**

루카스에 제시된대로 작성해줬습니다. `WebMvcConfigurerAdapter`가 deprecated 되었다고 해서 대신 `WebMvcConfigurer`를 구현했습니다.

**CustomHandlebarsHelper**

`Question`에 날짜의 타입을 스트링이 아닌 `LocalDateTime`으로 정했는데, 지정된 로케일로만 출력해주는 것 같아 출력해주기가 힘들었습니다. 스프링에서 제공하는 포멧 설정은 `ModelAttribute`로 입력을 받을때 혹은 json입출력에만 사용할 수 있는 것 같아 `formatDate`헬퍼를 만들어 사용했습니다. 현재 `qna/list.html`, `qna/show.html`에서 사용 중입니다.

감사합니다!

2021-03-06 00:39 UTC, wheejuni requested changes
스프링 첫 과제 구현하시느라 정말 수고 많으셨습니다. 💯 
크게 구조상의 변경이 필요하진 않고요, 간단한 피드백 몇 가지 드렸습니다.
확인해주시고, 추가 질문이 있으시다면 알려주세요~ 감사합니다.

2021-03-06 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/main/MainController.java
> +        return "forward:/questions";
`forward` 와 `redirect` 의 차이에 대해 아시나요?

2021-03-06 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private LocalDateTime createDateTime = LocalDateTime.now();
아래 생성자에선 또 파라메터로 이 값을 받는 것 같던데요..?

2021-03-06 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    )));
이 데이터를 리턴하는 메소드를 `Question` 에 스태틱 메소드로 별도 구현해주세요.

2021-03-06 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +@RequestMapping("questions")
항상 슬래시(`/`) 를 잊지 말아주세요. 불필요한 혼동을 방지하기 위해서요. 

```suggestion
@RequestMapping("/questions")

2021-03-06 00:39 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
> +            new User("slipp", "1234", "슬립", "slipp@sample.net")
이것도 리턴해주는 메소드를 `User`에 `static` 으로 구현해 주세요.

2021-03-07 16:52 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    )));
추가했습니다. 
2e6cd46
그런데, 네이밍을 하기 애매해서 일단 `getDummyData`로 했는데, 이런 식으로 해도 상관없는 것일지 궁금합니다.

2021-03-07 17:23 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +@RequestMapping("questions")
fc95d84
추가했습니다.
혼동을 줄 수 있는 이유가 어노테이션에 지정된 url을 스프링 내부(디스패쳐 서블릿?)에 저장할때 슬래쉬를 자동으로 붙여주는 것 같았는데,
이러면 절대경로인지 상대경로인지 명시적으로 작성되지 않아서 헷갈릴 수 있다고 생각되었습니다. 혹시 제가 생각한 부분이 맞나요?

2021-03-07 17:23 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserController.java
> +            new User("slipp", "1234", "슬립", "slipp@sample.net")
추가했습니다. 2e6cd46

2021-03-07 17:23 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/main/MainController.java
> +        return "forward:/questions";
forward는 리퀘스트를 그대로 전달해주는 것이고, redirect는 다시 전송하는 것이기 때문에 새로운 request scope가 생성된다고 알고 있습니다.

2021-03-07 17:25 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private LocalDateTime createDateTime = LocalDateTime.now();
ModelAttribute를 사용할때(기본 생성자를 사용할때)를 위해서 기본값으로 설정해뒀습니다.
제가 생각해봤을때 기본값이라는 느낌을 주기에 직접 넣어주는 것이 더 좋아보였는데 기본 생성자에서 넣어주는게 더 좋을까요?

2021-03-07 23:02 UTC, wheejuni approved these changes
네 말씀하신 것처럼 절대/상대경로 혼동 방지를 위해서라도 슬래시는 꼭 붙여주세요.
수고하셨습니다.

2021-03-07 23:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +    }
👍

2021-03-07 23:02 UTC, merged

2021-03-08 01:04 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/User.java
> +    }
감사합니다!