[Kyu] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #19
Opened 2021-03-05 08:43 UTC by kyu-kim-kr

안녕하세요.

먼저 이번 미션은 구현하는 것 자체에 신경을 많이 썼습니다.
커밋을 그다지 신경쓰지 않았습니다.
아무것도 모르는 상태에서 구현하는 게 너무너무 힘들어서 커밋 메시지까지 작성하는 데에 큰 에너지를 쓰고 싶지 않았습니다.

이번 미션1을 위해서 제가 겪은 것을 시간 순으로 적어보았습니다. 자세한 내용은 링크 누르시면 보실수 있긴한데 막 적은거라 그닥 안누르셔도 될거같아요
어려웠던 점은 진하게 표시했습니다.

### 화요일

- 배포한다는 말의 의미가 무엇인가?
- Heroku?

[내용 정리](https://velog.io/@kyukim/20210302)

### 수요일

- 헤로쿠를 통한 서버 배포
- MVC에 대한 개념을 처음 배웠다. 그닥 와닿지는 않는다.
- 회원 가입 기능 구현 자바지기 영상을 따라 잘해낸듯.
- **MVC 패턴을 몰라서 그런지 몰라도 Mapping하고 모델에 객체들을 담고 리턴하는 그런 과정들이 전혀이해가 가지 않아서 어려웠다. 비슷한 반복적인 과정을 통해 조금 어떤식으로 돌아가는지 알았다. 이게 MVC패턴을 배웠다라고 하는거겠지?**

[내용 정리](https://velog.io/@kyukim/20210303)

### 목요일

- **회원프로필정보보기 구현중에 `<th>여기</th>` 에다가 `{{userId}}` 넣으면 안되고 `<td>여기</td>` 에는 `{{userId}}` 넣으니까 된다**
- handlebars 를 이용해서 html 중복줄이는법을 배움
- 왜 다른 분들은 domain 이라는 패키지에 상태가 담긴 클래스를 넣는거지?

[내용 정리](https://velog.io/@kyukim/20210304)

### 금요일 (PR보냄)

- private static 필드를 어떻게 쓸까까 궁금했었는데, static method 메서드를 필드를 가져와서 쓰고 싶을때 그 필드를 private static으로 선언해서 사용하도록하고 외부에서는 사용하지 못하도록한다.
- **질문 제목을 클릭했을때 질문 내용을 구현하는 게 어려웠음**

[내용 정리](https://velog.io/@kyukim/20210305)

2021-03-06 08:21 UTC, ksundong requested changes
안녕하세요. Kyu! 리뷰어 Dion입니다.
이제부터 정말 재미있는 웹 서비스를 만드는 시간이네요. 앞으로의 과정은 더 즐거울 예정입니다.
제 기준에 아쉬운 부분이 보여서, 변경 요청을 드립니다. 수정하시고 다시 리뷰요청 해주세요!

---

학습 과정이니까 꼭 커밋에도 신경 많이 써주세요. 그런데, 지금도 그렇게 나쁘진 않은 것 같아요!
왜 커밋 내용에 신경을 많이 써달라고 하냐면, 좋은 습관을 들여두어야하기 때문입니다.

toggl 쓰는 분들이 있군요. 좋은 습관이라고 생각합니다.

글을 읽어보면서, 저는 스트레스 받지 말고, 그냥 만들어지는 재미를 조금 느껴가면서 해보셨음 좋겠다는 생각이 많이드네요.
구현하다가 막혀서 삽질도 좀 해보고 이런게 다 프로그래밍의 재미라고 느끼셨으면 좋겠어요.
모든 현업 개발자들은 그런 과정을 이미 한 번 밟았습니다. 검색하면 나오는 결과들이 바로 그 과정이죠.
스프링 입문은 그냥 코드스쿼드 과정만 따라가셔도 감이 오실겁니다. 저는 뭐 자랑은 아닌데 코쿼 끝날 때 까지 개구리책 말고 다른 스프링책은 본 적이 없네요. 필요하면 검색해서 공부하면 다 나옵니다.

---

- Heorku에 배포하면 초기 로딩이 느리고, 트래픽이 없으면 콜드 스타트를 한다는 문제가 있습니다. 이를 어떻게 해결할 수 있을지 한 번 고민해보시는걸 추천합니다.
- 수정 페이지의 css가 깨지는데 꼭 확인해주세요. 그래도 비밀번호만 빼고 나머지 필드가 채워지는건 잘하셨어요.
- 수정기능이 동작하지 않아요. 라고 쓰려고 했는데 아직 구현을 안하셨네요. ㅎㅎ
- 다른분들은 회원번호가 노출이 되는데, Kyu는 없더라고요. 혹시 의도적으로 제거하신건지 궁금하네요.

## 리뷰

- 불필요하게 `static`은 사용하지 말아주세요.
- `Question`에 날짜를 String으로 저장하는데 어떤 문제가 있을까요?
- `System.out.println()`은 금지입니다. `Logger`를 사용해주세요.
- 여러 클라이언트가 동시에 접근하는 이슈에 대해서 생각해보세요.
- RESTful에 대해서 정말 간단한 개념만이라도 공부해보세요.
- 클래스의 책임에 대해서 한 번 생각해보세요. 어떤 클래스가 어떤 메서드를 가져서 우리 프로그램에서 어떤 역할을 해야하는가?를 생각해보세요.
- 중복 코드에 유의해주세요.

미션 진행하느라 수고 많으셨습니다. 궁금한 점이나, 이해가 안가는 내용, 도움이 필요한 내용 등은 코멘트 남겨주세요. 빨리 확인하겠습니다.
주말 잘 보내시고, 화이팅하세요!

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/Question.java
> +    private String writer;
이후에는 User로 변경되는 편이 좋겠죠? 일단 진행해봅시다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/Question.java
> +    private String date;
날짜가 String 형태면 어떤 단점이 있을까요?
한 번 생각해봅시다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/Question.java
> +    }
toString을 오버라이딩 해주신 특별한 이유가 있을까요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    public static List<Question> questionList() {
```suggestion
    private static List<Question> questionList = new ArrayList<>();
    
    public static List<Question> questionList() {
```
필드와 메서드는 떼어주세요~

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private static List<Question> questionList = new ArrayList<>();
잘 생각해 봅시다. Controller가 하는 역할은 무엇일까요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private static List<Question> questionList = new ArrayList<>();
그리고 `static`을 붙여주신 이유가 궁금한데, 왜 붙여주셨는지 알려주세요.
그와는 별개로, 이것이 스프링의 빈에서 크게 의미가 없는 이유는 무엇일까요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private static List<Question> questionList = new ArrayList<>();
여러 명의 사용자가 동시에 접근한다면 어떤 문제가 발생할 수 있을까요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        return Collections.unmodifiableList(questionList);
이 메서드는 어디서 사용되는지 궁금하네요. 이것도 굳이 `static`일 필요는 없거든요.
일단은, `unmodifiableList`를 다들 어디서 아셨는지 궁금해지네요 ㅋㅋ
👍

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    public String question(Question question, Model model) {
저라면 `/qna`가 중복되기 때문에, class레벨에 `@RequestMapping` 애너테이션을 붙여서 전체적으로 fix를 해줄 것 같아요.
그리고 RESTful하게 표현한다면, `@PostMapping("/qna")` 정도로 표현할 수 있습니다.
보다 더 나아가면 `/questions` 정도로 바꿔볼 수 있겠네요.

---

메서드명에 조금 더 신경을 써주세요. question은 너무 하는 일을 표현해주지 못하는 것 같지 않나요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
`LocalDateTime`의 사용은 좋습니다. 상수로 뽑아줄 수 있는 부분도 보이는데 한 번 추출해보세요.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        System.out.println(question.toString());
이 미션부터는 `System.out.println` 사용보다는 `Logger`의 사용을 권장드립니다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    private List<User> userList = new ArrayList<>();
ㅋㅋ 여기는 또 `static`이 없네요. 여기를 참고해서 `QuestionController`도 한 번 바꿔봅시다.
여기도 똑같이, 동시에 많은 사용자가 접근해서 조작한다면 위험한 포인트 중 하나입니다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
과연 이거 맞는 선택일까요? 다시 생각해봐주세요.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
이 친구도 마찬가지 입니다. `UserController` 인데요... 흠..

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    @GetMapping("/user/form")
`users`를 권장합니다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    public String question(Question question, Model model) {
RESTful은 앞으로 나오게 될 정말 중요한 개념 중의 하나이기 때문에 언젠가 반드시 학습해야합니다.
어려우니까 일단 HTTP 메서드와 리소스의 조합까지만 공부해봅시다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +        System.out.println("user: " + user.toString());
여기도 `Logger`를 사용해주시고. url은 `QuestionController`의 코멘트를 참고하셔서 수정해주세요.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    @GetMapping("/user/list")
여기도 `/users` 면 충분합니다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    @GetMapping("/userList/{userId}")
보통 url에는 자료형을 보여주는 표현 대신 복수형을 많이 사용합니다. 참고해주세요.
이는 API 디자인의 안티패턴이라고 볼 수 있는데요, 내부 구현이 외부에 드러나게 되는 문제가 있습니다.

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +            if(user.getUserId().equals(userId)) {
```suggestion
            if (user.getUserId().equals(userId)) {
```
포매팅 신경 써주시구, user의 `equals` 를 오버라이딩 한다던지, `userId`를 비교하기 위한 메서드를 정의해준다던지 하면 더 깔끔해지지 않을까요?

2021-03-06 08:21 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +        }
위의 코드와 중복되지 않나요?

2021-03-06 08:21 UTC, ksundong commented on src/main/resources/templates/base.html
> +                <li><a href="#"><i class="glyphicon glyphicon-user" style="color:#1111dd;"></i> Profile</a></li>
`#`의 사용은 현재는 하지 않는 편으로 알고 있습니다~

2021-03-07 02:44 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/Question.java
> +    }
특별한 이유는 없고 자바지기님 영상 따라하면서 하다보니 넣었어요. 객체가 잘 들어가는지 보려고 toString 오버라이드 했다고도 할 수 있네요

2021-03-07 02:49 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        return Collections.unmodifiableList(questionList);
ㅎㅎ [다른 팀원 코드]((https://github.com/codesquad-members-2021/spring-boot-qna/pull/7/files#diff-64b665f3ca13fe3f4ef063d4784c1e683fe123dee8a8c1b51a8041ce5b5de092)) 따라했습니다. 현재는 이 코드에 대해서 아무 이해가 없어요.

2021-03-07 04:01 UTC, kyupid commented on src/main/java/com/codessquad/qna/Question.java
> +    private String date;
검색 중에 Calendar와 Date 클래스의 문제점을 보고 생각난건데,

날짜를 사용자가 바꿀 수도 있다? 정도밖에 생각이안나네요.

이에 대해서 한번 생각해본 링크 첨부합니다.
 https://velog.io/@kyukim/20210307

2021-03-07 04:17 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/Question.java
> +    private String date;
https://velog.io/@kyukim/20210307

2021-03-07 05:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/Question.java
> +    private String date;
`String`은 불변입니다. 면접 단골질문인데, 한 번 관련해서 찾아보시는 것을 추천드려요.
그리고, 날짜/시간 데이터를 문자열 형으로 저장하는 것은

- 데이터가 어떤 형식일지 가늠할 수 없어서, 어떤 데이터가 저장될지 모른다.
- 날짜와 시간은 표기 형식이 언제든 달라질 수 있다.
- 연산을 수행하기 적절치 않은 형태다.

정도의 문제가 있을 수 있습니다.

'날짜를 사용자가 바꿀 수도 있다.'는 이전 날짜/시간 API에서 발생하는 문젠데, 이와는 관련이 없습니다.

2021-03-07 05:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        return Collections.unmodifiableList(questionList);
ㅎㅎ `unmodifiableList`도 공부해보세요!

2021-03-08 05:34 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/Question.java
> +    private String date;
알려주셔서 감사합니다. 잘 정리해놓겠습니다!

2021-03-08 05:34 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    public static List<Question> questionList() {
넵!

2021-03-08 07:25 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    public String question(Question question, Model model) {
`@RequestMapping` 에 대해서 팀원들끼리 리뷰할 때도 배웠는데 이번엔 적용해봤습니다. 그리고 메서드명 수정했어요.

RESTful 은 나중에 한번 배워보도록 하겠습니다. 감사합니다!

2021-03-08 07:27 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
죄송합니다. 상수로 뽑아줄 수 있는 부분이라는 게 어떤 말인지 이해를 잘 못했어요 ㅠ

2021-03-08 08:02 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        System.out.println(question.toString());
넵!

2021-03-08 08:05 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    private List<User> userList = new ArrayList<>();
넵, static을 사용하지 않기위해서 questionList를 QuestionController 로 옮겼습니다.

2021-03-08 08:07 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
static 패키지에 있는 html파일들을 다 templates로 옮기면서 이렇게 하는 방법밖에는..잘 모르겠습니다..ㅠㅠ

2021-03-08 08:07 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
넵!

2021-03-08 08:08 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +        System.out.println("user: " + user.toString());
넵! 수정완료!

2021-03-08 08:09 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    @GetMapping("/userList/{userId}")
넵 숙지하겠습니다! 코드 수정하겠습니다.

2021-03-08 08:29 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +        }
넵. 메서드로 빼서 중복을 제거했어요

2021-03-08 09:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
`DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")`의 경우에는 상수로 뽑아두고, 다른곳에서 재사용할 수 있도록 해두는 편이 좋겠죠? 더불어 String을 하드코딩한 것도 상수로 추출되는 효과도 있겠습니다.

2021-03-08 09:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
`UserController`인데 `User`와 전혀 상관없는 일을 수행하는데요.
별도의 `Controller`를 빼서 (저라면 `MainController`) 해당 메서드를 그곳에 둘 것 같습니다.

2021-03-08 18:15 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
이 부분 저도 MainController 로 빼고 싶은데
MainController로 빼면 questionList()가 static이 아닌 이상 사용할수 없을거같습니다.
이유는 디온이 static 쓸 필요없다고 해서 static을 안붙이기로 해서요

그래서 그것을 questionList를 선언하고있는 QuestionController 클래스로 가져오려고했는데
그렇게하자니 `@RequestMapping`을 사용할 수 없게 됩니다. `index()`는 `@GetMapping("/")` 이라서요.

어떻게 해야 좋을까요..? 잘 모르겠습니당 ㅠ

2021-03-08 18:15 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        return Collections.unmodifiableList(questionList);
unmodifiableList에 대해서 공부해봤습니다!

TIL에 쓴거라 독백체입니다.

일단 저걸 사용하게 된 계기는 일단 빨리 구현했으면 해서 다른 분 코드를 그냥 가져온 것 뿐이었다.

unmodifiableList()는 Collections 클래스에서 제공하는 메서드이다. unmodifiableList 에 List 를 담아서 사용하면 Collection 의 add, remove 메서드 등을 사용할 수 없다. Read-only 상태가 된다. 하지만 원본 리스트 자체가 수정되지 않도록 보장되는 것은 아니다. Collections.unmodifiableList()로 리턴받은 레퍼런스 이외의 다른 레퍼런스로는 수정할 수 있다.

출처
https://soft.plusblog.co.kr/71

2021-03-08 23:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
제가 방법은 다 알려드렸는데요 ㅎㅎ
index 링크 접속 → question 목록으로 redirect 되도록 구현해보세요!

2021-03-09 06:12 UTC, kyu-kim-kr commented
@ksundong 

먼저 항상 자세하게 리뷰해주셔서 정말 감사드립니다🙏
일단 제가 전체적으로 할 수 있는 부분은 다 한것 같습니다.
[이쪽 부분](https://github.com/codesquad-members-2021/spring-boot-qna/pull/19#discussion_r588847907)은 제가 나중에 따로 시간을 내서 학습해보도록 하겠습니다.
그리고 언급해주신 다른 몇몇 부분이나 공부해야할 부분은 다음 단계에서 진행하고 싶어요.
approve 요청좀 드려도 될까요?

2021-03-09 10:55 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        return Collections.unmodifiableList(questionList);
가급적이면 우리가 사용하는 기술에 대해 이해하고 사용하시길 권장드립니다.

2021-03-09 11:28 UTC, ksundong approved these changes
안녕하세요! Kyu!
요구사항이 충족되지 않은 부분이 있어 Approve해드리고 변경 요청 드립니다.
좀 더 상세하게 방향을 제시해드렸으니, 꼭 수정해주세요.
다음 단계는 DB연동 단계여서 제가 생각하기엔 이번 단계에서 Url 설계를 하는 방법을 익히고 가는게 낫다고 판단해서 변경요청 드립니다.
다음 단계는 쉬운 편이어서 미리 진행하고 계셔도 상관 없을 것 같아요.

2021-03-09 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(QuestionController.class.getName());
`static`하게 만들어주세요!

2021-03-09 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    }
이 부분이 QuestionController에 있어야 하는지 생각해보시구, index라는 네이밍도 적절히 수정해보세요!

2021-03-09 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    @PostMapping("/qna/create")
RESTful 하게 표현한다면 `POST /question` 이 더 적절합니다.
이 부분은 요구사항이라 이 부분은 반영해주세요!

2021-03-09 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        LOGGER.info(question.toString());
```suggestion
        LOGGER.info("question: {}", question);
```

이렇게 사용하시는걸 더 권장합니다!

2021-03-09 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/UserController.java
> +    public String createUser(User user) {
이곳도 마찬가지로 `POST /users/`가 더 적절합니다.

2021-03-09 17:19 UTC, kyupid commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(QuestionController.class.getName());
`static`을 만드는게 아니라 `static`하게 하시라는 말씀이시죠?

일단 제가 시도하고 느낀점은 아래와 같습니다

Logger를 사용하는 클래스가 두 군데가 있어서 필드에 따로 각각 선언안하고 클래스로 따로 빼서 info() 를 **정적메서드로 사용하려고** 했다.  QuestionController와 UserController 둘다 같은 코드가 있기 때문에 중복제거하자는 의미에서 출발함.

근데 그렇게하려니까 문제가 발생.

private final Logger LOGGER = LoggerFactory.getLogger(QuestionController.class.getName());
이 코드에서 getLogger의 아규먼트는 Logger가 사용되어지는 클래스의 이름을 넣어야함.

근데 각각의 클래스 이름을 어떻게 따로받아서 그것도 다른 클래스에 있는 필드에 인자로 넣어줘야하나?
정적 메서드로 만드려고 시도했을 때는 그렇게 할 수 있는 방법이 보이지 않았다.
왜냐면 변수로 받아서 다음과 같이 사용할수 없다고 판단했기때문이다
```
String str;
Logger LOGGER = LoggerFactory.getLogger(str.class.getName());
```
실제로 해보니까 안됐다.

---

그래서 다른 분 코드(August)를 참고해봤더니 private static final 이라고 되어 있떠라구요.

그래서 아,, 일반적으로 상수선언할때 private static final 이라고 하던데 그걸 말씀하셨구나 하고 깨달았습니다

더나아가서 왜 굳이 static을 붙여줘야하지? 
https://stackoverflow.com/questions/11677670/when-exactly-are-we-supposed-to-use-public-static-final-string
링크를 참고했더니 이유는:

> Use public final static String when you want to create a String that:
belongs to the class (static: no instance necessary to use it)

라고 나오네요. 그러니까 인스턴스에는 불필요하고, 클래스에 속하도록 만들어야한다는것을 알았습니다

그러면 `@Controller` 가 붙은 클래스도 인스턴스가 생성되어지나? 바깥에서 일단 직접 생성할 일은 없는거같은데 내부적으로 생성되어지는 일이있나? 그런 궁금증이 생기네요. 이부분은 Controller가 어떻게 작동하는지 이해해봐야 알수잇는 부분이겠죠?

2021-03-09 17:19 UTC, kyupid commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    }
QuestionController에 일단 둔 이유는 questionList를 사용하고 싶어서입니다.
다른 곳으로 빼 questionList가 static이 될수밖에 없다고 생각해서요.
index는 음..showHome 정도로 바꿔봤습니다. 멋진이름은 생각이 안나네요..

2021-03-09 17:19 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    @PostMapping("/qna/create")
RESTful 이 자주 나와서 좀 간략하게 자료를 찾아봤는데 REST를 REST답게 사용하기 위한 컨벤션의 일종이라고 봐도 되나요?

POST /question 으로 반영하겠습니다

2021-03-09 17:19 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        LOGGER.info(question.toString());
.toString() 을 안붙이니까 리졸브할수없다고 에러가 뜨네요.
toString 안붙여도 기본적으로 재정의된 toString 으로 나온다고 알고있었는데..음

2021-03-09 17:19 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/UserController.java
> +    public String createUser(User user) {
넵 두번째 단계 중인데 로컬에서는 이쪽 부분은 모두 수정했습니다.

2021-03-10 03:37 UTC, honux77 commented
"아무것도 모르는 상태에서 구현하는 게 너무너무 힘들어서 커밋 메시지까지 작성하는 데에 큰 에너지를 쓰고 싶지 않았습니다."
-> 요거는 안 됩니다. 라고 쓰고 커밋은 봤는데 그 정도면 무난한 거 같아요.

2021-03-10 03:42 UTC, honux77 commented on src/main/java/com/codessquad/qna/UserController.java
> +    }
satic도 없애야겠죠?

2021-03-10 03:46 UTC, honux77 commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(QuestionController.class.getName());
저는 logger에는 static 안 써도 될 것 같은데요? 잘 모르겠네요.

2021-03-10 03:48 UTC, honux77 commented
Approve 되었지만 다음 단계에서 조금씩 고민해보고 수정할 것들이 있는 것 같아요. 힘들겠지만 화이팅입니다!

2021-03-10 03:48 UTC, merged

2021-03-10 04:28 UTC, kyu-kim-kr commented
> "아무것도 모르는 상태에서 구현하는 게 너무너무 힘들어서 커밋 메시지까지 작성하는 데에 큰 에너지를 쓰고 싶지 않았습니다."
> -> 요거는 안 됩니다. 라고 쓰고 커밋은 봤는데 그 정도면 무난한 거 같아요.

커밋 최대한 자세하라고 작성하라고 하셨는데,, 요번에는 최대한 열심히 작성하지 않아서 이렇게 먼저 언급했었습니다..ㅎㅎ

2021-03-10 14:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        LOGGER.info(question.toString());
제가 제안드린 형태로 사용하셨다면 그럴리 없을텐데요...

2021-03-10 14:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    }
다른 곳에서 요청을 전달하는 식으로 충분히 구현 가능합니다.
`index`의 의미는 조금 생각해 볼 여지가 있죠. 과연 저 메서드가 `index`라는 이름을 가지기에 합당할까요?

2021-03-10 14:20 UTC, ksundong commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(QuestionController.class.getName());
`@Controller`가 붙은 클래스도 인스턴스가 생성되어지나? 되게 좋은 질문이네요.
`static`을 사용하는 이유는 로딩 시점에서의 차이도 있기 때문에, 일반적인 경우엔 `static`을 붙여주는게 좋은 것 같아요.

2021-03-10 17:26 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        LOGGER.info(question.toString());
제가 뭐 잘못건드렸나봐요;; 확인해보겠습니다

2021-03-10 17:29 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    }
다른 곳에서 요청을 전달하는 식으로...한번 고민해보겠습니다.
메인페이이지를 화면에 뿌린다는 의미에서 `index` 가 맞다고 생각했는데.. 실제로 동작부분은 questionList에 관한 것이니 합당하지 않다는 생각이 들기도 하구요...음