[Bongf] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #22
Opened 2021-03-05 14:17 UTC by bong6981

안녕하세요. 백엔드반 Bongf라고 합니다. 
스프링은 처음이라 미션1에 나온 조건 안에서 구현하도록 노력해보았습니다. 
코드리뷰 감사하다는 말씀 드립니다! 

###배포링크 
---
<https://bong-spring-boot-qna.herokuapp.com/>

###User 관련 기능 구현 
-----
- UserController에서 관련 기능을 담당하도록 했습니다.
- 회원가입,  회원목록조회, 프로필조회, 회원정보 수정을 구현했습니다.
- 미션에는 회원정보 수정시 {id} 값으로 수정하라고 나와있습니다.  Questions에서 id값을 questions라는 List의 size의 값에 따라 부여하라는 조건에 따라 user에도 같은 기준을 적용했습니다. 
- User에 id값을 멤버변수로 선언하고 이를 구현했습니다.
- Repository를 사용하여 별도의 id값을 부여하는 것이 다음 단계에 나와있어 현 단게에서는 arrayList로 구현했습니다. 

####Questions 관련 기능 구현
---
- QuestionController에서  관련 기능을 담당하도록 했습니다. 
- 질문하기, 질문목록 조회하기, 질문 상세보기 기능을 구현했습니다. 
- 생성 날짜는 생성자에 LocalDateTime.now(); 으로 값을 갖도록 했습니다.

2021-03-06 12:01 UTC, ksundong requested changes
안녕하세요. Bongf! 리뷰어 Dion입니다.
재미있는 스프링 프로젝트를 시작하신것을 진심으로 축하드립니다. 🎉
앞으로는 더 재미있을 예정이니 재밌게 즐겨주세요!

## App 관련 피드백

- Heroku 배포는 초기 로딩이 느린 문제가 있습니다. 이를 콜드 스타트한다고 하는데요, 이를 어떻게 하면 해결할 수 있을지 고민해봐주세요.
- 사용자 프로필에서 사용자 이미지가 깨지는 문제가 있네요. 확인해주세요!
- 회원정보를 수정할 때, 비밀번호 필드가 채워져 있으면 안되지 않을까요?
- 비밀번호가 틀렸는데도 수정이 되는 문제가 있네요.
- 게시글 내에서 게시글이 작성된 시점의 날짜가 나오진 않네요.

## 리뷰

전반적으로 깔끔한 구현이었습니다. 몇 가지 아쉬운 부분이 있어서 변경요청을 드려요.

- `Controller`가 너무 비대한 책임을 가지는 문제가 있습니다.
- 여러 클라이언트가 동시에 접근해서 조작하는 경우를 한 번 고려해봐주세요.(다음 미션에서 해결되지만, 인지는 하고 있어야해요.)
- url 설계는 전반적으로 깔끔하지만, 한 가지 아쉬운 부분이 있었습니다.
- `Controller`에서는 `Optional`에 대한 처리를 하지 않고, 깔끔하게 다뤄주세요.
- 불필요한 기본 생성자는 생성하지 말아주세요.

첫 미션을 수행하느라 고생하셨습니다. 가급적이면 다음 미션은 참고하지 않고 진행하시는 것을 추천드립니다.
왜냐면, 현재 설계에 다음 미션이 영향을 줘버리면 학습에 도움이 되지 않을 가능성이 높거든요.

코멘트에 대해서 궁금하신 점이나, 이해가 가지 않는 부분, 도움이 필요하신 부분은 언제든 코멘트 남겨주세요.
고생하셨습니다~

2021-03-06 12:01 UTC, ksundong commented on README.md
> +<https://bong-spring-boot-qna.herokuapp.com/>
```suggestion
## 💡배포링크

<https://bong-spring-boot-qna.herokuapp.com/>
```

마크다운 lint rule은 요렇게 쓰는것을 권장합니다~

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/MvcConfig.java
> +    }
요 설정이 어떤것인지 학습해보셨나요?

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    private List<Question> questions = new ArrayList<>();
과연 `List`가 `Controller`에 위치하는 것이 좋은 것일까요?
이렇게 되면 `Controller`의 책임이 많아지게 됩니다. 어떻게 해결할 수 있을까요?

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    private List<Question> questions = new ArrayList<>();
추가적으로, 여러 클라이언트가 동시에 접근해서 조작하는 경우를 생각해보세요!

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/")
이 Url은 별로 좋지 않아보입니다.
index page는 별도의 Controller에서 담당해주는 것이 좋을 것 같네요.
redirection을 주어도 되고, 방법은 자유입니다.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @PostMapping("/questions")
이 Url은 좋네요.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    }
Controller가 가질 성격의 메서드가 아니기 때문에 발생하는 문제입니다.
private 메서드가 나올 때에는 항상 클래스 분리도 고려해봐주세요.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    @PostMapping("/users")
중복되는 url은 `@RequestMapping`을 class레벨에 붙여서 해결해줄 수 있습니다.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    public String updateUser(User updatedUser) {
변수명은 이미 업데이트 된 유저네요. 혼동을 초래할 수 있어보입니다.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    private LocalDateTime createdDate;
자바8의 날짜/시간 API 사용 좋네요 👍

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    Question() {
이 생성자에는 접근 제어자가 빠져있습니다.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        this.createdDate = LocalDateTime.now();
그리고, 이 값만 넣을 것이라면 그냥 저같은 경우에는 필드에 직접 입력하는 것을 선호하는 편입니다.

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        return createdDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
Format을 상수로 추출하는 방법도 고민해보세요!

2021-03-06 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
```suggestion
```
이런 기본 생성자는 무의미합니다. 제거해주세요.

2021-03-08 00:36 UTC, bong6981 commented on README.md
> +<https://bong-spring-boot-qna.herokuapp.com/>
네 적용했습니다~!

2021-03-08 00:46 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/config/MvcConfig.java
> +    }
기존에 static에 있던 html 들을 templates으로 옮기면서 루카스에 있는 내용을 적용했습니다.
예를들어 "/questions/form"으로 url 접근할 경우 static 폴더에 더이상 없기 때문에 getMapping을 해줘야 하는데 이들을 한 번에 해주는 기능으로 알고 있습니다. 
해서 현재 index.html에서  <a href="/questions/form" class="btn btn-primary pull-right" role="button">질문하기</a> 이부분에서 "/questions/form" 부분을 mapping 해주지 않아도 해당 html로 (qna/ 디렉토리에 form) 연결 된다고 아는 선에서 학습했습니다.!

2021-03-08 05:06 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    @PostMapping("/users")
@RequestMapiing을 적용해보았습니다. 훨씬 코드가 깔끔해졌네요. 감사합니다 : )

2021-03-08 05:15 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    public String updateUser(User updatedUser) {
수정된 내용이 날라오기 때문에 구분해주기 위해 다른 단어를 사용한다는 것이 혼동을 초래한 것 같습니다. 
메소드명이 updateUser이며 구현 내용도 users에 user를 업데이트 해주고 있기 때문에 
user가 업데이트된다는 내용이 이해될 수 있다 생각 & 주신 피드백 반영하여 변수명을 user로 변경했습니다. !

2021-03-08 05:38 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    Question() {
생성자를 추가했습니다!

2021-03-08 05:56 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        this.createdDate = LocalDateTime.now();
생성자에서 여러 개를 초기화 해주는 것이 아니니 필드에서의 초기화가 더 가독성이 좋은 이유에서일까요? 해당 이유로 학습하고 말씀주신대로 수정했습니다.

2021-03-08 05:57 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        return createdDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
값이 고정적이므로 상수로 사용하는 것이 더 좋을 것 같습니다. 감사합니다. : )

2021-03-08 06:31 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
사실 자바의 정석을 보고 '생성자가 하나도 없을 때만 컴파일러가 기본생성자를 자동 추가해주기 때문에 다양한 에러가( 예를 들어 기본생성자가 아닌 다른 생성자가 있는 상황에서 기본 생성자로 객체를 만들 경우 혹은 이를 상송 받은 다른 클래스에서 super();로 인해 존재하지 않는 기본생성자가 호출될 경우 등으로 오류가 나는 상황 등) 발생할 수 있어 비어있는 기본 생성자를 추가해주는 것을 습관으로 해야한다'.는 습관을 들이기 위해 넣어주고 있는데 이런 피드백을 벌써 여러번 받은 것 같습니다.  
주신 피드백으로 명확한 기능 없이 생성자를 넣는 것은 안되는 것이라고 ( 단순히 차후에 발생할 에러방지를 위해서라도) 인지하고 있으면 되는 것일까요?

2021-03-08 10:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/config/MvcConfig.java
> +    }
학습하느라 고생하셨어요!

2021-03-08 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    public String updateUser(User updatedUser) {
오 나름의 결론을 내리셨군요 👍

2021-03-08 10:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    Question() {
접근 제어자 말씀하신거 맞죠? ㅋㅋ

2021-03-08 10:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        this.createdDate = LocalDateTime.now();
네, 저같은 경우에는 저 값이 기본생성자 이외의 새로운 생성자가 생긴다하더라도 어지간하면 `now()` 값이 기본일 것이라고 생각합니다. 그런 이유에서 선택하기도 했어요.

2021-03-08 10:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
네 어차피 컴파일 에러가 발생하는 부분이기 때문에,  컴파일 에러가 나도록 하는 편이 낫겠습니다.

2021-03-08 16:49 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    private List<Question> questions = new ArrayList<>();
controller에 대한 이해가 부족하여 예제를 보고 따라하고 다른 곳으로 옮길 생각을 못했습니다. 
주말동안 controller-service-repository  부분을 학습해보아 적용해보았습니다! 
동시 접근 문제에 관해 synchronizedList로 만들어주었습니다.

2021-03-08 16:49 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/")
Home Controller를 만들어 처리했습니다!

2021-03-08 16:50 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +    }
private 메서드가 나와서 찜찜했었는데 학습 부족의 결과였네요😂
private 메서드가 나올 때는 클래스 분리를 고민하겠습니다. 
현재는 해당 기능은 다른 클래스로 분리했습니다!

2021-03-08 16:51 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    Question() {
앗 넵! 처음에는 생성자를 추가했고 말씀주신대로 필드에 입력하여 생성자를 제거했습니다!

2021-03-08 16:52 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        this.createdDate = LocalDateTime.now();
다른 생성자가 생길시도 고려하시는군요. 많이 배워갑니다! 감사합니다

2021-03-08 16:53 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
오 그렇군요!

2021-03-08 17:03 UTC, bong6981 commented
꼼꼼한 피드백 덕분에 많이 배웠습니다. 감사합니다 : ) 
주말에 controller-service-repository에 대해 학습해서 말씀 주신 컨트롤러가 맡을 일이 아닌 일들을 부과했던 문제를 해결해 보았습니다. 아직 이해가 미흡하여 올바른 적용을 했을지 걱정 됩니다. 
다음 미션은 참고하지 않고 진행해보겠습니다. 감사합니다. 

피드백 관련
---
- Heroku 배포는 초기 로딩이 느린 문제가 있습니다. 이를 콜드 스타트한다고 하는데요, 이를 어떻게 하면 해결할 수 있을지 고민해봐주세요.
    - 아직 이부분에 대해 답을 찾지 못했습니다. 조금 더 공부해보겠습니다.
- 사용자 프로필에서 사용자 이미지가 깨지는 문제가 있네요. 확인해주세요!
   - 경로가 잘못되어 있던 부분 수정했습니다! 
- 회원정보를 수정할 때, 비밀번호 필드가 채워져 있으면 안되지 않을까요? 비밀번호가 틀렸는데도 수정이 되는 문제가 있네요.
  - 비밀번호 로직에 관해 아예 생각을 안해봤던 것 같습니다. 처음에 비밀번호가 나타나지 않게 수정하였고, 올바른 비밀번호를 입력해야 회원 정보가 수정되록 구현했습니다. 
- 게시글 내에서 게시글이 작성된 시점의 날짜가 나오진 않네요.
   - 날짜 반영 안된 부분 수정했습니다. 

Conroller 관련 수정한 부분
---
- controller - service - repository 로 컨트롤러에 쏠려 있던 기능을 분산시켰습니다. 
- 차후에 repositosry를 찾는 부분은 데이터 관련으로 갈아낄 것으로 생각되어 interface로 구현한 후 해당 구현체는 Memory~Repository 클래스로 만들었습니다.

2021-03-09 12:19 UTC, ksundong approved these changes
피드백 반영해주시느라 고생많으셨습니다. 공부 열심히 하신것이 눈에 띄는 것 같아요.
어떤걸 참고하지 않으신다는건지 궁금하네요!
바로 다음단계 진행해주셔도 좋을 것 같습니다! 고생하셨어요~

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +        return "redirect:/questions";
👍

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    }
Spring의 Injection 방식에 대해서도 간단하게 알아보세요~

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    private LocalDateTime createdDate = LocalDateTime.now();
```suggestion
    private LocalDateTime createdDateTime = LocalDateTime.now();
```
요렇게 쓰시는걸 추천드릴게요!

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/repository/MemoryQuestionRepository.java
> +    private List<Question> questions = Collections.synchronizedList(new ArrayList<>());
👍

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/repository/MemoryQuestionRepository.java
> +        return new ArrayList<>(questions);
👍

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/repository/MemoryUserRepository.java
> +    public Optional<User> findByUserId(String userId) {
오 Optional의 사용 좋습니다.

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/repository/QuestionRepository.java
> +public interface QuestionRepository {
오 공부 열심히하셨네요!

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
validation 좋네요!

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        return foundUser.get();
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/
여기 참고하셔서 `OrElseThrow`로도 바꿔보세요!

2021-03-09 12:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        if (!originUser.getPassword().equals(user.getPassword())) {
`User`쪽에서 처리를 해주는 것은 어떨까요?

2021-03-09 13:11 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    }
간단하게만 알고 있는데 더 학습해보겠습니다~!

2021-03-09 13:19 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    private LocalDateTime createdDate = LocalDateTime.now();
넵 수정했습니다!

2021-03-09 13:25 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        if (!originUser.getPassword().equals(user.getPassword())) {
오! 그게 더 깔끔할 것 같습니다. 다음 미션 때 적용해보겠습니다!

2021-03-09 13:32 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        return foundUser.get();
네 수정했습니다. 더 학습해봐야겠네요!

2021-03-10 04:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
필요한 순간이 나오면 그 때 추가하는게 좋죠 👍

2021-03-10 04:09 UTC, merged