[Pyro] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #23
Opened 2021-03-05 14:49 UTC by ghojeong

https://ghojeong-spring-boot-qna.herokuapp.com/

위 링크에서 배포를 했습니다.

아래 기능을 모두 구현했습니다.

- 회원가입
- 사용자 목록
- 회원 프로필 정보 보기
- 질문 목록
- 질문 상세보기
- 회원정보 수정

추가 구현이나 수정이 욕심나는 부분에, TODO 와 FIXME 주석을 달았습니다.

2021-03-05 14:54 UTC, ghojeong commented on src/main/resources/templates/layout/base2.html
> +<script src="../../js/scripts.js"></script>
base2.html 은 base.html 에서 상대경로가 `../` 이 한단계 더 있다는 것을 빼놓고는 모든 것이 동일합니다.
base.html 과 base2.html 을 하나의 파일로 합치고 싶은데 무슨 좋은 수가 없을 까요?
url 의 host 가 달라지더라도, pathname 은 상관없이 절대경로처럼 지정할 수 있는 방법이 없을 지 여쭈어봅니다.

[웹펙에는 alias path](https://webpack.js.org/configuration/resolve/) 라는 개념이있어서, 경로를 지정이 가능한데
plain html 과 plain javascript 는 어렵군요.

2021-03-05 15:21 UTC, janeljs commented on src/main/resources/templates/layout/base2.html
> +<script src="../../js/scripts.js"></script>
상대경로가 아닌 절대경로로 `/js/jquery-2.2.0.min.js`와 같이 지정하면 해당 문제를 해결할 수 있지 않을까요?🤔

2021-03-05 15:45 UTC, ghojeong commented on src/main/resources/templates/layout/base2.html
> +<script src="../../js/scripts.js"></script>
헉!! 잘 되네요... 감사합니다.

2021-03-07 04:14 UTC, SANGCO requested changes
Pyro님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/question/QuestionController.java
> +    QuestionMapper questionMapper = new QuestionMapper();
Mapper라는 이름은 좀 어색한거 같네요. 
매핑 하는 부분은 없는거 같아서요. 
QuestionRepository 정도면 어떨까 싶은데요.

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/question/QuestionMapper.java
> +        int questionId = questions.size() + 1;
`questions.size() + 1` 이런식으로 구현을 하면
여러명이 동시에 질문을 등록하면 문제가 되지 않을까요?
Map도 사용하시고 했는데
디비 적용하기 전에 이런 부분들도 한번 고민해 보면 좋을거 같아서요.

다음 미션에서 디비를 적용하니깐 따로 수정은 안하셔도 될거 같네요~

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/user/User.java
> +    private String email = "defaultEmail";
이 부분은 좀 이상한데요.
테스트용 User가 필요하면 테스트용 객체를 만드는게 어떨까요?

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/user/UserMapper.java
> +public class UserMapper {
이 부분도 클래스 이름이 좀 어색한거 같습니다.

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/question/QuestionController.java
> +    @PostMapping("/question/create")
uri가 question으로 되어있군요.
요구사항에 있는
`각 기능에 따른 url과 메소드 convention`
항목을 보고 전체적으로 url을 다시 수정해 봅시다.

2021-03-07 04:14 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @PostMapping("/user/create")
UserController도 동일하게 uri에 대해서 전체적으로 수정해 봅시다.

2021-03-07 04:20 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/user/User.java
> +    private String email = "defaultEmail";
앗 이건 지울려고 했던 건데 깜빡했네요. 저 default 텍스트 삭제하겠습니다.

2021-03-07 04:23 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @PostMapping("/user/create")
기존의 html 에 나와있는 uri 를 그대로 사용했더니 이렇게 되었네요. 컨벤션에 맞게 전부 수정하겠습니다.

2021-03-07 04:37 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/question/QuestionMapper.java
> +        int questionId = questions.size() + 1;
단순한 HashMap 대신에 ConcurrentHashMap 을 사용해서 race condition 을 방지하겠습니다.

2021-03-07 04:38 UTC, ghojeong commented
@SANGCO 주신 피드백에 대해서 수정 완료했습니다!
주말인데도 휴식을 취하지 못하고 고생하시네요 ㅠ.ㅠ

2021-03-07 04:40 UTC, ghojeong commented
Mapper 대신에 Repository 라는 네이밍을 쓰시기를 권장하셨는데,
Repository 가 무엇을 뜻하는지에 대한 설명 추가로 해주시면 감사하겠습니다.
DDD 에서 나온 개념이라고 들었는데, 자세히 알지는 못해서요.
@SANGCO

2021-03-07 05:08 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @RequestMapping(value = "/{userId}/update", method = RequestMethod.POST)
```suggestion
    @RequestMapping(value = "/{userId}/update", method = RequestMethod.PUT)
```

으로 하고 싶은데, html 의 form 태그에서 
`<form name="question" method="put" action="/users/{{user.userId}}/update">`
처럼 메소드를 put 으로 지정할 수 있는 방법은 없을 까요?
form 의 메소드를 put 으로 지정하려하니, 제대로 요청이 가지 않아서요

2021-03-07 05:09 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @RequestMapping(value = "/{userId}/update", method = RequestMethod.POST)
https://stackoverflow.com/questions/8054165/using-put-method-in-html-form

```html
<form method="post" ...>
  <input type="hidden" name="_method" value="put" />
...
```

2021-03-07 05:11 UTC, ghojeong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @RequestMapping(value = "/{userId}/update", method = RequestMethod.POST)
위의 stackoverflow 를 따라해보았는데 잘 되지 않네유 😭

2021-03-07 11:27 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +    @RequestMapping(value = "/{userId}/update", method = RequestMethod.POST)
디온이 슬랙에 올렸던데 확인하셨죠?ㅋ

2021-03-07 11:28 UTC, SANGCO commented
> Mapper 대신에 Repository 라는 네이밍을 쓰시기를 권장하셨는데,
> Repository 가 무엇을 뜻하는지에 대한 설명 추가로 해주시면 감사하겠습니다.
> DDD 에서 나온 개념이라고 들었는데, 자세히 알지는 못해서요.
> @SANGCO

2021-03-07 11:28 UTC, closed without merging