[노을] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #24
Opened 2021-03-05 14:52 UTC by sanhee

📣 배포링크 : https://noel-boot-qna.herokuapp.com/

안녕하세요, 백엔드반 노을입니다.
이번 스프링 부트 프로젝트 따라하기? 과제는 콘솔창을 보던 자바 프로젝트보다 훨씬 재미있던 것 같습니다.

다만 웹 개발에 대한 경험이 없어서, 과정을 실습하는데 꽤 오래 걸렸습니다.
또 미션을 진행하면서 어려움이 생겼을 때 동기분들의 코드를 참고하면서 문제를 해결하여, 비슷한 부분이 다수 존재합니다.😂

아직 개선될 부분이 많은 부족 코드지만, 섬세히 리뷰해주셔서 감사합니다!!

### 현재 구현된 기능
 - 요구사항에 있는 기능 모두 구현하였습니다.
 
✔ 회원가입, 사용자 목록 기능
✔ 회원 프로필 정보보기
✔ 질문하기, 질문 목록 기능 구현
✔ 회원정보 수정

### 궁금한 점
- 요구사항에 있던 `URL과 html 쉽게 연결하기` 에서 
```java
@Configuration
public class MvcConfig extends WebMvcConfigurerAdapter {
	@Override
 public void addViewControllers(ViewControllerRegistry registry) {
		registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
		
  registry.addViewController("/users/form").setViewName("user/form");
  registry.addViewController("/users/login").setViewName("user/login");
  registry.addViewController("/questions/form").setViewName("qna/form");
 }
}
```
와 같이 구현하는 것은 컨트롤러 클래스에서 맵핑하여 메소드를 만드는 것과 무슨 차이가 있는지 궁금합니다.
제가 이해한 것은 맵핑해서 메소드로 작성하는 방식이 좀 더 세세한 설정이 가능하다는 것인데 맞게 이해한것인지 모르겠습니다.

### 번외로 회원정보를 수정할 때 비밀번호가 틀리면 경고창이 뜨는 것을 적용해보았습니다.
 - JavaScript를 다뤄본적이 없어서, 간단히 학습하면서 적용해보았는데, 작동은 하지만 올바르게 쓴 것인지 잘 모르겠습니다..
 - 경고창은 `script.html`에 모아서 작성했습니다.
 
![](https://i.imgur.com/VMYwzCR.gif)

2021-03-05 14:56 UTC, ghojeong commented
@sanhee 
와우! gif 로 실행과정을 직접 만드신게 인상깊네요.
어떻게 gif 만드셨나요?

2021-03-05 15:58 UTC, sanhee commented
> @sanhee
> 와우! gif 로 실행과정을 직접 만드신게 인상깊네요.
> 어떻게 gif 만드셨나요?

엇.. 특별한건 없습니다!! 생각보다 손이 조금가긴 하지만,,
1. `ocam`이라는 녹화프로그램으로 촬영하고,
2. [ezgif](https://ezgif.com/video-speed) 사이트에서 속도 조절 및 gif 변환하면 제작할 수 있습니다.😀

2021-03-06 17:14 UTC, janeljs commented on src/main/resources/templates/common/script.html
> +{{#invalidPassword}}<script> alert( "비밀번호가 올바르지 않아, 변경이 취소됐습니다." ); </script>{{/invalidPassword}}
오오! 저도 창 띄우는 거 따라해봐야겠어요😆

2021-03-07 05:25 UTC, SANGCO requested changes
노을님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +        registry.addViewController("/qna/form.html").setViewName("qna/form");
`registry.addViewController("/index.html")` 뒤에 .html을 때서 다시 또 실험을 해봅시다.

https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-config-view-controller

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/Question.java
> +    private int id;
id가 제일 위로 오면 좋을거 같네요.
id를 int로 하는것과 long으로 하것은 어떤 차이가 있을까요?

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        question.setId(questionList.size() + 1); // 질문 객체 아이디 정의
`questions.size() + 1`
나중에 넣고 지우고 하면 이런식으로 구현을 했을때는 문제가 생기겠네요.
동시에 여러명이 `/questions`를 호출해도 문제가 있겠죠?

다음 미션에서 데이터베이스를 적용하면 자연스럽게 수정을 하시겠지만
한번 생각해보시면 좋을거 같아서 리뷰 남깁니다.
따로 수정은 안하셔도 될거 같네요~

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    @GetMapping("/")
요구사항에 있는
`각 기능에 따른 url과 메소드 convention`
항목을 보고 전체적으로 url을 다시 수정해 봅시다.

`/index`로 보내는 부분은 별도의 컨트롤러를 만드는게 좋을거 같네요.
`questionList`를 사용하는데 별도에 컨트롤러로 분리 시키시는게 이상해 보일 수도 있지만
향후에 AJAX를 적용하는 미션에 가면 이 부분도 깔끔하게 분리가 된답니다.

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/QuestionController.java
> +            }
다음 단계에서 repository를 적용하는 부분이 있어서 
이번 미션에서는 이부분은 넘어가도 될거 같네요ㅋ

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/UserController.java
> +    @PostMapping("/user/create")
UserController 클래스도  uri를 전체적으로 수정해 봅시다.

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/UserController.java
> +        userId = Objects.toString(userId, ""); // null 값일 경우 "" 정의
null 값일 경우 일단 Exception을 던지는 쪽으로 수정해 봅시다.
향후에 벨리데이션을 적용할 기회가 있을거 같습니다.

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/UserController.java
> +        userId = Objects.toString(userId, ""); // null 값일 경우 "" 정의
이 부분도 동일합니다.

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/UserController.java
> +        }
다음 미션에서 repository가 적용이 되면 이부분이 깔끔하게 변경이 되었으면 좋겠네요.

이번 미션에서는 
`Objects.equals(userList.get(index).getPassword(), updateUser.getPassword());`
이부분을 User 클래스로 옮겨 봅시다.
페스워드를 가지고 있는 User 객체에게 비밀번호가 맞는지 물어보는거죠.

2021-03-07 05:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +package com.codessquad.qna;
패키지도 Controller나 domain 별로 나누는건 어떨까요?

2021-03-07 05:25 UTC, SANGCO commented on src/main/resources/templates/user/login_failed.html
> +<script src="../../js/scripts.js"></script>
https://github.com/codesquad-members-2021/spring-boot-qna/pull/23#discussion_r588353714

이 부분도 추가로 다시 학습을 해봅시다.

2021-03-07 09:13 UTC, sanhee commented on src/main/resources/templates/common/script.html
> +{{#invalidPassword}}<script> alert( "비밀번호가 올바르지 않아, 변경이 취소됐습니다." ); </script>{{/invalidPassword}}
좋게봐주셔서 감사합니다 ㅎㅎ

2021-03-07 09:18 UTC, sanhee commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +        registry.addViewController("/qna/form.html").setViewName("qna/form");
> 노을님 구현 잘하셨네요. 고생하셨습니다!
> 리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

섬세한 리뷰 감사합니다! 오늘 일정이 있어서 일정 마치는대로 
리뷰해주신 부분 학습하고 반영하도록 하겠습니다.😁

2021-03-08 10:00 UTC, sanhee commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +        registry.addViewController("/qna/form.html").setViewName("qna/form");
```java
        registry.addViewController("/qna/form").setViewName("qna/form");
        registry.addViewController("/user/form").setViewName("/user/form");
```
와 같이 해본 결과 `GetMapping` 메서드와 동일한대 좀더 간결하게 모아서 정리할 수 있는 것 같습니다.

하지만 아래와 같은 `GetMapping` 메서드는 `addViewController` 에서 정상적으로 표현하지 못하는 것 같은데
제가 이해한 것이 맞을까요?

```java
    @GetMapping("/")
    private String questionsList(Model model) {
        model.addAttribute("questions", questionList);
        return "/index";
    }
```

2021-03-08 10:36 UTC, sanhee commented on src/main/java/com/codessquad/qna/Question.java
> +    private int id;
더 많은 정수 범위를 허용할 수 있어서, 더 많은 아이디 정보를 저장할 수 있는게 차이점 같습니다.

혹시 더 존재하나요?😊

2021-03-08 10:38 UTC, sanhee commented on src/main/java/com/codessquad/qna/QuestionController.java
> +        question.setId(questionList.size() + 1); // 질문 객체 아이디 정의
스레드 파트에서 배운 synchronized() 메소드를 통해 경쟁상태를 해결할 수 있을 것 같습니다!!

2021-03-08 11:00 UTC, sanhee commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    @GetMapping("/")
```java
public class QuestionController {
    private static List<Question> questionList = new ArrayList<>();
...
    public static List<Question> getQuestionList(){
        return questionList;
    }
}
```

```java
@Controller
public class IndexController {
    @GetMapping("/")
    private String questionsList(Model model) {
        model.addAttribute("questions", QuestionController.getQuestionList());
        return "/index";
    }
}
```

와 같이 수정을 하였습니다!
List를 `static` 으로 선언한뒤 리턴시켜주는 방식으로 구현하였는데
올바르게 한게 맞을까요?

2021-03-08 11:00 UTC, sanhee commented on src/main/java/com/codessquad/qna/QuestionController.java
> +            }
넵 ,다음 미션에서 개선해보도록 하겠습니다!! 감사합니다ㅎㅎ

2021-03-08 11:03 UTC, sanhee commented on src/main/java/com/codessquad/qna/UserController.java
> +        userId = Objects.toString(userId, ""); // null 값일 경우 "" 정의
```java
userId = Objects.requireNonNull(userId, "Exception: userId가 NULL 값입니다.");
```
와 같이 구현 완료 및 푸쉬했습니다ㅎㅎ

2021-03-08 11:03 UTC, sanhee commented on src/main/java/com/codessquad/qna/UserController.java
> +        userId = Objects.toString(userId, ""); // null 값일 경우 "" 정의
반영했습니다!

2021-03-08 11:07 UTC, sanhee commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +package com.codessquad.qna;
아직 클래스 파일이 많지 않아서, 따로 정리하지 않았었는데
지금 보니까 지전분한면이 있는것 같네요!!
리뷰어님 말씀 반영하고 푸쉬 완료했습니다!

2021-03-08 11:18 UTC, sanhee commented on src/main/resources/templates/user/login_failed.html
> +<script src="../../js/scripts.js"></script>
`..`는 현재 웹페이지의 부모 폴더였군요.. 
실습중에 카테고리를 클릭할 때마다 URL이 중복해서 뒤에 덕지덕지 붙는 불상사가 있었는데 우연히 지우다가 문제를 해결 한 케이스라 원인을 모르고 있었습니다. `키워드` 감사합니다!!

리뷰 반영하여 푸쉬 완료했습니다 .

2021-03-08 11:30 UTC, sanhee commented on src/main/java/com/codessquad/qna/UserController.java
> +        }
```java
👻User.java

    public static boolean checkId(User previousId, User updatedId){
        return Objects.equals(previousId.getUserId(), updatedId.getUserId());
    }
    public static boolean chekPassword(User previousId, User updatedId){
        return Objects.equals(previousId.getPassword(), updatedId.getPassword());
    }

```


```java
🌏UserController.java

boolean idCheck = User.checkId(userList.get(index),updateUser); // 아이디 유효성 체크
boolean findPasswordCheck = User.chekPassword(userList.get(index),updateUser); // 비밀번호 유효성 체크
```

와 같이 분리해보았는데, 리뷰어님의 말씀하신 의도를 제가 잘 수행했는지 궁금합니다!

2021-03-08 11:35 UTC, sanhee commented
리뷰어님이 말씀하신 사항 반영 및 푸쉬 완료하여 `PR 재요청` 드립니다.😊

그리고 한 가지 궁금한 점이 있어서 질문✋드립니다!

```java
registry.addViewController("/user/form").setViewName("/user/form");
```
에서 `/user/form` 을 `user/form` 으로 해주게 되면 URL이 중첩되는 현상이 있었는데
제가 학습 후 이해한 바로는 경로 앞에 `/`를 안해주면 `상대경로`로 인식해서, 이전 페이지 URL에서 중첩되는 현상이 발생하는게 맞나요?

2021-03-09 03:46 UTC, SANGCO commented on src/main/java/com/codessquad/qna/Question.java
> +    private int id;
다른 차이점은 없습니다~
프로그램을 만들 때 서비스가 얼마나 많이 쓰일지는 알 수 가 없으니
주로 id 값은 int 보다 long을 사용한답니다.

2021-03-09 03:55 UTC, SANGCO commented on src/main/java/com/codessquad/qna/MvcConfig.java
> +        registry.addViewController("/qna/form.html").setViewName("qna/form");
`registry.addViewController("/user/form").setViewName("/user/form");`
`return "/index";`
뷰를 리턴 할 때는 `/`를 빼주셔도 됩니다.

uri가 '/' 되면 기본으로 index.html이 호출이 될겁니다.
addViewControllers에서 등록할 필요가 없죠.

2021-03-09 03:57 UTC, SANGCO commented on src/main/java/com/codessquad/qna/QuestionController.java
> +    @GetMapping("/")
이 부분은 다음 미션에서 repository를 적용을 하면 저절로 수정이 될겁니다~

2021-03-09 04:19 UTC, SANGCO approved these changes
고생 하셨습니다~

2021-03-09 04:19 UTC, SANGCO commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/user/form").setViewName("/user/form");
`.setViewName("/user/form");`
`.setViewName("user/form");` 이렇게 수정해 주세요.

2021-03-09 04:19 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/IndexController.java
> +        return "/index";
여기도 `"index"` 이렇게 수정합시다.

2021-03-09 04:19 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        return "/qna/show";
여기도 `"qna/show"`
전체적으로 이 부분은 다 수정합시다.

2021-03-09 04:21 UTC, merged