[새리] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #25
Opened 2021-03-05 17:33 UTC by min27604

안녕하세요, 새리입니다.
많이 부족한 실력이지만 최선을 다해 미션요구사항을 구현했습니다. 시간내주셔서 리뷰해주시는 점 미리 감사드리며 구현사항은 아래와 같습니다.

- 회원가입
- 회원 목록 조회
- 회원 프로필 조회
- 회원 정보 수정
- 질문하기
- 질문 조회

[배포 URL](https://sallys-qna.herokuapp.com/)

감사합니다!

2021-03-07 11:18 UTC, SANGCO requested changes
새리님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        Question question = new Question(writer, title, contents, questions.size() + 1);
`questions.size() + 1`
나중에 넣고 지우고 하면 이런식으로 구현을 했을때는 문제가 생기겠네요.
동시에 여러명이 `/questions`를 호출해도 문제가 있겠죠?

다음 미션에서 데이터베이스를 적용하면 자연스럽게 수정을 하시겠지만
한번 생각해보시면 좋을거 같아서 리뷰 남깁니다.
따로 수정은 안하셔도 될거 같네요~

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int id;
id가 제일 위로 오면 좋을거 같네요.
id를 int로 하는것과 long으로 하것은 어떤 차이가 있을까요?

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    @GetMapping("/")
요구사항에 있는
`각 기능에 따른 url과 메소드 convention`
항목을 보고 전체적으로 url을 다시 수정해 봅시다.

`index`로 보내는 부분은 별도의 컨트롤러를 만드는게 좋을거 같네요.
`questions `를 사용하는데 별도에 컨트롤러로 분리 시키시는게 이상해 보일 수도 있지만
향후에 AJAX를 적용하는 미션에 가면 이 부분도 깔끔하게 분리가 된답니다.

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("user")
`@RequestMapping("/user")`
저는 개인적으로 `/`를 생략하지 않습니다.

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("")
`@GetMapping("/")`

2021-03-07 11:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/create")
요구사항에 있는
`각 기능에 따른 url과 메소드 convention`
항목을 보고 전체적으로 url을 다시 수정해 봅시다.

2021-03-07 12:13 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int id;
제가 알고있는 int와 long은 값의 범위와 크기에 차이가 있다고 알고있습니다. 제 서버에서는 question 인스턴스가 20억개는 넘지 않을 것 같아 int로 설정했습니다. long으로 하는 편이 더 나을까요?

2021-03-07 12:51 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    @GetMapping("/")
말씀하신 리뷰를 토대로 별도의 컨트롤러(메인컨트롤러)를 만들어 메인컨트롤러에서 QnaController로 redirect를 해주는 방식으로 고쳐보았습니다. 근데 이렇게 하니 메인 페이지임에도 URL에 /questions를 붙여야하는 방법밖에 떠오르지 않네요(개인적으로 인덱스 페이지는 '/' 로만 시작하고 싶습니다😢) 반대로 QnaController에서 메인컨트롤러로 redirect하려니 questions 리스트를 모델로 감싸 넘겨주어야 하는데 이 부분도 questions getter를 만들어야 하는건지, 또 @Controller 애노테이션이 붙은 클래스에 getter를 집어넣는게 맞는 방식인지 궁금합니다

2021-03-07 14:05 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    @GetMapping("/")
다음 미션에 보면 repository를 적용하는데
메인컨트롤러에서 QnaRepository를 사용하면
고민하시던 부분이 깔끔하게 해결이 되실겁니다.
이 부분은 다음 미션에서 수정하셔도 될거 같네요~

2021-03-07 14:25 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int id;
프로그램을 만들 때  서비스가 얼마나 많이 쓰일지는 알 수 가 없으니
주로 id 값은 int 보다 long을 사용한답니다.

2021-03-07 14:54 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("")
말씀하신대로 RequestMapping에 슬래시를 넣고 해당부분에도 슬래시를 넣었습니다. 이런저런 시도를 해 본 결과 @GetMapping("")으로 매핑하면(리퀘스트 매핑을 거치므로 "/user") URL 끝에 슬래시의 유무에 상관없이 맞는 페이지로 가지만 @GetMapping("/")의 경우에는(URL = "/user/" 로 가게되지만) 슬래시를 임의로 빼게되면 URL을 인지하지 못해 404에러가 뜹니다. 이 부분이 혹시나 나중에 문제가 될 지, 또 어떤 방식으로 처리하는 게 더 나을 지 의견 알려주시면 감사하겠습니다!
1. @GetMapping(“users/form”) -> users/form (O) + users/form/ (O)
2 @GetMapping(“users/form/“) -> users/form (X) + users/form/ (O)

2021-03-07 14:55 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int id;
넵ㅎㅎ 감사합니다!

2021-03-07 15:01 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    @GetMapping("/")
알겠습니다. 감사합니다!

2021-03-08 01:21 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("")
`@GetMapping("/")`
`@GetMapping(“/users/form”)`
제가 말하고 싶었던건 이런 식으로 uri가 `/`로 시작하게 수정을 해달라는 것 이었습니다. 
마지막에 `“users/form/“` 이렇게 `/`를 넣을 필요는 없습니다.

2021-03-08 07:04 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("")
`@RequestMapping("/user")`가 있는 상태에서 말씀하신 부분을 `@GetMapping("/")`로 바꾸니 URL을 /user/ 로 하지 않으면 404 에러가 떠서요..😢 혹시 제가 잘못 이해하는 부분이 있을까요 알려주시면 감사하겠습니다ㅠㅡㅠ

2021-03-08 15:58 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("")
그렇네요.
이 경우에는 `@RequestMapping("/users")`를 없애고
`@GetMapping("/users")`
`@GetMapping(“/users/form”)`
이렇게 가야 겠군요.

2021-03-08 16:11 UTC, SANGCO approved these changes
고생 하셨습니다~

2021-03-08 16:11 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/user")
`"/users"`가 좋겠죠?

위에 댓글 드린 것처럼 `@RequestMapping("/users")` 없애고
`@GetMapping("/users")` 이렇게 가셔도 될거 같네요~

2021-03-09 01:07 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/user")
네 리뷰 너무 감사합니다😊😊

2021-03-09 03:23 UTC, merged