[Woody] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #30
Opened 2021-03-07 17:04 UTC by jihye-woo

안녕하세요! 우디입니다!
이번에 PR이 많이 늦어버렸습니다..😱 죄송합니당💦 
얼른 속도를 내야겠어요..😅

이번 코드 리뷰도 잘 부탁드립니다!🙏

### 😅 신경쓰이는 부분이긴 하지만 아직 구현하지 못했습니다..!

#### 1. 네비게이션 active 카테고리
- active 카테고리의 수정이 필요해 보이지만 아직 구현하지 않았습니다.

#### 2. 질문 상세 페이지 수정 / 삭제 기능 X
- 수정 / 삭제 기능은 구현하지 않았습니다(요구사항 X)

#### 3. 로그인 기능 X
- 마찬가지로 로그인 기능은 구현하지는 않았고(요구사항 X),  login.html 페이지로 이동할 수 있도록 네비게이션의 url만 수정해 놓았습니다

#### 4. 개인정보 수정 기능
 1. 비밀번호가 수정되면 확인할 수가 없습니다
    - 안내 창을 띄우고 싶지만 아직까지 구현하지는 못했습니다.
 2. 개인 정보 수정을 위해서는 새로운 비밀번호를 반드시 입력해야합니다.
    - 이름만 수정하고 싶어도 비밀번호도 강제로 바꿔야하는 불상사가..💦 마음에 드는 구조는 아니지만..ㅠㅠ 일단 제출했습니다
 3. updateProfile()의 매개변수
  - 요구사항에서는 @PostMapping("/users/{userId}/update") 을 사용하라고 하셨지만, 현재 제 회원정보 수정 로직에서는 업데이트해야할 정보를 user 인스턴스로 가져오기 때문에 userId가 필요하지는 않습니다. ("/users/update" 도 가능할 것 같습니다)
  - 일단 요구사항의 url을 지키는 것이 좋을 것 같아서 그대로 두었습니다! 혹시나 로직을 변경하거나, {userId} 부분이 사용되지 않으므로 없애는 것이 좋을 것 같다면 말씀해주세요!
  
### 🙋‍♀️ 질문!
#### 1. MvcConfig에서 직접 뷰 컨트롤러를 추가하는 url Path 혹은 뷰 기준? 장점?
- MvcConfig에서 뷰컨트롤러를 직접 추가하는 기능도 요구사항에 있어서 아래와 같이 구현했는데요! 
```java
@Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.setOrder(Ordered.HIGHEST_PRECEDENCE);

        registry.addViewController("/users/form").setViewName("user/form");
        registry.addViewController("/users/login").setViewName("user/login");
        registry.addViewController("/questions/form").setViewName("qna/form");
    }
```
- 컨트롤러에 종속적이지 않고 단순히 뷰만 리턴하는 경우라면 컨트롤러보다는 MvcConfig에서 직접 뷰를 추가하는 것이 좋은 건가요? 만약 추가해야할 뷰 컨트롤러의 갯수가 많아지면 단순히 뷰만 매핑해주는 컨트롤러를 따로 구현하는게 더 좋은가요? 궁금합니다!

#### 2. 컨트롤러 공통 url 묶어주기
- 원래는 UserController의 "users" 와 QuestionController의 "questions"가 공통적인 url이라서 `@Controller`아래 `@RequestMapping("/users")` 와 같이 공통 url을 분리시키려고 하였습니다!
- 그런데 메인 페이지(`@GetMapping("/")`) 와 매핑되는 메소드가 questions 리스트에 종속적이라서 (맨 첫 화면에 질문 목록을 띄우기 위해서) `@RequestMapping("/questions")`로 분리하지 못했습니다. 혹시 좋은 방법을 알고 계시다면 🦻귀띔 부탁드립니다!!
- ```java
  @GetMapping("/")
      public String getHome(Model model){
          model.addAttribute("questions", questions);
          return "index";
      }
  ```
  
  읽어주셔서 감사합니다!😆

2021-03-08 00:35 UTC, wheejuni requested changes
첫 스프링 과제 수행하시느라 고생하셨습니다. 😃 
질문에 대한 답변은 인라인 코멘트로 남겼습니다. 
답변 외에도 수정해볼만한 부분 의견을 남겼습니다. 
기본적인 코딩 컨벤션은 과제를 수행하며 항상 지켜주세요. 감사합니다~

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/config/MvcConfig.java
> +    public void addViewControllers(ViewControllerRegistry registry) {
스프링 MVC를 이루는 많은 컴포넌트들 중에 "뷰 리졸버" 가 있습니다. 

뷰 리졸버는 개발자가 스트링이나 모델앤 부 형태로 리턴한 뷰 값을 적절한 뷰 템플릿에 묶어 html을 형성하거나, 스태틱 리소스를 사용자에게 찾아 보내주는 역할을 하는데요. 

"스태틱 리소스" 를 사용자에게 리턴하려면 어떤 뷰 리졸버가 구성돼야 하는지, 그리고 스프링 부트 스타터 MVC에서 이 리졸버가 자동으로 구성되지는 않을지 학습해 보시기 바랍니다.

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    List<Question> questions = new ArrayList<>();
뭔가 빠진 것 같네요.

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/")
질문하신 부분이 이 부분인 것 같은데 지금 상황에선 딱히 솔루션이 보이지 않는군요. 

`Service` 객체가 구성된다면 컨트롤러 분리를 통해 대응할 수 있어 보입니다.

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +            throw new IndexOutOfBoundsException(stringIdx + " is out of range!");
기왕에 명시적으로 예외를 던지기로 했다면, 우디가 직접 설계한 예외 객체를 활용해보는 것도 좋을 뻔했네요. 

[이 링크](https://woowacourse.github.io/javable/post/2020-08-17-custom-exception/) 에서 다른 개발자들의 고민을 읽어보시는 것도 추천합니다.

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +@Controller
여기엔 `@RequestMapping` 이 들어갔어도 됐을 것 같은데요?

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +            if (user.getPassword().equals(oldPassword)) {
`User` 에 아래와 같은 메소드를 구현해서 게터 없이 로직 수행할 수 있도록 설계 부탁드려요. 

```java
public boolean isMatchingPassword(String password)
```

2021-03-08 00:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/validation/CastValidation.java
> +        if(stringInt.matches("\\d+")){
굳이 정규식 매칭 없이도 적절한 예외 캐치를 통해 대응할 수 있었을 것 같은데요. 

정규식은 꼭 필요한 순간에 필요한 만큼만 사용할 수 있었으면 좋겠습니다.

2021-03-08 15:12 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    List<Question> questions = new ArrayList<>();
😱 private 붙여주었습니다..!ㅠㅠ

2021-03-08 15:20 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/")
아직 Spring이 익숙하지 않아서, 코멘트 주신 부분을 보고 어떻게 구현해야할지 아직 머릿속에 그려지진 않지만..! 미션을 계속 진행하면서 이해해보도록 하겠습니다! 감사합니다🙇‍♀️🙇‍♀️

2021-03-08 15:28 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +            throw new IndexOutOfBoundsException(stringIdx + " is out of range!");
좋은 링크 공유 감사드립니다!👍 주신 링크를 보니 커스텀 예외 객체의 장단점이 있더라구요!
하지만 커스텀 예외 객체를 사용해보는게 처음이기도 하고,  구체적인 예외 정보를 담고싶어서
아래 두 가지 커스텀 예외 클래스를 만들어보았습니다!
 -  `QuestionListindexOfBoundException` 
    - 질문 리스트의 index 범위를 넘어서게 될 때 
    - (생각해보니 이름이 너무 긴 것 같네요😅 가독성이 떨어질 수도 있겠습니다🤦‍♀️)
 - `UserNotFoundException`
    - 사용자 리스트에 존재하지 않는 userId로 유저 객체를 찾으려고 할 때

2021-03-08 15:35 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +@Controller
원래 `@RequestMapping("/users")`을 달아줬었는데 QuestionController랑 통일하는게 헷갈리지 않겠다 싶어서 둘 다 안달아주었습니다..! 다시 생각해보니 컨트롤러가 두 개 뿐인데, 굳이 그렇게까지 생각할 필요는 없을 것 같네요..!😅 

- `@RequestMapping("/users")` 추가해주었습니다!

2021-03-08 15:39 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
> +            if (user.getPassword().equals(oldPassword)) {
확실히..! user 객체의 내부 정보는 최대한 밖에서 사용하지 않는게 좋겠네요! 좋은 코멘트 감사합니다🙇‍♀️🙇‍♀️

2021-03-08 15:42 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/validation/CastValidation.java
> +        if(stringInt.matches("\\d+")){
넵! 정규식은 제거하고 try-catch로 예외를 처리하도록 수정하였습니다
 -  아래와 같이 `@NumberFormatException` 예외 발생 시 `@IllegalArgumentException`을 던지도록 했습니다
   ```java
   public static Integer stringToInt(String stringInt){
        try{
            return Integer.parseInt(stringInt);
        } catch (NumberFormatException formatException){
            throw new IllegalArgumentException(stringInt + " is not a numeric value!");
        }
    }
   ```

2021-03-08 18:21 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/config/MvcConfig.java
> +    public void addViewControllers(ViewControllerRegistry registry) {
자세한 설명 감사드립니다! 찾아보니 뷰 리졸버의 종류가 다양하군요!
맞는지는 모르겠지만..!😅 얕게나마 공부해본 바로는
- 스프링 MVC에서는 view resolver를 따로 설정하지 않는다면 디폴트인 `InternalResourceViewResolver`가 자동으로 사용되는 것 같네요!
-  `InternalResourceViewResolver`에서 기본으로 jsp를 지원하지만, 이번 미션에서는 handlebars 템플릿 엔진을 사용하고 있기때문에 여기서 제공하는 `HandlebbarsProperties`에 의해 prefix는 'templates'로  suffix는 ('.hbs' 지만 따로 application.properties에서 설정해줘서) `.html`로 설정이 되는 것 같네요! 
- 그리고 컨트롤러에서 request url을 가지고 view solver에 있는 설정 값대로 구체적인 html 뷰를 리턴하는 것으로 이해했습니다👀
 - `prefix + {컨트롤러에서 리턴된 request url} + suffix` 이런 식으로요!

2021-03-08 18:31 UTC, jihye-woo commented
코멘트 주신 부분은 최대한 반영해서 수정해보았습니다!

그리고 코멘트를 따로 주시진 않았지만 `@ExceptionHandler`에 대해서 알게되어서 적용해보았습니다..!
- 전체 예외에 대해서 핸들해주지는 않고
- 일단 한 가지 예외 상황(invalid한 question id를 받았을 때)에 한해서만 적용해보았습니다!

혹시나 또 수정해야할 점이 있다면 말씀해주세요!! 감사합니다🙇‍♀️

2021-03-11 07:24 UTC, wheejuni approved these changes
수고하셨습니다~ 간단한 코멘트 두 개 남겼는데 한번 슥 읽어보시고 다음 미션으로 넘어가주세요! 
리뷰가 늦어 죄송합니다 ㅠ
그리고 리뷰가 늦어질 땐 먼저 다음 미션을 진행하셔도 괜찮습니다.

2021-03-11 07:24 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/exception/QuestionListIndexOutOfBoundException.java
> +    public QuestionListIndexOutOfBoundException(int index, int lowerBound, int upperbound){
보통 예외 클래스의 생성자로는 `String`, `Throwable` 정도로 정리하는게 좋을 것 같아요.
지금 방향을 충분히 이해하겠지만, 너무 과한 것으로 보입니다!

2021-03-11 07:24 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/exception/UserNotFoundException.java
> +        super("There is no user id, " + userId);
예외의 풀 메세지를 생성자로 전달받는 것을 추구해 주세요.

2021-03-11 07:24 UTC, merged

2021-03-11 07:43 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/exception/QuestionListIndexOutOfBoundException.java
> +    public QuestionListIndexOutOfBoundException(int index, int lowerBound, int upperbound){
앗 그렇군요!👀 수정하는게 좋겠네요!! 짚어주셔서 감사합니다😀😀

2021-03-11 07:51 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/exception/UserNotFoundException.java
> +        super("There is no user id, " + userId);
넵! 생각해보니 말씀하신대로 해야 좀 더 유연한 구조로 만들 수 있겠네요..!
아직 이런 부분에 대해 감이 많이 없어서ㅠ 이렇게 짚어주실 때 마다 많이 배워갑니다! 감사합니다 🙇‍♀️🙇‍♀️