[ Bat ] 미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #33
Opened 2021-03-08 07:27 UTC by kjk402

안녕하세요, 웹백엔드과정 Bat입니다.

하기와 같이 미션2 구현하여 pull request 드립니다.

• mission2 summary
=====================================
• 미션2 구현 URL : https://bat-spring-qna.herokuapp.com/

• DB연결 - H2 DB연결을 위해 build.gradle, application.properties 설정하였습니다.
                  최신 H2보다는 지난 버전이 안정적이라는 평이 있어 1.4.199로 버전 지정해주었습니다.

• DB 저장, 조회를 위해 Repository 생성하였습니다.

• 회원 정보 수정 기능 : Put 메소드 적용은 hiddenHttpMethodFilter 설정 해주어 GET, POST 가 아닌 
                                     다른 메소드도 에러발생 없이 실행 가능합니다.

• Null 체크 : get() 으로만 정보를 받아올 시 null 값일 때 NoSuchElementException 발생합니다.
                    orElse() 을 사용하여 null값일 때 값을 지정해주었습니다.

=====================================

• mission2에서 부족한 점 및 궁금점.
DB 연결 후 구현에 집중하여 ModelAndView 사용이 잦습니다. 특히 회원 정보 수정할 시에 비밀번호 확인페이지와 정보 수정 페이지 총 두페이지가 사용됩니다. ModelAndView 역시 두번 사용되는 데 혹시 생략 가능한 부분이 있을 지 궁금합니다.

리뷰 잘 부탁드립니다.
감사합니다.

2021-03-08 09:38 UTC, imjinbro commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.199'
글 작성하신 부분 봤는데 버젼 관련해서 내용을 잘 찾아보셨군요 💯 
시간 나신다면 gradle 디펜던시 작성할 때 버젼 부분을 변수로 대체하는 방법도 찾아보셔요

2021-03-08 09:42 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("question", questionRepository.findById(id).orElse(null));
questionRepository 코드 라인을 분리해보는게 어떨까요?
라인이 줄어들면 좋긴하지만 명확하게 어떤 값이 리턴되어서 Model에 세팅되는지 한 눈에 들어오는 코드도 좋습니다

2021-03-08 09:43 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
Question이 Null인 케이스는 언제든지 발생할 수 있어요
예외처리 코드 작성하시는 연습해보시길 추천드립니다

2021-03-08 09:46 UTC, imjinbro commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setId(Long id) {
id는 한번 세팅되면 바뀌면 안되는 부분입니다
의미 없거나 허용 되어선 안되는 setter 메소드 만들지 않는 연습을 해보세요
id 뿐만 아니라 다른 setter 메소드도 한번씩 보시면서 수정해보셔요

2021-03-08 09:48 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        System.out.println("user Info: " + user);
로그 찍으시려는 노력 좋네요
다른 로그 찍는 방법도 있는데 차차 알아가시면 좋겠습니다

2021-03-08 09:50 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        ModelAndView modelAndView = new ModelAndView("/user/confirmUserInfo");
View 명은 하나의 파일에서 관리해주면 좋지 않을까요?
예를 들면 enum이나 아니면 클래스 파일 만들어서 문자열 상수로 정의해두고 한 곳에서 관리 하는 것을 추천드립니다.

2021-03-08 09:51 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User user = userRepository.findById(id).orElse(null);
User setter 메소드 관련해서 코드에 코멘트를 달아두었습니다
참고해서 여기 코드 수정해봐주세요 

**힌트**
user.update 하나로 만들어주고 예외처리/정보변경 등을 해주는게 좋겠습니다

2021-03-08 09:52 UTC, imjinbro requested changes
안녕하세요 리뷰어 콜린입니다
수정 필요해보이는 코드에 코멘트 달아두었습니다
코드 절대양을 줄이는 것도 좋지만 읽기 쉬운 코드 만드는 것에도 조금 더 치중을 해주시면 좋겠고
객체지향에 대해서 공부하시는 것도 추천드려요(setter 메소드 관련)

2021-03-08 14:20 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        ModelAndView modelAndView = new ModelAndView("/user/confirmUserInfo");
ac1245f 에서 UserCotroller에서 중복되어 사용되는 ViewName 
"/confirm/{id}" 와 "/update/{id}" 상수 선언 하였습니다.

2021-03-08 14:22 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("question", questionRepository.findById(id).orElse(null));
ac1245f 에서 분리하였습니다. 혹시 의도하신 것과 다른 부분이 있을까요?

2021-03-08 15:27 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User user = userRepository.findById(id).orElse(null);
8bfa873 에서 메소드 한개로 정보 수정 하도록하였습니다.

2021-03-08 16:26 UTC, kjk402 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.199'
변수로 두는 방법도 있는 지 몰랐습니다.
gradle 작성법 관련하여 공부하겠습니다.

감사합니다.~~

2021-03-09 03:36 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
2177cec 에서 null 체크 생성하였습니다.
근데 여전히 null 값일 때 질문이 생성됩니다. 
id 부분이 자동으로 생겨서 그런 것 같습니다.;;

해결책 가르쳐주시면 감사하겠습니다.

2021-03-09 03:36 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setId(Long id) {
setId 제거하였습니다.

2021-03-09 03:37 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        System.out.println("user Info: " + user);
네 다음 스텝에서 Logger 사용해보겠습니다.

감사합니다.

2021-03-09 07:45 UTC, MJbae commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.199'
아하 1.4.199버전이 안정적이군요!

2021-03-09 07:51 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setId(Long id) {
오호! 어노테이션으로 id를 생성할 수도 있군요!

2021-03-09 08:49 UTC, kjk402 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:1.4.199'
제 생각에는 굳이 1.4.199버전이 아니더라도 최신버전보다는 이전 버전 쓰는 것이 안정적일 것 같습니다. ㅎㅎ

2021-03-11 01:53 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
흠 디비에 저장된 데이터가 여전히 생긴다는거죠?
컨트롤러 메소드의 인자가 Question이 아니라 dto로 받아서 필수값이 정상적으로 들어왔는지 체크하는 로직을 넣어보는건 어떨까요?
public String create(QuestionDto questionDto) {
    // 필수값 체크 (questionDto Null 여부도 체크)
    // 생성
    // 응답
}

2021-03-11 01:53 UTC, imjinbro commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User user = userRepository.findById(id).orElse(null);
메소드는 한개로 되었는데, 아직 예외처리가 없어보입니다
데이터를 변경하는 코드의 경우 언제나 예외 처리가 필요합니다!

2021-03-11 01:54 UTC, imjinbro approved these changes
예외처리에 대해서 조금 더 신경써주시면서 코딩 해주면 좋을 것 같아요!
데이터 변경되는 코드에서는 특히요!
고생하셨어요
답변 달아둔거는 잘 읽어보셨으면 해요!

2021-03-11 01:56 UTC, kjk402 commented
예외처리 관하여 더욱 중점적으로 신경쓰며 코딩하겠습니다.
리뷰 정말 감사드립니다.~~

2021-03-12 00:33 UTC, merged