[MJ] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #34
Opened 2021-03-08 07:28 UTC by MJbae

안녕하세요~ MJ입니다.

이번 리뷰도 잘 부탁드립니다!

### [배포] (https://spring-qna.herokuapp.com/)

## 가. 고민한 부분

### 1. First Logic Last Code

- 지난 체스게임 미션을 하면서 프로그램의 전체적인 로직을 고려하지 않고 코드를 먼저 작성했습니다.
- 리뷰어의 코멘트의 다수가 프로그램의 부족한 논리에 대한 지적이었습니다.
- QnA 게시판 미션부터는 프로그램의 전체적인 로직을 먼저 고민해보고 코드를 작성하는 식으로 진행하고 있습니다.
- 각 기능의 로직은 Given(입력), When(처리), Then(결과)의 틀에 따라 작성하였습니다.

### 2. 컨트롤러, 서비스, 도메인, 리포지토리 구조 활용

- 컨트롤러, 서비스, 도메인, 리포지토리 구조 구조를 프로그램에 반영했습니다.

    → 단, 서비스 부분은 아직 필요성을 느끼지 못하여 컨트롤러에 서비스에 해당하는 로직을 포함시켰습니다.

- 웹 어플리케이션 구조의 주요 부분에 대한 정의(by myself)

    → 컨트롤러: **책임 전달자**, 클라이언트로부터 요청을 받고, 해당 요청에 대한 처리 책임을 전달함

    → 서비스: **책임자**, 컨트롤러로부터 받은 처리 책임을 이관 받아서 핵심 로직을 처리함

    → 도메인: **데이터 처리 기본 단위**, DB에 저장되고 관리되는 객체

    → 리포지토리: **DB 관리자**, DB에 직접 접근하여 관련 연산을 처리

## 나. 회원 관련 기능 구현

### 1) 회원가입

- Given(조건)

    → 클라이언트에서 POST 방식으로  '/users' 요청

- When(처리)

    → UserController에서 해당 요청을 받아옴

    → UserController::createUser에서 해당 요청 처리함

    가) 매개변수로 받아온 User Domain 객체의 속성 중 userId 값의 중복여부 확인

    나) User Domain 객체의 속성을 Repository에 저장

    다)  /users 경로로 리다이렉트

- Then(결과)

    → userId가 중복되지 않았다면 User의 모든 속성이 로그로 보여진다

    → /users 경로로 정상 리다이렉트

### 2) 회원목록 조회

- Given(조건)

    → 클라이언트에서 GET 방식으로  '/users' 요청

- When(처리)

    → UserController에서 해당 요청을 받아옴

    → UserController::createUserList에서 해당 요청 처리함

    가) UserRepository::getAll 이용하여 List<User> users 생성

    나) Model 이용하여 users를 템플릿 엔진으로 전달 

    다)  "users/list" 반환

    → viewResolver는 UserController::createUserList의 반환값을 기준으로 html 파일을 찾아서 템플릿 엔진에게 전달

    → 템플릿 엔진은 html 파일을 변환하여 웹 브라우저에게 응답으로 전달함

- Then(결과)

    → 모든 User에 대한 속성이 로그로 보여진다

    → users/list.html 파일이 동적으로 변환된 결과가 웹 브라우저에 렌더링

### 3) 회원프로필 정보보기

- Given(조건)

    → 클라이언트에서 GET 방식으로  /users/{userId} 요청

- When(처리)

    → UserController에서 해당 요청을 받아옴

    → UserController::createProfile에서 해당 요청 처리함

    가) http 요청에 포함된 userId를 targetId라는 매개변수로 받아옴

    나) UserRepository::getOne에서 targetId를 userId로 가지고 있는 User Domain 객체를 반환함

    다) 해당 User Domain 객체를 Model을 이용하여 템플릿 엔진으로 전달

    라) users/profile 반환

    → viewResolver는 users/profile.html 파일을 찾아서 템플릿 엔진에게 전달

    → 템플릿 엔진은 해당 파일을 변형하여 웹브라우저에게 응답으로 전달

- Then(결과)

    → targetId에 해당하는 User Domain 객체가 정상적으로 받아왔다면 로그에 기록됨

    → users/profile.html 파일이 동적으로 변환된 결과가 웹 브라우저에 렌더링됨

## 다. 질문 관련 기능 구현

### 1) 질문하기

- Given

    → 클라이언트 요청, POST 방식 /questions

- When

    → Question Domain 객체 생성

    → Question Controller::createQuestion으로 처리책임 이관

    → QuestionRepository 생성

    → POST body의 question 속성을 받아서 Question Domain 객체에 할당

    → QuestionRepository에 Question Domain 객체 추가

    → QuestionController 내부 로직 종료 후 홈으로 리다이렉트

- Then

    → POST body의 question 속성 값을 잘 받아왔는 지 확인

    → 리다이렉션에 따라 정상 렌더링 여부 확인

### 2) 질문목록 조회

- Given

    → 클라이언트 요청, GET 방식 /

- When

    → 위의 요청을 QuestionController::createQuestionList에서 처리하도록 맵핑

    → repository에서 리스트를 받아와서 모델로 감싸서 템플릿 엔진에 전달

    → html 파일의 반복부분에 대해 템블릿 엔진 문법 적용

    → /index 반환

- Then

    → 로그에 모든 Qeustion에 대한 속성이 기록됨

    → 출력한 목록이 정상적으로 렌더링됨 

### 3) 질문 상세보기

- Given

    → 각 질문을 클릭하면 각 질문에 해당하는 상세페이지에 대한 요청 발생

    → GET 방식, /questions/{questionId}

- When

    → Question 객체에 questionId 속성 추가

    → QuestionRepository::save에 하나의 객체가 추가되기 전에, 해당 객체의 questionI 값 할당(할당값은 Object.size() + 1)

    → QuestionRepository::getOne(int targetId) 생성

    → QuestionController::createQuestionInDetail에서 각 상세페이지 보기 요청에 대한 처리 책임

    → HTTP 요청에 들어있는 매개변수를 메소드 매개변수로 가져옴

    → 메소드 매개변수의 값을 기준으로 questionRepository에서 해당하는 Question 객체 반환

    → Question 객체를 모델로 싸서 템플릿 엔진으로 전달

    → /questions/show 반환

- Then

    → 정상 렌더링 확인

    → 로그 확인 

## 라. 회원정보 수정 기능 구현

### 1) 회원정보 수정 페이지로 이동

- Given

     → 수정버튼 클릭하면 GET방식(users/{userId}/form) 요청 발생

- When

    → UserController::createUpdateForm 생성 및 해당 요청에 대한 처리 책임 전달

    → URI 경로의 userId를 메소드 매개변수로 받아옴

    → 매개변수 userId를 모델로 감싸서 update.html로 전달

    → update.html에 id값을 model로 전달한 값으로 고정

    → 메소드 반환값으로 users/update

    → HTML 파일 작성(update.html)

- Then

    → 회원정보 수정 페이지로 이동(users/update)

### 2) 회원 정보 수정 기능 구현

- Given

     → 회원 정보 수정 버튼 클릭하면 POST 방식(users/{userId}/update) 요청 발생

- When

    → UserController::updateUser 생성하여 POST 요청 body에 포함된 User Domain 객체의 속성을 전달 받는다

    → UserController::updateUser에서 비밀번호 일치여부 확인(isValidPassword)

    → 비밀번호가 일치하지 않으면 회원 정보를 변경하지 않은 채로 "redirect:/users"

    → 아이디 수정불가 등의 요구사항을 반영한다

    → 회원 정보를 변경한다(setter 활용)

    → users/ 값을 반환"redirect:/users"

- Then

    → 회원목록 페이지에 수정내용 반영된 회원정보 확인

2021-03-08 09:08 UTC, honux77 requested changes
수고하셨어요. 
몇가지 간단한 코멘트가 있으니, 보고 개선해 주세요.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionList(Question question, Model model) {
```suggestion
    public String createQuestionList(Model model) {
```
Question은 필요없는 것 같죠?

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionList(Question question, Model model) {
`createQuestionList` 메소드 이름이 어울리지 않는 것 같아요.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionList(Question question, Model model) {
미션에는 없지만 이부분 참 모호한게 메인 페이지인데 Question 클래스에서 관리하는 바람에 다른 메소드들의 /questions URL을 별도 분리를 못하게 되거든요. 이것만 따로 뺄 수 있는 방안이 있으면 좋은데 저도 잘 모르겠네요 ㅋㅋ

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionInDetail(@PathVariable(name = "questionId") int targetId, Model model) {
create 라는 동사가 의미없이 사용되고 있네요. 실제로 질문을 생성하는 경우 말고는 다 제거해 주세요.,

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        newQuestion.setContents(question.getContents());
이 부분 코드가 좋지 않아요. 
1. 왜 새로운 Question 객체를 만드는지 의아하고
2. 불필요하게 getter()와 setter()를 사용합니다. 

새로운 객체를 만들지 않아도 좋다면 안 만들거나, 새로운 객체를 만들어야 한다면  Question.create(question) 같은 메소드 방식으로 새 객체를 만드는게 좋겠네요.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User newUser = new User(referenceUser.getUserId());
여기도 새 유저를 생성했네요. 꼭 해야 하는지 확인하고 알려주세요.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User newUser = new User(referenceUser.getUserId());
user에 값이 정상적으로 들어오고 있는지 특정 필드에 null이 없는지 확인도 필요합니다.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String createUserList(Model model) {
여기도 create 제거

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User targetUser = userRepository.getOne(targetId);
사용자가 없다면?

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/users/{userId}/update")
```suggestion
    @PutMapping("/users/{userId}")
```

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private boolean isValidPassword(String real, String expected) {
1) 이름과 동작이 맞지 않아요. 이름만으로는 글자가 8자 이상, 대소문자 이런걸 볼것 같아요.
2) password를 체크하는 것은 User 클래스의 메소드여야 할 것 같은 느낌입니다.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        presentUser.setEmail(referenceUser.getEmail());
가능하면 getter와 setter는 사용하지 않는 것이 좋습니다.

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +    private final List<Question> questionList = new ArrayList<>();
```suggestion
    private final List<Question> questions = new ArrayList<>();
```

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    private final List<User> userStorage = new ArrayList<>();
```suggestion
    private final List<User> users = new ArrayList<>();
```

2021-03-08 09:08 UTC, honux77 commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    }
삭제 여부를 알수가 없네요?

2021-03-08 09:08 UTC, honux77 commented on src/main/resources/templates/users/update.html
> +<!DOCTYPE html><html lang="kr"><head>    <meta http-equiv="content-type" content="text/html; charset=UTF-8">    <meta charset="utf-8">    <title>SLiPP Java Web Programming</title>    <meta name
헉 이거는 왜 이렇죠??

2021-03-08 22:34 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionList(Question question, Model model) {
@honux77 HomeController를 생성해서 관련 로직을 옮기는게 깔끔할 것 같습니다!

2021-03-08 22:36 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String createQuestionInDetail(@PathVariable(name = "questionId") int targetId, Model model) {
@honux77 메소드의 기능과 이름이 매칭이 안되네요. 수정해보겠습니다!

2021-03-08 22:44 UTC, MJbae commented on src/main/resources/templates/users/update.html
> +<!DOCTYPE html><html lang="kr"><head>    <meta http-equiv="content-type" content="text/html; charset=UTF-8">    <meta charset="utf-8">    <title>SLiPP Java Web Programming</title>    <meta name
띠옹... 개행문자가 이상하게 들어갔네요.

2021-03-09 02:40 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        newQuestion.setContents(question.getContents());
@honux77 POST 요청의 바디로부터 얻은 매개변수만으로 해당 기능을 구현하면 되네요! 불필요하게 새로운 도메인 객체를 생성하고 getter, setter를 사용한 부분을 제거했습니다.

2021-03-09 03:27 UTC, MJbae commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    }
@honux77 반환값을 boolean으로 변경했습니다.

2021-03-09 03:28 UTC, MJbae commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    private final List<User> userStorage = new ArrayList<>();
@honux77 반영했습니다. userStorage... 너무 비인간적인 네이밍이네요

2021-03-09 03:29 UTC, MJbae commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +    private final List<Question> questionList = new ArrayList<>();
@honux77 복수명사가 일반적으로 사용되므로 가독성면에서 더 낫겠네요

2021-03-09 04:54 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User newUser = new User(referenceUser.getUserId());
@honux77 도메인 객체의 null 여부 확인하는 부분과 POST body로 전달받은 여러 속성의 빈값이나 null 여부 확인하는 부분을 추가했습니다.

2021-03-09 04:57 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/users/{userId}/update")
이 부분은 컨벤션에 있던 내용이네요.. 자료를 조금 더 꼼꼼하게 읽어봐야겠습니다!

2021-03-09 05:11 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User targetUser = userRepository.getOne(targetId);
빈값이나 null 체크하는 부분을 추가했습니다

2021-03-09 05:24 UTC, MJbae commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private boolean isValidPassword(String real, String expected) {
1. 비밀번호의 일치 여부를 확인하는 메소드이므로 isEqualPassword로 수정했습니다.
2. 이 부분은 추후에 컨트롤러에서 서비스 부분을 분리할 때 함께 작업하면 좋을 것 같습니다

2021-03-09 05:27 UTC, MJbae commented
@honux77 코멘트 주신 부분을 최대한 반영하여 수정했습니다. 특히 메소드, 변수의 이름짓는 부분과 불필요하게 추가된 코드를 정리하면서 코드의 가독성이 많이 좋아진 것 같습니다. 추가적으로 수정할 부분이 있다면, 알려주세요~

2021-03-12 00:32 UTC, honux77 commented
수정 후에는 다시 리뷰를 요청할 수 있어요. 그렇게 하거나 리뷰어에게 DM을 하는게 좋을 것 같네요. 늦어서 죄송합니다.

2021-03-12 00:32 UTC, merged