[이노] 미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #37
Opened 2021-03-08 11:11 UTC by eNoLJ

이번 미션에서는 따로 추가된 기능은 없습니다.
repository를 만들어 db와 연결하는 것에 중점을 두고 진행했습니다.

미션의 안내와 다른점이 있다면 controller에서 직접적으로 repository를 조작하지 않고 service에서 repository를 조작하는 메소드를 만들어 controller에 제공하도록 작성했습니다.

항상 느끼는거지만 코드가 무언가 부족한 느낌이 듭니다. 중요한건 그게 뭔지 모르겠다는거죠!!!!!
그래서 리뷰어분이나 혹시라도 제 코드를 보시는 동기분들은 사소한거라도 좋으니 언제든 아무거나 지적해주시면 감사하겠습니다.

이번 리뷰도 잘부탁드립니다. 감사합니다!!

배포 링크 : https://enolj-spring-qna.herokuapp.com

2021-03-08 12:22 UTC, wheejuni requested changes
2단계 진행하시느라 수고 많으셨습니다. 👍 💯 
전반적으로 깔끔히 구현하셔서 드릴 피드백이 많지 않았는데, 간단한 개선 의견 두 가지 드렸습니다.
충분히 읽어보시고 이해 되지 않으신다면 추가 질문을 던져주세요.

2021-03-08 12:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/User.java
> +    @Column(nullable = false)
이 필드가 좀 애매한 부분인데 이 클래스 이름이 `User` 인데다가 이 필드는 `userId` 라서 코드 작성중에 바로 위에 있는 `id` 랑 혼동이 될 우려도 있거든요.
그래서 이런 경우에 다른 네이밍을 고민하기도 합니다. 애매하고 어려운 부분이죠...

2021-03-08 12:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                targetUser.setEmail(user.getEmail());
이 로직은 `User` 가 직접 수행하도록 필요한 메소드를 설계한 후 수정해주세요.

2021-03-09 02:25 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                targetUser.setEmail(user.getEmail());
해당 부분 수정했습니다. 하면서 알게 된게 optional 객체에 get을 사용하는건 안티패턴이라는 걸 알게되어서 그부분도 안쓰도록 수정했어요!!

2021-03-09 02:26 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/User.java
> +    @Column(nullable = false)
음.... 이부분 고민을 해봤는데 마땅히 생각나는 이름이 없습니다ㅠㅠ 그냥 id를 풀어쓰자니 그건 또 거추장스러운 것 같고... 혹시 염두에 두고 계신 해답이 있으면 부탁드려요!!!!

2021-03-09 03:49 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/User.java
> +    @Column(nullable = false)
@eNoLJ 네이밍은 어려워서 저도 잘 떠오르지 않네요 ㅋㅋㅋ 보통 `username` 이라는 대체재가 있긴 합니다만....

2021-03-09 03:49 UTC, wheejuni approved these changes
👍

2021-03-09 03:50 UTC, merged

2021-03-09 03:51 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/User.java
> +    @Column(nullable = false)
그렇군요... 이름 짓는게 제일 어려운 것 같아요!!
이번 미션 리뷰도 감사했습니다!!