[마르코] 미션1: 회원 가입, 사용자 목록, 질문하기 구현 PR
codesquad-members-2021/spring-boot-qna pull request #38
Opened 2021-03-08 12:10 UTC by 95degree

안녕하세요 백엔드 마르코 입니다. 
미션1 PR 요청 드립니다. 스프링은 처음이라 미션을 천천히 따라가면서 구현했습니다.
리뷰로 뚜들겨 맞을 준비가 됐습니다. 🚑🚑🚑 🏥🏥🏥

### 구현 내용
- 회원가입 기능 
- 회원목록 기능 
- 회원 프로필 정보
- html 중복제거
- MvcConfig 생성
- 질문하기,질문목록 기능
- 회원 정보 수정

2021-03-08 14:48 UTC, sonypark requested changes
안녕하세요 마르코, 리뷰어 소니 입니다.😊
스프링이 처음이라 많이 생소하셨을 텐데 미션1 잘 구현해주신 것 같네요! 👍
그런데 heroku에 배포하신 링크가 없어 동작을 확인하지는 못했어요 😢
작성하신 코드 기준으로 몇가지 코멘트 남겼으니 확인부탁드려요!

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +
미션2에서 하실 부분이지만 미리 말씀드리면, questions 데이터를 관리하는 역할은 컨트롤러가 아닌 repository 클래스에서 해주도록 개선해보세요.

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            if (questions.indexOf(question) == index - 1) {
for문을 돌지 않고 List의 인덱스로 바로 접근할 수도 있지 않을까요?
`questions.get(index - 1)`

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
👍

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "redirect:/users";
로그를 찍을 때는 logger를 사용해주세요~

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.getUserId().equals(userId)) {
User 클래스에서는 필드로 userId를 갖고 있기 때문에 외부에서 getUserId로 호출해서 비교하지 않고, User 클래스 내부에서 비교하면 어떨까요?
```java
    public boolean isMatchingUserId(String userId){..}
```

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.getId() == id) {
여기도 마찬가지 :)

2021-03-08 14:48 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        targetUser.setUser(updateUser);
`users.get(id - 1)`에서 id가 index 범위를 벗어나는 경우 어떻게 되나요?

2021-03-09 03:04 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +
넵 다음 미션에 꼭 반영하도록 하겠습니다.!!

2021-03-09 03:05 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            if (questions.indexOf(question) == index - 1) {
아 그렇네요 questions.get(index - 1)으로 가져오면 쓸때없이 for문을  돌릴 필요가 없어 효율성이 더 높아지겠네요:)

2021-03-09 03:11 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "redirect:/users";
println()를 사용하여 콘솔창에 출력을 할 경우는 시스템 성능이 떨어지고 
logger를 사용하면 제가 보고 싶은 정보 이외의 제가 체크 못한 정보들을 볼 수 있다는 장점이 있네요!!
수정완료했습니다.

2021-03-09 03:21 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.getUserId().equals(userId)) {
외부에서 getter사용 해 호출 하면  user객체의 값이 겉으로 드러나고 user객체가 스스로 할수 있는 일은 다른 곳에서 처리해 주고 있어 응집성이 떨어지네요.  왜 getter를 사용하면 안되는지 공부를 조금 해봤습니다.
좋은 리뷰 감사합니다.👍👍🤞

2021-03-09 03:22 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        targetUser.setUser(updateUser);
예외처리를 안 해주고 있었네요.... 수정했습니다.

2021-03-11 09:41 UTC, sonypark approved these changes
마르코 수정사항 확인했습니다.
확인이 늦어 죄송합니다😅

2021-03-12 00:34 UTC, merged