[Cooper] 미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #39
Opened 2021-03-08 14:40 UTC by pbg0205

안녕하세요😄
코드스쿼드2021 백엔드 과정의 Cooper 입니다.
미션2에 관한 요구사항을 완료하여 PR 보냅니다!
주요 변경사항은 하단에 기입하였습니다.
부족한 부분이나 아쉬운 부분에 대해 거침없는 피드백은 환영입니다!
리뷰해주시는데 시간내어주셔서 감사합니다👏

###  🌏  배포 사이트 : [https://cooper-boot-qna.herokuapp.com/](https://cooper-boot-qna.herokuapp.com/)

---

### 1️⃣  List<Entity> -> [Entity]Repository 변경
- 기존 List<Entity>에서 데이터를 관리하던 방식을 h2 db를 이용해 데이터를 관리하는 방식으로 변경하였습니다.
- h2 db의 데이터를 접근 및 열람, 조회를 위해 CrudRespotiory<Entity, Key> interface 구현체인 UserRepository, QuestionRepository를 구현하였습니다.

### 2️⃣  Question, User에 Entity annotation 추가
- db에 링크할 수 있는 객체는 Entity로 선언하여 관리함을 나타내기 위해 @Entity annotaion을 선언하였습니다.
- 모든 멤버변수가 column으로 선언되지만, 그 중 특정 조건(ex. Not Null, length)이 필요한 경우 @Column을 선언하여 기능을 추가하였습니다.

### 3️⃣  회원 정보 수정 기능 추가
- 회원 정보를 변경하기 이전에 현재 비밀번호를 확인하는 메서드를 User 클래스에 matchPassword 메서드를 선언하여 비교합니다.
- 현재 비밀번호와 일치하지 않을 경우, 변경사항에 대해 수정이 불가능하며 조회 페이지로 다시 이동합니다.
- 현재 비밀번호가 일치할 경우, 입력한 수정 사항에 대해 변경이 가능하고 변경 사항을 조회 창에서 확인 가능합니다.

2021-03-08 16:16 UTC, ksundong requested changes
안녕하세요! Cooper!! 리뷰어 Dion입니다.
코드를 정말 깔끔하게 잘 구현해주셨네요. 조금만 수정해주시면 바로 다음단계를 진행하셔도 될 것 같습니다.

- Posts를 누르면 `index.nbs`로 이동하는데, 이 부분도 개선해주시면 좋을 것 같아요. Q&A 목록이 나오게끔요!
- https://cooper-boot-qna.herokuapp.com/user/create?userId=asd&password=asdf&name=asdf&email=asdf%40asdf.asdf 이건 에러가 발생하네요. 왜그럴까요? 그리고 비밀번호가 url로 넘어가네요??? users로 가는부분과 user로 가는 부분이 있는 것 같습니다.
- 접근제어자 누락된 부분은 추가해주세요.
- Spring의 Injection 방식에 대해서 학습해보세요.
- Optional을 그대로 `get()`하는 것은 안티패턴입니다. 개선해주세요.

궁금하시거나, 이해가 안가는 부분은 코멘트 남겨주세요~ 고생하셨습니다~

2021-03-08 16:16 UTC, ksundong commented on build.gradle
> +	compile ('com.h2database:h2')
compile은 implementation으로 바꾸는걸 권장합니다~

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +    }
오 어디서 보고 요렇게 만들어주셨는지 궁금하네요~

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
format을 상수로 추출해볼까요?

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/user/User.java
> +import javax.jws.soap.SOAPBinding;
이건 어디서 온걸까요?

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/user/User.java
> +        return this.password.equals(prevPasswrod);
👍

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/user/User.java
> +        this.name = updateUser.name;
👍

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
>      Logger logger = LoggerFactory.getLogger(QuestionController.class);
뭔가 빠지지 않았나요?

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    private QuestionRepository questionRepository;
저는 생성자 injection에 대해서 학습하고 시도해보시길 권장합니다.

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        logger.debug(question.toString());
```suggestion
        logger.debug("question: {}", question);
```
요렇게 쓰시는걸 권장드려요~

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question question = questionRepository.findById(index).get();
`Optional`을 그대로 `get()`하는건 지양해줍시다.
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/
여기를 참고해주세요~

2021-03-08 16:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        userRepository.save(user);
요걸 빼도 정상적으로 동작할 텐데요. JPA에서 변경감지를 자동으로 해주기 때문에 그렇습니다.
그냥 그렇다는 것만 알아두고 넘어갑시다~

2021-03-08 16:16 UTC, ksundong commented on src/main/resources/application.properties
> +# PutMapping 설정
주석 달아놓은거 좋네요~

2021-03-09 02:56 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        logger.debug(question.toString());
말씀해주신대로 수정 완료했습니다!
코멘트 감사합니다😄

2021-03-09 03:01 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/user/User.java
> +import javax.jws.soap.SOAPBinding;
auto import로 설정해놓고 오탈자 발생할 때 생긴 import인거 같습니다ㅠ
자동으로 해놓는 과정에서 제가 신경을 못쓴 부분인거 같네요. 주의하겠습니다!!🔥

2021-03-09 03:06 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    private QuestionRepository questionRepository;
넵! 말씀해주신대로 생성자 주입 형태로 변경 완료하였습니다!
생성자 주입으로 변경하면 
```
1. null을 주입하지 않는 경우, NullPointerException을 발생시키지 않는다.
2.의존관계를 주입하지 않은 경우에 컴파일 시 오류를 잡아낼 수 있다.
```
오... 신기하네요. 코멘트 남겨주셔서 알게되었습니다.
감사합니다👍👍

2021-03-09 03:13 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question question = questionRepository.findById(index).get();
findById로 Optional로 처리해주고 model에 객체를 전달해주는 경우에 get()메서드를 사용하는 방식으로 변경했습니다!
추가적으로 question을 받아오지 못할 경우를 처리하고 싶어 
```java
if(!question.isPresent()) {
   return "redirect:/";
}
```
이런식으로 구현했는데 글에서는 isPresent 사용하는 것이 좋은 방법은 아니라고 하네요ㅠ 아래에 model 객체를 담아주고 log를 확인하고 싶어 위와 같이 처리 했습니다ㅠ 혹시 더 괜찮은 방법있으시면 조언 좀 구할 수 있을까요??

2021-03-09 03:16 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        userRepository.save(user);
아 저는 @Transactional이 있어야만 JPA가 그 부분만 변경 감지를 해주는줄 알았는데 그게 아닌가 아닌가 보네요ㅎㅎ
그와 관련된 내용을 찾아보니까 더티체킹(dirty checking)이라는 내용이 있던데 이 부분을 좀 더 학습해보는게 좋을까요??🔥🔥

2021-03-09 03:17 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
넵! 말씀해주신대로 static final로 변경 완료하였습니다!

2021-03-09 03:27 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +    }
이전 미션에서 view에서 전달받는 매개인자가 많아져서 객체로 받고자 id만 제외한 생성자를 선언했습니다. 그런데 JPA 설정하는 과정에 default constructor를 선언하면 매개인자가 있는 생성자로 값을 전달 받지 못하는 경우가 발생하더라구요; 그래서 우선적으로 K 코드를 보고 따라서 해봤는데 알고보니까 저 부분이 BeanUtil 의 getConstructor, getDeclaredConstructor에서 생성자 입력하는 순서, 접근제어자(public)에 따라 받아오는 부분?이  달라지더라구요ㅠ 우선 이 부분만 간략히 확인해보았습니다ㅠ 어제 잠깐 다른분들한테 여쭤보고 확인한 부분이라 좀 더 학습을 해봐야 할 것 같아요ㅠ

2021-03-09 03:33 UTC, pbg0205 commented
말씀해주신 수정 사항에 대해서 변경해보고 궁금한 사항들에 대해 댓글 남겼습니다 😄
그리고 배포 시 다른 url로 이동하는 오류도 navar의 링크를 변경해 수정 완료하였습니다.
꼼꼼하게 해주셔서 얻어가는 부분이 많네요ㅎㅎ 감사합니다👍👍
바쁘시겠지만 확인 부탁드립니다ㅎㅎ

2021-03-09 12:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        userRepository.save(user);
음 코쿼 과정에서 JPA를 적극적으로 쓰진 않을것이기 때문에 코쿼 수료 후에 공부하셔도 괜찮을 것 같아요.

2021-03-09 12:58 UTC, ksundong approved these changes
수정해주시느라 고생 많으셨습니다!
몇 가지 부분에 대한 코멘트는 남겨드렸지만, 다음단계를 진행해주셔도 될만큼 학습이 되신 것 같습니다.
깔끔하게 작성해주시느라 고생 많으셨습니다!
navbar 말씀하시는거겠죠? 잘 하셨네요. 👍 
![image](https://user-images.githubusercontent.com/38597469/110473854-56333600-8122-11eb-882f-46ed22700084.png)
여기 뭔가 있긴한데 다음 미션에 몰래 수정해주세요!

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +                .format(DateTimeFormatter.ofPattern(DATE_FORMAT));
앗 제가 의미한건 `DateTimeFormatter.ofPattern(~)` 부분이었어요!
죄송합니다 ㅠㅠ

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        logger.debug("question : {} ", question.toString());
```suggestion
        logger.debug("question : {} ", question);
```

이렇게는 안되던가요?

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Optional<Question> question = questionRepository.findById(index);
와 어려운 문제네요. null을 리턴해주고 null 처리를 해서 로직을 구현하는건 어떨까요?
사실 `isPresent()`도 그리 나쁘지는 않다고 생각하거든요.

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Optional<Question> question = questionRepository.findById(index);
아니면 예외를 리턴해서 catch 문에 `redirect`를 시켜주도록 하는 방안도 생각해볼 수 있겠네요.

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
```

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    }
여기도 생성자 인젝션 고려해봐주세요~

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @Autowired
이 부분도 제거해주셔도 괜찮아요~

2021-03-09 12:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private UserRepository userRepository;
```suggestion
    private final UserRepository userRepository;
```

2021-03-09 14:12 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/question/Question.java
> +                .format(DateTimeFormatter.ofPattern(DATE_FORMAT));
아닙니다! 다음 미션에서 수정해보도록 할게요ㅎㅎ 감사합니다!

2021-03-09 14:36 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @Autowired
네! @Autowired 제거 하겠습니다👍

2021-03-09 14:38 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private UserRepository userRepository;
앗... final;; 계속 놓치고 있네요ㅠ 신경쓰도록 하겠습니다!!

2021-03-09 14:38 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    }
네 알겠습니다!

2021-03-09 14:42 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
logger를 static final로 선언하시는 이유가 궁금한데 혹시 이야기 해주실 수 있을까요??

2021-03-09 14:44 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Optional<Question> question = questionRepository.findById(index);
아아 한번 try/catch문은 생각을 못했었는데 한번 시도해보도록 하겠습니다!

2021-03-09 14:46 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        logger.debug("question : {} ", question.toString());
아 commit만 해놓고 push를 하지 않아서 누락되었네요ㅠ
이 부분 미션3 커밋으로 반영해놓도록 하겠습니다!

2021-03-09 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
Logger는 굳이 인스턴스마다 생성될 이유가 없고, 변경되어서는 안되기 때문입니다.
답변이 되셨나요?

2021-03-09 16:16 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
사용자 여러명이 요청을 하게될 때, 각각의 Controller 인스턴스가 생성되어 요청을 처리하게 되는건가요? 구조 위주로만 생각하다보니 Controller가 하나만 존재하는걸로 생각하게 되어 기본적인 질문을 여쭤보게 되었습니다ㅠ

2021-03-09 16:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
`Controller`는 일반적인 스프링 Bean의 특성상 Spring Application에서 Singleton으로 존재합니다.

Singletone이긴 하지만, `static`의 경우 클래스 로드 시점에 로딩되기 때문에 `static`이 아닌 필드와 속도의 차이가 존재합니다.
저도 궁금해서 찾아보았는데요, 아래 링크를 통해서 추가적인 학습을 해보시는걸 권장합니다!

https://stackoverflow.com/questions/6653520/why-do-we-declare-loggers-static-final
https://stackoverflow.com/questions/8262310/any-reason-to-use-private-instead-of-private-final-static-on-the-logback-logger

2021-03-10 01:47 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
아직 개념이 부족해서 좀더 공부를 해봐야할 것 같습니다
관련 링크 남겨주셔서 감사합니다!👍

2021-03-10 07:42 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
옛날에는 로거 static으로 많이 썼는데, 요즘은 안 쓰는 분들도 있어요. spring 빈은 singleton이여서 크게 차이나지 않습니다. 저도 방금 spring 예제 프로젝트 찾아봤는데 거기서도 static 쓰는 분들과 안 쓰는 분들 둘 다 있네요.

2021-03-10 07:42 UTC, merged

2021-03-10 14:47 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
맞아요 애매한 부분입니다. Java진영에서 자주쓰는 Lombok에서는 `private static final`로 만들어줍니다.
이 정도 레벨에서는 취향 차이인 것 같아요.