[roach] 미션1: 회원 가입, 사용자 조회, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #4
Opened 2021-03-02 14:00 UTC by tmdgusya

구현하면서 고려한 점들 🧐
최근 공부해왔던 객체지향에 입각해서 최대한 역할의 분리를 해내려고 노력했습니다.
JavaDoc 을 최대한 사용해보려고 했습니다. (공부 용도)
Api Documentation 을 간략하게라도 적어보기 위해 별도의 Md 파일로 구성하였습니다. (src/documentation)
Repository 를 분리한 이유? 😃
해당 게시판을 만들면서 느낀 점은 해당 저장소(Repository) 가 언제든 다른 걸로 바뀔 수 있다고 생각하였습니다. 만약 나중에 DB 에 입각해서 ORM 혹은 JDBC 를 사용한다면 코드를 갈아엎는 일이아닌 또 다른 클래스를 만든 뒤 Repository 를 구현하여 다른코드에 영향이 가지 않도록 구현하려고 노력했습니다.
신경쓰지 않은 부분들
사실 validation 부분이나 Optional 로 넘겨줘야 될것 같은 부분들을 처리하지 않았습니다. 이번 장에서는 해당 유효성 검증보다, 스프링 자체가 어떤 원리로 돌아가는지 공부하고, 해당 기술을 응용해보는 챕터라고 생각했습니다. 만약 이번주에 시간이 난다면 해당 부분에 대한 유효성 검증 로직을 작성할 것입니다.

테스트 코드는 선택사항으로 제공되어 있어 간단하게 테스트 했던것 같습니다. 최대한 자바 코드로서 테스트를 해보려고 노력했고, 어떻게 하면 인터페이스나 다른 코드가 변경되더라도 구현 요구사항만 충족된다면 해당 테스트를 통과할 수 있을까? 라는 생각을 했던것 같습니다. 그렇게 생각하다보니, 인터페이스 자체를 다시 보게되고 좋은 경험이였던것 같습니다.

** 아직 스프링에 대해 잘 모르기 때문에 리뷰 주실때 어떤 방향으로 가면 좋은지 알려주시면 감사하겠습니다!**

제가 만든 싸이트는 아래 링크에서 확인이 가능합니다!

Herouku 배포링크 : https://fierce-bayou-72083.herokuapp.com/

2021-03-03 13:08 UTC, wheejuni requested changes
스프링 첫 과제 진행하시느라 고생 많으셨습니다. 👍 
앞으로도 아름다운 스프링의 세계에서 허우적거리시게 될 겁니다. 제가 항상 응원하겠습니다. 
간단한 피드백 조금 남겨 드렸습니다. 확인해보시고 반영 혹은 추가 질문 부탁드릴게요.

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/qna/form").setViewName("qna/form");
이 설정의 역할은 무엇이고, 왜 설정하셨나요?

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private Logger logger = LoggerFactory.getLogger(UserController.class);
`Autowired` 된 필드와 그렇지 않은 필드엔 강제 개행을 둬서 구분될 수 있도록 해 주세요. 
그리고 많은 경우에 `Logger` 는 클래스 최상단에 위치합니다.

```suggestion
    private Logger logger = LoggerFactory.getLogger(UserController.class);
    
    @Autowired
    private UserService userService;

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
`User` 를 통째로 모델에 넣을 방법은 없으려나요?

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm");
이건 상수 성격이 짙은 것 같네요. 
`private static final` 이나 심지어 `public static final` 이면 안될까요? 그리고 변수명도 `simpleDateFormat` 보다는 구체적이여야 할 것 같은데요. "간단 날짜 형식" 을 표현하고 싶으셨나요?

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/PostRepository.java
> +    public void add(Post post);
`add` 라는 메소드명은 L 모 컬렉션 객체의 향이 진하게 납니다. 
`save` 가 본질에 더 가까운 표현 같아보여요. 그리고, `save` 한 다음 `save` 된 객체를 다시 되돌려주면 활용가치가 무궁무진할 것 같은데요, 이를테면 아래와 같은 구현이 가능해질겁니다.

```java
public Post saveSomething(Post post) {
    return postRepository.save(post);
}
```

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/PostRepositoryImpl.java
> +    private List<Post> posts;
여러 스레드가 한 번에 여기에 접근하면 어떻게 될까요?

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    public void save(User user);
여긴 `save` 라고 하셨네요 크흠;; ㅋㅋ

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/UserRepositoryImpl.java
> +    private final ConcurrentMap<String, User> users;
여긴 또 `ConcurrentMap` 잘 쓰셨네요 크흠;;

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/PostService.java
> +    PostRepository postRepository = new PostRepositoryImpl(Collections.synchronizedList(new ArrayList<>()));
이것도 의존성 주입을 통해 관리할 수 있으려면 어떻게 해야할까요?

_힌트_
`@Configuration`
`@Bean`

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/PostService.java
> +    }
`Service` 클래스에서 `Optional<T>` 를 리턴하는 건 좀 아쉬운 것 같고요,
판단하시기에 `null` 이 아니어야 한다면 이 `Optional` 객체를 풀어보고, `null` 여부에 따른 예외 처리가 여기에 들어가야 할 것 같습니다.

2021-03-03 13:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public int contOfUsers() {return userRepository.size();}
오타 있네요.

2021-03-03 13:15 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/service/PostService.java
> +    }
아 저도 이부분이 참 애매했는데 좋지 않은 방식이였네요.
저도 Service 단에서 Optional 에 대한 처리가 이뤄지는게 맞는지, Controller 단에서 이뤄지는게 맞는지 애매하다고 생각하여,
일단 넘겨두었는데 좋은 피드백 감사합니다. Service 단에서 이뤄지는게 좋은 방식이군요

2021-03-03 13:16 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/service/PostService.java
> +    PostRepository postRepository = new PostRepositoryImpl(Collections.synchronizedList(new ArrayList<>()));
AppConfig 파일 만들어서 따로 관계를 지정 시켜주는 역할을 하는곳을 만들면 될것 같습니다

2021-03-03 13:16 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/repository/UserRepositoryImpl.java
> +    private final ConcurrentMap<String, User> users;
크흠.. 위에 List 부분은 고치도록하겠습니다.

2021-03-03 13:18 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/repository/PostRepositoryImpl.java
> +    private List<Post> posts;
해당 부분을 근데 주입하는 부분에서 synchronized 로 주고있는데 이거말고 다른 thread-safe list 가 있나요?
제가 다른거 아는거는 CopyOnWriteArrayList 밖에 없는데 혹시 다른 좋은 방법이 있을까요?

```java
PostRepository postRepository = new PostRepositoryImpl(Collections.synchronizedList(new ArrayList<>()));
```

2021-03-03 13:19 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/repository/PostRepository.java
> +    public void add(Post post);
고치도록 하겠습니다. 생각해보니 한쪽은 save 로 했는데 통일성도 떨어지고 위의 방식이 더 좋은 네이밍 같네요.

2021-03-03 13:20 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm");
아 그부분을 생각하지 못했네요. 음 "간단 날짜 형식" 은 아닌데 기존에 포비 게시글에 있던 날짜 그대로를 사용했습니다.
이 부분 네이밍은 생각해보아야 겠네요.

2021-03-03 13:20 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/PostRepositoryImpl.java
> +    private List<Post> posts;
아 죄송합니다. 이부분을 미처 놓쳤네요.

2021-03-03 13:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/UserRepositoryImpl.java
> +    private final ConcurrentMap<String, User> users;
앞서서 제가 놓친 부분이 있는데 생성자를 통해 동시성이 확보된 구현체가 들어간다면 어느 쪽이든 무방합니다.

2021-03-03 13:23 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/qna/form").setViewName("qna/form");
이게 그 templates 로 html 파일들을 옮기게 될시 그 특정 url 에 요청을 보내야 templates 에 있는 html 파일들을 보내줄 수 있는 구조더라고요. 그래서 루카스에 올라와 있는 자료에 이러한 경우 addViewController 를 이용해라 라고 나와있어 해당 방식을 사용했습니다. 따로 Controller 를 두어 처리하기에는 반복작업에 별도의 처리가 필요하지 않고, Html 파일만 return 해주면 되기때문입니다.

제가 이해한 방식은 `/user/form` 에 GET 요청이오면 `user/form.html` 을 반환하라 입니다.

2021-03-03 14:10 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
```java
model.addAttribute("user", user);
```

로 보내고, 해당 html 에서 {{user.name}} {{user.email}} 로 하니 정상적으로 작동하네요!

2021-03-03 14:19 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm");
"yyyy-MM-dd hh:mm:ss" 는 ISO8601 이라고 불린다고 하네요 해당 naming 으로 변경하였습니다.

2021-03-04 00:31 UTC, wheejuni approved these changes
`Optional.get()` 은 과정이 끝날 때까지 봉인해주세요. 
`UserService` 에서는 `.isPresent()` 호출이 먼저 있어서 괜찮았지만 검증 없는 `.get()` 은 안됩니다. 
수고 많으셨습니다.

2021-03-04 00:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/PostService.java
> +        return post.get();
`Optional.get()` 은 위험합니다;;
적절한 예외 처리를 해 주세요.

2021-03-04 00:31 UTC, merged

2021-03-04 01:04 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/service/PostService.java
> +        return post.get();
아넵 이부분 명심할 수 있도록 하겠습니다. 제가 실수했네요

리뷰 감사합니다 🙏🏻