[Jane] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #43
Opened 2021-03-09 10:35 UTC by janeljs

안녕하세요 제인입니다!🙂 이번 PR에서 변경된 부분들에 대해 간략하게 설명드리겠습니다.

1. 원래는 User만 서비스와 컨트롤러가 분리되어 있었는데, Question과 Answer 또한 서비스와 컨트롤러를 분리하였습니다.

2. try~catch문을 많이 사용하는 것을 지양하기 위해 GlobalExceptionHandler 클래스를 정의하였습니다. 
  - FailedUserLoginException, IllegalUserAccessException, QuestionNotFoundException, UserNotFoundException을 정의한 뒤 각 예외에 대한 핸들러 메서드를 만들었습니다.
  - ❓궁금한 점: 제가 참고했던 블로그에서는 각 메서드를 protected로 선언하고 있었는데, private으로 선언해도 잘 작동하길래 접근 제어자를 변경했습니다. 일반적인 경우 `@ExceptionHandler`가 달린 메서드는 접근제어자를 어떻게 설정하는지 궁금합니다.

그러면 이번에도 리뷰 잘 부탁드리겠습니다! 감사합니다🙇‍♀️

+) 2단계 approve를 받았지만, 아직 머지가 되지 않아 변경 커밋에 2단계 수정 내역도 같이 뜨네요! 2단계 변경사항도 기재드립니다.
### 2단계 변경사항
- EntityManager에 대해 잘 알지 못하고 사용하는 것 같아 해당 부분을 삭제하고 JpaRepository를 상속하는 인터페이스로 각 repository를 구현하였습니다.
- UserController에서 직접 처리해주던 Optional 처리를 UserService 안에서 하도록 수정하였습니다.
- 지난 체스 미션 때 롬복을 적용해보라는 피드백을 받은 것이 생각나 해당 부분에 대해 학습하고 롬복을 적용해보았습니다.
- UserController와 QuestionController 내부에 checkPermission 메서드를 추가하여 중복 코드를 제거하고, try ~catch문으로 예외를 잡아주었습니다.

2021-03-09 12:25 UTC, wheejuni requested changes
3단계까지 빠르게 진행해 주셨네요. 수고 많으셨습니다 💯 
크게 구조개선이 필요한 부분은 없어보이고요, 사소한 피드백을 좀 남겨 보았습니다.
한번 검토해 보시고요, 추가 질문 있으시면 남겨주세요. 감사합니다!

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +
👍

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private final Logger logger = LoggerFactory.getLogger(UserController.class);
헐~ 뭔가 이상한데요? ㅋㅋㅋ

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("")
빈 문자열을 두시지 말고 그냥 과감히 빼셔도 괜찮습니다!

```suggestion
    @PostMapping

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        return String.format("redirect:/questions/%d", questionId);
이런 경우에는 그냥 문자열 덧셈 연산을 하는 것이 가독성 측면에서 조금 더 유리할 것 같네요.

```suggestion
        return "redirect:/questions/" + questionId;

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            throw new FailedUserLoginException();
👍 👍 👍

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.delete(question);
퍼미션 체크를 `QuestionService` 안에서 수행하는 게 더 자연스러워 보여요.

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
👍 👍 👍 
놓치기 쉬운 포인트인데 잘 잡고 사용하셨네요.

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
`Lob` 이요??? 그렇게 길어야 하나요?

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        return date.format(DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm"));
`.ofPattern()` 의 파라메터로 전달된 포맷은 별도 상수로 선언해서 쓰는 것도 좋아보여요.

```java
public static final String ANSWER_DATETIME_FORMAT = "yyyy.MM.dd HH:mm";

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
이걸 두고 저도 한때 많은 고민을 했었는데 제인도 고민을 해보시기를 강력히 권합니다. 
읽어볼만한 글을 두개 추천드릴게요.

https://stackoverflow.com/questions/5031614/the-jpa-hashcode-equals-dilemma
https://web.archive.org/web/20171211235806/http://www.onjava.com/pub/a/onjava/2006/09/13/dont-let-hibernate-steal-your-identity.html

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/FailedUserLoginException.java
> +public class FailedUserLoginException extends RuntimeException {
너무 좁은 범위의 예외인 것 같네요.
넓은 범위에서 유저 인증/보안 관련 상황을 핸들할 수 있는 예외라면 어땠을까요.

2021-03-09 12:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
👍 👍 👍

2021-03-09 12:29 UTC, janeljs commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private final Logger logger = LoggerFactory.getLogger(UserController.class);
앗 죄송합니다ㅋㅋㅋㅋ User에서 복붙했는데 들켰네요...ㅎㅎ

2021-03-09 12:33 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
자바지기님 강의를 들을 때 추가하시길래 따라했는데 이미지나 동영상 등을 삽입하지 않으면 필요 없을 것 같긴 합니다..ㅎㅎ 삭제하는게 좋을까요?

2021-03-09 12:35 UTC, janeljs commented on src/main/java/com/codessquad/qna/exception/FailedUserLoginException.java
> +public class FailedUserLoginException extends RuntimeException {
exception handler에서 각각 다른 페이지로 리다이렉트 시키려고 범위를 좁게 잡았는데, 지금 보니 거의 다 로그인 페이지로 가고있어 유저 인증 및 보안 예외를 통합할 수 있을 것 같아요!ㅎㅎ 피드백 감사합니다.

2021-03-09 13:06 UTC, janeljs commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +
저는 왜 `Ensure every saved file ends with a line break` 설정을 해뒀는데도 자동으로 추가가 안되는 걸까요?😅 매 PR마다 꼼꼼하게 확인하는데도 파일이 많다보니 가끔 추가를 까먹네요..ㅠㅠ

2021-03-09 14:18 UTC, janeljs commented
@wheejuni 안녕하세요 제인입니다!🙂 저번에 DM으로 질문드린다음 실례가 되는 행동이 아니었을까 혼자 걱정이 많았는데, 다시 소중한 시간을 내어 리뷰해주셔서 감사합니다❤️ 

1. User와 Question의 컨트롤러에 있는 checkPermission을 Service 내로 이동하였고, permission 체크를 포함하는 메서드는 `Question findVerifiedQuestion(Long id, HttpSession session)`와 같이 정의해 주었습니다.

2. FailedUserLoginException와 IllegalUserAccessException를 IllegalUserAccessException로 합치고,  IllegalUserAccessException 내부에 메시지를 매개변수로 받는 생성자를 추가하여 유저 검증 및 보안을 한 예외가 담당하게 하였습니다. 

3. 기타 피드백 주신 부분들을 반영하였습니다!

### 해결되지 않은 질문
❓일반적인 경우 @ExceptionHandler가 달린 메서드는 접근제어자를 어떻게 설정하는지 궁금합니다. 제가 참고했던 블로그에서는 각 메서드를 protected로 선언하고 있었는데, private으로 선언해도 잘 작동하길래 접근 제어자를 변경했습니다. 

링크해주신 글 두개에 대해서는 깊이 고민해본 뒤, 생각이 정리되면 코멘트 남기겠습니다. 변경사항들을 검토하신 후 이상이 없다면 approve 부탁드립니다!

2021-03-09 17:40 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
@wheejuni 데이터베이스에 대한 지식이 전혀 없어 이해가 어려웠지만 정독해 보았습니다🔥 

현재 저는 Long id를 기본키로 사용하고 있고, `@GeneratedValue(strategy = GenerationType.IDENTITY)`처럼 설정하여 기본키 생성을 DB에 위임한 상태인데요. 링크해주신 글에서는 데이터베이스의 자동 증가값 또는 (혹시 변경될 수도 있는) 객체의 id가 아닌 entity 특정 id를 기본키로 사용할 것을 권장하네요. 
기본키는 (데이터베이스에 저장되기 전) 객체의 생성과 동시에 부여되어야 하고, 이전에 저장되었던 객체인지 새로 생성된 객체인지는 version 등 객체의 다른 필드가 null인지 체크해서 알아내는 것이 좋으므로 키 생성을 외부에 위임하기 보다는 자바에 있는 UUID Generator를 이용하라는 것 같습니다.
(만약 Long이 아닌 UUID로 id를 선언하고 `@Id, @GeneratedValue`를 붙이면 하이버네이트가 UUID generator가 되지만, 이것 역시 하이버네이트에 종속적이므로 객체가 생성될 때 id가 부여되는 것이 아니라, 저장될 때까지 기다려야 한다는 점에서 db 자동생성키 사용이랑 동일하니까요)

제가 이해한 바로는`@GeneratedValue(strategy = GenerationType.IDENTITY) Long id` 부분을 `UUID uuid = UUID.randomUUID();`로 대체하면 될 것 같은데 제대로 이해한 걸까요? 이렇게 바꿀 시 어떤 문제점이 발생할까요? 확실히 데이터베이스에 저장되는 순서대로 기본키를 설정하는 것보다는 객체 생성과 동시에 키를 부여하는게 좋아보이는데 어떤 지점에서 고민하고 계신지가 궁금합니다!

2021-03-09 17:45 UTC, janeljs commented
@wheejuni 안녕하세요 제인입니다!🙂 저번에 DM으로 질문드린다음 실례가 되는 행동이 아니었을까 혼자 걱정이 많았는데, 다시 소중한 시간을 내어 리뷰해주셔서 감사합니다❤️ 

### 변경 사항
1. User와 Question의 컨트롤러에 있는 checkPermission을 Service 내로 이동하였고, permission 체크를 포함하는 메서드는 `Question findVerifiedQuestion(Long id, HttpSession session)`와 같이 정의해 주었습니다.

2. FailedUserLoginException와 IllegalUserAccessException를 IllegalUserAccessException로 합치고,  IllegalUserAccessException 내부에 메시지를 매개변수로 받는 생성자를 추가하여 유저 검증 및 보안을 한 예외가 담당하게 하였습니다. 

3. 기타 피드백 주신 부분들을 반영하였습니다!

### 해결되지 않은 질문
❓일반적인 경우 @ExceptionHandler가 달린 메서드는 접근제어자를 어떻게 설정하는지 궁금합니다. 제가 참고했던 블로그에서는 각 메서드를 protected로 선언하고 있었는데, private으로 선언해도 잘 작동하길래 접근 제어자를 변경했습니다. 

🌟  기본키 설정 관련 링크해주신 글에 대해 코멘트 남겼습니다. 이에 대한 브라이언의 생각을 꼭 듣고싶네요! 
🌟 변경사항들을 검토하신 후 이상이 없다면 approve 부탁드립니다!

2021-03-09 17:48 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
@wheejuni 데이터베이스에 대한 지식이 전혀 없어 이해가 어려웠지만 정독해 보았습니다🔥 

현재 저는 Long id를 기본키로 사용하고 있고, `@GeneratedValue(strategy = GenerationType.IDENTITY)`처럼 설정하여 기본키 생성을 DB에 위임한 상태인데요. 링크해주신 글에서는 데이터베이스의 자동 증가값 또는 (혹시 변경될 수도 있는) 객체의 id가 아닌 entity 특정 id를 기본키로 사용할 것을 권장하네요. 

글 전체에 걸쳐 기본키는 (데이터베이스에 저장되기 전) 객체의 생성과 동시에 부여되어야 하고, 이전에 저장되었던 객체인지 새로 생성된 객체인지는 version 등 객체의 다른 필드가 null인지 체크해서 알아낼 것을 강조하고 있는데요.
구체적으로는 키 생성을 외부에 위임하지 말고 자바에 있는 UUID Generator를 이용하라는 것 같습니다.

(만약 Long이 아닌 UUID로 id를 선언하고 `@Id, @GeneratedValue`를 붙이면 하이버네이트가 UUID generator가 되지만, 이것 역시 하이버네이트에 종속적이므로 객체가 생성될 때 id가 부여되는 것이 아니라, 저장될 때까지 기다려야 한다는 점에서 db 자동생성키 사용이랑 동일하니까요)

제가 이해한 바로는`@GeneratedValue(strategy = GenerationType.IDENTITY) Long id` 부분을 `UUID uuid = UUID.randomUUID();`로 대체하면 될 것 같은데 제대로 이해한 걸까요? 이렇게 바꿀 시 어떤 문제점이 발생할까요? 확실히 데이터베이스에 저장되는 순서대로 기본키를 설정하는 것보다는 객체 생성과 동시에 키를 부여하는게 좋아보이는데 어떤 지점에서 고민하고 계신지가 궁금합니다!

2021-03-10 02:03 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
진짜 읽기 좋은글이네요.
제가 해석한 바가 틀릴 수도 있는데 해당 글 자체에서 이제 Hibernate 에 Key 생성을 위임하지 말라고 하는 이유는,
JVM 과 우리가 ORM 을 썼을 때 두개의 객체가 DB 의 한 row 를 가르키게 되는데, 이게 다른 객체로 판단 될 수 있기 때문입니다.
밑에서 이해한 바를 조금 상세하게 적어보겠습니다.

그래서 우리는 이 두 객체를 DB 의 한 row 를 바라보기 때문에 같은 객체로서 인식시켜야 되서, 우리의 unique key 인 id 를 기반으로 `equals()` 와 `hashcode()` 를 재정의 해줘야 합니다. 그니까 여기서 말하는게 객체가 생성되는 시점에 @GeneratedValue 를 주게 되면 이제 Hibernate 로 key 할당 권한이 넘어가게 되는데, **이 경우 처음에는 객체의 id 가 null** 이고, DB 를 보고 할당된 후 부터 id 를 가지게 되는데 처음 id 가 null 일때는 두 객체가 같은 DB 를 바라보고 있어도 `equals()`, `hashcode()` 가 안될 수 있다고 말하는 것같습니다. 그러기에 위에 @wheejuni 께서 다른 방법들을 고민하신것 같네요.

2021-03-10 02:04 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
> @wheejuni 데이터베이스에 대한 지식이 전혀 없어 이해가 어려웠지만 정독해 보았습니다🔥
> 
> 현재 저는 Long id를 기본키로 사용하고 있고, `@GeneratedValue(strategy = GenerationType.IDENTITY)`처럼 설정하여 기본키 생성을 DB에 위임한 상태인데요. 링크해주신 글에서는 데이터베이스의 자동 증가값 또는 (혹시 변경될 수도 있는) 객체의 id가 아닌 entity 특정 id를 기본키로 사용할 것을 권장하네요.
> 
> 글 전체에 걸쳐 기본키는 (데이터베이스에 저장되기 전) 객체의 생성과 동시에 부여되어야 하고, 이전에 저장되었던 객체인지 새로 생성된 객체인지는 version 등 객체의 다른 필드가 null인지 체크해서 알아낼 것을 강조하고 있는데요.
> 구체적으로는 키 생성을 외부에 위임하지 말고 자바에 있는 UUID Generator를 이용하라는 것 같습니다.
> 
> (만약 Long이 아닌 UUID로 id를 선언하고 `@Id, @GeneratedValue`를 붙이면 하이버네이트가 UUID generator가 되지만, 이것 역시 하이버네이트에 종속적이므로 객체가 생성될 때 id가 부여되는 것이 아니라, 저장될 때까지 기다려야 한다는 점에서 db 자동생성키 사용이랑 동일하니까요)
> 
> 제가 이해한 바로는`@GeneratedValue(strategy = GenerationType.IDENTITY) Long id` 부분을 `UUID uuid = UUID.randomUUID();`로 대체하면 될 것 같은데 제대로 이해한 걸까요? 이렇게 바꿀 시 어떤 문제점이 발생할까요? 확실히 데이터베이스에 저장되는 순서대로 기본키를 설정하는 것보다는 객체 생성과 동시에 키를 부여하는게 좋아보이는데 어떤 지점에서 고민하고 계신지가 궁금합니다!

제인 덕분에 좋은거 하나 공부하고 갑니다~~

2021-03-10 02:18 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
@tmdgusya 로치 코멘트 감사합니다!ㅎㅎ 로치 설명을 들으니 더 이해가 잘 되는 것 같네요!😄

>  Hibernate 에 Key 생성을 위임하지 말라고 하는 이유는, JVM 과 우리가 ORM 을 썼을 때 두개의 객체가 DB 의 한 row 를 가르키게 되는데, 이게 다른 객체로 판단 될 수 있기 때문입니다. (...) 이 경우 처음에는 객체의 id 가 null 이고, DB 를 보고 할당된 후 부터 id 를 가지게 되는데 처음 id 가 null 일때는 두 객체가 같은 DB 를 바라보고 있어도 equals(), hashcode() 가 안될 수 있다고 말하는 것같습니다. 그러기에 위에 @wheejuni 께서 다른 방법들을 고민하신것 같네요.

해당 문제를 해결하기 위해 아티클에서는 "That is, instead of having a database-centric ID, or an object-centric ID, we should create one universal entity-specific ID that represents the data entity and is created when the data is first entered."라고 주장하는 것 같은데요! 제가 고민하셨던 지점을 여쭤본 건, 아티클의 결론대로 java.util.UUID 클래스를 쓰지 않고 현재와 같이 DB에 기본키 생성을 위임하는 것에 다른 장점이 있나 싶어서였습니다ㅎㅎ (아직 입문 강의라 그럴 수도 있겠지만) 김영한 님, 자바지기 님 등 다른 분들 강의에서도 UUID 사용보다는 `@GeneratedValue(strategy = GenerationType.IDENTITY)` 어노테이션과 함께 Long id를 쓰고 있어서요!

혹시 이 부분에 대해서 로치도 아는 부분이 있으시다면 코멘트 부탁드립니다!

2021-03-10 02:29 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
이건 그냥 제 추측인데 DB 를 갔다온 뒤 id 를 정하는 것이라면 성능 저하도 있을 수 있다고 생각합니다.

**uuid 를 통해 id 를 정해줄시**
  - uuid 로직만 거친뒤 id 에 그값을 저장해주는 비용
  
**기본키 생상 전략을 위임할 시**
  - DB 값 기준으로 이뤄져야 하기에 초기에 null 이며, DB 를 보고 어떤 id 값을 넣어야 할지 판단하는것

두 비용을 계산해봤을때 아무래도 후자의 비용이 조금 더 크지 않을까 생각합니다. 
이런 걸 보완하기 위해서 다른 strategy 들이 있는 것이 아닐까 싶네요? 
저도 이 부분 조금 생각해봐야겠다는 생각이 드네요. 만약 데이터베이스 삽입이 많은데 DB 와의 통신을 거친뒤 id 를 생성해주는 로직이라면
그게 성능상의 영향을 끼칠 수 있다고 생각되거든요. 

아마 리뷰어 분들이 더 잘알것같긴하네요! 저도 초보이기에..

2021-03-10 02:38 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
답변감사해요! ㅎㅎ 성능 저하에 대해서는 생각을 못해봤는데 데이터가 엄청 많고 미션 때처럼 bulk insert?같은 걸 하면 키 생성 전략이 성능에도 영향을 미칠 것 같은 느낌적인 느낌이네요ㅋㅋ 브라이언의 코멘트를 기다려야겠어요😄

2021-03-10 03:35 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
@tmdgusya 우선 롱타입 PK와 성능 차이는 거의 발생하지 않을 것이라고 생각합니다. 
@janeljs 이 글이 지적하는 핵심 포인트는 **하이버네이트 세션에 담길 때까지(PK가 부여될 때까지) 객체의 동등성을 비교하지 못하는 문제**에 대해 대처하는 자세입니다. 하이버네이트로 관리되는 객체가 될 때까지 객체의 동등성을 판단하지 못 하는 케이스가 생겨도 괜찮냐는 것이죠. 저자는 "괜찮지 않다" 고 얘기하는 거고요.
그래서 UUID로 @Id를 삼으라는 것이 아니라 개발자의 책임에 따라 비즈니스 목적으로 객체의 동등성을 규정할 만한 다른 키를 만들라는 얘기입니다. 그리고 그 값은 UUID이면 안될 것 같긴 하네요. UUID로 비즈니스 로직 상 의미있는 동등성 비교를 할 수 있는 방법이 제가 생각하기엔 없어 보여서요. 

`@GenerationStrategy` 의 퍼포먼스에 대해서는 [여기](https://github.com/HomoEfficio/dev-tips/blob/master/JPA-GenerationType-%EB%B3%84-INSERT-%EC%84%B1%EB%8A%A5-%EB%B9%84%EA%B5%90.md) 를 참고해보시면 좋겠네요.

2021-03-10 04:46 UTC, honux77 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
어떤 타입이 좋을지 한번 찾아보는 것도 좋겠네요? 저도 영상 그 부분 들으면서 어 이건 아닌데? 생각했습니다 ㅋㅋ

2021-03-10 06:45 UTC, janeljs commented
[추가] 과정 중에는 롬복을 사용하지 않는다는 피드백을 받아 롬복 애노테이션을 제거하였습니다.

2021-03-10 14:23 UTC, janeljs commented
[추가] 그룹 코드 리뷰시간에 받은 피드백들을 적용하였습니다.

2021-03-10 15:05 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
@wheejuni 핵심 포인트에 대하여 다시 정리해주셔서 감사합니다! 아직 제가 관련 지식이 부족하여 이 문제에 대해서는 더 공부한 뒤 다시 생각을 정리해볼게요! 감사합니다🙏

2021-03-10 15:08 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
현재로서 드는 의문은, 하이버네이트로 관리되는 객체가 되기 전에 키를 부여하려면 어떤 방식이든 그 아이디를 만드는 id generator가 있어야 할 것 같은데요. UUID generator는 이에 적합하지 않다면 어떤 키를 적용해야할지 고민이 되네요.

2021-03-10 15:16 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/User.java
> +@EqualsAndHashCode(of = {"id"})
호눅스 페북에서 봤는데 반대되는 입장들도 있네요. 제 수준에서 이해하기는 어렵지만 @tmdgusya 는 참고하시면 좋을 것 같아요ㅋㅋ
https://forum.hibernate.org/viewtopic.php?p=2329719

2021-03-10 15:36 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
@wheejuni @honux77  [Datatype Limits](https://docs.oracle.com/cd/B28359_01/server.111/b28320/limits001.htm#i287903)를 보니까 타입별 리밋이 나와있는데요! Lob annotation을 붙인 CLOB은 최대 용량이 `(4 GB - 1) * DB_BLOCK_SIZE`이고, varchar는 최대 사이즈가 4000 바이트라고 합니다. 생각보다 맥스가 낮아서 `@Lob`을 붙이는게 좋을 것 같은데 혹시 어떻게 생각하세용??

2021-03-10 15:43 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
@janeljs 우선 계수가 4GiB네요? 하나의 질문글에 최소 4GiB를 가져야할 요구사항이...전 잘 보이지 않아요.
그리고 제인이 참고한 다큐먼트는 MySQL이 아니라 Oracle 11g DBMS의 레퍼런스네요. 
전 개인적으로 오랜만에 오라클 문서를 봐서 반갑긴 한데 제인의 상황에 맞는 문서는 아닌 것처럼 보이네요.
오라클은 `CLOB` 과 `BLOB` 을 적극적으로 사용해요. 말씀처럼 `VARCHAR` 가 제공하는 스페이스가 너무 작아서요.
반면 MySQL은 65535 Byte까지 제공하니까요. `VARCHAR` 나 `TEXT` 를 사용하는 것이 좋겠는데 어떻게 생각하세요?

2021-03-10 15:46 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
아하 그렇군요! 제가 이번에 db를 처음 접해서 데이터베이스에 따라 스펙이 달라진다는 생각을 못했어요! 그러면 h2 database에 해당하는 문서를 찾아야했던 거군요ㅎㅎ 말씀주신대로 현재 요구사항에서는 varchar를 사용하는게 더 좋을 것 같습니다. 해당 애노테이션 제거할게요~ㅎㅎ

2021-03-10 16:17 UTC, janeljs commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
h2 database는 지원 용량이 적은 것 같습니다 ㅠㅠ 롭 애노테이션을 제거했더니 ` Value too long for column "CONTENTS VARCHAR(255)"`와 같은 메시지가 나오면서 프로그램이 종료되어 다시 추가할게요!

2021-03-11 08:23 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @Lob
@janeljs `@Column(length = xxx)`로 하면 varchar로도 될거에요! JPA기본값이 255일 것 같아요

2021-03-12 03:31 UTC, wheejuni approved these changes
이제 머지되어도 되겠죠? @janeljs

2021-03-12 03:35 UTC, janeljs commented
@wheejuni 넵! 머지 부탁드립니다ㅎㅎ

2021-03-12 03:35 UTC, merged