[Dong] 미션1: 회원 가입, 사용자 조회, 질문하기 구현 PR 올립니다
codesquad-members-2021/spring-boot-qna pull request #44
Opened 2021-03-09 11:44 UTC by d-h-k

# intro
- 안녕하세요 코드스쿼드 백엔드반 Dong 입니다!
- 미션1 PR 요청 올립니다 많이 늦어서 죄송합니다! 
- 웹개발이 처음이라 http로 데이터가 어떻게 날아가고 주고받는지 이해하는데 어려움을 겪었습니다
- 하지만 코드스쿼드 수강생들의 도움 덕분에 해낼수 있었고, 미션의 요구사항 분석조차 어려워 아래 노션페이지에 문제를 재정의해가며 미션을 수행하였습니다. 
- https://www.notion.so/Q-A-with-SpringBoot-4c6e0273407a477bb089a64266845314

#

2021-03-10 15:23 UTC, wheejuni requested changes
수고하셨습니다. 👍 전반적으로 로직의 구현 방향은 나쁘지 않으나, 
**기본적인 코딩 컨벤션** 을 준수하였는지 항상 확인해주시는 습관을 가지시면 좋겠습니다.
코딩 컨벤션 관련 의견 비롯해서 몇 가지 개선 의견 드렸습니다.
확인해보시고, 반영해주시거나 추가 질문 있으시면 알려주세요.

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        question.setIndex(questionList.size()+1);
연산자 앞뒤로 한칸씩 공백 잊지 말아주세요!

```suggestion
        question.setIndex(questionList.size() + 1);

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    final private List<Question> questionList = new ArrayList<>();
접근제어자 누락됐네요.

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    @GetMapping("/qna/form.html")
뒤에 `.html` 이라는 접미사 꼭 붙어야 하나요?

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +    private boolean is_sameUser(User u1, User u2) {
메소드 이름 ㅠㅠ 이런건 이제 조심하실 수 있을 것 같아요.
반복된 피드백 받으시면 Dong도 저도 기분이 좋지 않을 것 같아요. 주의해주심이 어떠한가요?

그리고 이 로직은 `User` 의 `.equals()` 를 오버라이드함으로써 구현돼야 할 것 같네요.

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
`java.lang.Object` 의 메소드들을 오버라이드하는 경우 위치는 클래스의 맨 밑바닥으로 하는 것이 관례입니다.

2021-03-10 15:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +
이 개행은 필요없어 보이는데요.

2021-03-10 16:51 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        question.setIndex(questionList.size()+1);
넵! 말씀해주셔서 감사합니다. 앞으로도 연산자 앞뒤로 공백 한칸씩 꼭 삽입하겠습니다!

2021-03-10 16:54 UTC, moto6 commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    final private List<Question> questionList = new ArrayList<>();
넵 Logger 클래스의 인스턴스 생성시 private 접근제어자를 추가하겠습니다! 감사합니다

2021-03-10 16:59 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    @GetMapping("/qna/form.html")
접미사는 붙지 않아도 동작 가능합니다!  해당 부분 수정했습니다!

2021-03-10 17:03 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
넵 그런관례가 있는지 몰랐습니다. 말씀하신 부분 수정하고 앞으로도 유념하겠습니다.

2021-03-10 17:04 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/User.java
> +
넵 해당부분의 불필요한 개행을 제거하겠습니다

2021-03-10 17:44 UTC, moto6 commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +    private boolean is_sameUser(User u1, User u2) {
해당 부분 변명의 여지없는 제 실수입니다 ㅠㅠ..

사실 코딩할때는 편하게 쓰고 제출전에 변수명을 고쳐야지라는 안일한 생각을 해서 이렇게 황당하게 메서드명과 입력매개변수명을 지었습니다. ㅠㅠ.. 죄송합니다. 앞으로는 이런 실수 없도록 주의하겠습니다!

2021-03-12 03:33 UTC, wheejuni approved these changes
👏👏

2021-03-12 03:34 UTC, merged