[NAS] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #45
Opened 2021-03-09 12:00 UTC by Malloc72P

안녕하세요? 😄 
백엔드 클래스의 NAS라고 해요! 

미션3 로그인 기능 구현을 완료해서 PR을 남기게 되었어요!

배포주소는 [여기예요!](https://spring-qna-nas.herokuapp.com/)

이번에는 뭘 구현했는지 쓰기 보다, 구현하면서 겪었던 어려웠던 점을 작성해보았습니다!
### 1. 객체 관계 매핑문제
* `@ManyToOne`어노테이션으로 Answer와 Question을 매핑했더니 Question을 지울때 에러가 발생하더라구요. Question에 종속된 Answer가 남아있는 상태에서 Question을 지우려니까 이런 문제가 발생한 것 같았어요. 그래서 어떻게 할까 하다가 Question에도 관계를 부여했어요. 그 다음 cascade 설정을 해서, Question이 지워지면 관계된 모든 Answer가 지워지도록 구현했습니다. 이렇게 하니까 되긴 되는데 올바른 구현인지 의문이 드네요. 참 어려운 것 같아요 😫 

이상으로 글을 마치겠습니다.
이번에도 리뷰 잘 부탁드려요! 😆

2021-03-10 17:10 UTC, ksundong requested changes
안녕하세요! NAS! 리뷰어 Dion입니다!!
3단계를 진행해주시느라 고생 많으셨습니다!
커밋메시지 인상깊네요. 우리말로 명령문 쓰는건 되게 오랜만에 보는 것 같아요.(한 때, 저렇게 적었었습니다.) 😊
'ID설정 실수한거 고쳐라' 이거 너무 웃겼어요 ㅋㅋㅋ

## 질문에 대한 답변

> 1. 객체 관계 매핑문제
> `@ManyToOne`어노테이션으로 Answer와 Question을 매핑했더니 Question을 지울때 에러가 발생하더라구요. Question에 종속된 Answer가 남아있는 상태에서 Question을 지우려니까 이런 문제가 발생한 것 같았어요. 그래서 어떻게 할까 하다가 Question에도 관계를 부여했어요. 그 다음 cascade 설정을 해서, Question이 지워지면 관계된 모든 Answer가 지워지도록 구현했습니다. 이렇게 하니까 되긴 되는데 올바른 구현인지 의문이 드네요. 참 어려운 것 같아요 😫

제가 생각했을 때에는 충분한 구현이라고 생각됩니다. 직접적으로 지워도 괜찮았을 것 같아요.

## 요구사항이 지켜지지 않은 부분

- 애매하긴 한데, 테스트 데이터를 추가해보셨으면 좋았을 것 같아요.
- 수정시에 'https://spring-qna-nas.herokuapp.com/users//modify' 페이지로 가게됩니다. url을 주목해주세요.

## 리뷰

로그인 하지 않았을 때, 질문하기 버튼이 사라지는 구현은 정말 좋네요. 다만 댓글 다는 기능도 처리해줬으면 더 좋았을 것 같아요. (욕심은 끝이 없습니다. ㅋㅋ)
게시글 조회시 시간이 노출되는 부분이 너무 상세합니다. 적절히 Format 해주세요.

이번 미션은 조금 더 생각해보시고, 고쳐볼 부분이 남아있는 것 같아서 **'변경 요청'** 드립니다.
코멘트 참고해주세요!

보시면서 궁금하신 점, 이해가 되지 않는 부분, 토론이 필요한 부분, 도움이 필요한 부분이 있으시면 코멘트 남겨주세요!
고생많으셨습니다!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    @JoinColumn(foreignKey = @ForeignKey(name = "fk_answer_writer"))
ForeignKey를 사용하는게 자바지기님 영상 방식인가요? ㅎㅎ

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
```suggestion
    private String contents;
    
    private LocalDateTime reportingDate;
```

애노테이션이 등록되었을 때, 서로 관계가 없는 필드는 떼어주는 편이 가독성이 좋습니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    @Column(nullable = false, length = 20)
length 20이면 contents로 충분할까요?

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    public boolean isMatchingWriter(User suggestedWriter) {
'suggested'는 조금 맞지 않는 단어가 아닌가 싶어요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +        return writer.isMatchingId(suggestedWriter.getId());
그냥 `suggestedWriter`를 넘겨주어서, 처리하는 것이 더 좋을 것 같습니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +        return writer.isMatchingId(suggestedWriter.getId());
이는 객체지향과 연관이 있는데요, 객체를 직접 전달해줄 수 있으면 속성을 전달하기 보다는 객체를 전달해줍시다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
```suggestion
    private LocalDateTime reportingDateTime;
```

혹은 `createdDateTime`이 무난한 형태입니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    AnswersRepository answersRepository;
아직 Service Layer의 분리가 일어나진 않았나보네요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    AnswersRepository answersRepository;
Spring의 Injection 방식이 무엇인지 알아보고, 최근에 가장 많이 사용하는 Injection 방식이 있는데 한 번 적용해보시는 것을 권장합니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
위의 `url`과 다르네요.
REST에선 둘이 다른 리소스로 인식됩니다.
공통된 부분은 `@RequestMapping`을 통해 추출해주세요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        Question targetQuestion = questionRepository.findById(questionId).orElse(null);
`orElse(null)` 은 좋지 않은 패턴입니다.
차라리 `orElseThrow()`를 사용해보시길 추천드리구요.
`orElseGet()`도 있는데 한 번 학습해봅시다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        Question targetQuestion = questionRepository.findById(questionId).orElse(null);
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        answersRepository.save(answer);
`Controller`가 가지기에는 너무 큰 책임입니다.
`Controller`가 가지는 책임에 대해서 학습해보시고, Spring MVC를 사용할 때, 왜 Controller와 Service, Repository를 구분짓는지 생각해보세요!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        }
중복된 코드가 등장했습니다. 어떻게 해결해 줄 수 있을까요?

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +    private List<Answer> answers;
왠만하면 id를 최 상단에 두고, 적절히 필드 배치를 하시길 추천드립니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +    private List<Answer> answers;
cascade의 사용 좋네요.
다른 옵션의 공부는 나중에 해도 괜찮을 것 같아요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      @Column(nullable = false)
이 애노테이션은 title에 붙여주기 위함인가요?

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
만약 위의 `Column` 애너테이션을 붙여주기 위함이라면 떼줍시다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        return writer.getId() == suggestedWriterId;
이것도 `User`에 메서드를 추가해서 해결해봅시다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +    }
👍 👍👍👍

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    Logger logger = LoggerFactory.getLogger(QuestionsController.class);
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(QuestionsController.class);
    
    @Autowired
    private QuestionRepository questionRepository;
```

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
저라면 `HomeController` 정도를 만든 다음에 이곳으로 redirect 되도록 구현해볼 것 같습니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    @GetMapping("/questions/modify/{questionId}")
```suggestion
    @GetMapping("/questions/{questionId}/modify-form")
```
정도가 적당할 것 같네요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    @PutMapping("/questions/modify")
```suggestion
    @PutMapping("/questions/{questionId}")
```

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +                                 Model model, HttpSession session) {
요거 어떻게 동작하는거죠? 신기하네요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
private 메서드가 나오면, 한 번 클래스를 분리해야 할 때가 아닌지 고민해봅시다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
여기도 `orElse(null)`을 사용하는데 지양해주세요!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/User.java
> +    private long id;
왜 Wrapper Type에서 primitive Type으로 변경해주셨나요?

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    Logger logger = LoggerFactory.getLogger(UsersController.class);
여기도 다른 곳 코멘트 참고하셔서 변경 반영해주세요!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @GetMapping()
위하고 다른 형태네요. 일관성을 지키는 것도 중요하다고 생각해요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +        logger.info("user created : " + createdUser.getUserId());
```suggestion
        logger.info("user created : {}", createdUser);
```

또는 createdUser.getUserId() 해주셔도 돼요.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @GetMapping("/modify")
```suggestion
    @GetMapping("/modify-form")
```

REST API 설계시 동사는 지양해줍시다!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @PutMapping("/modify")
```suggestion
    @PutMapping("")
```

url과 메서드가 중복되어 제거요청 드립니다!

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @PostMapping("/login")
이런 경우는 동사를 사용할 수 밖에 없어서 예외 입니다!
혹시 궁금해하실까봐 달아두어요~

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +            return "redirect:/users/loginForm";
어디는 하이픈을 사용하고 어디는 camelCase네요.
혹시 NAS만의 규칙이 있었을까요?

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @GetMapping("/logout")
과연 `GetMapping`을 사용하는게 맞을까요?

https://stackoverflow.com/questions/3521290/logout-get-or-post

한 번 쯤 생각해보면 좋은 문제입니다.

2021-03-10 17:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/SessionUtil.java
> +    }
👍

2021-03-10 17:10 UTC, ksundong commented on src/main/resources/templates/qna/form.html
> +                <input class="form-control" disabled id="writer" name="writerId" placeholder="글쓴이" value="{{loginUser.userId}}"/>
👍

2021-03-10 17:10 UTC, ksundong commented on src/main/resources/templates/qna/modify-form.html
> +{{> base}}
여기 통행금지 표시가 붙었네요.

https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
이곳 참고하셔서 설정 반영해주세요.

만약 설정되어 있으시다면 엔터 한 번 입력해주세요!

2021-03-10 17:10 UTC, ksundong commented on src/main/resources/templates/qna/show.html
> +                        <a class="article-header-time" href="#" title="퍼머링크">
`#`의 사용은 최근에는 지양하는 편입니다!

2021-03-11 07:48 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    @JoinColumn(foreignKey = @ForeignKey(name = "fk_answer_writer"))
넵 맞습니다 ㅋㅋ. 이렇게 써주니까 자동으로 외래키 제약조건이 생기는 것 같았는데 정말 신기했어요!
```
Hibernate: 
   
    alter table answer 
       add constraint fk_answer_writer 
       foreign key (writer_id) 
       references user
```
이렇게 로그가 출력되더라구요 ㅋㅋ. 이거보니까 SQL공부를 빨리 해야겠다는 생각이 들었습니다 . 😆 
스프링은 어떤 분야라도 지식이 얕으면 따라가는 것 조차 힘든 것 같아요.

빨리 SQL첫걸음 책을 때야겠어요 😄

2021-03-11 07:48 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
앗 그렇군요! 이 부분 반영하도록 하겠습니다!

2021-03-11 07:49 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
그런데 이런식으로 `@Entity`어노테이션을 붙인 클래스를 따로 부르는 이름이 있나요?
엔티티클래스? 이렇게 부르면 될까요?

2021-03-11 07:51 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    @Column(nullable = false, length = 20)
복사 붙여넣기한게 여기서 딱 걸렸네요 ㅋㅋ 😆 

안 충분할 것 같아요ㅎㅎ 이것도 적절한 `length`값을 갖도록 수정해서 커밋하겠습니다!

2021-03-11 07:54 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    public boolean isMatchingWriter(User suggestedWriter) {
그렇군요... 이 값이랑 같은지 제안했다는 의미로 suggested를 앞에 붙였는데, 제 의도랑은 다른 의미를 갖는 것 같아요.
아무래도 이렇게 쓰면 추천작가? 쯤으로 해석되는 것 같네요 😆 이게 아니었는데 ㅋㅋ

그냥 writer라고 하거나 anotherWriter쯤으로 이름을 지어주는게 무난할 것 같네요! 
이렇게 수정해서 커밋하도록 하겠습니다!

2021-03-11 07:55 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +        return writer.isMatchingId(suggestedWriter.getId());
`속성을 전달하기보다 객체를 전달하자` 명심하겠습니다!

2021-03-11 07:58 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
그렇네요 ㅋㅋ 타입은 LocalDateTime인데 변수명은 Date라고만 되어있으니 오해하기 좋은 변수명인 것 같아요!
스프링도 어려운데 변수 이름짓는것도 엄청 어렵네요 ㅎㅎ
이 부분도 수정해서 다시 커밋하겠습니다!

2021-03-11 08:47 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    AnswersRepository answersRepository;
[여기보고 따라해봤어요](https://yaboong.github.io/spring/2019/08/29/why-field-injection-is-bad/)
와우 생성자에다가 써주기만 했는데도 Repository객체가 주입되었어요! 
`@AutoWired`도 엄청 신기했는데 이것도 되게 신기하네요 ㅋㅋ

`생성자를 통해서 주입하니까 final을 쓸 수 있다` 이 점이 좋은 것 같아요.

변수 선언위치 외에는 생성자에서만 레퍼런스 변수를 초기화할 수 있으니까, 생성자를 통해서 주입하면 final을 쓸 수 있어서 좋다! 이렇게 이해했습니다!

2021-03-12 06:54 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        Question targetQuestion = questionRepository.findById(questionId).orElse(null);
이참에 Optional을 조금 공부해서 적용해봤어요!
코멘트 달아주신 내용이랑, K님의 코드를 참고해서 `orElseThrow()`를 사용해서 구현하는쪽으로 바꿨어요
이렇게하니까 중복된 코드도 많이 제거되고, 무엇보다 null값을 조건문으로 핸들링하기보다, Exception으로 대신 처리할 수 있게 되었습니다. 또 Exception을 핸들링하는 컨트롤러? 를 만들어서 처리해주니까, Question컨트롤러같은 애들의 부담이 좀 줄어드는 것 같아서 작업하기도 편하고 좋네요!

2021-03-12 06:55 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        answersRepository.save(answer);
이 부분은 어떻게 고쳐볼까 하다가 Answer의 생성자를 하나 더 추가하는걸로 수정했어요!
생성자에서 targetQuestion, sessionUser까지 다 받아서 처리하도록 수정해서, 책임을 Answer클래스로 넘겼습니다.

2021-03-12 07:02 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        }
Optional과 ExceptionHandler를 사용해서 해결했어요!
사실 이 부분은 팀원분의 코드를 거의 배끼다시피 해서 해결한거라 조금 부끄럽긴 한데, 진짜 좋은 방법인 것 같아요.
가령 getSessionUser메서드를 호출했는데 세션에 로그인된 유저정보가 없다면, NoLoginUserException가 발생하도록 했습니다. 그러면 `@ControllerAdvice`어노테이션을 달고 있는 `ControllerExceptionHandler`클래스의 `handleNoLoginUserException`메서드가 예외를 처리하도록 했구요. 위의 중복코드와 비슷한 null처리하는 코드도 같은 방식으로 처리해서, 컨트롤러에 지저분하게 붙어있던 조건문 코드블록들을 거의 다 제거했습니다.

2021-03-12 07:06 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +    private List<Answer> answers;
넵!

2021-03-12 07:08 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      @Column(nullable = false)
`@Column(nullable = false)`말씀이시죠? 네, title은 비어있으면 안된다고 생각해서 nullable이 false가 되어야 할 것 같아요.

2021-03-12 07:11 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        return writer.getId() == suggestedWriterId;
``` java
public boolean isMatchingWriter(User anotherWriter) {
```
이런식으로 바꾸니까 호출하는 쪽에서 getter메서드를 쓰는 일이 줄어드니까, 코드의 가독성이 좀 더 나아지는 것 같네요 ㅎㅎ

2021-03-12 07:26 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
Home컨트롤러를 만들고, Question컨트롤러로 리다이렉트하도록 수정했습니다!
그리고 Questions에서 루트패스가 빠져서, 여기서도 RequestMapping을 쓰도록 수정했습니다!

2021-03-12 08:31 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/User.java
> +    private long id;
이 부분은 별 생각없이 Question처럼 프리미티브 타입으로 바꿔줬어요. 한번 찾아보니까 Nullable? 을 표현할 수 있도록 Wrapper타입으로 해주는게 좋다는 것 같아요. 엔티티 클래스의 ID는 다시 Wrapper타입으로 바꿔주도록 하겠습니다!

2021-03-12 08:40 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @GetMapping()
`로깅도 일관성을 지키자!` 명심하겠습니다!

2021-03-12 08:40 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
기왕 Optional을 쓰게 된 만큼 null로 인한 문제가 없도록 주의하겠습니다!

2021-03-12 08:49 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +                                 Model model, HttpSession session) {
questionId로 질문객체를 찾고, 로그인된 유저의 질문객체인지 검사한다음, 
newTitle, newContents로 업데이트해주도록 구현했어요!
혹시 구현이 어색하거나 잘못된 부분이 있을까요?

2021-03-12 08:50 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +        logger.info("user created : " + createdUser.getUserId());
오 신기하네요! 로거가 생각한것보다 똑똑한 친구같네요

2021-03-12 08:50 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @GetMapping("/modify")
넵 알겠습니다!

2021-03-12 08:50 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @PutMapping("/modify")
넵!

2021-03-12 08:52 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +            return "redirect:/users/loginForm";
html은 하이픈을 이용해서 이름을 지어주려고 했는데요, 정작 loginForm 이렇게 썼네요 ㅠㅠ
수정해서 다시 커밋하겠습니다!

2021-03-12 08:55 UTC, Malloc72P commented on src/main/resources/templates/qna/modify-form.html
> +{{> base}}
설정했습니다! 감사합니다!

2021-03-12 08:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    private LocalDateTime reportingDate;
보통 그냥 Entity라고 부릅니다~

2021-03-12 08:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    AnswersRepository answersRepository;
넵 그정도만 이해하셔도 충분합니다.

2021-03-12 08:59 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +        answersRepository.save(answer);
그것도 괜찮은 방법이네요! 👍

2021-03-12 09:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      @Column(nullable = false)
밑의 리뷰까지 참고해주세요~

2021-03-12 09:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +                                 Model model, HttpSession session) {
제가 위에 제안드린 부분을 참고해보세요 ㅎㅎ

2021-03-12 09:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @GetMapping()
로깅 얘기 말구 `GetMapping()`에 대한 얘기 였어요 ㅎㅎ

2021-03-12 09:18 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @PostMapping("/login")
ㅋㅋ 그렇군요! 알려주셔서 감사합니다!

2021-03-12 09:24 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    @GetMapping("/questions/modify/{questionId}")
REST API의 URL 규칙?이라고 해야할까요? 이 부분도 공부해볼 필요가 있겠네요!
이 부분은 `@GetMapping("/{questionId}/modify-form")` 이렇게 수정했습니다!

2021-03-13 03:17 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
요건 어떻게 할지 고민하다가 `@PostMapping("/questions/{questionId}/answers")`를 `QuestionController`로 옮겼어요! `Answer`를 만드는거긴 한데, `Question`에 종속되니까 이렇게 해도 괜찮지 않을까 싶어요.

2021-03-13 04:34 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
>      @GetMapping()
아 ㅋㅋ 제가 착각했네요 ㅋㅋㅋ 저번에 코드리뷰를 반영하면서 `@GetMapping()`같이 비어있는괄호를 다 지워줬다고 생각했는데 남아있었네요! 다시 한번 검사해봐야겠습니다!

2021-03-13 04:39 UTC, Malloc72P commented on src/main/resources/templates/qna/show.html
> +                        <a class="article-header-time" href="#" title="퍼머링크">
아직 매핑시켜줄 URL이 없어서 평소 하던대로 `#`을 붙였던건데, 이게 문제가 될 수 있겠네요! 찾아보니까 스크롤을 맨 위로 올려버리는 문제가 있어서 쓰는사람이 많이 불편해할 수 있겠다는 생각이 들었어요. 대신 `javascript:;`을 쓰니까, URL이동도 없으면서 스크롤을 맨 위로 올려버리지 않으니까 좋은 것 같아요!

2021-03-13 04:40 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    Logger logger = LoggerFactory.getLogger(UsersController.class);
비어있는 괄호 말씀하시는거 맞죠? ㅎㅎ 반영해서 다시 커밋하겠습니다!

2021-03-13 04:50 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    Logger logger = LoggerFactory.getLogger(QuestionsController.class);
아하 ㅋㅋ 아무생각없이 접근제어자를 또 안줬네요 ㅋㅋ

이 부분도 반영하도록 하겠습니다!

저 근데 질문이 하나 있어요! 제안해주신 내용을 보면 static으로 해주셨는데요.
스프링의 컨트롤러는 싱글톤인가요? 검색해보니까 싱글톤인 것 같은데, 그러면 static으로 해주지 않아도 단 하나의 로거객체만 있으니까 static을 쓰는것과 안쓰는것이 차이가 없을 것 같아서요. 로거를 스태틱으로 선언할때의 장점을 여쭤봐도 될까요?

2021-03-13 05:28 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
아하 꼭 `@Column`어노테이션을 안붙여줘도 되는군요? 이 부분은 떼주는걸로 반영하겠습니다!

그런데 만약 title이나 contents에 `NOT NULL`속성을 주고 싶다면, 그때는 어떻게 하는게 좋을까요? 각각의 필드마다 어노테이션을 붙여줘야 하나요? 
``` java
    @Column(nullable = false)
    private String title;

    @Column(nullable = false)
    private String contents;

    @Column(nullable = false)
    private LocalDateTime reportingDateTime;
```
이렇게하면 코드중복이 많이 발생하는게 아닌가 하는 생각이 들어서요.  혹시 좋은 방법이 없을까요?

2021-03-13 05:30 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +                                 Model model, HttpSession session) {
`리소스에 대한 수정을 한다`라는 의미로, 매핑되는 URL을 `@PutMapping("/{questionId}")`로 수정했어요!
그리고 RequestMapping을 통해서 앞의 /questions를 붙이지 않도록 했습니다!

2021-03-13 05:44 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @GetMapping("/logout")
링크를 읽어봤는데요, 제가 맞게 이해한건지 잘 모르겠어요 ㅠㅠ
`2013년부터 브라우저는 제가 또 방문할 것 같은 웹페이지를 미리 fetch하니까, 로그아웃기능의 요청메서드를 GET으로 하면 문제가 될 수 있다` 라고 이해했는데 맞나요?
근데 정말 이렇다면 아무생각없이 GET을 요청메서드로 쓰면 좋지 않을 것 같다는 생각이 드네요! 이 부분도 수정해서 커밋하겠습니다!

2021-03-13 06:04 UTC, Malloc72P commented
안녕하세요! 코멘트 달아주신 내용을 참고해서 추가수정했습니다!
이번에 코멘트 받은 내용중 에서 진짜 중요하다고 생각되는걸 요약해보았어요! (물론 다 중요합니다 😄 )

* 속성을 전달하기보다 객체를 전달하자
* 생성자를 통해서 인젝션하자
* 공통된 부분은 @RequestMapping을 통해 추출하자
  * 만약 추출이 안된다면 URL매핑을 어색하게 한게 아닌가 의심해보고 고쳐보자
* orElseThrow()를 사용해서 구현하자. 옵셔널을 쓰는데 orElse(null)과 같이 null문제가 생기는 코드를 피하자.
* 객체에 너무 큰 책임을 주지 말자. 예를들면, 값을 업데이트하는 책임은 엔티티 클래스가 담당하도록 하자

리뷰 정말 감사합니다! 이렇게 꼼꼼하게 봐주시다니 정말 놀랐습니다 😆 

혹시 빠뜨리고 수정하지 않은 부분이 있다면 바로 피드백 해주세요! 바로 반영하갰습니다!

다시 한번, 리뷰 감사드려요! 😄

2021-03-13 14:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
일단은 요구사항은 `AnswerController`에 넣는 것이지만, 이 방법도 한 번 해보세요 ㅎㅎ

2021-03-13 14:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
이건 코드 중복이 아니에요 ㅎㅎ

2021-03-13 14:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
저렇게 `Column` 애노테이션을 생략해주시면 `nullable = true`가 됩니다. 참고해주세요.

2021-03-13 14:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
각각 붙여주고 싶으면 각각 달아주는 것이 맞습니다.

2021-03-13 14:04 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
이는 DB DDL을 보시면 아시겠지만, 선언이라서 붙여주는게 맞아요!

2021-03-13 14:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    Logger logger = LoggerFactory.getLogger(QuestionsController.class);
차이가 없을까요?
한 번 찾아보시는 걸 추천해요. 라고 쓰고 전에 찾아둔 것을 공유해드립니다.

https://stackoverflow.com/questions/8262310/any-reason-to-use-private-instead-of-private-final-static-on-the-logback-logger

2021-03-13 14:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/users/UsersController.java
> +    @GetMapping("/logout")
어떻게 하면 좋을까?를 고민해보세요 ㅎㅎ
과연 우리가 이렇게 하는게 맞나? 하는 고민은 항상 가지는 것이 좋습니다.
리뷰도, 100% 신뢰하지 마시고, 꼭 생각해보세요.

2021-03-13 15:44 UTC, ksundong approved these changes
안녕하세요! NAS 리뷰어 Dion입니다!!
피드백 사항을 수정해주시느라 고생많으셨어요.
이제 다음 단계를 진행하셔도 될 것 같습니다!! 고생하셨습니다~

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    }
생성자가 3개나 정의될 필요가 있었나요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    public String handleUnauthorizedAccessException() {
가급적이면 예외를 받아서, 예외에 대한 정보를 사용해주세요~

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/answers/AnswerNotFoundException.java
> +public class AnswerNotFoundException extends RuntimeException {
왜 `RuntimeException`을 상속해주셨나요?
`CheckedException`과 `UncheckedException`의 차이는 무엇인가요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/home/HomeController.java
> +    public String onRootRequest() {
네이밍 좀 더 고민해보세용~

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        return writer.getId() == anotherWriter.getId();
`getter`없이 속성에 접근 할 수 있습니다.

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        }
그냥 비교 안하고 덮어 씌우는 건 어때요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    private final QuestionRepository questionRepository;
왜 떨어져 있는건가요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +        logger.info("question created " + newQuestion);
```suggestion
        logger.info("question created {}", newQuestion);
```

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +        logger.info("question created " + newQuestion);
로거에서 문자열 + 연산은 주의해줍시다!

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    public String createAnswer(@PathVariable("questionId") long questionId, String answerContents,
AnswerController가 있는데 왜 여기로 왔을까요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +        model.addAttribute("numberOfAnswers", foundQuestion.getSizeOfAnswers());
65번 라인 꼭 model에 안넣어줘도 될 것 같은데... 아닌가요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +@HandlebarsHelper
`@Component` 가 과연 필요한가요?

2021-03-13 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +    DateTimeFormatter myFormatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
여기엔 접근 제어자가 없네요?

2021-03-13 15:44 UTC, ksundong commented on src/main/resources/data.sql
> +        {ts '2021-03-12 18:23:32'},
오 이런 형식은 어디서 아셨나요?

2021-03-14 02:39 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    }
정리하는 편이 좋겠네요 ㅋㅋ 예전에 쓰던건 지우도록 하겠습니다!

2021-03-14 02:40 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    public String handleUnauthorizedAccessException() {
그러는 편이 나중에 디버깅할때 더 좋겠네요! 감사합니다!

2021-03-14 06:01 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/answers/AnswerNotFoundException.java
> +public class AnswerNotFoundException extends RuntimeException {
실은 아무생각없이 나만의 커스텀 `Exception`은 무조건 `RuntimeException`을 상속해서 만드는거겠지? 라고 생각해서 이렇게 했습니다 ㅋㅋㅋㅋ 😆 코멘트 달아주신걸 보고 아 이거 그냥 넘기면 안되는 거였구나! 라는 느낌이 들어서 공부했습니다

`Checked`와 `Unchecked`의 차이는 발견시점인 것 같네요. `Checked`는 컴파일 시점에서 체크되는 예외이고, 발생 우려가 있으면 반드시 try/catch 구문으로 감싸줘야 하고, `Unchecked`는 런타임에 체크되는 예외이고, 반드시 try/catch구문으로 감싸줄 필요는 없는 예외인 것 같네요.

`AnswerNotFoundException`의 경우, 런타임에 발생하는 예외이므로, `Unchecked Exception`에 해당하는 `RuntimeException`을 상속해줘야 할 것 같습니다!

2021-03-14 06:02 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/home/HomeController.java
> +    public String onRootRequest() {
아 ㅋㅋ 이름짓는거 진짜 어려워요 ㅋㅋ 좀 더 좋은 이름을 지어줄 수 있도록 더 고민해볼께요!

2021-03-14 06:07 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        return writer.getId() == anotherWriter.getId();
아 맞네요 ㅋㅋㅋ `isMatchingId()`라는 메서드를 만들어놓고 정작 이렇게 썼네요 ㅋㅋ
전 진짜 갈길이 먼 것 같습니다 ㅋㅋㅋ

2021-03-14 06:11 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
> +        }
실제로 실행된 sql문을 확인해보니까 title이나 contents가 바뀌건 안바뀌건 update쿼리는 같군요. 저렇게 조건문으로 검사해서 바뀌었을때만 덮어쓰도록 한다고 해서 나아지는게 없었겠네요. 코
멘트 달아주신것 처럼 그냥 덮어쓰는 편이 더 나을 것 같아요!

2021-03-14 06:16 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    private final QuestionRepository questionRepository;
로거랑 리포지토리랑 구분해서 선언해주려고 한줄 띄웠어요! 😄 
가독성에 도움이 되지 않을까 해서요.

오히려 역효과인가요? ㅋㅋㅋ

2021-03-14 06:17 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +        logger.info("question created " + newQuestion);
아 이게 단순히 편의성문제가 아니라 연산문제가 있었군요! 주의하겠습니다!

2021-03-14 06:22 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    public String createAnswer(@PathVariable("questionId") long questionId, String answerContents,
루카스에 이런 요구사항이 있었어요.

>  * Question에 종속되어 있는 Answer 목록을 조회하는 메소드를 AnswerRepository에 추가한다.
>    * findByQuestionId(questionId)와 같은 메소드를 추가한다.
>  * 답변 기능 구현을 담당할 AnswerController를 추가하고 구현한다.
>  * 답변은 질문에 종속되기 때문에 URL 매핑을 다음과 같이 할 수 있다.
>    * /questions/{questionId}/answers/{id}

답변기능을 `AnswerController`에 하라고 하긴 했지만, URL은 질문에 종속된다고 `/questions`로 하라고 해서 `QuestionsController`로 이사가게 되었어요. `AnswerController`의 `RequestMapping`을 `/answers`로 해야 한다고 생각했기 때문이예요.

그런데 지금 생각해보니까 그냥 `AnswerController`의 `RequestMapping`이 `/questions`이면 되는 문제였네요...?
왜 이제서야 생각이 난걸까요 ㅠㅠ 다음작업때 다시 돌려놔야겠네요 😆

2021-03-14 06:23 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +        model.addAttribute("numberOfAnswers", foundQuestion.getSizeOfAnswers());
아 맞네요 저거 그냥 템플릿에서 `question.answers.length`하면 될 것 같네요! 피어리뷰때 들었던 것 같은데 깜빡하고 그대로 뒀나봐요.

2021-03-14 06:25 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +    DateTimeFormatter myFormatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
아예 모니터에 포스트잇을 붙여놔야겠습니다 ㅋㅋ
`접근 제어자 잊지말 것!` 이렇게요 ㅋㅋㅋ
이것도 고치겠습니다!

2021-03-14 06:40 UTC, Malloc72P reviewed
d

2021-03-14 06:44 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +@HandlebarsHelper
생각없이 따라친게 여기서 들통나네요 ㅋㅋ
혹시? 하고 `@HandlebarsHelper`를 `Ctrl + LMB`하니까 요렇게 나오네요
``` java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Component
public @interface HandlebarsHelper {
}
```

이미 컴포넌트 어노테이션이 붙어있었군요 ㅋㅋ
고치도록 하겠습니다! 감사합니다!

2021-03-14 06:44 UTC, Malloc72P commented on src/main/resources/data.sql
> +        {ts '2021-03-12 18:23:32'},
ts말씀하시는거라면, [구글링](https://stackoverflow.com/questions/14138532/h2-database-string-to-timestamp)하다가 우연히 알게되었습니다!

2021-03-14 08:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/answers/Answer.java
> +    }
네 필요한 생성자는 얼마든지 만들어줘도 되지만, 필요없는 생성자의 경우에는 제거해주는 편이 좋겠습니다.

2021-03-14 08:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    public String handleUnauthorizedAccessException() {
디버깅 할 때에도 좋고, 반환을 해줄 때에도 예외에 담긴 정보를 그대로 반환하거나, 가공해서 반환하는 것도 도움이 많이 됩니다.

2021-03-14 08:04 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/answers/AnswerNotFoundException.java
> +public class AnswerNotFoundException extends RuntimeException {
네 이 부분은 Spring을 좀 더 공부하다보면 나오는데요.
이 때, 구분을 잘 하셨으면 좋겠습니다. `CheckedException`, `UncheckedException`은 자바의 개념이고
이후에 등장할 Transaction Rollback 시점에 대한 개념은 Spring의 개념입니다.
CustomException도 CheckedException일 경우가 얼마든지 있을 수 있고, 중요한 개념이라 꼭 나중에 다시 한 번 보세요~

2021-03-14 08:05 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    private final QuestionRepository questionRepository;
이를 구분지어줄 필요가 있는지도 생각해보면 좋을 듯 해요.
의도적으로 띄어주었다면 나쁘지 않다고 생각합니다 ㅎㅎ
다만 저는 아예 static으로 두어서 구분짓는 편이에요.

2021-03-14 08:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    public String createAnswer(@PathVariable("questionId") long questionId, String answerContents,
간다면 모두 같이 이동해야하죠 ㅎㅎ
혼자만 이사하면 안됩니다. ㅎㅎ

2021-03-14 08:11 UTC, ksundong commented on src/main/resources/data.sql
> +        {ts '2021-03-12 18:23:32'},
그렇군요. 날짜/시간 관련해서는 ANSI SQL 표준이 존재하지 않는 것 같네요.
신기한 문법 잘 봤습니다 ㅎㅎ

2021-03-14 08:12 UTC, merged

2021-03-14 08:31 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/Question.java
>      private String contents;
앗 그렇군요 ㅋㅋㅋ 알려주셔서 감사합니다!

2021-03-14 08:41 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    Logger logger = LoggerFactory.getLogger(QuestionsController.class);
어렵네요 ㅋㅋㅋ 코멘트로 남겨주신 링크를 찾아봤는데, 어려워요 ㅋㅋㅋ
아무래도 static 로거를 쓰면 멤버 로거로 했을때보다 CPU나 메모리 상에서 성능이점이 있다는 것 같네요! 그런데 왜 성능상의 이점이 있는지에 대한 설명은 잘 이해가 가지를 않아요 ㅠㅠ. 좀 더 공부해보고 왜 성능차이가 발생하는지 공부해봐야겠네요!
이건 나중에 강해져서 돌아와서 해치우겠습니다 ㅋㅋ 🔪

2021-03-14 08:42 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    public String handleUnauthorizedAccessException() {
그렇군요! `발생시킨 예외에 담긴 정보를 이용한다` 이것도 더 공부해야겠네요!

2021-03-14 08:44 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/answers/AnswerNotFoundException.java
> +public class AnswerNotFoundException extends RuntimeException {
이게 자바에서의 예외에 대한 개념도 있고, 스프링에서의 예외에 대한 개념도 있는거였군요! 트랜잭션 처리에 대해 공부하면서 예외에 대한 공부도 빠뜨리지 말고 공부하면 좋겠네요! 정말 감사합니다!

2021-03-14 08:46 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    public String createAnswer(@PathVariable("questionId") long questionId, String answerContents,
혼자만 이사한다는 표현이 왤케 재밌죠 ㅋㅋㅋㅋ
빨리 가출한 메서드를 잡아와야겠네요 ㅋㅋㅋ

2021-03-14 08:47 UTC, Malloc72P commented on src/main/resources/data.sql
> +        {ts '2021-03-12 18:23:32'},
SQL첫걸음이란 책을 읽으면서 표준 SQL에서 벗어난걸 `방언`이라고 표현하던데, 이것도 어떻게 보면 방언이라고 할 수 있을 것 같아요 ㅋㅋ