[Pyro] 미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #46
Opened 2021-03-09 12:33 UTC by ghojeong

자바지기님의 영상을 그대로 따라했습니다.
findOne 을 시도하니, PK 로 지정한 Long 타입의 id 로 조회할 수 없던데,
무엇을 잘못했는지 잘 모르겠습니다.
findById 로 대신 하려다가, 아직은 Exception 에 대한 핸들러를 추가하지 않아서,
getOne 으로 조회를 하도록 임시 처리했습니다.
혹시 이렇게 JPA 조회를 할 때에, Optional 처리를 위한 정석적인 방법이 있는지 여쭈어봅니다.
그냥 단순하게 findById().get() 을 하면 getOne 메서드와 별 차이가 없어보여서요.

비밀번호 확인 기능은 굳이 서버를 경유하지 않고, 프론트에서 자바스크립트를 통해 구현했습니다.
plain 자바스크립트 싫어요 흑 😞

2021-03-10 05:20 UTC, ghojeong commented
리뷰가 늦어져서, ATDD 관련된 환경설정 및 테스트 코드를 추가했습니다.
오버 엔지니어링이 된 것 처럼 보인다면, 이게 다 저를 심심하게 만든 리뷰어님 탓입니다.

2021-03-11 01:21 UTC, ghojeong commented
@ksundong
아무나 코드 리뷰 좀 해주세요!!

2021-03-11 07:09 UTC, honux77 commented on src/main/java/com/codessquad/qna/QnaApplication.java
>  public class QnaApplication implements WebApplicationInitializer {
요걸로 하셨군요. 강의자료에 나와있는 서블릿필터 옵션으로 해도 됩니다.

2021-03-11 07:10 UTC, honux77 commented on src/main/java/com/codessquad/qna/common/BaseTimeEntity.java
> +}
이거 직접 만드신 이유가 있을까요?

2021-03-11 07:11 UTC, honux77 commented on src/main/java/com/codessquad/qna/common/MvcConfig.java
>      }
깃헙은 이런거 그냥 github.com/join  이런 식으로 간단 URL로 구성했더라구요. 저도 나쁘지 않아 보였어요.

2021-03-11 07:59 UTC, honux77 requested changes
크게 이상한 건 없고, 잘 짰어요. 다만 사소한 것들 value= 이라던가, 메소드명에 _ 사용한 것 이런거 수정해 주시고,  나머지 코멘트에 대해서는 고민해 주세요.
익셉션 핸들러는 따로 빼면 좋을 것 같은 느낌?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/common/RootController.java
>      }
이경우는 리다이렉트보다 뷰를 호출해 주는게 좋겠네요.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/common/RootController.java
>      }
메소드 이름도 home() 정도면 무난하지 않을까요? 자바에서는 스네이크케이스는 일반적으로 잘 사용하지 않습니다.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +@Transactional
transactional을 적용한 이유를 알 수 있을까요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +@Transactional
안 써도 돌아가는데 문제가 생기지 않을 것 같아서요.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +public class QuestionService {
서비스의 역할은 복잡한 비지니스 로직의 구현에 있는데 지금 단순한 구현을 감싸느라 오히려 복잡도가 증가한 느낌입니다.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
그냥 Iterable<Question> 으로 할 수 있는 게 더 복잡해진 느낌이에요. Request와 Response 객체는 무엇을 위해 필요할까요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        Question question = questionRepository.getOne(id);
findById(id).orElse() 등을 활용해 주시는 건 어떨까요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +public class Question extends BaseTimeEntity {
BaseTimeEntity가 여기서 사용되는군요.
1) 추가적으로 더 사용하는 곳이 있을까요?
2) 그냥 처음부터 Question 안에 필드로 존재하는 것에 비해 장점은 무엇일까요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    private String writer;
User writer로 사용하면 어때요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/dto/QuestionRequest.java
> +public class QuestionRequest {
이 클래스를 적용해서 얻은 장점은 무엇일까요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
> +    @PostMapping(value = "create")
```suggestion
    @PostMapping("/create")
```
취향이겠지만 이게 더 낫지 않나요?

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
> +        questionService.saveQuestion(QuestionRequest.of(question));
여기서 보니까 근데 또 깔끔하니 좋네요 ㅋㅋㅋ. 이래서 짧은 코드도 서비스를 만드는 건가 봐요.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
> +        return ResponseEntity.notFound().build();
이게 여기가 적당한지 모아서 다른 곳에 모아서 쓰는게 좋은지 한번 생각해 보세요. (생각만)

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +    }
User나 Question을 넣을 때 유효성 겁사 같은게 있으면 좋을 것 같은데 없네요. 비어 있는 값 체크 같은 거 해 주면 좋을 것 같아요.

2021-03-11 07:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +    }
그러고 보니 User Entity에 컬럼 속성으로 있군요. 그럼 없어도 괜찮으려나...

2021-03-11 10:38 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
> +    @PostMapping(value = "create")
헙! 이게 훨씬 좋아보이네요. Spring 처음 써보는 지라, 이런 문법이 가능한지 잘 몰랐습니다.

2021-03-11 10:44 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/RootController.java
>      }
자바에서는 항상 낙타 케이스가 될 수 있도록 주의하겠습니다.

2021-03-11 10:51 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +@Transactional
아직 학습 중이는 하지만, transactional 을 적용하면, ACID 와 관련된 설정을 할 수 있다고 이해했습니다.
지금은 대부분 readonly 설정만 하였지만, 추후에 update 혹은 delete 작업을 수행하게 되었을 때, rollback 과 관련된 설정을 해보고 싶어 욕심을 내었습니다.
지금은 Transactional 을 안 써도 돌아가는데, 전혀 문제가 없는게 맞기는 합니다.
오버 엔지니어링 같아서, Transactional 은 삭제하겠습니다.

2021-03-11 10:52 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        Question question = questionRepository.getOne(id);
orElseThrow 를 통해 커스텀 Exception 을 던질 수 있도록 하겠습니다.

2021-03-11 11:02 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +public class Question extends BaseTimeEntity {
> 1. 추가적으로 더 사용하는 곳이 있을까요?

아직 미션 2 이후의 내용을 전혀 학습하지 않아서, 더 사용할 곳이 어딘지는 잘 모르곘습니다.
(요구사항을 모른채 제 욕심을 제외하면, 댓글 엔티티를 만들때 추가로 사용하고 싶습니다.)
다만 어떤 엔티티가 추가가되었던 createdDate 와, modifiedDate 정보는 추후 기록할 로깅 정보와의 비교를 위해서라도 사용할 수 있도록 하는게 좋지 않을까 하고 생각을 하였습니다.

> 2. 그냥 처음부터 Question 안에 필드로 존재하는 것에 비해 장점은 무엇일까요?

User 에 createdDate 와 modifedDate 를 만들지 않고, Question 안에만 필드로 만드는 방법도 존재합니다.
그럼에도 BaseTimeEntity 를 따로 만들게 된 것은 결국 확장성 때문인 것 같습니다.
createdDate 와, modifiedDate 는 어떤 엔티티가 되었든 자주 쓰일 것 같다고 예상되는지라,
언젠가 엔티티가 추가되었을 때 쉽게 활용할 수 있도록 BaseTimeEntity 로 분리했습니다.
(현재의 요구사항에는 없더라도, 나중의 요구사항이 바뀔지도 모르는 경우를 쓸데없이 너무 고민하는 것 같기도 하네요.)

2021-03-11 11:03 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
> +        return ResponseEntity.notFound().build();
ExceptionHandler 와 관련된 부분은 컨트롤러와 분리하도록 하겠습니다.

2021-03-11 11:06 UTC, ghojeong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +    }
넵 비어있는 값 같은 경우에는 Entity 에 컬럼 속성을 통해 전부 막아 놓았습니다.
만약 발생하는 Exception 에 대한 Handler 가 부재함을 지적하신 거라면, Handler 를 추가하고 그에 관한 테스트 코드도 같이 작성해 놓겠습니다.

2021-03-11 11:08 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +public class QuestionService {
맞습니다. 지금은 서비스의 역할이 딱히 없는지라, 쓸데없이 복잡한 것은 맞는 것 같습니다.
원래는 서비스 전혀 없이 컨트롤러만 있는채로 구현 후 PR 을 올렸었는데, 리뷰가 너무 늦어져서 Service 를 학습하는 겸 추가하게 되었습니다.
기왕 구축해 놓은 것, 학습을 위해서라도 이 Service 와 Controller 의 분리는 유지하도록 하겠습니다.

2021-03-11 11:21 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
> Request와 Response 객체는 무엇을 위해 필요할까요?

Request 와 Response 를 추가하게 된 이유는 Acceptance Test 때문이었습니다.
ATDD 를 추가로 학습중인데, 인수 테스트는 결국 "주어진 Request (given, when) 에 대해서 어떤 Response 가 받아와졌는가(then)" 에 대한 테스트라고 이해했습니다.
그러려면 Request 와 Response 를 별도의 클래스로 정의할 필요가 있다고 이해했습니다.
지금은 html 문서를 반환하고 있지만, 제대로 json 과 같은 정보를 반환하는 백엔드 API 를 만들게 되면,
정의된 Request 와 Response 를 통해 Request 와 Response 내부의 데이터 값 까지도 테스트 할 수 있다고 생각해서 추가했습니다.
아쉽게도 지금은 html 이 반환되고 있기 때문에 statusCode 만을 테스트 하고 있습니다.

2021-03-11 11:23 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
> 그냥 Iterable 으로 할 수 있는 게 더 복잡해진 느낌이에요.

취향차이가 아닐까 개인적으로 생각하지만, 호눅스님이 팀장님이므로 팀장님 의견에 따르겠습니다.
Iterable 로 고치겠습니다.

2021-03-11 11:25 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/dto/QuestionRequest.java
> +public class QuestionRequest {
[위 코멘트 답변](#discussion_r592278294) 으로 같이 설명된다고 생각합니다.
지금으로써는 딱히 장점이 없는 오버 엔지니어링이라고 할 수도 있겠네요.

2021-03-11 11:26 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/BaseTimeEntity.java
> +}
혹시 직접 만들지 않고 할 수 있는 방법도 있나요?
이게 제가 공부했을 때 찾아낸 가장 쉬운 방법이라서 직접 만들었는데,
만들지 않고 더 쉽게 할 수 있는 방법이 있다면 알려주시면 감사하겠습니다.

2021-03-11 11:27 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/MvcConfig.java
>      }
""/users/form" 을 그냥 "/join" 으로 하는것 나쁘지 않군요.
반영하겠습니다.

2021-03-11 11:32 UTC, ghojeong commented on src/main/java/com/codessquad/qna/QnaApplication.java
>  public class QnaApplication implements WebApplicationInitializer {
헙 `spring.mvc.hiddenmethod.filter.enabled=true` 라고 루카스 강의 마지막에 나와있군요.
servletContext.addFilter 는 삭제하겠습니다.

2021-03-12 00:37 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
안 고쳐도 되는데요 ㅋㅋㅋ

2021-03-12 00:40 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    private String writer;
@honux77 
<img width="485" alt="스크린샷 2021-03-12 오전 9 36 10" src="https://user-images.githubusercontent.com/38595650/110874078-70ce0080-8316-11eb-959c-5ad539513ae4.png">

지금 여기서 막혀서 질문 드립니다.
본래 계획은 questions/form.html 에서 보내온 userId 를 QuestionService 에서 userRepository 를 사용해, 해당하는 User 를 가져와서, Question 도메인 객체를 생성한 후 save 하려는 계획을 가지고 있었습니다.
다만 이렇게 하니 ,'Basic' attribute type should not be 'Persistence Entity' 라고 뜨는데,
이런 에러는 어떻게 해결해야할지 모르겠어서 질문 드립니다.

데이터베이서 컬럼값으로 저장하려면, 저장 자체는 String userId 값으로 할 수 밖에 없지 않나 라는 생각으로 뒤죽박죽입니다.

2021-03-12 02:13 UTC, ghojeong commented
[User writer 로 사용하면 어때요?](#discussion_r592125542)

엔티티 안에 또다른 엔티티를 넣는 방법을 잘 모르겠는데, 도와주시면 감사하겠습니다.
현재 제 능력에서 수정할 수 있는 범위 까지는 전부 수정하였습니다.

2021-03-12 07:57 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    private String writer;
@honux77 
오늘 계속 공부를 하다보니 [Embedded](https://galid1.tistory.com/592) 라는 어노테이션을 알게 되었습니다.
이렇게하면 User 객체 정보를 컬럼으로 넣을 수는 있게 되지만,
Question 테이블 안에 User 와 관련된 컬럼들이 여러개 추가되는 것이므로,
"관계형" 데이터베이스의 장점을 살리지 못할 것 같다는 느낌을 받았습니다.

또다른 방법으로 [JoinColumn](https://www.baeldung.com/jpa-join-column) 이라는 것 또한 알게 되었는데,
JoinColumn 이 호눅스 께서 의도하신게 맞는지 여쭈어봅니다.

2021-03-12 08:58 UTC, honux77 commented
생각해 보니 User writer는 아마 나중 미션에 나올거에요. 지금 상태로 충분한 거 같아요. 수고하셨어요!

2021-03-12 08:58 UTC, merged