[K] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #5
Opened 2021-03-03 06:37 UTC by PizzaCola-K

# 배포 사이트

[https://safe-waters-28423.herokuapp.com/](https://safe-waters-28423.herokuapp.com/)

# UserController

- 회원가입 기능 구현

/users로 POST 요청을 보내면, User 객체로 받아, List에 저장합니다.

- 회원 목록 기능 구현

/users로 GET 요청을 보내면, User List로 users/list.html을 구성하여 보내줍니다.

- 회원 프로필 정보 보기

/users/{userId}로 GET 요청을 보내면, 그 유저의 정보를 보여줍니다.

- 회원 정보 수정

/users/{userId}/form 에 GET 요청을 보내면, 비밀번호를 제외한 원래 정보를 포함한 문서를 보냅니다.

/users/{userId}/update에 POST 요청을 보내면 컨트롤러에서 존재하는 유저인지, 현재 비밀번호가 변경 전 비밀번호화 일치하는지 확인하고 정보를 수정합니다.

# QuestionController
- 질문하기

/questions로 POST 요청을 보내면, Question 객체를 새로 만들어, id와 질문 시간을 추가하여 List에 저장합니다.

- 질문 목록

/로 GET 요청을 보내면 Question List를 이용하여 질문 목록을 구성하여 보내줍니다.

- 질문 상세보기

/questions/{id}로 GET 요청을 보내면 id에 맞는 질문을 찾아서 질문 상세 페이지를 보내줍니다.

# HTML 중복 제거

head, navbar, subnav, script 로 나누어, components 디렉토리에 두었습니다.

# 그 외

[handlebars Helper](https://jknack.github.io/handlebars.java/helpers.html)
[handlebars-spring-boot-starter helper](https://github.com/allegro/handlebars-spring-boot-starter#custom-helpers)
handlebars의 helper 기능을 이용하여, Question의 ZonedDateTime을 포맷에 맞는 String으로 변환하거나, 유저목록의 index를 row 번호로 변환합니다.

리뷰 감사드립니다.

2021-03-03 06:57 UTC, tmdgusya commented
와 helpers 라는 기능을 사용하면 index 도 자동으로 해주나보군요.. 하나 알아갑니다 K~

2021-03-03 07:07 UTC, PizzaCola-K commented
> 와 helpers 라는 기능을 사용하면 index 도 자동으로 해주나보군요.. 하나 알아갑니다 K~

helper는 구현해줘야합니다.

2021-03-04 00:22 UTC, wheejuni requested changes
첫번째 스프링 미션 진행하시느라 고생 많으셨습니다. 👍 
전반적으로 구현이 잘 되었고요, 사소한 피드백 몇 가지 남겨 보았는데요,
확인해 보시고 반영/추가질문 부탁드릴게요~

2021-03-04 00:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (!id.matches("[1-9]\\d*")) {
지금같은 단순한 애플리케이션에선 큰 문제가 되지 않을 수 있지만 정규식을 런타임에 분석하고 매치 여부를 판정하는 것은 꽤 연산력이 소모되는 작업입니다. 
정규식을 미리 분석해두고(컴파일해두고) 계속해서 재사용할 수 있는 `Pattern` 클래스에 대해 [학습](https://offbyone.tistory.com/400) 하시고 적용해주세요.

2021-03-04 00:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            model.addAttribute(question);
이 두 라인은 한줄로 합칠 수도 있겠네요.

```suggestion
            model.addAttribute(questions.get(questionIndex));

2021-03-04 00:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (userId.equals(user.getUserId())) {
`User` 에 아래와 같은 메소드를 구현해서, `.get()` 없이도 비교할 수 있게 해주세요.

```java
public boolean isMatchingUserId(String userId);

2021-03-04 00:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
시간대 변환의 필요성이 없을 경우엔 `LocalDateTime` 을 많이 사용합니다. 
`ZonedDateTime` 을 사용하신 특별한 이유가 있나요?

2021-03-04 00:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private String writer;
충분히 좋은 구현입니다만, `User` 를 담는 건 어떨까요?

2021-03-04 00:46 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
배포를 하니까 서버시간 기준으로 잡히더라구요. 그래서 ZonedDateTime을 사용해서 서울 시간 기준으로 잡았습니다.

2021-03-04 00:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
그러면 서버 시간을 수정해야 하는 건 아닐까요? Heroku에 시간대 옵션을 부여하는 방법이 있을텐데, 그렇게 해결해야 할 것 같네요.

2021-03-04 00:57 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
궁금한 것이 있는데, 접속하는 사용자마다 시간대가 다르면 서버에서는 어떤식으로 처리해주나요?

2021-03-04 01:19 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
> 그러면 서버 시간을 수정해야 하는 건 아닐까요? Heroku에 시간대 옵션을 부여하는 방법이 있을텐데, 그렇게 해결해야 할 것 같네요.

Heroku에 설정 확인해서 수정해보겠습니다!

2021-03-04 01:55 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (!id.matches("[1-9]\\d*")) {
Matcher에 find()하면 string의 일부분만 매칭이 되서 전체가 패턴에 맞는지를 확인하고 싶어서 저렇게 String의 matches를 사용했는데, Matcher에 전체 매칭하는 matches()가 있었네요!

2021-03-04 04:09 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private ZonedDateTime time;
접속하는 사용자마다 시간대가 다르면 당연히 서버 시간 기준으로 요청이 처리돼야겠죠. 그것이 서버의 역할이니까요.

2021-03-04 07:00 UTC, PizzaCola-K commented
리뷰해주신 것을 반영하였습니다!
1. QuestionController에서 미리 컴파일한 Pattern을 이용하여 정규표현식 매칭
2. ZonedDateTime 대신에 LocalDateTime 사용
3. User의 필드를 비교할 때 getter 대신에 User 내의 메소드를 사용하도록 수정
4. Question에서 writer를 String 대신에 User로 사용

여기서 2번은 서버시간 설정을 해서 서울 시간으로 나오도록 하였습니다.

그리고 4번은 단순히 Question에 User를 가지고 있게 하지 않고, UserController에서 추가했던 User와 연결할 수 있도록
- UserRepository를 만들어 UserController와 QuestionController에 의존성 추가
- 질문하기 폼에서 글쓴이에 userId를 입력하면 기존에 있는 유저를 찾아서 Question의 writer에서 찾은 유저를 참조
- 없는 유저면 익명 유저처럼 새 User를 생성해서 Question의 writer로 사용

하도록 하였습니다.

아직 DB연결이나 로그인 인증 후 상태 관리 등이 안되서 이상한 구현이 되긴 했습니다.

리뷰 부탁드립니다!

2021-03-04 11:59 UTC, wheejuni approved these changes
수고하셨습니다 👍

2021-03-04 11:59 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final UserRepository userRepository;
보통 `Repository` 를 바로 받기보다는 중간에 `Service` 를 두긴 하는데요, 뭐 아직은 괜찮아요.

2021-03-04 11:59 UTC, merged

2021-03-04 12:07 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final UserRepository userRepository;
그렇군요! 공부하겠습니다.