[ coco ] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #51
Opened 2021-03-10 08:05 UTC by ChoiGiSung

안녕하세요 백엔드반의 coco라고 합니다.

배포사이트
https://coco-springboot-qna.herokuapp.com/

놓친 부분이 많은 느낌이 들지만 잘 부탁드립니다.

궁금한 점이 있습니다.
userRepository에서 findById시 값이 없으면 예외를 터트리고 있습니다.
이게 옳바른 방법인지 궁금합니다.

이유는 login시에는 userId가 없으면 다른 곳으로 redirect를 해주고 있어서 
findById시에도 예외말고 다른 기능을 넣어야 하나 아님 잘못된 id에 접근은 예외 발생이 맞나
궁금합니다.

감사합니다.

2021-03-11 11:28 UTC, ksundong requested changes
안녕하세요. coco!! 리뷰어 Dion입니다.
3단계 미션을 진행하시느라 수고 많으셨습니다. 🎉 🎉 🎉
몇 가지 반영되지 않은 요구사항과, 생각해보셨으면 하는 내용들이 있어 **변경 요청** 드립니다.
참고하시고 수정해서 다시 리뷰요청해주세요!

## 미 반영된 요구 사항

- 다른 사용자의 정보를 수정할 수 없도록 한다.(이 때, 당연히 에러페이지 출력이 되면 안됩니다.)
- 질문 수정하기 기능이 미구현 되어있습니다.
- 질문 삭제하기 기능이 미구현 되어있습니다.

## 리뷰

전체적으로 깔끔하게 구현되어 있는 느낌입니다. 특히 사용의 플로우는 완벽하진 않지만, 조금 신경쓰셨다는 느낌은 받았습니다.
다만, 에러페이지가 그대로 노출되는 구간이 많아서 이 점은 아쉬웠습니다.
코드도 전반적으로 깔끔했고, 인상깊은 부분도 있었습니다.

아마 언급된 부분만 수정해주시면 충분히 다음단계를 진행하셔도 좋을 것 같습니다.
고생하셨습니다~ 궁금하신 점이나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론이 필요한 부분은 언제든 코멘트 남겨주세요!

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +@RequestMapping("/questions/{questionId}/answers")
👍

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private AnswerService answerService;
final로 바꿔주는 것이 좋겠습니다!

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```
이렇게도 되는데, 기본값이 무엇인지 한 번 알아보세요!

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.write(HttpSessionUtils.getUserFromSession(session), contents, questionId);
`HttpSessionUtils.getUserFromSession(session)`같은 경우에 저는 변수로 추출해서 읽기 좋게 만들어주는 편입니다.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        }
분기문을 사용하지 않고 처리하는 방법도 고민해보세요!!

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        User findUser = userService.login(userId, password);
그냥 `user` 정도여도 충분하지 않을까 싶어요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        session.setAttribute("sessionedUser", findUser);
"sessionedUser" 같은 경우 여러 군데에서 사용하기 쉽겠네요. 어떻게 처리해주는게 좋을까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +    @GetMapping("/logout")
logout이 get mapping인지 한 번 고민해보시길 바래요.
https://stackoverflow.com/questions/3521290/logout-get-or-post

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
공통된 처리가 반복되는 느낌이네요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PutMapping("/update")
```suggestion
    @PutMapping("/{id}")
```

`users/update` 는 뭔가 컬렉션 전체에 대한 변경의 느낌이 강하게 드네요.
그리고 url을 설계할 때는 되도록 동사가 등장하지 않도록 해주세요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime createDate;
```suggestion
    private LocalDateTime createDateTime;
```

DateTime 형이므로 이름에 그것이 드러나도록 해주는 것이 좋을 것 같습니다.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        question.getAnswerList().add(this);
`answerList`가 `null`인 경우에는 어떻게 될까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        question.getAnswerList().add(this);
`this`를 넣어주는 발상은 좋은 것 같아요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
가급적이면 `getter`는 `getter`대로 두고, `getFormattedDateTime()` 정도로 수정해보는게 어떨까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @OrderBy("id ASC ")
`OrderBy`를 넣어주신 이유는 무엇인가요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private LocalDateTime writeTime;
`writerTime`은 무슨 의미일까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
>      private String name;
```suggestion
    @Column(nullable = false, length = 20, unique = true)
    private String userId;

    private String name;
```

가독성을 위해서 이렇게 떼주세요!

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
요구사항은 `CrudRepository`를 사용하는 것이었는데요.
이것이 어떤 차이가 있는지 한 번 알아봅시다.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    User findByUserId(String userId);
`Optional`로 감싸서 반환하시는걸 추천드릴게요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        UserValidation.validUserInfo(writer);
```suggestion
        UserValidator.validUserInfo(writer);
```

이렇게 행위자의 느낌으로 작명하는게 더 좋은 것 같아요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        Question findQuestion = questionService.findById(questionId);
동사+명사 조합은 객체보단 메서드에 더 어울리는 네이밍이라고 생각됩니다.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
>          User DBUser = userRepository.save(user);
네이밍 컨벤션을 지켜주세요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
>  @Transactional(readOnly = true)
👍

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return null;
`null`을 리턴하는건 매우 주의해주세요.
가급적이면 하지 않았으면 좋겠습니다.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new IllegalStateException("자신의 정보만 수정 가능");
이건 재사용하기 힘들게 만드는 원인이 되겠네요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    public static final String USER_SESSION_KEY = "sessionedUser";
상수가 있었네요? 왜 활용을 해주지 않으신걸까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +        return true;
return sessionUser != null;

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/valid/UserValidation.java
> +//        validID(user.getId());
불필요한 주석은 바로바로 지워주세요.

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/valid/UserValidation.java
> +//        validID(user.getId());
`validate`가 더 맞지않을까요?

2021-03-11 11:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/valid/UserValidation.java
> +        if (userId.trim().isEmpty()) {
뭔가 반복되는 코드가 보이죠?

2021-03-11 11:28 UTC, ksundong commented on src/main/resources/application.properties
> +handlebars.expose-session-attributes=true
통행금지 표시가 남아있는 부분이 있네요.

https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344

반영하셨는데도 영향이 없다면, 직접 조정해주시면 됩니다.

2021-03-11 11:28 UTC, ksundong commented on src/main/resources/static/js/validInput.js
> +function checkInput() {
네임은 check인데 submit까지 하네요.

2021-03-11 14:29 UTC, ChoiGiSung commented
뭔가 놓친 게 있는 느낌이 있었는데 미션 요구사항을 빼먹었네여..ㅎㅎ
일단 요구 사항들은 다시 모두 구현했습니다. (중복 코드가 많습니다.)
 내일 날이 밝는 데로 피드백과 중복코드 제거를 해보겠습니다.

2021-03-12 01:45 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private AnswerService answerService;
final을 붙이는 것이 더 안전하겠네요. 개발의도도 엿볼 수 있고. 변경했습니다!

2021-03-12 02:00 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("")
기본값이 String[]이었네요. 배열이기 때문에 PathVariable로 값을 쉽게 끌어올 수 있는 거 맞겠죠?

2021-03-12 02:09 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.write(HttpSessionUtils.getUserFromSession(session), contents, questionId);
저도 그렇게 사용하는 것을 좋아합니다. 미래에 유지 보수나 가독성 부분에서 이점이 있다고 생각을 합니다.

이번엔 "코드도 한 줄 줄고 나쁘지 않네", 이런 생각으로 도입을 시켜봤습니다.

2021-03-12 02:31 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        }
19c9800 
리팩토링을 진행해 봤습니다 . null 체크 보다는 boolean으로 체크하는 게 맞는 거 같아 service쪽 return type을 변경했고요.
findByUserId 메소드를 추가했습니다.

그러나 분기문을 제거하지 못했습니다. login시에 로그인 가능 여부에 따라 분기문은 필연적이지 않나요?
생각해봐도 정답을 잘 모르겠습니다.

2021-03-12 02:41 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        User findUser = userService.login(userId, password);
수정했습니다!

2021-03-12 02:43 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        session.setAttribute("sessionedUser", findUser);
아..이미 정의한 상수가 있었네요. 변경했습니다!

2021-03-12 03:08 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +    @GetMapping("/logout")
좀 어렵네요. post가 안전하긴 하지만 logout이 db에 쓰기/편집/변경 기능이 아니라 목적에 맞는지.
일단 post가 안전하기에 post로 변경했습니다.

2021-03-12 06:54 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
`createQuestion()` , `renderQuestionForm()` 에서 로그인 여부를 검사하고 있습니다. 
메소드로 빼서 사용을 한다고 해도 저 분기문 이후의 행동이 다른 데 의미가 있을 까요?
아님 다른 방법이 존재할까요? 
중복 제거 너무 어렵네요.

2021-03-12 06:57 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PutMapping("/update")
수정했습니다!
form에서 input hidden으로 id값을 받고 있어서 url을 바꾸지 않았었는데, 컨벤션을 따라야겠네요.
근데 @PathVariable을 사용하진 않고 있습니다. 현재 넘어오는 user에서 getId() 를 통해 사용하고 있습니다. 
cfda9c9

2021-03-12 06:59 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        question.getAnswerList().add(this);
필드 초기화로 바꿔줬습니다. 
또 `getAnswerList()`를 사용하는 것이 아닌 `addAnswer()` 메소드를 정의해서 값을 넣는 것으로 변경했습니다.

2021-03-12 06:59 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private LocalDateTime createDate;
수정했습니다!

2021-03-12 07:02 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return null;
19c9800 수정했습니다!

2021-03-12 07:14 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
메소드 명을 변경하니 html에서 handlebars가 getter를 못 찾아서 일단 유지해 놓겠습니다.

2021-03-12 07:23 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @OrderBy("id ASC ")
id순서대로 가져오기 위함입니다.
desc를 할 게 아니면 굳이 필요 없긴 하겠네요.

2021-03-12 07:27 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private LocalDateTime writeTime;
writeTime이었습니다.ㅎㅎ
오타도 있고 해서 createDateTime으로 변경했습니다

2021-03-12 07:46 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
crud가 더 상위였네요.  
jpaRepository는 중간에 PagingAndSortingRepository 까지 상속 받아서 
findAll(Sort) ,flush()등 기능이 더 많습니다.

2021-03-12 07:50 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    User findByUserId(String userId);
수정했습니다!

2021-03-12 07:56 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        UserValidation.validUserInfo(writer);
행위자로 작명 기억하겠습니다!

2021-03-12 07:57 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        Question findQuestion = questionService.findById(questionId);
question으로 수정했습니다!

2021-03-12 08:00 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/UserService.java
>          User DBUser = userRepository.save(user);
네이밍이 애매해` return userRepository.save(user).getId(); ` 변수로 사용하지 않고 리턴 하면서 주는 것으로 변경했습니다.

2021-03-12 08:20 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +    public static final String USER_SESSION_KEY = "sessionedUser";
하하..변경했습니다.

2021-03-12 08:35 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new IllegalStateException("자신의 정보만 수정 가능");
`checkSession`의 길이가 길어지는 것을 보기 싫어서 분리한 게 큰 이유입니다.
그래서 아무래도 다른 곳에서는 사용처가 마땅치 않습니다.

2021-03-12 08:48 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +        return true;
변경했습니다!

2021-03-12 08:52 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/valid/UserValidation.java
> +//        validID(user.getId());
수정했습니다!

2021-03-12 08:59 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/valid/UserValidation.java
> +        if (userId.trim().isEmpty()) {
와 감사합니다.
왜 굳이 하나하나 만들었었을까요.
수정했습니다!

2021-03-12 09:00 UTC, ChoiGiSung commented on src/main/resources/application.properties
> +handlebars.expose-session-attributes=true
설정 부분은 신경을 못썼네요. 감사합니다!

2021-03-12 09:06 UTC, ChoiGiSung commented on src/main/resources/static/js/validInput.js
> +function checkInput() {
validate()로 변경해봤습니다.

2021-03-12 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("")
오 저도 거기까지는 생각 안해봤는데요.
일단 기본값은 맞고, 뒤의 내용은 스프링 내부 구현과 관련된 얘기라 어려울 듯 하네요.
저도 나중에 한 번 찾아봐야 할 것 같아요.

2021-03-12 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.write(HttpSessionUtils.getUserFromSession(session), contents, questionId);
실험 정신 좋네요.

2021-03-12 14:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        }
예외를 통해서 처리하는 방식도 사용해보세요.
보통 로그인 실패의 경우는 저는 일반적인 로직이 아니라고 생각합니다.

2021-03-12 14:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        }
그리고 꼭 정답이 있는 문제가 아니라서, 뭐가 옳다 그르다는 정할 수 없는 것 같아요~

2021-03-12 14:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +    @GetMapping("/logout")
css는 어려워요 ㅎㅎ

2021-03-12 14:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
이미 return된 이후의 내용은 달라도 상관없지 않나요?

2021-03-12 14:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PutMapping("/update")
ㅎㅎ form으로 굳이 넘겨주지 않아도 되는 정보인건 아닐까요?

2021-03-12 14:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
formattedDateTime으로 받아도 될거에요.
다른 분들은 해결하셨다더라고요~

2021-03-12 14:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @OrderBy("id ASC ")
정렬할 때, 과연 question이 순서대로 나와야할지는 고민해보세요~

2021-03-12 14:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private LocalDateTime writeTime;
어 제가 잘못봤나보네요.

2021-03-12 14:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
>          User DBUser = userRepository.save(user);
그것도 방법이긴 하죠 ㅎㅎ

2021-03-12 14:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +            throw new IllegalStateException("자신의 정보만 수정 가능");
아 문자열 하드코딩 얘기한 것 이었습니다 ㅎㅎ

2021-03-12 15:06 UTC, ksundong approved these changes
안녕하세요. coco!! 리뷰어 Dion입니다.

일단 애플리케이션 관련 피드백입니다.

- css가 깨졌네요.
    ![image](https://user-images.githubusercontent.com/38597469/110957803-55eba280-838f-11eb-92d9-b29c29af988c.png)
- 로그인 중일 때, 로그인 창이 뜨는 것이 정말 맞을까요?
    ![image](https://user-images.githubusercontent.com/38597469/110957912-7582cb00-838f-11eb-935a-ddbe1419be58.png)

기타 코드 관련 피드백은 코멘트를 참고해주세요.
현재 단계에서 피드백은 충분히 수용하신 것 같아서, 말씀드린 피드백은 다음 단계에 적용해주시면 되겠습니다.

3단계 미션을 진행하시느라 고생하셨습니다~

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        userService.checkSession(session, findQuestion.getWriter().getId());
왠만하면 session을 넘겨주지 않고 해결해보세요!
뒤쪽 파라미터의 경우에는 객체를 직접 넘겨주는 방법도 고민해보세요.

https://woowacourse.github.io/javable/post/2020-06-02-law-of-demeter
이 글도 한 번 참고해보세요.

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return findUser != null && findUser.checkPassword(password);
이 findUser가 null일 수 있는건가요?

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/util/DateTimeUtils.java
> +public class DateTimeUtils {
Utility 클래스는 `private` 기본 생성자로 인스턴스 생성을 막아주세요~

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +            return null;
되도록 `null`의 반환은 지양해주시고, 저는 `null`을 반환하는 메서드는 아예 작성하지 않는 편이긴 합니다.

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/valid/QuestionValidator.java
> +            throw new NullPointerException("제목이 비었습니다.");
NPE는 이럴 때 쓰는 Exception이 아닙니다.
CustomException을 정의해서 사용해주세요.

2021-03-12 15:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/valid/QuestionValidator.java
> +            throw new NullPointerException("제목이 비었습니다.");
NPE를 직접 생성해서 반환하는건 절대 하지 말아줍시다 ㅎㅎ

2021-03-12 15:06 UTC, ksundong commented on src/main/resources/templates/error.html
> +</html>
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
여기 참고해서 설정 적용해주시고,
만약에 변경되지 않았다면 직접 엔터 치시고 저장하시면 됩니다.

2021-03-13 01:48 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/LoginController.java
> +        }
일반적인 로직이 아니라고 생각하면 예외를 던지는 게 맞겠네요.
이번에 exception Handeler를 이용해 볼 계획입니다.
제인 덕분에 알게 됐는 데 예외만 던져주면 돼서 확실히 깔끔해 지긴 하네요!

2021-03-13 02:15 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        }
제가 생각한 방식은 저 3줄을 메소드로 분리해서 String리턴값으로 목적지를 적어주고
createQuestion() , renderQuestionForm() 에서 바로 리턴 한다는 생각이었습니다.

2021-03-13 02:39 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PutMapping("/update")
중간에 DTO가 있었다면 더 좋았겠네요.
그래도 아직 DTO 없이도 잘 동작해 추가는 하지 않고 id값을 배제 시켰습니다.
이제는 url의 id를 활용하기에, update()는 인자로 Long id를 하나 더 받게 되었습니다.

2021-03-13 02:50 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
오 html에서 entity의 필드명을 따라가는 줄 알았는데 get 뒤에 있는 이름을 따라가는 거였네요!
변경했습니다!

2021-03-13 06:09 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        userService.checkSession(session, findQuestion.getWriter().getId());
service쪽으로 세션을 넘기지 않게 처리했습니다. 
getUserFromSession 에서 비 로그인 시 예외를 던져주게 해서 
많은 검증 코드가 줄었습니다.

뒤 쪽 파라미터는 userController와 questionController에서 질문 글과 유저를 통해 id를 뽑아내 사용합니다.
각각 정의하는 것 보다 공통으로 사용하는 게 좋은 거 같아서 Long id를 받는 데 좀 더러워 보이네요.

2021-03-13 06:10 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        return findUser != null && findUser.checkPassword(password);
findUserId() 시 이미 null이면 예외를 던지네요.
수정했습니다!

2021-03-13 06:31 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/util/HttpSessionUtils.java
> +            return null;
예외를 반환하도록 변경했습니다!

2021-03-13 06:36 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/valid/QuestionValidator.java
> +            throw new NullPointerException("제목이 비었습니다.");
IllegalArgumentException이 맞겠네요, 변경했습니다.

2021-03-13 14:16 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    @PostMapping("")
찾아보니 PathVariable은 URI 클래스를 이용해서 값을 얻는 거 같아요.

2021-03-14 14:59 UTC, honux77 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        userService.checkSession(session, findQuestion.getWriter().getId());
디미터가 데미테르군요 ㅋㅋ 생각해 보니 게임에 종종 등장하는 풍요의 여신! (큰 관계는 없습니다 ㅎㅎ)

2021-03-14 15:01 UTC, merged