[yeon] 미션2: 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #52
Opened 2021-03-10 08:23 UTC by kimnayeon0108

안녕하세요 yeon입니다!😄 미션2 완료하고 코드리뷰 부탁드립니다
스프링 과정은 에러와의 싸움이라고 느꼈습니다😅

미션 진행하면서 학습하고 고민했던 부분에 대해 말씀드리면,

**생성자 주입
User와 Question 클래스에서 각각 해당되는 repository에  @Autowired를 이용한 의존성 주입시 
루카스에는 필드 주입을 하라고 나와있어서 처음에는 코드를 따라쳤다가, 다른분들의 pr을 보고 생성자 주입이 더 좋다고 하여 변경했습니다.
생성자 주입의 장점은 다음과 같다고 학습했으나, 명확히 이해되지는 않아서 그렇구나 하고 일단 넘어갔습니다.
- 의존관계 설정이 되지 않으면 객체 생성 불가 → NullPointerException 방지
- 주입받을 필드를 final로 선언 가능 → Immutable
- 순환참조 감지 가능

**JpaRepository와 CrudRepository의 차이?
루카스에는 CrudRepository를 상속받고, 자바지기님 영상에선 JpaRepository를 상속받아서 둘의 차이가 궁금해서 찾아봤습니다. 
참고링크 : https://stackoverflow.com/questions/14014086/what-is-difference-between-crudrepository-and-jparepository-interfaces-in-spring
결론적으로 JpaRepository가 CrudRepository의 자손이라고 합니다. 일단은 JpaRepository를  extends하도록 했습니다. 

**ExceptionHandler
userRepository와 questionRepository에서 객체를 꺼내올때 orElseThrow()를 사용했습니다.
그리고 예외 발생시 nullErrorHandle.html을 에러 메시지를 띄어주는 뷰로 추가했습니다. 이렇게 구현하는게 맞는건지 잘 모르겠지만 findById()로 객체를 가져올때 get()을 쓰는게 안좋다고 하여 예외처리를 해주고 싶어서 이렇게 구현해봤습니다. 

부족한 부분이 많은데 주저없이 피드백 주시면 학습하면서 반영하겠습니다..!!!

2021-03-10 08:35 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
생성자 주입은 이렇게 하는거군요!
배워갑니다!!👍

2021-03-10 08:37 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    }
@sanhee 엇 저도 다른분들거 참고했어요!ㅋㅋㅋㅋ 아직 DI 개념이 안잡혀있어서 계속 공부가 필요합니다😖

2021-03-11 10:02 UTC, wheejuni requested changes
오류와의 싸움을 하신 것 치고는 좋은 코드를 간결하게 잘 작성해주신 것 같아요. 👍 💯 
생성자 주입에 대해 고민해보신 것 정말 좋고요, 특히 `CrudRepository` 와 `JpaRepository` 의 차이에 대해 학습해 보신 것도 인상적이네요. `@ExceptionHandler` 도 잘 구현하셨습니다.
컨벤션 중심으로 간단한 개선 의견 드렸는데 참고해 주세요. 금방 반영하실 수 있을 것 같습니다. 🥇

2021-03-11 10:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        this.questionRepository = questionRepository;
👍

2021-03-11 10:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @ExceptionHandler(NullPointerException.class)
`NullPointerException` 은 너무 넓은 범위의 exception 캐치 같은데, 
예외 처리에서 중요한 점은 항상 **가장 적합한 범위**를 설정하고 그에 맞는 로직을 구현해주는 일입니다.
커스텀 예외 등을 구현하여 조금 좁혀주시는 건 어떨까요?

2021-03-11 10:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("")
빈 문자열이라면 과감히 날려도 됩니다!

```suggestion
    @PostMapping

2021-03-11 10:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public boolean matchPassword(String inputPassword){
사소하다고 생각될 수 있지만, `boolean` 타입 리턴하는 메소드에는 _동사형 이름_ 을 붙이는 습관을 들여주세요.

**제안**
- hasMatchingPassword
- passwordMatches
- isPasswordMatching

2021-03-11 11:14 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @ExceptionHandler(NullPointerException.class)
@wheejuni 넵! 말씀해주신대로 변경해보겠습니다

2021-03-11 11:15 UTC, kimnayeon0108 commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public boolean matchPassword(String inputPassword){
@wheejuni 넵 메소드명에도 더 신경써야겠어요 수정하겠습니다!

2021-03-11 12:12 UTC, kimnayeon0108 commented
@wheejuni 코드 수정완료했습니다.

커스텀 예외 NoUserException과 NoQuestionException 클래스를 정의했습니다.
@ExceptionHandler 부분에서 User와 Question 객체를 꺼내올때 orElseThrow()로 각각 해당되는 커스텀 예외를 발생시키도록 하고, Controller에서 해당하는 예외를 처리하도록 했습니다.

사용자 정의 예외를 처음 구현해보는데, 현재 제 코드에서 예외클래스에서 로직이 구현된것도 없고, 가능하면 기존의 예외클래스를 사용하라고 하여 실제로 발생하게되는 NoSuchElementException을 발생시키도록 할까라고 생각하다가
사용자 정의 예외의 이름만으로 정보가 좀 더 명확하게 표현될수 있는 장점이 적용된다고 이를 이용하는 방식으로 수정했습니다.

아직 부족한점이 많아서 어떤게 더 좋은방법인지 판단하기 어렵네요😰

2021-03-11 12:19 UTC, wheejuni approved these changes
좋습니다. 더 많은 고민은 3단계에서 해주세요. 👍 merge 하겠습니다!

2021-03-11 12:19 UTC, merged