[Starve] Mission2 -  데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #53
Opened 2021-03-10 09:41 UTC by Jiwon-JJW

안녕하세요.

코드스쿼드 백엔드 과정 Starve입니다.

미션 2를 완료하였으며, 부족한 코드이지만 이번 리뷰도 잘 부탁드립니다!

[배포 사이트](https://starve-spring-0119.herokuapp.com/)

##### 이번 미션에서 궁금한 사항:

아주 기초적인 사항인 것 같지만, not null 설정을 했음에도 회원 가입 혹은 질문 기입 시 공란으로 둔 상태임에도 회원가입이 되거나, 질문이 등록되고 있기에 validation을 이용해 @NotEmpty 같은 것도 사용을 해보았지만 이 역시 잘 되지 않았습니다. 그래서 지금은 그냥 nullable = false을 이용 하였는데, 어떻게 하면 이를 해결할 수 있을지 잘 모르겠어서, 검색어 힌트라도 받을 수 있을지 요청해봅니다. 🥲

감사합니다!

2021-03-11 12:00 UTC, ksundong requested changes
안녕하세요. Starve!! 리뷰어 Dion 입니다!
DB와 연결하는 Mission2를 진행해주시느라 고생많으셨습니다.

- 유저 생성 후 https://starve-spring-0119.herokuapp.com/users/1 여기로 가면, 프로필 이미지가 깨집니다. 확인하시고 수정해주세요.
- 회원 정보 수정시 비밀번호 검증절차가 없네요. 확인해주세요.

이번 단계는 간단했지만, 그래도 다음 단계로 넘어가기 전에 확인해주셨으면 하는 부분들이 좀 있어서 **변경 요청** 드립니다.
코멘트 확인하시고 수정하실 부분은 수정해주신 다음 리뷰요청 보내주세요.

코멘트 보시면서 궁금하시거나, 이해가 잘 되지 않는 부분, 도움이 필요한 부분, 토론하고 싶은 부분은 코멘트 남겨주시면 확인하겠습니다.
고생하셨습니다~

2021-03-11 12:00 UTC, ksundong commented on build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: '2.4.3'
```suggestion
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
```
위에 버전은 이미 명시되어있습니다~

2021-03-11 12:00 UTC, ksundong commented on build.gradle
> +    compile('org.springframework.boot:spring-boot-starter-mustache')
`compile`은 `implementation`으로 바꿔주세요.

2021-03-11 12:00 UTC, ksundong commented on build.gradle
> +    implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.6.1"
흠.. 이 친구가 필요한 수준은 아닌 것 같은데요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false)
    private String writer;
    
    @Column(nullable = false)
```

애노테이션이 붙은 라인은 서로 떼어서 가독성을 높여줍시다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    @Column(nullable = false)
`Not NULL` 제약조건이 필요한지는 조금 고민해보고 넣어주세요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    private LocalDateTime date = LocalDateTime.now();
```suggestion
    private LocalDateTime createdDateTime = LocalDateTime.now();
```
이렇게 이름을 정확히 명시해주는 습관을 들여주세요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
>      }
되도록이면 `getter`는 `getter`로만 사용하고
`getFormattedDateTime`정도로 바꿔 사용하는 것을 권장합니다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
>      }
`id`가 쉽게 변경될 수 있겠네요.
왠만하면 필드들에 특히 `id`에는 `setter`를 열어주는 것을 권장하지 않습니다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
👍

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/QnaRepository.java
> +public interface QnaRepository extends JpaRepository<Qna, Long> {
요구사항은 `CrudRepository`의 사용인데, 둘의 차이에 대해 한 번 알아보세요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    private QnaRepository qnaRepository;
스프링의 인젝션 방식에 대해서 학습하시고, 생성자 Injection으로 변경해보시는걸 권장합니다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public String qnaMain(Qna qna) {
이 메서드.. 정말 `qnaMain`이 적절한 네이밍인가요?

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if(qna == null){
이런 경우가 있나요?

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if(qna == null){
```suggestion
        if(qna == null) {
```

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
>      public String getQnaList(Model model) {
`getXXX`같은 네이밍은 지양해봅시다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
>      public String getQnaList(Model model) {
`index`를 리턴하는데 메서드명은 `qnaList`군요.
저라면 `index`를 따로 매핑해줄 것 같네요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public ModelAndView getOneQuestion(@PathVariable long qnaId) {
오호 `ModelAndView` 써보니 어떤가요?

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        modelAndView.addObject("Qna", qnaRepository.findById(qnaId).orElse(null));
`orElse(null)` 지양합시다 ㅎㅎ
`orElseThrow()`를 더 권장합니다.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
>      @GetMapping("qna/show/{qnaId}")
```suggestion
    @GetMapping("qna/{qnaId}")
```

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
>      @PostMapping("/create")
```suggestion
    @PostMapping("/")
```

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        }
지금 생각해보니 여러 상황을 고려해서 잘 한 것 같아요.

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
>      @GetMapping("/list")
```suggestion
    @GetMapping("/users")
```

2021-03-11 12:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/create/{id}")
이거는 죄송하지만... 굉장히 이상한 url이라고 생각합니다.
RESTful에 대해서 대략적이라도 개념을 잡고 가주세요.

2021-03-11 12:00 UTC, ksundong commented on src/main/resources/application.properties
> +spring.jpa.database-platform= org.hibernate.dialect.H2Dialect
통행금지 표시~ 신경써주세요~

https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344

2021-03-12 08:53 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if(qna == null){
전부 다 공백처리하고 등록 했을 때, not null로 등록해놨음에도 등록이 되길래 넣은 if문입니다!  아무 것도 작성되지 않았는데 등록되면 안될것 같아서요 ㅠㅠ 딱히 제대로 작동은 안하는 것 같아서 어떻게 해야할지 힌트라도 받을 수 있을까요? @NotNull, @NotEmpty 같은걸 해도 작동을 안해서요 ㅠ

2021-03-12 08:54 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public ModelAndView getOneQuestion(@PathVariable long qnaId) {
가독성 측면에서 조금 떨어진다고 느꼈습니다... 강의에서 사용하면 안된다 하여 다시 String을 return하도록 변경하였습니다..!

2021-03-12 08:55 UTC, Jiwon-JJW commented
말씀해주신 사항 및 새로운 적용사항을 적용해보았습니다! 부족한 코드 리뷰해주셔서 감사합니다!

2021-03-12 15:08 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if(qna == null){
제가 질문을 제대로 안읽고 리뷰했었네요. 죄송합니다.
다음 리뷰에서 알려드릴게요.

2021-03-12 15:31 UTC, ksundong requested changes
안녕하세요. Starve, 리뷰어 Dion입니다.
질문 주신 내용을 제가 깜빡하고 답변을 드리지 않았네요. 죄송합니다.

질문에 대한 답변입니다.

> 아주 기초적인 사항인 것 같지만, not null 설정을 했음에도 회원 가입 혹은 질문 기입 시 공란으로 둔 상태임에도 회원가입이 되거나, 질문이 등록되고 있기에 validation을 이용해 @notempty 같은 것도 사용을 해보았지만 이 역시 잘 되지 않았습니다. 그래서 지금은 그냥 nullable = false을 이용 하였는데, 어떻게 하면 이를 해결할 수 있을지 잘 모르겠어서, 검색어 힌트라도 받을 수 있을지 요청해봅니다. 🥲

아주 좋은 고민을 하고계시네요. 사용자의 입력을 받을 때, 검증할 수 있는 수단은 여러가지 방안이 있을 수 있습니다.
제가 애용하는 방식은 Spring에서도 지원하는 Bean Validation이라는 방식인데, 이는 이해하는데 시간이 걸릴 수 있으므로, 직접 validation 로직을 작성해주시는 편이 좋을 것 같습니다.
Bean Validation 방식이 바로, 말씀하신 애너테이션을 활용해서 검증하는 방식이고, 현재단계에서 굳이 공부하실 필욘 없습니다.

그리고 적용하신 nullable = false는 db에서 제약조건을 적용해주는 방법으로써 조금 잘못된 접근 방식이라고 생각됩니다.
이렇게 설정해 줄 경우 DB에서 예외가 발생하게 됩니다.

Controller 수준에서 값에 대한 검증을 해주고, 이후 절차에선 추가적인 검증은 하지 않도록 하는 것이 좋을 것 같습니다.
이해가 되지 않으시면 다시 한 번 질문 부탁드려요.

## 애플리케이션 피드백

- 로그인이 되지 않네요. 확인 부탁드립니다.
- 코드 관련 피드백은 코멘트에 작성해두었습니다.

로그인이 되지 않는 치명적인 오류가 있어, **변경 요청**을 드리니 확인 후에 다시 리뷰 요청해주세요!
항상 궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분 등에 대해서는 코멘트 남겨주세요.
고생하셨습니다!

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    private long id;
여기 `Long`을 쓸 때와 `long`을 쓸 때의 차이를 알고 계신가요?
한 번 알아보세요~

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    public LocalDateTime getDate() {
`getter`의 이름도 같이 변경해줍시다.

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +        return createdDateTime.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
포매터는 상수로 추출해봐도 좋을 것 같아요.

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    private String newPassword;
19번 라인, 이거 `User`에 있어도 되는 필드인가요?
`DB`에 저장할 것 만이 `Entity`에 존재해야합니다~

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +        if(checkPassword(updateUser.password)){
```suggestion
        if(checkPassword(updateUser.password)) {
```

커밋 전 꼭 포맷팅 해줍시다~

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
>      }
저라면 MainController 같은걸 만들어서 옮겨주고, root 접근시 qnaList로 리다이렉트 시켜줄 것 같아요~

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        }
리뷰 때 어떻게 처리할 수 있는지 알려드리겠습니다.

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("/")
맨 위에 `RequestMapping("/users")`를 써주고 이렇게 사용해야합니다.
지금 요청이 엉뚱한 Path로 전송되고 있네요 ㅠㅠ

2021-03-12 15:31 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        model.addAttribute("user", userRepository.findById(id).orElseThrow(NoUserException::new));
잘 사용해주셨네요.

2021-03-15 13:15 UTC, Jiwon-JJW commented
안녕하세요! 질문 답변주셔서 감사합니다! 나름대로 컨트롤러에 추가는 해봤지만, 따로 별개의 클래스로 관리하는게 더 좋을지 고민이 됩니다..
그리고, 로그인 기능은 미션 2에는 해당 요구사항이 없어 아직 기능을 넣지 않았습니다! 미션 3에서 넣을 예정인지라 다시 pr 요청드립니다..! 
감사합니다!

2021-03-15 14:50 UTC, ksundong approved these changes
아, 제가 3단계 리뷰와 번갈아가며 하다보니 헷갈렸나보네요. 죄송합니다.

코드가 리뷰를 받고서 아쉬운 부분이 조금 더 늘어났네요. 😭 
유효성 검증은 굳이 이 단계에서 해주실 필요는 없으니, 좀 더 깔끔한 코드를 작성하는 것에 중심을 두고 개발해주세요.
고생많으셨습니다. 다음 단계 진행해주세요~

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
>      }
파싱을 할 것이 아니라 그냥 String을 넘겨주면 됩니다. ㅎㅎ

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
>      private String email;
`nullable` 제약조건은 정말 이 필드가 `null`이 아니어야 하는가? 도 고민해보세요.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/NoQuestionException.java
> +public class NoQuestionException extends RuntimeException{
```suggestion
public class NoQuestionException extends RuntimeException {
```
포매팅 아직 잘 안되네요~ 신경 많이 써주셔야 할 것 같아요.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        }
`null`인 경우가 있나요?

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        }
```suggestion
        qna.setCreatedDateTime(qna.getFormattedDateTime());
        qnaRepository.save(qna);
        return "redirect:/";
```

early return을 했으면 else는 필요 없습니다.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    private boolean checkNull(Qna qna){
메서드 명과 하는 일이 다르네요.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    private boolean checkNull(Qna qna){
Null, Empty, Blank의 차이에 대해서 정리해보세요.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    private final Logger logger = LoggerFactory.getLogger(QuestionController.class);
순서를 잘 지켜주세요.

2021-03-15 14:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        }
else의 사용을 최대한 지양해주세요.

2021-03-16 01:53 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/create/{id}")
ㅎㅎㅎ

2021-03-17 06:15 UTC, honux77 commented on build.gradle
> +    implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.6.1"
implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.6.1" 이건 뭔가요??

2021-03-17 06:16 UTC, merged

2021-03-17 10:03 UTC, ksundong commented on build.gradle
> +    implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.6.1"
요거는 JPA에서 쿼리에 사용되는 파라미터를 확인할 수 있도록 해주는 친구입니다!