[이노] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #54
Opened 2021-03-10 13:02 UTC by eNoLJ

미션3 로그인 기능과 댓글 수정, 삭제 기능을 구현했습니다.

세션을 활용하여 최대한 로그인을 한 사람인지, 질문 작성자와 세션유저가 일치하는지, 댓글 작성자와 세션유저가 일치하는지 등 확인을하고 처리하도록 구현했습니다.

진행하면서 의문점이 2개정도 생겼습니다.

1. 정상적이지 않은 요청, 예를 들어 본인이 작성한 질문이 아닌데 수정이나 삭제를 요청하는 경우 에러 메세지를 띄우는 것과 홈화면이나 적절한 화면으로 리다이렉션을 하는 것 중에 어떤 방법이 옳거나 많이 사용 하나요??

2. MvcConfig에서 "/user/form"으로 viewController가 잡혀 있으면 UserController에서 @PostMapping으로 같은 url로 생성 시 제대로 들어오지 않습니다. `setOrder`에 `Ordered.HIGHEST_PRECEDENCE`나 `Ordered.LOWEST_PRECEDENCE`를 사용해서 우선순위를 변경해도 제대로 작동하질 않습니다. highest로 설정 시 컨트롤러에 포스트매핑이 안잡히고 lowest로 설정 시 포스트매핑으로는 들어오는데 정작 MvcConfig에는 들어오질 않네요... 해당 이슈에 관한 검색 키워드나 글이 있다면 알려주시면 감사하겠습니다.

이번 리뷰도 잘 부탁드립니다!!!
좋은 하루 되세요!!

2021-03-11 13:00 UTC, wheejuni requested changes
수고하셨습니다 👍 💯 
전반적으로 잘 구현해 주셨는데 개선할 부분도 있고, 궁금한 점도 있어서 피드백을 남깁니다.

2021-03-11 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/user/login_failed").setViewName("user/login_failed");
여기에 2번 질문에 대한 답변을 드릴게요.
`.setOrder()` 는 같은 URL 설정이 경합될때 우선 순위를 결정하는 로직에 대한 설정인데, 어찌보면 지금 작동하는 방식이 당연히 기대되는 작동 로직 아닐까요.
`.HIGHEST_PRECEDENCE` 를 준다면 `MvcConfig` 이 자리에서 설정한 뷰 컨트롤러가 최우선적으로 작동할 거고요,
`.LOWEST_PRECEDENCE` 를 준다면 그 거꾸로겠죠. 어차피 path 하나에 하나의 동작이 수행돼야 할 건데요.
어떤 작동을 기대하셨는지 잘 이해는 안되지만, 지금 설명해주신 부분으로 보면 당연한 로직이 수행된 것 같아요. path를 다르게 매핑하는 수정이 필요하겠네요.

2021-03-11 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        boolean result = this.userService.update(id, user, oldPassword, session);
`Service` 단에 `HttpSession` 객체가 직접 들어가는건 다소 아쉬운 것 같아요.
각 레이어가 분리돼서 서로의 관심사에서 분리되는 게 가장 좋은 구현인데요, 지금 단계에서 공감하기 어려우실거고 저도 설명하기 어렵네요.
그치만 이런 피드백을 받았다는 것을 기억하시고 앞으로 개발 과제 구현에 임해주세요.

2021-03-11 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/User.java
> +        }
`.equals()` 호출시엔 많은 경우에 null check를 안 하셔도 됩니다.

2021-03-11 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Autowired
이건 왜 달린건가요?

2021-03-11 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        if (targetUser.nonNull() && targetUser.matchPassword(password)) {
`.nonNull()` 이라는 메소드를 여러곳에서 많이 사용하는데요, 이것에 대해 설명을 좀 부탁드려요.
어차피 변수가 `null`이면 이 메소드를 호출하는 시점에 `NullPointerException`이 발생할 거거든요.

2021-03-11 15:20 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/user/login_failed").setViewName("user/login_failed");
그 동작에 대해선 이해하고 있습니다. 다만 제가 하고싶은 부분은 예를들어 MvcConfig에 `registry.addViewController("/user/login").setViewName("user/login");`이 코드가 있을 때, `UserController`에 같은 url로 묶였지만 요청 메소드가 다른`@PostMapping("/user/login")`도 실행이 되게 만들고 싶습니다.

제가 예상했던 부분은 `.HIGHEST_PRECEDENCE`로 설정 했을 때 MvcConfig를 먼저 통해서 들어오게 되어 컨트롤러까지 안간다면 반대로 `.LOWEST_PRECEDENC`로 설정하면 컨트롤러에 있는 post요청에 걸리고 만약 get같은 다른 메소드 요청 시 MvcConfig의 걸릴거라고 예상했었습니다.

하지만 실제적으로 해보니 같은 url이라면 어떻게 설정해도 MvcConfig나 UserController나 둘 중에 하나만 걸리더라고요. 현재 상황에서는 제가 원하는 동작을 하려면 MvcConfig를 사용하지 않고 UserController에 `@GetMapping`과 `@PostMapping`을 두가지를 다 만드는 수밖에 없는건지 그게 궁금했습니다.

2021-03-11 15:21 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        boolean result = this.userService.update(id, user, oldPassword, session);
아 그럼 이부분은 컨트롤러에서 `HttpSession`에 담긴 객체를 꺼낸 후 `Service`로 넘겨주는 방식으로 수정을하면 좀 더 나은 코드가 될까요??

2021-03-11 15:21 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/User.java
> +        }
해당 부분은 수정하도록 하겠습니다!!

2021-03-11 15:30 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Autowired
`@Autowired` 이거 말씀하시는거죠?? 음... 테스트를 해보진 않았는데 포비 동영상에서 꾸준히 달아주시길래 달았습니다. 브라이언이 물어보시는거보면 저 부분은 필요가 없는거겠죠?? 그럼 여기서 확인차 하나 여쭤볼게 생겼습니다. 포비 동영상에서 저렇게 해주는 이유가 저걸 안해주면 `AnswerRepository`가 초기화가 안된다고 말을 하셨던 것 같은데 저같은 경우 저렇게 해도 제대로 작동을 안하길래 `AnswerService`에 생성자로부터 초기화를 하도록 만들었습니다. 이렇게 생성자로 초기화를 해줬기 때문에 `@Autowired`는 필요가 없는건가요??

2021-03-11 15:36 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        if (targetUser.nonNull() && targetUser.matchPassword(password)) {
현재 제가 구현한 흐름이 저 메소드들을 `Controller`에서 사용을하는데 반환값이 있어야 `Controller`에서 결과에 맞춰 `redirect`를 해주게끔 만들어 놨습니다. 하지만 `Exception`이 발생하면 그렇게 해줄 수가 없어서 `nonNull()`을 만들었습니다. 그래서 pr 날릴 때 코멘트에 질문을 남겼는데 저 처럼 예외가 발생했을 때 그 부분을 확인해서 적절한 페이지로 `redirect`를 해주는 것과 그냥 화면에 에러 페이지를 보여주는 것 중에 어떤게 컨벤션이고 혹시 제가 하는 방법에 문제가 있다면 무엇인지 알고싶었습니다.

2021-03-12 02:25 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        boolean result = this.userService.update(id, user, oldPassword, session);
Service에서 HttpSession을 직접 핸들링하지 않고 Controller에서 User 객체를 꺼낸 후 넘겨주도록 수정했습니다.

2021-03-12 02:25 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/User.java
> +        }
불필요한 null check 삭제 했습니다.

2021-03-12 02:26 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Autowired
해당 부분 삭제 했습니다.

2021-03-12 12:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/user/login_failed").setViewName("user/login_failed");
@eNoLJ 사실 `ViewController` 와 `Controller` 클래스에 작성하는 `@RequestMapping` 은 성질이 조금 다릅니다. 
우선 `ViewController` 는 `GET` 이외의 요청을 처리할 수 없고 이 부분은 이해하고 계실 거라고 생각해요.
`ViewController` 쪽의 프로퍼티에 타겟 메소드에 관한 정보가 없기 때문에 발생하는 현상이라고 저 또한 피상적으로 분석이 되는데요,
이 부분은 저도 자세히 봐야겠네요. 사실 이런 방향의 구현을 생각해본 적이 없습니다. ㅎㅎ
그런데 이런 시나리오라면 말씀처럼 하나의 컨트롤러에 `GET`, `POST` 매핑이 모두 이뤄져야 한다고 생각합니다.

2021-03-12 12:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/User.java
> +        }
헐 죄송합니다.

2021-03-12 13:00 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        if (targetUser.nonNull() && targetUser.matchPassword(password)) {
이 부분은 컨벤션이 마땅히 없고 기획대로(구현 요구사항대로) 진행하는 것이 원칙인데요,
좀 애매하긴 하네요. 제가 그냥 편하게 생각하기에는 이번 과제를 통해서 예외 처리도 공부할 겸 예외를 모아서 한번에 처리하는 방식이 좋아보이긴 하는데요, 이건 @eNoLJ 가 판단하시고 좋은 방법대로 해 주세요. 

이 얘기를 할까말까 했는데 [Null Object Pattern](https://johngrib.github.io/wiki/null-object-pattern/) 이라는 게 있어서 같은 메소드에 대해 동작을 다르게 수행하는 Null Object 클래스를 따로 구현하는 경우가 있습니다. 아직 학습 초기단계라 디자인 패턴에 대해 너무 깊게 들어가실까봐 소개하지 않았는데요, 이런 방법이 있다는 걸 학습해보시는 것도 좋겠습니다.

그리고 제가 PR 상에서 `.nonNull()` 구현부가 제대로 캐치되지 않아서 조금 코드에 대해 모르고 코멘트를 단 부분도 있습니다. ^^;;

2021-03-12 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Autowired
지금 우리는 생성자 주입을 받아서 필드 주입을 받을때 사용하는 이 애노테이션은 필요가 없겠습니다.
제대로 작동하지 않았다면 뭔가 다른 이유였을 것 같아요.

2021-03-12 13:01 UTC, merged

2021-03-12 13:14 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        registry.addViewController("/user/login_failed").setViewName("user/login_failed");
충분한 답변이 되었습니다!! 감사합니다!!

2021-03-12 13:16 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    @Autowired
이 부분을 간과하고 넘어갔는데 집어주셔서 감사합니다!! 덕분에 알게되었습니다ㅎㅎ

2021-03-12 13:19 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/service/UserService.java
> +        if (targetUser.nonNull() && targetUser.matchPassword(password)) {
오늘 미션4을 좀 진행했는데 예외를 어떻게 발생시키고 어떻게 활용할지 보여주더라구요. 예를들어 예외를 발생시키고 그 예외를 모델에 담아 view에서 안내를 해준다던지 그런 부분이요!! 그리고 @ControllerAdvice 라는 키워드도 알게 되었고 다음 미션에서는 예외처리를 공부하고 적용해보도록 하겠습니다!! 그리고 브라이언이 말씀하신 디자인패턴도 열린 시각으로 참고용? 정도로 공부해보도록 할게요.

@wheejuni
아 그리고 오늘 브라이언은 모르시겠지만 오프라인에서 봬서 반가웠습니다ㅎㅎ
앞으로도 잘 부탁드려요!!