[Woody] 미션2. 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #56
Opened 2021-03-11 14:04 UTC by jihye-woo

안녕하세요 우디입니다! 

### 🎯 DB를 사용하는 방향으로 기존 코드를 수정하는데 초점! 
최대한 요구사항에 맞춰서 진행했습니다!
미션 1에서 회원정보 수정기능을 이미 구현해놓았었기 때문에 **미션 1과 기능적인 부분에서 큰 차이는 없습니다**
요구사항대로, **데이터베이스와 연동해서 Controller에 있는 crud 기능 관련 메소드들을 수정**했습니다!

### 그 밖에 특이(?)한 점 - 예외 처리
미션 1에서 `@ExceptionHandler`를 사용하여 에러 페이지를 따로 띄우거나, 커스텀 예외 클래스를 만들기도 했었지만 지금은 크게 필요없는 것 같아서 일단 제거해놓았습니다!

###  🙋‍♀️질문! - Entity Validation
Entity 객체 생성자에서 인자 값에 대한 별도의 validation을 아래와 같이 추가해주는 것이 좋을까요?
```java
public User(String userId, String password, String name, String email) {
        this.userId = validateId(userId);
        //...
    }
```
혹은 필드 변수 위에 `@Column`을 통해 좀 더 구체적인 설정 값을 지정해주면 상관이 없을까요?
```java
@Column(nullable = false, unique = true, length = 20)
    private String userId;
```
무언가 잘못된 입력값에 대한 처리를 해야할 것 같긴 하지만 어디에서 어떤 식으로 해주는 것이 가장 적절할지 잘 모르겠습니다😅😂

2021-03-12 08:46 UTC, wheejuni requested changes
2단계 진행하시느라 수고 많으셨습니다. 💯 
코드에 크게 손을 댈 부분은 없네요. 1단계에서부터 워낙 구조를 잘 잡으신 것 같아요.

그리고 질문에 대해 답변 드립니다.
일단 두 방법 모두 개발자들이 이야기하는 `Entity Validation` 은 아닙니다.
`Entity Validation` 이란 자바 진영에서는 대체로 [JSR-380 스펙을 따르는 방법](https://prohannah.tistory.com/113) 을 말합니다. 따라서 두 방법 모두 엔티티 밸리데이션과는 거리가 좀 있구요.

그리고 언급하신 두 방법은 결과는 같을지 몰라도 결과로 가는 과정까지는, 특히 JVM 안에서 일어나는 일들은 완전히 다른 방법입니다. JPA의 `@Column` 안에 기술되는 성질들은 DB의 칼럼을 관리하는 방법에 대한 설명임을 잊지 말아주세요. 객체나 객체가 갖고있는 필드의 성질과는 완전히 무관합니다. 

두 방법에 각각 위배되는 데이터가 들어왔을때 일어날 것 같은 일들을 클라이언트의 요청부터 DB INSERT 시점까지 순서대로 정리해보세요. 정리한 후에, 같이 생각을 나눠봐요.

2021-03-12 08:46 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +    @Column(nullable=false)
애노테이션 필드에도 연산자 앞뒤로 한칸씩 공백을 잊지 말아주세요.
```suggestion
    @Column(nullable = false)

2021-03-14 05:46 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +    @Column(nullable=false)
앗..! 코드 포멧팅이 안되어있었네요..!🤦‍♀️ 짚어주셔서 감사합니다! 바로 수정하겠습니다!

2021-03-14 06:43 UTC, jihye-woo commented
Entity Validation에 대해서 상세하게 답변해주셔서 감사합니다!😳(감동)

JVM을 자세히 뜯어볼 수는 없었지만😂

대신 말씀하신대로,
각각 위배되는 데이터가 들어왔을 때 아래와 같이 제가 언급했던 두 가지 방법을 사용해서
나올 수 있는 과정들을 간단히 정리해보았습니다!

---
예를 들어 위배되는 데이터(길이가 20을 넘는 userId)가 들어왔을 경우

### 공통 과정
1. client가 데이터와 함께 request 요청
    - 회원가입 form에서 정보(사용자 정보) 입력 후 request 요청
2. 컨트롤러에서 url과 매핑된 서블릿 메소드를 찾는다.
    - UserController 에서 `/create` 과 매핑된 create() 메소드를 찾는다.
3. 바인딩된 Command Object 생성자를 호출한다.
    - (현재 DTO 클래스가 없으므로) User 생성자를 호출한다.
4. [ 방법 1 ] or [ 방법 2 ]  수행

#### 👉 [ 방법 1 ] 인자 값에 대한 별도의 validation 메소드를 만들어 Entity 객체 생성자 내부에서 호출하는 경우

```java
public User(String userId, String password, String name, String email) {
        this.userId = validateId(userId);
        this.password = password;
        this.name = name;
        this.email = email;
    }

  private String validateId(String userId){
        if (userId.length() > 20 || userId.length() == 0){
            throw new IllegalArgumentException("invalid userId");
        }
        return userId;
  }
```
1. validateId()에서 throw IllegalArgumentException
2. BeanUtils 클래스에서 throw BeanInstantiationException
3. DB INSERT 쿼리가 실행되지 않음
4. 최종적으로 500 에러 발생

![Untitled (1)](https://user-images.githubusercontent.com/74452069/111059828-c43d7b80-84db-11eb-8cf2-aa07a9e42d00.png)


#### 👉 [ 방법 2 ] 필드 변수 위에 @Column을 통해 좀 더 구체적인 설정 값을 지정

```java
@Column(nullable = false, unique = true, length = 20)
private String userId;

@Column(nullable = false)
private String password;

@Column(nullable = false)
private String name;

@Column(nullable = false)
private String email;
```
1. User 인스턴스 생성, 바인딩 성공 
2. Insert를 수행하지만 SqlExceptionHelper에서 SQL 예외(JdbcSQLDateException) 발생
3. DB INSERT 쿼리가 실행
4. 최종적으로 500 에러 발생

![Untitled](https://user-images.githubusercontent.com/74452069/111059826-be479a80-84db-11eb-8c94-75dba50f4ac4.png)
![Untitled (2)](https://user-images.githubusercontent.com/74452069/111059845-dae3d280-84db-11eb-9793-9f4aa90ccdc6.png)

---
혹시.. 의도하신 것과 다르다면..😂 말씀해주세요..!!

2021-03-14 10:23 UTC, wheejuni commented
@jihye-woo 너무 잘 정리하셨어요 ㅋㅋ 이럴수가.... 
다른 분들하고 공유하셔도 될 것 같네요. 수고하셨습니다.

2021-03-14 10:23 UTC, merged