[Bongf] Step2 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #58
Opened 2021-03-11 16:02 UTC by bong6981

안녕하세요 Bongf입니다. 
코드리뷰 감사하다는 말씀 드립니다. 

배포서버
---

<https://bong-spring-boot-qna.herokuapp.com/questions>

내용 
---

- 커밋 메시지가 영어와 한글이 섞여 있습니다. 다음부터는 일관성있는 커밋 메시지 형식을 갖도록 하겠습니다. 
- 회원정보 수정시 비밀번호도 수정 가능하게 변경했습니다.
    - 기존에는 비밀번호 입력이 올바른 비밀번호를 입력하는 확인 용도로만 쓰였습니다.
    - 현재/새로운 비밀번호 칸으로 나누어 새로운 비밀번호를 입력할 수 있도록  (user/updateForm.html)과 관련 로직을 변경했습니다.

2021-03-12 13:54 UTC, SANGCO requested changes
Bongf님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-12 13:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
```java
@Controller
public class HomeController {
    @GetMapping("/")
    public String goHome() {
        return "redirect:/questions";
    }
}
```

[Spring QnA](https://lucas.codesquad.kr/main/course/%EB%A7%88%EC%8A%A4%ED%84%B0%EC%A6%88-%EB%B0%B1%EC%97%94%EB%93%9C-Java-%ED%81%B4%EB%9E%98%EC%8A%A4-2021/%EA%B0%95%EC%9D%98-%EC%9E%90%EB%A3%8C-%EB%AA%A8%EC%9D%8C/21%EB%85%84-3%EC%9B%94-11%EC%9D%BC-QnA-2%EC%A3%BC%EC%B0%A8-%EA%B0%95%EC%9D%98%EB%85%B8%ED%8A%B8)

링크에 `redirect:, forward:, 그냥 리턴의 차이` 이걸 보고 수정해 봅시다.

2021-03-12 13:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/questions/{id}")
공통적인 부분은 `@RequestMapping("/questions")` 이렇게 묶는 것도 좋을거 같에요~

2021-03-12 13:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
>          }
전체적으로 이런 부분은 향후에 `@ControllerAdvice`, `@ExceptionHandler` 등을 적용해서 
수정하면 좋을거 같네요.
뭐 일단은 넘어가도 될거 같긴 합니다~

2021-03-12 13:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
signUp()에서 validateUserID()를 호출했는데 
IllegalStateException이 발생하면
signUp() 메서드는 어떻게 해야할까요?
익셉션은 잡아서 처리를 하던지 밖으로 던지든 해야합니다.

2021-03-13 21:45 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
강의내용 복습과 <https://doublesprogramming.tistory.com/63> <https://www.baeldung.com/servlet-redirect-forward> 를 통해서 해당 내용을 학습했습니다. 
다만 변경 이유에 대한 확신이 들지 않아 질문 납깁니다. 
- 제가 forward로 변경한 이유는 https://bong-spring-boot-qna.herokuapp.com/ 라는 url이 가능하도록 한 것이 이유였습니다. 더이상 /questions로 redirect 되지 않아 forward를 return하는 것으로 변경했습니다. 

아래는 고민했던 지점을 적어보았습니다. 
- 우선 return은 고려하지 않았습니다. UserController에 선언 된  private final UserService userService; 를 가져와 읽어줘야 하기 때문에 UserController로 가는 것이 맞지 않을까 생각했습니다. 
- 남은 redirect와 forward에서 고민하던 중에 goHome의 return이 forward일 때, "/"로 갔을 경우로 나눠서 생각해봤습니다.  
    - goHome의 return이 forward일 때
        ![image](https://user-images.githubusercontent.com/73228803/111025983-2e4a1800-842b-11eb-8875-482d474b11f7.png)
       ![image](https://user-images.githubusercontent.com/73228803/111025843-3eadc300-842a-11eb-99e2-981ec0090c09.png)
    - goHome의 return이 redirect 일 때
        ![image](https://user-images.githubusercontent.com/73228803/111025972-17a3c100-842b-11eb-8b06-fb5c48f96ec5.png)
        ![image](https://user-images.githubusercontent.com/73228803/111025876-656bf980-842a-11eb-846d-3b65737141b9.png)
- 위 내용이 주요 학습 내용이긴 했지만, 브라우저가 다시 request를 보내게 되기 때문에 한번에 요청되는 forward로 바꿔야 하는지는 물음표 입니다.  
- 단지 url이 홈 디렉토리이기 때문에 /questions으로 가는 것을 사용자가 알 필요도 없으므로 forward로 변경하는 것이 맞는 것인지 질문남깁니다.

2021-03-13 21:50 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> +    @GetMapping("/questions/{id}")
UserController에만 @RequestMapping을 적용했군요! 피드백 반영하여 내용 수정했습니다.

2021-03-13 21:50 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/UserController.java
>          }
해당 내용에 대해 학습해보겠습니다~!

2021-03-13 23:23 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
해당 부분을 테스트 해봤을 때 validateUserID에서 발생한 예외가 UserController의 createUser까지 와서 try-catch에 걸려서 "redirect/"까지 되는 것을 확인하고 처리를 해주지 않은 결과 같습니다. 
- 해당 내용에 의문이 들어 학습했을 때, jvm exception handling에 따라 자동으로 call stack을 순회하며 적절한 exception handler를 찾아 처리해주기 때문이라는 것을 알 수 있엇습니다. 
-  궁금한 것은 unchecked exception의 경우 호출한 쪽으로 예외를 떠넘기는 상황일 때 throws 로 명시를 하는 것이 명확하게 보여주기 위해서 하는 것인지 궁금해서 질문 남깁니다!  
-  아니면 제가 예외 자체를 잘못쓰고 있는 것이고 이를 checked 예외로 변경해서 throws 해야 하는 것인지 확신이 들지 않아 코드 수정 전에 질문 남깁니다!

2021-03-13 23:50 UTC, bong6981 commented
안녕하세요! 말씀 주신 내용으로 수정했습니다 
주신 리뷰를 바탕으로 여러 내용을 학습할 수 있었습니다. 감사합니다. 
다만 궁금한 점이 있어 질문 드립니다! 

수정한 내용 
---

1.[ 피드백 반영] goHome의 return을 forward로 수정 
2. [ 피드백 반영 ] QuestionController에 @RequestMapping 사용 
3. [추가 수정] UserService의 validateUserId 메소드 수정 
: 해당 메소드가 userId가 아닌 name을 중복체크 해주고 있는 것을 발견하여 userId를 중복체크해주도록 했습니다. 

궁금한 부분 
---

1. redirect를 forward로 바꾼 이유
-  url "/"이 홈페이지를 나타낼 수 있도록 forward로 수정하였는데 이 이유로 코드 수정 요청을 주신 것인지 질문드립니다. 맞는 이유로 고친 것인지 확신이 들지 않습니다. 

2. unchecked 예외를 thorws로 처리 할 때 checked예외로 바꾸어야 할지 여부 
- unchecked 예외는 jvm이 예외가 발생하면 call stack을 순회하면서 해당 예외가 처리 될 곳을 찾는 다는 것을 학습했습니다. 
- 그래서 test해봤을 때 throws로 메소드를 호출한 곳으로 넘기지 않았음에도 validateUserId에서 발생한 예외가 그를 호출한 singUp메소드로 가고 또 그를 호출한  createUser메소드로 가게되어 원했던 처리인 홈 디렉토리로 가게되었음을 알 수 있었습니다. 
- throws로 명시를 하지 않더라도 예외처리가 되는 부분에서 throws를 적어주는 이유는 명확하게 표현하기 위해서 인지 궁금해서 질문납깁니다. 
- 아니면 throws를 하려면 checked 예외로 변환해서 넘겨줘야 맞게 사용하는 것인지 질문 남깁니다.  
    - 학습하다보니  [throws keyword는 checked 예외에서만 의미가 있다](https://www.geeksforgeeks.org/throw-throws-java/)고 알게되어 제가 예외 발생 자체를 잘못한 것인지 의문이 들었습니다. 

예외에 대한 이해가 부족하여 이런 질문을 남기는 것 같습니다. 더 학습해보겠습니다. 리뷰 감사하다는 말씀 드립니다!

2021-03-14 01:43 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
> 브라우저가 다시 request를 보내게 되기 때문에 한번에 요청되는 forward로 바꿔야 하는지는 물음표 입니다.

쓸데 없는 요청은 줄이는게 좋겠죠?

> 단지 url이 홈 디렉토리이기 때문에 /questions으로 가는 것을 사용자가 알 필요도 없으므로 forward로 변경하는 것이 맞는 것인지 질문남깁니다.

네 이 부분도 `/questions`로 가는거 보다 `/` 이렇게 가는게 좋을거 같아서 피드백 드렸었습니다~

2021-03-14 02:35 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
에고 이 부분은 제가 착각했네요.
수정 안하셔도 되겠네요.
unchecked exception을 던지고 향후에 `@ControllerAdvice`, `@ExceptionHandler`
적용해서 한곳에서 처리하면 될거 같네요.

검사 예외와 비검사 예외에 대해서 공부를 잘하셨는데 
저 때문에 헷갈리셨을 것 같아서 죄송하네요ㅜㅜ

2021-03-14 02:57 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
저 때문에 예외 관련되서 헷갈리셨을 까봐서 참고 할거 남깁니다. 

'토비의 스프링 1권' - `4장 예외`에 `4.3 정리`

- [토비의 스프링 4장을 읽으며](https://velog.io/@dahye4321/%ED%86%A0%EB%B9%84%EC%9D%98-%EC%8A%A4%ED%94%84%EB%A7%81-4%EC%9E%A5%EC%9D%84-%EC%9D%BD%EC%9C%BC%EB%A9%B0)
(블로그에 간단하게 정리 잘하셨네요.)

`이펙티브 자바` - `아이템 71. 필요 없는 검사 예외 사용은 피하라`

- 검사 예외는 발생한 문제를 프로그래머가 처리하여 안전성을 높이게끔 해주지만 남용 하지말고 꼭 필요한 곳에만 사용해야한다.
- 검사 예외를 던지게 되면 API 사용자는 try 블록을 추가해야 하고 자바8 스트림에서 메서드를 직접 사용하지 못하게 된다.
- 검사 예외를 회피하는 방법
   - 옵셔널을 반환
   - 검사 예외를 던지는 메서드를 2개로 쪼개 비검사 예외로 바꿀 수 있다.
      - 기존 메서드(throw 검사 예외) -> 상태 검사 메서드, 기존 메서드(throw 비검사 예외)

2021-03-14 04:26 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
아하 그렇군요! 넵 감사합니다

2021-03-14 04:32 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
@ContorllerAdvice와 @ExceptionHandler 내용을 학습하여 다음 미션에서 적용해보겠습니다~! 

전달주신 링크와 내용 감사합니다 ! 😍 아직은 이해가 부족하여 검사예외를 꼭 필요한 곳에만 사용해야 하고, 검사예외를 비검사 예외로 던지는  방법 정도로 학습했습니다. 작성 주신 자료로 더 공부해봐야할 것 같습니다!

2021-03-14 04:33 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
덕분에 오히려 더 명확하게 학습할 수 있었습니다. : )!!

2021-03-14 04:34 UTC, bong6981 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
>      private void validateUserID(User user) {
> 검사 예외와 비검사 예외에 대해서 공부를 잘하셨는데
> 저 때문에 헷갈리셨을 것 같아서 죄송하네요ㅜㅜ

덕분에 더 많은 부분에 대해서 학습할 수 있었습니다! 감사합니다 :)

2021-03-14 04:38 UTC, bong6981 commented
작성해주신 자료로 예외에 대해 더 공부해봐야겠다는 생각이듭니다. 
@ControllerAdvice, @ExceptionHandler 부분은 다음 미션에서 적용해보겠습니다. 감사힙니다. : )

2021-03-14 09:52 UTC, SANGCO approved these changes
고생 하셨습니다~

2021-03-15 00:41 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/controller/QuestionController.java
이거 forward 괜찮네요! 나쁘지 않은 생각인거 같아요.

2021-03-15 00:42 UTC, honux77 commented
봉프 공부도 열심히 하고 코딩도 잘하고 있는 것 같아요. 예상보다 잘해서(???) 다행입니다 ㅋㅋㅋ

2021-03-15 00:42 UTC, merged