[MJ]미션2: 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #59
Opened 2021-03-12 01:00 UTC by MJbae

안녕하세요~ MJ입니다. 이번 리뷰도 잘 부탁드립니다!

[배포] ([https://spring-qna.herokuapp.com/](https://spring-qna.herokuapp.com/))

(이하 주요 변경사항에 대한 요약)

## 가. H2 DB 추가 및 설정

## 나. 회원, 질문 관련 기능 수정

### 1) DB table과 객체 연동

- User Class와 DB table 연동

    → key값 설정

    → 객체 속성과 DB Column 맵핑

- Repository 설정(CrudRepository 인터페이스 상속)
- Controller에서 Repository에 대한 의존성 주입

### 2) 회원가입(질문하기) 기능 수정

- Repository의 기본 메서드 save 활용

### 3) 회원목록(질문목록) 기능 수정

- Repository의 기본 메서드 findAll 활용

### 4) 사용자조회(질문조회) 기능 수정

- ModelAndView(레거시) 제거
- Repository의 기본 메서드 findById 활용

### 4) 회원정보변경 기능 수정

- pathVariable로부터 받은 id를 기준으로 해당 User 객체(presentUser) 반환
- form tag로부터 전달 받은 User 객체(referenceUser)의 속성에 presentUser의 userId 추가
- UserRepository::delete 활용하여 presentUser 삭제
- UserRepository::save 활용하여 referenceUser 추가

## 다. Refactoring

### 1) template file 경로 변경(복수명사 → 단수명사)

### 2) 추가적으로 html 중복 코드 제거

### 3) Optional 적용

### 4) Controller에서 비지니스 로직을 Service로 분리

### 5) 회원 중복 가입 방지 로직 추가

2021-03-12 14:41 UTC, SANGCO requested changes
MJ님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-12 14:41 UTC, SANGCO commented on build.gradle
> +	compile group: 'javax.persistence', name: 'javax.persistence-api', version: '2.2'
이거는 왜 추가 하신건가요?

위와 동일하게 `compile 'javax.persistence:javax.persistence-api:2.2'` 이렇게 통일해주면 좋을거 같네요.

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/MvcConfig.java
>      public void addViewControllers(ViewControllerRegistry registry) {
MvcConfig 클래스는 config 패키지를 만들어서 그 하위에 두는게 어떨까요.

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/HomeController.java
>          return "/index";
`/` 빼셔도 됩니다.

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    Logger logger = LoggerFactory.getLogger(UserController.class);
logger를 제일 위로 올려주세요.

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +            return "/question/form";
동일하게 전체적으로 `/` 빼주시면 됩니다.
`return "question/form";`

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
향후에 벨레데이션을 학습하고 이 부분을 수정해 봅시다.

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
equals(), hashCode()를 재정의해서 이부분을 대체 할 수는 없을까요?

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/exception/UserExistException.java
> +}
![image](https://user-images.githubusercontent.com/26179444/110953609-ea073b00-838a-11eb-9b45-a632e89f1a98.png)

IntelliJ 설정을 찾아서 적용해 보아요.
[How to make IntelliJ IDEA insert a new line at every end of file?](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)
[파일 끝에 개행을 추가해야 하는 이유](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/exception/UserExistException.java
> +public class UserExistException extends RuntimeException{
커스텀 익셉션은 이렇게 만들면 되는건가요?

2021-03-12 14:41 UTC, SANGCO commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public Iterable<User> showAll() {
`showAll()` 메서드 명 좀 어색하지 않나요?

왜 리턴 타입을  `Iterable`로 하셨나요?

2021-03-12 14:41 UTC, SANGCO commented on src/main/resources/templates/common/script-references.html
> +<script src="../js/scripts.js"></script>
https://github.com/codesquad-members-2021/spring-boot-qna/pull/23#discussion_r588353714

2021-03-14 23:20 UTC, MJbae commented on build.gradle
> +	compile group: 'javax.persistence', name: 'javax.persistence-api', version: '2.2'
그렇군요! 동일한 형식으로 통일했습니다

2021-03-14 23:28 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
추후에 추가학습하고 수정해보겠습니다

2021-03-14 23:53 UTC, MJbae commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
equals, hashCode 재정의하는게 더 깔끔하네요

2021-03-15 00:02 UTC, MJbae commented on src/main/resources/templates/common/script-references.html
> +<script src="../js/scripts.js"></script>
굳이 상대경로로 처리할 필요가 없군요!

2021-03-15 00:41 UTC, MJbae commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public Iterable<User> showAll() {
1. showAll이라는 메소드명은 getAllUsers로 변경했습니다. 해당 메소드의 책임 책임은 레파지토리에서 모든 회원 목록을 가져와서 반환하는 것이므로 show라는 단어보다 get이 적절하겠네요 
2. List로 타입을 명확히 해주는게 적절하겠네요

2021-03-15 07:32 UTC, MJbae commented on src/main/java/com/codessquad/qna/exception/UserExistException.java
> +public class UserExistException extends RuntimeException{
@SANGCO 예외처리 시 커스텀 익셉션 보다 기본적으로 제공하는 예외를 사용할 것을 권장하고 있네요! 커스텀 익셉션 적용은 추후에 학습해서 사용해보겠습니다.

2021-03-15 07:34 UTC, MJbae commented
@SANGCO 코멘트 감사합니다 :) 기본적인 부분에서 부족한 것이 많이 있다는 것을 알고 매울 수 있었습니다.

2021-03-17 11:54 UTC, SANGCO requested changes
고생 하셨습니다~

2021-03-17 11:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    List<User> findAll();
이게 꼭 필요할까요~

2021-03-17 11:54 UTC, SANGCO commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +    List<Question> findAll();
이게 꼭 필요할까요~

2021-03-18 00:22 UTC, MJbae commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    List<User> findAll();
findAll의 기본 반환 타입, Iterable<> 대신 List<>를 사용하기 위해 override해서 구현했습니다. 
다음 미션을 진행하면서 더 좋은 방법을 고민해보겠습니다 :)

2021-03-19 01:25 UTC, merged