[August] 미션2: 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #60
Opened 2021-03-12 02:54 UTC by Polynomeer

### 미션 2: 데이터베이스 활용

안녕하세요, 코드스쿼드 백엔드 반의 August입니다. 항상 상세하고 좋은 리뷰 너무 감사합니다! 이번 과제는 주어진 요구사항인 H2 DB 설정 및 적용, 회원가입 및 회원목록 기능 구현, 개인정보 수정 기능(미션1에서 진행한 것을 약간 수정) 했습니다.

- 서버 주소 : https://august-qna.herokuapp.com/

### 구현 내용

미션1로부터 변경된 부분만 언급하겠습니다!

- QuestionController : 기존에 List의 size()로 id를 관리하던 부분은 모두 없어졌습니다. (@GeneratedValue)
- UserController : 기존에 user가 null인지 체크하는 부분은 service 계층으로 넘겨주었습니다. update()에서는 패스워드가 일치하는지 확인하고 일치한다면 수정하도록 했습니다.
- Question : id를 자동으로 증가하도록 했고, 나머지 칼럼들은 각 역할에 맞게 일부는 not null 제한을 두었습니다.
- User : 마찬가지로 id는 자동증가하고, 나머지 칼럼의 속성도 애노테이션으로 지정했습니다. matchPassword를 추가하여 패스워스 일치여부를 확인합니다.
- QuestionRepository/UserRepository : JPA를 적용하는 방식으로 변경했습니다.
- QuestionService : 대부분 QuestionRepository에서 제공하는 JPA 메서드를 그대로 전송해주는 역할만 하지만 findQuestionById에서는 Optional을 검증하는 로직을 포함하여 컨트롤러에서는 코드상에 변경사항이 없도록 했습니다.
- UserService : 마찬가지로 findUserById만 Optional 검증 로직이 포함되어 있습니다.

2021-03-12 15:51 UTC, sonypark requested changes
안녕하세요 August, 리뷰어 소니 입니다.😊
미션2 구현하시느라 수고 많으셨습니다.
개선할 부분에 대해 코멘트 남겼으니 확인 부탁드립니다~

1. 회원 정보 수정이 안 되는데 확인부탁해요
    - 아래 조건대로 작동하는지도 확인해주세요~
    - 비밀번호, 이름, 이메일만 수정할 수 있으며, 사용자 아이디는 수정할 수 없다.
    - 비밀번호가 일치하는 경우에만 수정 가능하다.
 2. Controller와 Service 에 있는 필드에 final을 붙여주세요.
 3. DTO에 대해 공부해보세요

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String question(Question question) {
request 데이터 바인딩을 Entity로 직접하는 것은 권장하지 않습니다. 이런 경우 DTO를 만들어 해결합니다. 한 번 공부해보세요~

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @PostMapping()
```suggestion

    @PostMapping
```
괄호는 없어도 될 것 같네요~

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +public interface QuestionRepository extends CrudRepository<Question, Long> {
여기는 CrudRepository를 사용하셨네요? UserRepository와 다르게 사용하신 이유가 있나요?

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return questionRepository.findAll();
Iterable을 반환하는것보다 List로 반환하는게 좋지 않을까요?

[Spring-Data JPA CrudRepository returns Iterable, is it OK to cast this to List?](https://stackoverflow.com/questions/34702252/spring-data-jpa-crudrepository-returns-iterable-is-it-ok-to-cast-this-to-list)

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>      }
http 예외를 발생시키는게 맞을까요??

2021-03-12 15:51 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +
이 로직은 userService에 update 메서드로 있는게 더 낫지 않을까요~?

2021-03-12 16:07 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @GeneratedValue
GeneratedValue의 strategy의 디폴트 값은 무엇이고 어떤걸 사용하면 좋을지도 공부해보세요~

2021-03-13 14:12 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +public interface QuestionRepository extends CrudRepository<Question, Long> {
그냥 참고하다가 잘 모르고 쓴 것 같은데, 팀원들과 리뷰하면서 조사해보다가 JpaRepository가 CrudRepository를 상송한다는 것을 알게 되었습니다. 그래서 JpaRepository로 변경하여 일관성을 지키도록 하였습니다.

2021-03-13 14:21 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return questionRepository.findAll();
List에서 Iterable로의 변경은 보장되지만, Iterable에서 List로의 변경은 보장이 안되는군요! 즉,  Iterable에서 List로의 캐스팅이 실패한다면 런타임 중에 에러가 발생한다는 것이므로 바람직하지 않다는 것이군요. 감사합니다!

2021-03-13 14:25 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>      }
의미를 정확히 모르고 사용했었는데, 현재는 맞지 않은 것 같아서 `NoSuchElementException`로 변경했습니다!

2021-03-13 14:46 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @GeneratedValue
- 기본값은 `GenerationType.AUTO`이며 `Generation.IDENTITY`와는 비슷하지만 유일한 차이점은 별도의 identity generator가 타입 계층별로 관리되므로 생성된 값은 타입 계층별로 고유하다는 것입니다.
- `GenerationType.AUTO`를 사용할 경우 save() 수행시 insert 쿼리 전에 select, update 쿼리가 사용되는데 이 때 별도의 트랜잭션을 사용하여 추가적인 Connection을 사용하게 된다고 합니다. 이 경우 트랜잭션 끝나기 전까지 Connection이 반납되지 않기 때문에, 동시에 접근할 경우 DeadLock이 발생할 수 있습니다.
- 이 정도만 학습했고, IDENTITY를 사용하도록 변경했습니다!
- https://www.objectdb.com/java/jpa/entity/generated
- https://lion-king.tistory.com/entry/JPA-JPA-Id-GenerationTypeAUTO-IDENTITY
- https://www.baeldung.com/hibernate-identifiers

2021-03-13 14:50 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +
네, UserService::update를 추가하여 이 부분을 서비스 계층에서 담당하도록 변경했습니다!

2021-03-13 15:21 UTC, Polynomeer commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String question(Question question) {
나름대로 학습한 내용으로는 여러가지 목적이 있겠지만, 현재 User와 Question이 가진 필드가 뷰에서 모두 사용되므로 조금 효용성을 느끼기에 부족한 것 같습니다. 그리고 제가 이것을 적용하기에 아직 이해도가 부족한 것도 있습니다! 혹시 이 부분을 다음 단계를 진행하면서 반영해도 괜찮을까요? ;(
- https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application
- https://medium.com/the-resonant-web/spring-boot-2-0-project-structure-and-best-practices-part-2-7137bdcba7d3
- https://www.baeldung.com/spring-dynamic-dto-validation
- https://medium.com/msolo021015/dto-data-transfer-object-%EC%97%90-%EB%8C%80%ED%95%B4-fbbd8b472c2b
- https://dbbymoon.tistory.com/4
- https://auth0.com/blog/automatically-mapping-dto-to-entity-on-spring-boot-apis/

2021-03-13 15:28 UTC, Polynomeer commented
1. 회원 정보 수정
- 회원 정보 수정이 되는것을 확인했고, 비밀번호가 맞지 않으면 별다른 문구는 없지만 수정하지 않고 돌아갑니다. 현재 `@NotEmpty`나 `@NotBlank` 애노테이션을 사용해보았는데, 이 부분에서 해당 경우가 발생할 때 500에러 페이지가 나옵니다. 
- 하지만 이 페이지가 뜨지않고 처리해주려면 ajax로 입력폼에 대한 검증을 실시간으로 하거나, 프론트 엔드에서 입력폼에 대한 검증을 하고 알림창을 띄우는 방법 밖에는 떠오르질 않네요..

2. final
- 주입받는 객체에 대하여 모두 `final`을 붙여주었습니다!

3. DTO
- DTO에 대한 개념이 어렴풋이 생겼습니다만, 현재는 엔티티의 필드를 모두 뷰에서 사용하는 상황이라 잘 와닿지가 않아서 다음 단계로 미뤄야할지 모르겠습니다.

2021-03-14 06:22 UTC, sonypark approved these changes
August 안녕하세요. 리뷰 반영하신 것 확인했습니다.

질문 주신 것에 대한 답변은 아래 링크를 참고하시면 도움이 될 것 같습니다.
1. @NotEmpty나 @NotBlank 애노테이션을 사용해보았는데, 이 부분에서 해당 경우가 발생할 때 500에러 페이지가 나옵니다.
-> ControllerAdvice로 예외처리를 하는 방법을 적용해보세요
3. 엔티티 대신 DTO를 사용하는 이유
- Domain 에 있는 필드가 모든 request, response 에 필요하지 않음에도 불필요하게 사용되는 것을 방지하기 위함이고
- API 의 request 와 response 에 형식을 맞추기 위해 domain 이 수정되서는 안되기 떄문 + domain의 변화가 api 스펙의 변화로 이어져서도 안되기 때문입니다.

일단 이번 미션은 여기서 approve 하겠습니다. 위에 언급한 부분은 다음 미션하면서 적용해보세요~ 수고하셨습니다!

2021-03-14 06:22 UTC, sonypark commented on src/main/java/com/codesquad/qna/domain/User.java
> +    @NotBlank(message = "Name may not be blank")
둘 중에 하나만 있어도 될 것 같은데요, 어떤걸 지우는게 좋을까요?

2021-03-14 06:22 UTC, sonypark commented on src/main/java/com/codesquad/qna/domain/User.java
> +    @NotBlank(message = "Password may not be blank")
여기도 마찬가지

2021-03-14 06:22 UTC, sonypark commented on src/main/java/com/codesquad/qna/service/UserService.java
>      }
`NoSuchElementException` 보다는 `IllegalArgumentException`이 더 적절하지 않나 생각되네요.

- [How to resolve the "java.util.NoSuchElementException" in Java](https://www.educative.io/edpresso/how-to-resolve-the-javautilnosuchelementexception-in-java)
- [What is the cause of NoSuchElementException and how can we fix it in java?](https://www.tutorialspoint.com/what-is-the-cause-of-nosuchelementexception-and-how-can-we-fix-it-in-java)

2021-03-14 15:50 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/domain/User.java
> +    @NotBlank(message = "Name may not be blank")
확인을 해보니 `@NotBlank`은  가장 validation 강도가 높은 것으로 null 과 "" 과 " " 모두 허용하지 않습니다. 따라서 userId와 password에 대해서는 `@NotBlank`를 적용하도록 했습니다.

2021-03-14 15:51 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/domain/User.java
> +    @NotBlank(message = "Name may not be blank")
반면, Question에서는 공백은 허용하도록 하기위해서 `@NotEmpty`만 설정했습니다.

2021-03-14 16:04 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/service/UserService.java
>      }
findById에서 발생할 수 있는 예외에 대한 것은 `IllegalArgumentException`이 더 맞는 것 같아요!
- https://www.tutorialspoint.com/how-to-solve-an-illegalargumentexception-in-java#:~:text=An%20IllegalArgumentException%20is%20thrown%20in,been%20passed%20an%20illegal%20argument.&text=It%20is%20an%20unchecked%20exception,or%20a%20constructor's%20throws%20clause.

2021-03-14 16:20 UTC, Polynomeer commented
리뷰 정말 감사합니다! DTO의 적용, 그리고 `@ControllerAdvice`를 통한 예외처리는 좀 더 학습해보겠습니다.

2021-03-15 06:49 UTC, merged