[Robin] 미션2 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #61
Opened 2021-03-12 03:23 UTC by malaheaven

안녕하세요 로빈입니다 😄 미션2 데이터베이스 활용 구현 완료하여 PR 보냅니다. 
먼저, 제 코드를 리뷰해주시는 리뷰어님에게 감사를 드립니다.

#### 배포URL
https://springboot-qna.herokuapp.com/

#### 미션 진행
해당 미션은 포비님 영상을 따라하는 느낌으로 진행했습니다. 
미션2 구현 초반에는 DB 조회 부분을 findById().get()을 사용했는데, 이렇게 사용하면 결과값이 null일 경우 NoSuchElementException이 발생한다는 것을 알게 되어, 이에 대해 값이 없을 경우 IllegalArgumentException에 대한 예외를 발생 시키도록 구현했습니다.

#### 구현 목록
1. H2 적용
2. User,Question 클래스를 DB 테이블에 매핑
3. 각 데이터에 대한 CRUD 구현( 각 Repository 클래스 생성하고, JpaRepository 상속)
4. 각 Contorller에서 Repository 사용
5. 회원수정 비밀번호 일치하면 수정 가능하도록 변경
6. hidden으로  POST 대신 PUT method를 전송할 수 있도록 변경

2021-03-12 16:06 UTC, sonypark requested changes
안녕하세요 Robin, 리뷰어 소니 입니다.😊
링크 들어가서 확인해보니 요구사항대로 잘 동작하네요👍
개선이 필요한 부분에 간단히 코멘트 남겼으니 확인부탁드릴게요~~

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
의존관계 주입은 필드 주입보다는 생성자를 통한 주입을 권장합니다.
왜 그런지 이유를 찾아보세요. 

인텔리제이도 경고창을 띄우네요 :)
![image](https://user-images.githubusercontent.com/34808501/110965102-3bb5c280-8397-11eb-9152-7d75cf9484b1.png)

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
request 데이터 바인딩을 Entity로 직접하는 것은 권장하지 않습니다. 이런 경우 DTO를 만들어 해결합니다. 한 번 공부해보세요~

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("")
```suggestion

    @PostMapping
```

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/users")
👍

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            updateUserInfo.setPassword(user.getPassword());
이 부분은 필요한 로직인가요??

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
이 메서드를 사용할 일이 있을까요?

2021-03-12 16:06 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @GeneratedValue
GeneratedValue의 strategy의 디폴트 값은 무엇이고 어떤걸 사용하면 좋을지도 공부해보세요~

2021-03-14 09:42 UTC, malaheaven commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("")
헉! 이렇게도 되는군여 고쳤습니당

2021-03-14 09:59 UTC, malaheaven commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            updateUserInfo.setPassword(user.getPassword());
제가 구현하고자 했던 것은 비밀번호 변경 란에 적힌 비밀번호가 없으면, 원래 기존 비밀번호를 가져가고 싶어서 추가한 코드입니다. 삭제하는 것이 좋을까요?

2021-03-14 10:11 UTC, malaheaven commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
엇,, 그러네용 어디서 받아서 id를 넣어주는게 아닌, 데이터가 들어가면 주키가 auto increment 해주는 데, 과거의 저는 왜 이 코드를 생성했을까요..ㅋㅋ set 메서드 삭제했습니당

2021-03-14 11:04 UTC, malaheaven commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @GeneratedValue
이부분 자동생성 전략을 데이터베이스에 위임하는 것으로 변경했습니다. 근데 찾아보니 H2는 시퀀스 전략도 사용하는 것 같네요? 우선 전 IDENTITY 전략을 선택했습니다. H2가 Auto increment가 가능하다면 딱히 지금은 시퀀스를 생성할 이유는 없는 것 같아서요. 제가 공부한 내용이 맞을까요? 확인 부탁드립니다.

2021-03-14 11:25 UTC, malaheaven commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
넵넵 이부분 변경했습니다. 이 부분에 대해서 이유를 찾아보는데 헤롱헤롱하네요 @_@
찾아본 내용에서 의존관계 주입은 생성자를 통한 주입을 권장하는 이유가 여러가지가 있었지만, 내용을 전부 이해하지는 못했습니다.

일단, 필드 주입은 의존성 주입을 하기가 쉬워 단일 책임의 원칙에 위반되고, 의존성을 명확하게 확인하기 힘들게 되고, 필드 주입은 final을 선얼할 수 없어 객체가 변할 수 있네요. 찾아보니 다른 이유도 많았는데, 지금은 잘 이해가 되지 않네요ㅜ 더 공부를 해야할 것 같습니다. 😢

2021-03-14 12:29 UTC, malaheaven commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
헉 그렇군요:) 관련 내용 찾아보니 많은 내용들이 나오네요.. 이 경우 포비님 영상을 따라 진행한 것이고, 포비님 따라하기에 초점을 맞춰 진행하고 싶은 데 괜찮을까요?

2021-03-14 12:33 UTC, malaheaven commented
안녕하세요 @sonypark  해당 리뷰 반영했습니다. 반영된 코드 리뷰 부탁드립니다:)

덧, 저번 misson1 리뷰와 함께 이번 misson2 리뷰도 진행해주셔서 감사합니다!

2021-03-14 12:38 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @GeneratedValue
네 h2도 명칭은 다르지만 auto increment 형식의 ID 생성을 지원합니다.
아래 링크를 참고해주세요~
```sql
// H2
create table Member (
  id varchar(255) generated by default as identity,
  ...
)
// MySQL
create table Member (
  id varchar(255) auto_increment,
  ...
)
```
- [[JPA] 기본키(PK) 매핑 방법 및 생성 전략](https://gmlwjd9405.github.io/2019/08/12/primary-key-mapping.html)
- [auto increment ID in H2 database](https://stackoverflow.com/questions/9353167/auto-increment-id-in-h2-database)

2021-03-14 12:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            updateUserInfo.setPassword(user.getPassword());
아하 이메일만 변경하고 싶은 경우 그럴 수 있겠네요!
그럼 의도하신대로 남겨두시면 될 것 같아요.
다만 빈문자열이나 공백을 체크하는 로직도 추가되면 좋겠네요. ""가 아닌 "   "이 들어오면 어떻게 될까요?

2021-03-14 12:42 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
네네 다음 미션부터 공부하며 적용해주세요~~

2021-03-14 12:42 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +
logger는 최상단에 위치시키는게 일반적입니다:)

2021-03-14 12:43 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private final UserRepository userRepository;
👍

2021-03-14 12:44 UTC, sonypark approved these changes
Robin~ 피드백 반영하느라 수고하셨어요!💯
공부가 많이 되었길 바랍니다.
이번 미션은 여기서 approve 하겠습니다
다음 미션 진행해주세요!👍

2021-03-14 15:49 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
의존성 주입 부분은 아직 이해하기 어려우실 수 있어요! 괜찮습니다.
중요한 부분인만큼 앞으로 공부하며 많이 접할 내용이니 점점 이해하게 되실거에요😊

2021-03-15 06:49 UTC, merged