[마르코] Mission2 데이터베이스 활용 PR 요청드립니다.
codesquad-members-2021/spring-boot-qna pull request #62
Opened 2021-03-12 07:28 UTC by 95degree

안녕하요🤞 백엔드반 마르코 입니다. 
미션2 데이터베이스 활용 PR 요청입니다. 이번 미션도 저번과 마찬가지로 구현에 초점을 두고 했습니다.
소중한 리뷰 감사합니다. 😃😃😃😃

### 구현
- 사용자, 질문 repository 생성
- db에 추가 및 조회
-put으로 회원정보 수정 사항 전달

2021-03-12 16:25 UTC, sonypark requested changes
안녕하세요 마르코, 리뷰어 소니 입니다.😊
미션2 구현하느라 고생 많으셨습니다.
링크 통해서 테스트 해본 결과 몇가지 문제를 발견했는데 확인 후 수정 부탁드릴게요~~

1. 회원 정보 수정창에 버튼이 '회원가입' 이네요..?🤭
![image](https://user-images.githubusercontent.com/34808501/110968335-bcc28900-839a-11eb-80a7-fa0c85c12e5e.png)

2. 회원 정보 수정이 안 되는데 확인부탁해요
    - 아래 조건대로 작동하는지도 확인해주세요~
    - 비밀번호, 이름, 이메일만 수정할 수 있으며, 사용자 아이디는 수정할 수 없다.
    - 비밀번호가 일치하는 경우에만 수정 가능하다.

3. 현재 컨트롤러에서 repository를 갖고 로직을 처리해주고 있는데, service로 분리해보는 것도 고려해보세요

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private QuestionRepository questionRepository;
[comment](https://github.com/codesquad-members-2021/spring-boot-qna/pull/61#discussion_r593278893) 확인하시고 마르코도 이 부분 공부해보시길 바랍니다 :)

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
request 데이터 바인딩을 Entity로 직접하는 것은 권장하지 않습니다. 이런 경우 DTO를 만들어 해결합니다. 
'request 데이터 바인딩 DTO' 키워드로 공부해보세요

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>          catch (IndexOutOfBoundsException e){
이 예외는 언제 발생하나요..?

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>              return "qna/show";
`findById(id).get()` 과 같은 코드는 사용하면 안 됩니다.
`orElseThrow()` 를 사용해주세요~ 왜 그런지도 공부해보세요:)

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        User targetUser = userRepository.findById(id).get();
여기도 마찬가지. .get()을 사용하는 경우는 매우 드물답니다.

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        targetUser.setUser(updateUser);
```suggestion
        targetUser.update(user);
```
set은 setter 메서드에만 한정에서 사용해주세요.

2021-03-12 16:25 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +
👍
IDENTITY 전략을 사용하신 이유가 있나요?

2021-03-15 12:49 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private QuestionRepository questionRepository;
필드에 주입을 하게 되면 외부에서 의존관계가 보기가 어렵고 클래스가 서로를 참조하면서 돌고 도는 순환참조를 조기에 방지 할 수 있다는 장점이 있네요 . 
그 외에 단일책임의 원칙 위반 ,DI 컨테이너의 결합성과 테스트 용이성과 같은 장점 키워드들이 있었는데 현재는 잘 와닿지 않아 이해가 어려운 부분이였습니다.

2021-03-15 13:00 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>          catch (IndexOutOfBoundsException e){
배열의 범위를 벗어났을때 일어나는 에러인데 이전에 list로 question을 관리할때 사용했는데 현재는 필요가 없겠네요 수정완료했습니다.

2021-03-15 13:06 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>              return "qna/show";
get()을 사용할 경우 결과값이 null일때 에러가 발생하게 되는데 orElseThrow()를 사용하면 예외를 던져줄 수 있네요 !!

2021-03-15 13:06 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        targetUser.setUser(updateUser);
수정 완료했습니다.

2021-03-15 13:11 UTC, 95degree commented on src/main/java/com/codessquad/qna/domain/Question.java
> +
예제에 나와있어 따라치기만 했는데 코멘트 주신 덕분에 많은 것을 알게됬습니다. 😃😃😃😃
IDENTITY 전략은 DB에 기본키 생성을 위임해주고, DB 값이 들어간 이후에 확인 할수 있다. 그리고 테이블에 종속적이기 때문에 이번 미션에서는 여러 테이블에 하나의 ID를 사용할 필요가 없기에 IDENTITY 전략이 좋다.
이 정도로 요약을 해봤는데 혹시나 빠뜨린 것이 있으면 코멘트 부탁드립니다.🙌

2021-03-15 13:12 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionRepository.save(question);
데이터 바인딩은 사용자의 입력값을 도매인 객체에 동적으로 할당 해주고 DTO는 계층간 데이터 교환을 위한 자바 beans라는 것을 알게되었습니다. 
하지만 아직 코드로 짜는건 어려운 상태라 다음 미션을 해나가면서 고쳐보겠습니다.

2021-03-15 14:41 UTC, sonypark approved these changes
마르코 리뷰 반영하느라 수고하셨어요!👍
다음 미션 진행해주세요! 😁

2021-03-15 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      }
사실 여기서 @Autowired가 없어도 정상적으로 동작합니다.
왜 그럴까요? 지금 당장은 아니라도 찾아보세요 ㅎㅎ

2021-03-15 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
왜 이 예외가 발생했는지 message도 넣어주면 더 좋겠네요.

2021-03-15 14:41 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.create(question);
다음 미션 하면서 DTO도 공부해보세요😊

2021-03-17 06:32 UTC, 95degree commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
다음 미션때 추가하도록 하겠습니다. !!!

2021-03-17 06:33 UTC, 95degree commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.create(question);
넵 감사합니다. 이번 리뷰를 통해 많은 것을 배웠습니다. 🤞🤞🤞🤞😊😊😊

2021-03-17 23:56 UTC, merged