[Bat] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #64
Opened 2021-03-12 15:32 UTC by kjk402

안녕하세요, 웹백엔드과정 Bat입니다.

미션3 구현하여 pull request 드립니다.

• 미션3 구현 URL : https://bat-spring-qna.herokuapp.com/

• 로그인 기능 추가 : 로그인 기능을 추가 & 로그인 한 상태에서만 질문 작성할 수 있도록 구현하였습니다.

• Answer (답변 기능) 추가 : 질문에 대한 답변을 추가할 수 있습니다.

• Logger 적용하였습니다.
                                            
• mission3에서는 NullException 처리 관련하여 coco의 조언으로 validation 클래스를 생성하였습니다. 

이번 미션 역시 클린코드를 신경쓰기보다는 미션의 요구사항 구현에 집중하여 코드가 많이 부족합니다. 제가 확인하였을 때는 요구사항 모두 구현된 듯 합니다. (아닐수도 있습니다 ;;)

리뷰 잘 부탁드립니다.
감사합니다.

2021-03-13 03:47 UTC, wheejuni requested changes
3단계까지 잘 구현해 주셨습니다. 👍 💯 
코멘트 중 말씀드린 `Service` 클래스 구현 및 사용은 꼭 한번 도전해 보시길 권해 드립니다.
다른 질문 있으시면 언제든지 남겨 주시고요. 감사합니다! 🥇

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private final QuestionRepository questionRepository;
이제는 `Service` 클래스들을 구현해보심이 어떠한가요? 
`AnswerService`, `QuestionService` 구현해서 컨트롤러에서 직접 레포지토리 접근하지 않는 구현을 시도해 보세요.
`new Answer()` 와 같은 생성자 호출이나 일체 비즈니스 로직을 다 `Service` 에 위임하시구요.

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerRepository.save(answer);
이것도 `AnswerService` 에서요!

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
ㅎㅎㅎ 복붙하시더라도 필요한 부분은 꼭 수정해주세요~

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        logger.info(question.toString());
`logger` 를 통해 로깅하실때는 정확한 템플릿을 가지고 일목요연하게 로그 내용을 알아볼 수 있도록 구현하시는 게 좋아요.
그리고 로거는 스트링 템플릿을 지원합니다. 
http://dveamer.github.io/backend/HowToUseSlf4j.html 를 읽어 보시고 참고해보세요.

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private final String LOGOUT = "/logout";
과도한 분리라고 생각하고요, 오히려 애노테이션 속에 위치하는 것이 더 가독성이 좋습니다.

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private static final DateTimeFormatter pattern = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
대문자로 변수명이 붙여져야 하지 않을까요? 
그리고 무엇을 위한 패턴인지가 변수명을 통해 드러나면 좋겠습니다.

```suggestion
    private static final DateTimeFormatter PATTERN = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int answerCount;
`Answer` 와 일대다 관계로 접근이 가능한데, 이 필드도 필요한가요?

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/valid/QuestionValidation.java
> +    public static void validQuestion(Question question) {
그래도 나름 `Validation` 인데 뭔가 리턴 타입이 있어야 하지 않을까요?

2021-03-13 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/valid/QuestionValidation.java
> +            throw new NullPointerException(error);
빈 문자열과 `null` 문자열은 조금 다른 것 같아서 적합한 예외인 것 같지 않습니다.

2021-03-13 04:52 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private static final DateTimeFormatter pattern = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
FORMATTER_PATTERN 으로 변수명 변경하였습니다.

2021-03-13 04:53 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private final String LOGOUT = "/logout";
넵 제거하였습니다.
저번 리뷰에서 피드백받은 부분이라 두번이상 사용되는 뷰네임 상수처리 하였습니다.
private final String CONFIRM_INFO = "/confirm/{id}";
 private final String UPDATE_INFO = "/update/{id}";
이 부분도 그냥 제거하는 것이 좋을까요??

2021-03-13 04:55 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
ㅎㅎ 수정하였습니다. 복붙 조심히 사용하겠습니다.

2021-03-13 04:56 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        logger.info(question.toString());
네. SLF4J  logger 사용으로 변경하였습니다. 

유용한 링크 주셔서 감사합니다. ~

2021-03-13 05:08 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int answerCount;
List 부분 말씀이신가요? 
하나의 question이 여러가지의 answer 를 list 형태로 가진다라는 의미여서 삭제할 수 없지않나요?

2021-03-13 05:26 UTC, kjk402 commented on src/main/java/com/codessquad/qna/valid/QuestionValidation.java
> +            throw new NullPointerException(error);
null값과 빈문자열 두가지 체크하도록 수정하였습니다.

2021-03-13 05:48 UTC, kjk402 commented on src/main/java/com/codessquad/qna/valid/QuestionValidation.java
> +    public static void validQuestion(Question question) {
e2ebd37 의 형태로 변경하였습니다.
complete null check 값을 반환하여 logger로 나타냅니다.

2021-03-13 07:04 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerRepository.save(answer);
네 수정하였습니다. ^^

2021-03-13 07:09 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    private final QuestionRepository questionRepository;
리뷰어님 말씀해주신 바와 같이 Service 구현하였습니다.
Answer, Question, User 총 세개의 service 생성 후 확인하였습니다.

Service 분리가 낯설어서 contorller에서 직접 repository 접근하는 부분만 수정하였습니다.

2021-03-13 07:14 UTC, kjk402 commented
브라이언께서 남겨주신 피드백들 확인하여 수정하였습니다.

수정 후 의문이 생긴 부분은 validation 리턴값을 string으로 정하고, log에서 보여주는 방식이 조금 어색합니다ㅎㅎ. 이 방법의 문제가 있다면 말씀해 주시면 감사하겠습니다. 

리뷰 감사드립니다. ~~

2021-03-13 14:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private final String LOGOUT = "/logout";
@kjk402 혹시 제 리뷰는 아니었죠? ㅎㅎ 개발자마다 생각이 다를 수 있는 부분인데 전 그런 방향의 구현을 해본 적은 아직 없어요. 
각자의 판단에 따르면 될 것 같아요.

2021-03-13 14:26 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int answerCount;
네 맞죠. 그래서... `answers.size()` 로 카운트를 세면 될 거 같은데 `answerCount` 가 또 필요하냐는 말슴이었습니다.

2021-03-13 14:30 UTC, wheejuni commented
@kjk402 validation의 목적이 어디에 있을까요? 로직 중에 부적절한/데이터 정합성을 깨는 데이터가 온다면 그에 맞는 예외 로직을 수행하기 위해 validator를 구현하신 것 아니었나요?
그런 관점에서 바라본다면 저도 validator가 에러 메세지를 만들고 logger로 찍는 방식의 구현은 반대합니다. 그보다 더 중요한 역할을 해야죠.
제가 느끼기엔 validator라면 `ValidationResult` 나 `boolean` 을 내려주고, validator에 의존한 객체가 그런 로직을 구현해줘야 할 것 같은데요.
Spring이 제공하는 validation result인 [Errors](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/Errors.html) 인터페이스를 살펴보세요. 밸리데이션의 결과물로는 이런 클래스가 필요합니다. 원래는요.

2021-03-13 14:43 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int answerCount;
제가 잘못 이해했었네요. ㅎㅎ
f48d0ae 에서 필드 삭제하였습니다.

감사합니다.

2021-03-14 10:22 UTC, kjk402 commented
@wheejuni validation 을 단지 예외 확인용으로만 작성한 점이 부족했습니다. 
다음 단계에서는 스프링에서 기본으로 제공되는 validation인 NotNull 혹은 NotEmpty 어노테이션에 대해 공부, 사용해보겠습니다. 
아니면 말씀해주신 바와 같이 boolean 이나 ValidationResult 으로 리턴값을 교체해보도록 하겠습니다.

Validation 구현을 간단히 생각한 점 죄송합니다.;; 유효성 검증과정과 그에 따른 예외처리가 복잡하고 어려운 것 같습니다. 이 부분 중점적으로 생각하며 코딩하겠습니다.

감사합니다.

2021-03-14 10:25 UTC, wheejuni approved these changes
👍

2021-03-14 10:25 UTC, merged