[Jung] 미션2: 데이터베이스 활용 PR입니다
codesquad-members-2021/spring-boot-qna pull request #65
Opened 2021-03-12 18:37 UTC by rla36

https://jung-spring-boot-qna.herokuapp.com/

안녕하세요 Jung입니다.
두번째 미션 진행하면서 전혀 모르던! db에 대해 조금이나마 공부해볼수있어서 좋았습니다!
기본개념에 대한 이해도가 낮아 시키는대로 repository등을 만들면서도
스프링 내에서 작동 원리..?를 완벽히 알지 못한채 미션을 진행해 완성도가 떨어집니다..ㅎㅎ
코드에서 repository, domain, controller의 역할에 대한 이해가 얕아 보이는 부분있으면 지적 부탁드립니다!!!
검색 키워드도 추천해주시면 감사하겠습니다!

미션하면서 고민했던 부분들은 다음과 같습니다.

User
User클래스의 Column들에 대한 @column(nullable=false, length=20) 20자 길이제한을 해제했습니다. 길이를 제한하면 이 길이를 넘어가는 input을 입력했을 시 에러페이지로 넘어갑니다. 그런데 저는 그 페이지에서 팝업형식(?)으로 에러 메세지를 사용자에게 보여주는 방식을 구현하고 싶어서 일단은 길이제한을 해제했습니다.
UserController
findById(id)에서 Optional을 리턴하기 때문에 만약 null이 리턴될시(orElseThrow) 지정된메세지(해당id의 사용자가 존재하지 않습니다)로 예외를 발생시키도록 메서드를 구현했습니다.
userRepository.findById(id).get()을 하면 User을 리턴하고, User이 없어 null일 경우 NoSuchElementException을 던집니다.
get메서드를 사용하면 optional의 기능을 충분히 못쓰는 것이기 때문에 get을 쓰지 말라는 조언을 들었습니다. get을 쓰나 orElseThrow를 쓰나 NoSuchElementException을 던지지만, orElseThrow는 메세지를 설정할수있기 때문에 get 대신 쓰는 것이 제가 이해한 것이 맞는지요..?
리뷰해주셔서 감사합니다~

--------------------------------------------------

디온.. 
conflict났던 것 잘 해결했었는데 해결과정에서 커밋을 잘못 수정한 것을 고치면서
미션 2 커밋들이 전부 날아가는 실수를 저질러버렸습니다.. (정확히는 미션2가 마지막 한개의 커밋만 가리키게 됐습니다..)
불가피하게 새로 PR 보냅니다.. 최대한 원래 PR내에서 해결하려했으나 잘 안됐어요.. 죄송함다..

(1. 바꾸려는 커밋 바로 위 커밋에 checkout
2. newBranch만들고 바꾸려는 커밋 cherry-pick해서 수정(git commit --amend)
3. 바꾸려는 커밋에 checkout해서
   새로운 tmpbranch만들기
4. tmpbranch 이후부터 mission2 커밋까지 newbranch 로 rebase하고
(git rebase --onto newbranch1 tmpbranch mission2)
5. mission2를 branch -f해서 가리키게 함 (git branch -f mission2)
6.  원격에 반영 ( git push origin mission2)
이것이 저의 야심찬 계획이었으나 장렬히 실패했습니다.) 

> properties conflict해결 … h2 데이터베이스 의존성 추가와 설정
4e161af 커밋은 conflict 해결 과정에서 잘못 커밋되었는데요, (기존 커밋을 수정해버림)
원래는 내용인 <h2 데이터베이스 의존성 추가와 설정> 요 부분이 커밋 타이틀입니다.
수정을 시도하고 있으나 잘 안될 경우 참고 부탁드립니다!
-> 이것을 수정하려다 재PR 날리게 됐습니다.. git 좀더 연습해봐야겠어요 

오늘도 리뷰 감사합니당

2021-03-13 13:44 UTC, ksundong requested changes
안녕하세요! Jung!! 리뷰어 Dion입니다.

제가 오늘은 조금 여유를 즐기느라 이제야 리뷰해드려서 죄송합니다.
이번 단계는 사실 특별하게 큰 요구사항은 없지만, 그래도 피드백을 드릴 부분이 있어서, **변경 요청** 드립니다.

## 애플리케이션 리뷰

- 회원 정보 변경시 비밀번호를 검증하는 절차가 없네요. 추가해주시면 감사하겠습니다~

## 피드백

- 커밋 전 정렬을 꼭 수행해주시고, 어려우시면 Auto Formatting을 적용해주세요.
- Java8에서 추가된 날짜/시간 API를 사용해주세요.
- Controller/Service/Repository 구조에 대해서 한 번 학습해보시고, Service 부분을 분리해보세요.
- 네이밍이 어느 부분은 좋은데, 어느 부분은 참 아쉬워요. 좀 더 신경써주세요!
- 통행금지 표시 꼭 고쳐주세요.

미션 2 진행해주시느라 고생많으셨고, 코멘트 드린 부분만 고쳐주시고 다음 단계 진행해주시면 될 것 같아요!
고생하셨습니다~ 질문하시고 싶거나, 도움이 필요한 부분, 토론하고 싶은 부분 등에 대해서 코멘트 남겨주세요~

2021-03-13 13:44 UTC, ksundong commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
버전을 명시하지 않으면 어떤 버전이 import 될까요?
한 번 알아봅시다~

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private QuestionRepository questionRepository;
Spring의 Injection 방식에 대해서 공부해보시고,
이를 한 번 생성자 인젝션 방식으로 수정해보세요~

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
이런 메서드는 Utility성 클래스를 만들어서 사용하는 편이 좋구요.
Java8 부터 도입된 날짜/시간 API에 대해서 한 번 공부해보시고 사용해보세요.
최근 Java 코드에서 `Date`, `Calendar`는 쓰지 않습니다.

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
요건 별도의 Controller를 만들어서 분리를 해볼까요?
그리고, redirect를 사용해서, 전체 목록을 출력해주는 방식으로 구현해봅시다~
"/"를 입력하면, "/questions"로 요청을 전달하는 방식으로 구현해보세요!
그러면, `/questions`라는 url이 중복될 것이고, 이를 `@RequestMapping`으로 추출해줄 수 있을겁니다!

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String getQuestionShow(@PathVariable("id") Long id, Model model) {
메서드 명이 뭔가 전체적으로 좀 이상하다고 느껴지셔야 해요.
가급적이면 HTTP Method가 메서드 명에는 드러나지 않도록 네이밍 해봅시다.

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionRepository.findById(id).get();
`findById`는 `Optional`이 리턴되는데요.
여기서 `get()`을 바로 쓰는 것은 안티패턴으로 사용하지 말아주세요.
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/
이 글을 참고하셔서 개선해보세요!

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      @PostMapping("/user/form")
어디는 `/user`고, 어디는 /`users`로 구성해주셨는데요.
이렇게 구현하면 RESTful에서는 전혀 다른 리소스라고 판단됩니다.
꼭 맞춰주시고, `RequestMapping`으로 중복을 제거해줍시다!

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        model.addAttribute("user", user );
```suggestion
        model.addAttribute("user", user);
```

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      }
이런 메서드는 `Controller`가 가지기엔 너무 큰 책임이죠?
그래서 `Service` Layer를 두곤 합니다. 일단 메서드 분리는 잘 하셨어요.

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    public String updateUser(@PathVariable Long id, User newInfoUser) {
네이밍 좋은데요?

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    public static final String DATE_PATTERN = "yyyy-MM-dd HH:mm";
중복되는 코드고, 여기에 존재하면 안 될 코드라고 생각되네요~
위에 드린 피드백인 Utility를 분리해보세요~

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
>      private String contents;
제약조건을 두는 것은 좋은데, 어떻게 제약조건이 변환되는지 알고 쓰는게 좋아요~
근데, JPA의 영역이라 학습은 나중에 필요할 때 해봅시다.

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
>      private String dateTime;
날짜와 시간을 저장할 때에는 날짜/시간 타입으로 저장해주실 것을 권장합니다!

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    @Column(nullable=false)
정렬을 꼭 해주세요~

2021-03-13 13:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    }
이런 메서드 정의 아주 좋습니다~

2021-03-13 13:44 UTC, ksundong commented on src/main/resources/application.properties
> +spring.mvc.hiddenmethod.filter.enabled=true
주석 좋아요! 👍
참고한 링크를 한 번 적어주는 것도 좋겠네요~

2021-03-13 13:44 UTC, ksundong commented on src/main/resources/templates/user/updateForm.html
> +{{>base}}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
여기 참고하셔서 설정 해주시고, 이래도 반영이 안되시면 엔터치고 저장해주세요!

2021-03-13 13:57 UTC, ksundong commented
> 안녕하세요 Jung입니다.
> 두번째 미션 진행하면서 전혀 모르던! db에 대해 조금이나마 공부해볼수있어서 좋았습니다!

좋네요.!

> 기본개념에 대한 이해도가 낮아 시키는대로 repository등을 만들면서도
> 스프링 내에서 작동 원리..?를 완벽히 알지 못한채 미션을 진행해 완성도가 떨어집니다..ㅎㅎ

모두가 거의 비슷한 상태입니다. 완성도는 차차 코드스쿼드 과정을 하다보면 나아질거에요.

> 코드에서 repository, domain, controller의 역할에 대한 이해가 얕아 보이는 부분있으면 지적 부탁드립니다!!!

코멘트 참고해주세요~

> 미션하면서 고민했던 부분들은 다음과 같습니다.
> 
> User
> User클래스의 Column들에 대한 @column(nullable=false, length=20) 20자 길이제한을 해제했습니다. 길이를 제한하면 이 길이를 넘어가는 input을 입력했을 시 에러페이지로 넘어갑니다. 그런데 저는 그 페이지에서 팝업형식(?)으로 에러 메세지를 사용자에게 보여주는 방식을 구현하고 싶어서 일단은 길이제한을 해제했습니다.

Javascript를 이용해서 해보세요~

> UserController
> findById(id)에서 Optional을 리턴하기 때문에 만약 null이 리턴될시(orElseThrow) 지정된메세지(해당id의 사용자가 존재하지 않습니다)로 예외를 발생시키도록 메서드를 구현했습니다.
> userRepository.findById(id).get()을 하면 User을 리턴하고, User이 없어 null일 경우 NoSuchElementException을 던집니다.

좋네요!

> get메서드를 사용하면 optional의 기능을 충분히 못쓰는 것이기 때문에 get을 쓰지 말라는 조언을 들었습니다. get을 쓰나 orElseThrow를 쓰나 NoSuchElementException을 던지지만, orElseThrow는 메세지를 설정할수있기 때문에 get 대신 쓰는 것이 제가 이해한 것이 맞는지요..?

`get()`의 JavaDoc API Document를 읽어보시길 추천드려요. 원래, `isPresent()`를 선행해서 사용하는 것이 맞는 사용방법입니다.
근데, `Optional`을 사용하는 것과 null을 사용하는 것이 큰 차이가 없게되는 형태다 보니 조금 덜 선호되는 것 같아요.

그리고 가급적이면 Java에서 제공하는 예외를 사용해줘도 좋지만, Custom한 예외가 필요한 경우엔 과감히 선언해주는 것도 필요합니다.

> 리뷰해주셔서 감사합니다~
> 
> 디온..
> conflict났던 것 잘 해결했었는데 해결과정에서 커밋을 잘못 수정한 것을 고치면서
> 미션 2 커밋들이 전부 날아가는 실수를 저질러버렸습니다.. (정확히는 미션2가 마지막 한개의 커밋만 가리키게 됐습니다..)
> 불가피하게 새로 PR 보냅니다.. 최대한 원래 PR내에서 해결하려했으나 잘 안됐어요.. 죄송함다..
> 
> (1. 바꾸려는 커밋 바로 위 커밋에 checkout
> 2. newBranch만들고 바꾸려는 커밋 cherry-pick해서 수정(git commit --amend)
> 3. 바꾸려는 커밋에 checkout해서
> 새로운 tmpbranch만들기
> 4. tmpbranch 이후부터 mission2 커밋까지 newbranch 로 rebase하고
> (git rebase --onto newbranch1 tmpbranch mission2)
> 5. mission2를 branch -f해서 가리키게 함 (git branch -f mission2)
> 6. 원격에 반영 ( git push origin mission2)
> 이것이 저의 야심찬 계획이었으나 장렬히 실패했습니다.)
> 
> > properties conflict해결 … h2 데이터베이스 의존성 추가와 설정
> > [4e161af](https://github.com/codesquad-members-2021/spring-boot-qna/commit/4e161afaf474ae509b8425ba198e7701a3b3e83a) 커밋은 conflict 해결 과정에서 잘못 커밋되었는데요, (기존 커밋을 수정해버림)
> > 원래는 내용인 <h2 데이터베이스 의존성 추가와 설정> 요 부분이 커밋 타이틀입니다.
> > 수정을 시도하고 있으나 잘 안될 경우 참고 부탁드립니다!
> > -> 이것을 수정하려다 재PR 날리게 됐습니다.. git 좀더 연습해봐야겠어요
> 
> 오늘도 리뷰 감사합니당

깃하고 싸우느라 고생하셨겠네요. git도 이해를 하고 사용하시면 도움이 많이 됩니다.
호눅스의 책을 꼭 구매하시라는 것은 아니지만, 가급적이면 Git 관련 책 하나 구입하셔서 잘 이용하기 위해 노력하는 것도 추천드려요.
고생 많으셨어요!

2021-03-15 07:57 UTC, rla36 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
If no ranges are involved, then the highest version that is not rejected will be selected.
[출처](https://docs.gradle.org/current/userguide/dependency_management.html)
검색해봤는데 가장 최신 버전이 import되는 것 같습니다!

2021-03-15 08:16 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private QuestionRepository questionRepository;
말씀하신대로 수정했습니다 생성자 매개변수로는 writer, title, contents를 넣었습니다!
id 는 생성자에 없어도 @GeneratedValue로 자동생성되므로 뺐고 
dateTime은 setDateTime을 다른 클래스에서 따로 메서드로 빼내었으므로 일단 생성자 매개변수에 넣지 않았습니다.
(String dateTime 어차피 바꿔야할 것 같지만 일단 뒀습니다)

그리고 인텔리제이에서 매개변수가 없는 생성자도 필요하다해서  추가했습니다..!

2021-03-15 08:41 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
HomeController 클래스를 만들어 @GetMapping("/") -> return "redirect:/questions"; 으로 redirect하게 했습니다.
QuestionController클래스 안에는  @GetMapping("/questions") ->모델에 모든 questions 추가 -> return "index";
하도록 했습니다.

그리고 중복되는 url을 RequestMapping으로 빼내었습니다~

2021-03-15 13:58 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
User클래스에도 동일한 방법을 적용해 url을 user을 users로 바꾼후 requestMapping으로 추출했습니다!

2021-03-15 14:51 UTC, ksundong commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
네 이 점 때문에 보통은 버전 명시를 해주는게 좋습니다.

2021-03-15 14:51 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private QuestionRepository questionRepository;
Injection에 대해서 다시 공부해보세요.

2021-03-15 14:52 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    private QuestionRepository questionRepository;
`Controller`에 코멘트를 남겼는데 바뀐 부분이 Entity네요 ㅠㅠ

2021-03-15 14:58 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
QuestionUtility클래스를 따로 만들어 지정된 형식의 DateTimeFormatter을 갖도록했습니다!

Question  생성자 안에 LocalDateTime이 저장되도록했습니다. 
(this.writtenDateTime = LocalDateTime.now();)

질문 목록에서 주어진 형식으로 date/time이 출력되도록 하기 위해서 getter은 (LocalDateTime이 아닌) String을 리턴하도록했습니다. 원하는 포맷으로 편집된 LocalDateTime을 리턴하는 방식도 있을 것 같은데 찾기가 어려워서 일단 스트링으로 리턴하도록했습니다! 
`    public String getWrittenDateTime() {
        return writtenDateTime.format(QuestionUtility.DATE_PATTERN);
    }
`

2021-03-15 15:03 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String getQuestionShow(@PathVariable("id") Long id, Model model) {
showQuestion으로 이름을 리네이밍해서 질문의 상세내용을 볼수있다는 것을 드러내도록 했습니다!

2021-03-15 15:08 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionRepository.findById(id).get();
앗.. User에서는 get을 전부 제거했는데 여기 남아잇었네요ㅜㅜ 
null일 경우 예외를 throw하도록 orElseThrow로 수정했습니다!

2021-03-15 15:10 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      @PostMapping("/user/form")
넵 위에 Question클래스에서 리퀘스트매핑하면서 같이 수정했습니다!

2021-03-15 15:10 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        model.addAttribute("user", user );
몽골분이시군요... 수정하겠습니다. 정렬 단축키를 생활화하겠습니다..

2021-03-15 15:53 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      }
Repository -> Service -> Controller
Service에서는 Repository를 접근할수있도록 Service생성자 안에 Repository를 넣어주고,
Controller에선 Service를 접근할수있도록 Controller생성자 안에 Service를 넣어주었습니다.

Controller에서 Repository를 직접 접근할 수 없게 됨에 따라 Controller과 Repository 를 이어줄수있도록
Service클래스에 findAll, save와 같은 메서드들을 추가했습니다.

2021-03-15 15:54 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    public static final String DATE_PATTERN = "yyyy-MM-dd HH:mm";
넵 위에서 분리했습니당

2021-03-15 15:54 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
>      private String dateTime;
넵넵!!

2021-03-15 15:54 UTC, rla36 commented on src/main/resources/application.properties
> +spring.mvc.hiddenmethod.filter.enabled=true
네 루카스에서 참고했기 때문에.. 루카스 링크를 달겠습니다..ㅎㅎ

2021-03-15 16:03 UTC, rla36 commented on src/main/resources/templates/user/updateForm.html
> +{{>base}}
![image](https://user-images.githubusercontent.com/74045466/111183471-48ceed80-85f3-11eb-80c8-65e8da3ad3b2.png)
수정했습니다!
[링크](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/) 잘 봤습니다! 이런 문제가 있는 줄 전혀 몰랐어요.. 리뷰 덕분에 많은 걸 배웁니당!!

2021-03-15 16:45 UTC, rla36 commented
@ksundong 
말씀해주신 것들 모두 수정했습니다!
회원정보 수정시에 비밀번호 검증하는 과정도 추가했습니다. 다만, 새로운 비밀번호로 수정할 수 있는 방법도 추가하려했는데 빨리 다음 미션으로 넘어가고 싶어서.. ㅎㅎ 아이디, 이름, 이메일만 수정할수있도록 지금은! 그냥 두었습니다. 나중에 다시 돌아와서 수정하겠습니다..

이건 좀 tmi인데 금요일에 깃과 사투 벌이고 새벽3~4시?에 잠들었는데 
꿈에 디온이 나오셨어여...ㅋㅋㅋ 
꿈에서도 리뷰 실컷 받았습니다. 그래서 이번 미션 두번째 수정하는 것 같아욬ㅋㅋ
길몽으로 생각하겠습니다!!ㅋㅋㅋㅋ (봉황같은 존재) 제 꿈에 나와주셔서 감사합니다ㅎㅎ

아무튼 스프링 등을 처음 접하다보니 
Service, Repository, Controller의 기능과 역할 / 각종 애노테이션 / 모든 것 / 이 헷갈리는데
리뷰해주신것 키워드로 검색해보니 조오금 조오오오금은 알것같기도 합니다!
이번에도 리뷰해주셔서 감사합니당!

2021-03-15 16:51 UTC, rla36 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
아 같은 프로그램을 오래 사용하다 보면 최신 버전이 계속 교체될텐데
그럼 호환성 문제도 있을수있겠네요

h2 버전 명시를 추가하겠습니다!

2021-03-15 23:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
'원하는 포맷으로 편집된' (문자열을 반환하는) `LocalDateTime` 을 의미한 것 같은데, 그렇지 않습니다.
LocalDateTime은 지정된 형식으로 데이터를 저장하고, 포매팅은 포매터를 이용해야죠.
그래도 잘 하셨어요.

2021-03-15 23:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
>      }
잘 하셨습니다.

2021-03-15 23:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    public String getQuestionShow(@PathVariable("id") Long id, Model model) {
잘 바꾸셨습니다.

2021-03-15 23:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        Question question = questionRepository.findById(id).get();
넵넵 잘 바꾸신 것 같네요.

2021-03-15 23:24 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        model.addAttribute("user", user );
오래 코딩하다보면, 컨벤션에 민감해져서 그래요 ㅎㅎ
신경 많이써주세요.

2021-03-15 23:24 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      @PostMapping("/user/form")
잘 하셨습니다~

2021-03-15 23:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
>      }
넵 아직 안하셔도 되지만, 잘 공부하셨네요.

2021-03-15 23:39 UTC, ksundong approved these changes
피드백 반영해주시느라 고생하셨습니다!
몇몇 기초적인 부분은 계속 피드백 받으면 스트레스 받으니까, 항상 주의해봅시다.
다음 단계로 진행해도 괜찮을 것 같다고 판단되어, **Approve** 합니다.
고생하셨습니다!

2021-03-15 23:39 UTC, ksundong commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
버전 명시는 다음 미션에서 바뀌는건가요?

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/HomeController.java
> +    public String getIndex() {
네이밍~ 신경써주세요.
`getXXX`는 지양합시다!

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```
이렇게도 쓸 수 있습니다~

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        model.addAttribute("questions", questionRepository.findAll());
여기는 아직 `Repository`를 그대로 보네요.

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    UserController(UserService userService) {
접근제어자가 누락되었군요?

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    UserController(UserService userService) {
생성자 인젝션은 잘 써주셨어요.

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @PostMapping("/form")
```suggestion
    @PostMapping("")
```

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
protected 기본 생성자를 추가해주신 이유는 알고 계신가요?

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
가급적이면 getter를 그대로 쓰기보다는 새로운 `getter`를 정의해서 포맷된 정보를 반환해줍시다
`getFormattedWrittenDateTime()`이 좋겠네요.

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    public String getNewPassword () {return newPassword;}
```suggestion
    public String getNewPassword() {
        return newPassword;
    }
```

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    private String newPassword;
`newPassword`는 DB에는 저장되면 안되는데요. 이를 해결하기 위한 방법이 두 가지 있습니다.
1. `@Transient`를 이용한다. (비추천합니다. 왜일까요?)
2. `DTO`라는 계층간 데이터를 전달하는 용도의 객체를 정의한다. (추천)

이 부분은 학습이 필요하니 다음 단계에서 고민해봅시다.

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    public String getNewPassword () {return newPassword;}
`setter` 없애주신건 잘 하셨어요.

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    UserService(UserRepository userRepository) {
여기도~ 접근제어자 빠졌습니다.
기초적인 실수는 이제 하면 안돼요~

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
`Iterable`을 그대로 반환하는 건 추천하지 않아요.
어떻게 하면 `List`를 반환해줄 수 있을까요?

https://stackoverflow.com/questions/34702252/spring-data-jpa-crudrepository-returns-iterable-is-it-ok-to-cast-this-to-list

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
👍

2021-03-15 23:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utility/QuestionUtility.java
> +public class QuestionUtility {
보통 상수만 있을 경우에는 `Utility`라고 하지 않고, `Constants`라는 네이밍을 더 많이 사용합니다.
`Constants`는 상수 모음
`Utility`는 유틸리티성 메서드 모음
정도로 받아들이시면 될 것 같아요.
그리고 이런 류의 클래스는 `private` 기본생성자로 불필요한 인스턴스 생성을 막아줍시다.

2021-03-16 01:18 UTC, rla36 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
로컬에서 바꾸고 커밋을 안했네요..ㅎ 죄송해여

2021-03-16 01:37 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/HomeController.java
> +    public String getIndex() {
visitHome으로 바꾸고 다른 매핑메소드들도 수정해봤습니당

2021-03-16 01:37 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +    @PostMapping("")
오오 넵!!

2021-03-16 01:40 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/QuestionController.java
> +        model.addAttribute("questions", questionRepository.findAll());
아 User에는  UserService를 만들어줬는데
Question에는 Service가 없어서 Controller에서 Repository를 바로 접근합니다

일관성을 위해서 Question도 Service를 만들어주는게 좋겠네요! 수정하겠습니다

2021-03-16 02:06 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    UserController(UserService userService) {
넵 ㅜㅜ

2021-03-16 02:15 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    }
UserRepository에서 findAll메서드가 List<User>을 반환하도록 오버라이딩했습니다!

2021-03-16 02:15 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +    UserService(UserRepository userRepository) {
넵 ㅜㅜ

2021-03-16 02:17 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/utility/QuestionUtility.java
> +public class QuestionUtility {
원래는 메서드를 만들 생각으로 Utility클래스를 추가했으나.. 상수만 쓰게 됐네요 
private생성자 추가하겠습니다! 기본적인 것이 정말 어려운것같아요

2021-03-16 02:19 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    private String newPassword;
DTO... 키워드 기억하고 다음단계에서 공부해보겠습니다!

2021-03-16 02:22 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +    public String getNewPassword () {return newPassword;}
현재로선 비밀번호 수정이 불가능한 .. 게시판이라서 getNewPassword메소드도 지우는 것이 맞는데, 나중에 비밀번호 수정 기능을 추가할 생각이라 일단 두도록 하겠습니다!
정렬은 예쁘게 했습니다.

2021-03-16 02:26 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
넵 메소드 이름 수정하고, 
qna/show.html과 index.html에서도 question.formattedWrittenDateTime을 가져오도록(?) 수정했습니다.

2021-03-16 02:35 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
> 기본생성자가 필요한 이유는 하이버네이트와 같은 JPA프로바이더는 DB에서 데이터를 읽어와 매핑된 객체를 생성할 때 기본생성자를 사용해서 객체를 생성하기 때문에 기본생성자는 꼭 추가해주어야 한다. 하지만, 기본 생성자를 다른 코드에서 사용하면 값이 없는 온전하지 못한 객체를 만들게 되므로, 다른 코드에서 기본 생성자를 사용하지 못하도록 proteced로 해주었다. 
[출처](http://blog.eomdev.com/ddd/2019/02/17/ddd-setter-default-constructor.html)

> GET 요청을 통해 repository에서 엔티티 정보를 조회해 인스턴스를 만들 때 기본 생성자를 사용한다는 것을 알 수 있습니다.
[출처](https://wbluke.tistory.com/6)

이렇게 알고 있는데, 혹시 다른 이유가 있으면 말씀해주시면 감사하겠습니다!

2021-03-16 02:51 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @PostMapping("/form")
회원가입 버튼을 클릭하면 입력한 회원정보 데이터가 전송되는 url이 
users/form인것보단 users인 것이 더 직관적이기 때문인가요??
아니면 이 메소드에서 return "redirect:/users" 하기 때문에 매핑도 비슷하게 하는 것인가요??

2021-03-16 09:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @PostMapping("/form")
RESTful한 url을 설계하는 것이 어떤건지 한 번 공부해보세요~
`POST /users`가 `user`를 생성한다는 의미로 읽힌답니다!

2021-03-16 09:51 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
잘 고웁하셨네요~

2021-03-16 12:38 UTC, ksundong approved these changes
Approve 했지만 한 번 더 리뷰했어요~
고생하셨습니다!

2021-03-16 12:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +        if (userService.isCorrectPassword(user, newInfoUser.getPassword())) {
객체를 직접 넘겨주는 것도 고민해보세요~

2021-03-17 02:24 UTC, rla36 commented on src/main/java/com/codessquad/qna/web/controllers/UserController.java
> +    @PostMapping("/form")
post와 form이 이미 동어반복이라서 POST users 에 form까지 더할 필요가 없는거군요!!
말씀하신대로 수정했습니당
url설계도 공부해봐야겟습니다!

2021-03-17 10:07 UTC, merged