[Kyu] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #66
Opened 2021-03-14 05:04 UTC by kyu-kim-kr

## 미션3 첫째날
### 회원 목록 초기화
서버 키고 끌때마다 회원가입한 데이터가 다 날아간다. 아마 데이터 안날아가도록 다른 설정이 있을 것 같지만, `data.sql`을 `src/main/resources`에 넣는 방식으로 히원목록을 초기화하기로 했다. 예시로 다음과 같이 파일에 넣어주면 된다.
```sql
INSERT INTO user (id, user_id, name, password, email) VALUES
    (1, 'lala', 'lala', 'lala', 'lala@lala.com'),
    (2, 'kyu', 'kyu', 'kyu', 'kyu@kyu.com');
```
참고로 User클래스에 넣어준 속성의 이름을 사용하면 안되고..테이블이 컬럼들을 이름을 어떻게 생성했는지 확인하고 해줘야한다. 다행인건 틀려도 Run 하면 인텔리제이가 뭐가 틀렸는지 알려준다. (런타임 에러 라고 부르면 맞는 말인가?)

참고로 [튜토리얼을 따라하다보면](https://www.youtube.com/watch?v=9xmTAmyv_ic) 이 부분을 검색할때 sprig data jpa initialize database 정도로 검색하는데 여기서 **jpa**가 왜 들어갈까? jpa에 대해서 자세히 잘 이해해야할 듯.

### HttpSession
로그인, 로그아웃 기능을 구현할때 HttpSession을 이용해서 쉽게 구현할 수 있었다. HttpSession은 뭘까? 

 웹에서 로그인 기능을 구현할때 가장 기본적인 방식이 HttpSession 객체를 이용하는 것이다. HttpSession의 동작은 세션 쿠키를 통해 이루어진다. 서버는 접속한 브라우저에게 고유한 세션 쿠키를 전달한다.
 
세션쿠키가 열쇠라면 HttpSession은 자물쇠로 잠겨진 박스라고 생각하면 된다. 사용자는 항상 열쇠를 가지고 접근한다. _그 때문에 각각의 열쇠를 가진 사용자들이 다른데이터를 가질 수 있다? (걍 추론)_

### 로그인 상태에서 자기 자신의 정보 수정
```
There was an unexpected error (type=Internal Server Error, status=500).
Cannot expose session attribute 'user' because of an existing model object of the same name
javax.servlet.ServletException: Cannot expose session attribute 'user' because of an existing model object of the same name
```
로그인 상태에서 개인정보수정을 누르면 세션에 설정된 유저의 정보를 바뀌도록 구현하는 과정에서 위와 같은 에러가 나왔다. 자바지기님의 설명은 이렇게 말씀하셨다.
> - 유저라는 이름으로 데이터를 전달하는 거처럼 세션에 데이터를 담을때 expose를 하면서 모델의 데이터가 담겼는데 이름이 똑같기 때문에 같은 이름을 전달할수없다고 나온거다
>
>
> - 개인정보수정을 할때 모델에 전달되는 데이터와 세션에 담기는 데이터의 이름을 다르게 변경해야지 에러가 없습니다

근데 무슨 말인지 모르겠다.

그리고 session에 들어간 user를 불러서, 들어온 id와 일치하지 않으면 updateForm 에 접근하지 못하도록 자바지기님을 따라했는데, 이상하다. 반대로작동한다. 예상되는 동작은 id와 session의 id가 다를때 야이노무자식아가 나오는건데, 분명히 같은데 야이노무자식이가 나온다. 근데 느낌표를 지우면 id가 같음에도 불구하고 updateForm이 잘나온다. 흠

```java
 @GetMapping("/{id}/form")
    public String getForm(@PathVariable Long id, Model model, HttpSession session) {
        Object tempUser = session.getAttribute("sessionedUser");
        if (tempUser == null) {
            return "redirect:/users/login";
        }

        User sessionedUser = (User) tempUser;
        if (!id.equals(sessionedUser.getUserId())) {
            throw new IllegalStateException("야이노무자식아");
        }

        model.addAttribute("user", getUserBy(id));
        return "/user/updateForm";
    }
```

---

##미션3 둘째날
### 로그인 상태에서 자기 자신의 정보 수정
어제 TIL 에서 로그인 상태에서 자기 자신의 정보 수정을 위해서 유효성 검사를 하는 조건문을 구현했는데 작동하지 않았다고 했다. 이유는 단지 id를 userid와 비교해서였다.

분명히 자바지기님 다 따라했는데 왜 난 다르게 나오는거지 하고 생각했는데 단순히 오타실수였다. 이건 내가 체크도 안하고 IDE에서 나오는 자동완성기능을 무작정 따라해서인거 같다.  조심해야겠다.

### 스프링부트 Null 처리
>회원가입이나 수정할떄 Null 처리 어떻게 하는거지? 공백도 못들어가게..?

일단 Null 처리는 여러가지 방법이있다. `@NotNull`, `@NotEmpty`, `@NotBlank` 그리고 `@Column (nullable = flase)`. 각각의 차이점같은건 잘모르겠다. 중요한건 지금 미션에서 Null이 언제 들어오길래 Null값을 처리하라는건지 잘모르겠다. 일단 회원가입이나 글쓰기 폼에 아무것도 입력안하고 버튼을 누르면 null이 아니라 공백 blank 상태로 객체가 만들어진다. 그럼 이걸 처리해야하는 걸 찾아야한다

그 방법은 bat가 알려준 `trim.isEmpty()` 와 Jane이 알려준 `@NotEmpty`를 쓰면된다. 꼭 공부해서 써먹어보자.

### 스프링부트 Setter & Getter
객체가 한번 만들어지고 업데이트될 일이 없으면 세터가 없어도 된다.
게터는 음...도메인 객체 안에 여러 멤버변수들을 뷰에 전달하는 방법은 여러가지가 있는데 그게 세터나 생성자를 통해가져오고
게터는 컨트롤러가 뷰에서 가져올떄 쓰인다.

### 캡슐화 관련 조언
데이터를 꺼내서 사용하려하지말고 그 객체에서 직접 메서드를 호출해서 사용하도록 해라. 상태데이터를 외부로 노출시키는 것은 그리 좋은 것이 아니다. (From 자바지기님) (캡슐화) 

예를 들어서 
```java
if(id.equals(sessionedUser.getId(id)) {
	[...]
}
```
위 코드처럼 id 를 비교해서 일치하면 어떤 로직을 실행하는 조건문이 있다고 쳤을 때, 지금 User 객체에서 getId() 메서드를 통해서 데이터를 꺼내 사용하>고 있다.?

```java
if (sessionedUser.isRightId(id)){
	[...]
}
```
isRightId() 라는 메서드로 객체 내에서 외부에서 들어오는 값에따라 바로 id 가 일치하는지 안하는지 체크하는 메서드를 추가한 후에 위 코드처럼 바꿔서 사용하는게 좋다고 한다.

---

## 미션3 셋째날

2021-03-15 12:24 UTC, wheejuni requested changes
전반적으로 깔끔하게 잘 구현하셨고, 특별히 리뷰 드릴 내용이 많진 않았습니다. 👏👏 잘 하셨어요. 

Spring MVC에 대해 궁금한 점도 많으시고 정리도 잘 하셨네요. 전반적으로 잘 정리해 주셨는데 추가 학습 과제로 ViewResolver와 MessageConverter에 대해 학습해 보시길 권해 드려요. 

제가 슬랙 채널에 농반진반으로 _Spring만큼 유연하고 우아한 프레임워크는 없다_ 는 말씀을 드렸었는데 이런 유연한 설계의 진수를 보여주는 것이 바로 Spring MVC의 ViewResolver와 MessageConverter 입니다. 

꼭 한번 정리하시고 여기에도 남겨주세요. 기다릴게요 ㅋㅋㅋ 🤞

2021-03-15 12:24 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/HttepSessionUtils.java
> +public class HttepSessionUtils {
ㅋㅋ 오타 인상적이네요.

2021-03-15 12:24 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/HttepSessionUtils.java
> +        return true;
아래와 같이 줄일 수 있겠네요. 

```suggestion
return session.getAttribute() != null
```

2021-03-15 12:24 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question selectedQuestion = questionRepository.findById(id).get();
`Optional.get()` 을 강제 언래핑이라고 부르고요, **지양** 하셔야 합니다. 

옵셔널이 가져다주는 선물 같은 이점을 다 포기하는 구현입니다. 유념해 주세요.

2021-03-16 09:02 UTC, kyu-kim-kr commented
@wheejuni 
> 기다릴게요 ㅋㅋㅋ 🤞

기다리실거라고하셔서 제대로 공부해보고 싶었는데 일단 오늘 하룻동안 공부한 것은 아래와 같습니다. MessageConverter는 찾아보니 이해안가는 곳이 많아서 내일 다시 좀 찾아봐야할거같아요 ㅎㅎ

---

ViewResolver에 대해 이해하려고하니 DispatcherServlet이 나오고, DispatcherServlet을 이해하려고 보니 먼저 Servlet에 대해 조금이라도 알아야겠다고 생각했다.

## Servlet
서블릿을 배운걸 바탕으로 종합적으로 한 문장으로 표현해보자면, 

서블릿이란 자바로 웹 프로그램을 만들기 위해서 가져야할 가장 기본적인 서버 어플리케이션이다.

자세한 내용은 따로 포스트를 했다.
>https://velog.io/@kyukim/Servlet

## DispatcherServlet
Servlet은 뭔지 알았다. DispatcherServlet은?

일단 Dispatch는 택배에서 발송하다는 의미로 쓰이는걸 많이봤따. 발송하는 사람의 역할을 하는 Servlet?

뭘 발송할까? 요청받은 것을 고객에게 발송한다는 의미로 해석하면 맞을것 같다.

Servlet을 배운 대로라면, 클라이언트가 특정 서블릿을 요청하는 것을 받기 위해서 톰캣에다가 그것을 설정해줬었다.(web.xml)

기존에는 모든 서블릿에 대해 URL 매핑을 활용하기 위해서 web.xml에 모두 등록해주어야 했지만, Spring MVC의 DispatcherServlet는 앞단에서 요청받은 걸 다시 클라이언트에게 발송한다.

그 과정은 이 이미지가 너무 설명이 잘되어있는거 같아 가져왔다.

![](https://blog.kakaocdn.net/dn/MRXX3/btqK7014LOZ/wMKgG9RVkdZR7Ag5nD4wh0/img.png)

>참고 여기 굿굿
https://mangkyu.tistory.com/18

## ViewResolver
이때까지 미션하면서 String 값으로 뷰를 리턴했다. 그냥 쓰면서 그냥 이렇게하면 작동하네~정도로 넘어갔었는데,

String 값을 리턴하면 리턴 값으로부터 실제로 사용할 뷰 객체를 결정해주는 뷰 리졸버가 필요하다고한다.

뷰 리졸버는 리턴값으로부터 사용할 뷰 오브젝트를 매핑해준다. 매핑해주는 방법에도 여러가지가 있다고 한다.

특정 뷰리졸버를 빈으로 등록하지 않으면  DispatcherServlet은  기본 뷰 리졸버이고 JSP 사용을 위한 InternalResourceViewResolver를 사용한다.

여기서 템플릿엔진이랑 좀 헷갈리는데 미션에 난 handlbars를 쓰고 있다. 찾아보니 web.xml도 없다.
그런데 application.properties에 들어가보니까
```
handlebars.suffix=.html
handlebars.cache=false
```
라고 되어있따.

이거 어디서 주워들어서 설정해준건지 원래설정되어있는건지 기억이안난다.

여튼 중요한건 web.xml이 왜 없고,,,,그러니까 지금까지 배운걸 보면 모두 jsp를 이용하는거 같은데...
템플릿엔진이 어느 위치에 있는 기술인지 정확하게 알아야할 것 같다.

2021-03-16 10:38 UTC, wheejuni commented
> 여튼 중요한건 web.xml이 왜 없고,,,,그러니까 지금까지 배운걸 보면 모두 jsp를 이용하는거 같은데...

아닙니다. 조금 더 자세히 공부해보시면 좋을 것 같은데요 ㅋㅋ 메세지 컨버터는 아직 못 공부하신 건가요? 혹은 자료를 못 찾으시겠나요?

2021-03-16 20:31 UTC, kyu-kim-kr commented
일단 중간점검차 배운것까지 댓글을 달았었습니다. ㅎㅎ

 [여기 글의 이미지](https://wondongho.tistory.com/76)를 보아 메세지컨버터도 동일한 위치의 개념인거 같아보이는데요. 메세지컨버터는 뷰리졸버와 비교하면서 공부해야하는 것 같은데,,, 혹시 추천하는 글이 있으시다면 한번 봐도 될까요?

--- 

> 여튼 중요한건 web.xml이 왜 없고,,,,그러니까 지금까지 배운걸 보면 모두 jsp를 이용하는거 같은데...

그리고 제가 잘못 작성한거 같습니다. 모두 jsp를 이용한다는 말은 이때까지 배운 servlet, dispatcherservlet, viewresolver 에 대한 자료들을 살펴보니까 전부 WEB-INF 내에 있는 web.xml을 언급하더라구요..

근데 지금 미션 하면서 web.xml이 없어서, 왜인지는 잘 모르겠으나 지금은 JPA를 이용해서 만들고있기 때문에 그런가보다 라고 추측했습니다.

이 말은 맞나요? 

> 지금까지 배운걸보면 모두 JPA 를 사용하는거 같은데....

2021-03-17 03:32 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/HttepSessionUtils.java
> +public class HttepSessionUtils {
ㅎㅎ 수정완료했습니다.

2021-03-17 03:32 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/HttepSessionUtils.java
> +        return true;
이렇게 작성할수있군요. 감사합니당.

2021-03-17 03:34 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question selectedQuestion = questionRepository.findById(id).get();
옵셥널에 대해서는 자바8부터 생긴 null을 처리하는 유용한 도구(?) 정도로 밖에 모르고 있었습니다. 그리고 QuestionRepository가 옵셔널인 것 자체도 몰랐네용 ㅠ
옵셔널도 공부해보겠습니다.

2021-03-17 18:00 UTC, kyu-kim-kr commented
### MessageConverter
Spring MVC를 이용해서 컨트롤러에 값을 주고 받을때는 HTTP 요청 프로퍼티를 분석하여 그에 따라 특정 클래스로 바인딩이 되게끔 하고 컨트롤러에서 특정 객체를 Model Object에 집어 넣어 View를 리턴하는 식으로 주고받게 된다.

그러나 메시지 컨버터는 그런 개념이 아니라 HTTP 요청 메시지 본문과 HTTP 응답 메시지 본문을 통째로 하나의 메시지로 보고 이를 처리한다.

> 참고
> https://zgundam.tistory.com/12

2021-03-18 03:23 UTC, wheejuni commented
@kyu-kim-kr 네. 수고하셨습니다 ㅎㅎ

2021-03-18 03:24 UTC, merged