[Roach] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #67
Opened 2021-03-14 06:01 UTC by tmdgusya

## 쿼리 관련 고민

`soft delete` 이용간 장 단점

- 게시물이 완전히 삭제되지 않고, 논리적으로만 삭제되었다는 상태값을 가지게 되어 후에 이를 확인할 수 있음 
   - 이러한 논리적으로 삭제된 데이터가 보관되는 주기를 가지고 운영할듯함? 실무에서는?
- 단점이라면, 쿼리를 날릴때 상태값을 확인해주는 조건이 계속들어가야 함. 
   - COUNT 등등에도 WHERE 가 들어가야 할 수 있으므로 항상 유의해서 사용해야 함 (=> 실수를 유발할 수 있음)

## 대략적으로 생각했던 쿼리 

```sql
SELECT * FROM POST LEFT OUTER JOIN COMMENT ON COMMENT.POST_ID = POST.POST_ID AND COMMENT.DELETE_FLAG <> TRUE WHERE POST.POST_ID = 1 AND POST.DELETE_FLAG <> TRUE;
```

## 제가 잘 모르는 것인지?

jpa 에서 fetch join 의 대상에 대한 쿼리를 날려야 하는 상황인데, 왜냐면 아래와 같이 해야됨
하지만 fetch join 의 대상은 조건의 대상으로 사용할 수 없음.
fetch join 의 대상은 있다고 가정하는 것이기에, 만약 게시글이 처음 생성되고 눌렀을때, comments 가 없으므로 해당 게시물을 찾지 못함.

```
@Query("select p from Post p left join fetch p.comments c " +
            "left join fetch p.author "+
            "left join fetch c.author "+
            "where p.deleteFlag <> true and p.postId = :id and c.deleteFlag ")
Optional<Post> findById(@Param("id") Long id);
```

**위와 같은 쿼리를 진행하면 정상작동이 안되니까**...

위와 같은 문제로 LAZY? 방식을 이용한다.. 그러면 또 **쿼리가 급증**하는 문제가 생김.

jpa 특성상 주인관계에서의 외래키값 쓰기 / 수정이 가능하다고 알고있어서 그래서 **comments 삭제시 의 post 참조를 null** 로 해주게 되었습니다. (이 부분에 대한 생각이 궁금하실까봐 적었습니다.)

만약 comment 가 어떤 post 에 있었는지 기록되어야 한다면, 따로 Column 을 유지하는 방식도 좋을 것 같습니다.

이 부분에 대한 Comment 를 남겨주시면 감사할 것 같습니다!

2021-03-15 14:33 UTC, wheejuni requested changes
Soft Delete에 대해 장단점 잘 분석해 주셨네요. 거의 맞습니다. 
그런데 한가지 반문해 보고 싶습니다. _쿼리가 급증하는 것이 왜 문제인가요?_
이것부터 생각해 보셨으면 좋겠네요. 그저 피상적으로 뭔가 여러번 날라가니 문제라고 느낀 것인지요. 사실 문제가 아닐 때도 많습니다. 
DBCP들은 커넥션이 살아있는지 체크하기 위해 `SELECT 1` 과 같은 쿼리를 수시로 날립니다. 이게 운영상에 문제가 될 땐 거의 없죠. 
`SELECT 1` 이나 다름없는 비용을 갖는 쿼리가 수백개 수천개 날라가는 게 큰 문제가 될까? 글쎄요...

JPA 특성상 주인 관계에서 **영속성 전이** 를 일으킬 수 있는 것은 맞습니다.
그러나 `Comment` 가 연관관계의 주인이어야 하는지는 잘 모르겠습니다. 쉽게 생각하면... `Comment` 없는 `Post` 는 가능해도, `Post` 없는 `Comment` 가 가능할까요? 누가 진짜 주인인가요? 

생각해볼 거리를 몇개 전달해 드립니다. 👍 수고 많으셨고요, Roach의 생각도 들려주세요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/PostController.java
> +        model.addAttribute("comments", post.getComment());
`view`  안에서  `post` 객체를 탐색하면서 만들어줄 수 있었을 텐데, `.getComment()` 하신 이유가 궁금해요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Comment.java
> +    @JoinColumn(name = "USER_PK")
칼럼명에도 약어는 쓰지 않는 것을 이제 원칙으로 삼아주세요.
`writer_user_id` 나 `user_id` 정도면 적절할 것 같아요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Comment.java
> +    }
연관관계의 주인이 누가 돼야 할까요? 
`Comment` 부터 탐색한 후 `Post` 를 따라가는 시나리오가 많을까요, 혹은 그 반대가 많을까요?
요구사항에도 반대 방향의 매핑을 `@OneToMany` 로 구현할 것을 요구하는 듯합니다.
`Post` 가 관리하는 `List<Comment>` 에서 삭제할 `Comment` 를 pop out 시키고, 그에 따라 영속성을 전이시키는 구현을 고려해볼만 합니다(지금 우리 상황에선 soft delete가 요구되기때문에 pop out 보단 `List` 탐색 후 해당 객체의 상태를 `.deleted = true` 로 두어야 하겠네요). 

`Cascade` 라는 키워드로 학습해 보시고 다시 한 번 생각해 주세요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Comment.java
> +    private boolean deleteFlag = false;
필드명에 `Flag` 라는 접미사는 그렇게 좋지 않습니다.
상태를 나타낼 수 있는 형태 - 형용사, 명사 등 - 로 개선해 주세요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final List<Comment> comments = new ArrayList<>();
`@OneToMany` 필드를 `final` 로 선언하는 것은 아주 좋은 습관입니다. 👍 
_왜 그럴까요?_

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Post.java
> +
여기에서 `Comment` 의 상태가 관리돼야 할 겁니다.
메소드를 추가해주세요.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/User.java
> +    @Column(name = "USER_PK")
`USER` 테이블에 선언될 칼럼인데 굳이 `USER_` 라는 접두사를 뒀어야 했나라는 의문은 듭니다.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/repository/CommentRepository.java
> +    @Query("select c from Comment c where c.deleteFlag = false and c.id = :id")
`@Query` 의 사용은 당분간 봉인해 주세요.
스프링 데이터의 쿼리 메소드로 충분히 풀어낼 수 있습니다. 지금은 이 방법에 더 익숙해져보실 것을 추천합니다.

2021-03-15 14:33 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/CommentService.java
> +        Comment comment = new Comment(postService.getPost(postId), user, body);
좀 어색합니다. `Comment` 에 대한 영속성 관리의 책임은 `Post` 가 져야 하고, 
따라서 이 메소드도 `PostService` 에 `.addCommentToPost()` 와 같은 형태로 구현돼야 한다고 생각합니다.

2021-03-16 01:57 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final List<Comment> comments = new ArrayList<>();
일단 제 생각에는 만약에 comments 를 조회한다고 했을때, `= new ArrayList<>();` 가 되어 있지 않으면
아무것도 없는 상태에서는 NPE 가 발생할것 같다고 생각되어 선언해주었습니다.

2021-03-16 01:57 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/controller/PostController.java
> +        model.addAttribute("comments", post.getComment());
이거 처음에 잘안되서.. 왜 안되지 하고 지금 들여다보니
getter 에 comments 가 아닌 comment 라고 되어있었네요.
해당 부분 수정하여 반영했습니다. 👍

2021-03-16 02:04 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Comment.java
> +    @JoinColumn(name = "USER_PK")
넵 약어들보다는 조금더 의미있는 네이밍으로 지어지는 것이 좋겠네요!

2021-03-16 02:14 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/User.java
> +    @Column(name = "USER_PK")
헷갈리지 않게 해두던 습관때문에 그런데 아무래도 필요없는 행위인것 같네요. :)
앞으로 안하도록 해야겠네요.

2021-03-16 02:31 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Comment.java
> +    }
오 좋은 주제 였네요.
제가 너무 데이터베이스 관점에서만 생각한것 같기도 하네요.
사실 객체지향적인 관점에서는 Post 의 List 에 Comment 들이 돌아가는 형태로 가는것이 맞는 형태인것 같아요.
영속성 전이를 통해서 아래와 같이 post 가 영속화 될때 Comment 도 같이 영속화 시키는 것이 좋겠네요.

```java
    @OneToMany(mappedBy = "post", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    private final List<Comment> comments = new ArrayList<>();
```

2021-03-16 06:32 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Post.java
> +
해당 부분은 사용할 만할 부분을 찾지 못해서 제거 했습니다.

만약 사용된다면 댓글이 전부 삭제되어야 게시글을 삭제될 수 있다고 했을때 라고 한다면 이런 조건 문을 통해서 삭제가 불가능하게 할 것 같은데..

```java
public boolean isDeleteFlag() {
  return deleted && isDeletedAllComments();
}
```
선택 요구 사항이라 제 생각은 과연 글쓴이가 남이 댓글을 지울때까지? 글을 못지우는게 맞는가? 라는 걸 사용자 입장에서 생각해봤을때..
저는 그러한 사항은 아닌 것 같아서 글이 삭제되면 종속된 댓글들도 soft delete 하도록 했습니다.

2021-03-16 09:02 UTC, tmdgusya commented
일단 생각할 거리가 꽤 흥미롭고 새로운 주제들을 생각해보는데 도움이 많이 된것 같습니다.

그래서 아래와 같이 정리해보면..

## 일단 컨셉적인 문제?

- **Post 는 로딩 되는 동시에 Comments 를 가져오는것이 맞다.** 그리고 쿼리 자체도 분명히 늘어날 수 있는 테이블에 대한 조회가 이루어 지고 있다. 간략하게 User 는 언제든 추가되거나 삭제될 수 있고, Post , Comments 도 마찬가지이다.
따라서 해당 select 문은 여러개 이루어진다면 해당 개수에 따라서 n 만큼의 시간이 증가할 수 있게 된다.
그래서 해당 방법에는 EAGER 를 사용하는 것이 좋다고 생각한다.

- 하지만 공부를 위해서 Brian 이 던져준 컨셉들을 생각해보자 비용이 적은 쿼리가 급증하는 것이 과연 문제일까?

- 비용이 적은 쿼리는 그렇게 문제가 되지 않을것 같다. 왜냐? 딱히 병목을 일으키지 않을 것 같다. 흠 근데 어려운것은 여러 곳에서 동시에 수백 수천 쿼리를 날린다고 해도 부담이 가지 않을까? 라는 것이다. 근데 이러한 부분은 아직 데이터베이스에 대한 지식이 낮아서 잘 모르겠다. 

그래도 조금은 알아보자

```
explain select 1;
```
을 했을때를 보면 해당 쿼리는 어떠한 테이블도 이용하고 있지 않다.

아마 겉보기로 보기에는 O(1) 의 정도의 비용이 아닐까 싶다..?

DB 에서 ConnectionPool 을 유지할때 대략적으로 10초 마다 한번씩 SELECT 1 쿼리를 날린다고 한다.

```java
public class DBConnectionMaintainerThread extends Thread {
    private volatile boolean bGoOn = true;
    
    public void run() {
        DBConnection conn = null;
        Connection rConn = null;
        ResultSet RS = null;
        Statement readStmt = null;
        
        while(bGoOn) {
            try {
                Thread.sleep(10000);
                          
                conn = MainEntry.dbMan.getResource("cim");           
                rConn = conn.getRawConnection();
                readStmt =  rConn.createStatement();
                RS = readStmt.executeQuery("select 1");   
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                if(RS != null) {
                    try {
                        RS.close();
                        if(readStmt != null) readStmt.close();
                        if(conn != null) MainEntry.dbMan.putResource("cim", conn);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }
}
```

이런걸 보아 DB 에 SELECT 1 을 날린다고 해도 유지시간이 짧기에 실제 서비스에 큰 영향을 미칠것 같지는 않다.

## 생각한 것..?

쿼리가 급증하는 것 이런것이 문제가 아니라, 그 쿼리의 비용이 얼마인지, N 번씩 늘어난다고 했을때 충분히 장애를 일으킬 만한 요소인지? LAZY 방식으로 되는것과 EAGER 방식으로 될때 어떤 비용차이가 발생하는지? 이런것을 기준으로 생각하여 앞으로 쿼리를 짜야 겠다고 생각했습니다.

2021-03-16 10:42 UTC, wheejuni commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final List<Comment> comments = new ArrayList<>();
@tmdgusya 그것도 그렇긴 한데 조금 부족한 것 같네요. 
`cascade` 의 성질과 관련된 부분인데 조금 더 찾아보시면 좋겠습니다.

2021-03-16 10:44 UTC, wheejuni commented
@tmdgusya 좋은 고민이네요. 사실 처음에 구현하셨을 때 고민하시던 그 시각으로 실제 애플리케이션 개발에 임하시는 것이 가장 안전합니다. 
그래서 사실 첫 코드도 그리 나쁜 코드는 아니었습니다. 그치만 뭐든지 새로운 시각에서 들여다 보시길 기대했어요. 
앞으로도 더 많이 고민해주세요. 수정은 아직 덜 하신 것으로 알고 머지는 아직 하지 않겠습니다.

2021-03-16 11:48 UTC, tmdgusya commented
@wheejuni  좋은 리뷰 감사했습니다.

연속적으로 좋은 리뷰들 덕분에 좋은 개발자로 계속 성장해 나가는것 같네요.

2021-03-16 13:30 UTC, tmdgusya commented on src/main/java/com/codessquad/qna/entity/Post.java
> +    private final List<Comment> comments = new ArrayList<>();
계속해서 찾아보고 있는데 해당 부분은 제가 키워드를 놓치고 있는 것인지 찾기가 힘드네요.
일단 제 지식에서는 JPA 가 항상 Collection 을 초기화 하기에 final 로 재할당을 금지시키는건가요..?

이 부분은 잘 모르겠네요.

2021-03-17 11:47 UTC, merged