[새리]미션2 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #68
Opened 2021-03-14 11:59 UTC by min27604

안녕하세요 새리입니다. 
미션2 요구사항인 H2 DB 추가 및 설정, Repository 사용, 회원정보 수정을 마쳤습니다.
진행하는 과정에서 유저클래스에 로거를 쓰는 부분이나 엔티티 활용 등 새로운 개념을 적용시키는 데에 어려움을 많이 겪었습니다. 컨트롤러 부분에서 optional로 isPresent, get을 처리하는 부분은 여전히 헷갈립니다. 마구 지적해주시면 감사하겠습니다!
시간내주어 리뷰해주셔서 감사드리며, 배포주소는 아래와 같습니다.

https://sallys-qna.herokuapp.com/

2021-03-15 02:27 UTC, sonypark requested changes
안녕하세요 새리, 리뷰어 소니 입니다.😊
미션2 구현하느라 수고많으셨어요~~
링크 들어가서 확인해봤는데, 아래 요구사항대로 동작하지 않네요. 
- 비밀번호가 일치하는 경우에만 수정 가능하다.
비밀번호 없이 수정이 가능한데 한 번 체크해주세요~

그 외 간단한 코멘트 남겼으니 확인 부탁드립니다👍

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    }
생성자를 통한 의존성 주입👍

++ 현재는 컨트롤러에서 repository에 대한 의존성을 갖고 있는데, 서비스 단으로 분리해주면 좋을 것 같네요.
service에서 repository를 갖고 있고,controller에서는 service에 의존하는 방식으로.

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        questionRepository.save(question);
`writer, title, contents`가 null이거나 비어있는 경우는 어떻게 되나요?

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
👍

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        logger.info("New User Created: {}", user);
👍

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        model.addAttribute("user", user.get());
잘못된 user의 Id가 들어왔을 때 자동으로 유저 목록으로 리다이렉트 해주는게 좋은 방법일까요?
사용자 입장에서는 왜 리다이렉트가 되는지 모를것 같아서요. repository에 없는 id를 조회하려고 하면 exception을 발생시켜주는 건 어떨까요? `userRepository.findById(id).orElseThrow()`

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            return "redirect:/users";
여기도 마찬가지.

optional 객체의 `.get()` 메서드는 사용하지 않는다고 보시면 됩니다. NullPointException이 날 확률이 높아 실무에서는 거의 사용되지 않습니다.

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private long id;
id 타입을 primitive type으로 하신 이유가 있나요?

2021-03-15 02:27 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd kk:mm");
패턴을 상수로 빼준 것 좋네요. 위치만 수정하면 좋겠네요. 상수는 최상단에 위치시켜주세요~

2021-03-15 12:20 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private long id;
강의 동영상에 포비님께서는 클래스타입으로 선언하셨는데 특별한 이유는 없으시고 primitive type, class type 무방하지만 성능을 고려하면 primitive type을 추천하신다는 코멘트를 보고 정했습니다.

2021-03-15 12:20 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd kk:mm");
네 고쳤습니다!

2021-03-15 13:10 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        questionRepository.save(question);
유저컨트롤러처럼 Question 타입을 매개변수로 받도록 수정했습니다.

2021-03-15 13:44 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
>      private long id;
그렇군요. 둘 다 정상적으로 동작하지만 저는 Long 타입으로 선언하는걸 선호하는데요. 
아래 링크도 한 번 참고해보세요~

- [Boxed vs primitive type as entity id](https://stackoverflow.com/questions/51642979/boxed-vs-primitive-type-as-entity-id)
- [Current Documentation recommends to use Boxed Type.](https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-identifier)

2021-03-15 15:15 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        model.addAttribute("user", user.get());
예외발생시켜 핸들러로 처리하게 수정했습니다!

2021-03-17 06:59 UTC, min27604 commented
소니 다시금 리뷰 감사드립니다.
서비스 부분을 공부하는데 시간이 다소 걸려 이제서야 re-request 다시 보냅니다.
또 피드백이 필요한 부분이 있으면 짚어주세요! 감사합니다.

2021-03-17 15:21 UTC, sonypark approved these changes
새리 피드백 반영하느라 수고하셨어요!
몇가지 아쉬운 점이 있지만, 이건 다음 미션을 하면서 적용해보도록 해요~👍
Approve 하겠습니다~

2021-03-17 15:21 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        this.questionService = questionService;
👍

2021-03-17 15:21 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        questionRepository.save(question);
setTimeCreated를 외부에서 하지 않고, Question 생성자에서 초기화 해주면 어떨까요?
컨트롤러에서 Question 도메인으로 직접 데이터 바인딩 하지 않고 DTO를 사용하는 걸 권장합니다. DTO에 대해서도 공부해보세요~

2021-03-17 15:21 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @ExceptionHandler(NoSuchElementException.class)
NoSuchElementException은 언제 발생하나요?

2021-03-17 15:21 UTC, sonypark commented on src/main/resources/templates/error.html
> +</body>
현재 예외가 발생하면 이 페이지를 보여주고 있는데,
`Page Not Found` 라는 메시지가 모든 error가 발생했을 때 보여질 메시지로는 적합하지 않은 것 같네요.

2021-03-17 15:21 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public Question() {}
기본생성자의 접근제어자는 protected가 좋을 것 같아요.

[JPA Entity의 기본 생성자 관련 예외 정리하기](https://wbluke.tistory.com/6)

2021-03-18 00:06 UTC, merged

2021-03-18 07:53 UTC, min27604 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public Question() {}
코드리뷰때 들었던 부분인데 왜 protected가 더 나은 지 몰랐는데 링크 감사합니다!

2021-03-18 07:53 UTC, min27604 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @ExceptionHandler(NoSuchElementException.class)
수정하는 과정에서 IllegalArgumentException으로 해야했는데 깜빡했네요ㅠㅡㅠ 주의하겠습니다

2021-03-18 07:53 UTC, min27604 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        questionRepository.save(question);
네 참고하고 공부해보겠습니다. 감사합니다.