미션 4 객체 - 관계 매핑
codesquad-members-2021/spring-boot-qna pull request #69
Opened 2021-03-15 01:30 UTC by PizzaCola-K

[배포 주소](https://safe-waters-28423.herokuapp.com/)

미션 3와 내용이 겹치는 것이 많아서 수정한 것은 많이 없습니다. 이번에 진행한 것은 다음과 같습니다.

## deleted 플래그 추가
Question와 Answer가 deleted 플래그를 갖고, 삭제되면 같은 테이블에서 deleted 플래그만 true로 바뀝니다.

## Question 에서 Answer와 OneToMany
Question에서 Answer를 `OneToMany` 관계의 List로 가집니다. 그리고, Hibernate의 애노테이션인 `Where`을 이용하여 삭제되지 않은 답변들만 가져옵니다.

## 질문 삭제로직 변경
원래 질문을 삭제하면 답변도 한번에 다같이 삭제됐는데, 이제는 다른사람의 답변이 존재하지 않는 경우에만 삭제할 수 있습니다.

## Service 계층 구현
저번 미션에서 리뷰어께서 주셨던 과제인데, 여러가지 공부하다보니 늦어져서 이미 머지를 받아 이번 미션4에서 반영하였습니다.

공부한 내용을 간단히 써보면, 이런 것을 Multitier Architecture 또는 Layered Architecture라고 합니다. 3계층으로 나누면 presentation, business, data 계층으로 구성합니다.

Spring MVC는 프레젠테이션 계층에 속하여 웹 어플리케이션이면 HTTP 요청을 검증하고, HTTP 응답과 View를 구성하여 클라이언트에 보내줍니다.

Service는 비즈니스 계층이 되어 프레젠테이션 계층에서 요청하는 작업을 수행합니다.

Repository는 데이터 계층이며, DB에 접근하여 자료를 저장하거나 제공하는 역할을 합니다.

이정도 구분에 따라서, User / Question / Answer Service를 추가하였고, HTTP 요청의 형태가 정상적이면 이후에는 서비스에서 처리하도록 하였습니다.

어떻게 해야할지 잘 몰라서 여러가지 찾아보고 하느라 미흡한 것이 많습니다. 리뷰 잘부탁드립니다!

2021-03-16 14:10 UTC, ksundong requested changes
안녕하세요! K! 리뷰어 Dion 입니다!!
4번째 미션까지 수행하시느라 고생 많으셨습니다.
애플리케이션은 요구사항에 잘 맞춰서 구성된 것 같습니다. 잘하셨어요.👍

코드 관련해서만 간단히 코멘트를 드리도록 하겠습니다.

- 정렬을 습관화 해주세요.
- 생성자 인젝션을 사용할 때, `@Autowired`는 붙여주지 않아도 됩니다.
- 코드를 일관성 있게 작성 할 수 있도록 노력해주세요!
- 서비스를 구현할 때, `interface`와 이를 구현하는 구현 클래스 구조로 만들어주셨는데, 저는 일단은 그 방법은 나중으로 미뤄두셔도 된다고 말씀드리고 싶네요. 일단은, `Impl`이라는 좋지 않은 네이밍이 등장하기 쉬워지기 때문입니다.
- 한 메서드가 너무 많은 역할을 하고 있다면, 일단 개행으로 구분지어보고, 메서드로 분리해봅시다.

4단계 진행해주시느라 너무 고생많으셨고, 코드에 조금 생각해보셨으면 하는 부분이 있어 **변경 요청** 드립니다.
궁금한 점이나, 이해가 되지 않는 부분, 도움이 필요한 부분, 토론하고 싶은 부분이 있으시면 언제든 코멘트 남겨주세요!
고생하셨습니다~

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @Autowired
생성자 Injection을 사용해 줄 때에는 `@Autowired` 애너테이션을 굳이 붙여주지 않아도 됩니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping()
```suggestion
    @PostMapping
```

이렇게도 사용이 가능합니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable("questionId") Long questionId, Answer answer, HttpSession session){
```suggestion
    public String createAnswer(@PathVariable("questionId") Long questionId, Answer answer, HttpSession session) {
```

항상 코드 정렬을 습관화해주세요~

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable("questionId") Long questionId, Answer answer, HttpSession session){
그리고 아래의 `delete`처럼 `Answer`는 굳이 없어도 좋을 것 같습니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.deleteAnswer(questionId, answerId, loginUser);
코드는 일관성 있게 작성해주세요. 어디는 Inline으로 작성하고 어디는 variable을 추출해주기보다는 일관성있게 한 형태로 작성하실 것을 권장합니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        model.addAttribute("questions", questionService.getQuestionList());
저는 이렇게 사용하기 보다는 `redirect`해주시기를 더 권장드리겠습니다.
Home에서 Question을 안다는 것은 제가 생각하기에 관계없는 정보를 아는 것과 다르지 않다고 생각돼요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HttpSessionUtils.java
유틸리티성 클래스는 인스턴스가 생성될 수 없도록 `private` 생성자를 생성해주세요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HttpSessionUtils.java
> +    public static User getLoginUser(HttpSession session) throws NotLoggedInException{
```suggestion
    public static User getLoginUser(HttpSession session) throws NotLoggedInException {
```

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String query(Question question, HttpSession session) {
제가 생각하기엔 메서드명은 create가 더 좋지 않았을까? 하는 생각이 들어요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String qnaShow(@PathVariable("questionId") Long id, Model model) {
여기도 그냥 `show`가 낫겠네요!

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String qnaShow(@PathVariable("questionId") Long id, Model model) {
혹은 다른 이름으로 바꿔도 좋을 것 같습니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String update(@PathVariable("questionId") Long id, Question updatedQuestion, HttpSession session) {
너무 네이밍만 말씀드리는 것 같긴 한데, 저 같은 경우에는 파라미터명에 이미 update 되었다는 의미 보다는 될 것이다라는 의미를 담아서 파라미터명을 지어줄 것 같아요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      }
꼭 여기엔 있지 않아도 되는 메서드 같아요. K 생각은 어떤가요?

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/advice/GlobalControllerExceptionHandler.java
> +        model.addAttribute("loginFailed", true);
model 활용 좋네요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private boolean deleted;
빈 줄은 왜 띄워주셨나요?

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @Where(clause = "deleted = false")
적절히 잘 활용해 주신 것 같아요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void delete(){
```suggestion
    public void delete() {
```

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public boolean matchesId(Long id) {
저는 이전 네이밍도 좋은 것 같아요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ForbiddenException.java
> +    public ForbiddenException(String message) {
저는 메시지 기본값을 가지고 있는 생성자를 만들어주는 것을 선호하는 편입니다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/handlebarsHelper/handlebarsHelper.java
> +        }
`stream`으로 바꾸기 좋아 보이는데 한 번 바꿔볼까요?

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +public interface AnswerService {
인터페이스를 만들어주지 않아도 됩니다.
둘이 조금 차이가 있긴 한데, 가급적이면 필요한 시점에 Interface를 분리해주는 편이 좋다고 생각해요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerServiceImpl.java
> +public class AnswerServiceImpl implements AnswerService{
`Impl`이라는 네이밍은 '지양' 합시다.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionServiceImpl.java
> +        questionRepository.save(question);
적어도 세 가지 일을 하고 있는데요. 메서드 분리를 해봅시다.
그리고 마지막 `save`를 해주는 이유는 무엇인가요?

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .ifPresent(u -> {throw new UserExistException();});
```suggestion
                .ifPresent(u -> throw new UserExistException());
```

살짝 애매하긴 했는데, 괜찮은 로직인 것 같네요.

2021-03-16 14:10 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .orElseThrow(() -> new UnauthorizedAccessException("권한이 존재하지 않습니다."));
오류 메시지가 조금 이상하다는 느낌이 드네요.

2021-03-17 00:34 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @Autowired
[Spring Core:Using Autowired](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-autowired-annotation)

어제 팀 리뷰 중에 나왔던 이야기네요! 스프링 4.3부터, 생성자가 하나면 `@Autowired`가 없어도 된다고 합니다.

아직 스프링을 잘 몰라서, 어렵습니다.

2021-03-17 00:50 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping()
그렇군요. `@PostMapping` 도, `@PostMapping()`, `@PostMapping('")` 등의 방식이 있는데, 어떤 것이 좋을지 잘 모르겠습니다. 없는게 깔끔한것 같긴 해요.

2021-03-17 02:41 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable("questionId") Long questionId, Answer answer, HttpSession session){
메소드와 클래스 이름 정하는 것이 제일 어려워요. 컨트롤러와 관계에서 기능이 드러나는 메소드의 이름은 동사형으로만 적어도 좋은 것 같습니다.

---Service도 비슷한 것 같은데, 서비스가 대상으로하는 객체를 다룬다고 생각을 하면 AnswerService.create() 같은 메소드 이름이 더 좋은 것 같아요.

2021-03-17 03:06 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        answerService.deleteAnswer(questionId, answerId, loginUser);
네 알겠습니다.

2021-03-17 03:08 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/HttpSessionUtils.java
잊고 있었네요. 빨리 추가하겠습니다.

2021-03-17 03:24 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public boolean matchesId(Long id) {
is matching이란 표현이 너무 어색한거 같아서 바꿨습니다. matching이란 표현은 형용사로 쓰이는 것이 일반적인 것 같아요.

2021-03-17 03:35 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      }
앗... 그렇네요. 서비스에게 넘기는 것이 좋은것 같습니다.

2021-03-17 03:45 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/handlebarsHelper/handlebarsHelper.java
> +        }
```java
long count = answers.stream()
        .filter(a -> !a.isDeleted())
        .count();
return String.valueOf(count);
```
이렇게 수정할 수 있습니다. 근데 `Question`에서 `@OneToMany(mappedBy = "question")`, `@Where(clause = "deleted = false")` 답변 리스트를 가져와서 더 이상 쓰지 않는걸 까먹었습니다.

그리고 어떤 때에 스트림을 써야할 지 잘 모르겠습니다. 가독성이 좋아진다면 사용하는 것이 좋을까요? 성능으론 스트림을 사용하지 않는 것이 좋다고 해서요.

2021-03-17 03:48 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .ifPresent(u -> {throw new UserExistException();});
이거 리턴이 아니라서 그런지 중괄호 빠지면 컴파일 에러가 생깁니다.

2021-03-17 03:50 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .orElseThrow(() -> new UnauthorizedAccessException("권한이 존재하지 않습니다."));
유저 정보 업데이트시에 비밀번호가 틀렸을 경우인데 "비밀번호가 틀렸습니다."가 맞네요.

2021-03-17 05:15 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        model.addAttribute("questions", questionService.getQuestionList());
URL의 의미를 생각해보니, /questions에 접속하면 질문의 목록을 보여주고, / 페이지는 존재하지 않는 상태로 /questions로 리다이렉션 해주는 것이 좋은 것 같습니다.

2021-03-17 05:42 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    private boolean deleted;
아무 이유 없이 추가할때 한칸 더 띄워서 추가한 것 같습니다. 수정하겠습니다.

2021-03-17 06:38 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/QuestionServiceImpl.java
> +        questionRepository.save(question);
save를 하면 Id를 받지 않은 새 객체의 경우 PERSIST가 되고, Id가 동일한 것이 존재하는 객체의 경우 MERGE 된다고 알고 있습니다. 

다른 곳에서는 `save`를 해야 DB로 반영이 되는데, 여기서 `@Transactional`을 붙이면 `save`를 하지 않아도 DB에 저장이 되네요. jpa를 조금밖에 몰라서 적었습니다.

근데 `@Transactional`을 빼고, question만 save해도 `@OneToMany`에 Cascade 옵션을 준 것이 없는데도 불구하고 answer도 업데이트되네요.

여기서 `@Transactional`을 적은 이유는 질문이 삭제될 때 답변도 전부다 삭제하는 경우에는 전체가 성공하거나 전체가 실패해야 된다고 생각해서 사용했습니다.

2021-03-17 06:46 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/exception/ForbiddenException.java
> +    public ForbiddenException(String message) {
기본 메시지를 갖는 생성자를 추가하겠습니다.

2021-03-17 07:13 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String update(@PathVariable("questionId") Long id, Question updatedQuestion, HttpSession session) {
아직 업데이트 되지 않았으니 updating이 맞는 것 같아요. 근데 이름 짓는게 너무 어렵습니다.

2021-03-17 07:22 UTC, PizzaCola-K commented
수정사항 정리합니다.

- 모든 파일에 Intellij 자동 포매팅 적용했습니다.
- 생성자가 하나고, 이 생성자로 주입받는 경우에 `@Autowired`를 뺐습니다. (전부 뺐습니다.)
- 일관적으로 변수를 따로 빼지 않고 패러미터로 바로 메소드를 불러서 넣었습니다.
- 서비스 인터페이스를 제거하였습니다.
- QuestionService의 delete 메소드 내부의 기능을 private 메소드로 분리하였습니다.
- 그외의 메소드 이름 컨벤션 수정

코드 리뷰 감사드려요!

2021-03-17 10:08 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @Autowired
잘 공부하셨네요!

2021-03-17 10:08 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
>      @PostMapping()
그냥 괄호만 적어주는 것은 거의 사용하지 않는다고 보시면 됩니다~

2021-03-17 10:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +    public String createAnswer(@PathVariable("questionId") Long questionId, Answer answer, HttpSession session){
네이밍은 계속해서 좋은 네이밍을 고민해봐야죠!
저도 회사에서 3일동안 네이밍 고민할 때도 있고 그렇습니다. 적당히 만들고 넘어간 다음 나중에 다시 확인하는 것도 좋은 것 같아요.

2021-03-17 10:11 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      public String update(@PathVariable("questionId") Long id, Question updatedQuestion, HttpSession session) {
맞아요 어려운게 맞습니다 ㅎㅎ
계속 좋은 네이밍을 고민하다보면 좋은 네이밍을 하실 수 있지 않을까 싶습니다!

2021-03-17 10:11 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    public boolean matchesId(Long id) {
그러면 matches도 나쁘지 않아보이긴 합니다!
네이밍 역시 어렵네요!

2021-03-17 10:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/handlebarsHelper/handlebarsHelper.java
> +        }
사실 성능은 거의 고민하지 않으셔도 됩니다.
자바지기님께서 항상 하는 얘기들이 있는데, 컴퓨팅 파워가 우리의 몸값보다 훨씬 싸기 때문에 우리에게 더 맞춘 코드를 작성하고
성능이 필요한 시점에 최적화를 고려하라는 얘기가 있습니다.
그리고 이펙티브 자바에서도 아마 stream을 사용한 코드와 for를 사용한 코드를 비교해보고, 더 읽기 좋은 쪽을 취사선택하라고 나와있을겁니다.

결론은 성능 신경쓰지 마시고, K가 좋아보이는 쪽을 선택해보세요!

2021-03-17 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionServiceImpl.java
> +        questionRepository.save(question);
사실 JPA에서는 Dirty Check라는 기능이 있어서 `save` 를 해주지 않아도 됩니다만
이건 저희 과정에서 아직은 배울 내용이 아니니 넘어가봅시다~

2021-03-17 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .ifPresent(u -> {throw new UserExistException();});
앗 그렇군요... 그렇다면 if문으로 풀어내는게 더 나을 것 같네요.

2021-03-17 10:44 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/UserServiceImpl.java
> +                .ifPresent(u -> {throw new UserExistException();});
전에 Optional을 isPresent()와 get을 이용해서 썼던 것이 별로인 것같아서 isPresent()를 피하던 것이 오히려 보기 안좋은 코드를 만들었네요.
```java
if (userRepository.findByUserId(user.getUserId()).isPresent()) {
    throw new UserExistException();
}
```

이게 조금 더 보기 좋은 것 같아요.

2021-03-17 10:44 UTC, ksundong approved these changes
피드백 반영하느라 고생많으셨습니다!
바로 다음단계를 진행하셔도 될 것 같아요!
고생많으셨습니다~

---

JPA는 많이 어렵고, Spring도 많이 어렵습니다.
자동 포맷은 잘 활용해주시면 코딩이 편해집니다.
원래 실수하기 마련이고, 그래서 코드리뷰를 통해서 실수를 바로잡을 수 있는 기회가 주어집니다.

네이밍은 저도 어렵고, 선배 개발자들도 많이들 어려워 하는 부분입니다.
좋은 네이밍을 향해서 계속 노력해봅시다~

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
>      private LocalDateTime time;
time보다는 createDateTime 정도로 변경하시는 것을 추천드려요~

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer getWithAuthentication(Long questionId, Long answerId, User loginUser) {
외부에서 쓰일 일이 있는 메서드인가요?
내부에서만 사용될 것 같아서요!

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
외부에서 사용될 일이 없는 메서드이지 않을까 싶어요.

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/QuestionRepository.java
>  }
false로만 쓰일것이라면 그냥 메서드에 false를 드러내는게 낫지않나요?

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        question.delete();
이걸 question 안에서 해결할 수도 있어보이는데, 한 번 생각해보세요~

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                });
`if`문으로 해결하는게 더 깔끔할 것 같아요.

2021-03-17 10:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public User getById(Long id) {
저는 개인적인 성향인데 `getXXX`는 별로 선호하지 않는 네이밍입니다!

2021-03-17 11:13 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/domain/QuestionRepository.java
>  }
```java
Optional<Question> findByIdAndDeletedFalse(Long id);
List<Question> findAllByDeletedFalse();
```

[Spring Data JPA: Query Creation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation)

이런 것도 되네요

2021-03-17 11:35 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/domain/Answer.java
>      private LocalDateTime time;
앗 그렇네요.

2021-03-17 11:49 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
질문을 수정할때 처럼 답변을 수정하기 위해서 /questions/{questionId}/answers/{answerid}/form에 Get으로 접근하는 경우에 AnswerController의 updateForm 메소드에서 사용합니다.

2021-03-17 12:31 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        question.delete();
그렇네요. Question에게 시키는게 나을것 같아요. 근데 이렇게 하면 예외는 QuestionService에서 만드는 것이 좋을까요?

2021-03-17 12:56 UTC, PizzaCola-K commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public User getById(Long id) {
[How and why to decide between naming methods with “get” and “find” prefixes](https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes)

읽어보니, get은 바로 주는 것이고 null 같은게 아닐때, find는 뭔가 시간이 걸리는 경우면서 찾지 못하는 경우도 있을때 보통 쓴다고 되어있긴 합니다.

근데 
>Do not use find or get prefixes. This is a violation of [UniformAccessPrinciple](https://martinfowler.com/bliki/UniformAccessPrinciple.html) coined by bertrand meyer. Why not create a method like the following:
>public String revision(Item item)

와 같이 UniformAccessPrinciple에 위배되기 때문에 get이나 find처럼 구분하는 것은 좋지 않다는 의견도 있습니다.

일단 영어를 잘 못해서 get find 정도밖에 생각나지 않아요. ㅠ

2021-03-17 13:52 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
아하 그렇군요!

2021-03-17 13:53 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        question.delete();
예외도 Question에서 발생하도록 해도 좋을 것 같은데요?

2021-03-17 13:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public User getById(Long id) {
retrieve라는 단어도 있습니다만, 오늘 제가 들은 강의에서는 조회해오는 메서드는 명사로 네이밍을 한다고 하네요.
참고해보시면 좋을 듯 합니다.

4. 메서드 이름을 신중하게 선택하세요.
메서드의 이름은 무조건 동사가 아닌 빌더의 이름은 명사로, 조정자의 이름은 동사로 짓는 것이다.

- 빌더: 뭔가를 만들고 새로운 객체를 반환하는 메서드, 항상 뭔가를 반환, 리턴 값이 있는 메서드, 항상 명사여야 한다. 여기에는 형용사를 붙여 메서드의 의미를 좀 더 풍부하게 해줄 수도 있다.
- 조정자: 객체로 추상화한 실세계 엔티티를 수정하는 메서드, 반환 타임은 void, 이름은 항상 동사여야 한다. 여기에는 부사를 붙여 메서드의 의미를 좀 더 풍부하게 해줄 수 있다.
무엇을 빌더, 조정자로 어떻게 만들 것인가가 어려울 것이다.

객체는 자신의 의무를 수행하는 방법을 알고 있고 존중받기를 원하는 살아있는 유기체이다. 계약에 기반해 살아가고 싶어한다.
위임을 할 때에는 확실하게 해라.
- 음악을 틀어주세요.
- 음악을 틀고, 현재의 볼륨 상태를 말해주세요.

- 조합한 것은 풀어낸다. (여러 역할을 하고 있으니 클래스로 분리한다.)
- Boolean은 가독성 측면에서 빌더이지만 형용사로 이름을 짓는 것을 추천한다.

2021-03-18 09:22 UTC, PizzaCola-K commented
추가로 수정한 것입니다.

- Service나 HttpSessionUtils에서 get 메소드 대신 명사형 이름으로 수정하였습니다.
  - 명사형도 괜찮은 것 같습니다. 어제 찾아본 [링크](https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes)에서 [how-to-name-clojure-functions](https://stuartsierra.com/2016/01/09/how-to-name-clojure-functions)도 봤었는데, closure이긴 해도 명사형으로 쓰는 것도 좋네요.
  - getter setter 같은 것에 얽메일 필요는 없는 것 같은데, 어떤 사람들은 메소드 이름은 동사형이어야 한다는 이야기도 있어서, 결국은 팀원들 끼리 다같이 공유하는 컨벤션 같은 것을 만들고 따르는 것이 좋을 것 같습니다.
 
- Question의 삭제를 이제 Question에게 맡깁니다.
  - Exception을 서비스에서 발생시키는 것이 좋은지 이런 것들을 고민해봤는데, Question에서 발생시켜도 문제 없는 것 같습니다. 결국 이후에 동작은 핸들러에게 맡기는 것이니까요.
- ifPresent -> throw 대신  if ( isPresent ) { throw } 로 수정
  -  orThrows는 내부에 Supplier를 받아 Exception을 반환하는거를 받아서 내부적으로 throw하는 로직이라 깔끔한데, ifPresent는 Consumer를 받는 거라 Exception 발생에는 어울리지 않는 것 같습니다.

리뷰 감사드립니다. 특히 이름 짓는 것이나 객체의 역할 등에 대해서 고민을 많이 해볼 수 있었습니다.

2021-03-18 12:58 UTC, ksundong commented
> 추가로 수정한 것입니다.
> 
> * Service나 HttpSessionUtils에서 get 메소드 대신 명사형 이름으로 수정하였습니다.
>   
>   * 명사형도 괜찮은 것 같습니다. 어제 찾아본 [링크](https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes)에서 [how-to-name-clojure-functions](https://stuartsierra.com/2016/01/09/how-to-name-clojure-functions)도 봤었는데, closure이긴 해도 명사형으로 쓰는 것도 좋네요.
>   * getter setter 같은 것에 얽메일 필요는 없는 것 같은데, 어떤 사람들은 메소드 이름은 동사형이어야 한다는 이야기도 있어서, 결국은 팀원들 끼리 다같이 공유하는 컨벤션 같은 것을 만들고 따르는 것이 좋을 것 같습니다.

네네! 명사형도 괜찮고, 이전과 같은 방식도 괜찮습니다. 하지만, 뭔가 안좋다는 냄새가 난다면, 한 번 생각해볼만한 주제인 것 같아요.

그리고, 코딩을 하면서 느끼는 것이지만, '무조건'이라는 말은 거의 없는 것 같아요. K 말처럼 협의를 하는 것이 중요한 것 같습니다.

> * Question의 삭제를 이제 Question에게 맡깁니다.
>   
>   * Exception을 서비스에서 발생시키는 것이 좋은지 이런 것들을 고민해봤는데, Question에서 발생시켜도 문제 없는 것 같습니다. 결국 이후에 동작은 핸들러에게 맡기는 것이니까요.

좋네요. 제가 생각하기엔 그 쪽이 좀 더 이상적인 자바코드 형태가 아닐까 생각해봅니다.

> * ifPresent -> throw 대신  if ( isPresent ) { throw } 로 수정
>   
>   * orThrows는 내부에 Supplier를 받아 Exception을 반환하는거를 받아서 내부적으로 throw하는 로직이라 깔끔한데, ifPresent는 Consumer를 받는 거라 Exception 발생에는 어울리지 않는 것 같습니다.

`stream`이 Java8에서 도입이 시작된 것이라서 부족한 기능이 많습니다. Java 11이 좀 더 다양한 API를 제공했던 것 같아요.

> 리뷰 감사드립니다. 특히 이름 짓는 것이나 객체의 역할 등에 대해서 고민을 많이 해볼 수 있었습니다.

리뷰의 의도를 알아주셔서 감사합니다. 고생하셨습니다~

2021-03-18 15:06 UTC, merged