[Jane] 4번째 PR 드립니다. (XHR 맟 AJAX 적용)
codesquad-members-2021/spring-boot-qna pull request #70
Opened 2021-03-15 01:43 UTC by janeljs

안녕하세요 제인입니다🙂 원래는 미션 4 PR을 드려야 하지만, 지난 PR에서 미션 4 요구사항에 대한 피드백을 받아 수정한 이후 해당 부분에 대한 변경 사항이 없어 미션 5 요구사항을 만족한 뒤 PR을 드립니다.

### 추가 및 변경된 부분
- JSON API, AJAX를 활용한 답변 추가 기능
- AJAX를 활용한 답변 삭제 기능
- 질문 목록 답변 수 보여주기
- 도메인 클래스에 대한 중복제거
  - AbstractEntity 클래스 추가 후 각 Answer, Question, User가 AbstractEntity를 상속하도록 함
- Swagger 라이브러리를 통한 API 문서화 및 테스트
- 404 에러 페이지

그럼 이번에도 리뷰 잘 부탁드리겠습니다! 감사합니다🙇‍♀️

2021-03-16 00:38 UTC, wheejuni requested changes
4단계까지 빠르게 잘 진행해 주셨네요. 수고 많으셨습니다. 👍 
Swagger 구성도 코드 상으론 잘 된듯 보이네요. 물론 실행해보진 않았습니다. 
4단계까지 별탈없이 잘 하신 것 같아서 조금 더 깊게 들어가는 학습이 필요한 피드백을 살짝 남겨 봤는데요, 질문 있으면 부담없이 전달해 주세요.

2021-03-16 00:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        logger.info("{}님께서 답변 작성에 성공하셨습니다.", user.getUserId());
_(이제 4단계니까...)_ 로거를 사용하실때는 로깅의 여파(?) 도 생각하셔야 합니다.
실제로 답변이 등록될때마다 이렇게 로그가 한 줄씩 써진다면, 더 중요한 다른 로그들을 빠르게 포착할 수 있을까요?
제 생각에 이 정도의 로깅은 `.debug()` 레벨이 적절합니다.

2021-03-16 00:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        questionService.update(question);
이 로직은 왜 들어갔죠?

2021-03-16 00:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.update(question);
`questionService.update(title, contents);` 이면 안 되나요?

2021-03-16 00:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElseThrow(RuntimeException::new);
그냥 `RuntimeException` 은 좀 섭섭하네요.

2021-03-16 00:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +
`Service` 클래스가 도메인에 대해서 단순히 CRUD만 수행하게끔 구성하지 마시고,
이 클래스가 다루는 도메인 엔티티에 대한 튼튼하고 좋은 창구가 되어야 합니다. 그리고 view layer로 나가기 이전의 마지막 수문장 역할도 해야 하죠. 특히 우리는 JPA를 사용하고 있기 때문에 `Service` 가 이 역할을 수행하는 것이 특히 중요합니다(아직 이해가 잘 안되실 수도 있습니다). 

managed entity의 상태 전이(DETACHED <-> MERGED)가 최종적으로 이뤄지는 곳이여야 하고요, view를 구성하는데 필요한 모든 정보가 완전하게 갖춰진 상태로 객체는 이 클래스를 떠나야 할 겁니다. 

그런 면에서 본다면 지금 설계하신 `Service` 클래스는 기능적으로 조금 부족한 면이 보이네요. 앞서 컨트롤러에서도 피드백 남겼는데, _수정_ 기능의 경우에도 `Controller` 에서 엔티티 클래스에 접근해서 내용을 다 바꾼 후 `Service` 호출하는 그림이 아닌, `Service` 에 바로 요청을 릴레이하는 구조가 되면 좋겠어요.

2021-03-16 02:19 UTC, janeljs commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        logger.info("{}님께서 답변 작성에 성공하셨습니다.", user.getUserId());
INFO가 상태변경과 같은 정보성 메시지를 나타낼 때 사용한다고 블로그에서 봤었는데, 서술이 포괄적이라 의미를 다르게 이해하고 사용한 것 같습니다. 해당 부분은 답변을 추가하는 기능을 디버깅할 때 어떤 부분이 문제인지 확인하기 위해 추가한 로거이므로 debug로 수정할게요! 코멘트 감사합니다ㅎㅎ

2021-03-16 02:29 UTC, janeljs commented
![image](https://user-images.githubusercontent.com/68000537/111247037-ab070d00-864a-11eb-9ca8-ed924be1ec94.png)
Swagger를 처음 써봐서 잘 알지는 못했지만 몇 가지 테스트했던 기능들은 잘 돌아갔습니다!ㅎㅎ

2021-03-16 02:34 UTC, janeljs commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        questionService.update(question);
처음에는 Question 내부에 countOfAnswer라는 필드를 따로 선언하여 관리하고, deleteAnswer 메서드로 수를 감소시키도록 설계했어서 해당 필드를 업데이트하기 위해 로직을 추가했었습니다. 그런데 ` public int getAnswerSize() {  return answers.size();  }`를 이용하면 해당 필드가 필요 없어 뒤늦게 countOfAnswer와 deleteAnswer 메서드를 제거했었는데 저 부분을 빼는 걸 까먹었네요 ㅠㅠ 제거하였습니다!

2021-03-16 02:54 UTC, janeljs commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.update(question);
questionService 내부에 `update(question, title, contents)` 메서드를 추가하고 question.update(title, contents)는 questionService 내부의 update 메서드로 넣어주었습니다! questionService.update(title, contents)로 리팩토링하는 방법이 떠오르지 않아 이렇게 바꾸어 보았는데 잘못된 방향이었다면 피드백 부탁드립니다 ㅎㅎ

2021-03-16 03:04 UTC, janeljs commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElseThrow(RuntimeException::new);
AnswerNotFoundException을 정의해주었습니다! 섭섭하셨다니 죄송합니다😢😢😢 변명을 해보자면 ajax 적용하는데 에러가 많이 났고 해결하기 힘들었어서 다른 부분은 신경을 많이 못 썼네요😭

2021-03-16 03:36 UTC, janeljs commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +
아직 기본 지식이 부족해서 이해하기 어렵네요ㅎㅎ ㅠㅠ 

1. entity 주석을 단 아이들은 기본적으로 EntityManager에 의해 관리되는 상태인가요? 영속성 컨텍스트는 어플리케이션과 db 사이에서 엔티티들을 저장하는 곳?이라고 들었는데 `entityManager.persist()` 같은 걸 사용하지 않아도 영속성 컨텍스트에 들어가 있는건지 궁금합니다!
2. JPA 레파지토리에 데이터를 저장하거나 삭제하면 detached에서 merged 상태로 변경되는 건가요? 저는 따로 `EntityManager.merge()`를 사용해본 적이 없는데 어떻게 서비스 클래스에서 어떻게 상태전이가 일어나는지 이해가 되지 않아요. 엔티티가 EntityManager에 의해 관리되지 않으면서도 db의 오브젝트를 나타내고 있으면 detached 상태라는데 이 설명도 확 와닿지 않네용 ㅠㅠ 

3. 일단은 Controller에서 엔티티 클래스에 직접 접근하고 있던 부분들을 다 서비스에 접근하는 것으로 바꾸고, 서비스는 엔티티 클래스에 접근하는 방식으로 리팩토링하면 될까요?

2021-03-16 03:47 UTC, janeljs commented
@wheejuni 소중한 시간을 내어 코드 리뷰해주셔서 감사합니다🙂 답글로도 몇 가지 질문 남겼구요! 질문 부담없이 달라고 하셔서 몇 가지 질문을 더 드리려고 합니다ㅋㅋ

1. entity 내부의 기본 생성자를 protected로 정의하고 있는데요! private으로 정의해도 잘 작동하는 것 같아서요! 혹시 private으로 바꿀 경우 발생할 수 있는 side effect가 있는지 궁금합니다.

2. 지난 pr에서도 드렸던 질문인데요! exceptionhandler를 private으로 정의하여 사용하고 있는데요! 예제에 보면 protected를 사용하는 경우가 많은 것 같아 protected를 사용해야하는 이유가 있는지, private으로 선언해도 무방한지 궁금합니다!

3. 지금은 각 예외마다 메시지를 지정해주고 해당 예외가 발생할 경우 나오는 메시지를 바로 뷰에 출력하고 있는데요! 이런 방식의 구현이 괜찮은 건지 피드백 부탁드려요ㅎㅎ
![image](https://user-images.githubusercontent.com/68000537/111252795-4309f400-8655-11eb-8388-4003ba285593.png)

4. 현재 Entity 클래스에 `@NotBlank` 애노테이션을 사용하고 있는데요! Entity 클래스에 이런 애노테이션을 붙여도 되는지, 따로 DTO를 만들어주는 것이 좋은지 피드백 부탁드립니다!

감사합니다🥰

2021-03-16 08:40 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        questionService.update(question);
@janeljs 잘하셨어요 ㅎㅎ 예시는 예시일 뿐

2021-03-16 08:40 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElseThrow(RuntimeException::new);
섭섭하다는건... 드립인 건 아시죠? ㅠㅠ

2021-03-16 08:42 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +
1. 개발하시면서 `entityManager.persist()` 라는 코드를 한번이라도 짜보신 적이 있나요? 아마 없을 겁니다. 그러면 누군가 대신 해 주고 있는 걸텐데요. 누가 대신하고 있는 건지, 스프링에선 `EntityManager` 를 어떻게 생성하고 관리하는지 자세히 학습해 보세요.
2. 1과 같습니다. 누군가가 대신 해 주고 있는 겁니다. _영속성 컨텍스트_ 를 넘나들기 위해선 어떤 상태 전이가 필요할지 한번 생각해 보시고, 그렇다면 영속성 컨텍스트는 어디서부터 어디까지 존재하는지도 알아보세요. 그리고 개발자가 영속성 컨텍스트의 범위를 지정하려면 어떤 표현을 사용하는지도 알아 보시고요(제인도 이미 몇 번 사용하셨습니다).
3. 네.

2021-03-16 08:45 UTC, wheejuni commented
ㅋㅋ 답변 드릴게요.

1. 제가 생각하기로는 없네요.
2. `Exception Handler` 라는 애노테이션을 붙이는 것만으로 예외 처리가 위임되려면 애플리케이션 컨텍스트에서 무슨 일이 일어나야 하는 걸까요? 참 신기합니다. 나는 다른 설정을 하지 않았는데도 스프링이 자동으로 위임해 주었습니다. 그렇다면 무슨 일이 일어난 걸까요?

_참고 단어_
- `cglib`
- `proxy`
- `enhancer`

우선 이걸 공부하고 다시 얘기 나눠봐요.

3. 네 좋아요. 예쁘네요 ㅋㅋ

2021-03-16 08:46 UTC, wheejuni commented
아 4번도 있군요...

2021-03-16 08:46 UTC, wheejuni commented
4. 엔티티 클래스에 대해 바로 밸리데이션을 수행하실 거라면 그렇게 하셔도 무방합니다.

2021-03-16 09:39 UTC, janeljs commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElseThrow(RuntimeException::new);
드립인 줄 몰랐습니다ㅋㅋㅋㅋㅋ🥺😂

2021-03-17 01:32 UTC, janeljs commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +
해당 부분에 대해서 오늘 더 공부해볼게요!! 더 진도를 나가기보다는 기초를 좀 다지고 가야겠네요ㅎㅎ

2021-03-17 01:47 UTC, janeljs commented
@wheejuni 질문이 많았는데 답변 감사합니다!ㅎㅎ
+) 1번 질문에 대해서는 제가 착각했었나봐요ㅠㅠ 분명 저번에는 private으로 잘 돌아갔었던 것 같은데 private으로 고치려고 하니 "Class 'Answer' should have [public, protected] no-arg constructor"라는 메시지가 뜨네요. 관련 내용을 찾아봤더니 JPA 공식문서에 "The entity class must have a no-arg constructor. It may have other constructors as well. The no-arg constructor must be public or protected."라고 나와있어 protected 또는 public으로 생성해야 하는 것 같습니다. 잘못된 정보를 알려드려 죄송합니다 ㅠㅠ

2021-03-17 14:47 UTC, janeljs commented
@wheejuni 에러를 해결하기가 힘들어서 커밋을 되돌리고, push된 커밋을 취소하는 과정에서 force push를 하게 되었습니다ㅠㅠ 앞으로 push는 더욱더 신중히 해야겠다는 생각이 듭니다...
이외에 최대한 컨트롤러의 로직을 서비스로 이동하는 방식으로 리팩토링 하였습니다! 확인하시고 이상이 없다면 approve 부탁드립니다🙌

2021-03-17 14:57 UTC, wheejuni commented
@janeljs force push도 적절히 활용하면 괜찮지만, 학습 단계에선 커밋 트리를 최대한 살리는 쪽으로 진행해보면 좋겠습니다. ㅎㅎ
그래도 불가피한 이슈 해결을 위해선 적절히 사용하셔도 됩니다.

2021-03-17 14:58 UTC, wheejuni approved these changes
👍

2021-03-17 14:58 UTC, merged