[Tree]미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #71
Opened 2021-03-15 08:18 UTC by choitree

안녕하세요 tree입니다.
이번에도 역시나 제가 꼴찌네요 하하하하
스프링에 대한 개념이 전혀 없고, 수업에도 무슨 소리인지 이해가 안되서 강의를 먼저 들어보고 시작하느라 많이 지연되었습니다.
처음에 진행하다가, 코드에 문제가 있는데 어디에 문제가 있는지 파악하기가 어려워 밀고서 새로 시작했습니다.
미션1 내용에 있는 부분만 수정하였는데, 혹시 문제가 더 있을지도 모르겠네요ㅠㅠ
그래도 밀고 다시 해보니까 처음에 했을때보다는 조금 더 이해한 것 같아서 나름 재미있었습니다(한 10퍼센트 더 이해한 것 같습니닿ㅎㅎ)

자바지기님, 김영한님 강의와 루카스에 있는 힌트를 짬뽕으로 진행하다 보니
아직 사용하지 않는 h2 관련된 내용도 application.properties 내 포함되어 있습니다.
h2로 db에 저장되도록 작성했으나, 미션2에 반영하는 것이 좋을 것 같아서 레파지토리 인터페이스는 삭제하였습니다.

2021-03-15 11:27 UTC, ksundong commented
커밋메시지는 왜 한 뭉텅이가 되어있을까요 ㅠㅠ
커밋은 작은 단위로 구분되어야 하고, 커밋을 하는 팁은 '이 커밋이 되돌려 졌을 때'를 생각해보시면 어느 선에서 커밋을 해야하는지 감이 오실겁니다.
또, 한 번 개발해보시고 지우신 다음 다시 개발을 해보시는 것도 방법이구요.
요구사항을 정리하시고, 요구사항 만큼만 개발하시는 것도 추천합니다.(저는 실무에서 이렇게 일하고 있습니다!)

2021-03-15 12:01 UTC, ksundong requested changes
안녕하세요. Tree! 리뷰어 Dion입니다.
가급적이면 미션 내용대로만 진행해보시고, 추후에 부족한 부분을 채우길 권장드립니다.
물론 선택은 자유입니다. 요구사항에 집중하면 여러 생각을 할 수 있기 때문에 저는 이 방법을 추천드려봅니다.

재미있는 스프링 웹 애플리케이션 만들기에 오신것을 축하드리고, 재미있게 진행해보시면 좋을 것 같습니다.
먼저 이번 미션은 프로젝트를 시작하는 시점이다보니 여러가지 리뷰드릴 것이 많은 것 같네요.

## 애플리케이션 관련 리뷰

- 게시글 목록, 게시글에서 시간이 출력되지 않네요. 확인해보니 클래스에 해당 필드가 없군요.
- 회원 목록 출력시 '#'이 모두 0인데, 의도된 동작인지 궁금해요.
- 요구사항을 지켜주세요~
  - 비밀번호, 이름, 이메일만 수정할 수 있으며, 사용자 아이디는 수정할 수 없다.
  - 비밀번호가 일치하는 경우에만 수정 가능하다.

## 코드 관련 리뷰

- 현재 사용하지 않는 의존성은 제거해주세요!
- 여러 사용자가 동시에 접근하는 경우도 항상 고려해주세요!
- 이제는 `System.out.println`을 사용하기 보다는 `Logger`를 사용해주세요.
- 코드 포맷팅 잊지 말아주세요.
- 조금 더 로직의 순서에 대해서 고민해봐주세요.
- RESTful한 Url을 설계한다는 것이 어떤건지 한 번 시간나실 때 학습해주세요.

궁금한 점이나, 도움이 필요한 점, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으면 언제든지 코멘트 남겨주세요.
고생하셨습니다! 수정 후에 다시 리뷰요청해주세요~

2021-03-15 12:01 UTC, ksundong commented on README.md
> +* https://treeqna.herokuapp.com/
```suggestion
## 배포 url

* https://treeqna.herokuapp.com/
```

일반적인 마크다운 문법 규칙에 따르면 제목과 그 다음 줄 사이는 띄워주는 것이 맞습니다.~

2021-03-15 12:01 UTC, ksundong commented on build.gradle
> +	implementation 'org.webjars:jquery:3.1.0'
이 의존성도 필요한 건가요? 왜 추가되었나요?

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfiguration.java
> +    }
각 설정이 어떤 역할을 하는지 간단하게 정리해두고 넘어가봅시다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    private List<Question> questions = new ArrayList<>();
만약에, 여러 사용자가 QnaController를 이용한다면, 어떤 문제가 발생하게 될까요?
힌트는 동기화입니다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        System.out.println("question.getQuestionId() = " + question.getQuestionId());
이번 미션부터는 `System.out.println()`은 봉인하시고, `Logger`를 사용해봅시다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        question.setQuestionId(questions.size());
Id를 나중에 설정해주셨네요. 나쁘지 않은 것 같습니다 ㅎㅎ

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
저라면, HomeController를 두고, 들어오는 요청을 Question의 목록을 출력하는 곳으로 redirect를 시켜줄 것 같아요.
왜냐하면, 현재의 행동은 Home을 불러오는 역할이 아니기 때문이에요.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        Question question = questions.get(questionId -1);
```suggestion
        Question question = questions.get(questionId - 1);
```

항상 커밋 전 포매팅을 해주시고, 자꾸 까먹게 되시면, IntelliJ에 커밋 시 reformat을 자동으로 해주는 옵션을 켜줍시다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        model.addAttribute("question",question);
```suggestion
        model.addAttribute("question", question);
```

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```

으로도 변경할 수 있다는 점! 알아주세요!

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            return "redirect:/user/form";
순서가 조금 이상하지 않나요?
`null`을 `users`에 추가한 후에 이동하면 뭔가 잘못된거 아닐까요?

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
```suggestion
        }
        return "redirect:/users";
```

early return을 해주면, 굳이 else문이 필요없어집니다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "/user/profile";
굳이 tempUser를 선언하지 않고, 조회 즉시 바로 return하는 방법도 있을 것 같네요.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/update/{userId}")
만약 GET 과 POST 만 써야한다면, 저라면

`/users/{userId}/update` 를 사용할 것 같아요.
url은 최상위 요소가 앞에 나온답니다~

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int questionId;
이미 클래스에 question이라는 단어가 있기 때문에 `id`여도 충분합니다.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
나중에 이 `writer`는 `User`가 되겠네요.

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
`toString`을 정의해 주신 이유는 무엇인가요?

2021-03-15 12:01 UTC, ksundong commented on build.gradle
> +	implementation 'org.webjars:jquery:3.1.0'
벌써 jpa 의존성이 들어오진 않아도 될 것 같은데요~

2021-03-15 12:01 UTC, ksundong commented on src/main/resources/application.properties
> +spring.datasource.password=
현재 시점에선 필요하지 않은 설정이네요.

2021-03-15 12:01 UTC, ksundong commented on src/main/resources/templates/user/list.html
> +                    <th>#</th> <th>사용자 아이디</th> <th>이름</th> <th>이메일</th><th></th>
가급적이면 각각 줄바꿈해주시면 좋을 것 같아요~

2021-03-15 12:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +
날짜 시간 정보가 들어있지 않네요 👀

2021-03-16 05:50 UTC, choitree commented on README.md
> +* https://treeqna.herokuapp.com/
넵넵!!

2021-03-16 05:52 UTC, choitree commented on build.gradle
> +	implementation 'org.webjars:jquery:3.1.0'
이거는 추가하고, html 경로를 변경하고 static 패키지안에 파일을 삭제하려고 하다가, 후처리를 못했습니다ㅠㅠ
아마 뒤에 추가하는 과정이 있는 것 같으니 우선은 의존성을 삭제하도록 하겠습니다!

2021-03-16 05:56 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        System.out.println("question.getQuestionId() = " + question.getQuestionId());
네네! 그런데 로거를 사용하려면 각 클래스별로 로거를 정의하는 것이 맞나요?
우선 아래 내용을 추가해서 logger.info로 찍었습니다 
 private static final Logger logger = LoggerFactory.getLogger(QnaController.class);

2021-03-16 08:50 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
HomeController를 추가해서 리다이렉션을 해줬는데, 있는것과 없는 것에 차이를 잘 모르겠네요ㅠㅠ 없어도 똑같이 작동하는거같아보여서요...

데이터를 리스트에 관리하다보니, QnaController에서 index로 넘겨주는 방식으로 작성했는데, h2로 데이터 관리를 하게되면 변경해보도록 하겠습니다!

2021-03-16 12:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        System.out.println("question.getQuestionId() = " + question.getQuestionId());
넵 각 클래스 별로 정의해주시는 것이 일반적입니다.

2021-03-16 12:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
redirect와 직접 접근, forward의 차이에 대해서 한 번 알아보세요.
이 점은 꼭 알아야 합니다 ㅎㅎ

2021-03-17 02:22 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/update/{userId}")
그게 더 가독성이 좋은거같네요!!

2021-03-17 02:26 UTC, choitree commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private int questionId;
User에 id와 헷갈릴까봐 그렇게 작성했는데, 어차피 클래스로 구분되는군요~~

2021-03-17 02:26 UTC, choitree commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
제대로 값이 들어가는지 찍어보고 싶어서 재정의했습니다

2021-03-17 02:37 UTC, choitree commented on src/main/java/com/codessquad/qna/domain/Question.java
> +
수정했습니다~~ 아예 기능 넣는것을 안했었어요ㅠㅠ

2021-03-17 02:41 UTC, choitree commented on src/main/resources/templates/user/list.html
> +                    <th>#</th> <th>사용자 아이디</th> <th>이름</th> <th>이메일</th><th></th>
네네!!

2021-03-17 02:42 UTC, choitree commented on src/main/resources/application.properties
> +spring.datasource.password=
레파지토리를 삭제하고 여기는 미련이 남아서 못지웠는데ㅠㅠ(설정하는데 애를 먹었어가지구요😅) 미련없이 지웠습니다!~~

2021-03-17 02:43 UTC, choitree commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writer;
네네 현재는 로그인이 되지 않아서 로그인 구현 후 같은 값이 되도록 구현해보겠습니다~~

2021-03-17 02:44 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "/user/profile";
User객체를 만들어서 사용하면, 가독성 측면에서 더 좋을 것 같아서 사용했는데 선언하지 않고 사용하는 것은 메모리 측면에서 도움이 되는 부분이겠죠??

2021-03-17 02:45 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
가끔 early return해줄 때 원하는대로 안나와서 잘 안 사용하게 되었는데 else문을 지양하도록 습관들여보겠습니다!~~

2021-03-17 02:47 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            return "redirect:/user/form";
그러네요 널여부 먼저 확인하고 아닐 때, add해야 되었네요😶

2021-03-17 02:49 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
제가 궁금한거는 homecontroller가 굳이 있어야하는 이유였는데, 접근할 때 기본 페이지 로딩할 때 읽어줘야하는 부분때문에 필요한 코드였더라구요(맞죠...?)
리다이렉션의 유무가 궁금한 것은 아니였는데, 디온 리뷰 보고 복습했습니다~~

2021-03-17 03:08 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    private List<Question> questions = new ArrayList<>();
다른 사용자에 의해 의도하지 않은 값이 도출될 수 있어요
엄...어떤 이슈를 말씀하시는지는 알겠는데 말로 설명이 잘 안되네요ㅠㅠ
멀티쓰레드의 동기화때문에 synchronizedList 사용이 필요하다고 말씀하시는거죠?~~

2021-03-17 05:55 UTC, choitree commented on src/main/java/com/codessquad/qna/config/MvcConfiguration.java
> +    }
setOrder은 핸들러 매핑의 순서를 정해주는 것이고, HIGHEST_PRECEDENCE는 그 순서를 제일 먼저로 정해주는 것입니다.

        registry.addViewController("/questions/form").setViewName("qna/form");는
간단한 Get 요청의 뷰만 리턴해주는 내용으로 
@GetMapping("/questions/form")
public String showQuestionForm() {
	return "/qna/form";
}
와 같은 내용의 코드로 중복이 보여서 아래 QnaController 코드는 삭제하였습니다.
제가 이해한 바로 풀어봤는데 혹시 잘못되었다면 알려주세요🙄

2021-03-17 06:05 UTC, choitree commented
리뷰해주신 부분 반영했습니다 디온은 빨리 리뷰해주셨는데, 지연되서 죄송합니다ㅠㅠ
항상 꼼꼼하고 친절한 리뷰 너무 감사드립니다👍
커밋은 말씀해주신 것처럼 다시 한단계씩 해보려고 했는데, 그러면 너무 지연될 것 같아서 한번에 몰아서 했습니다 죄송합니다ㅠㅠㅠㅠ
GET POST이외에도 사용하려고 했는데, 우선은 1단계에서 할 수 있는 수준으로 구현해봤습니다.
거의 강의를 따라하면서 조금씩 이해하는 수준이라서 많이 부족하지만, 리뷰해주신 내용을 토대로 공부할 키워드를 더 알게되서 머리속에 물음표가 조금은 지워진 것 같네요 :>

2021-03-17 13:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/MvcConfiguration.java
> +    }
공부 열심히 하셨네요!! 👍

2021-03-17 13:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    private List<Question> questions = new ArrayList<>();
네 동기화를 해주지 않는 것이기 때문에 여러 곳에서 하나를 접근하는 경우엔 주의가 필요합니다.

2021-03-17 13:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
HomeController를 두도록 설계한 이유는 명확하게 책임을 분리하기 위해서라고 생각하시면 좋을 것 같아요.
우리가 개발을 하다보면 메인 페이지는 언제든 경로가 바뀔 수 있지만
질문 목록을 출력하는 페이지는 그대로 질문 목록만 출력하게 될겁니다.

이를 생각하고 분리해 주는게 어떤지 의견을 드렸던 거였어요!

2021-03-17 13:59 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        return "/user/profile";
음 메모리 문제가 아니라 굳이 변수 선언이 필요없기 때문입니다.
메모리는 신경 안쓰셔도 돼요. 정말 미미한 차이입니다. 😊

2021-03-17 14:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
아직은 문제가 되진 않지만, 추후에 문제가 되는 상황을 한 번 경험해보실 수 있으면 좋겠네요!
항상 조심하셔야합니다. ㅎㅎ

2021-03-17 14:07 UTC, ksundong approved these changes
Tree! 이번 과제를 피드백 받느라 고생하셨습니다.
원래라면 한 번 더 변경 요청을 드렸겠지만!
다음 미션을 바로 진행하시는 것이 좋을 것 같아서 변경은 다음 미션에서 해주시면 되겠습니다!

고생하셨습니다~

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        question.setWriteTime(new SimpleDateFormat(("yyyy-MM-dd HH:mm")).format(new Date()));
`Date`, `Calendar`는 이제 사용하지 않는 API입니다.
Java8에 추가된 날짜/ 시간 API를 사용해주세요.
그리고, 이런 set하는 코드를 사용하시기보다는 생성자를 이용해 값을 할당해주는 편이 낫겠습니다!

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +        logger.info("question.getQuestionId() = " + question.getId());
```suggestion
        logger.info("question.getQuestionId() = {}", question);
```

logger를 사용할 때에는 문자열 + 연산은 지양해줍시다!

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    Logger logger = LoggerFactory.getLogger(UserController.class);
여기는 접근제어자가 누락되었네요!

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if(user.getUserId().equals(userId)) {
```suggestion
            if (user.getUserId().equals(userId)) {
```

가급적이면 user 객체에서 비교를 할 수 있도록 해봅시다~

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private String writeTime;
날짜를 String으로 저장하면 어떤 점에서 불리할까요?
한 번 생각해보시고, 시간 형태로 값을 저장해보세요!

2021-03-17 14:07 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    private long id;
아직은 굳이 id가 필요없지만 그냥 넘어가도록 합시다. 😊

2021-03-18 06:57 UTC, choitree commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
어제 조별 리뷰하면서 파이로가 해당 내용에 대해서 설명해줬어요~~ 
제가 한 방식으로만 메인페이지를 로드하면, 만약 메인페이지를 개편하면 여러 코드를 손봐야하지만
HomeController를 두면 리턴해주는 내용만 메인페이지 내용에 해당하게 변경하면 된다고요~~
그래서 index에 리스트를 뿌리는 것보다는 qna/list.html 이 별도로 존재하는 것도 좋을 수 있다고 
어거스트가 조언해줬습니다!!

여러 분들의 리뷰와 조언을 들으니 애매하게 이해한 내용이 조금 더 와닿는 것 같네요☺️

2021-03-18 12:09 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QnaController.java
> +    public String loadHome(Model model) {
좋은 학습을 하셨네요! 😊

2021-03-18 15:07 UTC, merged