[bibi] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #72
Opened 2021-03-15 09:06 UTC by bibi6666667

안녕하세요, 백엔드반의 bibi입니다.
이보다 더 늦을 순 없는 미션1 PR, 이제 올립니다😅

<변명 및 해명 고해성사>
- 프로젝트를 여러 번 뒤엎고 다시 하고.. 를 반복해서 커밋이 엉망진창입니다...
- 미션1완성은 저번주 금요일쯤 끝났는데, Heroku배포에서 헤메느라 미션1 PR이 늦어졌습니다...
- Heroku배포는 못 했지만 '주말에 미션2 조금 진행해 보자!'며 H2 데이터베이스 연결을 시도했으나 잘 안 되었는데요.
- 분명 step2브랜치를 만들어 진행했(다고 생각하)는데 변경내역이 step1브랜치에 섞여버려 같이 올리게 되었습니다....😭

<미션1에서 배운 점>
- 스프링, 스프링 부트에 대한 기초 개념(+인프런 인강의 도움)
- 스프링 앱과 DB 연결하기 (H2 사용)
- 스프링 부트로 기초 웹 사이트 만드는 법 (GET, POST 방식으로 클라이언트-서버 간 데이터 주고받기)

<미션1에서 노력한 점>
- 주어진 요구사항을 빠짐없이 만족시키기
- 다른 앞서나가는 분들의 코드를 보고, 코드리뷰를 받으며 내 코드 개선하기
- 스프링 웹 개발에 대한 넓고 얕은 지식 학습하기

<미션1에서 부족한 점>
- 학습에 치중하느라 미션 진도 및 '따라하기'에 중점을 두지 못한 것 같아 반성 중입니다. 

많이 늦었고 또 부족한 코드지만 피드백 꼼꼼히 읽어보고 공부하겠습니다!
많은 코멘트, 피드백 부탁드립니다🙇‍♀️

2021-03-15 14:34 UTC, ksundong requested changes
안녕하세요. BiBi! 리뷰어 Dion입니다!
첫 미션 PR을 올리신 것을 축하드립니다. 이번 미션을 재미있게 진행해보도록 합시다!

일단 되도록이면 커밋을 엉망진창으로 만들지 않도록 노력을 기울여봅시다.
그리고, 필요없는 커밋은 해당 커밋으로 이동하는 `reset`을 활용해서 없애봅시다.

1. 요구사항을 빠짐없이 만족하기 위해서는 To-Do를 만들어두는 편이 유리합니다. 다음에는 한 번 만들어서 진행해보세요.
2. 다른 분들의 코드 리뷰를 보면서 개선하는 것도 좋지만, 본인이 짠 코드를 리뷰 받는 것이 훨씬 중요합니다. 가급적이면 PR을 제출하고 다른 분들의 리뷰를 참고해주세요.
3. 이번 프로젝트는 2주 짜리 프로젝트입니다. 현재 벌써 2주차인데요, 되도록 3단계 까지는 하실 수 있으셨음 좋겠네요. 개발자에게 중요한 역량 중 하나가 정해진 기한을 어떻게 하면 효과적으로 맞출 수 있는지 설정하는 것도 있기 때문에 최대한 지키려고 해보셨음 좋겠어요.
4. 피드백을 받고 수정하는게, 그냥 학습하는 것보다 더 효과적으로 빠르게 배울 수 있다고 생각합니다. ㅎㅎ

사실 이미 깨닫거나 반성하신 내용을 다시 한 번 찝어드리는 느낌이 있지만, 현재 시점에서 미션1은 많이 늦은 경향이 있습니다.
그래도 빠르게 달려가봅시다.

## 애플리케이션 관련 리뷰

- 회원 목록에서 순번은 제거해주신 이유가 있나요?
- 회원 정보 수정시 비밀번호가 채워져있으면 안되지 않을까요?
- 비밀번호 검증절차라는 요구사항이 충족되지 않았네요.
- 게시글 목록, 조회시 날짜가 정상적으로 표기되지 않네요.

## 코드 관련 리뷰

- 중복제거에 신경을 써주세요.
- url 설계를 할 때 RESTful API url 설계 관련 자료들을 검색해서 참고해주세요!
- 일관성 있게 url 설계를 해주세요. `user`, `users`
- 네이밍은 어렵지만 의미하는 바를 정확히 전달하도록 네이밍 해봅시다.
- temp라는 접두어는 임시로 사용될 경우에만 사용해주세요.

조금 생각해보셨으면 하는 부분과 일부 요구사항이 충족되지 않아 변경 요청 드립니다.
궁금한 점, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론이 필요한 부분은 언제든 코멘트 남겨주세요!
고생하셨습니다~

2021-03-15 14:34 UTC, ksundong commented on README.md
> -* [Gradle Build Scans – insights for your project's build](https://scans.gradle.com#gradle)
이 내용은 지워주신 이유가 따로 있나요?

2021-03-15 14:34 UTC, ksundong commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
미션2에서 필요한 의존성이 벌써 들어왔네요.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        List<Question> questions = QuestionController.getQuestions();
웹의 기능을 활용해봅시다. 이렇게 가져오지 말구요 ㅎㅎ
`redirect`를 이용해봅시다.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static List<Question> questions = new ArrayList<>();
- 왜 static으로 만들어주셨나요?
- 여러 사용자에게서 요청이 동시에 들어올 때, ArrayList는 어떻게 동작하게 될까요?

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @GetMapping("/questions")
중복되는 url은 클래스에 `@RequestMapping`을 사용해서 제거해줍시다!

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String goToCreateQuestion() {
url이 의미하는 바는 question의 목록을 가져와라인데, 행동은 question을 만드는 form을 만들어주네요.
무엇이 잘못되었을까요?

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private UserRepository userRepository;
앗 이게 들어오면 안되는 시점인데 들어와있네요.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/user/create")
어디는 `user`고 어디는 `users`죠?
`users`로 맞춰줍시다.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/user/create")
그리고 `url`에 동사는 최대한 지양해주세요.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/user/create")
`POST` 가 의미하는 것이 이미 `create`입니다.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String showUser(Model model) {
메서드명이 의미하는 바가 실제 메서드가 수행하는 행동과 다르네요~

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +                break;
```suggestion
                return "profile";
```

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String showUser(Model model) {
`showUser`는 유저를 보여준다! 겠죠?

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/users/{userId}/updateForm")
보통 url은 kebab case로 작성하는데 일단 넘어갑시다~

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.getUserId().equals(userId)) {
어디는 `isSameId`를 사용하고 어디는 `equals()`를 사용했네요.

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.isSameId(userId)) {
좋네요!

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/user/{user.userId}/update")
```suggestion
    @PostMapping("/user/{userId}/update")
```

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User temp : users) {
```suggestion
        for (User user : users) {
```

아무렇게나 temp라는 단어를 남용하지 맙시다!

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/Question.java
> +    private String contents;
시간 정보를 따로 저장을 하지 않네요?

2021-03-15 14:34 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
`CrudRepository`가 2단계의 요구사항인데 어떤 차이가 있는지 학습해보세요!

2021-03-16 02:14 UTC, bibi6666667 commented on README.md
> -* [Gradle Build Scans – insights for your project's build](https://scans.gradle.com#gradle)
적혀 있던 내용을 확인했고 도움이 됐지만, 제 프로젝트에 대한 README 설명이 아니기 때문에 지웠습니다. 지우지 않는 게 더 좋은 건가요? 🤔

2021-03-16 02:15 UTC, bibi6666667 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
넵ㅠㅠ 삭제하겠습니다!

2021-03-16 02:23 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    private UserRepository userRepository;
네! 이 부분도 삭제하겠습니다.

2021-03-16 05:43 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        List<Question> questions = QuestionController.getQuestions();
네! 다시 만들어 보겠습니다.

2021-03-16 05:51 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static List<Question> questions = new ArrayList<>();
위에서 피드백 주신 HomeController에서 questions를 List로 받아오는 부분을 만드느라 static으로 선언했었습니다 (`List<Question> questions = QuestionController.getQuestions();`)
이제 HomeController를 개선했으니 해당 부분도 수정하겠습니다!
`여러 사용자에게서 요청이 동시에 들어올 때` 이 부분은 생각 못 해 봤는데.. ArrayList가 쓰레드에 안전하지 않고(?), 그래서 문제인가요? 아니면 ArrayList 길이를 매번 늘이고 줄이느라 성능이 낮아지는 게 문제인가요? 🤔... 한번 찾아서 공부해 보겠습니다!🙇‍♀️

2021-03-16 08:23 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/repository/Question.java
> +    private String contents;
시간 표시하는 기능 구현을 놓쳤습니다. 구현해 보겠습니다!

2021-03-16 08:24 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +            if (user.getUserId().equals(userId)) {
앗 놓쳤네요ㅠㅠ 수정하겠습니다. 감사합니다!

2021-03-16 08:30 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User temp : users) {
해당 반복문에만 사용되는 임시변수명이라 일부러 temp로 지었습니다. 이전에 간소화된 for반복문에 temp를 임시변수로 사용하는 걸 많이 봤었는데 이게 잘못된 사용법인 건가요? 🤔

2021-03-16 12:41 UTC, ksundong commented on README.md
> -* [Gradle Build Scans – insights for your project's build](https://scans.gradle.com#gradle)
그냥 궁금해서 여쭤봤어요 ㅎㅎ

2021-03-16 12:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static List<Question> questions = new ArrayList<>();
'동시에~ 여러~' 가 등장하면 동시성 문제라고 생각하시면 될 것 같아요.
단순한 `ArrayList`는 동시성 문제에서 안전하지 못한 자료구조입니다!

2021-03-16 12:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User temp : users) {
해당 반복문에만 사용된다 하더라도, `temp`라는 단어가 적절하지는 않습니다.
임시로 데이터를 저장한다거나 하는 경우에만 제한적으로 `temp`를 써주도록 하는 편이 좋은 네이밍을 하는데 도움이 됩니다.

2021-03-16 13:39 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private static List<Question> questions = new ArrayList<>();
그렇군요! 해당 키워드로 찾아서 공부해보겠습니다. 감사합니다😀

2021-03-16 13:42 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User temp : users) {
그렇군요! 해당 부분 수정하고, 앞으로 `temp`는 최대한 덜 사용하겠습니다. 감사합니다🙇‍♀️!!

2021-03-16 13:43 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
넵 안그래도 인프런 강의랑 이 부분이 다르더라고요! 학습해보겠습니다😀

2021-03-16 13:45 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @GetMapping("/questions")
네! 사용해서 중복 제거해 보겠습니다😀

2021-03-16 13:48 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String goToCreateQuestion() {
이 부분 설계를 완전히 잘못 했었습니다😭 `index.html`에 질문목록을 웹으로 받아 표시하지 못한 것과 연관되더라고요. 그룹원분들의 도움을 받아 이 메서드는 `index`를 리턴하도록 하고, HomeController도 함께 수정해 해결했습니다!😀

2021-03-16 13:49 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/user/create")
넵 URL 설계를 전체적으로 다시 해 보겠습니다!

2021-03-16 13:50 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String showUser(Model model) {
네 메서드명도 전체적으로 수정해 보겠습니다!!

2021-03-16 14:00 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/users/{userId}/updateForm")
그렇군요! 그래도 공부해서 적용해 보겠습니다!

2021-03-16 14:05 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +                break;
어.. 제안대로 수정해봤는데, 반복문 밖에도 return선언을 해야 하게 되네요. 이렇게 되면 맞는 아이디가 없을 때 리턴할 페이지를 만들어야 하나요?🤔 아니면 다른 방법이 있을까요?

2021-03-16 14:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +                break;
앗 그러네요. 일단은 그대로 두시는게 좋을 것 같아요.
아직 해당 리소스가 없을 때 예외 처리하는 건 너무 큰 요구사항 일 것 같다는 생각이 드네요.

2021-03-17 08:51 UTC, bibi6666667 commented
안녕하세요, Bibi입니다😀
미션1 피드백 사항을 수정해 다시 요청 드립니다.

### 수정내역
놓친 요구사항
- 회원목록 순번
- 회원정보 수정 - 비밀번호 검증
- 질문에 날짜 표시
- 미션2 내용 삭제
개선사항
- URL설계 : REST API, kebab case 공부해 일관성 있게 만들기
  - README.md에 URL convention 추가
- 메서드명 수정 : 메서드명이 메서드의 동작을 반영하도록 
  - 좋은 네이밍에 대한 감이 부족하네요😅 나름 노력은 해 보았습니다..!
- 중복URL 제거 : `@RequestMapping` 사용

혼자 작업하며 남긴 커밋과 피드백하며 남긴 커밋이 비슷한 걸 보면서, 이번 미션 피드백에서 정말 많은 걸 배웠다고 느꼈습니다. 꼼꼼한 피드백 감사합니다👍 혹시 제가 놓친 피드백이나 잘못한 고친 부분이 있으면 조언 부탁드리겠습니다!

마지막으로 좋은 저녁 되세요😊

2021-03-17 14:26 UTC, ksundong approved these changes
BiBi! 피드백 반영하시느라 고생하셨습니다!
원래라면 변경요청을 드렸겠지만, 코멘트를 남겨드리니 다음 단계 미션을 진행하시기 전에 반영해주세요.
다음 단계 미션 바로 진행해주시면 되겠습니다.
고생하셨어요!

2021-03-17 14:26 UTC, ksundong commented on README.md
> +▶ [Heroku 배포 URL](https://damp-lowlands-18176.herokuapp.com/)
문서화 잘 하셨어요! 💯

2021-03-17 14:26 UTC, ksundong commented on README.md
> +▶ [Heroku 배포 URL](https://damp-lowlands-18176.herokuapp.com/)
너무 상세하게 세부 구현은 적지 않아도 된답니다~

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String redirectQuestions() {
메서드에는 메서드 내부 동작을 드러내기 보다는 메서드가 수행할 행동을 적어주세요.
간단하게 home으로 갈것이니 `home()`정도여도 충분합니다.

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public String showQuestions(Model model) {
👍

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @GetMapping("/new")
new는 뭔가 새롭네요 ㅎㅎ

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @PostMapping("/new")
앗 여기에는 `new`가 없어도 될 것 같아요.

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
매 요청마다 생성이 될 것 같은데, 상수로 빼는 것이 낫지 않을까요?

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setDateTime(formatTime);
객체 생성 시점에 시간이 생성되도록 하는 방법이 있지 않을까요~

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setIndex(questions.size() + 1);
list인데 index를 이중으로 관리하는 것 같지 않나요?

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +
빈라인이 너무 많네요~

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/user")
보통은 `users`를 많이 사용합니다~

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
어떤 페이지로 가는지 궁금해지네요 👀

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        String inputPw = user.getPassword();
굳이 뽑아줄 필요가 있을까요~?

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User aUser : users) {
`aUser`는 a user인가요?

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        String inputPw = user.getPassword();
그리고 줄여쓰기는 지양합시다!

2021-03-17 14:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
이 로직은 개선이 필요한 것 같아요.
단순히 값을 변경하는데 remove하고, id를 set하는 과정이 들어가면 안될 것 같은데요?

2021-03-17 14:38 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String redirectQuestions() {
아 그렇군요! 메서드명은 동사로 하는 게 좋다는 말을 들어서 이렇게 했는데, `동사`에 집착하기보다는 메서드의 행동을 나타내는 것에 더 중점을 두면 되나요?😮

2021-03-17 14:44 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @PostMapping("/new")
넵 이 부분 URL 수정하겠습니다!

2021-03-17 14:56 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
비밀번호 검증 절차를 위한 html파일을 하나 만들고 `passwordCheck`라고 이름을 지었습니다. 파일 네이밍이 좀.. 그런가요?🤔 `passwordCheckForm` 이 더 나을까요?😅

2021-03-17 14:58 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User aUser : users) {
네! 이런 임시변수명도 바람직하지 않나요?😅

2021-03-17 15:00 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
네! 해당 메서드 로직 개선해 보겠습니다👍

2021-03-17 15:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +    public String redirectQuestions() {
네 동사 보다는 메서드가 어떤 일을 해줄 것인가가 더 중요하답니다!

2021-03-17 15:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    }
네 저는 후자가 더 나은 것 같아요~

2021-03-17 15:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User aUser : users) {
관사는 붙이지 않는게 일반적이어서요~
인자로 받는 `user`를 바꿔주는건 어떨까 싶네요~

2021-03-17 15:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User aUser : users) {
`targetUser`? 대충 생각해낸 이름이에요.

2021-03-18 09:01 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        for (User aUser : users) {
그걸로 바꿔볼게요! 감사합니다😀

2021-03-18 11:49 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setDateTime(formatTime);
`Date`객체를 사용하도록 수정하겠습니다!
질문이 있는데, `Date`를 쓰면 따로 import를 해야 하지만 `System.currentTimeMillies()`는 import할 필요가 없어서 저는 이걸 선택했었는데요 (날짜출력 메서드가 이미 있는데 굳이 `import java.util.Date`를 하는 게 더 안좋을거라는 짐작 때문이었습니다)
시간을 메서드로 받아오는 것보다 객체 생성 시점에 시간을 생성하는 게 더 좋은 건가요?🤔

2021-03-18 11:55 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setIndex(questions.size() + 1);
어.. 제가 코멘트를 잘 이해를 못 한 것 같아서 질문드립니다!
index를 이중으로 관리하고 있다는 말씀이, `question`클래스에 index 인스턴스변수를 따로 선언 및 사용하기보다 `questions` ArrayList의 인덱스를 활용하라는 뜻인가요?😮

2021-03-18 13:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setDateTime(formatTime);
일단은 `Java8` 이전의 날짜/시간 API인 `Date`, `Calendar`는 사용하지 마시구요!
`Java8`에서 추가된 날짜/시간 API를 사용해주시면 되겠습니다. 일단 `LocalDateTime`의 사용을 추천드릴게요.

질문에 대한 답변입니다.

`import`를 한다는 것은 그 코드가 필요해서 가져다 쓴다는 의미입니다. `import`를 한다고, 그것이 잘못된 행동이 아닙니다.
간단히 정리해드리자면, 더 전문적인 친구에게 일을 맡기는 것입니다. 우리가 날짜를 하루 뒤로 조작한다고 가정해볼게요.
`import`를 해준 전문적인 친구는 날짜를 조작하는 메서드를 제공하기 때문에 편하게 이용할 수 있습니다.
하지만 우리가 `import`를 하지않고 직접 사용했다면, 두 가지 문제가 발생합니다. 코드가 더러워지고, 오류가 발생할 수 있습니다.

제가 생각하기에 뒤의 질문은 어떻게 하는가를 정하는건 개발자의 몫인데요. 저의 경우에는 객체 생성시점을 넣어주는 것을 선호하는 편입니다.

2021-03-18 13:04 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setIndex(questions.size() + 1);
네 잘 이해하셨네요!

2021-03-18 13:06 UTC, ksundong reviewed
간단하게 리뷰 더 해보았습니다!
코멘트 된 내용들 다음 미션 진행하시기 전에 전부 다시 한 번 확인해주시고 꼭꼭 반영해주세요!

2021-03-18 13:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/new")
`new`는 아직 안사라졌네요. 😭

2021-03-18 13:06 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +                String pwBefore = user.getPassword();
줄여쓰기는 지양해줍시다~

2021-03-18 13:21 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setDateTime(formatTime);
그렇군요! `LocalDateTime`을 사용하도록 수정하겠습니다. `import`관련해 자세하게 답변 주셔서 감사합니다🙇‍♀️🙇‍♀️!!

2021-03-18 13:43 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setIndex(questions.size() + 1);
앗 다시 자세히 봤는데, 미션1 질문 상세보기 힌트 - '질문 객체를 추가할 때 `ArrayList.size() + 1`을 질문객체의 id로 사용하라'는 부분인데 제가 괜히 인스턴스변수 이름을 `index`로 해서 생긴 문제 같네요..😭😭 변수명을 고쳐서 해결하겠습니다😥

2021-03-18 14:29 UTC, bibi6666667 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @GetMapping("/new")
아이고.. 제가 수정했다고 착각하고 있었네요😭😭  수정하겠습니다!!

2021-03-18 15:07 UTC, merged