[프레디]미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #75
Opened 2021-03-15 17:31 UTC by Dae-Hwa

안녕하세요 프레디입니다! 미션3 완료했습니다.
[배포 사이트](https://spring-boot-qna-freddie.herokuapp.com/)

생각보다 구현이 잘 되는 것 같아서 선택 미션까지 함께 진행했는데, 욕심이 과했던 것인지 시간도 오래걸리고 갑자기 프로그램이 커졌습니다. 완성시키고 나니 pr단위가 너무 큰 것이 아닌가 하는 생각도 드네요😅

규모가 커지면서 서비스와 레포지토리의 연결 때문에 고민을 좀 했는데, 순환 참조도 해보고 이것 저것 해보다가 지금 내린 결론은 `Question`이라는 하나의 단위에 `Answer`가 종속적이기 때문에 `QuestionService`에서 레포지토리를 모두 받아서 써도 되지 않나 하는 생각입니다. 
만약 로직이 너무 커진다면 `AnswerService`만 따로 뺄 수도 있을 것 같았는데, `Question`과 `Answer` 양쪽에서 참조가 필요할 경우 순환참조가 되어버리는 일이 발생했습니다. 
리팩토링을 진행하며 해당 부분이 없어지긴 했습니다만, 저렇게 될 경우 컨트롤러에서 각각 불러오는 것 말고는 해답이 떠오르지 않았습니다. 그런데 또, 그렇게 되면 컨트롤러에서 불필요한 로직이 노출되는 것이 아닌가 하여 지금같은 구조를 선택하게 됐습니다.

이외에 예외처리도 나름 한다고 해봤는데 잘 된건지 모르겠네요 ㅎㅎ..

테스트 데이터는 data.sql을 사용하지 않고 이전 미션에서 사용했던 `ApplicationRunner`을 계속 사용하도록 했습니다.

**로그인 기능 구현**
- 로그인 성공 시 세션에 저장
- 실패 시 재로그인
  - 실패할 경우 `LoginFailedException`이 발생하고 ExceptionHandler에서 401로 보내주도록 했습니다.

**로그인 상태에 따른 메뉴 처리 및 로그아웃**
- 로그인 상태에는 로그아웃과 개인정보 수정을, 로그아웃 시에는 로그인과 회원가입이 나오도록 했습니다.

- https://github.com/codesquad-members-2021/spring-boot-qna/pull/41#discussion_r591614148 을 참고해서 로그아웃도 post로 만들어보려고 했는데, css가 a태그에 맞춰져있어 get을 사용하도록 했습니다. onClick 같은 것을 이용하면 되긴 하겠지만 좋지 않은 방법인 것 같아 사용하지 않았습니다.

**자기 자신의 정보만 수정**
- 자신의 정보 및 게시글 댓글에 접근할 수 있도록 했습니다.
- 권한이 없을 경우 403 에러를 발생시키도록 했습니다.
- 아이디와 이름은 수정할 수 없도록 html에서 막아주고, 서버에서도 제외하고 업데이트했습니다.
- `User`에 비밀번호 및 id 검증을 추가했습니다.

**질문하기, 질문 목록 기능 구현**
  - 로그인 하지 않으면 질문을 하지 못하도록 버튼을 숨겼습니다.
  - 만약 url로 직접 접근한다면 401로 보내줬습니다.
  - 질문한 사람은 본인의 글을 수정 및 삭제할 수 있습니다. 질문한 사람이 아니라면 버튼이 보이지 않고, url로 직접 접근시에도 예외처리를 해줬습니다.

**중복 제거, clean code, 쿼리보기 설정**
- `SessionUtils`를 만들어 세션을 이용할때 발생하는 중복을 제거했습니다.
- 전체적으로 repository에서 가져올 때 중복이 발생하는 것 같아 메소드로 만들었습니다. 체크 로직이 점점 섞이면서 복잡해지는 것 같아 서비스를 추가해줬습니다.
- 정보 검증을 어디에서 해야할지 고민을 많이 했는데 최대한 `User`와 `Question`이 직접 처리하도록 했습니다.
- 쿼리 보기는 루카스에 있는 설정을 넣었고, 추가로 어떻게 매핑되었는지 결과를 보여주는 옵션도 넣었습니다.

**User와 Question 연결 실습(선택)**
- `Question`에 `@ManyToOne`으로 `User`를 연결했습니다.

**Answer 구현하기 실습(선택)**
- `Answer`에 `@ManyToOne`으로 `Question`을 연결했습니다. 하다보니, `Answer`에만 데이터가 있을 경우 비효율적인 것 같아 `Question`에 `@OneToMany`도 추가해줬습니다.
- 로그인 할 경우 답글을 달 수 있도록 했습니다.
- 자신이 쓴 답변만 삭제할 수 있도록 했습니다.

감사합니다!

2021-03-17 15:29 UTC, ksundong requested changes
안녕하세요! 프레디! 리뷰어 Dion입니다.
벌써 3단계 미션이네요. 정말 고생많으셨습니다!
PR 메시지 잘 작성해주셨네요. 

## 애플리케이션 관련 리뷰

- 게시글이 작성되지 않습니다. 500에러가 발생하네요.
- 자신의 글과, 댓글이 아닌 것에는 메뉴가 표시되지 않는 것은 좋네요.
- 댓글 작성은 되는데 수정이 불가합니다. 확인해주세요.
- 직접 접근 막아주신 것도 좋습니다.

## 코드 관련 리뷰

- ExceptionHandling에서는 Exception을 받아서 유의미한 정보를 뽑아내는 편이 좋겠습니다.
- 커밋에 해당 기능이 왜 추가되었는지 정리해주는 것도 좋다고 봅니다. (주석도 없어서 파악하기 어려운 코드가 있었습니다.)
- dummy 데이터를 생성해주는 코드가 해당 Entity 내부에 있는 것은 저는 좀 그렇네요. 별도의 클래스로 뽑아내는 것은 어떨까요?
- 중복 코드 제거를 유의미하게 해주시면 좋을 것 같습니다.
- 빈 라인이 메서드에 많이 들어가는데, 이는 메서드가 잘못 설계되었다는 느낌이 듭니다. 빈 라인 없이 하나의 일만 수행하도록 변경해보는게 어떨까요?
- `getXXX` 네이밍은 저는 최대한 지양하시라 말씀드리고 싶습니다. 네이밍이 일률적으로 `getXXX`로 되어있는데, `get`말고 더 좋은 단어를 생각해봅시다.

순환참조구조는 대부분 잘못된 설계일 가능성이 높습니다. 하지만 많이들 그렇게 구현합니다.
그리고 Question에서 Answer를 관리하는 것은 나중에 배우실 DDD와도 어느정도 연관이 있는 고민이라 좋은 고민이라고 말씀드리고 싶네요.
logout에 대한 고민은 이미 해보셔서 별다른 코멘트를 남기진 않을게요 ㅎㅎ

3단계 진행하시느라 고생하셨고, 애플리케이션에서 치명적인 버그가 조금 있어서 **변경 요청** 드립니다.
코멘트 확인하시면서, 궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론이 필요한 부분은 코멘트 남겨주세요.
고생하셨습니다! 다시 리뷰 요청 해주세요~

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public String illegalArgumentExceptionHandler() {
예외 핸들링을 할 때, 예외 객체를 받아서 사용하면 더 많은 정보를 사용자에게 전달해줄 수 있고, 로깅 및 디버깅에도 좋습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public String illegalArgumentExceptionHandler() {
밑에서는 사용하셨군요!
그리고, 가급적이면 기본 예외를 사용하시기 보다는 Custom 예외를 핸들링하는게 어땠나 싶네요.
IllegalArgumentException은 HTTP 상태 코드로 따지자면 400 에러에 가깝거든요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public ModelAndView loginFailedExceptionHandler(LoginFailedException e) {
여긴 잘 해주셨는데 `ModelAndView`를 사용해주신 이유를 알 수 있을까요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    public String formatDate(LocalDateTime date, String pattern) {
```suggestion
    public String formatDateTime(LocalDateTime date, String pattern) {
```
메서드가 정확히 하는 일을 명시해줍시다!

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
>          DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern(pattern);
매번 만들기보다는 상수로 추출하는 방법을 고민해봅시다.
사실 pattern별로 만들어줄 일이 그렇게 많진 않거든요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    }
이건 왜 추가되었는지 알 수 있을까요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
`RuntimeException`을 상속해주신 이유가 있으신가요?
`CheckedException`과 `UncheckedException`에 대해서도 알고계신가요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
이 부분은 간과하고 넘어가실 수 있을 것 같아서 한 번 짚어보는 개념으로 여쭤봤어요!

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +    }
여러개의 생성자 정의 좋습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    private LocalDateTime updateDateTime;
```suggestion
    private String comment;
    private LocalDateTime createDateTime = LocalDateTime.now();
    private LocalDateTime updateDateTime;
```

여기는 굳이 떨어뜨려주지 않아도 좋습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
`public`의 사용은 말리고 싶네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
createdDateTime은 기본값으로 넣어주기 때문에 굳이 받지 않아도 될 것 같네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
이 메서드가 여기 있어야하는지는 의문이 드네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
메서드 정의 좋습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
`JpaRepository`와 `CrudRepository`의 차이점에 대해서 알고계신가요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
요걸 추가해주신 이유는 어떤 이유인가요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
>      }
`null`을 넣어주는건 좋지 못한 것 같습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
>      }
그래야만 하는 이유가 있나요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
> +    }
좋습니다. 하지만 `writer.verifyWith` 말고 현재 클래스의 `verifyWriter`를 썼으면 어떨까 하는 생각이 드네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    }
생성자 인젝션 좋네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +        question.setWriter(SessionUtils.getSessionUser(session).toEntity());
메서드명은 그냥 `create` 정도면 무난한것 같아요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionController.java
>      public ModelAndView getQuestion(@PathVariable Long id) {
저는 개인적으로 `getXXX` 라는 네이밍을 지양하는 편입니다.
좋은 네이밍도 한 번 고민해봐주세요!

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +                .collect(Collectors.toList());
너무 과도한데요?
정말 방법이 이거밖에 없나요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +                .orElseThrow(() -> new IllegalArgumentException("질문이 존재하지 않습니다. id : " + id));
Custom Exception을 정의해주시면 좋을 것 같아요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +    @Transactional
`@Transactional`을 여기만 사용해주신 이유가 있나요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +        question.verifyWriter(currentSessionUser.toEntity());
기껏 메서드 정의했는데 사용하지 못하고 있네요.
`getVerifiedQuestion`을 사용해주는건 어떤가요?

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +        answerRepository.delete(answer);
메서드가 빈라인이 너무 많죠?
빈 라인은 의미를 구분하는 단위인데, 세 줄에 빈 라인이 두 개라면 한 번 쯤 더 좋은 코드를 의심해봅시다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/User.java
> +    }
외부에 오픈되어야 하나요?
굳이 그럴 필요 없을 것 같은데요~

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
>      public ModelAndView getUsers() {
`ModelAndView`를 많이 쓰셨는데, 어떤점에서 많이 쓰셨는지 궁금하네요!

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
> +        SessionUtils.setSessionUser(session, userService.updateUser(verifiedUser, newUser));
👍 
저라면 updateUser부분은 변수로 추출해서 쉽게 구분할 수 있도록 해줬을 것 같네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                .toDTO();
음 이건 설계레벨이긴 한데, `Entity`는 `DTO`를 모르는 편이 좋습니다.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public UserDTO getLoginableUser(String userId, String password) {
그냥 login하는 것 같은데, 메서드명은 의미를 잘 모르겠네요.

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                });
그냥 if 문으로 처리하는 편이 더 깔끔할 것 같은데요~

2021-03-17 15:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/utils/SessionUtils.java
> +    }
👍

2021-03-19 10:16 UTC, ksundong commented
@Dae-Hwa 
혹시 피드백이 다 반영된 건가요?
다 되셨다면 Review 요청을 다시 해주시면 감사하겠습니다!

2021-03-19 10:17 UTC, Dae-Hwa commented
> @Dae-Hwa 
> 
> 혹시 피드백이 다 반영된 건가요?
> 
> 다 되셨다면 Review 요청을 다시 해주시면 감사하겠습니다!

아직 반영 중입니다! 완료되면 다시 요청 드리겠습니다 감사합니다!

2021-03-19 14:14 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +                .orElseThrow(() -> new IllegalArgumentException("질문이 존재하지 않습니다. id : " + id));
서버에서 자원을 찾을 수 없는 경우를 `ResourceNotFoundException`로 정의해줬습니다.
9a067b224e3c2d7eda5999a05dd1838998bf468a

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
>      public ModelAndView getQuestion(@PathVariable Long id) {
처음에는 get 외에는 create, update, delete를 사용하고 있어서 read로 바꿔주며 crud로 통일성 있게 만들어줬습니다. 
0229fcad9fcf2f41086eb877b8210292ecc17a0f

그런데 위에서 `create` 정도면 충분하다고 하신걸 힌트라고 생각하고 다시 수정했습니다.
2ef2837daa79254ed6a39528921beb6ae1a04b77

클래스 명에서 어떤 것에 대한 작업인지 명시해주기 때문에(예를 들어 QuestionService면 Question에 관한 작업) 메소드에서 굳이 한번 더 언급할 필요가 없다 정도로 이해했는데, 혹시 너무 과하게 받아들인건지 여쭤보고 싶습니다.

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +                .collect(Collectors.toList());
수정했습니다.
3c4f028746e8b6550409d6c836e4d86176c92553

공변 리턴 타입이라는걸 몰랐습니다. 언어 이해도가 떨어졌네요. 
https://www.geeksforgeeks.org/covariant-return-types-java/ 참고해서 학습했습니다.

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +    @Transactional
다른 부분에서는 트랜잭션을 사용할 일이 없는 것 같아 여기만 사용했습니다.
전역으로 ReadOnly를 걸어주면 성능향상을 기대할 수 있다고 봤는데, 아직 자세하게 보지는 못했습니다 😅

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +        question.verifyWriter(currentSessionUser.toEntity());
수정했습니다!
cf8101a576ed023b1ce840a9f74aaeade44ef85c

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +        answerRepository.delete(answer);
의심해보고 나름 나눈다고 나눠봤는데 쉽게 없어지진 않는 것 같습니다 😅 계속 고민해보도록 하겠습니다! 
해당 부분은 `readVerifiedAnswer`로 조회 및 검증 부분을 따로 분리해서 묶어줬습니다.
cf8101a576ed023b1ce840a9f74aaeade44ef85c

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/User.java
> +    }
수정했습니다!
357f0e90c0f67fc2c32d71bf96ddbd0de314e2fa

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserController.java
>      public ModelAndView getUsers() {
특별한 이유는 없고 이게 마음에 들어서 썼습니다.
장황해보인다 하시던데 저는 왠지 깔끔해보여서... 쓰기 시작했는데, 리뷰 받는동안 크게 말씀이 없어서 계속 사용했습니다. 이후에는 통일성을 위해 계속 사용해줬습니다.

쓰면 안되는 것인지 궁금해서 찾아봤는데 옛날에 쓰던것이고 view를 직접 리턴할 경우가 생길때 사용하면 좋다 라고 되어있긴 했는데, deprecated된 것도 아니고 내부 동작도 어차피 ModelAndView를 사용하니 크게 문제가 없지 않을까? 라고 생각했습니다!

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserController.java
> +        SessionUtils.setSessionUser(session, userService.updateUser(verifiedUser, newUser));
수정했습니다!

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                .toDTO();
일단 말씀을 듣고 DTO에서 팩토리 메소드를 구현해줬습니다.
869729d43e6c6d5af8aa2eb7aa7c11189a09a0e1

혹시 이유를 여쭤봐도 될까요? DTO와 관련된 것은 entity의 책임을 벗어나는 일이기 때문이 아닐까 짐작해봤습니다.

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public UserDTO getLoginableUser(String userId, String password) {
수정했습니다.
f0d290926bbbff59e06920b72355a78394067430

`readVerifiedUser`를 재사용하기에는 조금 다른 로직이 들어가는 부분이 있어서 `readPasswordVerifiedUser`를 새로 만들어 줬습니다. 이유는 id가 아닌 userId로 데이터를 조회해야 하기 때문이고, 로그인 시에 사용자의 id키값을 미리 알 수는 없기때문에 검증 대상에 id가 없이 password만 들어있습니다.

만들고 나서 궁금한 점은, 그냥 login하는 것 같다고 하셨는데, 굳이 이렇게 메소드명을 지은 이유는 실질적으로 로그인하는 동작은 현재 session에 사용자 정보를 넣는 부분이고, 서비스에서는 조회와 원하는 정보가 맞는지 검증하는 동작을 하는데 이게 로그인의 일부라고 명시할 수 있긴 하지만 실질적인 동작은 아니니 login으로 이름짓기가 조금 꺼려졌습니다.
혹시 제가 너무 딱딱하게 생각하고 있는 것일지 여쭤보고 싶습니다

2021-03-19 15:03 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                });
수정했습니다!
b0f72e2c36ee3c834dfb0f633d25dffc08a724c0

2021-03-19 15:04 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Question.java
> +    }
수정했습니다.
cf8101a576ed023b1ce840a9f74aaeade44ef85c

2021-03-19 15:05 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Question.java
>      }
더미데이터에서 사용하기 편하게 만들었던 것 같은데, 이런 부분들 제거하기 위해 빌더를 추가해줬습니다.

6daae6bc8d26d35e58cba0d3a1545a24a2724973

2021-03-19 15:06 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Question.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
추가 하지 않으면 Auto로 설정된다고 알고 있었는데, 당연히 AutoIncreament같은 것을 활용할 것이라 생각했는데, 제가 생각했던 id값과 다르게 나와서 당황했습니다. 찾아보니 특정 버전 이후부터 일부 db에서는 auto가 테이블을 사용하는 전략으로 지정된다는걸 확인했고, 제가 생각했을 때는 각 테이블 별로 id는 각각 다르게 증가해야 한다고 생각해서 선택했습니다.

2021-03-19 15:09 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
둘 다 SimpleRepository를 인스턴스로 사용하는데, JpaRepository가 더 많은 기능을 제공하는 것으로 알고 있습니다. 현재는 불필요하다고 판단해서 Crud로 변경해줬습니다!

2021-03-19 15:10 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
DummyDataFactory를 따로 만들어서 분리해줬습니다.
c8be26021037b2fc43bedf0003a0ad0ae98fa91c

2021-03-19 15:10 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    }
수정했습니다

2021-03-19 15:12 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
기본적으로 RuntimeException을 상속받아서 customException을 만든다고 알고 있습니다.
Checked는 소스 레벨에서 수정할 수 있는 예외고 반드시 처리해주거나 throws로 명시해줘야하고 Unchecked는 소스 레벨에서 막을 수 없는 예외를 뜻한다고 알고 있습니다.

2021-03-19 15:13 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    }
```html
{{#equals sessionedUser.id question.writer.id}}
<li>
    <a class="link-modify-article" href="/questions/{{question.id}}/form">수정</a>
</li>
<li>
    <form class="form-delete" action="/questions/{{question.id}}" method="post">
        <input type="hidden" name="_method" value="DELETE">
        <button class="link-delete-article" type="submit">삭제</button>
    </form>
</li>
{{/equals}}
```
이런 식으로 글쓴이와 로그인 상태의 사용자가 다를 경우는 페이지에서 버튼을 노출하지 않게 하기 위해서 추가했습니다.

2021-03-19 15:14 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
>          DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern(pattern);
어딘가에 속하기 애매한 것 같아 상수 정의용 클래스 Const를 만들어서 넣어줬습니다.
b92083fdc861fb095c75d56d49a69e160e58bc65

2021-03-19 15:16 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public String illegalArgumentExceptionHandler() {
예외 상황의 정보를 logger.error로 출력해주도록 처리했습니다.

8313008b48eaf6a52d0c8ba040bd527fe890de4a

2021-03-19 15:23 UTC, Dae-Hwa commented
우선, 배포가 제대로 되지 않아서 리뷰에 방해가 된 것 같아 사과를 드립니다. 피어 리뷰에서 지적 받고 고쳤는데 배포를 하지 않아 오류가 계속 남아있었습니다.
생각해보면 이전에도 비슷한 경우가 계속 생겼던 것 같아서 깃헙 액션을 이용해서 자동 배포를 해주도록 설정해봤습니다.

댓글 수정은 요구사항에 없어서 다음 단계에서 새로운 요구사항으로 제시되는 줄 알고 신경쓰지 않고 있었는데, 다른 분들께 물어보니 3~4단계에서 구현을 하셨다고 하여 저도 구현해줬습니다. 실제 동작하는 프로그램에 신경을 덜 쓴것 같아 이외에 다른 부분도 조금씩 손봤습니다.

파악하기 힘든 부분이 있다고 하셨는데, 커밋까지 읽어보실줄 모르고 저 혼자만 알아보게 썼던것 같아요 😅 좋은 방법을 찾아보다가 [git-cz](https://github.com/streamich/git-cz)라는게 있어서 적용해봤습니다.
깃헙 커맨트 포멧을 도와준다고 해서 사용해봤는데, 간단한 설명과 자세한 설명을 작성하도록 안내해줘서 좀 더 신경써서 작성할 수 있는 것 같아 계속 사용하기로 했습니다.
npm으로 제공되는거라 그레이들에 붙이기는 어려울 것 같아서, gitcz.sh라는 쉘 스크립트를 따로 작성해서 굳이 설치 하지 않아도 쉽게 사용할 수 있게 해봤습니다.

항상 많은 생각을 할 수 있게 리뷰 해주시는 것 같아 감사하네요! 재요청 드립니다 감사합니다!

2021-03-19 15:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public String illegalArgumentExceptionHandler() {
일단은 이정도로 충분해보입니다. ㅎㅎ

2021-03-19 15:33 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/config/CommonExceptionHandlers.java
> +    public ModelAndView loginFailedExceptionHandler(LoginFailedException e) {
에러 메세지를 화면에 출력해주기 위해 사용했습니다

2021-03-19 15:33 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
>          DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern(pattern);
좋네요 ㅎㅎ

2021-03-19 15:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    }
equals는 자바에서 이미 사용중인 메서드 명이잖아요?
다른 이름이 어땠을까 싶네요!
하시려는 의도는 어떤것인지 알 것 같아요.

2021-03-19 15:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
좀 더 예외에 대해서 공부해보시길 추천드려요.
'기본적으로' 해주니까 한다는 말은 별로 좋은 답변이 아니라고 생각됩니다.
'왜'가 빠져있잖아요?

얼마든지 CustomException은 Exception을 상속할 수도 있습니다.
다시 질문드리자면 '왜' 대부분의 CustomException이 RuntimeException을 상속하게 될까요?

`CheckedException`과 `UncheckedException`이 코드에서 가지는 의미는 무엇이 있나요?

2021-03-19 15:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
저는 그냥 둘의 동작의 차이점에 대해서 알고 요구사항과 다른 선택을 하셨는지에 대해서 질문한 거였어요.
굳이 안바꾸셔도 됬는데, 일단은 CrudRepository로 진행해보시죠 ^^

2021-03-19 15:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
좋네요. 원하는 것과 달라서 공부를 하셨군요! 👍

2021-03-19 15:43 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionController.java
>      public ModelAndView getQuestion(@PathVariable Long id) {
제가 `getXXX`를 지양하는 이유는, 이것이 Java에서 흔히 사용되는 '속성'을 가져오는 형태이기 때문입니다.
이것이 위험한 이유는 `getXXX`로 지정하면 `getter`로 인식하는 몇몇 라이브러리들이 존재하고, 원치않는 결과를 초래할 수 있어요.
말은 무섭게 적었는데, 더 좋은 네이밍을 항상 고민해보자는 측면에서 조언드린것입니다.

2021-03-19 15:44 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +                .collect(Collectors.toList());
잘 찾아서 해결하셨네요. 👍

2021-03-19 15:44 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    }
어렵지 않은 수정이라 바로 반영해뒀습니다

2021-03-19 15:45 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +    @Transactional
그런쪽의 성능은 지금부터 신경쓰실 필요 없습니다.
트랜잭션을 사용한 이유는 무엇인가요?

2021-03-19 15:49 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +    @Transactional
삭제 시 질문에 대한 답변도 함께 삭제를 해줘야 하기 때문에
`deleteAnswers(question.getAnswers());` 이후에
`questionRepository.delete(question);`를 해주도록 되어있습니다.
Cascade 옵션을 이용해서 처리가 가능한 것으로 알고 있지만, 이렇게 하는게 더 자연스럽게 느껴져서 이런 식으로 구현했습니다.

2021-03-19 15:50 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
>      public ModelAndView getQuestion(@PathVariable Long id) {
아 전혀 생각 못했던 문제네요! 감사합니다!

2021-03-19 15:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
>      public ModelAndView getUsers() {
무엇이 좋은지는 저도 잘 모르겠네요 ㅎㅎ
사실 둘 다 써도 무방한 프로젝트기도 했고, 언뜻보면 직관적인 형태가 될 수도 있을 것 같아요.
다만, `Model`이 필요없는 경우에 `ModelAndView`를 사용하는 것은 유쾌하지 않은 형태가 될 것 같네요.

2021-03-19 15:54 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                .toDTO();
Entity는 변화하기 어려운 것 입니다. 반면 DTO는 변화하기 쉬운 것 입니다.
너무 다 알려드리면 재미 없는 것 같아서, 힌트를 드릴테니 한 번 공부해보시길 추천드려요.

2021-03-19 16:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public UserDTO getLoginableUser(String userId, String password) {
로그인이라는 과정은 어떤 것인지에 대한 서로간의 시각 차이가 있었던 것 같습니다.
저는 id, pw 매칭을 하는 것이 로그인이라고 생각했고, 프레디는 세션에 정보를 넣는 부분까지를 로그인이라고 생각했던 것 같아요.
코드에 정답은 없으니 프레디가 하고싶으신 대로 하셔도 된다고 생각해요.
그리고, 딱딱하지 않습니다!

2021-03-19 16:07 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
만약 CheckedException을 상속받아 사용했다면 해당 에러가 발생하는 소스는 반드시 호출하는 쪽에서 직접 처리해줘야 할 것입니다.
그런데, 제가 정의한 예외 상황은 사용자 권한이 올바르지 않은 경우인데, 이는 내부의 문제가 아닌 외부에서 들어온 값이 제가 정한 제약조건과 다르기 때문에 발생합니다. 이 것은 catch해서 수정할 수 없는 경우이기 때문에 UncheckedExcpetion이 적절하다고 생각합니다.
예를 들어, 배열의 인덱스가 -1로 들어왔을때 발생하는 에러에 대해서 호출한 사람이 해당 경우에 유효한 값으로 바꾸어서 처리하게 하는것은 부자연스러운 일입니다. 제가 정의한 예외가 이러한 경우라고 생각합니다.

기본적으로라는 말은 확실히 틀린 것 같습니다. 제가 생각했거나 그동안 봐왔던 대부분의 사용자 정의 예외가 이런 경우라서 기본적으로라고 착각을 하고 있었던 것 같습니다.

일단 현재 제가 아는 범위 내에서 최대한 답변을 드려봤는데 좀 더 공부해보겠습니다! 좋은 주제 던져주셔서 감사합니다

2021-03-19 16:10 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public UserDTO getLoginableUser(String userId, String password) {
매칭을 하는 것도 로그인의 일부라고 볼 수 있겠네요. 딱딱하지 않다고 해주셨지만 살짝 딱딱했던 것 같기도 합니다..ㅎㅎ
답변 해주신걸 보면서 생각해보니 이런 주제가 논쟁이 되기 좋은 주제인 것 같다는 생각이 드는데, 좀 더 유연하게 생각하도록 노력해야겠네요
답변 감사합니다!

2021-03-19 16:13 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserController.java
>      public ModelAndView getUsers() {
말씀 해주신 관점으로 생각해보니 `Model`이 없는 경우에는 `String`으로 리턴해줘야 하는 것이 더 깔끔한 형태이니 오히려 통일성을 해치는 것 처럼 보일 수도 있겠네요. 많이 쓰는 이유를 조금 알 것 같습니다 ㅎㅎ 감사합니다!

2021-03-19 16:23 UTC, ksundong approved these changes
미션3에 대한 피드백을 반영해주시느라 고생하셨습니다.
다음 단계를 진행하기 전에 피드백을 추가로 드리니 한 번 생각해봐주세요.
4단계 진행하러 가봅시다. 고생하셨어요!

2021-03-19 16:23 UTC, ksundong commented on .github/workflows/main.yml
> +          heroku_email: "daehwa_jeong@outlook.com"
GitHub Actions의 사용 좋네요.

2021-03-19 16:23 UTC, ksundong commented on gitcz.sh
> +npx git-cz --disable-emoji
신기하네용

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/Const.java
> +public class Const {
약어 사용은 지양해주시고, 누락된 private 기본생성자도 만들어주세요.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/DummyDataFactory.java
> +public class DummyDataFactory {
유틸리티성 클래스이니만큼 private 기본생성자를 만들어줍시다.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/config/CustomHandlebarsHelper.java
> +    public Object ifEquals(Object s1, Object s2, Options options) throws IOException {
메서드명이 바뀌었네요.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/LoginFailedException.java
> +    }
생성자들은 필요한 시점에 추가해줘도 된다고 봐요~

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private LocalDateTime updateDateTime;
여기는 붙여주세요~

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Question.java
> +    public static class Builder {
빌더패턴을 적용해주셨군요?
직접 구현해보는게 많은 도움이 될겁니다.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +        return "redirect:/questions/" + questionId;
메서드가 한 클래스에 집약되는 형태는 그리 추천드리고 싶지는 않네요.
한 번 분리를 고민해봐주세요~

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionRepository.java
> +    List<Question> findAll();
방법을 잘 찾으셨네요. 👍

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/QuestionService.java
> +    @Transactional
cascade를 써줘도 `@Transactional`을 사용해줘야 하는 것은 동일합니다.
나중에 DB 수업을 듣고나서 다시 한 번 고민해봅시다~

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/User.java
> +        if (this.id.longValue() != id.longValue()) {
왜 `longValue()`를 사용해서 비교해주셨나요?

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                .map(UserDTO::of)
보통 인자가 하나면 `from`을 쓴다고 하더라고요~ 참고해주세요~

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +        User result = read(id).toEntity();
재사용때문에 많은걸 포기하는 느낌이네요!

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    private UserDTO readUser(String userId) {
이 메서드가 내부적으로 사용되는 이유가 있나요?

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException(e);
예외 포장 좋습니다.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException(e);
로그인 실패가 예외인지는 고민해봐야겠죠?
브라이언이 동영상을 준비중이신 것 같던데, 나오면 같이 봅시다.

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public void createUser(UserDTO user) {
아직 여긴 User가 메서드명에 있군요

2021-03-19 16:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException("이미 존재하는 ID 입니다.");
이게 과연 LoginFailedException일까요?

2021-03-19 16:23 UTC, ksundong commented on src/main/resources/templates/qna/show.html
> +                          {{#ifEquals sessionedUser.id question.writer.id}}
👍

2021-03-19 16:32 UTC, Dae-Hwa commented on .github/workflows/main.yml
> +          heroku_email: "daehwa_jeong@outlook.com"
생각보다 쉽게 구현돼서 놀랐어요. 일단은 써본데 의의를 두려고 합니다!

2021-03-19 16:32 UTC, Dae-Hwa commented on gitcz.sh
> +npx git-cz --disable-emoji
정말 신기했습니다 ㅋㅋ

2021-03-19 16:43 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/common/Const.java
> +public class Const {
부끄럽네요 ㅎㅎ... 수정했습니다!

2021-03-19 16:43 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/common/DummyDataFactory.java
> +public class DummyDataFactory {
수정해줬습니다

2021-03-19 16:44 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/Question.java
> +    private LocalDateTime updateDateTime;
어떤 기준으로 맞춰야 할지 감이 제대로 왔습니다. 앞으로는 보기좋게 포메팅 해보도록 하겠습니다 😁

2021-03-19 16:50 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/User.java
> +        if (this.id.longValue() != id.longValue()) {
id가 반드시 들어와야 하는데, null인 경우를 비교하는게 어색하다고 생각됐습니다

2021-03-19 16:51 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException(e);
당연하지만 예외 너무 어려운 것 같습니다..ㅎㅎㅎ
얼른 보고 싶네요! ㅋㅋ

2021-03-19 16:52 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/exception/LoginFailedException.java
> +    }
불필요한 생성자들 모두 제거해줬습니다

2021-03-19 16:53 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +        return "redirect:/questions/" + questionId;
`readQuestion()` -> `read()` 와 같은 형태로 이름을 바꿔주면서 어색함을 느끼긴 했습니다.
고민해보겠습니다!

2021-03-19 16:53 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +                .map(UserDTO::of)
감사합니다! 바로 적용해봤습니다

2021-03-19 16:55 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    private UserDTO readUser(String userId) {
String으로 된 UserId를 가져오기 위한 메소드인데, 원래는 `readPasswordVerifiedUser`에서 한꺼번에 가져오면서 null체크 까지 해주던 것을 분리한 메소드입니다

2021-03-19 16:55 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +    public void createUser(UserDTO user) {
수정했습니다

2021-03-19 17:02 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +        User result = read(id).toEntity();
혹시 이런부분 어떻게 처리하시는지 여쭤봐도 될까요?
결이 조금 다르긴 하지만, 스프링에서는 readInternal 이런 식으로 명명하는 것도 봤는데, 지금의 저에게는 가장 어려운 부분 중 하나인 것 같습니다😭.
너무 어렵게 생각하는걸까요

2021-03-19 17:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/User.java
> +        if (this.id.longValue() != id.longValue()) {
equals()를 사용해보면 어때요?

2021-03-19 17:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +        User result = read(id).toEntity();
그냥 직접 repository에서 들고와주면 되지 않을까요?

2021-03-19 17:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/InsufficientAuthenticationException.java
> +public class InsufficientAuthenticationException extends RuntimeException {
네 많은 고민을 하신 것 같네요. 좋습니다.

2021-03-19 17:38 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/User.java
> +        if (this.id.longValue() != id.longValue()) {
아... longValue()로 바꿔서 비교하게 돼있네요 감사합니다! 바로 적용하겠습니다

2021-03-19 17:44 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/User.java
> +        if (this.id.longValue() != id.longValue()) {
따지고 보면 비교대상이 null인 경우까지 체크해주니 더 좋은 것 같아요 감사합니다!

2021-03-19 17:48 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +        User result = read(id).toEntity();
null 체크 되는 부분이 계속 중복되는 것 같아 이런식으로 한 것이었는데, 다른 메소드로 중복 제거하는 방향으로 생각해봐야할까요?

2021-03-19 18:54 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException("이미 존재하는 ID 입니다.");
Login하는 상황의 예외가 아니니, `UserExistedException`를 추가해줬습니다.
위에서 예외에 대해 고민해보라는 말씀이랑 연관지어서 생각해봤는데,

제가 해당 메소드에서 기대하는 상황은 저장되어 있지 않은 user에 대한 update작업이 일어나는 것입니다. 그렇기 때문에 이미 저장되어 있는 사용자라면 예외 상황으로 간주했습니다.

그런데 다시 생각해보면, id로 들어오고 조회를 하여 판단하는 것이 제가 의도한 것과 별개로 메소드 내부에서 예외처리 없이도 잘 작동하는 정상 흐름이고, 거기에 대한 참 거짓을 충분히 판단할 수 있습니다. 그렇다면 리턴 타입을 true/false로 정하여 컨트롤러에서 그에 따라 뷰를 리턴하거나 상황에 맞는 모델을 넣어서 구성할 수도 있다는 생각을 해봤는데요.
혹시 위에서 말씀해주신 로그인 실패가 예외인지 고민해보라는 것이 이런 상황인건지 궁금합니다

2021-03-19 19:09 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException("이미 존재하는 ID 입니다.");
위의 생각에 이어서 이렇게 생각해봤습니다.
우선 예외를 설정하는 기준을 애플리케이션에 값이 들어오는 상황으로 잡습니다.
예를들어, 컨트롤러로 request가 들어오는 시점, 조회한 결과가 돌아오는 시점이 될 수 있을 것 같습니다.
이외에 내부에서 돌아가는 특별한 경우를 제외하고 로직은 정상 작동 범위 안에 있으니 거기에 따라 판단하도록 하고, 특별한 경우에 대해서만 예외를 던져주는 식으로 기준을 잡아보는건 어떨까 하고 생각해봤습니다.

2021-03-19 19:16 UTC, Dae-Hwa commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +        return "redirect:/questions/" + questionId;
이동 완료 했습니다!

2021-03-20 03:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +        User result = read(id).toEntity();
null 체크가 계속된다면, 반환 타입을 Optional로 래핑하는 방법을 고민해보세요~

2021-03-20 03:13 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserService.java
> +            throw new LoginFailedException("이미 존재하는 ID 입니다.");
제가 의도한건, 예외는 명확해야 한다는 것이었는데, 추가적인 답변이 달렸네요.
이미 아이디가 존재하는 경우는 exist 쿼리로 충분히 if문으로 처리가 가능할 겁니다.
좋은 고민을 하셨네요. 👍 저도 프레디의 생각이 맞는것 같아요.

2021-03-20 05:07 UTC, merged