[Bat] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #76
Opened 2021-03-16 02:43 UTC by kjk402

안녕하세요, 웹백엔드과정 Bat입니다.

미션4 구현하여 pull request 드립니다.

• 미션4 구현 URL : https://bat-spring-qna.herokuapp.com/

미션4는 미션3에서 약간의 내용만 추가되어 코드의 변동이 적습니다. 
하기와 같이 미션4 구현하였습니다.

• @NotBlank 사용 : 미션3에서는 직접 validator를 만들어 사용했으나, 원래 validation의 목적과는 다르게 사용된다는 리뷰어분의 피드백을 받아서 spring boot에서 기본으로 제공되는 valid를 사용하였습니다. 

• 답변 삭제 기능 구현 : 답변 작성자와 로그인한 유저가 같을 경우 삭제할 수 있습니다.

• 질문과 답변 삭제 soft delete 로 구현 : 질문과 답변을 삭제 시에 repository에서 삭제하는 것이 아니라 boolean type을 true로 변경시킵니다. (질문 삭제 시에는 하위 답변들 모두 true로 변경됩니다.)

• @Query 사용 : 삭제된 데이터 (boolean type이 false 상태)가 아닌 Active 상태인 질문과 답변만을 가져오기 위해  @Query 어노테이션으로 false만 불러오도록 쿼리를 정의하였습니다.
                                            
• canDelete 메소드 : 질문 삭제 가능 여부 검증 시에 필요한 메소드입니다. 
질문 삭제 가능 조건은 두가지이고 Active 상태의 답변들 개수를 뜻하는 allAnswers 를 사용하여 조건을 확인합니다.
1. 답변이 없는 경우 : allAnswers == 0 이면 삭제 가능합니다.
2. 질문 작성자와 모든 답변 작성자가 같을 경우 : 모든 답변 작성자와 질문 작성자를 리스트 선회를 사용하며 비교합니다. 같을 경우 count를 증가시켜 선회 종료 시 allAnswers 와 비교하여 동일하면 삭제 가능합니다.

리뷰 잘 부탁드립니다.
감사합니다.

2021-03-17 16:12 UTC, ksundong requested changes
안녕하세요! Bat!! 리뷰어 Dion입니다.
먼저 4단계 미션까지 수행하시느라 고생많으셨습니다. 이제 얼마 안남았네요~
이번 미션은 애플리케이션에서 문제가 발생하는 부분이 있어 **변경 요청** 드립니다.
피드백을 확인해주세요!

---

리뷰는 열심히 했습니다 ㅎㅎ

## 애플리케이션 관련 피드백

- url 설계가 조금 아쉽습니다. `users/update/3` 등을 보면 RESTful한 url 설계에 대해서 조금 더 이해하셨으면 좋겠다는 생각이 드네요.
- 회원정보 수정시 비밀번호 필드를 제외한 필드는 채워져있어도 괜찮지 않을까요?
- 다른 유저의 회원정보 수정시 500에러가 발생합니다.
- 코멘트에도 있는데, 빈 정보를 입력할 때 500에러가 발생합니다. 유효성 체크가 되고 있는건지는 잘 모르겠네요.
- 목록 버튼을 누르면 404에러가 발생합니다.

## 코드 관련 피드백

- 유효성 검증이 제대로 되는지는 잘 모르겠네요. 제가 알기론 동작하지 않을 것 같습니다. `@Valid` 애노테이션도 학습해보세요~
- 객체지향적인 코드를 지향해주셨으면 합니다. 뭔가 get해서 처리해주는 것은 절차지향적입니다. 객체에게 물어보세요~
- 중복제거에 조금만 더 신경써주세요~

추가적인 코멘트는 아래에 작성해두었습니다.
4단계 진행하느라 고생 많으셨고, 궁금하시거나, 도움이 필요한 부분, 이해가 안되는 부분, 토론하고 싶은 부분은 언제든 코멘트 남겨주세요.
고생하셨습니다~

2021-03-17 16:12 UTC, ksundong commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
오 validation이군요.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        if (answer.matchUser(loginUser)) {
👍

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
>      }
이렇게 구현하기 보다는 home에서 question 목록으로 redirect하는 구현으로 변경드리길 권장드립니다.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (questionService.canDelete(id, question, loginUser)) {
if문을 service에서 수행해봅시다.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("answerCount", questionService.findAnswer(id).size());
중복이죠?

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
ㅎㅎ 벌써 Validation을 보게되었네요.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
근데 이것만 가지고 Validation이 되던가요?

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
빈 내용을 입력하면 500에러가 발생하긴 하네요...

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
>      private LocalDateTime currentDateTime;
현재시간이라는 변수명보다는 다른 이름으로 바꿔봅시다.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        if (this.writer.getUserId().equals(userId)) {
writer에게 물어봅시다. "이 아이디 네거랑 일치하니?"

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        if (this.writer.getUserId().equals(userId)) {
혹은 이렇게 물어봐도 되겠네요.
"이 계정이 너니?"

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        return false;
```suggestion
        return this.writer.getUserId().equals(userId));
```

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
별다른 문제는 발생하지 않던가요?

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
Null, Emtpy, Blank의 차이에 대해서 학습해봅시다.
여기도 똑같이 500에러 발생하네요.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    }
이 메서드 좋은 것 같은데 왜 지워주셨나요?

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    }
그냥 `answerCount()`여도 좋은 것 같아요.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    @Query("SELECT answer FROM Answer answer WHERE answer.deleted = false and answer.question.id = :questionId")
Query 애노테이션 없이도 충분히 가능할텐데요~
한 번 메서드로 이용해봅시다.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElse(null);
`orElse(null)` 말고 다른 방법을 고민해봅시다. 
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        for (Answer answer : findAnswer(id)) {
메서드 명만 봐서는 하나의 answer만 반환될 것 같은데 collection인가요?

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        for (Answer answer : findAnswer(id)) {
question의 id인데 그냥 id여서 헷갈릴 것 같아요.

2021-03-17 16:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
너무 복잡한 메서드네요.
1. 객체에게 물어보면 안될까요?
2. 객체를 이용해서 비교를 하면 안될까요?
3. 조건을 변수로 추출해보면 안될까요?

2021-03-17 16:44 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/HomeController.java
>      }
057bf94 에서 home이 redirect 하도록 변경하였습니다.

2021-03-17 17:12 UTC, kjk402 commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    @Query("SELECT answer FROM Answer answer WHERE answer.deleted = false and answer.question.id = :questionId")
저도 처음엔 이 부분을
List<Question> findActiveAnswer(Long questionId, boolean deleted);
이런 식으로 구현할려고 하였으나, 학습차원에서 시도해보았습니다. 

별거 아니지만 구현하는데 오래걸려서 지우기 아쉽네요. ㅠㅠ

2021-03-17 18:11 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        for (Answer answer : findAnswer(id)) {
answers 로 수정하였습니다.
questionId 로 변경하였습니다.

2021-03-17 18:12 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
2ed4b1e 에서 객체를 이용하여 비교, 조건을 변수로 추출하였습니다.

2021-03-17 18:13 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        return false;
넵 수정하였습니다.

2021-03-17 18:15 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        if (questionService.canDelete(id, question, loginUser)) {
controller 에선 questionService.delete(question, id, loginUser) 만을 이용하여
으로  기존의 if문은 service에서 동작합니다.

2021-03-17 18:41 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
500에러가 발생하면서 에러메시지가 표시됩니다.

2021-03-17 18:43 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
로그에 겹치는 내용이 많이 등장합니다. contents 와 deleted만 로그에 남기는 것이 좋을까요?

2021-03-17 18:45 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
null이 제일 작은 범위이고, Blank는 "" , " " , null 체크가 가능하여 Blank를 사용하였습니다.

2021-03-17 18:47 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    }
이 메서드를 사용하면 deleted 된 답변들까지 셈을 하여 삭제하였습니다.

2021-03-17 18:52 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
>      private LocalDateTime currentDateTime;
createdDateTime 으로 변경하였습니다.

2021-03-17 18:58 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        if (this.writer.getUserId().equals(userId)) {
7f970cf 에서 가독성 좋게 변경하였습니다.

2021-03-18 02:43 UTC, kjk402 commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    @Query("SELECT answer FROM Answer answer WHERE answer.deleted = false and answer.question.id = :questionId")
ad7b77e 쿼리 제거하였습니다.

2021-03-18 02:49 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("answerCount", questionService.findAnswer(id).size());
answersList만 보내고 th:text="${#lists.size('answersList')}" 
을 사용하여 크기를 구할려고 했는데 잘 안됩니다.

findAnswer(id).size() 를 지우고 html에서 list 크기를 구할 수 있을까요?

2021-03-18 03:06 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
우선  writer 와 question은 제거하였습니다.

2021-03-18 03:14 UTC, kjk402 commented
RESTful한 url 설계에 대해 이번 기회에 처음 공부해보았습니다. url에 update, delete 같은 행위를 포함하면 안되는 것 확인하였습니다.

또 궁금한 점 두가지가 있습니다.

1. ("answerCount",questionService.findAnswer(id).size()) 을 제거하고 list크기를 구할 수 있나요.
2. 쿼리 어노테이션을 사용하지 않고 쿼리 메서드를 사용해야하는 이유가 따로 
있을까요?

리뷰 감사드립니다. ~~

2021-03-18 03:19 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElse(null);
5d9e551 orElseThrow 로 변경하였습니다.

2021-03-18 08:00 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
exception을 따로 생성하고 정의해주겠습니다.

2021-03-18 08:35 UTC, kjk402 commented
다른 유저의 회원정보 수정시 500에러가 발생합니다
 ㄴ 7a9fb78 에서 수정하였습니다.

2021-03-18 09:18 UTC, kjk402 commented
멘트에도 있는데, 빈 정보를 입력할 때 500에러가 발생합니다. 유효성 체크가 되고 있는건지는 잘 모르겠네요.
 ㄴ 8de8b2d NotBlank exception 연결해주었습니다.

2021-03-18 12:12 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        modelAndView.addObject("answerCount", questionService.findAnswer(id).size());
handlebar에서 객체를 탐색해서 그려주는지가 기억이 잘 안나네요.
일단 `questionService.findAnswer(id)` 만 추출해줘도 괜찮지 않을까 싶습니다.
`answerList.size()` 같은 형태로 꺼내면 좋을텐데 말이죠...

2021-03-18 12:13 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
차차 학습하시겠지만, 500에러는 서버에 문제가 있음을 알려주는 상태코드입니다.
따라서, 유저가 잘못 입력했을 때에는 무엇을 잘못입력했는지 알려주고, 이를 사용자가 다시 입력하는 형태로 구현을 하는 것이 좋겠습니다!

2021-03-18 12:14 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        if (this.writer.getUserId().equals(userId)) {
해당 메서드는 객체지향적이지 않네요 ㅠㅠ

2021-03-18 12:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
로깅을 할 때, 서로 연관관계가 설정되어있어 생기는 문제입니다.
저같은 경우에는 연관관계가 설정된 내용만 제거해주는 편입니다.

2021-03-18 12:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    @NotBlank(message = "내용은 필수 입력 값입니다.")
발생하는 Exception으로 충분할 것으로 생각됩니다!

2021-03-18 12:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    }
그렇네요~

2021-03-18 12:16 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    @Query("SELECT answer FROM Answer answer WHERE answer.deleted = false and answer.question.id = :questionId")
나중에는 마음껏 쿼리 작성하실 수 있습니다.
그리고 굳이 안지우셔도 됐는데 ㅎㅎ 메서드 명이 명확한 편이 나은 것 같다고 생각해요!

2021-03-18 12:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
이 부분 리뷰 다시 남겨드릴게요~

2021-03-18 12:49 UTC, ksundong approved these changes
안녕하세요! Bat!! 리뷰어 Dion입니다.
다시 **변경 요청** 드리니 참고해주세요.

1. `Exception`을 직접사용하는 경우는 없다고 보시면 됩니다.
2. `throws Exception` 역시 무조건 지양하는 편이 바람직합니다.
3. `url`에 동사형태가 왠만하면 들어가지 않도록 해주세요. (`create`, `update`, `delete` 등은 HTTP Method로 표현가능합니다.)
4. HTTP 상태 코드에 대해서 학습하시고, 명확한 상태코드를 반환해주세요.
5. 네이밍은 조금 더 신경써주세요. 메서드의 이것이 어떤 것을 해줄 수 있는지를 작성해주시면 됩니다. 변수명의 경우엔 이것이 무엇인지를 설명해주세요.
6. 객체지향적인 코딩을 지향하기 위해서 `get`의 사용은 멀리해주세요. `get`으로 꺼내서 직접 사용하지 말고, 객체에게 물어보는 형태로 개발해주세요.

피드백 반영하느라 수고하셨습니다! 조금만 더 고생해주세요!

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/HomeController.java
> +        return "redirect:/questions";
👍

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public ModelAndView viewQuestion(@PathVariable Long id) throws Exception {
`throws Exception`은 지양해주세요!
명확한 예외를 지정해주시거나, 런타임 예외를 발생시켜주세요.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>          return getQuestionRepository("/qna/show", id);
중복코드가 있나요? 없다면 굳이 추출할 필요가 없다고 생각합니다.
메서드가 의미하는 것과 행동하는 것이 다르기도 하고요.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      @PutMapping("/{id}/update")
여기 아직도 `update`가 남아있네요.
url 조금 더 신경써 주세요!

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @GetMapping(CONFIRM_INFO)
이런식의 정의는 처음봤네요.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String confirmUserInfo(@PathVariable Long id, String password) throws Exception {
메서드 명이 위에 작성해주신 것과 다를게 없네요.
하는 행동이 다른데, 같으면 안됩니다~

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
객체지향적으로 사고한다면, user에게 loginUser가 맞니? 하고 물어볼 수 있습니다.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>      }
굳이 필요할까요?

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +    @ExceptionHandler(IllegalStateException.class)
이런 자바 기본 예외는 여러 상태값이 될 수 있어서 저는 가급적이면, 예외를 생성해서 지정해주는 편입니다.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +    @ExceptionHandler(IllegalStateException.class)
IllegalState가 정말 UnAuthorized만 될까요?

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        model.addAttribute("errorMessage",error[1]);
혹시 어떤 이유로 error[1]을 반환하는지 알 수 있을까요?

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        return "error/402";
BAD REQUEST의 상태 코드는 400입니다!

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    List<Answer> findAllByQuestionIdAndIsDelete(Long questionId, boolean deleted);
여기도 삭제되지 않은것만 조회할 것이지 않나요?
그냥 쿼리 메서드에 False를 넣어줘도 좋을 것 같아요.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        Question question = questionRepository.findById(id).orElseThrow(() -> new Exception("null 값입니다."));
예외 다시 정의해주세요~

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        return answerRepository.findById(id).orElse(null);
안바뀌었네요~

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (canDelete(questionId, question, loginUser)) {
question에게 물어봅시다.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return (flag1 || flag2);
이 메서드를 `Question`으로 옮기는건 꽤 도전할 만한 것 같습니다.
1. `allAnswers`는 전혀 int형 변수에 맞는 이름이 아니라고 생각됩니다.
2. `numCount` 말고 그냥 `count`여도 된다고 생각해요.
3. `get`사용하지 말고 코딩해보세요. 전혀 객체지향의 이점을 못누리는게 바로 `get`을 사용하는 코딩입니다.
4. `flag1, 2`는 무조건 지양해야하는 변수명입니다. 그래서 저게 무슨 `flag`인지는 읽는 사람이 전혀 모르게됩니다.

2021-03-18 12:49 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return (flag1 || flag2);
그리고 `Question`에게 물어봅시다. '너 지워도 되니?'

2021-03-18 15:08 UTC, ksundong requested changes
앗 제가 실수했네요. 변경 요청인데 Approve를 했었네요 ㅠㅠ

2021-03-18 15:10 UTC, kjk402 commented
네 수정하겠습니다. ㅎㅎ

2021-03-18 15:44 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
연관관계가 있는 경우엔 더욱 신경쓰겠습니다. ^^

2021-03-18 15:50 UTC, kjk402 commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    List<Answer> findAllByQuestionIdAndIsDelete(Long questionId, boolean deleted);
a94b11b 에서 넣어줬습니다.
디온 말씀하신 바와 같이 쿼리 작성보다 더 명확한 것 같습니다.

감사합니다.

2021-03-18 15:55 UTC, kjk402 commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        model.addAttribute("errorMessage",error[1]);
message를 통으로 반환하면 
Validation failed for classes [com.codessquad.qna.domain.Question] during persist time for groups [javax.validation.groups.Default, ] ~생략~{interpolatedMessage='내용은 필수 입력 값입니다.', 
이렇게 표시됩니다. 저는 '내용은 필수 입력 값입니다.' 만 추출하고 싶어서 ' 기준으로 split 하고, error[1]을 반환합니다.

2021-03-18 15:57 UTC, kjk402 commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        model.addAttribute("errorMessage",error[1]);
@NotBlank(message = "내용은 필수 입력 값입니다.") 이렇게 하면 message를 지정해줄 수 있고, 에러화면에서도 사용하고 싶어서 이렇게 구현하였습니다.

2021-03-18 16:17 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        Question question = questionRepository.findById(id).orElseThrow(() -> new Exception("null 값입니다."));
4e339b0 404에러로 다시 정의하였습니다.

2021-03-18 16:21 UTC, kjk402 commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +    @ExceptionHandler(IllegalStateException.class)
UnAuthorized 으로 변경하였습니다. 기본 예외 사용 자제하겠습니다.

감사합니다.

2021-03-18 16:21 UTC, kjk402 commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        return "error/402";
넵 400으로 수정하였습니다. ㅎㅎ

2021-03-18 16:22 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +        Question question = questionRepository.findById(id).orElseThrow(() -> new Exception("null 값입니다."));
NotFoundException 생성하였습니다.

2021-03-18 16:26 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    public ModelAndView viewQuestion(@PathVariable Long id) throws Exception {
네 NotFoundException 생성하여 수정하였습니다.

2021-03-18 16:31 UTC, kjk402 commented on src/main/java/com/codessquad/qna/domain/Question.java
>      }
제거하였습니다. ~

2021-03-18 16:31 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      @PutMapping("/{id}/update")
put으로 변경하였습니다.

2021-03-18 16:36 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>          return getQuestionRepository("/qna/show", id);
view ->showQuestion 으로 변경, 추출한 것 다시 원복하였습니다.

2021-03-18 16:40 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String confirmUserInfo(@PathVariable Long id, String password) throws Exception {
GetMapping 부분 confirmForm으로 변경하였습니다.

2021-03-18 18:09 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        return (flag1 || flag2);
dcaff5a 에서 Question 에서 물어보도록 변경하였습니다.

2021-03-18 18:11 UTC, kjk402 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (canDelete(questionId, question, loginUser)) {
dcaff5a 에서 Question 에서 물어보도록 변경하였습니다.

2021-03-18 18:16 UTC, kjk402 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @GetMapping(CONFIRM_INFO)
뷰네임을 enum 혹은 상수로 관리하는 것에 대한 리뷰어분의 권유로 상수로 빼봤습니다. ^^ ~~

2021-03-19 09:40 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>          return getQuestionRepository("/qna/show", id);
제가 말한건 `viewQuestion`이 아니라, `getQuestionRepository`입니다. ㅠㅠ

2021-03-19 09:41 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      @GetMapping(CONFIRM_INFO)
넵넵!

2021-03-19 09:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        model.addAttribute("errorMessage",error[1]);
ConstraintViolationExcetpion에서 꺼내는 편이 좀 더 자연스럽지 않을까요?

2021-03-19 09:46 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/ExceptionAdvice.java
> +        model.addAttribute("errorMessage",error[1]);
`ConstraintViolationExcetpion`에서 꺼내는 편이 좀 더 자연스럽지 않을까요?

2021-03-19 10:15 UTC, ksundong approved these changes
이전 코드보다 제 생각에는 많이 나아진 것 같아요!
Bat 생각은 어떠신지 궁금합니다.
미션 4 피드백 반영해주시느라 고생많으셨고, 다음단계에서 아래의 피드백들을 반영해주세요~
고생하셨습니다!

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/AnswerController.java
> +        return "redirect:/questions/" + id;
```suggestion
        }
        return "redirect:/questions/" + id;
```
이렇게 해도 되지않을까 싶어요~

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @PutMapping("/{id}/put")
```suggestion
    @PutMapping("/{id}")
```
아직 Url 설계에 대한 감이 안오셨군요 ㅠㅠ
RESTful에 대해서 학습해보시는 것을 권장드리겠습니다.

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
>      @DeleteMapping("/{id}/delete")
```suggestion
    @DeleteMapping("/{id}")
```

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +        this.isDelete = false;
기본값이 false여서 굳이 지정해주지 않으셔도 됩니다.

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +    }
this.writer.equals(loginUser); 면 간단하겠죠?
아니면 개별 메서드를 지정해주셔도 됩니다.

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private LocalDateTime createdDateTime;
그냥 여기에 `LocalDateTime.now()` 를 지정해주시는 편이 중복 코드가 제거 될 것 같네요~

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +        if (!question.matchUser(loginUser)) {
```suggestion
        if (!question.isMatch(loginUser)) {
```

정도로 boolean 타입 값을 리턴하는 느낌을 줄 수 있을 것 같네요.

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>          }
이건 굳이 필요 없을 것 같은데요~

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>          }
없으면 아래의 for문을 수행하지 않습니다!

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
>          }
early return의 사용은 좋았어요~

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException{
```suggestion
public class NotFoundException extends RuntimeException {
```
ㅎㅎ 항상 정렬 신경써주세요!

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/repository/AnswerRepository.java
> +    List<Answer> findAllByQuestionIdAndIsDeleteFalse(Long questionId);
👍

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/AnswerService.java
>      private final AnswerRepository answerRepository;
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(AnswerService.class);
    
    private final AnswerRepository answerRepository;
```

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +        if (question.canDelete(question, loginUser, activeAnswers)) {
자기 자신을 넣는것도 빼면 더 좋을 것 같네요. `question`이 매개변수로 넘어가야 할까요?
`activeAnswers`도 `Question`이 가지고 있지 않을까요? (아닐 수도 있어요)
좀 더 읽기 좋은 코드가 된 것 같지 않나요?

2021-03-19 10:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/service/QuestionService.java
>      }
AnswerService에서 가져오는 편이 낫지 않을까요?

2021-03-19 12:01 UTC, kjk402 commented
제가 생각하지도 못한 곳까지 세세하게 리뷰해 주셔서 감사합니다. ㅎㅎ
디온 피드백을 반영하면서 많이 공부가 되었고 코드도 깔끔히 정돈됐습니다.
제 코드 개선점이 너무 많아 리뷰하시는 데 시간을 상당히 할애하셨을 것 같습니다. 죄송합니다. ㅠㅠ

다음 미션 진행하면서 추가로 리뷰해 주신 것 반영토록 하겠습니다.
@ksundong 감사합니다.~~

2021-03-20 05:07 UTC, merged