[이노] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #77
Opened 2021-03-16 05:56 UTC by eNoLJ

이번 미션4는 미션3에서 크게 변경 된 점은 두가지 입니다.

1. soft delete 적용
question과 answer 클래스에 isDelete 멤버변수를 만들고 삭제되었는지 유무를 확인 할 수 있도록 했습니다. 미션 요구사항대로 질문 작성자와 모든 답변의 답변자가 일치해야 질문을 삭제 할 수 있도록 했습니다. (하나라도 답변 작성자와 불일치 시 질문 삭제 불가 단, 작성자가 다른 답변이 삭제 될 시 삭제 가능)

2. exception 적용
그 동안 항상 객체가 생길 때 마다 전부 null인지 체크를 다 해줬던 부분을 예외를 만들고 `@ControllerAdvice'를 활용하여 수정했습니다.

위에 두가지 사항을 중점적으로 리뷰을 해주시면 감사하겠습니다. 특히 예외처리는 아예 무지했던 상황에서 적용한거라 제대로 한건지 아닌지 감이 잘 잡히지 않습니다. 많은 조언 부탁드려요.

이번 리뷰도 잘 부탁드립니다!!
좋은 하루 되세요!!

2021-03-17 15:31 UTC, wheejuni requested changes
4단계까지 진행하시느라 정말 고생 많으셨습니다. 👍 
예외를 적극적으로 사용해보시려 노력한 건 좋은 시도인데요, 가급적 `Exception` 엔 인스턴스 변수가 없었으면 좋겠습니다. 
`super()` 호출로 충분할 것 같고요, 다른 분기 로직이 필요하다면 다른곳에 구현을 고려해 주세요.
이외에 간단한 피드백 몇 개 더 드렸습니다. 참고해 주시고 반영하시거나 추가 질문 남겨주세요!

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        getUserFromSession(session);
메소드를 호출한 결과물은 사용하지 않나보네요?

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/CurrentPasswordNotMatchException.java
> +    private final User user;
예외 클래스가 갖기엔 너무 과한 필드입니다. ㅠㅠ

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/CurrentPasswordNotMatchException.java
> +    }
`Exception` 에서 꼭 이 객체를 갖다써야 할 이유가 있을까요? 
만약 유저에 따른 오류 메세지의 분기가 필요하다면, 그런 메세지를 만들어줄 다른 헬퍼 클래스를 구현해주시고,
이곳에서는 예외 상황에 직접적으로 관련된 정보만 관리되게 해주세요.

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
우선 비밀번호가 매치되지 않는 것은 예외는 아닌 것 같습니다. 예외를 너무 아껴도 곤란하지만 너무 남발하면 더욱 곤란합니다. 
암호 불일치가 정말 "예외" 인지 좀 따져봐야 할 것 같고요. 
그리고.... 비밀번호가 맞지 않아서 예외가 발생했는데... 그 예외에서 해당 유저에 대한 정보를 꺼내 쓰는 것, 좀 어색하지 않나요.
더군다나 이 정보로 뷰를 만들어서 유저에게 다시 주고 있네요. 여러모로 좀 이상한 것 같습니다.
조금 더 자연스러운 플로우를 고민해봐야할 것 같아요. 제가 보기에 이 모든 상황은 비밀번호 불일치를 "예외" 로 접근해서 시작된 것 같습니다.

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/WriterOfAnswerListNotMatchException.java
> +    private final Long questionId;
이것도 과합니다.

2021-03-17 15:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    @Column(nullable = false)
primitive type이라 애초에 `null` 이 들어올 수 없는 구조입니다.
default 값을 지정해주는 것이 더 자연스러운 방식 같긴 합니다.

2021-03-18 08:41 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/model/Answer.java
> +    @Column(nullable = false)
이 부분 `@Column(columnDefinition = "boolean default false")`로 수정했습니다.

2021-03-18 08:41 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        getUserFromSession(session);
getUserFromSession에서 세션이 없다면 로그인 페이지로 리다이렉트가 되고, 있다면 그냥 질문하기 페이지를 보여주면 되어서 따로 사용하진 않았습니다.

2021-03-18 08:53 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
위에 두 코멘까지 `CurrentPasswordNotMatchException`에 대해 지적을 해주셔서 여기에 하나로 말씀드리겠습니다.
예외 사용에 있어서 책임과 역할을 나누거나 정의할 때 생각해야 할 부분을 잘 몰라서 리뷰어님을 믿고 일단 다 만들었습니다!! 해당 부분 지적해주셔서 감사합니다. 말씀해주신대로 `CurrentPasswordNotMatchException`은 삭제를 했습니다. 그랬더니 `UserController`에 `updateProfile` 메소드에서 에러 메세지를 출력해줬는데 이렇게 처리하면 될까요??

그리고 밑에서 말씀해주신 `WriterOfAnswerListNotMatchException`도 삭제를 했습니다. 보니까 딱히 `redirect`를 해주는 것도 아니고 에러 메세지를 사용하지도 않아서 삭제했습니다.

그리고 이 질문은 꼭 답을 해주셨으면 좋겠는데 현재 남아 있는 예외들이 7가지가 있습니다.

1. db에서 User가 검색이 안될 때
2. db에서 Question이 검색이 안될 때
3. db에서 Answer가 검색이 안될 때
4. 중복 된 userId로 회원가입 요청할 때
5. 로그인 요청 시 아이디나 비밀번호가 다를 때
6. 유저의 세션이 없을 때
7. 유저가 세션이 있지만 다른 유저의 정보를 변경하려 할 때

브라이언이 이 부분을 보셨을 때 굳이 예외로 만들지 않아도 될 것 같거나 `CurrentPasswordNotMatchException`처럼 예외로 접근하긴 좀 애매한 것들이 있을까요?? 의견 주시면 감사하겠습니다!!

2021-03-18 08:55 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/exception/WriterOfAnswerListNotMatchException.java
> +    private final Long questionId;
`WriterOfAnswerListNotMatchException`도 딱히 역할이 맞는 것 같지않아 삭제했습니다.

2021-03-19 03:44 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/WriterOfAnswerListNotMatchException.java
> +    private final Long questionId;
`Exception` 자체가 과하다는 것이 아니라 `questionId` 필드를 말씀드린 부분입니다. ㅠㅠ
`Exception` 자체는 나쁘지 않습니다.

2021-03-19 03:47 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
@eNoLJ 우선 제가 코멘트를 남겨드릴때에 라인 코멘트를 즐겨 사용하는데요, 그게 아마 범위가 잘 전달이 안되는 것 같습니다.
익셉션 자체를 삭제하는 것이 아니라 익셉션들이 갖는 인스턴스 변수들이 과하다는 피드백을 드린 부분입니다. ㅠㅠ 
우선 제가 혼동되게 전달한 부분 무한한 사과의 말씀을 드립니다. 

우선 1~3번은 하나의 예외로 묶어서 처리하면 그만일 것 같고, 5번은 제가 보기엔 예외가 아닙니다. 
그리고 개인적인 생각으론 6, 7번도 하나의 예외로 처리해서 정보를 좀 숨겨야 한다고 생각합니다. 보안에 관한 예외는 세세한 것도 좋지만 사용자에게 너무 많은 정보를 노출하지 않는 것도 중요할 겁니다. 인터넷을 하시다보면 "ID나 패스워드가 틀립니다" 라는 불친절한 경고문을 많이 보셨을 거에요. 둘 중 뭐가 틀렸는지 알려줘도 되는데요. 

그래서 제가 볼 땐 1~7번의 상황에 대해선 두 가지 정도의 예외를 뽑아낼 수 있을 것 같네요. 그치만 어떤 예외로 뽑아내야 하는지는 말씀드리지 않겠습니다. ㅎㅎ 한번 생각해보시고 다시 review request 해주세요!

2021-03-19 15:48 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
오옹 자세한 피드백 감사합니다!! 일단 브라이언 말 듣고 낸 결과를 말씀드리면
1. UserNotFoundException
2. QuestionNotFoundException
3. AnswerNotFoundException
-> NotFoundException
피드백 주신대로 1~3번은 묶었습니다. 이름은 따로 생각나는게 없어서 NotFoundException이라 지었습니다.

1. UserNotLoginException
2. IllegalUserAccessException
-> UserSessionException
이것도 피드백 주신대로 6~7번을 묶었습니다. 둘다 session에 관련되어 있어서 UserSessionException이라 지었어요!! 메세지는 "접근권한이 없는 사용자입니다."라는 메세지를 보여줍니다.

1. DuplicateUserIdFoundException
2. IdOrPasswordNotMatchException
3. CurrentPasswordNotMatchException
-> UserAccountException
이 부분은 고민을 좀 많이 했는데 먼가 좀 애매한 느낌인데 결과적으로 유저 계정에 관련되었다 생각해서 UserAccountException이라 지었고 메세지는 아무리 생각해도 개별적으로 내려줄 필요성이 느껴져서 매개변수로 받았습니다.
`그리고 제일 중요한 부분인데 얘넨 하나의 예외로 묶었지만 다 개별적으로 보여주는 view가 달라서 이 부분을 어떻게 처리 하지 생각하다가 도저히 생각이 안나서 setAttribute로 path를 미리 내려줘서 처리하도록 구현했어요. 이런 용도로 setAttribute를 사용하는게 아닌 것 같지만 생각나는 방법이 없었습니다.
그래서 여쭤보고 싶은데 exception에 exception 외의 정보를 담지 말라 하셨을 때 염두에 두신 방법이 있을까요?? 처음 시도해 봤던 건 exception을 통해서가 아닌 예외가 발생했을 때 ExceptionHandler로 바로 값을 전달하는 방법을 찾아봤는데 없는 것 같더라구요?? 제가 못찾는 걸수도 있지만ㅠㅠ 그리고 말씀해주신 헬퍼 객체를 만들라는 말도 만들려면 service 단에서 만들어야할텐데 만들어도 ExceptionHandler로 넘겨 줄 방법이 생각이 안납니다. 이 부분 먼가 해주실 말씀이 있다면 꼭 좀 듣고 싶어요!!`

WriterOfAnswerListNotMatchException -> 삭제
얘는 아무리 생각해도 그냥 일치하는지 안하는지 결과만 알려주면 될 것 같아서 삭제하고 결과에 따라 view를 보여주도록 했습니다. 그리고 ExceptionHandler에서도 하는 일이라고는 redirect뿐이라 적합하지 않은 느낌이였습니다.

그럼 피드백 간절히 기다리고 있겠습니다!!
잘 부탁드려요!!

2021-03-20 01:02 UTC, wheejuni commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
@eNoLJ 예외를 묶으라고 한 건 예외 안에서 각기 다른 분기처리가 필요하다면 _예외 없이_ 구현하는 방법을 고민하시라고 제시해본 것입니다.
왜 꼭 예외로만 화면을 그려야 하나요? 예외 없이 화면을 만들 방법은 없나요? 
그리고 무조건 `Exception` 외의 정보를 담지 말라고 말씀드린 것이 아닙니다. ㅠㅠ `User` 나 `id` 같은 것을 두는 건 너무 과하다고 말씀드린 부분입니다. 메세지는 당연히 담아도 되고 HTTP status code에 대응되는 `ExceptionCode` 같은 것도 만들어서 쓰셔도 됩니다. 

모든 로직을 `ExceptionHandler` 에서만 처리하려고 하지 마세요. `Service` 에서 `Controller` 로 넘어가는 응답 객체에서 분기 처리를 만들 수도 있습니다. _응답 객체_ 를 어떻게 설계하면 좋을지도 고민해 보시고요.

2021-03-20 01:07 UTC, wheejuni commented
@eNoLJ 미션 진행이 다소 늦어지는 것 같아서 일단 이 PR은 머지하고 다음 미션에서 계속 고민해주세요!

2021-03-20 01:07 UTC, merged

2021-03-20 06:35 UTC, eNoLJ commented on src/main/java/com/codessquad/qna/exception/GlobalExceptionHandler.java
> +        model.addAttribute("user", e.getUser());
@wheejuni 아하 그렇게 말씀해주시니 좀 더 생각해볼 거리가 생긴것 같습니다. 좀 더 고민해보고 다음 미션에 수정하도록 하겠습니다!!
이번 리뷰도 도움이 많이 되었습니다. 감사합니다.