[Cooper]미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #78
Opened 2021-03-16 05:59 UTC by pbg0205

코드스쿼드2021 백엔드 과정의 Cooper 입니다.
미션3에 관한 요구사항을 완료하여 PR 보냅니다!
주요 변경사항은 하단에 기입하였습니다.
부족한 부분이나 아쉬운 부분에 대해 거침없는 피드백은 환영입니다!
리뷰해주시는데 시간내어주셔서 감사합니다👏

🌏 배포 사이트 : https://cooper-boot-qna.herokuapp.com/
1️⃣ Login 기능 추가
- 로그인 상태를 유지하기 위해 HttpSession을 이용해 session을 등록합니다.
- 로그인 유저임을 확인할 경우, getAttribute(session)을 이용해서 로그인 여부를 확인합니다.

2️⃣ 질문 목록 추가, 수정, 삭제 기능
- 로그인 상태를 확인하기 위해 HttpSession의 getUserFromSession메서드를 사용해 해당 세션의 User정보를 확인합니다.
-  equals 재정의를 통해 로그인 아이디와 작성자의 동등성을 비교하고 일치할 경우, 해당 글을 수정, 삭제가 가능하도록 하였습니다.
 - 기존의 String Writer를 User class와 맵핑하여 객체와의 연관성을 생성하였습니다.

3️⃣ 댓글 기능 추가
- 해당 댓글의 목록들은 foreign key인 question을 이용해 해당 리스트를 반환합니다.
- 해당 댓글 작성자 한해 삭제할 수 있도록 기능을 구현하였습니다.

4️⃣ 리팩토링 및 예외(ExceptionHandler)
- 로그인 관련 중복코드 HttpSessionUtils를 선언해 별도 클래스 분리
- ExceptionHandler와 ControllerAdvice를 이용한 공통 예외 처리 구현
- orElseThrow를 이용해 Optional 제거
❓질문
1. 로그인 실패와 동일 인물 확인하는 기능을 예외를 별도로 생성하는 법이 좀 더 효율적인가요??
- 값이 다를 경우 매칭이 안되기 때문에 이 부분도 exception으로 처리해주어야 하는 고민이 들었지만 값을 비교하는 것이지 예외의 경우로 들 수 없을 것 같아 별도로 구현하지는 않았습니다.!

2. 참조 관계에 있는 값의 멤버들을 통해서도 repository에서 가능한가요?
- answerRepository에서 Question의 아이디를 이용하는 방법을 시도해보려 했지만 실패하여 Question 인스턴스를 통해 값을 맵핑하는 방법을 선택하였습니다. 혹시 Question 내부 객체의 멤버를 사용해서 맵핑이 가능하다면 간단한 힌트 정도만 말씀해주시면 감사하겠습니다

2021-03-18 03:50 UTC, wheejuni requested changes
3단계까지 진행하시느라 수고 많으셨습니다! 💯 
크게 무리 없이 구현해주신 듯 합니다.
질문에 대해 답변도 드리면요...

1. Cooper가 생각하시는 예외는 뭔가요? _[예외란 무엇인가...](http://news.khan.co.kr/kh_news/khan_art_view.html?art_id=201809211922005)_
제가 생각하는 예외란, 로직의 수행에 있어 개발자가 설계하지 않은 변수가 발생한 순간 을 말합니다. 
사용자가 로그인을 시도하다가 패스워드를 틀려 로그인이 안 되는 상황.... Cooper가 설계하지 않은 변수인가요? 제가 로그인을 구현하는 개발자라면 그런 플로우는 당연히 설계할 것 같습니다. 감이 오시는지요? 

2. 네 가능하고 권장되는 방법입니다. `spring data query method` 정도로 검색해보세요. 레퍼런스가 아주 많이 나올 겁니다. 

감사합니다!

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        //registry.addViewController("/questions/form").setViewName("qna/form");
주석처리보다는 그때그때 지우는 방법을 선택해 주세요.

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/user/HttpSessionUtils.java
> +                false : true;
간단하게 리팩토링이 가능할 것 같아요.

```suggestion
        return session.getAttribute(USER_SESSION_KEY) != null

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
이것은 `CrudRepository` 에 [이미 있는 것 같네요.](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findAll--)

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer findBy(Long id) {
메소드명에 무언가가 빠진 것 같네요? 무엇을 통한 `By` 인가요?

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public void createAnswer(Answer answer) {
`CrudRepository.save()` 가 리턴을 갖는다는 건 이미 알고계실 것 같은데요,
의외로 이 리턴 객체가 유용한 경우가 많습니다. 레포지토리에 저장을 한 경우, `void` 로 끝내지 마시고 이 객체를 다시 돌려주는 구현을 추천합니다.

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    public UserService(UserRepository userRepository) {
이 사이엔 한 줄 띄우시는 것이 좋겠습니다.

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        return String.format("redirect:/questions/%d", questionId);
그냥 덧셈 연산을 하는 쪽이 조금 더 가독성이 좋게 느껴지는게 어떻게 생각하시나요?

```suggestion
        return "redirect:/questions/" + questionId;

2021-03-18 03:50 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/CommonExceptionHandler.java
> +    @ExceptionHandler(UserNotFoundException.class)
여기도 한 줄 띄워 주세요.

2021-03-18 06:27 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/user/HttpSessionUtils.java
> +                false : true;
훨씬 깔끔해지네요. 감사합니다👍

2021-03-18 06:30 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
말씀해주신 부분 제거하고 Iterable으로 리턴 타입을 변경하였습니다
코멘트 감사합니다ㅎㅎ

2021-03-18 07:19 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public void createAnswer(Answer answer) {
넵! 객체를 반환하는 방식으로 구현하겠습니다!

2021-03-18 07:21 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        return String.format("redirect:/questions/%d", questionId);
더하는게 눈에 잘 들어오는거 같습니다😄
말씀해주신 방식으로 변경하겠습니다ㅎㅎ

2021-03-18 07:51 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/config/MvcConfig.java
> +        //registry.addViewController("/questions/form").setViewName("qna/form");
넵! 숙지하겠습니다!!

2021-03-18 07:52 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    public Answer findBy(Long id) {
뒤에 내용이 빠졌네요. 이 부분 바로 수정하도록 하겠습니다!

2021-03-18 08:20 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
리턴 타입이 로타입일 경우, 컴파일 에러가 발생할 수도 있다는 내용을 책에서 읽은 기억이 있어 제네릭 형태로 선언하였는데 확신이 없네요ㅠ Iterable을 사용하는 것이 적합할까요??

2021-03-18 08:37 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
회원 등록하는 부분에서 기존 회원 아이디와 중복 아이디를 확인하기 위해 findByUserId(String userId)를 구현해보았습니다. 해당 메서드를 대체할만 방법도 모색해보았는데 마땅히 적합한 방법이 잘 안떠오르네요ㅠ 혹시 이 부분에서 괜찮은 방법에 대해 말씀 부탁드려요 될까요?

2021-03-18 08:43 UTC, pbg0205 commented
리뷰해주셔서 감사합니다!👏 👏
디테일한 부분에서 미숙한 면이 있네요ㅠㅠ
말씀해주신 부분에 대해 수정 진행해보았습니다.
한 부분은 확신이 없어 의견을 좀 구하고자 댓글 남겨두었습니다.
확인 부탁 드립니다!!😄

2021-03-19 03:42 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
죄송해요. 제가 `id` 와 `userId` 를 혼동했습니다. ㅠㅠ 무시해주세요

2021-03-19 03:48 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/user/UserRepository.java
> +    List<User> findAll();
죄송합니다. 제가 `id` 와 `userId` 를 혼동한 것 같아요. ㅠㅠ

2021-03-19 03:49 UTC, wheejuni approved these changes
수고하셨습니다. 👍

2021-03-19 03:49 UTC, merged

2021-03-26 08:43 UTC, kjk402 commented
쿠퍼 코드 보고 도움 많이 됐습니다. 감사합니다.