[아이작]미션2: 데이터베이스 활용
codesquad-members-2021/spring-boot-qna pull request #79
Opened 2021-03-16 07:45 UTC by isaac56

안녕하세요 아이작입니다.

미션2의 요구사항대로 h2 database를 사용하여 데이터를 관리하도록 구현하였습니다.
추가:
 - UserRepository: CrudRepository를 상속하여 User Entity에 해당하는 테이블에 접근하는 Repository입니다.
 - QuestionRepository: CrudRepository를 상속하여 Question Entity에 해당하는 테이블에 접근하는 Repository입니다.

많이 부족한 코드 리뷰 잘 부탁드립니다.
감사합니다.

2021-03-16 09:34 UTC, sonypark requested changes
안녕하세요 아이작, 리뷰어 소니 입니다.😊
heroku 링크가 없어서 기능 동작 확인을 하지 못했어요..
링크 첨부해주시면 감사하겠습니다~

개선할 부분에 대해 몇가지 코멘트 남겼는데 확인 후 반영 부탁드립니다!

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
👍

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    public String userProfile(@PathVariable String userId, Model model) {
메서드명에 user 키워드는 빼도 될 것 같네요

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      }
잘못된 userId가 들어오면 회원목록으로 리다이렉트 해주는게 맞을까요??
사용자 입장에서는 왜 리다이렉트가 되었는지 알 수 없을 것 같아서요.
예외를 던져주는 게 좋을 것 같아요~

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/entity/Question.java
> +
이 메서드는 왜 필요한가요~?

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    public Optional<User> findByUserId(String userId);
userId는 고유한 값인가요? 중복된 아이디는 없나요?
특정 user를 조회하는게 목적이라면 user는 PK로 조회하는게 좋을 것 같네요.

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
반환값을 Iterable로 하신 이유가 있나요?

[Spring-Data JPA CrudRepository returns Iterable, is it OK to cast this to List?](https://stackoverflow.com/questions/34702252/spring-data-jpa-crudrepository-returns-iterable-is-it-ok-to-cast-this-to-list)

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +}
존재하지 않는 id인 경우는 어떻게 되나요?
Optional을 리턴하기 보다 예외 처리 로직을 구현해보세요~

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
여기도 Iterable

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
Optional을 어떻게 처리하면 좋을까요?

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/UserController.java
>              model.addAttribute("user", user.get());
Optional.get() 메서드는 사용하지 않는걸 권장합니다~ 왜 그런지 이유도 찾아보시면 좋겠네요!

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        question.setWriteDateTime(LocalDateTime.now());
setter로 주입해주기 보단 Question 생성자 내에서 초기화 해주는 건 어떨까요?

2021-03-16 09:34 UTC, sonypark commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass().getName());
현재 logger는 사용되고 있지 않는 것 같네요. 필요할때 선언해서 사용해주세요~

2021-03-17 02:26 UTC, isaac56 commented on src/main/java/com/codessquad/qna/entity/Question.java
> +
spring에서 request로 온 객체를 setter로 생성해준다고 알고 있었습니다.
생성자를 통해서도 생성할 수 있으니까 수정할 필요가 없는 값의 setter는 제거하겠습니다.

2021-03-17 03:05 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/QuestionService.java
> +    }
딱히 이유는 없었고 CrudRepository에서 findAll 메소드가 반환하는 형식을 따라했습니다.
말씀해주신 자료 읽어보고 List로 바꿔보겠습니다!

2021-03-17 03:35 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>              model.addAttribute("user", user.get());
get을 사용할 경우 Optional이 가진 값이 Null일 경우 NPE를 발생할 수 있고,
isPresent()로 체크한 후 get을 사용하면 기존 null체크 하던 것과 똑같아 Optional 쓰는 이점이 없네요.

orElseThrow로 Exception을 처리해주는 방식으로 바꿔보려고 합니다.

2021-03-17 03:36 UTC, isaac56 commented on src/main/java/com/codessquad/qna/service/UserService.java
> +    }
optional의 값이 null일 경우 orElseThrow로 Exception을 발생시키고, ExceptionHandler를 만들어서 처리해려고 합니다

2021-03-17 03:40 UTC, isaac56 commented on src/main/java/com/codessquad/qna/controller/UserController.java
>      }
spring에서 Exception 핸들링 해주는게 어려워보여서 미루고 있었는데, 이참에 한번 시도해보겠습니다 감사합니다

2021-03-17 03:41 UTC, isaac56 commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    public Optional<User> findByUserId(String userId);
현재는 로그인 기능이 없어서 PK가 아닌 userId로 조회하고 있습니다.
말씀해주신 내용 참고하여 다음 스텝에서 구현해보겠습니다🙏

2021-03-17 05:17 UTC, isaac56 commented
안녕하세요 소니, 좋은 코드 리뷰 항상 감사드립니다.
말씀하신 내용 제가 이해한 만큼 수정하고 코멘트 남겨놨습니다.

스프링을 잘 모르는 상태에서 맨땅에 헤딩으로 진행하다 보니 많이 부족하네요😂
심각한 문제가 아니라면 다음 미션을 진행하며 배우고 싶습니다.(다른 분들보다 미션이 많이 늦은 상태네요 ㅠㅠ)
잘 부탁드려요🙏 ㅠㅠ

2021-03-17 15:29 UTC, sonypark commented on src/main/java/com/codessquad/qna/repository/GenericRepository.java
> +}
"abstract" repository까지 만들 필요는 없었는데..ㅎㅎ

2021-03-17 15:35 UTC, sonypark approved these changes
아이작 피드백 반영하신 코드 잘 봤습니다.
코멘트 남긴거 확인하시고 다음 미션 구현하실 때 고려해주세요~
다음 미션 진행해주세요 수고하셨습니다.👍

++ repository에서 엔티티를 조회할때는 특정 검색 조건을 사용해야하는 경우가 아니라면 PK를 이용해 조회하는게 성능이나 일관성 측면에서도 더 좋습니다.

2021-03-17 15:35 UTC, sonypark commented on src/main/java/com/codessquad/qna/entity/User.java
>      private String userId;
userId가 중복될 경우 예외처리를 해주는 로직이 있어야할 것 같네요

2021-03-18 15:37 UTC, merged