[ coco ] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #8
Opened 2021-03-03 10:24 UTC by ChoiGiSung

안녕하세요 백엔드반의 coco라고 합니다.

배포사이트  
https://coco-springboot-qna.herokuapp.com/  

이번 미션은 test를 진행하지 않았지만 잘 부탁드립니다.

2021-03-04 09:18 UTC, SANGCO requested changes
coco님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @PostMapping("/question")
`@PostMapping("/question")` 보다는 `@PostMapping("/questions")` 가 좋을거 같습니다.

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/user")
요구사항에 있는
`각 기능에 따른 url과 메소드 convention`
항목을 보고 전체적으로 url을 다시 수정해 봅시다.
예를 들어서 `@PostMapping("/users")`면 Create a new User

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
`checkPassword()` 이 메서드를 password를 가지고 있는 User 객체로 옮기는건 어떨까요?

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setWriteTime(LocalDateTime writeTime) {
Question 클래스에 안쓰는 setter가 있다면 제거해 봅시다.

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/repository/QuestionRepository.java
> +        question.setId((long) (questions.size() + 1));
`questions.size() + 1`
나중에 넣고 지우고 하면 이런식으로 구현을 하면 문제가 생기겠네요.
그런데 이부분도 다음 미션에서 데이터베이스 사용하면서 수정하실거 같기는 하네요~

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +        return null;
`.orElse(null);` 등 null을 반환하는 부분이 있느데
미션을 진행해 가면서 이부분도 수정이 되어야 겠네요.
일단 언급만 드립니다.

2021-03-04 09:18 UTC, SANGCO commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +    }
위에서 언급했던거 처럼 User 클래스로 옮겨 봅시다.

2021-03-05 02:16 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +@RequestMapping("/user")
수정했습니다! convention을 쓱 보고 넘어갔는데 중요한 거였네요.

2021-03-05 02:27 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        }
repository에는 db관련 코드만 있는 게 맞겠네요. 수정했습니다!

2021-03-05 02:27 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setWriteTime(LocalDateTime writeTime) {
수정했습니다!

2021-03-05 02:29 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/repository/UserRepository.java
> +        return null;
이 부분이 고민이었습니다. 찾는 값이 없어서 null인데 null을 줄지 예외를 줄지 아님 옵셔널을 공부해서 적용할지 하다가 null을 줘버렸습니다.

2021-03-05 07:39 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setWriteTime(LocalDateTime writeTime) {
setter를 제거하니 form에서 내용이 안보이는 문제가 있어서 일단 원복 시켰습니다.
후에 DTO를 사용하던지 해서 교체해보겠습니다.

2021-03-05 11:23 UTC, SANGCO approved these changes
고생 하셨습니다~

2021-03-05 11:23 UTC, SANGCO commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/update")
`@PostMapping("/{userId})`
이렇게 할 수 있지 않을까요~

2021-03-05 12:03 UTC, ChoiGiSung commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +    @PostMapping("/update")
맞습니다. 근데 저는 hidden으로 넘겨 주고 싶어서 hidden을 사용했습니다.

2021-03-08 04:27 UTC, merged