[Pyro] 미션 3, 미션 4 동시 진행
codesquad-members-2021/spring-boot-qna pull request #80
Opened 2021-03-17 03:45 UTC by ghojeong

https://ghojeong-spring-boot-qna.herokuapp.com/

[미션2에서 받았던 피드백](https://github.com/codesquad-members-2021/spring-boot-qna/pull/46#discussion_r592125542) 에서, Question 안의 writer 를 String 타입이 아닌 User 도메인 클래스 타입으로 하기를 요구받았습니다.

미션3의 내용만으로는 도저히 위의 피드백 요구사항을 구현하기 어려워서, 미션 4를 같이 공부하여 피드백을 반영할 수 있도록 했습니다.
세션을 통한 authorization 체크를 하는 부분을 AOP 로 분리하고 싶은데, 혼자서는 어떻게 해야할지 학습이나 구현 모두 어려워서 장벽이 막혔습니다.
혹시 좋은 학습 자료나, 따라할 만한 예시 코드가 있으면 공유해주시면 감사하겠습니다.
혹은 코드 리뷰를 통해, AOP 를 위해 설계를 어떻게 변경하면 좋을지 피드백을 해주시면 감사하겠습니다.

[Transactional 은 너무 과하다는 피드백](https://github.com/codesquad-members-2021/spring-boot-qna/pull/46#discussion_r592115133) 을 미션 2에서 받아서, 이번 미션의 CRUD 작업에서도 일부러 Transactional 을 배제했습니다.

2021-03-17 03:49 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        questionRepository.save(question); // HELP: 이유를 모르겠지만 dirty checking 이 동작하지 않는다.
이유를 모르겠지만, dirty checking 이 동작하지 않아서,
save 를 하였는데, 혹시 이런 문제는 어떻게 디버깅을 해야할지 조언주시면 감사하겠습니다.

2021-03-17 03:49 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
>      }
HttpSessionUtils.checkAuthorization 부분을 AOP 로 분리해내고 싶은데, 어떻게 하면 좋을지 조언주시면 감사하겠습니다.

2021-03-17 15:10 UTC, sanhee commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        questionRepository.save(question); // HELP: 이유를 모르겠지만 dirty checking 이 동작하지 않는다.
이부분 저도 그렇던데 궁금하네요!

2021-03-18 02:18 UTC, ghojeong commented on src/main/java/com/codessquad/qna/user/ui/UserController.java
> +        session.removeAttribute(USER_SESSION_KEY);
sessionId 로 서버의 세션을 통째로 날릴 수 있는 방법이 있나요?
포비님 영상에서는 sessionUser 키로 매핑된 값만 removeAttribute 해서요.
로그아웃 때는 특정 Attribute 만 삭제하는게 아니라 세션 자체를 삭제하고 싶습니다.

2021-03-18 13:28 UTC, ksundong commented
회원정보 수정하려니 500에러가 발생하네요. 확인해주세용~

2021-03-18 13:33 UTC, ksundong commented
제가 디버깅 해보려고 애플리케이션 띄웠는데 로그가 하나도 안찍혀서 당황했네요. ㅋㅋ

2021-03-18 13:47 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        questionRepository.save(question); // HELP: 이유를 모르겠지만 dirty checking 이 동작하지 않는다.
`@Transactional`을 붙여보시구요.
이런건 기술적인 문제라서 기술을 학습해야하는데, JPA 공부하긴 너무 이른 것 같아서 ㅎㅎ.. 그냥 `save` 해주시면 될 것 같아요.

2021-03-18 13:50 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
>      }
@honux77 AOP 수업을 하셨나용?
전 사실 호눅스 수업 듣고 실습 해보고 익힌 케이스라서
수업 잘 들으시면 될 것 같네요.

2021-03-18 13:53 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
>      }
아직 안하셨습니다.

2021-03-18 13:54 UTC, ghojeong commented
@ksundong 
> 회원정보 수정하려니 500에러가 발생하네요. 확인해주세용~

5b00abd 커밋에서 세션에서 비밀번호 관련된 정보를 저장하지 않으려다가 Class 타입 캐스팅이 실패해서 발생한 문제였습니다.
수정했습니다.

2021-03-18 13:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
>      }
AspectJ를 한 번 학습해보세요.
토비의 스프링 1권에서도 나왔어요. 한 번 보세요 ㅎㅎ

2021-03-18 14:03 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/ui/UserController.java
> +        session.removeAttribute(USER_SESSION_KEY);
`session.invalidate()`를 사용해주면 되지 않을까 싶네요.

2021-03-18 14:07 UTC, ghojeong commented on src/main/java/com/codessquad/qna/user/ui/UserController.java
> +        session.removeAttribute(USER_SESSION_KEY);
호오! invalidate 를 사용하면, [세션을 무효화](http://blog.naver.com/zino1187/110025698379) 할수 있군요!
removeAttribute 와 함께 invalidate 도 같이 할 수 있도록 하겠습니다.

2021-03-18 14:56 UTC, ksundong requested changes
안녕하세요! Pyro!! 리뷰어 Dion입니다!
리뷰를 하는데 시간이 좀 걸렸네요. 미션별로 피드백 드릴 내용이 다르다보니 & 다양한 리뷰어들의 관점을 받아들이기 위해 다음 부터는 나눠서 해주세요~
전반적으로 많은 고민이 느껴져서 좋았던 것 같아요.
기타 피드백으로는, spring의 validation starter를 넣으시면 더 좋을 것 같네요.

먼저 대부분은 정말 괜찮은 코드였는데, 개선할 점이 조금 남아있는 것 같아서 **변경 요청** 드립니다.

## 애플리케이션 관련 피드백

- 빈 정보를 넣어도 유저가 생성됩니다. 혹시 validation이 되지않는건 아닐까요?
- 따로 에러 페이지를 만들어주는게 좋을 것 같네요.
  ![image](https://user-images.githubusercontent.com/38597469/111646362-ec630c80-8844-11eb-8927-df58c1c70b79.png)
- 아이디 비밀번호 다르다고 나오는건 페이지에서는 둘 다 함께 나오고, 로그만 다르게 찍는군요? 👍
- 다른 사람의 댓글이 있을 때, 삭제되지 않는 것이 구현되어있지 않네요.

미션 3, 4를 동시에 진행해주시느라 고생하셨습니다.
피드백 반영하시면서 궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으면 언제든 코멘트 남겨주세요.
고생하셨습니다~

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/application/AnswerService.java
> +    public AnswerService(AnswerRepository answerRepository) {
생성자 인젝션 좋네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/application/AnswerService.java
> +    public AnswerResponse saveAnswer(AnswerRequest answerRequest, Question question, User writer) {
저는 동어반복은 지양하는 편이라 `save` 정도로 해도 괜찮은 것 같네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/application/AnswerService.java
> +                .orElseThrow(() -> new AnswerNotFoundException(String.format("존재하지 않는 답변입니다. id: %d", id)));
String은 Exception 내부에 넣어놓고, id만 전달하는 방향으로 수정하면 어떨까 싶어요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +public class Answer extends BaseTimeEntity {
와 벌써 이런 고급기술을 쓰시다니

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +    @Lob
Lob을 써주면 DB에선 어떤 형태로 저장될까요? 한 번 고민해보세요. ㅎㅎ

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +    protected Answer() {}
기본 생성자 사용 좋습니다.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +}
setter 없는 것도 아주 좋네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
요구사항에는 `CrudRepository`를 사용하라고 되어있었는데요, 둘이 어떤 차이를 가지는지는 공부해보시면 좋을 것 같네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +    @NotBlank(message = "answer contents is blank")
validation까지... 👍

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +    protected AnswerRequest() {}
이 기본생성자는 왜 추가해주셨나용?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +
`getter`가 사용되는 곳이 있었나요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +    private String contents;
`DTO`를 만들어주셨는데, 내부에는 Entity를 담고있는건 별로 좋지 못한 형태라고 생각되네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +
DateTime으로 변경해주세요~

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +    public static AnswerResponse of(Answer answer) {
저도 회사에서 리뷰받았던 건데 from이 일반적인 네이밍이라고 합니다 ㅎㅎ

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +}
저같은 경우에는 `getter`는 `getter`로만 쓰고, 별도의 형태가 필요한 경우에는 다른 `getter`를 정의해주는 편이에요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerController.java
> +        return String.format("redirect:/questions/%d", questionId);
그냥 + 연산 해주시는게 더 나은 것 같아요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerController.java
> +        Question question = questionService.getQuestionFromRepository(questionId);
어디서 들고오는지 `Controller`가 알고있을 필요가 있을까요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerController.java
> +        Question question = questionService.getQuestionFromRepository(questionId);
그래도 Repository를 직접 거치지 않고 Service를 이용하신건 잘하신 것 같아요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +    private final LoggerRepository loggerRepository = new LoggerRepository(AnswerExceptionHandler.class);
흠... 어떤 이유에서 이게 추가되었는지는 궁금하네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +        loggerRepository.saveError(e);
예외를 저장하는건가요? 뭔가 신기하네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +        return ResponseEntity.notFound().build();
그냥 애노테이션으로 Status를 지정해주셔도 됩니다.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/DateUtils.java
> +        return localDateTime.format(DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm"));
Formatter를 상수로 추출해주는건 어떤가요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/HomeController.java
> +        return "redirect:/questions";
👍

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/HttpSessionUtils.java
> +    private HttpSessionUtils() {}
생성자가 맨 위에 위치하는건 컨벤션에 어긋나지 않나요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/HttpSessionUtils.java
> +                .matchId(id);
그냥 한 줄로 작성해주셔도 될 것 같아요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/LoggerRepository.java
> +public class LoggerRepository {
이건 나중에 학습하셔도 되지만, 일반적으로 매 번 로그를 저장하기 보다는 로그를 파일로 떨궈서 한 번에 넣는 방식이 성능에 영향을 덜 줍니다.
슬랙과 연동하는 것은 참신하네요.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/LoggerRepository.java
> +}
나중에는 진짜 `save` 되는건가요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +        for (Question question : questionRepository.findAllByDeleted(false)) {
false만 사용할 것이라면 그냥 메서드에 false를 드러내줘도 좋을 것 같아요~

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
https://woowacourse.github.io/javable/post/2020-06-02-law-of-demeter
요거에 대해서 한 번 학습해보세요~

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    @Where(clause = "deleted = false")
👍

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    @Column
이 애노테이션은 왜 붙여주셨나요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
이건 너무 기네요~

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/ui/QuestionController.java
>      @PostMapping("create")
RESTful하게 url을 설계한다면 동사는 가능한 한 배제해주세요.
여기에선 `create`는 굳이 필요없습니다.

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +        }
이건 사용성과 관련된 문젠데요. 요즘 대부분의 사이트는 id 또는 password가 잘못되었습니다.로 메시지를 출력합니다.
왜일까요?

2021-03-18 14:56 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/ui/UserController.java
> +        session.setAttribute(USER_SESSION_KEY, userService.login(userId, password));
이것도 Utiltiy로 추출해보세요~

2021-03-18 14:56 UTC, ksundong commented on src/main/resources/application.properties
> +# NOTE: 레벨을 debug 로 하니깐 너무 많이 나온다. 개발하는 패키지만 debug 로 하자.
저는 개발시에는 모든 로그 debug로 설정해 다 확인하는 편입니다.

2021-03-18 14:56 UTC, ksundong commented on src/test/java/com/codessquad/qna/question/QuestionAcceptanceTest.java
>  public class QuestionAcceptanceTest extends AcceptanceTest {
ATDD인가요? 저는 학습해 본 적이 없어서 제가 배워가야겠네요 ㅋㅋ

2021-03-18 14:56 UTC, ksundong commented on src/test/java/com/codessquad/qna/question/QuestionAcceptanceTest.java
> +                .when().get(QUESTION_PATH + "/{id}", 100)
100이 의미하는바가 뭔가요? 존재하지 않는 ID?

2021-03-18 15:10 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/LoggerRepository.java
> +public class LoggerRepository {
그렇군요. 과거에 Express 를 이용한 백엔드 개발 시에, 모든 에러는 Web Hook 을 사용해 따로 로깅 서버로 알림을 보내라는 요구를 받았었습니다.
로깅 서버는 그렇게 전해받은 에러들을 다시 슬랙봇 혹은 텔레그램봇 등등과 연동시켜서, 장애 상황시에 새벽에도 개발자를 깨워서 야근을 하도록 하였구요.
그 당시에, 모든 에러 로깅 관련 작업은 LoggerRepository 라는 객체를 하도록 교육받았고, 깜빡하고 바닐라 자바스크립트의 Console.error 같은 걸로 로그를 남기면 엄청 혼났던 트라우마가 있어서, 습관적으로 저런 클래스를 만들어버렸네요.

다시보니깐 과거의 습관에 생각없이 의존하는 안좋은 군더더기 같습니다.
지금은 그런 연동을 할 필요도 없고, 연동외에도 해야할 작업들이 많으므로, LoggerRepository 클래스는 삭제하도록 하겠습니다.

2021-03-19 02:18 UTC, ghojeong commented on src/test/java/com/codessquad/qna/question/QuestionAcceptanceTest.java
> +                .when().get(QUESTION_PATH + "/{id}", 100)
존재하지 않는 임의의 ID 값을 넣은 건데, 헷갈릴 여지가 있군요.
이름있는 변수로 감싸서 의미를 명확하게 하겠습니다.

2021-03-19 02:46 UTC, ghojeong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +        }
exceptionMessage 는 실제 프론트 브라우저에게 전달되는 값이 아니라,
서버 로깅에 남는 값이므로 개발자가 편한 메시지로 하여도 괜찮을 것 같습니다.
프론트 브라우저에게 보내는 메시지는 ExceptionHandler 에서 ResponseEntity를 build 할 때 결정됩니다.

2021-03-19 02:48 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/HttpSessionUtils.java
> +    private HttpSessionUtils() {}
앗! 그렇네요. 제가 실수했습니다.

2021-03-19 02:49 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    @Column
딱히 필요가 없는 애노테이션이네요. 삭제하겠습니다.

2021-03-19 02:53 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +    protected AnswerRequest() {}
엇, 생각해보니 필요가 없군요 삭제하겠습니다.

2021-03-19 02:57 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +    protected AnswerRequest() {}
ATDD 를 위해 테스트 코드에서 Request dto 를 사용할 때,
기본 생성자가 정의되어 있지 않으면, 요청이 제대로 보내지지 않더군요.
왜 이런지에 대한 원인 파악을 못했는데, 그 전까지는 기본 생성자를 추가해 놓으려고 합니다.
사용하지 말라는 사소한 반항심으로 public 이 아닌 protected 접근자를 사용했습니다.

2021-03-19 02:59 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +
없지만 dto 이므로 미리 정의를 해두어서 나쁠 것은 없지 않을까 하고 생각했습니다.

2021-03-19 05:39 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/domain/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
<img width="727" alt="스크린샷 2021-03-19 오후 2 37 13" src="https://user-images.githubusercontent.com/38595650/111736162-a2b80780-88c0-11eb-8fdd-5f16bb02494b.png">

[CrudRepository vs JpaRepository](https://stackoverflow.com/questions/14014086/what-is-difference-between-crudrepository-and-jparepository-interfaces-in-spring)

JpaRepository 는 CrudRepository 의 하위 인터페이스로, CrudRepository 보다 더 많은 기능들이 있습니다.
나중에 페이지네이션 기능을 구현하려면 JpaRepository 가 더 편리하지 않을까 라는 생각에, JpaRepository 를 사용했습니다.
혹시, CrudRepository 를 사용해서 페이지네이션 기능을 밑바닥 부터 구현해보는게, 이번 교육과정의 목표 중 하나인가요?

2021-03-19 05:41 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
데메테르 여신님의 분노로 겨울이 오지 않도록 조심하겠습니다.

![983ed1e66268d991f69e3b29dbf23c51](https://user-images.githubusercontent.com/38595650/111736420-23770380-88c1-11eb-94ec-79b2ccbac747.jpeg)

2021-03-19 06:37 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +
잘 이해를 못했는데, 자바에 LocalDateTime 외에 DateTime 이라는 클래스가 존재하나요?
찾아도 검색이 잘 되지 않아서 도움을 요청합니다.
@ksungdong

2021-03-19 06:44 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +    @Lob
[LOB; Large OBject](https://www.baeldung.com/hibernate-lob) 를 사용하면,
CLOB(Character Large Object) 혹은 BLOB(Binary Large Object) 로 저장된다고 합니다.

h2-console 로 확인을 해보니 바이너리 데이터가 아니라, 텍스트의 형태로 저장되는 것을 확인했습니다.
<img width="670" alt="스크린샷 2021-03-19 오후 3 41 41" src="https://user-images.githubusercontent.com/38595650/111741319-a9974800-88c9-11eb-9720-eeb4550b6740.png">

포비님의 영상을 따라서 Lob 어노테이션을 사용했는데, 혹시 추가적으로 고려해야할 점이 있을까요?
말씀 주신 피드백에 따라 공부를 더 할 수 있었지만, 더 좋게 개선할 수 있는 점은 찾지 못해서요.

2021-03-19 06:56 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +        return ResponseEntity.notFound().build();
[ResponseStatus 어노테이션](https://www.baeldung.com/spring-response-status) 에 관해서 공부를 했는데,
AnswerNotFoundException 과, AnswerDeletedException 을 아래와 같은 형식으로 정의하라는 의도가 맞으신건가요?

```java
@ResponseStatus(code = HttpStatus.BAD_REQUEST)
class CustomException extends RuntimeException {}
```

2021-03-19 10:19 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/Answer.java
> +    @Lob
보통은 Lob에 대해서 검색해보면 Clob이나 MySQL의 Text, varchar까지 찾아볼 수 있던 것 같아요.
더 좋게 개선이라기 보다는, 이걸 토대로 여러가지를 학습할 수 있어서 제안드린 부분이에요.

2021-03-19 10:22 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
더 많은 기능이 있는 것도 맞는데, 동작 수행이 다른 부분이 존재합니다.
페이징이 필요한 시점이 오기 전까지는 CrudRepository를 사용해보는 것도 좋은 것 같아요~

2021-03-19 10:22 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/domain/AnswerRepository.java
> +public interface AnswerRepository extends JpaRepository<Answer, Long> {
바꾸실 필요는 없습니다!

2021-03-19 10:24 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +    protected AnswerRequest() {}
이것도 스프링의 마법중 하나 때문에 필요한 것이긴 한데요.
일단 넘어가는 것도 좋은 것 같아요 ㅎㅎ

2021-03-19 10:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +
저는 필요하지 않으면 안만드는 것이 좋다고 생각해요~
의견차가 있겠습니다만 ㅎㅎ필요할 때 만들어도 되거든요.

2021-03-19 10:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerResponse.java
> +
아 제가 너무 제 생각만 했군요.
변수명을 의미한 것이었습니다!
그리고 자바에는 LocalDateTime말고도 ZonedDateTime, OffsetDateTime이 존재하긴 합니다.

2021-03-19 10:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +        return ResponseEntity.notFound().build();
맞아요~
예외에도 붙여줄 수 있답니다 ㅋㅋ

2021-03-19 10:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/ui/AnswerExceptionHandler.java
> +        return ResponseEntity.notFound().build();
그리고 제가 의도한 것은 handAnswerNotFound에 붙여달라는 의미였어요!

2021-03-19 10:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/LoggerRepository.java
> +public class LoggerRepository {
오 경력자셨군요. 그런 니즈가 있었다면, 충분히 가능한 설계라고 생각됩니다.
필요한 시점에 만들어주셔도 좋을 것 같아요 ㅎㅎ

2021-03-19 10:29 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +    }
앗 추억의 만화네요 ㅎㅎ

2021-03-19 10:30 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +        }
넵 리뷰에서 관련내용 확인해서 남겼어요. ㅎㅎ

2021-03-19 10:31 UTC, ksundong commented
수정 다 되시면 리뷰요청 다시해주세요~

2021-03-19 12:08 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/dto/AnswerRequest.java
> +
넵 삭제하겠습니다! ㅎ

2021-03-19 12:26 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
[빌더 패턴](https://www.notion.so/02-eedfd1de61b7432daad7c539bc4392e6) 적용하겠습니다.

2021-03-19 13:29 UTC, ghojeong commented
> 따로 에러 페이지를 만들어주는게 좋을 것 같네요.

에러 페이지는 훗날의 프론트 개발자에게 맡기려 합니다. 🐷

2021-03-19 13:38 UTC, ghojeong commented
@ksundong 
최대한 머리를 쥐어 짜내서 피드백을 반영해보았습니다.
한번 더 리뷰 부탁드립니다.

> 미션별로 피드백 드릴 내용이 다르다보니 & 다양한 리뷰어들의 관점을 받아들이기 위해 다음 부터는 나눠서 해주세요~

안타깝지만, 미션을 진행할 수 있는 시간이 얼마 남지 않은 관계로, 5와 6도 동시에 진행을 하려고 합니다.

2021-03-19 14:39 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
앗 빌더 패턴의 문제가 아니라, 줄바꿈을 해달라는 의미였어요.

2021-03-19 14:40 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
그렇군요. 저는 꼼짝없이 이팩티브 자바 아이템 2 이야기를 하신건줄 알았어요

2021-03-19 14:40 UTC, ghojeong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
적용하느라 엄청 고생했는데 아쉽군요

2021-03-19 16:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/dto/QuestionResponse.java
> +    public QuestionResponse(Long id, User writer, String title, String contents, List<Answer> answers, LocalDateTime createdDate, LocalDateTime modifiedDate) {
뭐 빌더 패턴 공부해보시는 것도 좋다고 생각합니다 ㅋㅋ

2021-03-19 17:26 UTC, ksundong approved these changes
고생하셨습니다. 다음단계 진행해주세요~
몇가지 코멘트를 남겨드리니 한 번 생각해보세요!

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/answer/application/AnswerService.java
> +    public Long getWriterId(Long id) {
요 메서드가 서비스에 있는 이유는 뭘까요?

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/BaseEntity.java
> +    private boolean deleted = false;
이런 필드는 어쩌면 공통이 아닌 경우도 있을 것 같네요.
Entity는 DB와 연관되기 때문에 좀 더 신중할 필요가 있을 것 같아요.

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/common/BaseResponse.java
> +public abstract class BaseResponse {
중복 제거를 시도한 것은 좋은데, Response에 해당 정보들이 항상 포함되어야 하는지는 생각해봅시다.

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/application/QuestionService.java
> +            throw new QuestionNotDeletableException("삭제할 수 없는 질문입니다.");
여기도 문자열은 예외 클래스에 넣어주는 방법으로 구현해봅시다~

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/domain/Question.java
> +    @JsonBackReference
양방향 관련 문제가 발생했었나보군요?

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +                    return new LoginFailedException(exceptionMessage);
좀 더 간단하게 표현 가능할 것 같은데요?
꼭 debug로그를 여기서 찍어줄 필욘 없는 것 같아요. Exception Handling 과정에서 충분히 가능하다고 봅니다.
어차피 스택트레이스에 다 남으니까요.

2021-03-19 17:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/ui/UserController.java
> +    // FIXME: 로그아웃은 POST 로 구현해야한다.
GET이냐 POST냐는 자주나오는 떡밥인데요.
저는 POST를 선호하는데 GET으로 구현하는 분도 많은 것 같아요.
꼭 이래야 한다보다는 여러 의견을 바탕으로 선택하셨음 좋겠네요.

2021-03-19 23:12 UTC, ghojeong commented on src/main/java/com/codessquad/qna/answer/application/AnswerService.java
> +    public Long getWriterId(Long id) {
헙 question 만 getWriterId 를 삭제하고, AnswerService 에 대해서는 깜빡했군요. 해당 메서드도 삭제하겠습니다.

2021-03-19 23:14 UTC, ghojeong commented on src/main/java/com/codessquad/qna/user/application/UserService.java
> +                    return new LoginFailedException(exceptionMessage);
저도 원래 디버깅용 로그는 코드 상으로 남기는 것을 싫어하는 편인데,
포비님 강의를 따라하고 나서 삭제하는 것을 깜빡했네요.
해당 logger.debug 는 전부 삭제하겠습니다.

2021-03-19 23:21 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/BaseEntity.java
> +    private boolean deleted = false;
현재 answer, question, user 외에 추가적인 기능은 없다고 생각되고,
soft deletion 을 강제하는 연습을 위해서라도, deleted 를 공통으로 해도 큰 문제는 없지 않을까 생각합니다.
(협업을 하거나, 실제 돈을 받고 하는 코딩에는 엔티티에 deleted 필드는 넣지 않겠습니다.)

과제를 진행하는 동안 요구사항이 급작스럽게 변경되리라 생각되지는 않으므로,
spring-boot-qna 를 진행하는 동안은 위의 필드를 유지하겠습니다.

2021-03-19 23:25 UTC, ghojeong commented on src/main/java/com/codessquad/qna/common/BaseResponse.java
> +public abstract class BaseResponse {
Question 과 Answer 에는 해당되지만, UserResponse 에게도 생성날짜를 포함해야 하느냐? 라는 질문에는 확실히 아니라고 대답할 수밖에 없군요.
UserResponse 이후 설계의 유연성을 위해서라도 BaseResponse 를 삭제하겠습니다!!
라고 말을 해야겠지만,
BaseResponse 추상 클래스를 만들기 위해 추상 빌더 패턴을 적용하느라, 워낙 노고가 많이 들었기에 (진짜 머리 싸맸습니다.)
spring-boot-qna 를 진행하는 동안에는 봐주시면 감사하겠습니다. 이대로 지워버리기에는 무척 아깝네요.

협업이나, 다음 미션 진행시에는 response 에 Long id 만 공통 부분으로 남겨놓으려고 합니다.

2021-03-20 00:26 UTC, merged