[August] 미션3: 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #81
Opened 2021-03-17 03:50 UTC by Polynomeer

### 미션 2: 데이터베이스 활용

안녕하세요, 코드스쿼드 백엔드 반의 August입니다. 항상 좋은 리뷰 감사합니다! 이번 과제는 주어진 필수 요구사항인 로그인, 로그인 상태에 따른 네비게이션 바 변경, 로그아웃, 계정 정보 수정, 질문 생성/수정/삭제 까지 구현했습니다. 

선택 사항인 User와 Question 연결은 구현하지 않았고, 질문을 수정하거나 삭제할 때 현재 세션의 userId와 질문 글의 writer를 매칭하여 일치할 때만 수행하는 방식으로 작성하였습니다.

- 서버 주소 : https://august-qna.herokuapp.com/

### 구현 내용

- QuestionController
  - updateForm - 세션을 가져오고 변경할 질문을 가져와서 작성자와 세션 유저의 userId가 일치할 때만 `/qna/updateForm`을 띄워줍니다.
  - update - 세션을 가져오고 변경할 질문을 가져와서 작성자와 세션 유저의 userId가 일치할 때만 `QuestionService::update`를 호출합니다.
  - delete - 세션을 가져오고 작성자와 세션 유저의 userId가 일치할 때만 `QuestionService::delete`를 호출하여 삭제합니다.
- QuestionService
  - update - 기존의 Question과 새로운 Question을 받아서 update하고, QuestionRepository의 save를 호출합니다. 여기에서 `questionRepository.save(question)`이 없어도 기존에 추가된 레코드에 대해서 수정이 된다고 하는데, 저는 그렇게 동작하지 않아서 그냥 두었습니다.
  - delete - 단순히 QuestionRepository의 delete를 호출합니다.

2021-03-18 15:41 UTC, sonypark requested changes
안녕하세요 August, 리뷰어 소니 입니다.😊
미션3 구현하느라 고생하셨습니다.
개선할 부분이 몇 개 보여서 코멘트 남겼으니 확인 부탁드립니다.

추가로 공유해주신 배포 링크에 들어가 테스트하던 중 발견한 문제점 말씀드리겠습니다.

1. 현재 비밀번호를 수정할 수 없는것 같은데 맞나요..?
![image](https://user-images.githubusercontent.com/34808501/111653854-9180e380-884b-11eb-975e-164e982df429.png)

2. 게시글을 수정할 때 본문 내용이 모두 사라지네요. 수정 시에 본문 내용이 보여야하지 않을까요?

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/config/MvcConfig.java
> +//        registry.addViewController("/questions/form").setViewName("qna/form");
사용하지 않는 코드는 삭제해주세요~

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        }
아무 메시지 없이 리다이렉트를 해주면 사용자 입장에서는 왜 리다이렉트가 되는지 알 수 없을 것 같아요.
예외를 발생시켜 예외 메시지와 함께 리다이렉트 해주는 방식으로 변경하면 어떨까요?

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        session.removeAttribute("sessionedUser");
"sessionedUser"은 문자열이 아니라 상수로 처리해줘야 될 것 같습니다
이미 HttpSessionUtils에 `USER_SESSION_KEY`을 선언해놓으셨네요

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        logger.debug("User : {} found", sessionedUser.getUserId());
이 부분은 컨트롤러가 아닌 서비스 로직에서 처리해주면 좋을 것 같네요.
sessionedUser가 null일 경우 NPE이 발생할 것 같은데요. null을 리턴하는 건 매우 안 좋은 방법입니다. 다른 방법을 생각해보세요

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        userService.update(user, updatedUser);
여기도 마찬가지

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/service/UserService.java
> +    }
이 메서드 이름이 이게 맞나요?? `findUserByUserId` 가 되어야할 것 같아서요

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/service/UserService.java
>      }
`IllegalArgumentException` 을 던지기 보단, `UserNotFoundException`같은 CustomException을 발생시키는건 어떨까요?

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/util/HttpSessionUtils.java
> +    }
```suggestion
        public static boolean isLoginUser(HttpSession session) {
        return session.getAttribute(USER_SESSION_KEY) != null;
    }
```
이렇게 단순화시킬 수도 있겠네요

2021-03-18 15:41 UTC, sonypark commented on src/main/java/com/codesquad/qna/util/HttpSessionUtils.java
> +        }
null 리턴은 NPE의 원인이 됩니다.

2021-03-19 08:55 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/config/MvcConfig.java
> +//        registry.addViewController("/questions/form").setViewName("qna/form");
네, 제거했습니다!

2021-03-19 08:55 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        }
예외객체를 직접 정의하고 상황에 따라 에러 메시지를 출력하거나 리다이렉트 하도록 변경했습니다!

2021-03-19 08:56 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        session.removeAttribute("sessionedUser");
네, 변경했습니다.

2021-03-19 09:00 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        logger.debug("User : {} found", sessionedUser.getUserId());
UserService에서 findUserBySession이라는 메서드로 이동시켰습니다. 그런데 User::isMatchedId에서 equals로 반환하므로 이 메서드 내부에서는 NPE가 발생하지 않을 것 같습니다만, 반드시 처리해주어야 하나요?

2021-03-19 09:00 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/service/UserService.java
> +    }
변경했습니다!

2021-03-19 09:00 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/service/UserService.java
>      }
네, 예외객체를 정의했습니다!

2021-03-19 09:01 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/util/HttpSessionUtils.java
> +    }
그렇게 변경해보았습니다 :)

2021-03-19 09:01 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/util/HttpSessionUtils.java
> +        }
IllegalUserAccessException을 정의해서 throw하도록 했습니다!

2021-03-19 09:03 UTC, Polynomeer commented
1. 비밀번호는 변경할 비밀번호에 대한 input을 추가해서 현재 비밀번호가 일치하면서 빈 칸이면 변경하지 않고, 입력값이 있다면 변경하도록 구현했습니다!
2. 게시글 내용이 사라지는 문제도 해결했습니다!

2021-03-19 09:19 UTC, sonypark commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        logger.debug("User : {} found", sessionedUser.getUserId());
기존 코드에서 `getUserFromSession` 에서 null을 리턴하면 sessionedUser이 null 이기 때문에 `sessionedUser.isMatchedId(id)`를 호출할 때 NPE가 나는 경우를 말씀드렸습니다.
현재는 예외를 발생시키므로 sessionedUser가 null 인 경우는 없겠네요. 앞으로도 null 을 리턴하는건 지양해주세요~

2021-03-19 09:20 UTC, sonypark commented
> 1. 비밀번호는 변경할 비밀번호에 대한 input을 추가해서 현재 비밀번호가 일치하면서 빈 칸이면 변경하지 않고, 입력값이 있다면 변경하도록 구현했습니다!
> 2. 게시글 내용이 사라지는 문제도 해결했습니다!

아직 heroku에는 반영이 안 된건가요??

2021-03-19 23:09 UTC, Polynomeer commented on src/main/java/com/codesquad/qna/controller/UserController.java
> +        logger.debug("User : {} found", sessionedUser.getUserId());
그렇군요! 알겠습니다.

2021-03-19 23:09 UTC, Polynomeer commented
Heroku에는 반영이 안 되어있었군요, 죄송합니다!

2021-03-20 08:44 UTC, Polynomeer commented
@sonypark 최종 확인 부탁드립니다!

2021-03-21 10:49 UTC, sonypark approved these changes
확인했습니다.
수고하셨습니다!

2021-03-22 13:23 UTC, merged