[Dong] Mission2 데이터베이스 활용PR 올립니다
codesquad-members-2021/spring-boot-qna pull request #82
Opened 2021-03-17 04:12 UTC by d-h-k

# intro
안녕하세요 백엔드반 Dong 입니다. 
Mission2 데이터베이스 활용부분 구현을 완료해 PR 올립니다.
다른분들보다 늦어진데에는 이번 미션에서 몇가지 어려움을 겪었는데, 아래와 같습니다.
- 데이터베이스 설치 및 환경셋팅 후 h2 콘솔 접근
-

2021-03-17 15:53 UTC, sonypark requested changes
안녕하세요 Dong, 리뷰어 소니 입니다.😊
미션 구현하느라 고생하셨어요
스프링 MVC가 익숙지 않아서 어려움이 많으셨을 것 같네요
차근차근 공부해 봅시다!

개선할 부분에 대해 코멘트 남겼으니 관련해서 공부해주세요~
추가적으로 현재 컨트롤러에서 repository 의존성을 갖고 있는데, 컨트롤러와 서비스를 분리해보세요
(Controller -> Service -> Repository 로 의존성을 갖도록)

2021-03-17 15:53 UTC, sonypark commented on build.gradle
> +	testCompile('org.springframework.boot:spring-boot-starter-test')
중복 선언된 dependency가 몇개 보이네요~ 찾아서 하나만 남겨주세요

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    private QuestionRepostory questionRepostory;
의존성 주입은 필드가 아닌 생성자를 통한 주입을 사용해주세요~

[생성자 주입을 @Autowired를 사용하는 필드 주입보다 권장하는 하는 이유](https://madplay.github.io/post/why-constructor-injection-is-better-than-field-injection)

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>      private Logger logger = LoggerFactory.getLogger(UserController.class);
로거는 최상단으로 올려주시고, static final을 붙여주세요~

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        Question currentQuestion = questionRepostory.findById(id).get();
Optional.get()은 사용을 지양해야합니다. 왜 그럴까요?

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +    @GetMapping("")
```suggestion
    @GetMapping
```
취향이긴한데, 없어도 됩니다.

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        return "user/form";
음.. 이런 log가 필요한가요??

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        User currentUser = userRepository.findById(id).get();
여기도 .get()

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          logger.info("update User : " + currentUser.toString());
[SLF4J Logger 사용법 & 잘못된 사용법: Binding Parameters, Logging Exception Stack Trace](http://dveamer.github.io/backend/HowToUseSlf4j.html)

위 링크 참고해서 logger를 고쳐봅시다~

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/Question.java
>      }
이 코드는 필요한 코드일까요?

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/User.java
> +
여기도

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/domain/QuestionRepostory.java
> +}
여기는 CrudRepository를 사용하는 이유가 있나요?
UserRepository와 달라서 질문 드렸습니다

2021-03-17 15:53 UTC, sonypark commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +    private UserRepository userRepository;
여기도 필드 주입을 생성자 주입으로 바꿔주세요

2021-03-19 02:36 UTC, d-h-k commented on build.gradle
> +	testCompile('org.springframework.boot:spring-boot-starter-test')
넵 중복 선언된 DEPENDENCY를 제거하겠습니다!

2021-03-19 05:34 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    private QuestionRepostory questionRepostory;
감사합니다. 인텔리제이가 경고를 띄워주는 내용을 무심하게 지나쳤는데, 이런 내용이 있었네요!

2021-03-19 05:35 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +    private QuestionRepostory questionRepostory;
걸어주신 링크와 나름 학습한 내용을 노션으로 정리했습니다!

https://www.notion.so/c445b73d2ea94c859b93b58818b0e061

2021-03-19 05:49 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
>      private Logger logger = LoggerFactory.getLogger(UserController.class);
넵 말씀하신대로 수정하겠습니다 감사합니다!

왜 그래야 하는지도 공부해보겠습니다

2021-03-19 05:51 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        return "user/form";
이부분은 제가 users, user 두가지 용어가 혼용되서 이를 하나로 통일하는 과정에서 아쉬운 부분이 있었던 듯 합니다. 앞으로 유의하겠습니다

2021-03-19 06:01 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/Question.java
>      }
곰공히 생각을 해보니 관성적으로 인텔리제이 getter setter 자동생성을 했던것 같습니다. 앞으로 불필요한 메서드는 만들지 않고, 있어도 삭제하겠습니다!

2021-03-19 06:02 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/User.java
> +
넵 앞으로 불필요한 메서드는 생성하지 않겠습니다.

2021-03-19 06:05 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +    private UserRepository userRepository;
넵 감사합니다 앞으로도 필드주입이 아닌 생성자 주입 방식으로 사용하겠습니다.

2021-03-19 06:10 UTC, d-h-k commented on src/main/java/com/codessquad/qna/domain/QuestionRepostory.java
> +}
제가 사실 부끄럽게도... 웹개발 경험과 지식이 좀 많이 부족해서 다른분들 코드를 많이 참고하다 보니 이사람 저사람 코드가 혼재되어 있습니다. 해당 부분 관련해서도 저도 이부분이 궁금해서 정리를 해놓긴 했는데요.. 하나로 통일하겠습니다! 

https://velog.io/@d-h-k/%EC%BD%94%EC%BF%BC-11%EC%A3%BC%EC%B0%A8-Spring-Boot-%EA%B4%80%EB%A0%A8-%ED%86%A0%EB%A7%89%EC%A7%80%EC%8B%9D

2021-03-19 06:50 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
>          logger.info("update User : " + currentUser.toString());
감사합니다 이런 내용이 있는줄 몰랐는데, 앞으로 로그 기능을 사용할때도 리소스를 고려하겠습니다!

2021-03-21 18:33 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/QuestionController.java
> +        Question currentQuestion = questionRepostory.findById(id).get();
이번기회에 Optional 에 대해서 좀더 공부하게됬습니다. 제가 생각하기에는, Optional이 nullpointException을 처리하기 위해 사용되는 클래스인데, 단순하게 get()메서드를 사용해 값을 얻어오면 예외처리는 예외처리대로 못하고 성능낭비만 하기 때문에, Optional 을 사용하는 경우는 Null 에 대한 처리를 해준 코드를 사용해야 합니다.

아직 정리가 부족하지만 아래 링크처럼 정리&공부해봤습니다. 
https://www.notion.so/11-9e084610ce8242baac9e826c3082a993

2021-03-21 18:37 UTC, d-h-k commented on src/main/java/com/codessquad/qna/Controller/UserController.java
> +        User currentUser = userRepository.findById(id).get();
넵 수정하겠습니다

2021-03-22 13:26 UTC, honux77 commented
@sonypark 진도가 늦은 관계로 제가 대신 머지 했습니다. Dong 미흡한 점이 있다면 다음 단계에서 더 개선해 보세요.

2021-03-22 13:26 UTC, merged