[Woody] 미션3. 로그인 구현
codesquad-members-2021/spring-boot-qna pull request #84
Opened 2021-03-17 17:10 UTC by jihye-woo

안녕하세요 우디입니다!

이번에 미션 3 제출이 많이 늦어졌네요😂

🔗 배포 링크 : https://woodyqna.herokuapp.com/ 

----

### 👀 미션 3 요구사항 이외의 구현 사항
#### Custom Exception과 ControllerAdvice 사용
  - 사용자 정의 예외들을 구현했습니다!
  - 예외 발생 시 `@ControllerAdvice` 어노테이션을 추가한 GlobalControllerExceptionHandler 클래스에서 예외를 처리하게끔 했습니다!
#### 질문하기 기능 구현
  - 옵션인 질문하기 기능까지 구현해주었습니다!
  - (질문 수정하기는 아직 진행하지 않았습니다! )
#### Question DTO 구현
  - QuestionRequest라는 DTO 클래스를 구현해서 수정 메소드에서는 QuestionRequest를 인자로 받아오게 하였습니다.
---
### 🤔 구현을 고려하고 있는 점 - Service 계층 추가
- 미션 3의 요구 조건들을 구현하고 나니 컨트롤러의 역할이 너무 많아지고 코드가 길어졌습니다. 슬슬 service 계층을 만들어서 로직을 분리하는게 좋을 것 같다는 생각이 듭니다..!

----
### 😅 괜찮을까요? 
- 이번에 구현하면서도 확신이 서지 않는 부분들이 많았습니다ㅠㅠ
- 짧게 **Yes / No**로만 답변 주셔도 괜찮습니다!

#### 1. Custom Exception 너무 많은건 아니겠죠..?
- Custom Exception 클래스들을 정의해주었는데,  Respository에서 원하는 Entity를 찾지 못하는 상황에 대한 예외를 아래와 같이 Entity별로 각각 구현해주었습니다!
  - QuestionNotFoundException
  - UserNotFoundException
  - AnswerNotFoundException

- 사실 NotFoundException으로 충분히 핸들이 가능하다고 생각했지만 **에러를 한 눈에 파악하기 쉬운 점**에 더 초점을 맞추고 각 entity 별로 하나씩 예외를 만들었는데 괜찮을까요? 
- (아직 어느정도가 불필요한 정도인지 혹은 필요한 정도인지 감이 잘 오지 않네요ㅠ)

#### 2. User 클래스의 equals() 재정의 시 비교해야할 필드 값들?
- 로그인한 유저와 게시글 작성자가 동일한지 확인하기 위해서, User 클래스의 equals()를 아래와 같이 `id`와 `userId`를 비교하도록 재정의 해주었습니다. equals()를 오버라이드 할 때 이렇게 id와 userId만을 비교해주어도 괜찮을까요? 
- (equals()에서 어떤 필드를 비교해주는게 좋을지, 무엇이 기준이 되는게 좋을지 아직 그 기준을 잘 모르겠네요ㅠ)

```java
public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(id, user.id) && Objects.equals(userId, user.userId);
    }
```

#### 3. 메소드 내부에서 Entity 객체 생성 방법
- `Answer answer = new Answer(loginUser, question, contents);` 대신 아래와 같이 toEntity()라는 정적 팩토리 메소드를 구현해서 사용했는데 적절한 방법인지 모르겠습니다..!😅 
- (Service 계층을 추가하게되면 해결 될 것 같기도 한데.. 지금 단계에서는 저 방법밖에 생각이 나지 않았어요 흛흐)

```java
@PostMapping()
    public String create(@PathVariable Long questionId, String contents, HttpSession session) {
        User loginUser = SessionUtils.getLoginUser(session);

        Question question = getQuestionById(questionId);
        Answer answer = Answer.toEntity(loginUser, question, contents); // 👈👈
        answerRepository.save(answer);

        return "redirect:/questions/" + questionId;
    }
```
#### 4. ONE-TO-MANY 연관관계 양방향 참조
 - Answer 클래스와 Question 클래스 혹은 User 클래스 간에 연관 관계가 필요해보여서 `@OneToMany`에 mappedBy를 적용해주었습니다. 그러다보니 순환 참조 문제가 발생할 수 있다고 해서 아래와 같이 메소드에 순환참조를 방지하는 로직도 추가하게 되고 복잡한 관계가 만들어진 것 같습니다😅 지금 이런 방식(양방향 참조)이 맞는건지 확신이 서지 않아서 질문 드립니다..!
 
 - (아직 JPA 걸음마 단계라 언제 단뱡향 혹은 양방향 참조를 해주어야 할지 잘 모르겠네요ㅠㅠ 조금 더 공부해봐야할 것 같습니다..😂)
 
     ```java
    public void addAnswer(Answer answer) {
            answers.add(answer);
            if (answer.getQuestion() != this) {
                answer.setQuestion(this);
            }
        }
    ```
    ```java
    public void setQuestion(Question question) {
            this.question = question;
            if (!question.getAnswers().contains(this)) {
                question.getAnswers().add(this);
            }
        }
    ```
 ----

글이 길어지게 되었네요..ㅠㅠ  긴 글 읽어주셔서 감사합니다!

지금까지 모르는 것 투성이인 우디였습니다💦💦

2021-03-19 03:38 UTC, wheejuni requested changes
우디 안녕하세요. 이번에도 열심히 구현해서 PR 열어주셨네요. 수고하셨습니다. 👍 
항상 다채로운 이모지를 보면서 많이 감명받고 있습니다. 💯 

우선 생각하신 것처럼 이제 슬슬 `Service` 를 만들 때가 되었습니다. 더 늦기전에 4단계에선 구현해보시면 좋을 것 같네요. 
`.equals()` 와 `.toEntity()` 는 적절히 잘 구현해 주셨습니다. 다만, `.toEntity()` 는 보통 다른 계층의 클래스에서 엔티티 클래스로 변환이 될 때 사용하는 기법이기는 합니다. 오히려 지금 단계에선 `Builder` 를 적용해보셨으면 어떨까 하는 생각은 들어요. 

마지막으로... 양방향 참조에 대해서 설명해 드릴게요. 
우디는 왜 양방향 참조가 필요하다고 생각하셨고, 양방향 참조가 어떻게 위험할지도 충분히 파악하셨나요? 
양방향 매핑 자체가 안티 패턴은 전혀 아닙니다. 적절히 활용해야 좋을 때가 있고요. 
오히려 생각해볼 점은 _모든 엔티티 클래스를 위한 repository가 필요할까_ 입니다. 엔티티로 접근할 수 있는 접근 창구가 너무 많기 때문에, 여기저기서 참조관계를 불러다가 다음 엔티티로 넘어가고 싶은 욕구가 생기는 걸수도 있거든요.
예를 들어서 지금 `UserRepository` 와 `AnswerRepository` 가 다 있는 것 같은데, 만약 `UserRepository` 밖에 작성되지 않았다고 가정해 보죠.
그렇다면 우디가 비즈니스 로직을 개발하기 위해서라면 무조건 `User` 엔티티에서부터 탐색을 시작해야겠죠. 로그인된 유저를 꺼내 오고, 어라, 이 유저가 뭔가를 작성했네... 그러면 `User` 에 담겨있는 메소드 중 `Answer` 를 작성시켜줄 수 있는 메소드를 찾아보고(없으면 새로 구현하고), `User` 를 `.save()` 하는 것만으로도 `Answer` 까지 저장되는 `cascade` 옵션을 부여하고.... 이런 식으로 설계를 전개해나가다 보면 양방향 매핑 관계 중 많은 부분은 걷어낼 수 있지 않을까요?

뭔가 추상적인 얘기를 한 것 같네요. ㅎㅎ 더 궁금한 점이 생기셨다면 언제든지 추가질문 해 주시고요, 항상 응원합니다 우디~

2021-03-19 03:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +        }
👍

2021-03-19 03:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/exception/GlobalControllerExceptionHandler.java
> +    @ExceptionHandler({UserNotFoundException.class, QuestionNotFoundException.class, AnswerNotFoundException.class})
이 세가지 예외의 공통점이 무엇일까요?
앞으로도 이 예외들의 핸들링 로직이 같게 된다면, 이 세 가지 예외가 공통으로 상속받는 공통적인 예외가 있으면 더 좋을 것 같네요.

2021-03-19 03:38 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/utils/SessionUtils.java
> +    private static Optional<User> userFromSession(HttpSession session) {
👍 👍

2021-03-20 08:06 UTC, wheejuni commented
@jihye-woo 확인하셨나요? 머지할까요?

2021-03-20 15:12 UTC, jihye-woo commented
제가 피드백 반영이 너무 느린 것 같아서 죄송해요ㅠㅠ 
오늘 안으로 피드백 반영해서 수정하겠습니다..ㅠㅠ!!

2021-03-20 15:17 UTC, wheejuni commented
@jihye-woo 천천히 하셔도 괜찮아요 ㅠㅠㅠ

2021-03-20 19:54 UTC, jihye-woo commented
제가 손이 그렇게 빠른 편이 아니라 피드백 반영이 늦어지게 되었습니다😂
(체스 미션도 마무리 하지못했네요 흐엉..💦 하지만 체스 미션 피드백 주신 부분들은 다 읽어보았습니다!)

그리고 시작하기에 앞서.. 글이 길어지게된 점도 죄송합니다..😂

---

### Service 구현

**데이터에 접근**하거나 **예외를 처리**해주는 등 대부분의 로직들은 모두 `서비스 클래스`로 이동시켰습니다.

`컨트롤러 클래스`는 최대한 **service가 제공하는 기능들을 사용**하고 **뷰를 넘겨주는** 책임만 가지도록 했습니다!

### 🙋‍♀️ 질문
사실 아직 `비지니스 로직`이라는 단어가 명확하게 와닿지 않아서 위와 같은 기준을 가지고 분리를 하면 되는게 맞는지 궁금합니다..!!😂

---

### Builder 구현

모든 Entity(User, Question, Answer) 클래스 내부에 아래와 같이 Builder를 구현해주었습니다.

```java
// User 클래스 내부
static public class Builder {
	// 필드 변수들 private으로 선언
  private String userId;
  // ...

  public Builder()

  public Builder(User user){
	  this.userId = user.userId;
    // ...
  }

  // 모든 필드 변수들에 대한 initialize 메소드
  public Builder userId(String userId){
		 this.userId = userId;
     return this;
  }
 
	// ...
  public User build() { return new User(userId, ...); }
  
}
```

사실 아래의 경우는
```java
// QuestionRequest 클래스

public Question toEntity(User writer) {
    return new Question(writer, title, contents);
}
```
빌더 패턴 적용 시
```java
public Question toEntity(User writer) {
        return new Question.Builder()
                .writer(writer)
                .title(title)
                .contents(contents)
                .build();
    }
```
더 복잡하게 보이는 듯한 느낌을 받긴 했지만😂 좀 더 유연하게 Question을 생성하고 싶을 때를 대비하기 위해서 빌더패턴을 적용하는 거라고 생각하면 되겠죠?!

---

### toEntity() 위치 변경

- `toEntity()`가 다른 계층의 클래스에서 Entity 클래스로 변환이 될 때 사용된다고 말씀해주셔서! `toEntity()` 의 위치를 Entity 클래스 내부가 아닌 DTO 클래스 내부로 이동해주었습니다!

---

### 양방향 참조 
#### 1. 왜 필요한가?

[**필요한 상황]** **Answer를 가지고 있는 Question 데이터를 삭제하고 싶을 경우**

Answer만 Question을 참조할 때는 Question에 삭제와 같은 변화가 생기더라도 Answer 테이블은 알지 못하는 상황이 생깁니다!😢 그래서 Answer 데이터가 **존재하지 않는 Question 데이터를 참조**하게 되는 상태가 되겠더라구요..!(물론 그런 참사가 벌어지기 전에 다행히 에러가 발생해서, 데이터들은 무사하긴 하지만요..!) 

그래서 Question 테이블에서 발생하는 일들을 Answer 테이블도 알 수 있게끔 해주기 위해 **양방향 참조 + Cascade 옵션**을 사용하게 되었습니다

#### 2. 모든 엔티티 클래스를 위한 repository가 필요한가?

말씀해주신대로 확실히 양방향 참조가 무분별하게 이루어질 경우에는 하나의 엔티티로도 다른 엔티티 정보를 가져올 수 있게 되니까 하나의 repository에서 모든 일들을 처리할 수 있는 불상사(?)가 발생할 수도 있겠네요..!

### 🙋‍♀️ 들어주신 예시, 이렇게 이해하면 될까요?

그리고 아래와 같이 들어주신 예시를

> 예를 들어서 지금 UserRepository 와 AnswerRepository 가 다 있는 것 같은데, 만약 UserRepository 밖에 작성되지 않았다고 가정해 보죠.
그렇다면 우디가 비즈니스 로직을 개발하기 위해서라면 무조건 User 엔티티에서부터 탐색을 시작해야겠죠. 로그인된 유저를 꺼내 오고, 어라, 이 유저가 뭔가를 작성했네... 그러면 User 에 담겨있는 메소드 중 Answer 를 작성시켜줄 수 있는 메소드를 찾아보고(없으면 새로 구현하고), User 를 .save() 하는 것만으로도 Answer 까지 저장되는 cascade 옵션을 부여하고.... 이런 식으로 설계를 전개해나가다 보면 양방향 매핑 관계 중 많은 부분은 걷어낼 수 있지 않을까요?

아래와 같이  이해해도 괜찮을까요?

만약 많은 엔티티에 접근 가능한 Repository가 있을 경우, 비지니스 로직을 설계하고 개발하는 과정에서 
'특정 엔티티에 대한 Respository를 따로 구현하여 특정 엔티티 접근에 대한 책임을 분리'하는 등의 작업을 통해 양방향 매핑으로 인해 발생할 수 있는 문제점(특히 언급하셨던 `모든 엔티티 클래스에 접근가능한 repo` )을 해결할 수 있다!


#### 3. 그밖에 위험성(이라고 추측하는 것들)

🤦‍♀️**복잡하다**?

A → B 그리고 A ← B 두 관계 모두 고려를 해주어야하기 때문에 관리가 단방향보다는 복잡해질 것 같습니다..! 상황에 따라서 Cascade 옵션도 ALL이 아니라 특정 operation만 반영을 하게끔 해주어야할 수도 있구요.. 여러모로 신경써야할 부분이 많아질 것 같습니다..!

🐢**성능문제**?

그리고 (양방향 뿐만 아니라) 참조가 많아지게되면 A 테이블에 있는 데이터를 꺼내오는 순간 B 테이블까지도 확인해야하기 때문에 성능상 문제가 생기는 경우가 있을 수도 있다고 하더라구요..!

성능 문제를 방지하기위해서 나름 지연로딩 속성을 추가했는데 그걸로 해결안되는 제가 모르는 성능 문제들이 충분히 있을 수도..?! 있다고 생각합니다..!

🎡**순환 참조 문제?**

순환 참조가 발생할 수 있기 때문에 개발자가 이를 방어하는 로직을 따로 작성해야한다는 점..?

---

- JPA 파트는 물음표가 난무하네요ㅠㅠ 확실하게 안다고 이야기할 수 있는 부분들이 많지 않아서 조심스럽게 물음표를 콕콕 달아보았습니다..😂

- 왜 매번 이렇게 글이 길어지는지 모르겠네요..ㅎㅠㅠ 긴 글 읽어주셔서 감사합니다!!🙇‍♀️

2021-03-20 20:16 UTC, jihye-woo commented on src/main/java/com/codessquad/qna/web/exception/GlobalControllerExceptionHandler.java
> +    @ExceptionHandler({UserNotFoundException.class, QuestionNotFoundException.class, AnswerNotFoundException.class})
### [Option 1 - 적용 X] NotFoundException 상속받기
- 처음에 공통으로 `NotFoundException`을 상속받도록 하려고 했는데, checkedException이라서 핸들링이 힘들 것 같았습니다..ㅠ 
- 예외를 계속 caller로 던지거나 try-catch로 받기 보다는 RuntimeException으로 한 번 던지고 `@ExceptionHandler`에서 처리하는 편이 더 좋다고 생각했습니다..!
### [Option 2 - 적용 X] 상위 커스텀 예외를 구현
- 상위의 커스텀 예외를 구현해서 상속해주게 되면 NotFound와 관련한 커스텀 예외가 많아지지 않을까라는 걱정이 들었습니다..!
- 그래서 상속을 하는 대신 각 Entity에 대한 예외들을 없애고 EntityNotFoundException 이라는 상위 예외 하나로 통합했습니다..!

하지만 언제나 그렇듯 좋은 방법인지는 잘 모르겠네요..!😂 혹시 어떤 방식으로 해결했으면 하셨는지 조오금만 더 알려주실 수 있을까요?👀

2021-03-21 09:43 UTC, wheejuni approved these changes
@jihye-woo 우디 안녕하세요. 글이 길지만 읽는데 재미가 있어서 괜찮아요. ㅋㅋ
우선 `.toEntity()` 와 `Builder` 적용 잘 하셨네요. 
그럼 이제부터 저도 길게 제가 하고싶은 얘기를 해보도록 할게요.

### 비즈니스 로직에 대해

족발집에 갔다고 생각해보죠. 족발집에선 다양한 일들이 일어납니다. 손님이 청하를 시키면 청하를 갖다줘야 하고, 족발을 시키면 족발을 갖다줘야 합니다. 
족발을 시켰다고 족발만 줄 순 없죠. 밑반찬도 깔아야 하고, 수저도 준비돼 있어야 하고, 물컵도 인원수에 맞게 나가야하고.... 많은 일들이 일어나겠죠. 
많은 일들이 일어나지만, 족발집의 비즈니스 로직은 **족발을 삶고 소분하는 일** 일 겁니다. 

비즈니스 로직은 해당 애플리케이션이 _자신의 목적에 부합하게 정보를 가공하고 저장하는데 필요한 핵심 로직_ 을 말합니다. Q&A 서비스의 목적은 무엇일까요? 질문을 저장하고 답변을 내놓는 것이 목적이죠. 그렇다면 Q&A 서비스의 비즈니스 로직은요? 본질에 집중해서 생각해보면 _어디까지가 비즈니스 로직_ 인지는 쉽게 구분할 수 있을 거라 생각합니다.

잘 이해가 안간다면 이런 접근 방식을 취해보는 것도 좋습니다. 우디가 Q&A 서비스를 이용하는데 어느날 보니 서비스가 너무 못생긴 거에요. 그래서 "차세대 Q&A 서비스" 를 만든다고 생각해보죠. 그렇다면.... 어디부터 변경이 시작될까요? 서비스 클래스? 컨트롤러? view? 
가장 나중에 변경될 부분을 담고있는 것이 비즈니스 로직입니다. 

### 양방향 참조와 레포지토리에 대해 

우선 `cascade` 설정과 양방향 참조는 별로 관계가 없습니다. 물론 양방향 매핑 관계가 설정된 객체에서 `cascade` 를 많이 쓰긴 하지만요, 단방향 매핑에서도 `cascade` 를 줄 수 있습니다. `cascade` 가 어떤 역할을 하는지 다시 한 번 생각해 보면 좋겠습니다(개념적 정의를 굳이 꺼내오자면 _영속성 전이_ 입니다). 

양방향 매핑, 그리고 레포지토리의 관계에 대해 생각하기 전에 `Repository` 의 본질에 대해 생각해보는 시간을 가져도 좋을 것 같아요. `Repository` 가 왜 있을까요? 제가 이해하기로 레포지토리는 엔티티에 접근하는 유일한 통로 입니다. 물론 JDBC Template을 사용할 수도 있고, 기타 다른 쿼리 방법이 있겠지만 그런 가능성을 배제하고 `Repository` 는 엔티티로 가는 길을 추상화한 유일한 객체라고 봐요. 

우리가 개발을 진행하면서 entrypoint 역할을 할 엔티티와, 그렇지 않은 엔티티를 구분하는 것이 중요하다고 저는 믿는데요, 모든 엔티티가 이 엔트리 포인트 역할을 해야 하는 것은 아니라고 봅니다. 잘 추상화된, 잘 계층화된, 그리고 무엇보다 좋은 객체지향 개념을 갖고 설계한 객체 맵에는 엔트리 포인트가 여러개 필요하지 않습니다. 사용자의 액션은 하나, 혹은 두 개의 엔트리 포인트에서 늘 시작할 수 있거든요. 

Q&A 서비스로 이 생각을 적용시켜보면... 어떨까요? 

---

저도 글을 길게 남깁니다. ㅋㅋ 읽어보시고 생각할 시간을 가지셨으면 좋겠어요. 일요일 저녁에 생각해보기 좋은 주제네요. ㅎㅎ
읽어보시고 추가질문 있으면 또 남겨보시고 같은 그룹(?) 분들과 생각을 나누시는 것도 강력히 추천합니다~

2021-03-21 09:43 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/dto/question/QuestionRequest.java
> +    public Question toEntity(User writer) {
👍

2021-03-21 09:43 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/domain/question/Question.java
> +        public Question build() {return new Question(writer, title, contents);}
👍

2021-03-21 10:08 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/exception/GlobalControllerExceptionHandler.java
> +    @ExceptionHandler({UserNotFoundException.class, QuestionNotFoundException.class, AnswerNotFoundException.class})
아 이걸 이제 봤군요. @jihye-woo 저는 2번 옵션을 염두에 두고 말씀드린 거긴 합니다. ㅎㅎ

2021-03-22 00:34 UTC, merged