[Kyu] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #86
Opened 2021-03-18 09:18 UTC by kyu-kim-kr

배포 주소: https://desolate-escarpment-89047.herokuapp.com/

안녕하세요.

힘들었던 점
- 댓글 구현할때 디비에 값은 잘들어가는데 화면에 안나와서 고생함. 알고보니 Getter를 안만들어줘서 그랬는데 다른건 다 만들어줬었는데 왜 answer를 담는 List만 Getter를 안만들어주었을까?

리뷰 감사합니다.

2021-03-20 01:25 UTC, wheejuni requested changes
4단계까지 빠르게 진행하시느라 수고 많으셨습니다.
다만 **어떠한 경우에도 `Optional.get()` 은 사용하지 않는 것을 원칙으로 해 주세요.**

이외에도 이번 단계를 빠르게 구현하셨고, 진도도 늦은 상황이 아니기때문에, 이번 단계에서 `service` 구현까지 해보고 넘어가시면 어떨까 싶기는 합니다. 
한번 생각해보시고 구현 여부 알려주세요~

2021-03-20 01:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +    private QuestionRepository questionRepository;
진행상황도 결코 늦지 않고 하시니, `Service` 구현해서 주입받는 경험을 이번 단계에서 해봤으면 하는데요,
어떻게 생각하시나요?

2021-03-20 01:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +        return String.format("redirect:/questions/%d", questionId);
컨트롤러에서 리턴으로 나가는 view name으로는 문자열 덧셈 연산이 더 가독성이 좋습니다.

```suggestion
        return "redirect:/questions/" + questionId;

2021-03-20 01:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question selectedQuestion = questionRepository.findById(id).get();
`Optional.get()` 은 **사용 금지** 입니다. 
`NullPointerException` 을 막기 위해 옵셔널을 사용하는 것인데요. 이렇게 강제 언래핑하시면 아무런 의미가 없어집니다.

2021-03-20 01:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if (!selectedQuestion.hasSameUserAs(sessionedUser)) {
만약 `selectedQuestion` 이 `null` 이면 여기서 어떻게 될까요?

2021-03-20 01:25 UTC, wheejuni commented on src/main/resources/data.sql
> +    ('안녕하세용 큐큐입니다', CURRENT_TIMESTAMP(), '테스트입니당당', '2');
`create_date` 를 갖고 테스트하거나 로직을 검증할 일이 생겼을 때에, 조금 어려움을 겪을 수도 있을 것 같은데요,
고정된 시간값을 넣어주는 것이 어떨까요?

2021-03-23 21:57 UTC, kyu-kim-kr reviewed
짝프로그래밍 [Starve](https://github.com/Jiwon-JJW)와 같이하게 다시 Starve 아이디로 미션4 PR 보냈습니다. https://github.com/codesquad-members-2021/spring-boot-qna/pull/113

2021-03-23 21:57 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/AnswerController.java
> +    private QuestionRepository questionRepository;
이번에 짝 프로그래밍하면서 미션4를 다시하고 있는데 Service를 구현해봤습니다. 감사합니다!
https://github.com/codesquad-members-2021/spring-boot-qna/pull/113

2021-03-23 21:57 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        if (!selectedQuestion.hasSameUserAs(sessionedUser)) {
예외처리를 해줘야하겠군요.

2021-03-23 21:57 UTC, kyu-kim-kr commented on src/main/resources/data.sql
> +    ('안녕하세용 큐큐입니다', CURRENT_TIMESTAMP(), '테스트입니당당', '2');
듣고보니 그렇네요. 짝프로그래밍하면서도 현재시각을 넣어주도록 했는데, 수정하겠습니다
https://github.com/codesquad-members-2021/spring-boot-qna/pull/113

2021-03-23 21:59 UTC, kyu-kim-kr commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question selectedQuestion = questionRepository.findById(id).get();
넵 명심하겠습니다. 다른 방법으로 questionRepository에서 id를 통해 불러올수있는 방법을 찾아서 적용하겠습니다

2021-03-24 13:51 UTC, merged