Mission3 -  로그인 구현
codesquad-members-2021/spring-boot-qna pull request #87
Opened 2021-03-18 14:13 UTC by Jiwon-JJW

안녕하세요.

코드스쿼드 백엔드 과정 Starve입니다.

미션 3을 완료하였으며, 부족한 코드이지만 이번 리뷰도 잘 부탁드립니다!

[배포 사이트](https://starve-spring-0119.herokuapp.com/)

##### 이번 미션에서 고민하고 있는 사항:

1. QnaController나 UserController에 있는 체크 메서드들을 Service 계층을 생성하여 슬슬 옮기는 것이 나을 것 같아 미션 4에서 차차 추가하는게 좋을 것 같다는 생각을 했습니다.
   미션 3에서 추가하는게 더 좋을까요?
   
2. 현재는 index.html이나 qna/show.html 에서 직접적으로 포맷팅을 해주는 getFormattedDateTime을 호출하고 있는데, 핸들러를 사용하는게 더 나은 것인지에 대해 고민이 되어, 무엇이 더 나은 방식인지 궁금합니다!

감사합니다!

2021-03-20 05:36 UTC, ksundong requested changes
안녕하세요! Starve! 리뷰어 Dion입니다!!
3단계 미션을 수행하시느라 고생 많으셨습니다. 재밌게 잘 하고 계신가요?

회원가입이 500에러가 발생하면서 가입이 되지 않아서, Application 관련 피드백을 드릴 수가 없네요. 확인 부탁드릴게요~
되도록이면, 배포하시고 한 번 직접 테스트를 해주실 것을 추천드리겠습니다!

따라서 이번 미션은 코드와는 별개로 **변경 요청** 드립니다. 확인해주시고, 반영하시고 다시 리뷰요청 해주세요!

## 코드 관련 피드백

- `Q&A` 와 `Question`중 어떤 것이 나은지 고민해주세요.
- `Qna`의 writer는 현재 시점에서 `String`이 아닌 `User`로 할당이 가능합니다.
- `boolean`형 값을 리턴할 때에는 꼭 조건문이 필요하지 않은 경우가 존재합니다. 항상 신경써주세요.
- `null`을 리턴하는 경우는 지양해주세요. 왜 `null`이 리턴될까를 고민해보세요.
- `assert` 키워드가 무엇인지 학습하시고, 이것이 과연 `if`문을 대신할 수 있는지 생각해보세요.

그 밖의 피드백은 아래의 코멘트들 참고해주세요.
궁금하시거나, 도움이 필요한 부분, **이해가 되지 않는 부분**, 토론하고 싶은 부분이 있다면 언제든 코멘트 남겨주세요.
고생하셨습니다~

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> -    @Column(nullable = false)
제약조건을 제거해주신 이유가 있나요?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
>      private String writer;
이번 미션에서 로그인 한 유저가 누구인지 알 수 있기 때문에, `User`로 변경해주시면 좋을 것 같네요.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    public boolean checkWriter(String userId) {
`checkWriter` 도 괜찮긴 한데, 더 좋은 이름을 한 번 고민해보세요~

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Qna.java
> +    public boolean checkWriter(String userId) {
아마 `User`가 들어가면 좀 더 생각이 자유로워질 것 같네요.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/User.java
> +    }
여기도 마찬가지로 더 좋은 이름을 고민해봅시다.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/UserRepository.java
> +    User findByUserId(String userId);
반드시 해당 userId에 해당하는 User가 리턴될까요?
한 번 고민해보세요!

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +        return true;
```suggestion
        return sessionUser != null
```
으로 하면 더 간단하게 되겠죠?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +        }
`null`을 리턴해주는 것이 과연 좋을까요?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +        }
해당 동작은 로그인이 필요한 동작에서 예외적인 상황이 될 수도 있을 것 같네요.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        assert sessionUser != null;
`assert`는 언제 쓰는 것인지 학습하시고 사용해주세요~

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        assert sessionUser != null;
비즈니스 로직에서 `assert`의 사용은 하지 않습니다!

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Qna qna = qnaRepository.findById(id).orElseThrow(NoUserException::new);
사실 어떻게 보면 Q&A라는 이름은 Question And Answer로 볼 수 있겠는데요.
저희가 관심있는건 Question이므로 Question으로 변경해주시는게 어떨까 하는 제안을 드려봅니다.
인텔리제이의 리팩토링 도구를 이용하시면 쉽게 변경하실 수 있습니다!

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        }
몇몇 부분을 제외하곤 훌륭하게 잘 해주셨네요.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +            throw new IllegalStateException("자신의 질문만 수정할 수 있습니다.");
Custom Exception을 만들어서 처리해봅시다.
힌트는 권한이 없다는 것입니다.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @PostMapping("{id}/form")
`form`은 없어도 되겠죠? form을 수정한다는 의미로 읽힐 수 있습니다.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @DeleteMapping("{id}/delete")
```suggestion
    @DeleteMapping("{id}")
```

RESTful한 Url 설계에 대해서 한 번 학습해봅시다.

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    public String getOneUserProfile(@PathVariable long id, Model model, HttpSession session) {
```suggestion
    public String userProfile(@PathVariable long id, Model model, HttpSession session) {
```

이렇게 바꾸는 편이 훨씬 잘 읽히지 않을까요?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        User user = userRepository.findById(sessionUser.getId()).orElseThrow(NoUserException::new);
어떤 의도로 이렇게 작성해주셨는지 모르겠지만~
로그인 하지 않은 유저가 다른 유저의 프로필을 볼 수 없는 상황일까요?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        User user = userRepository.findById(sessionUser.getId()).orElseThrow(NoUserException::new);
만약 그렇다면, 조회를 요청한 유저의 정보를 조회해서 봐야하지 않을까요?

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        User user = userRepository.findById(sessionUser.getId()).orElseThrow(NoUserException::new);
무조건 로그인 한 유저의 정보를 보게 될 것 같네요!

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/logout")
logout이 GET 메서드를 써야하는지 POST 메서드를 써야하는지 한 번 고민해보세요!

2021-03-20 05:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/logout")
이러면 그냥 POST로 변경하실 것 같아서, 정답이 없는 문제니까 꼭 한 번 검색해보세요!

2021-03-20 05:36 UTC, ksundong commented on src/main/resources/import.sql
> +INSERT INTO USER (id, user_id, password, name, email) VALUES (2, 'test', '1234', 'test', 'test@slipp.net');
여기는 통행금지 표시가 남아있네요.

2021-03-20 05:36 UTC, ksundong commented on src/main/resources/templates/index.html
> +                                <span class="time">{{getFormattedDateTime}}</span>
`get`을 써줘야하던가요?

2021-03-20 05:44 UTC, ksundong commented
> ##### 이번 미션에서 고민하고 있는 사항:
>
> 1. QnaController나 UserController에 있는 체크 메서드들을 Service 계층을 생성하여 슬슬 옮기는 것이 나을 것 같아 미션 4에서 차차 추가하는게 좋을 것 같다는 생각을 했습니다.
>    미션 3에서 추가하는게 더 좋을까요?

계층의 분리가 필요하다고 느낀 시점에서 분리해주시면 됩니다. 저라면 바로 분리해봤을 것 같아요.

> 2. 현재는 index.html이나 qna/show.html 에서 직접적으로 포맷팅을 해주는 getFormattedDateTime을 호출하고 있는데, 핸들러를 사용하는게 더 나은 것인지에 대해 고민이 되어, 무엇이 더 나은 방식인지 궁금합니다!

무엇이 낫다고 제가 알려드리는 것 보단 starve가 고민하시고, 그 방법을 선택하시는 것을 추천합니다.
왜냐면, 고민하지 않고, 누가 좋다고 해서 선택한 것은 절대 성장에 도움을 줄 수 없기 때문입니다.

예를 들자면, 핸들러를 사용하는 방식에는 어떤 장점, 단점이 있고, getter로 포매팅을 해주는 방식에는 어떤 장점, 단점이 있어서 둘을 비교해 본 결과 이 기술을 사용하는 것이 좋을 것 같아서, 선택했습니다. 라는 얘기를 한다면 어떨까요?

나중에 면접을 보실 때, 한 번 이런식으로 설명해보세요. 적어도 저는 좋은 인상을 받을 것 같습니다.

2021-03-20 12:16 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/domain/Qna.java
> -    @Column(nullable = false)
비어있는 내용이나 제목을 입력하는 경우도 많은 것 같다는 생각 때문에 없어도 될것같다고 판단하여 제거했습니다!

2021-03-20 12:18 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Qna qna = qnaRepository.findById(id).orElseThrow(NoUserException::new);
Dion이 말씀하신대로, 저 또한 동일한 생각이 미션4를 진행하면서 들어서, 바로 변경했습니다!!
다음엔 메서드 명도 그렇고 전반적인 네이밍을 신중하게 결정해야할 것 같습니다..  감사합니다!!

2021-03-20 12:19 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @DeleteMapping("{id}/delete")
이전에도 알려주셨는데 또 같은 실수를 했네요..🥲 주의하겠습니다!

2021-03-20 12:24 UTC, Jiwon-JJW commented on src/main/resources/templates/index.html
> +                                <span class="time">{{getFormattedDateTime}}</span>
꼭 써줘야하는 줄 알았는데, 없어도 잘 구현이 되는것을 확인했습니다! 
한 가지 질문이 있는데, 다른 변수들의 이름만 입력했을 때 자동으로 getter를 불러오는 것과 비슷한 원리로 메서드도 get을 붙이지 않아도 호출이 되는 것 일까요? 
검색 방법이 잘못되었는지 적당한 답이 검색으로 나오지 않아 질문드립니다..!

2021-03-21 07:17 UTC, ksundong commented on src/main/resources/templates/index.html
> +                                <span class="time">{{getFormattedDateTime}}</span>
네 핸들바에서는 get을 붙이지 않아도 동작했던 것 같아요.

2021-03-21 11:31 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +        }
잘못하면 계속 NullPointException이 발생하는 원인이 될 수 있을 것 같아, IllegalStateException으로 에러페이지를 반환하는 방식으로 변경했습니다!! 감사합니다!

2021-03-21 12:15 UTC, Jiwon-JJW commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/logout")
검색으로 GET과 POST의 차이점을 살피고, 또 로그아웃엔 대체적으로 무엇을 사용하는지 확인 해 보니, 평균적으로 세션에서 로그인 정보를 삭제하는 것으로 DELETE를 많이 사용하지만, GET과  POST 둘 중 에서는 보안상 더 안전한 POST를 사용하는 것이 보편적인것으로 이해를 했습니다..!
좀 더 공부가 필요할 것 같아요! 키워드 감사드립니다!! 😊

2021-03-21 12:21 UTC, Jiwon-JJW commented
DB랑 연결이 안되어있어 회원가입이 안되는 문제를 해결하고, 코드 리뷰 남겨주신 것을 확인하여 최대한 수정 진행 하였습니다!

service는 리뷰를 기다리며 미션 4를 진행하고있던 상황이어서, 미션 4에서 적용하여 진행해보려고 합니다!
알려주신 키워드들이나 공부해봐야할 사항에 대하여 더 찾아보고 학습해보도록 하겠습니다!
감사합니다!😊

2021-03-21 13:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @GetMapping("/logout")
사실 POST가 보안상 더 안전하다? 는건 어폐가 있습니다.
이건 HTTP 좀 더 공부해보시면 아실 수 있어요. 그래도 공부해보셨으니 나중엔 더 이해하실 수 있을거에요~

2021-03-21 13:42 UTC, ksundong requested changes
안녕하세요! Starve! 피드백 반영해주시느라 수고하셨습니다.
조금 더 리뷰를 남겨봤구요.
애플리케이션 관련해서 오류로 보이는 동작이 있어 변경 요청 드립니다~

## 애플리케이션 관련 리뷰

- 날짜 포매팅을 한 번 시도해봐주세요.
- 회원 정보 수정시 비밀번호 인증을 하지 않네요. 확인해주세요.

코드 관련 리뷰는 다음 단계에서 반영해주셔도 되겠습니다~
고생하셨습니다!

2021-03-21 13:42 UTC, ksundong commented on build.gradle
>      runtimeOnly 'com.h2database:h2'
이럴 땐 그냥 implementation으로 사용해줘도 좋을 것 같네요~

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setCreatedDateTime(LocalDateTime createdDateTime) {
생각해보면 생성일자를 변경해줘야 할 경우가 있을까요~?

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public boolean userConfirmation(User loginUser) {
왠만하면 boolean형 타입의 메서드명은 boolean형 값을 반환함을 알 수 있도록 해주시는게 좋을 것 같아요.

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void update(Question updateQna) {
여기 매개변수명은 그대로 Qna네요.

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +        Object sessionUser = session.getAttribute(USER_SESSION_KEY);
그냥 inline으로 작성하는게 어떤가요~?

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/HttpSessionUtils.java
> +            throw new IllegalStateException("로그인 되어있지 않습니다. 로그인을 먼저 한 후, 시도해주세요.");
Custom 예외로 만들어주는게 어땠을까요?

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public String showOneQuestion(@PathVariable long id, Model model) {
너무 메서드가 솔직한 느낌이 있네요.

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public String showOneQuestion(@PathVariable long id, Model model) {
저라면 이미 Controller명으로 유추가 가능하기 때문에 빼줄 것 같아요.

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @PostMapping("{id}")
PostMapping말고 PutMapping을 써줍시다!

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +        Question question = qnaRepository.findById(id).orElseThrow(NoUserException::new);
`UserNotFoundException`이 일반적인 명칭인데, 이건 뭐 자유롭게 해보셔도 좋을 것 같네요,

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    public String delete(@PathVariable long id, HttpSession session) {
메서드 명이 일관적이지 않네요. 신경써주세요~

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    public String getUserList(Model model) {
`get`빼고 `userList`는 어때요?

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    public String editUserInfo(@PathVariable long id, Model model, HttpSession session) {
여기도 통일성 있는 이름을 지어주세요.

2021-03-21 13:42 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/UserController.java
>      @PostMapping("/{id}/form")
여기는 따로 변경사항이 없네요.

2021-03-23 09:10 UTC, Jiwon-JJW commented
안녕하세요 ! 말씀해주셨던 두가지 오류를 수정하여 다시 pr 요청드립니다! 
알려주신 코드 리뷰에 대해서는 미션 4에서 추가하였습니다! 감사합니다!!

2021-03-23 12:39 UTC, ksundong commented
Starve! 다음 단계에서 예외 처리 및 예외 핸들링을 해보세요~
`ExceptionHandler`에 대해서 알아봅시다~

게시글 수정이 안되네요! 다음 단계에서 고쳐주세요! 405 에러가 발생합니다!

2021-03-23 12:40 UTC, ksundong approved these changes
고생하셨습니다~
다음 단계에서 코멘트 남겨드렸던 부분 꼭 반영해주세요!!

2021-03-23 12:40 UTC, merged