[ Cooper ] 미션1: 회원 가입, 사용자 목록, 질문하기 구현
codesquad-members-2021/spring-boot-qna pull request #9
Opened 2021-03-03 17:24 UTC by pbg0205

안녕하세요.
코드스쿼드 마스터즈 백엔드 과정의 Cooper 입니다!
미션1 완료 및 리뷰받기 위해 PR 보냅니다.
부족한 부분이나 아쉬운 부분 있으시면 거침없는 피드백 부탁드립니다👉
리뷰해주시는데 시간 내어주셔서 감사합니다😁

### 배포 사이트 : [cooper-boot-qna.herokuapp.com](cooper-boot-qna.herokuapp.com)

## 주요 기능 구현 사항
### 1. 회원 가입 및 조회 기능 구현
- 회원가입에 관련된 기능은 /users 공통 url이 존재하여 @RequestMapping로 묶고 별개의 url을 mapping할 수 있는 구조로 작성하였습니다.
- 회원가입 완료 시, post.Method로 결과를 전송 후, redirect를 통해 회원 전체 목록을 조회할 수 있도록 하였습니다.

### 2. 질문 기능 구현
- 페이지 시작의 첫 부분이 질문 조회페이지이므로 QuestionController에 해당 요청 url을 처리할 수 있도록 구현하였습니다.
- 질문 등록 시, post.Mthod로 결과를 전송하고, redirect를 통해 질문 전체 목록을 조회할 수 있도록 구현하였습니다.
- 질문 세부사항의 경우, 해당 게시글의 index를 받아 QuestionController에서 해당 인덱스를 검색하고 Model 객체를 통해 view에 전달하는 방식으로 작업 진행하였습니다.

2021-03-04 10:28 UTC, SANGCO requested changes
Cooper님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setIndex(long index) {
`Question`, `User` 클래스에 안쓰는 setter가 있다면 제거해 봅시다.

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
저는 개인적으로 이 정도는 메서드로 안빼도 될거 같은네요.

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    List<Question> questionList = new ArrayList<>();
`private` 접근 제한자가 좋지 않을까요~

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @GetMapping("/")
여기도 `@GetMapping("/questions")` 이렇게 가는게 어떨까요?
그러면 `UserController `에 하신거 처럼 `@RequestMapping("/questions")` 이렇게 만들 수 있을거 같은데

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("")
`@PostMapping("/")` 저는 요렇게 한답니다.

2021-03-04 10:28 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        System.out.println("user: " + user);
향후에 로거 학습해서 로그로 남겨봅시다.

2021-03-04 10:28 UTC, SANGCO commented on src/main/resources/application.properties
> +pring.devtools.livereload.enabled=true
s가 지워진거 같네요.

2021-03-04 15:36 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @GetMapping("/")
기존에 Main.html에 해당하는 부분이 결국 전체 질문 조회창인 것 같아 QuestionController로 메서드를 이동시켜 보았습니다. @RequestMapping(/questions)로 변경할 경우 시작 링크를 /question으로 시작하거나 혹은 해당 Method를 MainController로 설정하는 방법을 고려하고 있는게 어떤 것이 더욱 괜찮은 방법이라고 생각하시나요??

2021-03-04 15:58 UTC, pbg0205 commented on src/main/resources/application.properties
> +pring.devtools.livereload.enabled=true
수정 작업에서 s가 누락되었던 것 같습니다ㅠ
말씀해주신대로 spring으로 수정 완료 하였습니다.
감사합니다!

2021-03-04 15:59 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        System.out.println("user: " + user);
기본적인 로거만 학습해서 System.out.print를 logger.info로 변경 해보았습니다.
확인부탁드립니다!

2021-03-04 16:00 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    List<Question> questionList = new ArrayList<>();
private로 수정 완료하였습니다!
기본적인 부분을 놓쳤네요ㅠ 주의하겠습니다!

2021-03-04 16:01 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public void setIndex(long index) {
불필요한 setter 제거 완료하였습니다.
코멘트 감사합니다ㅎㅎ

2021-03-04 16:05 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    }
생성자에 로직이 안들어가도록 하는 편이 좋다고 해서 일단 빼보았는데 저 정도는 괜찮다면 생성자에 포함해서 수정해보겠습니다ㅎㅎ

2021-03-04 16:56 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("")
넵! 말씀해주신 부분 수정완료 했습니다🔥
혹시 @PostMapping("/")으로 하시는 이유가 있으신지 궁금한데 혹시 말씀해주실 수 있을까요?

2021-03-04 16:58 UTC, pbg0205 commented
말씀해주신 부분에 대해 수정 및 궁금한 점에 대해 별도로 댓글 남겨두었습니다.
확인 부탁드리겠습니다. 감사합니다😁

2021-03-05 11:04 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("")
둘이 차이는 없는걸로 알고 있습니다~

2021-03-05 11:10 UTC, SANGCO commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @GetMapping("/")
메인 화면에서 질문 리스트가 뿌려지는거면
MainController로 옮기는게 좋을거 같네요~
향후에 ajax 학습하시고 나면 이부분도 다시 수정하실 수 있으실거에요.
일단은 MainController로 옮기고 넘어가시죠~

2021-03-05 11:24 UTC, SANGCO approved these changes
고생 하셨습니다~

2021-03-05 15:50 UTC, pbg0205 commented
네 히뷰해주셔서 감사합니다😃

2021-03-05 15:51 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/QuestionController.java
> +    @GetMapping("/")
네 우선적으로는 Question으로 가고 ajax 학습 후 변경하도록 하겠습니다!

2021-03-08 04:45 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +    @PostMapping("")
기분이 좀 좋다?

2021-03-08 04:46 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/UserController.java
> +        System.out.println("user: " + user);
Logger.info는 정말 중요한 정보라서 print는 없애버리거나 logger.debug()를 사용하는 것이 좋을 것 같아요.

2021-03-08 04:46 UTC, merged