[NAS] 미션4. 객체-관계 매핑
codesquad-members-2021/spring-boot-qna pull request #93
Opened 2021-03-20 02:56 UTC by Malloc72P

안녕하세요? 
백엔드 클래스의 NAS라고 해요. 😄 

미션4를 완료해서 PR을 남기게 되었어요.

배포주소는 [여기예요!](https://spring-qna-nas.herokuapp.com/)

### 1. 답변기능 구현 및 Soft Delete
답변기능은 미션3때 구현해서, 이번에는 Soft Delete만 추가했어요. Soft Delete는 `@SQLDelete`어노테이션을 이용해서 구현했어요.
```java
@Entity
@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
public class Answer extends BaseTimeEntity {
```
이렇게 하니까, 어떤 레코드를 삭제할 때, delete쿼리 대신, 위에서 지정한 update쿼리로 수정하더라구요. 정말 신기했어요.
h2-console을 통해서 레코드는 남아있지만, deleted값이 true로 바뀌어있는걸 확인했어요.

### 2. Soft Delete된 객체검색 방지
CrudRepository에서 어떤 객체를 찾는 메서드의 이름에 `~~DeletedFalse`를 추가했어요.
```java
Optional<Answer> findByIdAndDeletedFalse(Long id);
```
위와 같이 하니까 Soft Delete된 객체는 검색하지 않는것을 확인했어요! 그 외의 Soft Deleted된 객체에 대해서도 위와 같이 설정했습니다!

### 3. JPA Auditing기능 사용 : 생성일, 수정일 자동화
User, Question, Answer 엔티티에서 `BaseTimeEntity`를 상속받도록 했어요. `BaseTimeEntity`는 `@CreatedDate`랑 `@LastModifiedDate`어노테이션을 이용해서 생성일과 수정일을 관리해줍니다. 이 기능을 통해서 모든 엔티티 객체에 대한 생성일과 수정일을 자동으로 추가하고 관리하도록 했는데, 편리하고 유용한 기능같네요.

### 4. 에러페이지 추가 : 커스텀 에러페이지 및 404 등등...
커스텀 에러페이지에 대해서 공부해보았습니다! `template/error`밑에 페이지를 작성하면 에러페이지를 등록할 수 있더라구요. 그래서 404, 405, 500, 그리고 그 외의 상황에 대한 에러페이지를 만들고 적용했어요. 그 외의 상황에는, 자신의 답변이 아닌데 지운다거나 하는 경우에 에러페이지를 보여주도록 했습니다. 예전에는 무조건 홈으로 보냈는데, 이제는 지금 어떤 문제가 발생했는지 사용자가 알 수 있게 해줘서 좋은 것 같습니다.

이상으로 글을 마치겠습니다!

리뷰 잘 부탁드립니다! 😄

2021-03-20 16:53 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    private void validateAuthorizedAccess(Question currentQuestion, User loginUser) {
중복되는 validation 메서드로 뽑아내니까 코드가 훨씬 깔끔해지네요. NAS 👍

2021-03-20 16:54 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
중복되는 validation 메서드로 뽑아내니까 코드가 훨씬 깔끔해지네요. NAS 👍

2021-03-20 17:59 UTC, pbg0205 commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
이렇게 하는 방법이 있네요! Question을 삭제할 때 연쇄적으로 Answer도 사라져서
 어떻게 할지 고민하고 있었는데👍👍
한수 배웁니다!

2021-03-21 01:12 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
계속 고민하다가 이렇게 했는데, 깔끔해보인다니 다행이네요! 😄

2021-03-21 08:38 UTC, sanhee commented on src/main/java/com/codessquad/qna/web/questions/QuestionsController.java
> +    }
👍 👍

2021-03-21 15:26 UTC, ksundong requested changes
안녕하세요! NAS!! 리뷰어 Dion 입니다.
먼저 미션 4단계까지 진행해주시느라 고생많으셨습니다.
몇가지 제안사항이 있어, **변경 요청**을 드립니다.

## 애플리케이션 관련 리뷰

- 빈 데이터를 넣어서 회원가입이 가능하고, 글 작성도 가능해보입니다. 한 번 다음단계에서는 이를 어떻게 방지할 수 있을지 고민해보세요.
- 글 작성시 글쓴이 필드는 이전 요구사항에서 제거되었어야 했을겁니다. 그대로 두신 이유가 있나요?
- '질문자와 답변 글의 모든 답변자 같은 경우 삭제가 가능하다.' 는 요구사항이 충족되지 않았습니다.

## 코드 관련 리뷰

- 서비스 분리를 수행해주세요.
- url 설계에 대해서 한 번 더 고민해주세요.
- 메서드 네이밍에 대해서 고민해주세요.

세세한 내용은 코멘트를 참고해주세요. 4단계 진행하느라 고생많으셨습니다.
코멘트 보시면서 궁금하신 부분, 도움이 필요한 부분, 이해가 가지 않는 부분, 토론하고 싶은 부분에 대해서 코멘트 남겨주세요.
고생하셨습니다~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    private final AnswersRepository answersRepository;
이제는 서비스를 분리할 때가 된 것 같네요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
url 설계 뭔가 이상한 것을 못느끼셨나요?
`/questions/answers/{answerId}` 인데, 한 번 다시 생각해보세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
메서드 네이밍 다시 고민해봐주세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
`getXXX` 식 네이밍은 좋지 않다고 생각합니다.
한 번 좋은 네이밍을 고민해봐주세요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question currentQuestion = verifyQuestionAndGet(session, questionId);
그냥 question이어도 충분할 것 같네요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +    }
서비스 계층 분리하면서 `private` 메서드들 제거해보세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(UsersController.class);
Java 컨벤션에 따르면, 필드 순서도 정해져 있습니다.
한 번 찾아보세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +    @PutMapping
이렇게 되면 `/users`라는 리소스를 수정한다는 의미입니다.
의도하시는 바를 명확히 표현하는 url을 선택해주세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +            throw new UnauthorizedAccessException("자신이 작성한 질문만 수정 혹은 삭제할 수 있습니다");
예외에 문자열을 담는 형태로 구현해봐주세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +            throw new UnauthorizedAccessException("패스워드가 일치하지 않습니다");
이 상황은 예외적인 경우인가요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +    private void verifyAuthorizedAccess(User user, String password) {
중복제거 좋네요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +                    .orElseThrow(UserNotFoundException::new);
이거 줄바꿈 해줘야 할 정도로 긴가요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +        } catch (RuntimeException e) {
특정한 Exception을 한정해서 Catch해주시고, 과연 RuntimeException을 catch 해주어야 하는지도 고민해보세요~

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
이런 방법도 있군요. ㅎㅎ
객체를 좀 더 활용했으면 어떨까 하는 생각도 드네요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @Column(columnDefinition = "BOOLEAN DEFAULT FALSE")
아래에 이미 `false`를 써줘서 굳이 필요없는 것 같네요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    private Boolean deleted = false;
왜 Wrapper type인가요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
>      public Answer() {
기본 생성자가 `public`이면 어떤 문제가 생길 수 있을까요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    public Boolean getDeleted() {
```suggestion
    public boolean isDeleted() {
```

이 편이 훨씬 일반적인 네이밍 입니다.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    public Boolean getDeleted() {
가급적이면 인텔리제이의 getter 생성기를 이용해주세요.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    private Boolean deleted = false;
nullable이 false인데, Wrapper Type을 써주신 이유가 있나요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    private void processErrorState(String errorMessage, Exception exception, Model model) {
왜 `process`인가요?

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +    public String date(LocalDateTime date) {
왜 `date`인가요?

2021-03-21 15:26 UTC, ksundong commented on src/main/resources/templates/error/500.html
> +<H2 class="error-text">서버가 많이 아파요...... 흑흑</H2>
😆

2021-03-21 15:26 UTC, ksundong commented on src/main/resources/templates/error/global-error.html
> +<H2 class="error-text">수행할 수 없는 명령입니다!</H2>
요즘은 태그에 대문자를 사용하지 않습니다.

2021-03-21 15:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +    public String date(LocalDateTime date) {
뭔가 handlebar에서 읽히기 좋게 해주려고 하신 느낌이네요. 👍

2021-03-22 01:13 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    private final AnswersRepository answersRepository;
넵! 알겠습니다. 이번에 `스프링 부트와 AWS로 혼자 구현하는 웹서비스`라는 책을 샀는데, 이 책을 좀 읽어보고 서비스를 분리해보도록 하겠습니다!

2021-03-22 01:18 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
자꾸 URL 설계를 실수해서 부끄럽네요. 😞 
URL 설계에 관한 규칙을 다시 찾아보았어요. [관련 내용이 담긴 PDF](https://blog.appkr.dev/files/again2011_workshop_keynote_2.pdf)
링크에 있는 PDF파일을 보니까 `관계를 노출할 땐 리소스 중첩`을 하라고 하네요!
그런데, 저처럼 `questions/answers/:id`이런식이 아니라 `questions/:id/answers` 이런식으로 하는게 맞는 것 같군요!
수정해서 커밋하도록 하겠습니다!

2021-03-22 01:26 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
에구... 같은 내용으로 또 리뷰달리게 해서 죄송합니다 ㅠㅠ

변수명과 메서드 네이밍에 관한 규칙이 있는지 좀 더 찾아보고, 다른 분들은 이름을 어떻게 지어주셨는지 찾아보았어요.
음... 홈페이지 요청하는거니까 `requestHome()`으로 지어주면 좋지 않을까 라는 생각이 드네요. `사용자가 컨트롤러한테 홈페이지를 요청` 하는거니까 이거면 괜찮을 것 같은데 어떤가요?

2021-03-22 01:28 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
그렇군요... `getXXX`식의 네이밍을 피하고자 하는건 getter메서드랑 혼동되는걸 피하기 위해서인가요?

`getQuestionList`이랑 `getOneQuestion`메서드도 컨트롤러한테 요청하는거니까 `get` 대신 `request`로 바꿔주고, 뒤에 `Page`라는 단어를 추가해주면 좋을 것 같아요! 괜찮을까요?

2021-03-22 01:29 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question currentQuestion = verifyQuestionAndGet(session, questionId);
넵! 메서드를 추출하면서 변수명도 고쳐주면 좋았을 텐데 놓쳐서 아쉽네요!

2021-03-22 01:33 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +    }
넵! 이 부분도 서비스 공부하면서 반영하도록 하겠습니다!

2021-03-22 01:36 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
오, 좀 더 생각해보니까 `/questions/answers/:id`면 이건 마치 answers의 아이디같다는 생각이 들 수 있겠군요! 저렇게 할때는 딱히 별 생각 없었는데 리뷰받고 다시 보니까 엄청 어색하네요 ㅋㅋㅋㅋ 빨리 수정해서 커밋하겠습니다! 알려주셔서 감사합니다!

2021-03-22 01:37 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
이것도 뒤에 `Page`를 붙여서 `requestHomePage`라고 해주면 좀 더 나을 것 같아요!

2021-03-22 01:41 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +    @PutMapping
아하, 실제 메서드는 유저 하나를 수정하는건데, 위와 같이 하면 `users`, 즉 복수의 `user`를 수정한다는 의미가 되버리니까 올바른 의미가 아니겠군요. 이건 `@PutMapping("/{userId}")`로 바꿔줘야겠네요!

2021-03-22 01:52 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +            throw new UnauthorizedAccessException("자신이 작성한 질문만 수정 혹은 삭제할 수 있습니다");
이렇게 하면 괜찮을까요?
```java
String EXCEPTION_MESSAGE_UNAUTHORIZED_ACCESS_ON_QUESTION = "자신이 작성한 질문만...";
 private void verifyAuthorizedAccess(Question currentQuestion, User loginUser) {
        if (!currentQuestion.isMatchingWriter(loginUser)) {
            throw new UnauthorizedAccessException( EXCEPTION_MESSAGE_UNAUTHORIZED_ACCESS_ON_QUESTION  );
        }
}
```
일단 이렇게 하면 나중에 예외관련 메세지를 하나의 파일에 담아서 일괄관리할 수도 있고, 수정하기도 편해질 것 같아요!

2021-03-22 02:58 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +            throw new UnauthorizedAccessException("패스워드가 일치하지 않습니다");
네 저는 예외적인 경우라고 생각했어요. `verifyAuthorizedAccess`메서드는 허가된 접근인지 검사하는 메서드예요. 이게 실패했다면, 더 이상 다음 작업을 진행할 수 없으니까 예외적인 상황이라고 생각했어요.

2021-03-22 03:00 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +                    .orElseThrow(UserNotFoundException::new);
메서드 체이닝으로 연결하면 저렇게 줄바꿈을 해줘야 가독성에 도움이 되지 않을까 해서 띄워줬어요. 😄 
근데 저건 안 띄워줘도 괜찮겠다는 생각이 드네요. 수정해서 다시 커밋하겠습니다

2021-03-22 03:02 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +        } catch (RuntimeException e) {
아 저러면 `UserNotFoundException`이랑 `UnauthorizedAccessException`이 아닌 다른 RuntimeException이 발생해도 저 catch문에 걸리겠군요! 이건 문제가 되겠네요. 위의 두 커스텀 예외에 대해서만 catch하도록 수정하겠습니다!

2021-03-22 03:17 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
`SoftDelete`하는 방법에 대해 찾아보다가 저런 방법을 찾게 되었어요! 😄 

`객체를 좀 더 활용하는 방법`이라고 하셨는데, 혹시 이게 어떤 방법인지 여쭤봐도 될까요?

2021-03-22 03:29 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    @Column(columnDefinition = "BOOLEAN DEFAULT FALSE")
넵 알겠습니다!

2021-03-22 03:35 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    private Boolean deleted = false;
`컬럼의 Nullable속성을 표현하기 위해서!` 였습니다만, 생각해보니 애초에 이 필드는 NULL이 되어선 안되는 필드네요. 
그냥 프리미티브 타입으로 하고, `Column`에서 `nullable = false`를 추가해주는 편이 더 의미있을 것 같네요!

2021-03-22 05:14 UTC, Malloc72P commented on src/main/resources/templates/error/global-error.html
> +<H2 class="error-text">수행할 수 없는 명령입니다!</H2>
앗 그렇군요! 수정하도록 하겠습니다!

2021-03-22 05:16 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/utils/HandlebarDateHelper.java
> +    public String date(LocalDateTime date) {
핸들바 핼퍼는 메서드 이름을 핼퍼의 이름으로 쓴다고 하더라구요. 템플릿에서 날짜출력할때 너무 긴 이름보다는 짧은 `date`정도가 적당할 것 같아서 이렇게 지어주었습니다.

2021-03-22 05:20 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    private void processErrorState(String errorMessage, Exception exception, Model model) {
의도는 에러처리하는 중복코드를 처리한다는 의미였는데, 지금보니까 에러상황을 처리한다는 이름으로 보이네요. 실제로는  에러를 어떻게 처리해주는것도 아니니까 process라는 이름은 부적절한 것 같아요.
이게 참 이름짓는게 애매하네요. 이 경우엔 `initializeModelObject()`로 하는게 어떨까 싶어요. 이 메서드에서 하는 일이 결국 예외객체를 가지고 모델 객체에다가 `addAttribute`하는거니까 모델객체를 초기화한다는 이름이면 좋지 않을까 싶네요. 아...... 이름짓는거 진짜 어려워요.......

2021-03-22 05:21 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    private Boolean deleted = false;
nullable이 false이니까 `nullable`을 표현할 수 있는 wrapper type의 사용은 무의미하겠네요. 좀 더 주의하면서 코드를 작성하도록 하겠습니다!

2021-03-22 05:24 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    public Boolean getDeleted() {
그렇군요! 주의하도록 하겠습니다! 수정해서 다시 커밋할께요!

2021-03-22 07:17 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
>      public Answer() {
찾아보니까 기본생성자가 필요한 이유는  JPA가 DB에서 데이터를 가져와서 객체를 생성할때 기본생성자를 쓰기 때문이었군요. 그래서 public이나 protected로 기본생성자를 만들어야 하는건데, 이게 public이면 개발자가 실수로 비어있는 엔티티 객체를 만들 수 있을 것 같아요! protected로 하기만 해도 이런 실수를 방지할 수 있으니 좋을 것 같다는 생각이 들었습니다!

2021-03-22 09:22 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
request는 행위의 주체가 누굴까요?
애초에 메서드를 호출한다는 것 자체가 객체에게 요청한다는 의미입니다~
굳이 request를 붙여줘야할까요?

2021-03-22 09:23 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
사람은 `getter`와 get을 구분하지만, 프로그램은 구분하지 못합니다.
그런점도 있고, `get`으로 시작하는 이름은 대부분 객체지향을 온전히 못살리는 경우가 많아서 지양하는 편이에요.
`request`와 `Page`는 정말 필요할지 고민해보세요~

2021-03-22 09:24 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
코드엔 정답이 없기 때문에 제가 말씀드리는건 제 의견입니다.
`getXXX` 식의 네이밍 쓰는분도 정말 많구요. 근데, 제가 느끼기엔 `get`의 단점이 너무 많아서, 지양하는 것을 권유드리고 있어요.

2021-03-22 09:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +            throw new UnauthorizedAccessException("자신이 작성한 질문만 수정 혹은 삭제할 수 있습니다");
되도록이면 그렇게 해주는 편이 좋죠~
장점을 아셨으면 좋겠네요~

2021-03-22 09:25 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(UsersController.class);
필드순서라면 static여부에 따라서 코드를 배치하는 규칙이 있는 모양이군요! 이참에 자바 컨벤션 규칙을 찾아보고 적용해보겠습니다!

2021-03-22 09:25 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +            throw new UnauthorizedAccessException("패스워드가 일치하지 않습니다");
그런 근거가 있다면 좋은 것 같아요.

2021-03-22 09:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +                    .orElseThrow(UserNotFoundException::new);
보통 한 줄로 읽히면 그냥 두는게 좋아요.
줄 바꿈이 들어가는 경우 한 줄 한 줄 떼어주는 편이 세로로 나열되어있어서 가독성이 높아지구요.

2021-03-22 09:26 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +        } catch (RuntimeException e) {
`ExceptionHandler`가 필요하지는 않은지도 생각해보세요~

2021-03-22 09:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
객체에게 `delete()`를 했을 때, soft delete 되도록 구현해보세요~

2021-03-22 09:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    private void processErrorState(String errorMessage, Exception exception, Model model) {
이름을 지을 때, 메서드가 내부에서 어떻게 처리해서 이 동작을 수행하는지는 신경쓰지말고 지어보세요.
우리는 이 메서드가 어떤 일을 해주면 되는거지, 어떻게 하는것에는 별 관심이 없습니다.

2021-03-22 10:18 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
아 그렇네요! 토끼책에서 읽은 것 같아요! 객체가 다른 객체한테 이것좀 해달라고 요청을 하는거니까 결국 메서드를 호출하는건 그 객체한테 요청하는게 되네요. 그러면 request는 당연한거니까 생략할 수 있겠어요. 그러면 그냥 home 정도로 이름을 지어도 충분할 것 같습니다!

사실 이걸 좀 더 알고 싶어서 다른 클래스는 어떻게 되어있나 찾아봤어요. `ArrayList`를 보니까 `size`같은건 ArrayList객체한테 `너의 크기를 알려줘!`라고 요청하는거고 이름이 `size`이더라구요. 그러니 제 경우엔 홈컨트롤러한테 홈페이지를 줘! 라고 요청하는거니까 home이면 좋지 않을까 라는 생각이 들었습니다!

2021-03-22 10:21 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
위의 코멘트와 동일하게, request는 생략가능한 표현 같아요! 그래서 이 경우엔 컨트롤러한테 `질문 상세보기 페이지를 줘!`라고 요청하는거니까 `showQuestionDetailPage`로 고쳐주면 좋을 것 같아요.

2021-03-22 10:24 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +    private void processErrorState(String errorMessage, Exception exception, Model model) {
객체한테 뭘 요구하고자 하는건지, 다시 말해서 객체가 어떤 일을 해줘야 하는지에 초점을 맞춰서 메서드 이름을 짓도록 해보겠습니다!

2021-03-22 10:27 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +@SQLDelete(sql = "UPDATE ANSWER SET DELETED = TRUE WHERE ID = ?")
오, 그렇게 해보면 재밌을 것 같네요! 이번엔 객체를 활용해서 soft delete해보도록 하겠습니다! 이 부분도 수정해서 다시 커밋할께요! 😄

2021-03-22 10:28 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +        } catch (RuntimeException e) {
넵! 좀 더 고민해보도록 하겠습니다!

2021-03-22 10:29 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/UsersController.java
> +                    .orElseThrow(UserNotFoundException::new);
하긴 한줄이면 충분한데 굳이 띄우는것도 오히려 가독성을 해칠 수 있을 것 같아요! 감사합니다! 이 부분도 수정해서 커밋할께요!

2021-03-22 13:42 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
좀 더 고민해보니까, 어떤 question에 종속된 어떤 answer를 삭제하는 요청이니까, 리소스를 중심으로 URL을 설계하면 `/questions/:questionId/answers/:answerId`면 좋겠다는 생각이 드네요!

2021-03-22 22:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +    @DeleteMapping("/answers/{answerId}")
고민 많이 하셨네요 ㅎㅎ 저도 그 편이 좋은 것 같습니다.

2021-03-22 22:27 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/HomeController.java
> +    public String processHomePathRequest() {
오 토끼책 보셨군요 대단하시네요.

2021-03-22 22:28 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
>      public String getOneQuestion(@PathVariable("questionId") long questionId, Model model) {
Page는 어차피 보여줄거니까 `showQuestionDetail` 정도가 무난할 것 같아요.

2021-03-23 12:36 UTC, ksundong commented
@Malloc72P 
혹시 반영이 다 된건가요? 되셨다면 리뷰 요청 남겨주세요~

2021-03-23 12:53 UTC, Malloc72P commented
아직입니다! 완료되는대로 요청드리겠습니다!

2021-03-24 03:19 UTC, Malloc72P commented
안녕하세요 디온! 리뷰받은 내용을 반영해서 코멘트를 남깁니다!

수정한 내용을 요약해서 정리해보았습니다!

### 1. 서비스 분리 & 빈 데이터로 객체생성 가능한 문제
* 컨트롤러에 섞여있던 비즈니스 로직을 추출해서 서비스로 옮겼습니다!
* 서비스로 옮기니까, 컨트롤러에는 `@xxxMapping`이 붙은 메서드만 있게 되어서 코드를 보기가 더 편해졌어요!
* 비즈니스 로직만 분리하니까, 여기에 기능을 추가하기도 수월해지더라구요. 그래서 빈 데이터가 들어오는지 검사하는 로직도 추가했습니다. 그래서 이제 빈 데이터로 객체를 생성하지 못하게 막았습니다. 또 에러페이지로 왜 실패했는지도 보여주도록 구현했습니다!
* ![image](https://user-images.githubusercontent.com/41663269/112247727-28a8c980-8c98-11eb-9609-5768981deb66.png)

### 2. 소프트 딜리트를 객체를 활용하는 방법으로 수정하기 & 요구사항을 지키지 못한 문제
* 다른 분들은 어떻게 했나 찾아보고, 제 코드도 객체를 활용해서 소프트 딜리트를 하도록 수정했습니다
* 그리고, 요구사항에서 `질문자와 답변 글의 모든 답변자 같은 경우 삭제가 가능하다.`라는 요구사항을 만족시키기 위해서, 질문자와 답변자가 같은 경우엔 지울 수 있게 하고, 다르다면 예외가 발생하도록 해서 삭제하지 못하도록 수정했습니다. 그래서 이젠 내가 작성한 질문글이라도, 다른 사람이 답변을 남기면 지울 수 없게 되었습니다
* 이 부분도 에러페이지를 이용해서 왜 실패했는지 사용자에게 알려줄 수 있도록 구현했습니다
* ![image](https://user-images.githubusercontent.com/41663269/112248055-a2d94e00-8c98-11eb-9189-f00be59fc4c3.png)

### 3. 글 작성시 글쓴이 필드를 남겨둔 이유
* 글쓰기를 할 때, 지금 로그인된 계정이 어떤건지를 사용자에게 알려주고 싶었습니다.
* 만약 지금 로그인 된 계정이 자기가 생각한 거랑 다른 계정이었다면 실수할 수도 있으니까요.
* 그래서 글쓴이 필드를 남겨두었습니다. 
* 하지만 해당 필드에 `disabled` 속성을 주었기 때문에 서버에 전송하지 않습니다

### 4. 메서드 이름짓는 문제
* ㅎㅎ 이건 진짜 고민하면 할수록 어려워지는 문제인 것 같습니다 ㅋㅋ
* 일단 최대한 고쳐보았습니다. 그렇지만 아직 이름에 문제있는 메서드나 변수가 남아있을 수 있어요 ㅎㅎ;; 😄 
* 그리고 이름짓기에 대한 저만의 생각을 정리해보았습니다
  * 주석이 없어도 이해할 수 있도록 도와주는 변수명과 메서드명을 짓자.
  * 메서드명만 봐도 역할이 뭔지 알 수 있도록 해주자. 그래야 이 객체한테 뭘 요청하는건지 명확하게 알 수 있다.
  * 너무 복잡한 이름보다는 단순한 이름을 지어주자
* 이 생각을 갖고 이런 코드를 작성해보았습니다
```java
public void modifyUser(long id, String prevPassword, User newUserInfo, User loginUser) {
    User foundUser = userRepository.findById(id).orElseThrow(UserNotFoundException::new);
    verifyIsSameUser(loginUser, foundUser);
    verifyPassword(loginUser, prevPassword);
    verifyUserEntityIsValid(newUserInfo);

    loginUser.update(newUserInfo);
    userRepository.save(loginUser);
}
```
* 메서드 이름을 저렇게 지으니까, 딱히 주석이 필요없어지는 것 같습니다. 같은 유저인지 확인하고, 패스워드를 확인하고, `newUserInfo`엔티티객체가 비어있지는 않은지 확인하고, 그런 다음 update한 다음 save하라는 것이 이름만 봐도 알 수 있으니까 좋지 않을까 라는 생각이 들어요!

이상으로 글을 마치겠습니다!

디온! 많이 피곤하실텐데도 제 코드를 진짜 꼼꼼하게 봐주셔서 정말 감동입니다 😭 
코드리뷰 정말 정말 감사드려요!

2021-03-24 12:37 UTC, ksundong approved these changes
고생하셨습니다. 변경된 부분이 많아 시간이 좀 걸렸네요 ㅎㅎ
다음 단계 진행해주셔도 될 것 같고, 제가 생각하는 코드에 대해서 피드백을 남겼으니 확인해주시면 좋을 것 같아요.
고생하셨습니다~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +        Question targetQuestion = answerService.deleteAnswer(loginUser, answerId);
요거는 조금 특이한데, 저는 이렇게 안하시는게 좋을 것 같아요!

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +        Question targetQuestion = answerService.deleteAnswer(loginUser, answerId);
우리는 questionId를 알고 있습니다. 그렇죠?
그렇다면 해당 question에 answer가 있는지만 확인하는게 어떨까요?
메서드 구현이 궁금해지네요.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +    private final QuestionService questionService;
```suggestion
    private static final Logger LOGGER = LoggerFactory.getLogger(QuestionsController.class);
    
    private final QuestionService questionService;
```

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +    private final QuestionService questionService;
저는 private static final은 소문자로 사용해도 된다고 생각해요~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question modifiedQuestion = questionService.verifyIsOwnerAndGetQuestionDetail(questionId, loginUser);
메서드가 너무 많은 일을 하는건 아닐까요?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question modifiedQuestion = questionService.verifyIsOwnerAndGetQuestionDetail(questionId, loginUser);
제가 생각하기엔 너무 많은 일을 하는 것 같아요.
저라면 Question을 가져와서 Question에서 verify하는 식으로 구현할 것 같네요~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question modifiedQuestion = questionService.verifyIsOwnerAndGetQuestionDetail(questionId, loginUser);
그리고 modify 되지 않았는데 modified가 맞을까요?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    private boolean deleted = false;
```suggestion
    private String contents;
    
    private boolean deleted = false;
```

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        return !contents.isEmpty();
```suggestion
        return contents != null && !contents.isEmpty();
```

이렇게 바꿔주면 어떨까요~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
>      }
이 메서드는 필요할까요?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/AnswersRepository.java
> +    Optional<Answer> findByIdAndDeletedFalse(Long id);
👍

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
Column정의에 굳이 DEFAULT FALSE를 줘야할까요?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
이는 두 가지 역할을 하고 있습니다. 한 가지 역할만 하도록 바꿔보세요~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        return !title.isEmpty() && !contents.isEmpty();
이것도 boolean형으로 변수명을 추출하면 if문 없이도 되겠네요.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +        return !password.isEmpty() && !name.isEmpty() && !email.isEmpty();
어쩌면 if문을 여러개 넣는 편이 나을 수도 있습니다.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +        initializeModel("현재 로그인된 상태가 아닙니다", exception, model);
exception에 메세지를 넣어두는 식으로 구현한다던지 하면 더 나을 수도 있을 것 같아요.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +        if (!answer.isValid()) {
valid안에서 예외를 리턴하도록 하면 이 문제가 해결되겠죠?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    }
과연 service에서 verify하는 것이 맞는지 고민을 해보세요~

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        verifyUserEntityIsValid(newUserInfo);
필요한 부분만 verify해줍시다~ password verify는 필요없을 것 같아요.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User foundUser = null;
저는 이런식의 구현을 별로 좋아하지 않습니다 ㅎㅎ
그냥 바로 return하는 식으로 구현해봅시다.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        }
예외 래핑은 좋은데요. 이게 사용자에게 바로 전달된다면, 보안상 좋지 않을겁니다.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        }
그리고 ExceptionHandler에 대해서 학습해보시고, 적용해보세요.

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/ExceptionConstants.java
> +    public static final String CAN_NOT_DELETE_BECAUSE_ANOTHER_USERS_ANSWER_IS_EXISTS = "다른사람의 답변이 존재하므로 질문을 삭제할 수 없습니다";
굳이 전역에서 쓸 수 있는 상수로 만들어줘야 했을까요?
저는 이 부분은 과하다고 생각해요 ㅎㅎ
Exception Class에서 관리해도 되지 않을까요?

2021-03-24 12:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/ExceptionConstants.java
> +    }
빈 블럭도 가급적이면 일치시켜서 정렬해주세요~

2021-03-24 12:37 UTC, merged

2021-03-24 13:50 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/AnswersController.java
> +        Question targetQuestion = answerService.deleteAnswer(loginUser, answerId);
오 그러네요! 어차피 questionId를 알고 있으니까 굳이 `answerService.deleteAnswer()`에서 Question객체를 반환해줄 필요가 없겠네요. 거기다가 해당 question에 answer가 있는지 확인해주는 로직을 추가해주면 좋을 것 같네요! 다음 미션 시작할때 반영하도록 하겠습니다!

2021-03-24 13:51 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +    private final QuestionService questionService;
오 static이라고 해서 무조건 대문자로 쓸 필요는 없군요! 저도 `LOGGER` 보다는 `logger`로 쓰고 싶어요! 😄

2021-03-24 13:54 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/controller/QuestionsController.java
> +        Question modifiedQuestion = questionService.verifyIsOwnerAndGetQuestionDetail(questionId, loginUser);
그러네요. 메서드에 너무 많은 일을 부여한 것 같아요. Question에서 확인하고, 예외를 발생시키도록 수정하는 편이 덜 복잡할 것 같아요! 

아 그리고 `modifiedQuestion`은 제 실수입니다 ㅋㅋ 변수명도 마저 고쳐줬으면 좋을텐데 자꾸 하나씩 흘리네요! 조심하겠습니다!

2021-03-24 13:55 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +    private boolean deleted = false;
띄워주는 편이 더 좋군요! 수정하도록 하겠습니다!

2021-03-24 13:57 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
> +        return !contents.isEmpty();
와우 한줄로 줄었네요! 여기는 하나의 필드만 확인하면 되니까 이렇게 해주는게 더 깔끔하고 좋은 것 같습니다!

2021-03-24 13:58 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Answer.java
>      }
이제 필요없겠네요! delete메서드가 있으니까요! 알려주셔서 감사합니다!

2021-03-24 13:59 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
헉, 지워준다고 했던 것 같은데 빠뜨린 모양이예요! 얘는 nullable = false에다가 엔티티에서 false로 초기화해주니까 필요없을 것 같습니다!

2021-03-24 14:00 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +    }
answer 리스트를 검사하는 메서드를 하나 만들어주면 좋겠네요! 요것도 다음 미션 시작할때 바로 반영할께요!

2021-03-24 14:12 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/Question.java
> +        return !title.isEmpty() && !contents.isEmpty();
이렇게 말씀하시는건가요?
```java
return title != null && !title.isEmpty() && contents != null && !contents.isEmpty();
```
확실히 이렇게 하면 한줄로 작성할 수 있어서 더 깔끔할 것 같아요!

2021-03-24 14:12 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +        return !password.isEmpty() && !name.isEmpty() && !email.isEmpty();
세개는 좀 길 것 같네요 ㅋㅋ

2021-03-24 14:13 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/domain/User.java
> +        return !password.isEmpty() && !name.isEmpty() && !email.isEmpty();
그래도 얘도 한줄로 하는게 깔끔하고 좋을 것 같아요!

2021-03-24 14:18 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +        initializeModel("현재 로그인된 상태가 아닙니다", exception, model);
지금도 `throw new NoLoginUserException(ONLY_FOR_LOGGED_IN_USER)`이렇게 예외에 메세지를 담고 있어요! 왜 이런 예외가 발생했는지는 예외가 발생한 시점에서 더 잘 알고 있어서, 예외를 생성하는 시점에서 메세지를 예외에 실어서 발생시키도록 구현했습니다!

2021-03-24 14:18 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/AnswerService.java
> +        if (!answer.isValid()) {
맞아요! 이렇게 하는게 더 깔끔할 것 같아요!

2021-03-24 14:19 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/QuestionService.java
> +    }
위의 코멘트와 연계되는 내용 같네요! 처음엔 서비스에서 verify하는게 옳다고 생각했는데, 다시 생각해보니까 `Question`이나 `Answer`에서 `isValid`할때 `verify`까지 하면 수고가 줄어들 것 같습니다!

2021-03-24 14:29 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        verifyUserEntityIsValid(newUserInfo);
해당 기능은 개인정보 수정기능이네요! 요구사항에서 `비밀번호가 일치하는 경우에만 수정 가능하다` 라고 되어 있어서 prevPassword를 입력받고, 이게 로그인된 사용자의 패스워드와 일치할때만 개인정보를 수정할 수 있도록 구현했습니다!
제 생각엔 `verifyPassword(loginUser, prevPassword);`는 필요할 것 같아요!

2021-03-24 14:34 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User foundUser = null;
익셉션을 throw하고 익셉션핸들러에서 `"redirect:/users/login-form";`시키는 부분을 말씀하시는거죠?
저도 이 부분은 계속 고민하다가 결국 익셉션핸들러를 통해 처리되도록 수정했는데, 그냥 서비스에서 리턴하도록 해도 좋겠군요!

2021-03-24 14:36 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        }
이런 정보가 사용자에게 노출되면 왜 로그인에 실패했는지 알 수 있으니까, 적어도 아이디를 맞춰보는데 악용될 수 있겠네요. 
지금은 이 정보가 노출되지 않아서 다행이네요. 앞으로 이런 문제에 대해 주의하도록 하겠습니다!

아 그리고 ExceptionHandler에 대해서 더 공부해보겠습니다!

2021-03-24 14:38 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/utils/ExceptionConstants.java
> +    }
넵! 주의하도록 하겠습니다!

2021-03-24 14:51 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/utils/ExceptionConstants.java
> +    public static final String CAN_NOT_DELETE_BECAUSE_ANOTHER_USERS_ANSWER_IS_EXISTS = "다른사람의 답변이 존재하므로 질문을 삭제할 수 없습니다";
따로 상수 클래스를 만들고 일괄 관리하는편이 더 효율적일 것 같아서 이렇게 했어요 😄
그런데 해당하는 Exception 클래스에 문자열 상수를 쓰는것도 좋은 방법인 것 같아요! 생각치도 못했던 방법인데, 괜찮은 방법 같아요!

2021-03-24 15:35 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/exceptions/ControllerExceptionHandler.java
> +        initializeModel("현재 로그인된 상태가 아닙니다", exception, model);
NoLoginUserException 자체가 로그인 된 상태가 아니라는 의미를 담고있지 않을까요?
그러면 거기서 꺼내는 식의 구현을 해봐도 좋을 것 같아요.

2021-03-24 15:36 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        verifyUserEntityIsValid(newUserInfo);
앗 그렇네요 ㅎㅎ

2021-03-24 15:37 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User foundUser = null;
아뇨~ foundUser가 null이 되는 구간이 존재하는 것 보다는 try 안에서 충분히 선언되고 return 될 수 있다고 생각해요!

2021-03-24 15:38 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/utils/ExceptionConstants.java
> +    public static final String CAN_NOT_DELETE_BECAUSE_ANOTHER_USERS_ANSWER_IS_EXISTS = "다른사람의 답변이 존재하므로 질문을 삭제할 수 없습니다";
일괄 관리는 좋을수도, 나쁠수도 있습니다.
적어도 같은 관심사끼리 묶어주는것이 더 좋아보이네요!

2021-03-24 23:59 UTC, Malloc72P commented on src/main/java/com/codessquad/qna/web/service/UserService.java
> +        User foundUser = null;
아하 그거였군요! 그렇게 해주면 더 깔끔하고 null을 없앨 수 있어서 좋겠네요!

2021-03-27 08:07 UTC, d-h-k commented
잘 배워 갑니다! 감사합니다