[노을] 미션3-4 PR 요청드립니다.
codesquad-members-2021/spring-boot-qna pull request #94
Opened 2021-03-20 08:38 UTC by sanhee

안녕하세요! 백엔드반 노을👦 입니다!

QnA 미션 과정이 끝나가고 있어서, 
속도를 내고자 미션3와 비슷한 미션4를 한 브랜치에서 작업하고 PR요청 드리게 되었습니다.

이번 미션을 통해 `구현한 기능`은 다음과 같습니다!

| 미션 3. 로그인 구현   | 미션 4. 로그인 구현            | 그 외                                                        |
| --------------------- | ------------------------------ | ------------------------------------------------------------ |
| ✅ 로그인 기능         | ✅ 객체-관계 매핑               | ✅ 로그인한 사용자만 글쓰기 가능한 기능                       |
| ✅ 개인정보 수정 기능  | ✅ 답변 생성/수정/삭제          | ✅ 아이디 중복/로그인 실패에 대한 예외 처리 (페이지 이동)     |
| ✅ 로그인 기능         | ✅ Controller, Service 분리     | ✅ `@ExceptionHandler` 와 `@ControllerAdvise` 를 통한 예외 처리 |
| ✅ 질문 생성/수정/삭제 | ✅ (선택) Soft Delete, 삭제조건 | ✅ 에러 페이지 생성 ( `templates/error/404~500..`)            |

💫<u>배포링크</u>: https://noel-boot-qna.herokuapp.com/

### 궁금한점

1️⃣ 컨트롤러와 서비스를 처음으로 분리해보았는데 올바르게 했는지 궁금합니다.

2️⃣ @ExceptionHandler 를 이용해 예외처리를 시도해보았는데, 이러한 핸들러를 통해 View를 리턴해주는 방식이 옳은 방식인지 궁금합니다.

3️⃣ 객체를 find를 할 당시에 삭제 boolean 검사를 하고, 유효한 객체만 리턴하도록 `Soft Delete`를 구현하였는데, 올바르게 했는지 궁금합니다.

4️⃣ 아래와 같이, 맵핑되는 주소는 동일한대  스프링 에노테이션을 이용해  함수 오버로딩과 같이 구현을 했는데 올바른 방식인지 궁금합니다!

```java
@GetMapping("/questions/{id}") 
private String modifyQuestionButton(Parameter){..}

@PutMapping("/questions/{id}") 
private String modifyQuestion(Parameter){..}

@DeleteMapping("/questions/{id}") 
private String deleteQuestion(Parameter){..}
```

부족한 코드지만 시간내어 리뷰해주셔서 감사합니다! 😁

2021-03-22 00:17 UTC, wheejuni requested changes
안녕하세요 노을, 전반적으로 과제 잘 구현해 주셨습니다. 수고하셨어요. 👏👏

익셉션 핸들러와 소프트 딜리트, 서비스의 책임 분리까지 잘 해주셨어요. 다만 서비스가 더 많은 역할을 한다면 컨트롤러의 코드 량은 더 줄일 수 있을 것 같아요. 

그리고 패스 매핑을 같게 한 상황에서 메소드를 통한 핸들러 분리는 실제로도 많이 하는 방법이니 걱정하지 않으셔도 됩니다. 👍

다른 부분에서 피드백을 좀 남겼는데요, 확인해 주시면 좋겠습니다!

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        ValidUtils.checkIllegalArgumentOf(title, contents);
이건 `QuestionService` 안에서 수행되면 더 좋을 것 같은데요?

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @DeleteMapping("/questions/{id}") // 질문 삭제: 접근경로가 다른 메서드와 동일해도, 맵핑이 다르면 함수의 오버로드 같이 요청에 따라 다르게 인식하는건가?
메소드 + 패스로 인식하기 때문에 분기 처리가 가능했던 것입니다.

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        Question findQuestion = questionService.findById(questionId);
이것도 `QuestionService` 안에서 한번에 해야할 것 같은데요?

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        userService.save(user, UPDATE_FALSE);
`UserService` 에 업데이트 여부에 따른 메소드가 하나씩 구현되어 있는 방향은 어떨까요?

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +
각 필드별로 선언하실 때 한줄씩 띄워 주세요.

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    // 배포서버가 미국에 있기 때문에 타임존을 사용하였습니다.
미국에 있는 서버를 한국에서만 쓴다면, 
분명히 그 배포 서버에 타임존 설정을 부여하는 법이 있을 겁니다. 
그런 방식으로 대응해야 합니다.

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/AnswerService.java
> +    }
단순히 `SELECT` 하고 `INSERT` 하는 것보다 더 많은 역할을 하도록 설계를 확장시켜 주세요. 
지금도 컨트롤러가 꽤 많은 일을 하고 있고, 서비스로 옮길 수 있는 여지들이 보입니다.

2021-03-22 00:17 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                    duplicateCheck.set(true); // ID 중복 발생
여기 안에서 그냥 `.save()` 하고 조기에 리턴하면 굳이 `duplicateCheck` 과 같이 복잡한 구조를 갖지 않아도 됐을 텐데요.

2021-03-22 04:50 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        ValidUtils.checkIllegalArgumentOf(title, contents);
https://www.javaguides.net/2020/07/three-tier-three-layer-architecture-in-spring-mvc-web-application.html
의 3-tier-architecture를 참고해서 controller와 service를 분리했는데요!
본문에서 컨트롤러 클래스에서 입력의 유효성을 검사와 모델 조작을 한다고 해서 위와 같이 설계를 하였습니다.

혹시, 유효성 검사도 서비스에서 하는건가요??

2021-03-22 04:51 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +    @DeleteMapping("/questions/{id}") // 질문 삭제: 접근경로가 다른 메서드와 동일해도, 맵핑이 다르면 함수의 오버로드 같이 요청에 따라 다르게 인식하는건가?
답변 감사합니다!! 향후 미션이 끝나면 자세히 공부해보도록 하겠습니다!

2021-03-22 04:52 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        Question findQuestion = questionService.findById(questionId);
https://github.com/codesquad-members-2021/spring-boot-qna/pull/94#discussion_r598423258
에서 질문드렸습니다!😀

2021-03-22 04:53 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/UserController.java
> +        userService.save(user, UPDATE_FALSE);
좋은 방법인것 같습니다!! 뒤늦게 soft delete를 적용하다보니, 기존 틀에 추가하기 위해 하드코딩이 된 것 같습니다!
고쳐보도록 하겠습니다!

2021-03-22 04:54 UTC, sanhee commented on src/main/java/com/codessquad/qna/domain/Question.java
> -    // 배포서버가 미국에 있기 때문에 타임존을 사용하였습니다.
넵!! `heroku config:add TZ="Asia/Seoul"` 를 통해 타임존을 맞춰주었습니다.
`LocalDateTime`으로  변경하겠습니다.

2021-03-22 04:57 UTC, sanhee commented on src/main/java/com/codessquad/qna/domain/Answer.java
> +
차마 가독성을 신경쓰지 못한 것 같습니다.
반영완료 했습니다!

2021-03-22 11:56 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        ValidUtils.checkIllegalArgumentOf(title, contents);
@sanhee 엄격하게 3계층 구조를 적용해 presentation layer에서 유효성 체크까지 수행하고자 하신다면,
그 유효성 체크가 컨트롤러에서 일어나진 않았으면 좋겠습니다. 컨트롤러가 의존하는 다른 컴포넌트를 작성하셔도 좋고, Spring MVC가 유효성 검사를 어떻게 다루는지도 알아보시기 바랍니다.

2021-03-22 16:15 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        ValidUtils.checkIllegalArgumentOf(title, contents);
학습 키워드 감사합니다!,  학습정리하고 추가 코멘트 달겠습니다!!

2021-03-23 05:04 UTC, sanhee commented on src/main/java/com/codessquad/qna/controller/QuestionController.java
> +        ValidUtils.checkIllegalArgumentOf(title, contents);
학습을 통해, 제가 구현한 데이터 유효성 검사 로직 방식은 애플리케이션 전체에 분산 돼있어, 추적이 어렵고 각 계층별로 구현된 검증 로직간에 불일치로 오류가 발생하기 쉽다는 문제점에 대해 알게 됐습니다.  따라서 도메인 모델 자체를 묶어서  `Bean Validation` 프레임워크를 통해 유효성 검사를 할 수 있음을 확인했습니다.  하지만 바로 적용하기에는 현재 구조에서 많은 변화가 필요할 것 같아, 

우선 컨트롤러의 모든 유효성 검사 역할을 서비스단으로 옮기고, 다음 미션에서 적용해보려고 합니다!!

2021-03-23 10:38 UTC, sanhee commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                    duplicateCheck.set(true); // ID 중복 발생
안녕하세요 브라이언!!
https://github.com/codesquad-members-2021/spring-boot-qna/pull/94/commits/24ba1e8aec1cf0cca7f1f66fe0fc102f80845896 와 같이 메소드를 분리하는 방법 밖에 생각하지 못했습니다.

혹시 조기에 리턴하여, 중복체크를 안하는 방법이 어떤건지 여쭤봐도 될까요??
아직 실력이 부족해서 잘모르겠습니다!!..😂

2021-03-23 11:02 UTC, sanhee commented
안녕하세요, 브라이언 말씀하신 리뷰 사항 반영하여 수정하였습니다.
컨트롤러의 유효성검사의 경우, Bean Validation을 사용하고 싶었지만 구조의 많은 변화가 필요한 것 같아,
엄격한 구분을 짓지 않고 컨트롤러를 단순히 모델의 리턴 역할로 지정하고, 대부분의 유효성 검사 로직을 서비스단으로 이전하였습니다.

마지막으로, https://github.com/codesquad-members-2021/spring-boot-qna/pull/94#discussion_r598362204 이부분의 리뷰는 어떤식으로 반영하면 좋을지 잘 모르겠어서 다시 질문드렸습니다!

2021-03-24 00:23 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                    duplicateCheck.set(true); // ID 중복 발생
이런식으로 풀면 안되나요? 

```java
if(userRepository.findByUserId(user.getUserId()).isPresent()) {
    return;
}
...

2021-03-24 02:59 UTC, sanhee commented on src/main/java/com/codessquad/qna/service/UserService.java
> +                    duplicateCheck.set(true); // ID 중복 발생
중복체크를 해야한다!에 집중한 나머지 생각이 편협해져 쉬운 길을 못본것 같습니다..
친절한 설명 너무 감사합니다!! 
아래와 같이 구현 및 푸쉬완료했습니다..!!!

```java
    public void save(User user) {
        user = Optional.ofNullable(user).orElseThrow(IllegalArgumentException::new);
        if(userRepository.findByUserId(user.getUserId()).isPresent()){
            throw new DuplicateException();
        }
        userRepository.save(user);
    }
```

2021-03-24 13:52 UTC, wheejuni approved these changes
어찌보면 난해할 수 있는 피드백이었는데, 잘 받아주시고 열심히 수정해 줘서 감사합니다. 👍 
이제 머지해도 되겠네요. 수고하셨어요. 💯

2021-03-24 13:52 UTC, merged